### ISSUE TITLE
SDImageCache Restart App problem

### ISSUE THREAD

**Issue by Draveness** [rs/SDWebImage#1001]
I use sd_setImageWithURL method

    [_userCell.userImageView sd_setImageWithURL:profile.avatar
                               placeholderImage:DEFAULT_USER_IMAGE
                                        options:SDWebImageHighPriority];

And I calculate the image cache with 

    [[SDWebImageManager sharedManager].imageCache calculateSizeWithCompletionBlock:^(NSUInteger fileCount, NSUInteger totalSize) {
        NSLog(@"%d", fileCount);
    }];

Why do the totalSize smaller when I restart my app, and the image downloaded before has to download again. How to deal with this.

**Comment by mythodeia** [comment]
@Draveness did you check if the cache is being emptied when the app is restarted?
By default when the app goes into background the ```backgroundCleanDisk``` is called.
When the app receives a memory warning then the ```clearMemory``` is called and when the app is terminated the ```cleanDisk``` is called.
The ```clearMemory``` removes the in memory objects.
The ```clearDisk``` removes all objects from cache locatin.
The ```cleanDisk``` removes all objects from disk based on the modification date and the ```maxCacheAge``` set
Check the code of any of these methods is the one responsible for making the cache smaller.

**Comment by Draveness** [comment]
I have already forgot what I did then, I saved it in the data base instead of using the SDIMageCahe, - -.
