### ISSUE TITLE
Problem with table view and swift

### ISSUE THREAD

**Issue by bitomule** [rs/SDWebImage#1002]
I'm trying to use SDWebImage with a swift project but images only appear after scroll. I've tried using the block callback but self an cell throws an access error. Anyone has this working?

My code is:

    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier("MyCustomCell", forIndexPath: indexPath) as MyCustomCell
        let data = fetchedResultController.objectAtIndexPath(indexPath) as MyData
        cell.Name.text = data.name
        if let image = data.image{
            cell.Image.sd_setImageWithURL(NSURL(string: image.url), placeholderImage: UIImage(named: "DownloadingPlaceholder"))
        }
        return cell
    }

**Comment by bitomule** [comment]
The problem doesn't appear on device, only simulator.

**Comment by AlexChesters** [comment]
I'm seeing this on physical devices as well as the simulator. Has anyone else had this issue?

**Comment by AlexChesters** [comment]
I fixed this by calling `[cell setNeedsLayout]` in the completion block.

**Comment by bpoplauschi** [comment]
Great that you found a fix, @AlexChesters

**Comment by AlexChesters** [comment]
No worries, thanks for the awesome library @bpoplauschi :+1:
