### ISSUE TITLE
302 bug

### ISSUE THREAD

**Issue by fc01** [rs/SDWebImage#1003]
[imgView sd_setImageWithURL:@"http://sina.lt/EAc"];

//http://t.cn/Rh4hRdY

**Comment by mythodeia** [comment]
@fc01 i tried your url and i got this response
```
<NSHTTPURLResponse: 0x7fabe2c2a860> { URL: http://img1.imgtn.bdimg.com/it/u=2095998095,2004959060&fm=23&gp=0.jpg } { status code: 403, headers {
    "Content-Length" = 345;
    "Content-Type" = "text/html";
    Date = "Tue, 06 Jan 2015 09:18:58 GMT";
    Server = lighttpd;
} }
```
the status code is 403 thats why it does not load the redirected image and it cancels the request.
i think you should check your server's response
