### ISSUE TITLE
Compiled version 3.7.0

### ISSUE THREAD

**Issue by jeromejesse** [rs/SDWebImage#1006]
Hello,

I want to download the 3.7.0 version Framework compiled version. But It's not available on the download page.

**Comment by rromanchuk** [comment]
this should be closed, cocoapods is industry standard.  @jeromejesse if you need a static build, you can do it yourself http://www.raywenderlich.com/41377/creating-a-static-library-in-ios-tutorial

**Comment by mythodeia** [comment]
closing this. Please reopen if you need more help
