### ISSUE TITLE
progressBlock doesn't show continuous updates

### ISSUE THREAD

**Issue by harishkashyap** [rs/SDWebImage#1008]
I haven't had any success in using the progressBlock of :    

 [self.imageView sd_setImageWithURL:url placeholderImage:placeholderImage options:SDWebImageProgressiveDownload progress:^(NSInteger receivedSize, NSInteger expectedSize) {
// use the receivedSize/expectedSize here in a progress animation.
} completed: ^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
}

The updates are received but not continously to show an animation to the user. Currently it is mostly stalled and the download completes and the animation hardly is visible. Ideally will be good to get the updates at good intervals to provide a better UX.

**Comment by mythodeia** [comment]
@harishkashyap 
are you sure your server replies with the correct amount of info for the progress to show?

**Comment by mythodeia** [comment]
closing this. please reopen if you think its a problem with the library.
