### ISSUE TITLE
How can I cache both on disk or in memory when download a image from web?

### ISSUE THREAD

**Issue by seanLee** [rs/SDWebImage#1010]
Hello,

````
[cell.imageView sd_setImageWithPreviousCachedImageWithURL:(NSURL *) andPlaceholderImage:(UIImage *) options:(SDWebImageOptions) progress:^(NSInteger receivedSize, NSInteger expectedSize) {
            
        } completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
            
        }]
````

I use this methed to load the imageview of a cell.If i want to cache both on disk or in memory,what the parameter is for the options should i select?And if the method can't be in this way,what other method should I use?

Thx.

**Comment by mythodeia** [comment]
@seanLee the following method automatically caches in memory and disk unless stated otherwise using specific SDWebImageOptions parameter.
```
- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options;
```

**Comment by seanLee** [comment]
yeah,i know about the methed.What confuses me is which (SDWebImageOptions)options should I use.
It has eight values,which one is the default value that you meant automatically caches in memory  and disk.Or should I use nil to set the default value?

**Comment by mythodeia** [comment]
@seanLee you can check the documentation for each option and add the one that fits your needs.
There is only this option ```SDWebImageCacheMemoryOnly``` that forces the memory cache only and disables the disk cache
You can use only the ```SDWebImageProgressiveDownload``` option to slowly show the image as it downloads.

**Comment by seanLee** [comment]
@mythodeia  thx for soving my problem.

**Comment by mythodeia** [comment]
no problem. Good luck with your app
