### ISSUE TITLE
How to not cancel previous URL?

### ISSUE THREAD

**Issue by TheoJL** [rs/SDWebImage#1019]
```objective-c
    NSURL *url = [NSURL URLWithString:@"someURL.jpg"];

   [self.image1 sd_setImageWithURL:url placeholderImage:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        NSLog(@"completed image 1");
    }];
    [self.image2 sd_setImageWithURL:url placeholderImage:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        NSLog(@"completed image 2");
    }];
    [self.image3 sd_setImageWithURL:url placeholderImage:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        NSLog(@"completed image 3");
    }];

```
```
Log: completed image 3
```
The image is only set to the last one if the URL is the same. Is there any method I can call that certainly gives me a completion callback?
My use case is that when the user changes a profile image a notification is sent to the controllers that need to update its profile image, but right now only one imageView gets updated.

**Comment by mythodeia** [comment]
@TheoJL 
i tried your scenario in the demo project. I added 2 more imageviews in the detailviewcontroller and all worked just fine. i got the image to display in all 3 of them. Are you sure your code is not doing anything else unexpected? All requests are fulfilled just fine

**Comment by TheoJL** [comment]
sd_setImageWithURL works excellent! The problem was that I used the same imageView for all three calls. I had the problem in another project with different images, but it wasn't updated or something. 
Thanks @mythodeia and sorry for the fuss. Won't happen again. ;)
