### ISSUE TITLE
Unable to build and run the sample/demo project

### ISSUE THREAD

**Issue by aanchalkalani** [rs/SDWebImage#1020]

**Comment by mythodeia** [comment]
@aanchalkalani 
please read this:
https://github.com/rs/SDWebImage#installation-with-cocoapods
and this:
https://github.com/rs/SDWebImage#installation-by-cloning-the-repository

basically you download the library and and run pod install command in the Tests folder.
Then you open the project using the ```SDWebImage.xcworkspace```
