### ISSUE TITLE
Is it possible to download a compiled framework that does not have the arm64 compiling issue?

### ISSUE THREAD

**Issue by rosamerinoclaros** [rs/SDWebImage#1021]

**Comment by rosamerinoclaros** [comment]
I downloaded the DSWebImage version 3.0 and I am getting the linker error. Is it only fixed if using Cocoa Pods? My project does not use it and I would like to add just the compiled framework...

**Comment by mythodeia** [comment]
@rosamerinoclaros 
i think you can build the framework yourself. You can download the demo project and alter the architectures you want to support. Then choose the scheme you want and build the project.
Go to Derived Data folder and get your framework from there.

**Comment by rromanchuk** [comment]
`git clone git@github.com:rs/SDWebImage.git` and add the source yourself, or create a static lib http://www.raywenderlich.com/41377/creating-a-static-library-in-ios-tutorial    

This is beyond the scope of the maintainers.  @rosamerinoclaros just curious, why don't you use `cocoapods`?

**Comment by mythodeia** [comment]
closing this. Please reopen if you need more help. thanks
