### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by heaofei** [rs/SDWebImage#1022]
this framework on ios can not load a picture url that the url on the web broswer is  just for downlod .like this url http://5.youba.com/pic/2014/12/22/181548576001_watermark.jpg .how can i solve this problem.

**Comment by mythodeia** [comment]
@heaofei 
the problem i think is because you set content type of the response to be ```application/octet-stream```
so the file can be downloaded and not previewed.
check this
https://github.com/rs/SDWebImage/issues/285

SDWebImage uses these headers:
```image/webp,image/*;q=0.8```
if you remove them then you can download the image in your example
