### ISSUE TITLE
Dynamic URLs are not refreshing when I use SDWebImageRefreshCached even after #744

### ISSUE THREAD

**Issue by GoodSquishy** [rs/SDWebImage#1023]
I have seen the #744 merge and I can confirm that I am using version 3.7.1 and that the fix implemented in #744 is in my codebase, my implementation is below, I have placed a breakpoint in the completion block and when I check the UIImage in the completion block it is still the "old" cached image.

```Objective-C
[self.thumbnailImage sd_setImageWithURL:imageUrl
                           placeholderImage:[UIImage imageNamed:[Config universalImage:@"defaultTile"]]
                                    options:SDWebImageRefreshCached | SDWebImageRetryFailed
                                  completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {

    }];
```
This is reproducible in the a brand spanking new project with nothing but a imageView and the SDWebImage pod.

I'm really not sure what the problem is.

P.s. This is the first issue I have raised in GitHub so please excuse me if I'm not following any issue creation guidelines, also if this isn't the appropriate place for this type of comment let me know.

Thanks.

**Comment by bpoplauschi** [comment]
@GoodSquishy did you find a resolution to the issue? I see you've closed the issue.

**Comment by GoodSquishy** [comment]
@bpoplauschi yes I found that my backend was not setting max_age at all, we assumed that if max_age was not set SDWebImage would act as if max_age is zero, but it is the opposite if max_age SDWebImage falls back to the cached image.

**Comment by bpoplauschi** [comment]
Ok :)
