### ISSUE TITLE
Cell being populated with wrong images

### ISSUE THREAD

**Issue by marcustoy** [rs/SDWebImage#1024]
Hi,

I'm currently using this code to set-up my images:

[cell.coverImage sd_setImageWithURL:[self.dataInJSONModel.Content[indexPath.row] CoverImage] placeholderImage:[UIImage imageNamed:@"imageplaceholder_general"]];

And my cells are often wrongly populated when I scroll. Guessed it is due to the cell reuse issue, where the async-downloaded images are populated to the cell that may have been re-used/disappeared. I have searched online and tried those recommendations but to no avail. Any standard method to solving this problem?

**Comment by mythodeia** [comment]
@marcustoy in your prepareforreuse method nullify the image in your imageview

**Comment by marcustoy** [comment]
@mythodela Thanks a lot! It solves the problem!!! You save my several hours of debugging and searching online. Thanks again!!

**Comment by siddhesh12** [comment]
Hi Mythodeia, 
I used above method but that problem, I followed almost all the tricks mentions over internet, is there any other solution for this ?

**Comment by mythodeia** [comment]
@siddhesh12 there must be a cell reuse issue somewhere hidden in your code. check the demo project to see how it works. if still you have issues please share a demo project so everyone can take a look and help

**Comment by siddhesh12** [comment]
I got the solution for it. at the beginning I am calling sd_cancelImageLoadForState method. so when image gets download asynchronously  it will never assign it to different cell which was previously refused.

**Comment by ilyanengen** [comment]
Before setting new image to imageView add:

cell.imageView.sd_currentDownloadTask?.cancel()
