### ISSUE TITLE
SDWebImage - how to handle server nonce during digest authentication

### ISSUE THREAD

**Issue by saravr** [rs/SDWebImage#1025]
Posted this question in stackoverflow but did not get any response. Wonder if anyone has any information on this...

http://stackoverflow.com/questions/28139953/sdwebimage-how-to-handle-server-nonce-during-digest-authentication

Thanks!

**Comment by bpoplauschi** [comment]
At this point we don't have support for this. Feel free to create a pull request.

**Comment by bpoplauschi** [comment]
Any updates here?
