### ISSUE TITLE
Memory Leak in decodedImageWithImage

### ISSUE THREAD

**Issue by bluefish625** [rs/SDWebImage#1027]
Instruments Allocations show Leak at "CGBitmapContextCreate" "CGContextDrawImage" "CGBitmapContextCreateImage(context);"

![screen shot 2015-01-30 at 4 06 22 pm](https://cloud.githubusercontent.com/assets/317254/5972780/219e374e-a89a-11e4-815c-1391da334973.png)

**Comment by rromanchuk** [comment]
duplicate https://github.com/rs/SDWebImage/issues/538   Close please.

**Comment by mythodeia** [comment]
closing this

**Comment by weng1250** [comment]
duplicate #538 Close please.
