### ISSUE TITLE
Should we add something like 'drawingBlock' ? For draw a rounded corner and so on...

### ISSUE THREAD

**Issue by wangweiarr** [rs/SDWebImage#1028]
I take a lot of time to think how to design a category to add rounded corner to images efficient whit SDWebImage, but I just not find a simple way to do. Maybe I still too noob?
A little common requirement-'image with rounded corner', needs too much work to do.

**Comment by mythodeia** [comment]
@wangweiarr this is outside the scope of this library.
You can add rounded corners yourself in the completion block or simply use the 
```
- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;
```
to do whatever you want with the image and it will cache the changed file instead of the original

**Comment by wangweiarr** [comment]
sorry about this outside topic, but I think either the 'completion block' or the delegate about 'transformDownloadedImage' can't work well.
The completion block operation after target.image = image, you can see the changing	process of adding rounded corner.
The delegate can't controlling with given uiview like completion block..
I mean a function like '- (void)sd_setImageWithURL:(NSURL *)url completed:(SDWebImageCompletionBlock)completedBlock drawing:(..) drawingBlock',the drawingBlock work before set the image to view and after download image.

**Comment by mythodeia** [comment]
@wangweiarr 
if i understand correctly you want the image to have rounded corners,right?
i used the demo project and set the delegate of the SDWebImageManager to self in my detailsviewcontroller.
then i added the method i described above in the view.
I did not add any extra code to the ```sd_setImageWithURL``` method. 
I only added a UIImage category to take the image and add corners to it like this:
```
- (UIImage *) imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL{
    return [image add_imageWithCornerRadius:50];
}
```
on my completion block of the ```sd_setImageWithURL``` method i got my rounded image.
This does what you described. It does the transformations before caching the image and before returning it to the completion block.

**Comment by wangweiarr** [comment]
I know your mean, but maybe I can't make myself clear. 
In UIImageView+WebCache:
- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageCompletionBlock)completedBlock {
……
    if (url) {
        __weak UIImageView *wself = self;
        id <SDWebImageOperation> operation = [SDWebImageManager.sharedManager downloadImageWithURL:url options:options progress:progressBlock completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
            if (!wself) return;
            dispatch_main_sync_safe(^{
                if (!wself) return;
                if (image) {
                    wself.image = image;
                    [wself setNeedsLayout];
                } else {
                    if ((options & SDWebImageDelayPlaceholder)) {
                        wself.image = placeholder;
                        [wself setNeedsLayout];
                    }
                }
                if (completedBlock && finished) {
                    completedBlock(image, error, cacheType, url);
                }
            });
        }];
        [self sd_setImageLoadOperation:operation forKey:@"UIImageViewImageLoad"];
    } else {
        ……
    }
}


see? The 'completedBlock(image, error, cacheType, url); ' after 'wself.image = image;', and your 'add_imageWithCornerRadius' maybe take some time, so I really see the transformation process of addCorner.
On the other hand, although '- (UIImage *) imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL' can work well, but I need deal with many different picture(need addCorner or not), I can't determines witch picture should add corner with the param like 'image' or 'imageURL',I just want to pass a operation block while call sd_setImageWithURL: right away.

Still thank you for patience answer!

**Comment by mythodeia** [comment]
As i see it its a specific case you want to address. If you can do it then please create a pull request and maybe some users will find it handy!
Thanks
