### ISSUE TITLE
sd_setImageWithURL race condition?

### ISSUE THREAD

**Issue by TheoJL** [rs/SDWebImage#1032]
There seems to be an issue where images not being set if the same URL is used and multiple request to that URL is added at the same time. There is no problem if the image is cached. 
Unfortunately this happens all the time for us and all I can say is that the issue have been introduced with a later version of SDWebImage because we haven't seen this before. I don't know what version though.

I reproduced the issue in a simple project: https://github.com/TheoJL/SampleSDWeb
In this sample only one imageView is set, but the expected behaviour should be both. 
Next time we run the project it behaves as it should as the image is cached. 

Note that you may need to change the delay for the ```` performSelector:withObject:afterDelay ```` depending on the internet connection.

**Comment by Pash237** [comment]
I have checked this problem with the latest changes (commit 9cc8269dcdcf7dc5fd42abb5adbd911b835bb21b), and things got even worse – now no of the images will load :(

Simplest testcase:

	UIImageView *imageView1 = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 100, 100)];
	UIImageView *imageView2 = [[UIImageView alloc] initWithFrame:CGRectMake(100, 0, 100, 100)];
	[self.view addSubview:imageView1];
	[self.view addSubview:imageView2];

	NSString *urlString = @"http://upload.wikimedia.org/wikipedia/commons/6/6b/Big_Sur_June_2008.jpg";
	urlString = [urlString stringByAppendingFormat:@"?%d", arc4random_uniform(10000)];

	[imageView1 sd_setImageWithURL:[NSURL URLWithString:urlString]];
	[imageView2 sd_setImageWithURL:[NSURL URLWithString:urlString]];
	dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
	    [imageView1 sd_setImageWithURL:[NSURL URLWithString:urlString]];
	});


Before, the first ImageView will receive the callback and display an image, but the second ImageView will be left empty. Now both ImageViews are empty.

**Comment by timkoma** [comment]
It has nothing to do with commit 9cc8269:
If you will set the same URL to 2 different UIImageViews, only one download operation is started(for the first one). If the first one gets cancelled (e.g. because of setting the new URL) the download operation is cancelled(even though there is a second request for the same URL!). 
This is a design bug in the SDWebImageDownloaded.

**Comment by bpoplauschi** [comment]
This should be resolved by #883 on the 4.x branch.
