### ISSUE TITLE
sd_setImageWithURL's completedBlock not called if operation was cancelled

### ISSUE THREAD

**Issue by timkoma** [rs/SDWebImage#1034]
I think that it should be called with error code 'cancelled'.
For example: How I should write safe code with activity indicator during image loading operation, if I'm not sure that completed callback will be always called ?

            [_activityIndicator setHidden:NO];
            [_activityIndicator startAnimating];
            // load image
            __weak UIActivityIndicatorView* weakActivityIndicator = _activityIndicator;
            [_imageView sd_setImageWithURL:newUrl placeholderImage:nil options:SDWebImageProgressiveDownload|SDWebImageHighPriority
                progress:nil
                completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                    [weakActivityIndicator stopAnimating];
                    [weakActivityIndicator setHidden:YES];
                }];

**Comment by mythodeia** [comment]
@timkoma is there a reason why the completion callback wont be called?

**Comment by timkoma** [comment]
Because SDWebImageDownloader's downloadImageWithURL doesn't call it in it's cancelled block?

                                             cancelled:^{
                                                            SDWebImageDownloader *sself = wself;
                                                            if (!sself) return;
                                                            [sself removeCallbacksForURL:url];
                                                        }

**Comment by mythodeia** [comment]
as i can see it if you cancel the SDWebImageDownloader then the cancelBlock posts a notification:
```SDWebImageDownloadStopNotification```
The SDWebImageDownloader listens for that notification and calls the ```stopActivity````
am i missing something here?Please let me know if i am getting this wrong

**Comment by timkoma** [comment]
No, you got it wrong.

If you start the download operation from UIImageView+WebCache and download operation is cancelled, there is no guaranty that UIImageView+WebCache will be notified about cancel, because 
     cancelled:^{
            SDWebImageDownloader *sself = wself;
            if (!sself) return;
            [sself removeCallbacksForURL:url];
     }
will not do it!

**Comment by timkoma** [comment]
Ah, just noticed that this can be a root cause to #1032

**Comment by mythodeia** [comment]
this is where the completion block for cancelled requests was removed due to race conditions https://github.com/rs/SDWebImage/pull/699

**Comment by timkoma** [comment]
I cannot agree with #699. Correct fix for Race condition is to synchronize the call either with @synchronize or using GCD (e.g. serial dispatch queue). 
But not skipping(not calling) some code causing race condition!
As you can see you have some other guys complaining about missing calls here #847.

**Comment by bpoplauschi** [comment]
I think this should be fixed due to #883. Please retest after we release 4.0 (right now the fix is on the 4.x branch).
