### ISSUE TITLE
animations stop working

### ISSUE THREAD

**Issue by MobileMon** [rs/SDWebImage#1035]
something happens with this control that causes animations to stop working throughout the entire app on ios 7+

this article talks about why:
http://stackoverflow.com/questions/19411675/ios-animations-stop-working-in-my-app-in-ios7

basically its updating the UI on a background thread that should be done on the main thread

havent quite figured out what yet...

**Comment by mythodeia** [comment]
@MobileMon are you sure this control is causing the animations to stop? do you have any sample project that we can check for this? If you find any more info please let us know

**Comment by pasevin** [comment]
I have noticed this as well, it is very hard to catch this bug thou...

**Comment by MobileMon** [comment]
@mythodeia it is definitely SDWebImage

Catch there error using the method describe here:
http://stackoverflow.com/questions/19411675/ios-animations-stop-working-in-my-app-in-ios7

Assertion thats thrown is:
malloc: *** error for object 0x7fcd79b8fb80: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by mythodeia** [comment]
@MobileMon whats the object that the malloc is referring to? did you try the swizzle method in that thread? did you see the source code responsible for that error?

**Comment by MobileMon** [comment]
@mythodeia I solved the issue

In SDImageCache.m

change this:

+ (SDImageCache *)sharedImageCache {
    static dispatch_once_t once;
    static id instance;
    dispatch_once(&once, ^{
        instance = [self new];
    });     
    return instance;
}


to:

+ (SDImageCache *)sharedImageCache {
    static dispatch_once_t once;
    static id instance;
    dispatch_async(dispatch_get_main_queue(), ^(void){
        instance = [self new];
    });
    return instance;
}


it only happens the first time the cache is created so manually delete the app and run it the first time to get this to happen. CHEERS!

**Comment by MobileMon** [comment]
its the progress and completion blocks that dont get called on the main thread. this fixes:

     progress:^(NSInteger receivedSize, NSInteger expectedSize) {
                                             dispatch_async(dispatch_get_main_queue(), ^{
                                                 if (!activityIndicator) {
                                                   
                                                     [activityIndicator startAnimating];
                                                 }
                                             });
                                         }
                                        completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                                            dispatch_async(dispatch_get_main_queue(), ^{
                                                [activityIndicator removeFromSuperview];
                                                activityIndicator = nil;
                                               
                                            });
                                        }];

**Comment by Japspre** [comment]
@MobileMon It seems that adding the dispatch to the main queue does fix the problem for me.

**Comment by bpoplauschi** [comment]
@MobileMon @Japspre indeed there is an issue with progress blocks not being called on the main queue. We will fix this in the next release. For the completion blocks, I think those are already on the main queue.

**Comment by Japspre** [comment]
@bpoplauschi Good to know. 
After adding the dispatch the problem didn't occur anymore

**Comment by bpoplauschi** [comment]
Not yet fixed, but will very soon

**Comment by bpoplauschi** [comment]
Fixed by #1218
