### ISSUE TITLE
-[__NSCFString getBytes:length:]: unrecognized selector sent to instance 0x16eed1b0

### ISSUE THREAD

**Issue by huangguiyang** [rs/SDWebImage#1037]
got 2 crash:

-[__NSCFString getBytes:length:]: unrecognized selector sent to instance 0x16eed1b0

-[UINibStorage getBytes:length:]: unrecognized selector sent to instance 0x17df5170

why an NSString/UINibStorage is being passed instead of NSData?

I'm sorry I don't know how to reproduce.

**Comment by scottbyrns** [comment]
I've noticed a substantial increase in unrecognized selector exceptions with an update to the latest sdk. It may be that this project has relied on apis that are changing underneath it.

**Comment by mythodeia** [comment]
@huangguiyang are you still having these crashes

**Comment by mythodeia** [comment]
closing this. please reopen if you have troubles again

**Comment by takasek** [comment]
I got similar crash with v 3.7.2.

**NSInvalidArgumentException** in **NSData(ImageContentType)**
-[__NSCFString getBytes:length:]: unrecognized selector sent to instance 0x156c9df0

## Stacktrace

    Pods/SDWebImage/SDWebImage/NSData+ImageContentType.m:13 - +[NSData(ImageContentType) sd_contentTypeForImageData:]
    Pods/SDWebImage/SDWebImage/UIImage+MultiFormat.m:22 - +[UIImage(MultiFormat) sd_imageWithData:]
    Pods/SDWebImage/SDWebImage/SDImageCache.m:270 - -[SDImageCache diskImageForKey:]
    Pods/SDWebImage/SDWebImage/SDImageCache.m:310 - _42-[SDImageCache queryDiskCacheForKey:done:]_block_invoke
