### ISSUE TITLE
Trouble using SD on Swift

### ISSUE THREAD

**Issue by evertonfraga** [rs/SDWebImage#1039]
Hi guys, I was able to successfully import SDWebImage on my Swift project, and even use some methods, but some of them didn't work. A few examples:

This works:
`my_image.setImageWithURL(my_url, placeholderImage: nil, options: SDWebImageRefreshCached)`

**This doesn't work**
`my_image.setImageWithURL(my_url, placeholderImage: nil, options: SDWebImageRefreshCached, completed: ...block...)`
> Extra argument placeholderImage in call

Any thoughts?

**Comment by ashfurrow** [comment]
I seem to be experiencing this problem, too. The completion block is never actually invoked, either.

**Comment by pasevin** [comment]
you should use `sd_setImageWithURL` vs `setImageWithURL`

**Comment by evertonfraga** [comment]
That worked! I was using an old version of the lib. I had it updated and now it's working fine.
Thanks man
