### ISSUE TITLE
Cann't load image from Dropbox and Google Drive

### ISSUE THREAD

**Issue by RajChanchal** [rs/SDWebImage#1042]
Since google drive and dropbox offer their own way to download the images, please implement the way in your code so that everyone can use SDWebImage for above mentioned services too..

**Comment by mythodeia** [comment]
as i explained [here as well](https://github.com/mwaterfall/MWPhotoBrowser/issues/366) this is not possible if the response headers of the url is not an image.
the url's you provided are not valid for image downloading. the link from google drive does not even have permissions to access.
