### ISSUE TITLE
Travis CI build is failing: The platform of the target `ios` (iOS 5.0) is not compatible with `Expecta (0.3.2)` which has a minimum requirement of iOS 5.1.1 - OS X 10.7

### ISSUE THREAD

**Issue by timkoma** [rs/SDWebImage#1047]
$ pod update
Update all pods
Analyzing dependencies
CocoaPods 0.36.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.
For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.
Fetching podspec for `SDWebImage` from `../`
[!] The platform of the target `ios` (iOS 5.0) is not compatible with `Expecta (0.3.2)` which has a minimum requirement of iOS 5.1.1 - OS X 10.7

**Comment by bpoplauschi** [comment]
Travis CI builds were fixed
