### ISSUE TITLE
pod update

### ISSUE THREAD

**Issue by syrakozz** [rs/SDWebImage#1048]
i see a lot of change, 
but pod didnt get the latest update,
its like the last update of pod is 7 month ago, 
that old

**Comment by plivesey** [comment]
Same problem here. Looks like it will be solved with Issue #1061.

**Comment by rromanchuk** [comment]
So use the latest then.. 

`pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git', :commit => '962bcb03231d3baa8a0463743d148f494cbed5aa' #3.7.2`

**Comment by bpoplauschi** [comment]
I've just released a 3.7.2 version.
