### ISSUE TITLE
fail to get pictures when getting thumb picture first.

### ISSUE THREAD

**Issue by oday0311** [rs/SDWebImage#1050]
int defaultWidth = 640;
        if (self.showThumbFirst) {
            //load small pic first.
            defaultWidth = 640 / 4;
        }
        NSString * defineUrl = [[HGUtils sharedInstance] cloudinaryLink:imageLink width:defaultWidth height:0];
        
        NSURL * imageURL = [NSURL URLWithString:defineUrl];
        [cell.webImageView sd_setImageWithURL:imageURL placeholderImage:self.placeholderImage completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL)
        {
           
            else{
                if (self.showThumbFirst) {
                    //load big pic
                    NSString * defineUrl_big = [[HGUtils sharedInstance] cloudinaryLink:imageLink width:640 height:0];
                    
                    NSURL * imageURL_big = [NSURL URLWithString:defineUrl_big];
                    [cell.webImageView sd_setImageWithURL:imageURL_big placeholderImage:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                     
                        if (error) {
                            NSLog(@"get big image fail error: %@", error);
                        }
                    }];
                }
            }
        }];
    }
================================

hi, I am using SDwebimage to download pics, first download the thumb of the picture (size 160, ) , then in the complete block , will download the big size of the same pic with a different url, 

most of the cases, this functions work ok , but , there are 10% of the cases, the big picture fail to download,which make a smaller display all the time, and if this happen , this is always repeated, 
 I have traced inside , it seems that, if the first small url is found in the cache, the download operation is cancled, 

but it should not effected a different url, 
so may be this bug, should be fixed. in later version ...

please try, it is quite easy to repeat this bug.

**Comment by mythodeia** [comment]
there might be issues with the code you have pasted. In the completion block of the ```sd_setImageWithURL...``` you have an ```else``` statement which does not belong there...or you have forgotten some code on top of that.
anyway...can you replicate the bug using the demo project?

**Comment by oday0311** [comment]
nothing todo with the code," else", i try a demo, but much harder to repeat the bug, 
may be it is the network's problem, please close this, will give your more information if i can  repeat any cases.
Thx
