### ISSUE TITLE
Wrong image cached for some users

### ISSUE THREAD

**Issue by cnordvik** [rs/SDWebImage#1052]
We are using the Xamarin.iOS bindings of this project (https://components.xamarin.com/view/sdwebimage) and it has been working great but in a few rare cases the users end up having the wrong image cached for the URL. Even after closing the app and starting it they have the wrong image cached for the URL. I cannot reproduce it myself. If the user deletes the cache (I added a button that enables this) then the correct image appears. 

Any idea what can cause this? 

My code looks like this: 

    UITableViewCell cell = tableView.DequeueReusableCell (id);
			if (cell == null) {
                            ....
                         }
    UIImageView logoHome = (UIImageView)cell.ContentView.ViewWithTag (LOGO_HOME);
    var url = NSUrl.FromString(urlHome);
				if(url != null)
				{
					logoHome.SetImage(
						url, UIImage.FromBundle("empty_logo"), (image, error, cacheType, finished) => {
							if (image != null) {
								if(cacheType == SDImageCacheType.None)
								{
									logoHome.Alpha = 0.0f;
									UIView.Animate(0.5f, () => {
										logoHome.Alpha = 1.0f;
									});
								}
							}
						}
					);
				}

**Comment by heistings** [comment]
Sorry, I don't know swift very well. But I guess you have used reusable cell. So the `logoHome ` may doing more than one image downloading job.

**Comment by mythodeia** [comment]
sounds indeed like a case of reusable cell issues. make sure you are applying the image to the correct imageview in the completion block because it might get reused while scrolling

**Comment by cnordvik** [comment]
I can understand that might happen, but when the app is restarted it seems to have the wrong image stored in it's internal cache for the URL. So the user will always see the wrong image for the URL until they delete the cache. Doesn't that indicate that the problem lies somewhere else? I can scroll fast, slow and do whatever and it works great for me. It's just a small part of our users that have this issue (we have about 1 million active ones).

**Comment by heistings** [comment]
Do you mean the cell always show the wrong image when you scoll down and up?

**Comment by heistings** [comment]
Can you figure out the URL? And then you can set it to a image view without table cell in some other place.

**Comment by cnordvik** [comment]
Will see what I can do. And yes, once the wrong image is cached for that URL it stays like that. Here is the app but you probably won't be able to spot the error there since it happens for 1-2% of our users: 
https://itunes.apple.com/no/app/soccer-scores-pro-fotmob/id488575683?mt=8

**Comment by heistings** [comment]
Can this bug be reproduced on your test device? And I think the bug has chance to occur on the server as well.

**Comment by cnordvik** [comment]
No it cannot, and the server is static image files on Amazon S3 served via Cloudfront so pretty sure it's not there. I didn't have any issues with my own image downloading code but decided to switch to SDWebImage since it seemed like a good idea at the time :-) But I will try to investigate more what can cause this.

**Comment by Damol** [comment]
@cnordvik Did you find anything while investigating this? :)

I'm pretty much in the same situation as you were, a small (but growing) portion of our users started reporting this, so I just started investigating, first thing was to see if there's any open issue here, and this one has symptoms just like my case.

**Comment by cnordvik** [comment]
I think I had another image download library interfere with it. I removed the other library and the test users says its fine now. Will go live with it next week so hopefully it is fixed.

**Comment by Damol** [comment]
I see, that's a good clue I can start with when investigating more. Thanks for your answer! :)

**Comment by flashlib** [comment]
@cnordvik Why remove other library can fix this issue? Did these libraries integrate SDWebImage?

**Comment by cnordvik** [comment]
We actually still have this issue for 1% of our users. We hid an "easter egg" in the app so if you click a button 5 times it will append a random GUID to all image URLs. So each time we get a user complaining we make him hit the button 5 times to get proper images. It's a nightmarish hack but as nobody else is experiencing this and it's impossible to reproduce then it was the best we could come up with :-/

**Comment by flashlib** [comment]
@cnordvik Thanks for your quick reply! I will try some nightmarish hack solution:)
