### ISSUE TITLE
Animate UIImage

### ISSUE THREAD

**Issue by pronebird** [rs/SDWebImage#1053]
Is there any way to make a smooth cross-fade before setting image? I use SDWebImage category on UIImageView. I checked the source code and I don't seem to find a way to set image with transition, it simply sets image itself without anyway to wrap this operation into UIView animation or something..

**Comment by mythodeia** [comment]
check this https://github.com/rs/SDWebImage/pull/702
animating the appearing image is outside the scope/purpose of this library. Thanks
