### ISSUE TITLE
APNG support

### ISSUE THREAD

**Issue by TAKeanice** [rs/SDWebImage#1060]
Apng support would be a nice addition to SDWebImage, since there is already some sites which generate apngs, like http://preloaders.net .

**Comment by bpoplauschi** [comment]
Would you be interested in making a Pull Request?

**Comment by TAKeanice** [comment]
I´d love to provide you with a pull request! But it will take some time until I have one ready, since the idea for that came to me today, and I have not done anything with APNGs yet. There is some APNG Disassembler, maybe I can use some code from there. Do you know any existing APNG iOS Library or similar? Safari in iOS8 supports APNGs, but I don´t think it is possible to leverage that (and it would not be compatible with any prior versions, then)

**Comment by flovilmart** [comment]
Spec available here; https://wiki.mozilla.org/APNG_Specification

**Comment by TAKeanice** [comment]
Sounds reasonable, so I will close this request and instead look for supporting FLAnimatedImage with this. I've already read the specs, and looked at the code of an APNG disassembler, but I'm not sure ho to leverage all features of the format with UIImage or UIImageView

**Comment by aodhol** [comment]
Any plan to support APNG?

**Comment by bpoplauschi** [comment]
@aodhol there is no plan from us the maintainers to support APNG.
