### ISSUE TITLE
Missing tag for 3.7.2

### ISSUE THREAD

**Issue by zadr** [rs/SDWebImage#1061]
Any chance a git tag could be made for 3.7.2 to match the new podspec? Without it, we can't update use the new version -- `pod trunk push…` fails and can't generate an update for https://github.com/CocoaPods/Specs (resulting in `pod update` never finding the new version).

Thanks.

**Comment by iOSDeveloperL** [comment]
I've the same problem. It fails to update the Pods project.

[!] Unable to satisfy the following requirements:

- `SDWebImage (= 3.7.2)` required by `Podfile`

**Comment by bpoplauschi** [comment]
I will look into this, I must check if the current master doesn't have some breaking changes. If that is the case, then we can't release a 3.7.2 version, as it would break compatibility.

**Comment by rromanchuk** [comment]
Guys, just a reminder, you don't have to wait for the spec to update. Just cut the equivalent and leave yourself a comment 

`pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git', :commit => '962bcb03231d3baa8a0463743d148f494cbed5aa' #3.7.2`

**Comment by zadr** [comment]
@rromanchuk Thanks for the note. It's definitely a valid suggestion— and what wound up happening on the project I needed the tag for.

My qualm is that explicitly specifying a hash is nonstandard behavior. Ideally, the pod should be able to match the example spec as much as possible. That isn't to say that specifying a hash is undocumented or unsafe, only that it is undesirable (to me).

**Comment by bpoplauschi** [comment]
I have just released 3.7.2, with a tag and distribution via CocoaPods.
