### ISSUE TITLE
Custom headers for every image download

### ISSUE THREAD

**Issue by Igor-Palaguta** [rs/SDWebImage#1066]
Access to remote images require custom headers. For every image header values are different. Is there any way to implement this.

**Comment by Igor-Palaguta** [comment]
is headersFilter - what I need?

**Comment by mythodeia** [comment]
something like this you mean? https://github.com/rs/SDWebImage/pull/514

**Comment by Igor-Palaguta** [comment]
Yes! Thank you for great library! If it could store video it will be the best!

**Comment by mythodeia** [comment]
closing this. :+1:
