### ISSUE TITLE
For some cells image is downloaded but not updated on TableView

### ISSUE THREAD

**Issue by NomiJ** [rs/SDWebImage#1068]
Here is the scenario

Image # 9 is not yet downloaded 
![screen shot 2015-03-14 at 8 11 41 pm](https://cloud.githubusercontent.com/assets/8808212/6652144/99747db0-ca86-11e4-9120-cbc0af11721f.png)

Click on Image # 9 and its downloaded now 
![screen shot 2015-03-14 at 8 11 47 pm](https://cloud.githubusercontent.com/assets/8808212/6652145/a2bfb2a4-ca86-11e4-8fbd-ef4f0a5a65b3.png)

Go Back to TableView, Image # 9 is still blank, there is no preview of downloaded image

![screen shot 2015-03-14 at 8 11 51 pm](https://cloud.githubusercontent.com/assets/8808212/6652150/d6e659ca-ca86-11e4-8307-bc06744bbb57.png)

**Comment by mythodeia** [comment]
those 2 images in the demo fail to load. if you see the console log in your browser you will see that the images do not exist

**Comment by NomiJ** [comment]
Then why does i see the following image once i click # 9
https://cloud.githubusercontent.com/assets/8808212/6652145/a2bfb2a4-ca86-11e4-8fbd-ef4f0a5a65b3.png

**Comment by mythodeia** [comment]
number 9 image is [this](http://static2.dmcdn.net/static/video/771/577/44775177:jpeg_preview_small.jpg?20120509183230)
open it with your browser...on the console of the browser you will see 404 error message. thats why the small image does not appear.
the details screen has [this image](http://static2.dmcdn.net/static/video/771/577/44775177:jpeg_preview_source.jpg?20120509183230)
the difference in the 2 urls is the one asks for ```small``` and the other asks for ```source```
the source url works. the small url has 404 error message thats why you do not see the thumb
