### ISSUE TITLE
WKInterfaceImage Support

### ISSUE THREAD

**Issue by bassrock** [rs/SDWebImage#1070]
Now that WatchKit is upon us it would be really cool to see WKInterface being supported. I created an extension for it here that sort of mirrors the functionality of UIImageView:

https://gist.github.com/bassrock/2400d9c7167f626d50ca

Open for improvements discussions on supporting WatchKit. Especially the WatchKit device Image Cache

**Comment by twilly86** [comment]
That gist isn't loading for me.  I just see a blank page.

**Comment by bassrock** [comment]
@twilly86  sorry try this: https://gist.github.com/bassrock/2400d9c7167f626d50ca

**Comment by mythodeia** [comment]
closing this. keeping https://github.com/rs/SDWebImage/issues/1192

**Comment by dreampiggy** [comment]
If anyone who is still interested in using `sd_setImageWithURL` on the `WKInterfaceImage`, maybe it's time to see #2331. Which share the same codebase as UIKit's implementation, match the nearest behavior of all your iOS usage for SDWebImage framework :)
