### ISSUE TITLE
Wow! Immediate crash due to memory-use for a simple download of a single image

### ISSUE THREAD

**Issue by objectmethod** [rs/SDWebImage#1072]
I created a super, simple project to recreate this here: https://github.com/objectmethod/SDWebImageCrashTest

Basically, all it does is attempt to download one image using SDWebImage, and it immediately uses all available memory and crashes.

**Comment by rromanchuk** [comment]
Fix your podfile

`pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git', :commit => '962bcb03231d3baa8a0463743d148f494cbed5aa' #3.7.2`

And make sure you set below in your `didFinishLaunchingWithOptions`
```
 SDImageCache.sharedImageCache().shouldDecompressImages = false
 SDWebImageDownloader.sharedDownloader().shouldDecompressImages = false
```

**Comment by mythodeia** [comment]
Just a reference for the image in question:
for every pixel in an image 4 bytes are used. So to calculate the memory:
```height x width x 4 = total bytes in memory.```
```10.000*10.000*4 = roughly 382MB```
can you try with the latest build and use the advice @rromanchuk suggested and report back?

**Comment by objectmethod** [comment]
That's very helpful, @mythodeia.  I have tried with the latest build and using the advice of @rromanchuk.  Using the latest build and instructing SDWebImage to not decompress the image prevented the crash at that point.  I'm still left with the issue of how to display such a large image, but that seems beyond the scope of this wonderfully-built library!! :)  Thanks everyone for the support and feedback.

**Comment by zhangxiaolian1991** [comment]
@mythodeia  @objectmethod  I have try @rromanchuk 's advice,but that seem no use. The memory is still very high.Any else solution?

**Comment by mythodeia** [comment]
whats the resolution/size of the images you download? @zhangxiaolian1991

**Comment by zhangxiaolian1991** [comment]
@mythodeia  I use @objectmethod 's demo to test. so the size is 10000 × 10000

**Comment by mythodeia** [comment]
of course the memory is high with this kind of image. to load this you will need to do other things.
read [this](http://stackoverflow.com/questions/12089453/huge-images-in-ios-app-without-catiledlayer)

**Comment by zhangxiaolian1991** [comment]
Thanks @mythodeia ,Sometimes GIF will cause hight memory,any suggestion?

**Comment by mythodeia** [comment]
for gif you can use the [this](https://github.com/Flipboard/FLAnimatedImage)

**Comment by zhangxiaolian1991** [comment]
I ever use this but scroll is not smooth
