### ISSUE TITLE
SDWebImage residing in swift module breaks the debugger

### ISSUE THREAD

**Issue by KoCMoHaBTa** [rs/SDWebImage#1074]
When SDWebImage files are copied into a swift module (embedded framework) - debugger gets broken and stop to execute any commands.

When the debugger tries to convert ObjC module headers to Swift - __IPHONE_OS_VERSION_MIN_REQUIRED is set to 20000 which throws an error from the deployment target check.

The fix for this is to change line 16 in SDWebImageCompat.h 

from: 
#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_5_0
#error SDWebImage doesn't support Deployement Target version < 5.0
#endif

to 
#if __IPHONE_OS_VERSION_MIN_REQUIRED != 20000 && __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_5_0
#error SDWebImage doesn't support Deployement Target version < 5.0
#endif

**Comment by flovilmart** [comment]
@KoCMoHaBTa  Use the module WebImage instead of the static lib and you should be fine.

**Comment by KoCMoHaBTa** [comment]
Sorry for the late response.
Originally i was not using the static library, but was copying the files into a swift framework, which i created by my own. 
Right now i have migrated the lib to be a dependency for my project and link against the WebImage framework. 
It appears to be fine for now. 
Thanks!

**Comment by NitWitStudios** [comment]
@flovilmart  @KoCMoHaBTa  Late to the party, but having the same issue. I installed the latest version of SDWebImage using cocoapods yesterday and now having the debugger errors. What did you mean by: 

>Use the module WebImage instead of the static lib and you should be fine.

**Comment by flovilmart** [comment]
I've added a framework build scheme that builds WebImage.framework and doesn't break the debugger.




You can import it in your swift file with

    import WebImage

**Comment by NitWitStudios** [comment]
That's included in the current cocoa pod? Tried adding and failed 'No such module WebImage'.
Do I still need to import this in the bridging header?: #import <SDWebImage/UIImageView+WebCache.h>

Thanks for the quick response!

**Comment by flovilmart** [comment]
Dunno about cocoapods. Works perfectly with Carthage

**Comment by NitWitStudios** [comment]
@flovilmart Unfortunately, I can't introduce Carthage to this existing project due to some restrictions. But was wondering if I missed a step. What do you mean by "I've added a framework build scheme that builds WebImage.framework"?
Do I need to run anything to build the actual framework? Or should it already be included in the main library?

**Comment by KoCMoHaBTa** [comment]
Probably the cocoapods version automatically link against the static library, huh?!? and this is why you cannot import the swift module, because it does not exist when you are building.
@flovilmart Carthage FTW :)
Another option will be to manually add WebImage.framework as target dependency and link your target against it.

**Comment by NitWitStudios** [comment]
@KoCMoHaBTa Ahh ok I will give that a shot now. Thanks for the clarification!

**Comment by NitWitStudios** [comment]
@KoCMoHaBTa So I downloaded the latest master, and I'm not seeing the WebImage framework, just a WebImage folder with a .h / .plist file (see screenshot). Still missing something?
![screenshot](https://cloud.githubusercontent.com/assets/1779541/7526936/63472b60-f4cb-11e4-8224-f01a860610b9.png)

**Comment by KoCMoHaBTa** [comment]
![screen shot 2015-05-08 at 1 13 09 am](https://cloud.githubusercontent.com/assets/1181346/7527000/db6b5bee-f51f-11e4-9d9d-3427f14ebfca.png)
![screen shot 2015-05-08 at 1 18 47 am](https://cloud.githubusercontent.com/assets/1181346/7527024/3aa6cf4e-f520-11e4-95bd-bdddf05b52f7.png)

@NitWitStudios  Just copy or link the SDWebImage project to yours. Then add WebImage.framework as target dependency and link against it.
If you are copying the project - make sure you are have all targets unchecked.

**Comment by NitWitStudios** [comment]
@KoCMoHaBTa Thanks for the guide! Did all that, but now get this error:

>ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/WebImage.framework/WebImage) for architecture x86_64

Our app currently supports iOS 7.0 and up, so hoping their is a fix for this... :-/

**Comment by KoCMoHaBTa** [comment]
Umm, yes, you are supporting iOS 7. Well you have 2 options:
1. Use the workaround that i have provided in the issue definition and manually link against the static lib, without cocoapods in order to avoid changes when updating cocoapods.
2. Google for a way how to use swift frameworks in iOS 7. There was a way when swift was released initially at version 1.0 w/ Xcode 6.0 w/ iOS 8.0 and it was working for iOS 8.1 w/ Xcode 6.1. Just lookup for this, it may still work.

I would suggest you the first option.

**Comment by KoCMoHaBTa** [comment]
@flovilmart What do you think about applying the fix that i have initially provided? There are still a lot of developers targeting iOS 7 and/or using cocoa pods. 
I personally think that it won't affect/break anything.

**Comment by NitWitStudios** [comment]
@KoCMoHaBTa Thanks for all the help, I will keep playing around with it.
@flovilmart Yes, please add support for cocoapods and iOS 7! Still a lot of companies using those combinations and would be super helpful!

Thanks again for the support guys!

**Comment by flovilmart** [comment]
iOS 7 doesn't support dynamic frameworks, so I guess I can't go really forward from there.

If you're targeting ios7 with swift code, I guess your best option is to use the cocoapods with the broken headers and let the debugger complain :)




What was the fix you provided @Milen ?

**Comment by KoCMoHaBTa** [comment]
>The fix for this is to change line 16 in SDWebImageCompat.h
>
>from: 
>#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_5_0
>#error SDWebImage doesn't support Deployement Target version < 5.0
>#endif
>
>to 
>#if __IPHONE_OS_VERSION_MIN_REQUIRED != 20000 && >__IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_5_0
>#error SDWebImage doesn't support Deployement Target version < 5.0
>#endif

**Comment by flovilmart** [comment]
Fork mine, and PR on my branch :)

**Comment by KoCMoHaBTa** [comment]
Which one is your branch?

**Comment by NitWitStudios** [comment]
@KoCMoHaBTa FYI - You got an extra '>' after the &&

**Comment by flovilmart** [comment]
Actually you should PR on the master as it affects all versions :)

**Comment by KoCMoHaBTa** [comment]
@NitWitStudios Thanks
@flovilmart Your fork's master is few years old. I think to submit PR on the original repository.

**Comment by flovilmart** [comment]
Yeah sure :) I was thinking about my Carthage / WebImage branch, but it's been merged

**Comment by KoCMoHaBTa** [comment]
Submitted a Pull Request: #1138
