### ISSUE TITLE
question

### ISSUE THREAD

**Issue by swtlovewtt** [rs/SDWebImage#1077]
你定义的dispatch_main_sync_safe和dispatch_main_async_safe有什么区别？
我看他们的区别是主线程同步和异步，主线程同步设置了图片，异步设置了错误返回。
但是主线程异步设置图片的话会出错吗？
如果用
                [[NSOperationQueue mainQueue] addOperationWithBlock:^{
                    img.image = tempImage;
                }];
这个来设置图片和你的又有啥区别，求解释

**Comment by swtlovewtt** [comment]
the marco you defined 'dispatch_main_async_safe' and 'dispatch_main_async_safe'.
what's the difference of this two marco?
in 'dispatch_main_async_safe' you set the image from web.
in 'dispatch_main_async_safe' you return an error.
is this two marco has difference?
how about use OperatinonQueue:

[[NSOperationQueue mainQueue] addOperationWithBlock:^{
img.image = tempImage;
}];

need your answer ,thank you .😄

**Comment by heistings** [comment]
Do you mean `dispatch_main_sync_safe` and `dispatch_main_async_safe` ?

**Comment by heistings** [comment]
There are three ways to control threads, NSThread, NSOperationQueue and GCD. You can find them out with google I think.

**Comment by swtlovewtt** [comment]
thank you ,I know the 
 thank you .now I know the <code> dispatch_main_async_safe </code> may faster than  <code> dispatch_main_sync_safe </code>. am I right?
and  how about use OperatinonQueue:
<code>
[[NSOperationQueue mainQueue] addOperationWithBlock:^{

}];</code>

**Comment by heistings** [comment]
It's hard to say `dispatch_main_async_safe` is faster than  `dispatch_main_sync_safe`, it's about synchronization and asynchronization.

The NSOperationQueue code you give works just like `dispatch_main_async_safe `.

```objective-c
    NSLog(@"Before add queue.");
    
    [[NSOperationQueue mainQueue] addOperationWithBlock:^{
        NSLog(@"Queue block fired.");
    }];
    
    NSLog(@"After add queue.");
```

##### Result

```
2015-03-19 10:14:58.492 NSOperationQueueTest[923:32146] Before add queue.
2015-03-19 10:14:58.493 NSOperationQueueTest[923:32146] After add queue.
2015-03-19 10:14:58.501 NSOperationQueueTest[923:32146] Queue block fired.
```

**Comment by mythodeia** [comment]
@swtlovewtt check this [nice article](http://jeffreysambells.com/2013/03/01/asynchronous-operations-in-ios-with-grand-central-dispatch) and also [this](https://developer.apple.com/library/ios/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationQueues/OperationQueues.html) which can help understanding GCD
