### ISSUE TITLE
Some images blinks after appearing for a while when SDWebImageProgressiveDownload

### ISSUE THREAD

**Issue by nandodelauni** [rs/SDWebImage#1079]
This is the code I am using:

```
[self sd_setImageUsingProgressWithURL:url placeholderImage:nil options:SDWebImageProgressiveDownload progress:nil completed:nil];
```

I've tried also using `placeholderImage:self.image` and also the new method `sd_setImageWithPreviousCachedImageWithURL:...` but the same happens. Here you have a video demo:

https://www.dropbox.com/s/mepl9vjjr80m2vu/Untitled.mov?dl=0

If a remove the progressive download flag it doesn't happens.

**Comment by mythodeia** [comment]
how are you adding the progressview?
check this [old commit](https://github.com/mythodeia/SDWebImage/commit/2cfa5ccb883191df510ad15df2a97a765b9d5e82)
and let me know if that works better for you

**Comment by nandodelauni** [comment]
Actually I am not using progressView at all because option `SDWebImageProgressiveDownload` makes it useless most of the time showing part the image (low/decent quality or most of the image) and the progressView at a time. I am going to edit removing the noise.

**Comment by heistings** [comment]
I'm sorry, I just hardly to find out where is the method: `sd_setImageUsingProgressWithURL` ?

**Comment by mythodeia** [comment]
apparently its a custom method he wrote to add the progress functionality.

**Comment by heistings** [comment]
**Some** images blinks after appearing for a while when SDWebImageProgressiveDownload. 
Is this issue occurs on particular url?

**Comment by heistings** [comment]
The code below works well for me:
```objective-c
    NSString *urlString = @"http://x1.zhuti.com/down/2013/3/17-win7/lf-1.jpg";
    [[self imageView] sd_setImageWithURL:[NSURL URLWithString:urlString] placeholderImage:nil options:SDWebImageProgressiveDownload];
```

**Comment by mythodeia** [comment]
@nandodelauni can you try your datasource on the sample project, without changing anything else?

**Comment by mythodeia** [comment]
@nandodelauni any news on this? did you try the sample project using your own datasource ? does it still flicker?

**Comment by nandodelauni** [comment]
sorry @mythodeia will check tomorrow morning and come back to you. thanks!

**Comment by nandodelauni** [comment]
Images loaded in a UICollectionView (full width, scroll vertically) works just fine, however the same images blinks when presenting the same cells in UIPageViewController (horizontall scroll) and every page appears (as shown in the initial video) so the issue may be with the _page_ being refreshed or something, the image should be cached and no apparently blink should happen even refreshing the cell tho.

**Comment by mythodeia** [comment]
the image is cached and shown without blinking or flickering like you said in a collectionview either horizontal or vertical.
i think uipageviewcontroller has a fade effect that makes the image blink on load. Consider adding your own transition effect to make that go away.
Nevertheless i do not think there is a problem with the library.

**Comment by nandodelauni** [comment]
I'm closing this and investigaste further in the UIPageViewController thing. Will post here if find anything interesting. Thanks! :+1:

**Comment by bpoplauschi** [comment]
Thanks for the details @nandodelauni
