### ISSUE TITLE
crash on setImageWithURL: without -ObjC linker flag

### ISSUE THREAD

**Issue by tedyyu** [rs/SDWebImage#1080]
My project doesn't allow me to use -ObjC as it will cause linking errors in some other 3rd party static lib. So I follow the readme to use alternative linker flag "-force_load $(TARGET_BUILD_DIR)/libPods.a" as I use cocoapod in my projrect.

still I get the runtime exception:

SDWebImageDemo[84457:3341161] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIImageView sd_setImageWithURL:]: unrecognized selector sent to instance 0x7f879a77f710'

Please help me out!

**Comment by tedyyu** [comment]
![image](https://cloud.githubusercontent.com/assets/1762184/6730065/b25a2ee2-ce73-11e4-89e0-47d8f79fce26.png)

The linker flags I set, having the exception.

**Comment by bpoplauschi** [comment]
This should work. Please try some cleanup (delete derived data, refresh pods by removing SDWebImage from the podfile, doing a pod update, then re-adding it and pod update again, ...).

**Comment by tedyyu** [comment]
@bpoplauschi , I do exactly what you said, and it still failed at the same point.

You can get my simple demo project with only a UIImageView from following link:
http://share.weiyun.com/f6d3522da36b8e973a83aa05707179ee

**Comment by bpoplauschi** [comment]
I can't download the file, it asks me to login plus it's Chinese and I can't read it. Could you share it some other way?

**Comment by tedyyu** [comment]
sorry about that. Here is dropbox link:

https://www.dropbox.com/s/jpguvqivu5wfubr/SDWebImageDemo.zip?dl=0

**Comment by mythodeia** [comment]
@tedyyu sorry for the delay. add this to a new line in the other linker flags
```$(inherited)```
now it works :+1:

**Comment by bpoplauschi** [comment]
Could you add it, please?

**Comment by mythodeia** [comment]
done
