### ISSUE TITLE
UIImage+WebP.h file not found

### ISSUE THREAD

**Issue by wangyanlong** [rs/SDWebImage#1086]
no.1

When I use cocopods to install SDWebImage.I found no UIImage+WebP.h file in my Xcode directory.
![image](https://cloud.githubusercontent.com/assets/5455698/6764052/c36130b8-cfd7-11e4-88fd-712573ea2d5d.png)

This is my Podfile
![image](https://cloud.githubusercontent.com/assets/5455698/6764055/f5acbfa6-cfd7-11e4-8054-282a19235869.png)

How do I want to use WebP's format support?

no.2

What method can cache a webp format images, and provide the download progress percentage tips?

thanks!

**Comment by mythodeia** [comment]
check this https://github.com/rs/SDWebImage/issues/971 for your webp issues.
Basically you should clone the repository and add the missing files in your project
check [the documentation here](https://github.com/rs/SDWebImage/blob/master/SDWebImage/UIImageView%2BWebCache.h)
for available methods with progress
