### ISSUE TITLE
Carthage not working

### ISSUE THREAD

**Issue by guilhermecvm** [rs/SDWebImage#1087]
Project "SDWebImage.xcodeproj" has no shared schemes

**Comment by samritchie** [comment]
Carthage picks up the most recent github release, and the shared schemes were added after that. As a workaround, you can do:

    github "rs/SDWebImage" "master"

until a new release is created.

**Comment by TaylorSMarks** [comment]
The master branch fails to build right now. Is there a different specific version we can use which isn't a release version, but is new enough to use shared schemes and actually build?

**Comment by bpoplauschi** [comment]
Just released version 3.7.3. Closing.

**Comment by bpoplauschi** [comment]
Just released version 3.7.3. Closing.
