### ISSUE TITLE
crashed on image loading

### ISSUE THREAD

**Issue by sahabe1** [rs/SDWebImage#1088]
Hi I am using SDWebImage library and getting always crash
-[UIImageView sd_setImageWithURL:]: unrecognized selector sent to instance 0x7f9e9178d740
2015-03-23 11:47:22.829 ImageDemo[1206:22350] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIImageView sd_setImageWithURL:]:

I tried both way using cocoapods and by importing files

**Comment by mythodeia** [comment]
try cloning the repository using this 
``` git clone --recursive https://github.com/rs/SDWebImage.git ```

**Comment by mythodeia** [comment]
@sahabe1 do you have any updates on this?

**Comment by willbin** [comment]
@sahabe1 
Do you import?
  `#import <SDWebImage/SDImageCache.h>`
   `#import <UIImageView+WebCache.h>`

**Comment by mythodeia** [comment]
closing thins. if you need further help please reopen
