### ISSUE TITLE
UIImageView category calls progress block on random thread

### ISSUE THREAD

**Issue by pronebird** [rs/SDWebImage#1089]
Hi,

I use a method on UIImageView to preload image and update indicator view:

```objc
[self.imageView sd_setImageWithURL:url placeholderImage:nil options:SDWebImageRetryFailed | SDWebImageRefreshCached progress:^(NSInteger receivedSize, NSInteger expectedSize) {
    NSAssert([NSThread isMainThread], @"In UIKit we should be in main thread lands.");
    // do something useful
} completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
    NSAssert([NSThread isMainThread], @"In UIKit we should be in main thread lands.");
    // do something useful
}];
```
Turns out progress block is called on some random thread while completion block is called on main thread. 

What's the point of that behavior? This is not reflected in documentation either. If you call something on random thread, please mention this in documentation especially for UIKit categories.

**Comment by bpoplauschi** [comment]
@pronebird the documentation for `SDWebImageDownloader` stated that the `progressBlock` is called on a background queue. Also added 62180db for more explicitly saying this for all APIs. (4.x branch).
