### ISSUE TITLE
Ability To Set Disk Image Cache Path

### ISSUE THREAD

**Issue by bassrock** [rs/SDWebImage#1092]
Now with all the extension support it would be great if SDWebImage had the ability to set the diskPath manually as you need to set the path with the following method:

``` NSFileManager.defaultManager().containerURLForSecurityApplicationGroupIdentifier("com.democomapny.url") ```

**Comment by bpoplauschi** [comment]
Isn't the `makeDiskCachePath:` method sufficient. You can subclass `SDImageCache` and rewrite this method.

**Comment by bassrock** [comment]
yes it is

**Comment by georgbachmann** [comment]
Just a quick question... I'd like to use a folder that's shared between the main-app and my share-extension as the cache location.

In the change-logs for version 5 I read:

> makeDiskCachePath: removed, use NSSearchPathForDirectoriesInDomains with NSString's Path API instead.

So is it still possible to change the path? Or is that option gone?

**Comment by dreampiggy** [comment]
> So is it still possible to change the path

Is this anything related to `makeDiskCachePath` API ? That API is used to generate a temp directory of your input arg. Not change any config of cache. And this API actually, it's useless, it's just one line of `NSFileManager.createDirectoryAtURL + NSSearchPathForDirectoriesInDomains`. But its hack on the suffix break it's common usage.

> How to custom cache path

Just create your cache instance using `initWithNamespace:diskCacheDirectory:config:` instead.

**Comment by imWildCat** [comment]
@dreampiggy sorry to bother. After creating the cache instance, how to use it?

for example, 

```swift
    SDImageCachesManager.shared.caches = [
      SDImageCache(namespace: Constants.cacheNamespace, diskCacheDirectory: cacheFolderURL.path),
    ]
    
    SDWebImageManager.defaultImageCache = SDImageCachesManager.shared

    SDImageCache.defaultDiskCacheDirectory = cacheFolderURL.path
```

this does not seem to work for me
