### ISSUE TITLE
SDImageCache maxCacheAge

### ISSUE THREAD

**Issue by oleynikd** [rs/SDWebImage#1095]
It is said 
```
/**
 * The maximum length of time to keep an image in the cache, in seconds
 */
@property (assign, nonatomic) NSInteger maxCacheAge;
```

What kind of cache is it about? RAM or Disk?

I tried to use it like this:
`[[SDImageCache sharedImageCache] setMaxCacheAge:30];`

But it doesn't seem to work. Nothing happens in 30 secs... Memory usage is the same. Images are not being updated from remote server even after app restart.

Thanks.

**Comment by mythodeia** [comment]
this is actually used when using the ```cleanDisk``` method which removes all expired cached images from disk.
