### ISSUE TITLE
enable disk caching?

### ISSUE THREAD

**Issue by ryanmeador** [rs/SDWebImage#1096]
Hi,
The docs repeatedly mention an "optional disk cache", how do I turn this on?  I can't find anything automatic in the docs, it looks like the only way to use it is to call ```SDImageCache storeImage:forKey:toDisk:```.  Thanks!

**Comment by mythodeia** [comment]
@ryanmeador memory & disk caching is enabled by default. 
you can use ```SDWebImageCacheMemoryOnly``` option to disable the disk caching and leave only memory caching

**Comment by patniemeyer** [comment]
I had the same question.  It sounds from your response above that disk caching is the default, but the docs do not actually say this anywhere.  (I had been looking for a section describing some config parameters or some description of how the disk caching is accomplished or its limitations, etc.  e.g. Does it grow forever?  How do you clean it?)  The section describing the optional separate use of the cache might lead people to assume they have to manually cache to get this feature.  I'm sure it will all become clear as I dig into the code more but just wanted to note this as a new user reading through docs.

**Comment by mythodeia** [comment]
@patniemeyer 
[this](https://github.com/rs/SDWebImage#using-sdwebimagemanager) is used to download and cache image async
[this](https://github.com/rs/SDWebImage#using-asynchronous-image-downloader-independently) only downloads the image
You are right the docs are not clear enough on some issues. 
You can see [here](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDImageCache.h#L202) and [here](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDImageCache.h#L214)
how to clean the cache (memory and disk)
