### ISSUE TITLE
Allow using custom namespaced caches with UIImageView extensions

### ISSUE THREAD

**Issue by wesj** [rs/SDWebImage#1098]
I'd like to be able to maintain a few different caches (to allow wiping separate data types i.e. wipe all the images for list 1, but not the ones for list 2). I can do that by creating my own caches, but they aren't tied to UIImageView methods, so they can't be used for lists very easily. I'd like to be able to do something like:

NSString *MyNamespace = @"MyNamespace";
[cell.imageView sd_setImageWithURL:[
      NSURL URLWithString:@"http://www.domain.com/path/to/image.jpg"]
      placeholderImage:[UIImage imageNamed:@"placeholder.png"]
      namespace:[MyNamespace]];

or maybe better:

SDImageCache *imageCache = [[SDImageCache alloc] initWithNamespace:@"myNamespace"];
[cell.imageView sd_setImageWithURL:[
      NSURL URLWithString:@"http://www.domain.com/path/to/image.jpg"]
      placeholderImage:[UIImage imageNamed:@"placeholder.png"]
      cache:[imageCache]];

I can write something up if you would accept it?

**Comment by mythodeia** [comment]
@wesj check [this](https://github.com/rs/SDWebImage/pull/1041)
