### ISSUE TITLE
Sometimes Image can't be cached automatically

### ISSUE THREAD

**Issue by githubdbbest** [rs/SDWebImage#1100]
Fix
in SDWebImageDownloaderOperation.m 
function ```connectionDidFinishLoading``` code :
```completionBlock(nil, nil, nil, YES);```
replace with code 
```
            NSString *key = [[SDWebImageManager sharedManager] cacheKeyForURL:self.request.URL];
            UIImage *image = [UIImage sd_imageWithData:self.imageData];
            if (key && image) {
                [[SDImageCache sharedImageCache] removeImageForKey:key];
                [[SDImageCache sharedImageCache] storeImage:image forKey:key];
                image = [self scaledImageForKey:key image:image];
            }
            completionBlock(image, self.imageData, nil, YES);
```

**Comment by mythodeia** [comment]
@githubdbbest i edited your post so everyone can understand the code better

**Comment by mythodeia** [comment]
@githubdbbest if you check the option ```SDWebImageDownloaderIgnoreCachedResponse``` on the ```SDWebImageDownloader.h``` file you will see the image & data are set to nil on purpose when the image is read form NSURLCache
