### ISSUE TITLE
Can't import SDWebImage when using latest CocoaPod installation 

### ISSUE THREAD

**Issue by houmie** [rs/SDWebImage#1102]
Please see here for more info: http://stackoverflow.com/questions/29329170/import-sdwebimage-fails-despite-cocoapod-installation

Something doesn't seem to be right. I even deleted all pods and reinstalled everything.

**Comment by heistings** [comment]
What do you see when you are typing `pod search SDWebImage` in the shell?

**Comment by bpoplauschi** [comment]
Looks like the StackOverflow question was answered.
