### ISSUE TITLE
Some files have different licenser from LICENSE.

### ISSUE THREAD

**Issue by atsuto** [rs/SDWebImage#1103]
I found some files which has different licenser from LICENSE.
Could you fix it?
LICENSE says licenser is "Olivier Poitrey".
https://github.com/rs/SDWebImage/blob/master/LICENSE

but...
1.licenser is "Dailymotion".
below files.
SDWebImage/MKAnnotationView+WebCache.h
SDWebImage/MKAnnotationView+WebCache.m
SDWebImage/NSData+ImageContentType.h
SDWebImage/NSData+ImageContentType.m
SDWebImage/SDWebImageCompat.m
SDWebImage/UIImage+MultiFormat.h
SDWebImage/UIImage+MultiFormat.m
SDWebImage/UIImage+WebP.h
SDWebImage/UIImage+WebP.m

2.licenser is "__MyCompanyName__".
SDWebImage/UIImage+GIF.h
SDWebImage/UIImage+GIF.m

3.licenser is "Olivier Poitrey and Jamie Pinkham"
SDWebImage/SDWebImageCompat.h

**Comment by bpoplauschi** [comment]
Right. We need to review this.
@rs what should we use?
