### ISSUE TITLE
How return an UIImage directly from SDWebImage?

### ISSUE THREAD

**Issue by sekmo** [rs/SDWebImage#1105]
I know that SDWebImage can set an image property of an UIImageView out of an NSURL, but can I directly return a cached UIImage directly without setting an UIImageView.image property?

I made a class that have some methods that returns an UIImage, so I would use SDWebImage to cache UIImage... It would be possibile?

The trick is that SDWebImage relies on cached NSURLs instead on cached UIImages?

Thanks :-)

**Comment by mythodeia** [comment]
why do you want to cache the whole UIImage object and not its contents? 
I think its faster to cache and retrieve a simple URL instead of the whole image object.
To make something like that work you would need to create methods to add the UIImage to cache and to disk as well as retrieve the whole object based on key.

**Comment by mythodeia** [comment]
if i understand you correctly you want something like this:
``` - (UIImage *)imageFromDiskCacheForKey:(NSString *)key; ```
or
``` - (UIImage *)imageFromMemoryCacheForKey:(NSString *)key; ```
these methods will simply return the UIImage for a specific url

**Comment by sekmo** [comment]
Thanks for your support... It was exactly what I'm looking for, but I'm a little lost...
There is a method that takes an URL (NSURL or String) and outputs an UIImage, retrieving from cache if it's cached, or otherwise downloading and caching it?

**Comment by mythodeia** [comment]
The image must be downloaded first so it can be cached.
Or you can cache it manually
Please check documentation for more details

**Comment by hccgk** [comment]
i also have this problem，have you solve this problem？

**Comment by dreampiggy** [comment]
See wiki: [How-To-Use](https://github.com/SDWebImage/SDWebImage/wiki/How-to-use). You have multiple solutions to solve your use case depent on what you want.

## Network only ? Cache only ? Or both
For network download, using `SDWebImageDownloader downloadImageWithURL:` method.

For cache only, using `SDImageCache queryCacheOperationForKey:` method.

For both, using `SDWebImageManager loadImageWithURL:` method.

## Synchronized or Asynchronized ?
All of the above are asynchronized method. It's recommaned to do so to avoid blocking main queue for your application.

If you're already in the background queue or have need for synchronized version. Try these:

For network download, there are no official API. However, you can use `DispatchGroup` API with `group enter, group leave` with a async block. You can also download the data by yourself, then using our decoder `SDWebImageCoder decodedImageWithData:` method to decode `NSData` to `UIImage`.

For cache only, using `SDImageCache imageFromCacheForKey:`, `imageFromMemoryCacheForKey`, `imageFromDiskCacheForKey` method.

For both,  there are no official API. However, you can use `DispatchGroup` API to transfer the async version to sync version like the network download one.
