### ISSUE TITLE
Caching UIImage with Orientation RIGHT is retrieved from Disk with Orientation UP

### ISSUE THREAD

**Issue by levieggert** [rs/SDWebImage#1110]
Hey so I'm seeing something very odd when retrieving cached images from disk via SDWebImage v_3.7.2.  I'm hoping you guys can shed some light on what is happening.  

Here is the scenario.

1. I use UIImagePickerController to grab a UIImage *photo from the image library.  This photo from the photo library contains an image orientation RIGHT with dimensions 2448x3264.

2. I add the photo to a UIImageView via UIImageView setImage.  The image displays correctly.

3. I cache this photo via SDWebImageCache [imageCache storeImage:image forKey:key toDisk:YES];

Here's where things get weird.

4.  When I retrieve the photo from the cache and it is pulled from SDImageCache imageFromMemoryCacheForKey everything is fine.  The image orientation is still RIGHT and the dimensions are 2448x3264.  When I display this in a UIImageView the image is correctly drawn.

However, say I suspend the app to the background and relaunch the app, the image is now pulled from SDImageCache diskImageForKey and the orientation is UP and the dimensions are 3264x2448.  When I display this in a UIImageView the image is rotated -90 degrees CCW.

I'm not sure if this is a bug in SDWebImage or just iOS is doing something to the image once pulled from cache.

My workaround for this is before I cache any images, I check if the orientation is RIGHT, if it is, I create a new UIImage context that rotates the image 90 degrees clockwise.  Then when storing the image to cache the orientation will be UP and pulling the image from cache the orientatiln will remain UP and the photo is correctly drawn in a UIImageView.

It's a little scary doing this as I'd prefer any cached images with orientation RIGHT to keep that orientation once pulled from disk cache.

However, this may be the way iOS pulls images from disk.  Any insight on this is much appreciated.

Thanks!

Here's the code for rotating an image before cacheing if anyone needs a fix for this.
```
UIImage *photo = //photo from UIImagePickerController
if (photo.imageOrientation == UIImageOrientationRight)
{
            CGFloat radians = M_PI * 90.0f / 180.0f;
            
            UIGraphicsBeginImageContext(photo.size);
            
            CGContextRef bitmap = UIGraphicsGetCurrentContext();
            
            CGContextTranslateCTM(bitmap, photo.size.width / 2.0f, photo.size.height / 2.0f);
            
            CGContextRotateCTM(bitmap, radians);
            
            CGContextScaleCTM(bitmap, 1.0f, -1.0f);
            
            CGContextDrawImage(bitmap, CGRectMake(photo.size.height / 2.0f * -1.0f, photo.size.width / 2.0f * -1.0f, photo.size.height, photo.size.width), photo.CGImage);
            
            photo = UIGraphicsGetImageFromCurrentImageContext();
            UIGraphicsEndImageContext();
}
```

**Comment by mythodeia** [comment]
@levieggert 
i just tested with an image that has orientation uiimageorientationright and uploaded it to a server online. I tried that image and SDWebImage caches that image and keeps that orientation. The image in memory is still uiimageorientationright and the imageview shows it correctly.
When suspending the app and trying again the lib takes the image from disk like you said and still the image's orientation is right and the imageview shows it correctly.

what i suspect is this:
when you manually cache the image using the ```storeImage:image forKey....``` method the ```recalculate``` property is set to YES whereas when downloading and caching the image automatically the ```recalculate``` is set to NO.
what the ```recalculate``` does is that is reconstructs new data from the current UIImage with this:
```data = UIImageJPEGRepresentation(image, (CGFloat)1.0);``` 
something which strips the EXIF from the image thats why you get the uiimageorientationUp when retrieving it from disk.
can you try and cache the image using this and pass NO for recalculateFromImage.
You should pass the data as well
```
- (void)storeImage:(UIImage *)image recalculateFromImage:(BOOL)recalculate imageData:(NSData *)imageData forKey:(NSString *)key toDisk:(BOOL)toDisk
```
and see if it works for you?

**Comment by levieggert** [comment]
Hey @mythodeia 

Thank you for getting back to me.  I think I see what is going on now.

1. I tested the same flow this time storing the NSData as UIImageJPEGRepresentation and it does keep the orientation RIGHT when retrieving from disk.  

NSData *imageData = UIImageJPEGRepresentation(image, 1.0f);
[imageCache storeImage:image recalculateFromImage:NO imageData:imageData forKey:key toDisk:YES];

2. I also tried storing the NSData as UIImagePNGRepresentation to see what would happen like so.

NSData *imageData = UIImagePNGRepresentation(image);
[imageCache storeImage:image recalculateFromImage:NO imageData:imageData forKey:key toDisk:YES];

This gave me the original results where saving to disk the orientation is RIGHT and retrieving from disk the orientation is UP and my image is rotated -90 degrees CCW.

3. Finally, as a third test I rotated the image 90CW and then stored the image as UIImagePNGRepresentation like so.

NSData *imageData = UIImagePNGRepresentation(image);
[imageCache storeImage:image recalculateFromImage:NO imageData:imageData forKey:key toDisk:YES];

When retrieving the image from disk the orientation is UP, but now since I rotated the image before saving to NSFileManager, the image is correctly rotated.

4. So it seems it comes down to iOS interpreting the image data.  Storing UIImageJPEGRepresentation to NSFileManager will keep the orientation where as UIImagePNGRepresentation will convert the orientation to UP.  So if you want to store NSData to NSFileManager as UIImagePNGRepresentation, be sure to check the orientation before storing the image and apply any rotation as needed.

Does this appear to be the case for you?

Thanks!

**Comment by mythodeia** [comment]
when saving with ```UIImagePNGRepresentation``` the EXIF metadata are stripped. 
SDWebImage checks to see if the original image is a png and then uses the appropriate method to save it to disk.
generally PNG images do not keep orientation info inside as far as i know

**Comment by levieggert** [comment]
Okay makes sense now.

thanks for the help!

**Comment by Sazalak89** [comment]
I am facing same issue with sd_webimage. Need help. I want to make it work normally though image captured in portrait or landscape it should appear in portrait if viewed in portrait and landscape if viewed in landscape.
