### ISSUE TITLE
Cancelling one of downloadings with same URL cause all the callback cancelled

### ISSUE THREAD

**Issue by migrant** [rs/SDWebImage#1113]
I have saveral image views downloading the same image (with the same URL). Before downloading is finished I call `cancel` on one of the views, then all the callbacks for the URL are all removed so all other image views lose its callback.

Does it consider to be a bug ?

**Comment by timkoma** [comment]
Yes, and I have a fix for it in following PR: https://github.com/rs/SDWebImage/pull/1069

**Comment by migrant** [comment]
@timkoma Looks like it has not been merged into master ?

**Comment by bpoplauschi** [comment]
I will be merged, it's just a bigger change which I want to review thoroughly.

**Comment by migrant** [comment]
@bpoplauschi Thank you for that. Looking forward to it.

**Comment by itsthejb** [comment]
Any movement on this? I think we're experiencing some issues with this

**Comment by bpoplauschi** [comment]
Not yet, but we will look to include this fix soon. Not sure when we will release a 4.0 though.

**Comment by dongyu430** [comment]
The same problem occurs

**Comment by bpoplauschi** [comment]
Resolved by #883
