### ISSUE TITLE
Expose NSURLResponse for caching images in UIWebView

### ISSUE THREAD

**Issue by migrant** [rs/SDWebImage#1114]
I use a `NSURLProtocol` to download and cache images in HTML. And I want to download them using SDWebImage. Everything is OK except the need for caching NSURLResponse. SDWebImage stores response in `SDWebImageDownloaderOperation` but it never be used. Could we expose the response so that developer could handle the response ?

**Comment by bpoplauschi** [comment]
Ideally, we shouldn't expose the response as we don't want people messing around with it and probably most users won't care about it. Maybe you should fork the library and make those changes for yourself
