### ISSUE TITLE
Q: Swift?

### ISSUE THREAD

**Issue by szuniverse** [rs/SDWebImage#1116]
Hi

First of all, great work. I use SDWebImage in many projects and works great!
Do you plan to implement this in pure swift? 
I know i can use it via bridging header file but its not so pure.. :)

**Comment by onevcat** [comment]
@szuniverse 
Just open sourced a project call [Kingfisher](https://github.com/onevcat/Kingfisher), it is a simplified "copy" of SDWebImage in pure Swift. But only for iOS 8+ (since I want dynamic framework and cancelable block support).
