### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by troypayne** [rs/SDWebImage#1117]
I can't turn off logging of SDWebImage without modifying the code....

**Comment by mythodeia** [comment]
@troypayne are you talking about the prefetcher?

**Comment by troypayne** [comment]
@mythodeia yes

**Comment by mythodeia** [comment]
check this https://github.com/rs/SDWebImage/pull/1106

**Comment by troypayne** [comment]
Hmm perhaps it works in theory? I tried doing #define SD_LOG_NONE 1 in my bridge.h file (i'm using swift) above my import of the prefetcher and i'm still getting the logs

**Comment by mythodeia** [comment]
i do not know if swift is causing this or not but since the actual logging is taking place in 3 lines i think you can manually comment them for now
