### ISSUE TITLE
Add ability to use the prefetcher with a custom image manager

### ISSUE THREAD

**Issue by tfonfara** [rs/SDWebImage#1118]
Hi,

it would be great if you could change the ```SDWebImagePrefetcher``` init method in a way, that we could use the prefetcher with a custom image manager (compare with #1041)

```
- (id)init {
    if ((self = [super init])) {
        _manager = [self createImageManager];
       ...
    }
    return self;
}

- (SDWebImageManager *)createImageManager {
    return [SDWebImageManager new];
}
```

Thank you,
Tobias

**Comment by mythodeia** [comment]
@tfonfara can [this](https://github.com/rs/SDWebImage/pull/956) be of any assistance

**Comment by tfonfara** [comment]
@mythodeia this is exactly what I'm looking for, but unfortunately it isn't merged yet

**Comment by mythodeia** [comment]
until its merged you can copy paste the code you [need](https://github.com/TENDIGI/SDWebImage/commit/faaa0aabf3a985a1ad431b6fd167c4a8af1d09f4)
luckily its not that big of a change

**Comment by tfonfara** [comment]
Thanks, I've already included the snippet from my 1st post :)
I'll close the issue.
