### ISSUE TITLE
ImageDecoder error

### ISSUE THREAD

**Issue by Janrin** [rs/SDWebImage#1119]
In SDWebImageDecoder.m 
<Error>: CGBitmapContextCreate: unsupported parameter combination: 16 integer bits/component; 64 bits/pixel; 3-component color space; kCGImageAlphaNoneSkipFirst; 960 bytes/row.

**Comment by mythodeia** [comment]
@Janrin was it a warning or a crash?

**Comment by Janrin** [comment]
@mythodeia yes,do you have some way to resolve it?

**Comment by mythodeia** [comment]
no we do not have something concrete yet. Can you try this?
https://github.com/rs/SDWebImage/pull/1015

**Comment by Janrin** [comment]
The hardcode 8 still not work.
CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 32 bits/pixel; 3-component color space; kCGImageAlphaNoneSkipFirst; 480 bytes/row.

**Comment by mythodeia** [comment]
can you share the image that produces the warning?

**Comment by Janrin** [comment]
could be this image
https://cnodejs.org/agent?url=https%3A%2F%2Favatars.githubusercontent.com%2Fu%2F9914235%3Fv%3D3%26s%3D120

**Comment by mythodeia** [comment]
i did not get a warning from that

**Comment by Janrin** [comment]
https://cnodejs.org/agent?url=https%3A%2F%2Favatars.githubusercontent.com%2Fu%2F6581640%3Fv%3D3%26s%3D120

**Comment by Janrin** [comment]
please try the image url above.

**Comment by mythodeia** [comment]
yeap..this one does the trick and throws the warning. until we find a solution for this do not worry about it as it is just a warning

**Comment by mythodeia** [comment]
just a [reference](https://developer.apple.com/library/ios/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/dq_context/dq_context.html#//apple_ref/doc/uid/TP30001066-CH203-BCIBHHBB) for anyone interested

**Comment by mythodeia** [comment]
@Janrin 
can you replace the method 
```
+ (UIImage *)decodedImageWithImage:(UIImage *)image {
```

with the one below and test again?i am seeing the image in my tests now without warnings.
```
+ (UIImage *)decodedImageWithImage:(UIImage *)image {
    if (image.images) {
        // Do not decode animated images
        return image;
    }

    CGImageRef imageRef = image.CGImage;

    CGImageAlphaInfo alpha = CGImageGetAlphaInfo(image.CGImage);
    BOOL anyNonAlpha = (alpha == kCGImageAlphaFirst ||
                      alpha == kCGImageAlphaLast ||
                      alpha == kCGImageAlphaPremultipliedFirst ||
                      alpha == kCGImageAlphaPremultipliedLast);

    if (anyNonAlpha) { return image; }

    size_t width = CGImageGetWidth(imageRef);
    size_t height = CGImageGetHeight(imageRef);

    CGContextRef context = CGBitmapContextCreate(NULL, width,
                                                       height,
                                                       8,
                                                       0,
                                                       CGImageGetColorSpace(imageRef),
                                                       kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedFirst);

    // Draw the image into the context and retrieve the new image, which will now have an alpha layer
    CGContextDrawImage(context, CGRectMake(0, 0, width, height), imageRef);
    CGImageRef imageRefWithAlpha = CGBitmapContextCreateImage(context);
    UIImage *imageWithAlpha = [UIImage imageWithCGImage:imageRefWithAlpha];

    // Clean up
    CGContextRelease(context);
    CGImageRelease(imageRefWithAlpha);

    return imageWithAlpha;
}
```

**Comment by Janrin** [comment]
Thanks,this problem has bean fixed by the code.

**Comment by mythodeia** [comment]
:+1:

**Comment by littledogboy** [comment]
牛逼

**Comment by 1036938520** [comment]
<Error>: CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by ClegeJJ** [comment]
@mythodeia 

still could be this image . Why?
http://tp3.sinaimg.cn/1130677950/50/5653229811/1

**Comment by ClegeJJ** [comment]
@mythodeia 

用了大神的方法。 还是不能加载这张图

http://tp3.sinaimg.cn/1130677950/50/5653229811/1

错误 信息是这样  (Error):

Sep 13 13:45:30 imacdeiMac-33.local WeiBo[3309] <Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 16 bits/pixel; 1-component color space; kCGImageAlphaPremultipliedFirst; 128 bytes/row.
Sep 13 13:45:30 imacdeiMac-33.local WeiBo[3309] <Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Sep 13 13:45:30 imacdeiMac-33.local WeiBo[3309] <Error>: CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Message from debugger: Terminated due to signal 15

**Comment by mythodeia** [comment]
@ClegeJJ download the latest version of this library. i tried the demo project with your url and it works fine

**Comment by ClegeJJ** [comment]
@mythodeia 
:+1: 
Think you very much!!!

**Comment by A1314** [comment]
网络图片资源加载刷新时会出现<Error>: CGBitmapContextCreate: unsupported parameter combination: 16 integer bits/component; 64 bits/pixel; 3-component color space; kCGImageAlphaNoneSkipFirst; 960 bytes/row.
<Error>: CGBitmapContextCreate: unsupported parameter combination: 16 integer bits/component; 64 bits/pixel; 3-component color space; kCGImageAlphaPremultipliedFirst; 1216 bytes/row.
<Error>: CGBitmapContextCreate: unsupported parameter combination: 16 integer bits/component; 64 bits/pixel; 3-component color space; kCGImageAlphaNoneSkipFirst; 1216 bytes/row.
<Error>: ImageIO: CGImageSourceCreateWithData data parameter is nil
大神求解。。。。

**Comment by mythodeia** [comment]
@A1314  please download the latest version of the library and try again
