### ISSUE TITLE
Using SDWebImage to cache MKTileOverlays

### ISSUE THREAD

**Issue by swl367** [rs/SDWebImage#1120]
I currently have a subclassed MKTileOverlay and want to use SDWebImage to cache the tiles. Since MKTileOverlay doesn't have any kind of UIImageView, I have a "temporary" UIImageView that gets alloc'ed before any requests are made. After that, I have the following:

```
- (void)loadTileAtPath:(MKTileOverlayPath)path
                result:(void (^)(NSData *data, NSError *error))result
{
    if (!result) {
        return;
    }
    
    [self.tileTempImageView sd_setImageWithURL:[self URLForTilePath:path] completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        if (error) {
            NSLog(@"error: %@", error);
        }
        NSData *tileData = UIImagePNGRepresentation(image);
        result(tileData, nil);
    }];
}
```
However, not all the tiles are being displayed. On multiple launches, certain tiles (not consistent) are not showing up and just shows the MKMapView GPS map. If I remove this overridden method or replace the SDWebImage code with simple NSUrlRequests, then it works fine and shows all tiles. I don't want to use the latter 2 methods because caching doesn't work.

**Comment by mythodeia** [comment]
@swl367 instead of using a temp image to get the caching working why dont you use the method
```downloadImageWithURL``` from SDWebImageManager 
or even the 
```downloadImageWithURL``` of the ```SDWebImageDownloader```
to get the images & cache them?

did you check if the urls are unique for each tile image?

**Comment by mythodeia** [comment]
closing this. if you need more info please reopen
