### ISSUE TITLE
How to support webp?

### ISSUE THREAD

**Issue by willbin** [rs/SDWebImage#1122]
http://stackoverflow.com/questions/18012527/how-to-load-a-webp-image-with-sdwebimage

This is an answer in stackoverflow, but when I set SD_WEBP=1 ,  some errors founed.

 In UIImage+MultiFormat.m

    #ifdef SD_WEBP
    #import "UIImage+WebP.h"
    #endif
 

ps: I use cocoapods to add SDWebImage.

So please tell me the detail way to support webp in SDWebImage.

**Comment by mythodeia** [comment]
try and clone the repository using ```git clone --recursive https://github.com/rs/SDWebImage.git```
then add the files ```UIImage+WebP.h``` & ```UIImage+WebP.m``` manually in your project

**Comment by willbin** [comment]
Done!

Steps:

### 1: `Clone` and add `WebP.framework`

 clone the repository using `git clone --recursive https://github.com/rs/SDWebImage.git`
 
 add full folder of `SDWebImage` and `WebP.framework` into your project.
 
![image](http://ww1.sinaimg.cn/large/6aa39725gw1er421z43rmj209h0izq54.jpg)




###2: in `Build Settings` -- `Preprocessor Macros` , add `SD_WEBP=1`.

![image](http://ww2.sinaimg.cn/large/6aa39725gw1er421hkyq0j20ld09ujsy.jpg)


ps:If using `CocoaPods`, I don't konw how to add `WebP.framework` into `SDWebImage`, so I choose add files into my project.

@mythodeia Thanks.

**Comment by mythodeia** [comment]
:+1:

**Comment by OlegAnghelov** [comment]
Did we understand correctly that if we want WebP to be supported by SDWebImage, then we should remove the whole SDWebImage from Cocoapods and import it manually?

**Comment by mythodeia** [comment]
@OlegAnghelov i would suggest you start by cloning the repo and then adding the files UIImage+WebP.h & UIImage+WebP.m manually in your project
check if this works first

**Comment by worldligang** [comment]
good job

**Comment by OlegAnghelov** [comment]
@mythodeia 
We tried to follow your advice, but it didn't work. We had issues with SD_WEBP macros.

**Comment by mythodeia** [comment]
Please try the below steps. I just used the demo project and i got the files just fine. 

``` git clone --recursive https://github.com/rs/SDWebImage.git ```
``` pod install inside Tests folder ```
``` open SDWebImage.xcworkspace ```
``` choose WebImage target & build```
``` open derived data and get WebImage.framework ```
``` drag into your project ```
``` #import <WebImage/UIImage+WebP.h> ```

![d](https://cloud.githubusercontent.com/assets/1748458/7699844/70c08ac8-fe23-11e4-8638-be69bef18103.png)
![c](https://cloud.githubusercontent.com/assets/1748458/7699840/6d842914-fe23-11e4-8f6c-44261423ddab.png)
![a](https://cloud.githubusercontent.com/assets/1748458/7699836/68edfeca-fe23-11e4-91f5-682a0b861c32.png)
![b](https://cloud.githubusercontent.com/assets/1748458/7699837/6b36c14e-fe23-11e4-9642-f8d100d06e9d.png)

**Comment by lixiaoyu** [comment]
Anyone can tell me how to get the  WebImage.framework,I take steps as @mythodeia say,but couldn't find the derive data,the  WebImage.framework still shows red,can give me an advice ? pretty thanks! 
![2015-05-21 11 03 21](https://cloud.githubusercontent.com/assets/7939833/7740760/099c30ae-ffa9-11e4-8444-a165223d595b.png)

**Comment by lixiaoyu** [comment]
I gonna it，its path is  ~/Library/Developer/Xcode/DerivedData/<ProjectName>-<gibberish>/Build/Products/...
![2015-05-21 11 55 10](https://cloud.githubusercontent.com/assets/7939833/7741340/42a943a8-ffb0-11e4-802c-7f8aa299b5dc.png)

**Comment by terencezsw** [comment]
@lixiaoyu download it from https://github.com/seanooi/iOS-WebP, use cocoapods or just browse that website and click the "download" button.

**Comment by shiyingyan** [comment]
@mythodeia 
Hello, how to get the WebP.framework. 
I clone the repository, and stepped above . But can`t find the framework. Please tell me.  
Thank you!

**Comment by mythodeia** [comment]
@shiyingyan did you find the derived data folder?

**Comment by shiyingyan** [comment]
@mythodeia 
 Yes, but I just find the WebImage.framework !
how to generate WebP.framework?

**Comment by mythodeia** [comment]
@shiyingyan if you choose the SDWebImage+WebP target you can create the SDWebImage+WebP.framework

**Comment by IvanChan** [comment]
just add webp/decode.h manually to your project is ok.....

**Comment by cr400** [comment]
@willbin @mythodeia @shiyingyan   hello, I clone the repository, and stepped above .but still error #import "webp/decode.h" please help me.thanks

**Comment by cr400** [comment]
ps: i get the webimage.framework not webp.framewokr

**Comment by MR-WXD** [comment]
How to get WebP.framework
