### ISSUE TITLE
Q: Is it possible to download image automatically when no internet connection?

### ISSUE THREAD

**Issue by szuniverse** [rs/SDWebImage#1124]
Hi

use-case:
1. no internet connection, try to download image
2. internet comes back, try to download image automatically again

how can i do this with sdwebImage?

**Comment by mythodeia** [comment]
@szuniverse there is no way to do this with this library. you can however add some code of your own and combine it with SDWebImage to make this work. for example play with the reachability code and when the network status changes you can fire up this lib to download your image.
