### ISSUE TITLE
does not load the image with Russian characters

### ISSUE THREAD

**Issue by runia** [rs/SDWebImage#1126]
This url http://i0.wp.com/www.pure-t.ru/wp-content/uploads/2015/04/ззззз2.png not work for SDWebImage
This url http://i0.wp.com/www.pure-t.ru/wp-content/uploads/2015/04/secret.png work!

How to solve this problem?

**Comment by runia** [comment]
I resolved this problem! 
I use stringEncoding: 
myStringUrl = @"http://i0.wp.com/www.pure-t.ru/wp-content/uploads/2015/04/ззззз2.png";
urlSting = [myStringUrl stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];

**Comment by mythodeia** [comment]
:+1:
