### ISSUE TITLE
setImageWithURL:placeholderImage:completed: not caching to disk.

### ISSUE THREAD

**Issue by harinsa** [rs/SDWebImage#1127]
I am using setImageWithURL:placeholderImage:completed: to load image into my imageView in a table.
Everything time I reopen my application, it will re-download it from the internet, and not cache it to the disk. Someone else also experiencing the same issue [here](http://stackoverflow.com/questions/29649993/sdwebimage-not-caching-to-disk).

I am using it with Swift, installed through cocoapod.

**Comment by mythodeia** [comment]
can you share some code usage?

**Comment by harinsa** [comment]
It seems to be working now after I migrate to Swift 1.2.
