### ISSUE TITLE
placeholderImage is empty, no show network image

### ISSUE THREAD

**Issue by MakeZL** [rs/SDWebImage#1131]
Hey , 
function sd_setImageWithURL: placeholderImage: 
Careless wrong placeholderImageName, The network will not show pictures.

**Comment by mythodeia** [comment]
i used the demo project to add a large image url in the detail view controller and the placeholder image showed correctly while the large image was loading. please beware that several large images from the demo project as not working. Add you own url to test

**Comment by mythodeia** [comment]
closing this. if you find that its still an issue please reopen
