### ISSUE TITLE
Image not re downloading if images are saved with same name.

### ISSUE THREAD

**Issue by shreeshecommstreet** [rs/SDWebImage#1132]
For example, If I have an image abc.png on server. I have cached that image, now up0load a new image with same name. I am still able to see the old image. 

I think caching is happening on the basis on name, or is there any setting that I am missing.

**Comment by mythodeia** [comment]
you could use the ```SDWebImageRefreshCached``` option

**Comment by mythodeia** [comment]
closing this. if you need further assistance please reopen
