### ISSUE TITLE
Is there a way to customize request?

### ISSUE THREAD

**Issue by sainttail** [rs/SDWebImage#1136]
I want to download image from amazon s3 which i need to authorise request, but using UIImageView category from this library I can only set URL

So I need to write a custom code for modify request in `SDWebImageDownloader.m` before init `SDWebImageDownloaderOperation`

Are there any better way than this? like some a method to customise all out going request from sdwebimage

**Comment by mythodeia** [comment]
can [this](http://www.mazdigital.com/blog/post/2014/using-sdwebimage-with-images-on-amazon-s3-a-brief-tutorial-from-maz/) be of any help

**Comment by sainttail** [comment]
Thanks @mythodeia for your feedback

This is based on the old amazon sdk which is gone already and I have some custom progress animation on UIImageView when downloading. So I use [this](https://github.com/AFNetworking/AFAmazonS3Manager/blob/master/AFAmazonS3Manager/AFAmazonS3RequestSerializer.m) instead to authorise request and use callback from SDWebImage to update progress.  

The only problem here is that I need to add those authorize codes in the library itself which is a bit inconvenient. (i need to copy all the SDWebImage files into the project, cannot use pod)

**Comment by mythodeia** [comment]
closing this. if you need further assistance please reopen.
