### ISSUE TITLE
About uploading some images with SDWebImage?

### ISSUE THREAD

**Issue by SpongeBob-GitHub** [rs/SDWebImage#1139]
#1234 If we need to upload some images.

TODO:
Can we make a new class "SDWebImageUploader.h" & "SDWebImageUploader.m". or can we add a category "UIImage+Upload".

with SDImageCache.
Is the enumeration crashing because the files the directory enumerator references are protected? If so, could the clean up method anticipate this and avoid it?

**Comment by mythodeia** [comment]
@SpongeBob-GitHub the sole purpose of this library is to cache files on memory and disk.
By any means you can create a category that uploads files and caches them on completion.
The enumeration should not crash when protected files are found.

**Comment by SpongeBob-GitHub** [comment]
Cache files on memory and disk?
If we should post to the server, and we can ... ?

**Comment by rromanchuk** [comment]
@mythodeia just close, doesn't make sense
