### ISSUE TITLE
Crashes in [SDWebImageDownloaderOperation start] - UITableViewCell

### ISSUE THREAD

**Issue by bkvirendra** [rs/SDWebImage#1152]
I upgraded to SDWebImage 3.7 and Xcode 6.3. And my production app has started crashing like crazy.

I use SDWebImage to render images in UITableView, which has large number of images.

I'm seeing this all over my crash logs on Splunk mint.

Any idea, how I can prevent this.

0	IOKit	IOServiceAddInterestNotification (in IOKit) + 44
1	UIKit	_MatchedBatteries (in UIKit) + 116
2	UIKit	-[UIDevice setBatteryMonitoringEnabled:] (in UIKit) + 208
3	Earthmiles	-[DataFixture appendBaseValues] (in Earthmiles) + 2180
4	Earthmiles	-[DataFixture init] (in Earthmiles) + 80
5	Earthmiles	-[NetworkDataFixture init] (in Earthmiles) + 56
6	Earthmiles	-[SplunkNSURLConnectionDataDelegateInterceptor initAndInterceptFor:withRequest:] (in Earthmiles) + 244
7	Earthmiles	SplunkNSURLConnectionInitWithRequestDelegateStartImmediately (in Earthmiles) + 480
8	Earthmiles	-[SDWebImageDownloaderOperation start] (in Earthmiles) (SDWebImageDownloaderOperation.m:96)
9	Foundation	__NSOQSchedule_f (in Foundation) + 228
10	libdispatch.dylib	_dispatch_client_callout (in libdispatch.dylib) + 16
11	libdispatch.dylib	_dispatch_queue_drain (in libdispatch.dylib) + 1448
12	libdispatch.dylib	_dispatch_queue_invoke (in libdispatch.dylib) + 132
13	libdispatch.dylib	_dispatch_root_queue_drain (in libdispatch.dylib) + 720
14	libdispatch.dylib	_dispatch_worker_thread3 (in libdispatch.dylib) + 108
15	libsystem_pthread.dylib	_pthread_wqthread (in libsystem_pthread.dylib) + 816
16	libsystem_pthread.dylib	start_wqthread (in libsystem_pthread.dylib) + 4

This is my code that renders the images:

// reward is a object 

    SDWebImageManager *manager = [SDWebImageManager sharedManager];

    if (!reward.rewardPictureImage) {
        cell.imgViewReward.image = [UIImage imageNamed:@"rewardsDefault.png"];

        cell.operation = [manager downloadImageWithURL:reward.rewardImage options:SDWebImageLowPriority progress:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
            if (image) {
                // set the image
                cell.imgViewReward.image = image;
                
                // cache image
                reward.rewardPictureImage = image;
            }
        }];
    } else {
        cell.imgViewReward.image = reward.rewardPictureImage;
    }

**Comment by luoyibu** [comment]
Maybe you should show some code in 
```
3 Earthmiles -DataFixture appendBaseValues + 2180
4 Earthmiles -DataFixture init + 80
5 Earthmiles -NetworkDataFixture init + 56
```

**Comment by abhinav-mudgal** [comment]
The same issue replicated on my side as well.
![screen shot 2015-05-19 at 3 12 48 pm](https://cloud.githubusercontent.com/assets/10550081/7700048/9a6a9f92-fe39-11e4-9540-e0ca3fce14b3.png)

**Comment by abhinav-mudgal** [comment]
The same issue replicated on my side as well at -[SDWebImageDownloaderOperation start]
We are facing a BAD_ACCESS here due to some reason :

`self.connection = [[NSURLConnection alloc] initWithRequest:self.request delegate:self startImmediately:NO];`

@luoyibu The DataFixture methods are from SplunkMint itself.

**Comment by bkvirendra** [comment]
@abhinav-mudgal Yes that's correct! That's the line where the issue is raised

**Comment by bkvirendra** [comment]
Any updates?

**Comment by abuzar-amin-confiz** [comment]
@bkvirendra  You are using SDWebImage 3.7, and now latest version of SDWebImage is 4.2.1.

Have you updated SDWebImage to 4.2.1? 
If you updated then, updating the library to 4.2.1 removed your crash?

**Comment by bkvirendra** [comment]
nope! I replaced the SDWebImage library with AFNetworking. It removed that crash. AFNetworking does a good job.

**Comment by abuzar-amin-confiz** [comment]
@bkvirendra This crash was actually due to a bug in Splunk mint library, its not the fault of SDWebImage, Splunk mint reported this issue on their site see this: 
http://docs.splunk.com/Documentation/MintIOSSDK/latest/DevGuide/FixedIssues

So updating the splunk mint had removed the crash from my app.

**Comment by bkvirendra** [comment]
wow thanks!

**Comment by mythodeia** [comment]
so this can be closed then. @abuzar-amin-confiz thanks for the info
