### ISSUE TITLE
SDWebImage.framework 3.7

### ISSUE THREAD

**Issue by instantflashback** [rs/SDWebImage#1155]
Can you create a new .framework file and put it to:
https://github.com/rs/SDWebImage/downloads

Thank you!

**Comment by mythodeia** [comment]
@instantflashback that section is deprecated. You can check the [Releases](https://github.com/rs/SDWebImage/releases) section for downloads.
However for the 3.7 you can build the library using the framework scheme.Check your derived data folder to retrieve the framework.

**Comment by jkblgithub** [comment]
not helpful advice

**Comment by mythodeia** [comment]
@jkblgithub feel free to provide assistance.
