### ISSUE TITLE
Error Domain=SDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels" 

### ISSUE THREAD

**Issue by newdev7** [rs/SDWebImage#1156]
In SDWebImage version 3.7.2, I'm using the following method to download and place the image in table view asynchronously.

`- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage*)placeholder options:(SDWebImageOptions)options progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageCompletionBlock)completedBlock { }`

This method works for almost every url but for some urls. 
In the progressBlock it shows the download progress, but after downloading the image in the completedBlock it displays the following error :

**Error Domain=SDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels" UserInfo=0x146d1490 {NSLocalizedDescription=Downloaded image has 0 pixels}**

If you want to recreate the error, just use the following image url to download the image using the above method.

https://ksr-ugc.imgix.net/assets/003/823/411/a7d63ce297214cca39dc1b8396774798_original.jpg?v=1432070055&w=700&h=&fit=max&auto=format&q=92&s=1a635ee6e80b293e51b14bef53258514

Thanks.

**Comment by mythodeia** [comment]
the image is just fine. open the demo project and remove all other images.
add this url and test. you will see that it loads just fine

**Comment by newdev7** [comment]
@mythodeia

As you told, I used the demo project to troubleshoot the issue. I removed all the other urls and just run it with that one url. Also tried to download the image with different methods. But here also I received the same error in log. I received the same error for all the image url I got from the Kickstarter website. Some other urls also received the same error such as

http://i2.wp.com/venturebeat.com/wp-content/uploads/2015/05/charger-Piq-04.jpg?resize=160%2C140

http://i0.wp.com/venturebeat.com/wp-content/uploads/2013/12/airplane-jet-clouds-flight-shutterstock-kamenetskiy-konstantin.jpg?resize=160%2C140

Check out the screenshot

![screen shot 2015-05-22 at 2 55 14 pm](https://cloud.githubusercontent.com/assets/12545377/7767827/45220dac-0093-11e5-87f8-b7929ca130f8.png)

**Comment by indiandragon** [comment]
I can confirm @newdev7  that it happens in my setup too especially for Kickstarter images and few other sites.

**Comment by mythodeia** [comment]
i added all 3 urls and got no warnings at all when testing in simulator.
![screena](https://cloud.githubusercontent.com/assets/1748458/7768375/17ed89f2-0083-11e5-9b58-362e41d02c7e.png)
![screenb](https://cloud.githubusercontent.com/assets/1748458/7768382/223914a8-0083-11e5-9552-eebc9ab0de04.png)

**Comment by halpz** [comment]
This is not solved!

**Comment by HKH01** [comment]
I also meet the same problem: it works fine in simulator, but not in iPhone. @newdev7 @newdev7
