### ISSUE TITLE
URLs with trailing parameters get assigned an incorrect image scale value

### ISSUE THREAD

**Issue by akmarinov** [rs/SDWebImage#1157]
Hey,

Some URLs use parameters to indicate things like the version of the image.
As seen in this example of how CloudFront handles versioning of images

https://d1nqp51vi4zttr.cloudfront.net/008759-000001-171@2x.jpg?v=1431437703

The current code in SDWebImage looks at the last 3 or 4 characters for "@2x", which causes images that have these parameters to be incorrectly assigned a scale value of 1x.

I've submitted a PR (https://github.com/rs/SDWebImage/pull/1158), that looks for "@2x.", which might not be ideal, but does the right thing.
I was thinking that we could maybe do a regex validation, instead. 
What do you guys think?

**Comment by bpoplauschi** [comment]
Fixed by #1158
