### ISSUE TITLE
Calling setOperationClass crashes the App

### ISSUE THREAD

**Issue by amberaggarwal** [rs/SDWebImage#1160]
Team,

We are using SDWebImage 3.7.2, We want to use a class derived from SDWebImageDownloaderOperation to perform image downloads. So in order to do this we written following code where we are changing the Operation Class used by Image Downloader.

    SDWebImageDownloader *manager = [SDWebImageManager sharedManager].imageDownloader;
    [manager setOperationClass:[TestSavoDownloadOperation class]];

But this crashes our app with the following information in the debug window.

2015-05-26 15:39:14.871 SAVO[1364:60b] -[SDWebImageDownloader setOperationClass:]: unrecognized selector sent to instance 0x15589460
2015-05-26 15:39:14.874 SAVO[1364:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SDWebImageDownloader setOperationClass:]: unrecognized selector sent to instance 0x15589460'

Any idea why this is happening. 

Thanks in Advance
Amber Aggarwal

**Comment by mythodeia** [comment]
Is your TestSavoDownloadOperation a subclass of SDWebImageDownloader?
Does your custom subclass override this:
```
- (id)initWithRequest:(NSURLRequest *)request
              options:(SDWebImageDownloaderOptions)options
             progress:(SDWebImageDownloaderProgressBlock)progressBlock
            completed:(SDWebImageDownloaderCompletedBlock)completedBlock
            cancelled:(SDWebImageNoParamsBlock)cancelBlock 
```

**Comment by amberaggarwal** [comment]
TestSavoDownloadOperation is derived from SDWebImageDownloaderOperation.

**Comment by mythodeia** [comment]
just tried that using a custom subclass and its working fine.

```
SDWebImageDownloader *manager = [SDWebImageDownloader sharedDownloader];
[manager setOperationClass:[TestImageDownloaderOperation class]];
```

TestImageDownloaderOperation.h file
```
#import <SDWebImage/SDWebImageDownloaderOperation.h>
@interface TestImageDownloaderOperation : SDWebImageDownloaderOperation
@end
```
TestImageDownloaderOperation.m file

```
#import "TestImageDownloaderOperation.h"

@implementation TestImageDownloaderOperation

-(id)initWithRequest:(NSURLRequest *)request options:(SDWebImageDownloaderOptions)options progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageDownloaderCompletedBlock)completedBlock cancelled:(SDWebImageNoParamsBlock)cancelBlock{
 // your own custom code
}

- (void)done {
    NSLog(@"111");
}
@end
```
