### ISSUE TITLE
How to use SDWebImage to cache images in different network status?

### ISSUE THREAD

**Issue by xuyouyang** [rs/SDWebImage#1162]
We now face a tough problem that is how to cache images in different network status. For example, when I use WIFI the image url is "http://xxx.image.jpg?quality=85" and SDWebImage help us to cache it. But when I change the network status to 2G/3G, the same image url maybe is "http://xxx.image.jpg?quality=60". In order to reduce the traffic, I want to display the image cached in WIFI status. How can I use SDWebImage to solve this problem? Thank you very much!!

**Comment by mythodeia** [comment]
the way this library works is by using the url of the image as a key to track the actual cached image.
if you know the url of the wifi cached image before-hand then load that image as a placeholder in the 
```sd_setImageWithURL``` method. this way you will show the cached image while the other one is loading.
