### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by rex-remind101** [rs/SDWebImage#1165]
There was a recent merge to make app extensions safe. Would greatly appreciate it if a new release was tagged that includes this addition, thanks :)

**Comment by mythodeia** [comment]
something like [this](https://github.com/rs/SDWebImage/pull/1085) ?

**Comment by rex-remind101** [comment]
Yes, but the latest tagged release is `3.7.2` which does not include this PR.

**Comment by weibel** [comment]
+1 because of the recent support for system memory notifications

**Comment by cherishloveyou** [comment]
is SDWebImage will die?  there is less activity.

**Comment by kautaleksei** [comment]
Please update cocoapods to latest commit.
I have bug with current cocoapods version 3.7.2, and I tested your example and it's working.
When I set: pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git', :branch => 'master' 
still not working for me.
I don't want to include SDWebImage project manually without cocoapods.

**Comment by kautaleksei** [comment]
I made a tests: installed Cocoapods v. 3.7.2 to your Example project and it's not working with webp files (http://www.ioncannon.net/wp-content/uploads/2011/06/test2.webp and other).
So issue with Cocoapod v. 3.7.2: https://github.com/CocoaPods/Specs/blob/master/Specs/SDWebImage/3.7.2/SDWebImage.podspec.json
Can somebody look to it?

**Comment by kautaleksei** [comment]
I think I understand why I have issues with webp images.
By default: pod 'SDWebImage' doesn't set up WebP support. We need to add this dependencies: pod 'SDWebImage/WebP' to Podfile. Now it's working in v. 3.7.2.
In the documentation we don't have anything related to it.

**Comment by bpoplauschi** [comment]
Just released version 3.7.3. Closing.
