### ISSUE TITLE
Why install by pod 'SDWebImage',  pods SDWebImage's dir don't contain four following files?

### ISSUE THREAD

**Issue by lengmolehongyan** [rs/SDWebImage#1170]
Why install by pod 'SDWebImage',  pods SDWebImage's dir dosen't contain four following files?
'MKAnnotationView+WebCache'(h/m), 'UIImage+WebP'(h/m).
However, I download the Zip file, the four files is contained.

**Comment by mythodeia** [comment]
@lengmolehongyan if you clone the repository, then do a pod install in the tests folder and then open the SDWebImage.xcworkspace you will see that all 4 files you mention are there. Can you try that ?
Or am i missing something else?

**Comment by bpoplauschi** [comment]
Those files are contained in different subspecs (`MapKit` and `WebP`). To get those, you need to specify in the Podfile something like `pod 'SDWebImage/MapKit'`
