### ISSUE TITLE
Why sd_imageWithWebPData cost too much time?

### ISSUE THREAD

**Issue by willbin** [rs/SDWebImage#1171]
In file `UIImage+WebP.h`, 

function: `+ (UIImage *)sd_imageWithWebPData:(NSData *)data`

	if (WebPDecode(data.bytes, data.length, &config) != VP8_STATUS_OK) {
        return nil;
    }

My image size is  600*4000 in `webp` format,  and filesize is about 200k.

But when reading from dis cache with SDWebImage,  `WebPDecode()` cost almost 1.5s-2.0s.

Is this normal?

Thanks for any tips.

**Comment by weibel** [comment]
In my experience encoding/decoding WebP images using libwebp can be very CPU intensive. Try playing a bit with the decoding parameters to see if you can gain any performance. See https://developers.google.com/speed/webp/docs/api#advanced_decoding_api

**Comment by willbin** [comment]
@weibel  I have tested some decode parameters, and make the decode time a little shorter from 1.5s to about 1.0s.

But now I found something weird that when my app launch, the decode speed is fast, and after some time, the decode speed slow down.
 
Why does this happen, and how to make is fater?

**Comment by weibel** [comment]
It's difficult for me to say what happens in your case, but try asking in the webp group https://groups.google.com/a/webmproject.org/forum/#!forum/webp-discuss

**Comment by mythodeia** [comment]
thanks @weibel 
i think this can be transferred in the google groups forum as stated above. If anyone finds something interesting please share
