### ISSUE TITLE
Crash on UIImage+MultiFormat.m line 51 

### ISSUE THREAD

**Issue by mohammad19991** [rs/SDWebImage#1172]
+[UIImage(MultiFormat) sd_imageOrientationFromImageData:]

UIImage+MultiFormat.m line 34
+[UIImage(MultiFormat) sd_imageWithData:]

SDImageCache.m line 270
-[SDImageCache diskImageForKey:]

SDImageCache.m line 310
__42-[SDImageCache queryDiskCacheForKey:done:]_block_invoke

![screen shot 2015-06-09 at 3 49 26 pm](https://cloud.githubusercontent.com/assets/2028141/8058043/26d9e6a0-0ebf-11e5-90f7-2cbf8de18e37.png)

**Comment by mythodeia** [comment]
closing this...continue here https://github.com/rs/SDWebImage/issues/1154
