### ISSUE TITLE
DDCache: mmap failed with error 12

### ISSUE THREAD

**Issue by DanisFabric** [rs/SDWebImage#1174]
I use sd_setImageWithURL in UITableViewCell. when I scroll to bottom load more cells. Xcode log 
DDCache: mmap failed with error 12
DataDetectorsCore: mmapping the cache file failed

And in the last app crashed because of EXC_BAD_ACCESS in the line 
- (UIImage *)imageFromMemoryCacheForKey:(NSString *)key {
    return [self.memCache objectForKey:key];
}

**Comment by mythodeia** [comment]
how large are the images you download/cache?

**Comment by DanisFabric** [comment]
My device download 90 images, about 50kb per image

**Comment by mythodeia** [comment]
add your images in the demo project that comes with this library so you can check if the issue still persists. if yes then we need to check the images. if not then there is something wrong with your project's code

**Comment by DanisFabric** [comment]
thank you, let me have a try 😄

**Comment by mythodeia** [comment]
@DanisFabric any updates on this?

**Comment by DanisFabric** [comment]
There is no bugs in my demo project. I'm trying to fix my code in my project. thank u so much ! @mythodeia

**Comment by mythodeia** [comment]
good luck :+1:
