### ISSUE TITLE
What does _downloadQueue.maxConcurrentOperationCount do?

### ISSUE THREAD

**Issue by mmjuns** [rs/SDWebImage#1179]
I am developing an app which uses the SDWebImage lib. I met a strange problem. For example, I have six images to download using SDWebImageManager's downloadWithURL function. However, I only get two images displayed. No matter how I refresh the view, I cannot get more image downloaded. I found a variable named maxConcurrentOperationCount in SDWebImageDownloader and found its value is set as 2. I know this value is the capacity of the concurrent queue. Just wondering if this means the lib will only download two images at a time or it just means the lib will only deal with two downloads simultaneously and finally will still download all images (each download will call the downloadImageWithURL:options:progress:completed: once.)

**Comment by mythodeia** [comment]
@mmjuns not its not a but. the number show the max concurrent operations at any given time. check the sample code. it words just fine. i think there is an issue with your project.

**Comment by mmjuns** [comment]
@mythodeia 
You are correct. I tested the latest version and it works fine. Since the project is not written by me, I just want to confirm my guess is right. Thanks.
