### ISSUE TITLE
Parse issue expected ')'

### ISSUE THREAD

**Issue by justinbeatz** [rs/SDWebImage#1180]
Hi, I installed via cocoapods and when building I'm getting this weird error:

![screen](https://cloud.githubusercontent.com/assets/4844146/8164648/6cf66eb8-1358-11e5-8c1e-ceac26b88c71.jpg)

I'm using the latest Xcode 6.3.2 targeting iOS 8.3

**Comment by mythodeia** [comment]
can you try installing in an empty project and reply back?

**Comment by justinbeatz** [comment]
I made a new project and added via cocoapods and build without any issue.

**Comment by mythodeia** [comment]
then please check your project as the problem might be there.
