### ISSUE TITLE
After upgrade the mac system to the new EI Capitan beta version, no effect

### ISSUE THREAD

**Issue by alwaystrong** [rs/SDWebImage#1181]
After upgrade the mac system to the new EI Capitan beta version,  sd_setImageWithURL has no effect。
Anyone who knows?
code：
        var imageUrl = "http://img0.imgtn.bdimg.com/it/u=4034231403,1124015911&fm=23&gp=0.jpg"
        var placehoder = UIImage(named: "avatar_default")
        self.iconView.sd_setImageWithURL(NSURL(string: imageUrl), placeholderImage: placehoder);

**Comment by mythodeia** [comment]
@alwaystrong  what do you mean it has no effect? Can you try the demo project? Does it work there?

**Comment by alwaystrong** [comment]
@mythodeia The demo project have errors：

clang: error: no such file or directory: '/Users/wangfq/Downloads/SDWebImage-3.7.2/Vendors/libwebp/src/dsp/upsampling_sse2.c'
clang: error: no input files

clang: error: no such file or directory: '/Users/wangfq/Downloads/SDWebImage-master/Vendors/libwebp/src/utils/utils.c'
clang: error: no input files

I use the Xcode 6.3.1 or Xcode 7

**Comment by mythodeia** [comment]
the error comes from a missing file in the libwebp library.
Please remove the target thats causing the issue and then add the libSDWebImage.a as a link binary to the demo project. then try again. i have compile successfully but i cannot test as i have not upgraded to El Capitan.

**Comment by mythodeia** [comment]
@alwaystrong any updates on this?

**Comment by alwaystrong** [comment]
@mythodeia I hava find the reason today。That's because there's a "," in the URL("http://img0.imgtn.bdimg.com/it/u=4034231403,1124015911&fm=23&gp=0.jpg)。

Thanks a lot for help!

**Comment by mythodeia** [comment]
:+1:

**Comment by alwaystrong** [comment]
@mythodeia It's so hard to find it。The safari is so strong to load it out。
Thank you anyway.
