### ISSUE TITLE
Error Domain=SDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels"

### ISSUE THREAD

**Issue by WizzzI** [rs/SDWebImage#1183]
In SDWebImage version 3.7.2, I'm using the method: 
```
- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage*)placeholder options:(SDWebImageOptions)options progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageCompletionBlock)completedBlock { } 
```

In the progressBlock shows the download progress, but in the completedBlock the following error :

Error Domain=SDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels" UserInfo=0x146d1490 {NSLocalizedDescription=Downloaded image has 0 pixels}

Demo project:
```
    NSURL *url = [NSURL URLWithString:@"http://i0.wp.com/nmm-izhevsk.ru/wp-content/uploads/2015/06/Olga.jpg?resize=200%2C300"];
    [_imageView sd_setImageWithURL:url
            placeholderImage:nil
                     options:SDWebImageHighPriority
                    progress:^(NSInteger receivedSize, NSInteger expectedSize) {
                        NSLog(@"%li / %li", (long)receivedSize, (long)expectedSize);
                    }
                   completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                       if(image) {
                           
                       }
                   }];
```

**Comment by mythodeia** [comment]
that image is of type image/webp and i think its what causing the issues as the code does not go through the correct if statement to use ```sd_imageWithWebPData```
i will investigate further later on

**Comment by mythodeia** [comment]
have you installed through cocoapods or by dragging the files in your app?
i made a custom demo project and i added the files in my app plus the ones inside the libwebp folder.
now the image shows just fine

**Comment by WizzzI** [comment]
installed through cocoapods

**Comment by mythodeia** [comment]
make sure the uiimage+webp.h/m files and the files inside libwebp/src folder are included in your projects

**Comment by luangaolei** [comment]
After pod 'SDWebImage/WebP', WebP is still not loaded in the project. Is there any additional configuration required?

SDWebImage (4.4.3)
Libwebp (0.6.1)

**Comment by luangaolei** [comment]
@mythodeia hi, After pod 'SDWebImage/WebP', WebP is still not loaded in the project. Is there any additional configuration required?

SDWebImage (4.4.3)
Libwebp (0.6.1)

**Comment by kinarob** [comment]
@luangaolei Would you mind providing a URL for a picture of `Webp`?

**Comment by luangaolei** [comment]
http://feed.youshu.cc/readwith/media/picture/5c47e69a6ffb4.png?x-oss-process=image/format,webp @kinarob

**Comment by Mina-Gerges-BBN** [comment]
I have the same issue with that url  http://minamira.zvendo.online/store/web/media/image/test181223store/store/fcfd6676ff37c1fa53d5d2b4530680ad.svg
I'm using  SDWebImage (5.0.1) & Swift (5.0)

**Comment by dreampiggy** [comment]
@Mina-Gerges-BBN Add [SDWebImageSVGCoder](https://github.com/SDWebImage/SDWebImageSVGCoder) into your coder plugin list, do this in `AppDelegate.m`. And then re-request the SVG format.

**Comment by AbanoubNabil** [comment]
same issue here for url "https://www.youtube.com/embed/y6tjzBh9fWc/0.jpg"

**Comment by dreampiggy** [comment]
> https://www.youtube.com/embed/y6tjzBh9fWc/0.jpg

It's a HTML, not image.

```
curl -O https://www.youtube.com/embed/y6tjzBh9fWc/0.jpg
file 0.jpg
0.jpg: HTML document text, ASCII text, with very long lines
```

**Comment by sssbohdan** [comment]
@AbanoubNabil @dreampiggy Are you guys were able to solve this?
