### ISSUE TITLE
Download the picture incomplete,help me

### ISSUE THREAD

**Issue by fjhfjhfjh** [rs/SDWebImage#1184]
Hi, I am very fond of SDWebImage, but a problem that bothers me is when the network is not good, picture download is not complete, but call success callback, I don't know how to deal with, can you help me?

**Comment by mythodeia** [comment]
why dont you reload that request again to show the complete image? I will close this as it does not seem to be a problem with the library.

**Comment by fjhfjhfjh** [comment]
No detection to determine the picture is complete, because the call is download successfully callback

**Comment by fjhfjhfjh** [comment]
Download has been successful, how do I know whether the picture is complete, the situation is, the picture only shows part of the

**Comment by mythodeia** [comment]
if there is an error while you download the file the request will stop and the image will be nil.
can you check the completion block if the image is nil or not and whether there is an error there as well?
if you still get no errors and the image is not nil then remove the SDWebImageProgressiveDownload from your options and try again. this way the image will show only when its complete
