### ISSUE TITLE
image shows up twice, once in the right cell and once in the wrong one

### ISSUE THREAD

**Issue by genaks** [rs/SDWebImage#1191]
I have a TableView where some of the cells might have an image and some of them might not. My problem could perhaps get solved if I remove the image view from the cell but I just got curious as to why it started showing an image in a cell which was supposed to have no image.

cellForRowAtIndexPath method in my TableView Class

    if(![urlString isEqualToString:@""])
    {
    //[cell.imageView sd_setImageWithURL:[NSURL URLWithString:urlString]
                     //placeholderImage:objimage];
        UIImageView *addImage = [[UIImageView alloc] init];
        [addImage sd_setImageWithURL:[NSURL URLWithString:urlString] placeholderImage:[UIImage imageNamed:@"placeholder.png"]];
        [addImage setFrame:CGRectMake((screenWidth-300)/2, 35, 300, 300)];
        [cell.contentView addSubview:addImage];
        [cell setIndentationLevel:8];
    }
    
    [cell updateWithC:[sArray objectAtIndex:indexPath.row]];
    return cell;

 I am using the updateWithC to get the data of the corresponding cell from my custom TableViewCell. At first I was downloading the images in the TableViewCell Class as well but now I am doing it here in my TableView. The problem is that at the moment only the first cell in my TableView is supposed to have an image and the rest are empty, but for some reason it is showing the image from cell 1 in cell 4 as well.

I discovered this method yesterday only and I'm still pretty new to it so it is quite possible that I'm doing something wrong. Any help is appreciated.

**Comment by mythodeia** [comment]
@genaks your problem sounds like a cell-reuse issue. Are you sure you reuse your cells correctly?

**Comment by genaks** [comment]
I hope so.. I'll check and let you know

**Comment by genaks** [comment]
Cell identifier has been defined like - #define CELL_IDENTIFIER @"solutionCell"

and the code for cell-reuse

CSTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CELL_IDENTIFIER];
    cell.cellDelegate = self;
    if (!cell) {
        cell = [[CSTableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:CELL_IDENTIFIER];
        cell.selectionStyle = UITableViewCellSelectionStyleNone;
    }

**Comment by mythodeia** [comment]
try to replicate it in the demo project please. Also make sure you have preparetoreuse method in your cell and there you should empty your imageview's image.

**Comment by genaks** [comment]
Ok.. Demo project.. Thanks
Oh and I have the prepareToReuse method in my cell and I am emptying my imageView there.
I'll look into it.. Thanks for your help

**Comment by mlijin9011** [comment]
I empty the imageview in method prepareReuse, but it does not work.The image is still not correct used sd_setImageWithURL when the network is not good.
