### ISSUE TITLE
WatchKit Framework Support 

### ISSUE THREAD

**Issue by bassrock** [rs/SDWebImage#1192]
With WatchKit 2.0, there is a new WatchFramework type like iOS and Mac. It would be cool to see a framework for it as well.

**Comment by bpoplauschi** [comment]
Could you or someone else help by implementing this?

**Comment by bassrock** [comment]
Been looking into this, currently looking at the best practices to do this.

**Comment by bassrock** [comment]
Would be happy to support it but am unsure what the current state in the iOS world is to support this in the same codebase.

**Comment by bassrock** [comment]
So in order for this to work it requires #823 as only NSURLSession is available on watchOS. As for the framework, it requires creating a second Framework target and adding a preprocessor macro to define WatchKit, from there it is just adding preprocessor ifs in the code. Which is easy, except that it requires NSURLSession.

**Comment by bpoplauschi** [comment]
I am planing to do some refactoring in 4.0 that will involve integrating AFNetworking as network component, so we will gain access to their NSURLSession component. I will let you know as soon as we have that in place.

**Comment by bpoplauschi** [comment]
Just merged the `watchOS` support into the [4.x](https://github.com/rs/SDWebImage/tree/4.x) branch. Will definitely be included in the next release. In the meantime, you can take it from there and see if it works for you - please note that is in-progress work which breaks compatibility with the older versions of SDWebImage.
