### ISSUE TITLE
when I use the method  to load web iamge,then the iamge  allways is placeholder.  

### ISSUE THREAD

**Issue by starmier** [rs/SDWebImage#1194]
The method is 
 - (void)setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options success:(SDWebImageSuccessBlock)success failure:(SDWebImageFailureBlock)failure;  

With debug ,I find that  if the length  of imageData  when connection is finished , the image will not be changed , and allways be placeholder.

I solve it as follows; I want to know if has other method to solve this kind of situation. Thanks.
```
- (void)connectionDidFinishLoading:(NSURLConnection *)aConnection
{
    self.connection = nil;
    [[NSNotificationCenter defaultCenter] postNotificationName:SDWebImageDownloadStopNotification object:nil];
    if ([delegate respondsToSelector:@selector(imageDownloaderDidFinish:)])
    {
        [delegate performSelector:@selector(imageDownloaderDidFinish:) withObject:self];
    }

    if ([delegate respondsToSelector:@selector(imageDownloader:didFinishWithImage:)])
   {
        if (imageData.length == 0) {
            if ([delegate respondsToSelector:@selector(imageDownloader:didFailWithError:)])
            {
                [delegate performSelector:@selector(imageDownloader:didFailWithError:) withObject:self withObject:nil];
            }
           self.connection = nil;
            self.imageData = nil;
        }

        UIImage *image = SDScaledImageForPath(url.absoluteString, imageData);

        [[SDWebImageDecoder sharedImageDecoder] decodeImage:image withDelegate:self userInfo:nil];

    }

}
```

**Comment by mythodeia** [comment]
@starmier i cannot see this code in the library. What version are you using? Please try with the latest build

**Comment by mythodeia** [comment]
i will close this for now. please use the latest build and try again. if you still encounter issues please reopen
