### ISSUE TITLE
Images are not loaded on iOS9 when compiled with XCode7

### ISSUE THREAD

**Issue by stasix** [rs/SDWebImage#1195]
using beta2 of iOS9 and XCode7.

When compiled for iOS8 target from XCode6, the images load fine.

**Comment by mythodeia** [comment]
do you get any errors? Does the code pass by the completion block ?
maybe [this](http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/) has to do with it if you are solely targeting IOS 9. really i haven't had time to install the beta yet

**Comment by stasix** [comment]
@mythodeia thanks for the link. It has fixed the issue on iOS9.

**Comment by mythodeia** [comment]
:+1:

**Comment by ignaciov** [comment]
I had the same problem and the link also fixed the issue for iOS 9

**Comment by aqavi-paracha** [comment]
(y)
