### ISSUE TITLE
I want to download the images with out loading in to the uiimageview 

### ISSUE THREAD

**Issue by maheshm504** [rs/SDWebImage#1197]
Is there a possibility to download the images with out loading in to the uiimageview i mean when i go to the detail screen image is downloading so after open the 10 records (detail screen) then those images will downloaded so i want to download the images as a cache and load in to the imageview like a key 

so is there a possibility

**Comment by mythodeia** [comment]
you can use the prefetcher to download an array of images without attaching them to imageviews

**Comment by maheshm504** [comment]
please give me the code or referal link it can help me thanks for reply
ᐧ

**Comment by mythodeia** [comment]
see my post above for sample code

**Comment by maheshm504** [comment]
Okay got it i will try it now

ᐧ

**Comment by maheshm504** [comment]
[[SDWebImagePrefetcher sharedImagePrefetcher] prefetchURLs:[fetchArray valueForKey:@"backImage"]];

I given this in viewWillAppear does this effect in any case and is this downloads every time or only one time

**Comment by maheshm504** [comment]
every time view will appear it is working like this

Prefetched 1 out of 120
Prefetched 2 out of 120
Prefetched 3 out of 120
Prefetched 4 out of 120
Prefetched 5 out of 120
Prefetched 6 out of 120

i like this one but every time it is calling so does this effect

**Comment by mythodeia** [comment]
it will try and prefetch every time. you should do this once. or you could check which images exists in cache and prefetch the the ones that do not

**Comment by maheshm504** [comment]
Great this was really help full thanks so much

**Comment by mythodeia** [comment]
:+1:

**Comment by maheshm504** [comment]
so after giving that line and in the cellforrowatindexpath

can i give like this

[backgroundImage setImageWithURL:_backImageURL placeholderImage:placeHolder usingActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];

**Comment by mythodeia** [comment]
you should not prefetch while in ```cellforrowatindexpath```.
but if you have already prefetched images in another view or in your viewdidload then in your cellforrowatindexpath you could ask for that image directly from the cache and if its not there the use the setImageWithURL method

**Comment by maheshm504** [comment]
yes i understand 
i given this in viewWillAppear
[[SDWebImagePrefetcher sharedImagePrefetcher] prefetchURLs:[fetchArray valueForKey:@"backImage"]];

and in cellforatindexpath

[cell.mainImage setImageWithURL:[NSURL URLWithString:[deal frontImage]] placeholderImage:placeHolder usingActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];

so this is enough right ?

**Comment by mythodeia** [comment]
it does not work exactly like that. Because when you load your view the prefetch will not have finished downloading the images for the tableview to show. 
you can use the setImageWithURL method directly without prefetching anything. This will download and cache the image for you. You will not need to use prefetch at all

**Comment by maheshm504** [comment]
Okay i will check this thanks for help it was really helpfull

**Comment by maheshm504** [comment]
Hi i understand what you are saying i can give setImageWithURL for cell for row at index path
I have done this

But why i want the prefetch is for Detail Screen when user opens the detail screen i dont want user to see the image is downloading so i want to download the images in the main screen itself so now tell me this prefetcher will help me or not ?

**Comment by mythodeia** [comment]
the prefetcher will help but you need to put it in another screen and not in the screen where the tableview is already downloading images to show while scrolling.

**Comment by maheshm504** [comment]
Okay then i can give this in tableview cellforrow

[cell.mainImage setImageWithURL:[NSURL URLWithString:[deal frontImage]] placeholderImage:placeHolder usingActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];

**Comment by maheshm504** [comment]
and this in detailScreen viewWill appear and give this line for showing image
//viewDidLoad
  [backgroundImage sd_setImageWithURL:_backImageURL];
//viewWillAppear
[[SDWebImagePrefetcher sharedImagePrefetcher] prefetchURLs:[fetchArray valueForKey:@"backImage"]];

**Comment by mythodeia** [comment]
you said you want the user to be able to see the image without waiting for it to download. if you put the prefetcher in the viewwillappear and the sd_setImageWithURL in the viewdidload it might cancel eachother out. 
The prefetch should happen in another view. not in the detail screen or the thumb screen in my opinion.
Then in the detail view you can use the sd_setImageWithURL to get the already downloaded image.
thats all.

**Comment by maheshm504** [comment]
[[SDWebImagePrefetcher sharedImagePrefetcher] prefetchURLs:[fetchArray valueForKey:@"backImage"]];
this line i given in the viewWillAppear (MAIN SCREEN or MAIN CLASS)
 so even though user not opens the detail screen images are prefetching

and 

[backgroundImage sd_setImageWithURL:_backImageURL];
this line in viewDidLoad(MAINSCREEN  or MAIN TABLE CLASS)

**Comment by maheshm504** [comment]
MAIN CLASS --- > DETAIL CLASS

in MAIN  CLASS ==== viewWillAppear

this line 

[[SDWebImagePrefetcher sharedImagePrefetcher] prefetchURLs:[fetchArray valueForKey:@"backImage"]];

in DETAIL CLASS === viewDidLoad

[backgroundImage sd_setImageWithURL:_backImageURL];

this is working

**Comment by mythodeia** [comment]
ok..but the prefetcher should not be on the same view as your tableview.

**Comment by maheshm504** [comment]
in tableView cellForRow 

i given 

[cell.mainImage setImageWithURL:[NSURL URLWithString:[deal frontImage]] placeholderImage:placeHolder usingActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];

**Comment by mythodeia** [comment]
ok then you are all set

**Comment by maheshm504** [comment]
So now i understand one thing that i am downloading images (frontimage and backimage) in two types

frontimage == > setimageWithURL
backimage == > prefetcher

this is right ?

**Comment by mythodeia** [comment]
i think we have analysed this a lot. what i would do is this:
use the prefetcher somewhere besides the tableview(thumbs) and the detail view(full image).
then in both those views you can use the setimageWithURL to get the cached image

**Comment by maheshm504** [comment]
I understand but i am doing lot of stuff in my class in the first installation of application 150 records are downloading from the JSON and storing to the Core Data and once download finished then am calling one method there i am fetching the images array and i am prefetching the images so 

am confused what to do

**Comment by maheshm504** [comment]
how can i check if the image is not present in imageView  so that i can call again to download the image

**Comment by mythodeia** [comment]
you can check if the image exists in cache and if not then try to download it again. check the ```SDImageCache.h``` for more info

**Comment by maheshm504** [comment]
Okay thanks
