### ISSUE TITLE
crash on -[SDWebImageDownloaderOperation connectionDidFinishLoading:] 

### ISSUE THREAD

**Issue by afantree** [rs/SDWebImage#1198]
I found in the project of our company .
I guess that the data has been changed to NSString type when URI is bad ? 
Whether we want to assert the type ?
The following is the information:
HardwareModel：   iPhone5,2
OS_Version:     iPhone OS 8.3 (12F70)

![qq20150626-2 2x](https://cloud.githubusercontent.com/assets/3734851/8374376/7c7d53a6-1c27-11e5-83da-8407bb3f7524.png)

**Comment by iMinder** [comment]
I hava the same problem

**Comment by todaylover** [comment]
same issue

**Comment by bpoplauschi** [comment]
Looks like a duplicate

**Comment by swizzersweet** [comment]
Also happening to me,
Happens on iphone 6 simulator @ iOS 8.4 as well as device iPhone 6 @ iOS 8.3

**Comment by zhgw01** [comment]
We have similar issue but due to object over release which also happen in connectionDidFinishLoading

![3cc0e144-c54f-46e5-bd62-27480a0c31d2](https://cloud.githubusercontent.com/assets/1620435/18656785/dc341fba-7f26-11e6-811c-af0b4cab96b6.png)

**Comment by anywayfly** [comment]
i have the same problem

**Comment by bpoplauschi** [comment]
Let's close this issue, see if it happens again with 4.0.0 (4.0.0-beta is available for download, 4.0.0 official release is on its way).

**Comment by SongDaBei** [comment]
@zhgw01 ,嘿，哥们，是中国人吧？我也碰到和你一模一样的问题，不知道你是怎么解决的呀？
