### ISSUE TITLE
Getting memory warning and app is crashed  When I used with collectionview 

### ISSUE THREAD

**Issue by perlasivakrishna** [rs/SDWebImage#1200]
```
-(UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
   CustomCollectionCell *cell = (CustomCollectionCell *)[collectionView dequeueReusableCellWithReuseIdentifier:@"MyCell" forIndexPath:indexPath];
[cell.Imgview sd_setImageWithURL:[NSURL URLWithString:[[[self.Actualimagearray objectAtIndex:indexPath.item]objectForKey:@"FilePath"]stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]] placeholderImage:[UIImage imageNamed:@"loader.png"]];
 return cell;
}
```
Here My ```self.Actualimagearray``` contains around 200 Urls......
How to avoid Memory warning

**Comment by mythodeia** [comment]
@perlasivakrishna  i modified your post so everyone can read the code properly.
how large are the images you load to your cells?

**Comment by perlasivakrishna** [comment]
My Image sizes are around 100 Kb each...

**Comment by mythodeia** [comment]
resolution? dpi? Maybe its something of these two that causes the crash. Does it happen while scrolling fast? Can you try your datasource with the demo project and see if it crashes there as well?

**Comment by perlasivakrishna** [comment]
Yeah exactly when im scrolling continuosly getting crash..

**Comment by mythodeia** [comment]
if the resolution of the images is high then you will surely get a memory related crash. make sure the resolution is small and the dpi is 72. also check [this](https://github.com/rs/SDWebImage/issues/538#issuecomment-67892084)

**Comment by perlasivakrishna** [comment]
Hey all of my pictures resolution is 72 dpi..., Especcially Im getting crash when scrolling continoulsy for         2-3 minutes ..

**Comment by mythodeia** [comment]
did you try with these options:
```
[[SDImageCache sharedImageCache] setShouldDecompressImages:NO];
[[SDWebImageDownloader sharedDownloader] setShouldDecompressImages:NO];
```

**Comment by perlasivakrishna** [comment]
I Try decompressing images set to NO, But still crasing. here Im providing 2 images for example, plz check those ..
https://www.dropbox.com/s/0l6h78foyfbf2s9/11178288_946703472040923_8971103857414139436_n.jpg?dl=0
https://www.dropbox.com/s/ffms2zu68v6p9xs/11182222_946703485374255_1651310022180919810_n.jpg?dl=0

**Comment by mythodeia** [comment]
the images above are 720x960 and 960x720 resolution.
i think you should lower these down. The images should be the same as you cell keeping aspect ratio in mind

**Comment by perlasivakrishna** [comment]
Here I can get any reolsution Image from Service side, After a search Im going use this method 

-(UIImage *)imageWithImage:(UIImage *)image scaledToSize:(CGSize)newSize {
    //UIGraphicsBeginImageContext(newSize);
    // In next line, pass 0.0 to use the current device's pixel scaling factor (and thus account for Retina resolution).
    // Pass 1.0 to force exact pixel size.
    UIGraphicsBeginImageContextWithOptions(newSize, NO, 0.0);
    [image drawInRect:CGRectMake(0, 0, newSize.width, newSize.height)];
    UIImage *newImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return newImage;
}
how can I use this with place holder concept  in Sdwebimage

**Comment by mythodeia** [comment]
the best thing is to get already scaled down images from the server. This way you will not stress the app even more.
you can use this:
```- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;```
to transform the image before caching it to disk. You can scale the image down there if you want
but the best thing would be to already get a scaled down image from your server side code

**Comment by perlasivakrishna** [comment]
If I saved the transformed image in cache, I may get a problem after clicking image. Bcoz After cliking on image Im showing it in large imageview. (700x700). then can I get the Clear Image

**Comment by perlasivakrishna** [comment]
Any way thanks for suggestions, I think its finally due to relosutions,

**Comment by mythodeia** [comment]
then have 2 images. one smaller one and one larger for full preview mode. but for thumbs you should for sure lower the resolution. Way less than 700x

**Comment by perlasivakrishna** [comment]
k thanks, for  thumbs Im converting in to lower resolution, but saving the original one.

 SDWebImageManager *manager = [SDWebImageManager sharedManager];
    [manager downloadImageWithURL:url
                          options:0
                         progress:^(NSInteger receivedSize, NSInteger expectedSize) {
                             
                             
                             
                         }
                        completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
                            if (image) {
                                
                                UIImage *scaledimage =[self imageWithImage:image scaledToSize:CGSizeMake(220, 220)];
                                completionBlock(YES,scaledimage);

                                
                                // do something with image
                            }
                            else
                            {
                                completionBlock(NO,nil);

                                
                            }
                        }];
