### ISSUE TITLE
carthage install libwebp issue

### ISSUE THREAD

**Issue by silver619** [rs/SDWebImage#1204]
am trying to install with carthage but am getting an:

A shell task failed with exit code 128:
fatal: http://git.chromium.org/webm/libwebp.git/info/refs not valid: is this a git repository?

i am guessing the address for the library has changed or something?

**Comment by mythodeia** [comment]
can you check using master ?

**Comment by silver619** [comment]
that did the trick, thanks.

**Comment by AlexMcArdle** [comment]
I'm having the exact same problem. I assume you mean checkout carthage from master branch and use make install? I removed carthage from brew before installing using make, still get error.

It's reporting version 0.7.5
