### ISSUE TITLE
SDWebImage ignoring MaxCacheSize?

### ISSUE THREAD

**Issue by TobiasEdqvist** [rs/SDWebImage#1206]
Hi!

Maybe I'm a completely lost newbie but anyhow...

I'm testing this code out in a objective-c project and it's really easy to use and implement! Although I have a problem.. I'm setting the MaxCacheSize variable when the app starts (in the didfinishlaunching.... function in the appdelegate) but when the app starts to save images to the cache they still save more space than this variable instead of removing old images to make the cache stay this size as a maximum?! Am I missing something or is this a bug...?

**Comment by mythodeia** [comment]
Hello
check ```cleanDiskWithCompletionBlock``` method.  You will see that it takes into account the ```maxCacheSize```
this method is called when this is called manually ```cleanDisk``` or when the app goes into background by this method ```backgroundCleanDisk```
