### ISSUE TITLE
SDWebImageRefreshCached Issue - Cache Images not refreshed

### ISSUE THREAD

**Issue by prasathbabu** [rs/SDWebImage#1207]
Cache Images are not loading when we switch application or app goes background to foreground..
i applied image to listview using sdwebimage with SDWebImageRefreshCached option.
```
- (UIImage *)image
{
UIImageView *imgV = [[UIImageView alloc]init];
[imgV sd_setImageWithURL:@"https://og.github.com/logo/github-logo@1200x1200.png" placeholderImage:[UIImage imageNamed:@"img.png"] options:SDWebImageRefreshCached];
return imgV.image;
}
```
All images downloaded and its displayed in listview. After we switch application the downloaded cache images not refreshed its only displayed placeholder Image but when i scroll the list view cache images displayed, again we switch application the default image displayed and cache image not refreshed its repeats..

Please kindly check it and Reply As Soon As Possible,
Prasath

**Comment by mythodeia** [comment]
So you say that when you put the app in background or switch to another app and then open you app again, all images show the placeholder image? Check the demo project to see how the tableview best works and try to replicate the problem there.

**Comment by Ailix** [comment]
I met a similar Issue about SDWebImageRefreshCached option
`After I upload a new avatar and refresh,the image is still the previous one`
Right now my solution is : `remove the cache before I upload`
```
SDImageCache *cache = [SDImageCache sharedImageCache];   
[cache removeImageForKey:imageUrl];
[self.imageView sd_setImageWithURL:imageUrl placeholderImage:placeholder];
```

**Comment by prasathbabu** [comment]
@mythodeia i tried to reproduce the issue in the demo project but i can't reproduce in the tableview..

here i am using IGGridview to display images in Horizontal view with Hoodies Feature..
IGGridview - its infragistics Nuclios Component
Still i am facing the cache issue while retrieve images from cache.. instead of displaying cache images its display the default image.
when i switch off the network after downloaded all images and after switch application the images displayed, when i scroll it the default images displayed in there instead of displaying cache image.

![iggridview-hoodies](https://cloud.githubusercontent.com/assets/6059590/8587873/567dcdea-2620-11e5-8782-f87afb26a74d.png)

**Comment by mythodeia** [comment]
@prasathbabu maybe you are not reusing your cells correctly. I cannot provide more assistance if we cannot debug it properly
