### ISSUE TITLE
Resizing with UIGraphicsBeginImageContextWithOptions leads to wrong size displaying

### ISSUE THREAD

**Issue by AbelIngrand** [rs/SDWebImage#1208]
Hi,

I'm using SDWebImage to download thumbnails. I resize them before caching them by using the `- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL` delegate method.

The code i use to reisze images is:

    - (UIImage *)imageByScalingAndCroppingForSize:(CGSize)targetSize Image:(UIImage *)image
    {
        UIImage *sourceImage = image;
        UIImage *newImage = nil;
        CGSize imageSize = sourceImage.size;
        CGFloat width = imageSize.width;
        CGFloat height = imageSize.height;
        CGFloat targetWidth = targetSize.width;
        CGFloat targetHeight = targetSize.height;
        CGFloat scaleFactor = 0.0;
        CGFloat scaledWidth = targetWidth;
        CGFloat scaledHeight = targetHeight;
        CGPoint thumbnailPoint = CGPointMake(0.0, 0.0);
    
        if (CGSizeEqualToSize(imageSize, targetSize) == NO) {
            CGFloat widthFactor = targetWidth / width;
            CGFloat heightFactor = targetHeight / height;
    
            if (widthFactor > heightFactor) {
                scaleFactor = widthFactor; // scale to fit height
            } else {
                scaleFactor = heightFactor; // scale to fit width
            }
    
            scaledWidth = width * scaleFactor;
            scaledHeight = height * scaleFactor;
    
            // center the image
            if (widthFactor > heightFactor) {
                thumbnailPoint.y = (targetHeight - scaledHeight) * 0.5;
            } else {
                if (widthFactor < heightFactor) {
                    thumbnailPoint.x = (targetWidth - scaledWidth) * 0.5;
                }
            }
        }
    
        UIGraphicsBeginImageContextWithOptions(targetSize, YES, 0); // this will crop
    
        CGRect thumbnailRect = CGRectZero;
        thumbnailRect.origin = thumbnailPoint;
        thumbnailRect.size.width = scaledWidth;
        thumbnailRect.size.height = scaledHeight;
    
        [sourceImage drawInRect:thumbnailRect];
    
        newImage = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
        return newImage;
    }
At first, I used `UIGraphicsBeginImageContext(targetSize);` but images where blurry on retina deivces so I changed the function to `UIGraphicsBeginImageContextWithOptions(targetSize, YES, 0);`

But now my images appear much bigger in my TableView cells. It seems the resizing code makes higher definition images but the SDWebImage Library doesn't know how to load them correctly.

Thanks in advance for your help
<img width="247" alt="capture d ecran 2015-07-08 a 13 02 43" src="https://cloud.githubusercontent.com/assets/300872/8568818/a962f580-2571-11e5-8588-ead10319d511.png">
Correctly loaded images

<img width="247" alt="capture d ecran 2015-07-08 a 13 02 33" src="https://cloud.githubusercontent.com/assets/300872/8568819/a968de3c-2571-11e5-8454-58043f8cb2a7.png">
Uncorrect size images

**Comment by mythodeia** [comment]
@AbelIngrand check [this](http://www.wrichards.com/blog/2011/11/sdwebimage-fixed-width-cell-images/)

**Comment by AbelIngrand** [comment]
Hi,

Yes I tried to set the contentMode to AspectFit but it didn't work.

What I think is happening:
1. My code resizes the images by taking into account the scale factor of the current device. So images on an scale factor of 3 end up being 3 times the size of factor 1
2. When displaying the images, SDWebImage selects the cached image but the size is 3x to big..

**Comment by mythodeia** [comment]
can you add something like this in your custom cell subclass?
```
- (void)layoutSubviews {
    [super layoutSubviews];
    self.imageView.frame = CGRectMake(0,0,32,32);
}
```
of course change the imageview rect to your liking

**Comment by AbelIngrand** [comment]
Good idea, it's kind of a hacky workaround but it works great. Thanks !
