### ISSUE TITLE
Completion handler is not called.

### ISSUE THREAD

**Issue by pantkarun75** [rs/SDWebImage#1209]
I am trying to manage my map marker with sdwebimage but when i go to background and then when i re-call 
`[imageView setImageWithURL:imageURL placeholderImage:[UIImage imageNamed:[Utils getPlaceholderImageName:location_Details]] options:SDWebImageRetryFailed completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType)` 
completion handler is not called, when i tried to debug 
`if (!wself) return;` 
this line is called with wself nil that stopped me to get control of completion block.

```
UIImageView *imageView=[[UIImageView alloc] init];
                    [imageView setImageWithURL:imageURL placeholderImage:[UIImage imageNamed:[Utils getPlaceholderImageName:location_Details]] options:SDWebImageRetryFailed completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType) {
                        dispatch_async(dispatch_get_main_queue(), ^{
                            long long currentTimestamp = [[NSDate date] timeIntervalSince1970] * MISEC_PER_SEC;
                            currentTimestamp -= (HOWMUCHSTALELOCATIONTOSHOWINMINUTES * MISEC_PER_MIN);

                            if ([[location_Details objectForKey:@"created"] longLongValue] >= currentTimestamp) {

                                marker.icon=[Utils getRoundedMapIcon:image isStale:NO];
                            }else{

                                marker.icon=[Utils getRoundedMapIcon:image isStale:YES];
                            }
                            marker.userData=location_Details;
                            marker.map = self.mapView;
                        });
                    }];
```

But then when I did this every thing seems to work fine but I am not sure about this, Please help me with this.

```
if (url) {
        __weak UIImageView *wself = self;
        id <SDWebImageOperation> operation = [SDWebImageManager.sharedManager downloadWithURL:url options:options progress:progressBlock completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished) {
//            if (!wself) return;
            dispatch_main_sync_safe(^{
                @try {
                    if (image) {
                        wself.image = image;
                        [wself setNeedsLayout];
                    }
                    if (completedBlock && finished) {
                        completedBlock(image, error, cacheType);
                    }
                }
                @catch (NSException *exception) {

                }
                @finally {

                }
//                if (!wself) return;

            });
        }];
        objc_setAssociatedObject(self, &operationKey, operation, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    }
```

**Comment by mythodeia** [comment]
can you try this instead of using a uiimageview?
```
[SDWebImageDownloader.sharedDownloader downloadImageWithURL:your_image_url
                                                    options:0
                                                   progress:^(NSInteger receivedSize, NSInteger expectedSize)
                                                   {
                                                       // progression tracking code
                                                   }
                                                   completed:^(UIImage *image, NSData *data, NSError *error, BOOL finished)
                                                   {
                                                       if (image && finished)
                                                       {
                                                           // do something with image
                                                       }
                                                   }];
```

**Comment by kmiloaguilar** [comment]
I'm having the same problem. Callback is not getting called.

**Comment by mythodeia** [comment]
@kmiloaguilar are you having the same problem using markers or in another scenario? did you try the code in my post above?

**Comment by kmiloaguilar** [comment]
@mythodeia the solution you provided worked for me, but the completion callback doesn't work.

**Comment by mythodeia** [comment]
the completion handler from:
```[SDWebImageDownloader.sharedDownloader downloadImageWithURL```
or from:
```[imageView setImageWithURL:imageURL placeholderImage:```

**Comment by kmiloaguilar** [comment]
[cell.imageView sd_setImageWithURL:[NSURL    URLWithString:@"http://www.domain.com/path/to/image.jpg"]
                      placeholderImage:[UIImage imageNamed:@"placeholder.png"]
                             completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {... completion code here ...}];

That one ^ it never get into there. The one for SDWebImageDownloader works fine. I ended up using that one.

**Comment by mythodeia** [comment]
@kmiloaguilar  can you replicate it on the demo project?

**Comment by kmiloaguilar** [comment]
I can try later.

**Comment by bpoplauschi** [comment]
@kmiloaguilar any updates here?

**Comment by kmiloaguilar** [comment]
@bpoplauschi sorry, didn't try it. I keep using sharedDownloader.

**Comment by pantkarun75** [comment]
shared downloader works fine but imageview category is not working

**Comment by JPROFFICIAL** [comment]
After two days of pulling my hair out believing it was an issue with UIImageView (why?), I can add to this discussion that `SDWebImageManager.sharedManager().downloadImageWithURL` does not always complete as well. The `SDWebImageDownloader.sharedDownloader` does work everytime though.

**Comment by AncAinu** [comment]
I would like to put an update on this post, we use SDWebImage as our main image lib (our app have millions of users), and this is a recurring problem which ruin the UX.

Basically completion is sometime never called (on first download of the image), but the image does download and go to cache.

It makes the library unreliable...

**Comment by dreampiggy** [comment]
This is a bug. We should keep the strong reference before that `dispatch_main_async_safe` so that the image instance may not dealloc.

**Comment by dreampiggy** [comment]
#2178 Merged. Wait for 4.3.0 release :)
