### ISSUE TITLE
Resizing images on retina display

### ISSUE THREAD

**Issue by AbelIngrand** [rs/SDWebImage#1210]
Hi,

Sorry, this seem like a duplicate of issue #1208 but I figured ou the problem was different:

SDWebImage downloads an image from a URL.
I resize it using `UIGraphicsBeginImageContextWithOptions(targetSize, YES, 0);` (in `- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL`) which as the advantage of taking into account the retina display scale factor (so if the image needs to be resized to 100x100 pixels, it will be resized to 200x200 on retina displays)
The image then appears correctly, in the right quality.

On the next launch of my app, when the image is getting called from the cache, a 200x200 image is loaded and displayed in a UIImageView of size 200x200 even though it should be size 100x100 but with 2x more pixels.

I don't really understand which part of SDWebImage is buggy but the problem ends up being that resizing images by taking scale factor into account leads to displaying double size images instead of normal size and double quality.

I don't know if i'm really clear about this, fee free to tell me if it isn't.

Thanks

**Comment by mythodeia** [comment]
can you go to ```SDWebImageCompat.m``` file and change this:
```CGFloat scale = 1;``` to this ```CGFloat scale = [UIScreen mainScreen].scale;```

i think that he initial scale should be set to the current scale of the device just in case the image does not have a @2x or @3x suffix

**Comment by AbelIngrand** [comment]
Yes, that worked. The other workaround i found is telling my UIImageView that the image it is loading is for a @2x or @3x resolution by setting the image to `imageView.image = [UIImage imageWithCGImage:image.CGImage scale:[[UIScreen mainScreen] scale] orientation:image.imageOrientation];`

**Comment by tamoyal** [comment]
Just curious - why is this closed? The suggestion seems like a good one (setting the scale based in the screen) but it never made it into the codebase?
