### ISSUE TITLE
Image automatically removed from cache on change of device datetime and region.

### ISSUE THREAD

**Issue by raheelahmad786** [rs/SDWebImage#1211]
Hi

i am facing strange problem. I am downloading all images using this method. 

```
[[SDWebImagePrefetcher sharedImagePrefetcher] prefetchURLs:urls progress:^(NSUInteger noOfFinishedUrls, NSUInteger noOfTotalUrls) {}
```
But when i change the device datetime and region all images automatically removed from app and redownloading images start one by one. This exactly happen when i change the device datetime region and move app to background and reopens it.

**Comment by mythodeia** [comment]
why do you change the device datetime? the images are removed because i think that the maxCacheAge might have passed.
when you move the app to background this method runs ```backgroundCleanDisk```

**Comment by raheelahmad786** [comment]
My app is storing images locally. i don't want it to remove from cache when app come from background. So what is needed exactly for this?

**Comment by mythodeia** [comment]
this will only happen when maxcacheage is reached. The default is 1 week. you can change that to your liking
