### ISSUE TITLE
App crash while downloading large images using SDWebImage

### ISSUE THREAD

**Issue by asifbilal-vteams** [rs/SDWebImage#1212]
I am using SDWebImage to download image async from server.Some images on server are of size ~1.5 to 2. MB.I'm showing these images on UICollectionView. I'm getting memory warning and app crashes after several run.Some times it happens when images downloaded first time and some time when i scroll the collection view up and down.

Please help me to resolve this issue.

**Comment by mythodeia** [comment]
@asifbilal-vteams i hope you are not using that same 2mb image as a thumbnail. if yes then thats why you are crashing. please use lower res images as thumbs and show the larger ones when the user asks for it. 
and use this to see if that makes any difference.
```
[[SDImageCache sharedImageCache] setShouldDecompressImages:NO];
[[SDWebImageDownloader sharedDownloader] setShouldDecompressImages:NO];
```
if you search this repo you will see several posts regarding similar situations with crashes when large images are used as thumbs while scrolling

**Comment by asifbilal-vteams** [comment]
Alright @mythodeia i'll give it a try. But, this library should resolve this issue itself.

**Comment by mythodeia** [comment]
@asifbilal-vteams 
or you could use the this delegate method ```- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;```
and make any resizes you want. Then this library will cache the smaller image instead but its up to you to download the bigger one. :+1:
