### ISSUE TITLE
pods install failed

### ISSUE THREAD

**Issue by ygweric** [rs/SDWebImage#1213]
pods install failed

    Installing SDWebImage (3.7.2)
    Using SVWebViewController (1.0)
    Using UMengAnalytics (3.5.8)
    Using UMengFeedback (2.3.3)
    Installing libwebp (0.4.3)
    [!] Pod::Executable clone https://chromium.googlesource.com/webm/libwebp /Users/yangeric/Library/Caches/CocoaPods/Git/20a7e0caa11500cb6a6e030259d3b3f9a29eea77 --mirror
    
    Cloning into bare repository '/Users/yangeric/Library/Caches/CocoaPods/Git/20a7e0caa11500cb6a6e030259d3b3f9a29eea77'...
    fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

**Comment by mythodeia** [comment]
the operation timed out when trying to clone the libwebp repository as i can see from your post. 
I tried it just now and it works just fine.
![screen](https://cloud.githubusercontent.com/assets/1748458/8612717/b9edbe9a-26dd-11e5-9836-52969804fdb0.png)

**Comment by ny8080** [comment]
I have the same error @ygweric @mythodeia

**Comment by pathfinder1989** [comment]
i have the error :

Installing OpenUDID (1.0.0)
Installing SDWebImage (3.8.2)
Installing libwebp (0.5.0)

[!] Error installing libwebp
[!] /usr/bin/git clone https://chromium.googlesource.com/webm/libwebp /var/folders/0c/rt1dny3d64qfrncb1yq22_rc0000gn/T/d20161103-3177-11xvrzp --template= --single-branch --depth 1 --branch v0.5.0

Cloning into '/var/folders/0c/rt1dny3d64qfrncb1yq22_rc0000gn/T/d20161103-3177-11xvrzp'...
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

**Comment by johnzhu12** [comment]
I have the same error:
fatal: unable to access 'https://github.com/rs/SDWebImage.git/': Failed to connect to apn.huanhuba.com port 8800: Operation timed out

**Comment by bpoplauschi** [comment]
@johnzhu12 this is a problem with your network setup. Not sure how to help you here.

**Comment by dengbin9009** [comment]
refer to http://blog.csdn.net/dengbin9009/article/details/71125250
