### ISSUE TITLE
Damned libwebp. Not available Google Source for average Chinese users.

### ISSUE THREAD

**Issue by ShadyNinja** [rs/SDWebImage#1214]
SourceTree, ShadowsocksX, OSX and Google Source make it GODDAMN DIFFICULT to continue using SDWebImage. I wanna fetch the latest one more easier. Is there any other way to replace libwebp's URL?

**Comment by bpoplauschi** [comment]
Do you have a working URL for libwebp?

**Comment by mythodeia** [comment]
isnt this the correct one? 
https://chromium.googlesource.com/webm/libwebp

**Comment by ShadyNinja** [comment]
I ain't saying the one offered in this repo is incorrect. It is definitely correct. But our Great Fire-Wall blocked us users in China from any Google resources. Well, Fxxk Chinese Gov. I can access google source through proxy such as ShadowsocksX with Browsers. But cannot with SourceTree for Mac due to some unknown technical problem. What a pity! Now I'm using version 3.7.3 as final version currently. I just wanna know whether there is another way to use SDWebImage freely. Hmmmm, perhaps I need to consider stay abroad.

**Comment by bpoplauschi** [comment]
:) I can understand the frustration. You could just use SDWebImage without the webp stuff. I strongly suggest you use CocoaPods instead of a clone to the repo. This way, you will get only the files you really need.

**Comment by ShadyNinja** [comment]
Alright, I'll try. Thanks.

**Comment by bpoplauschi** [comment]
Let us know how it works
