### ISSUE TITLE
Analyse and decide what we can import from forks

### ISSUE THREAD

**Issue by bpoplauschi** [rs/SDWebImage#1216]
There are some GitHub good devs that have forked SDWebImage and due to our lack of responsiveness have maintained their forks. We need to assess those import at least some of the fixes into the main repo.

Here's a list:
- https://github.com/mattjgalloway/SDWebImage
- https://github.com/harishkashyap/SDWebImage
- https://github.com/donholly/SDWebImage
- https://github.com/timkoma/SDWebImage
- https://github.com/mythodeia/SDWebImage

**Comment by bpoplauschi** [comment]
Use http://forked.yannick.io/ to see which forks were updated in the past year and which have more stargazers.

**Comment by bpoplauschi** [comment]
See the list converted to git remotes:
```
donholly		git@github.com:donholly/SDWebImage.git (fetch)
donholly		git@github.com:donholly/SDWebImage.git (push)
flovilmart		git@github.com:flovilmart/SDWebImage.git (push)
flovilmart		git@github.com:flovilmart/SDWebImage.git (fetch)
harishkashyap	git@github.com:harishkashyap/SDWebImage.git (fetch)
harishkashyap	git@github.com:harishkashyap/SDWebImage.git (push)
liyong03		git@github.com:liyong03/SDWebImage.git (push)
liyong03		git@github.com:liyong03/SDWebImage.git (fetch)
mattjgalloway	git@github.com:mattjgalloway/SDWebImage.git (fetch)
mattjgalloway	git@github.com:mattjgalloway/SDWebImage.git (push)
origin			git@github.com:rs/SDWebImage.git (fetch)
origin			git@github.com:rs/SDWebImage.git (push)
rromanchuk		git@github.com:rromanchuk/SDWebImage.git (push)
rromanchuk		git@github.com:rromanchuk/SDWebImage.git (fetch)
timkoma			git@github.com:timkoma/SDWebImage.git (fetch)
timkoma			git@github.com:timkoma/SDWebImage.git (push)
```

**Comment by mythodeia** [comment]
@bpoplauschi check the last 5 commits [here](https://github.com/mythodeia/SDWebImage/commits/master)

i have added the following:
fixes #391  -> option to cache only on Disk
fixes #343  -> iCloud backup Option
fixes #371  -> CGBitmapContextCreate: unsupported parameter combination
fixes #576  -> scale set to screen scale
fixes #1035 -> progress queue with dispatch_async
new feature -> activity indicator using auto layout

if any of the above are of any interest let me know

**Comment by bpoplauschi** [comment]
For certainly, the fixes are most welcome. I'll need to check the feature because we have rejected features that are not 100% on track with the library core until now, as we want to keep it maintainable.
You should create PR's from those branches

**Comment by mythodeia** [comment]
@bpoplauschi  all the above are on my master branch. Do you want me to send you a pull request so you can pick what you want?

**Comment by bpoplauschi** [comment]
The activity indicator feature will replace https://github.com/rs/SDWebImage/pull/131

**Comment by bpoplauschi** [comment]
And the fix for #391 will replace https://github.com/rs/SDWebImage/pull/1130

**Comment by bpoplauschi** [comment]
I created a PR from your master branch: https://github.com/rs/SDWebImage/pull/1217

**Comment by bpoplauschi** [comment]
About future directions, I want to look at the other forks I listed in the other issue and see what other good fixes we can get. Then refactor the dispatch sync to async.

I replaced the GIF solution with FLAnimatedImage on the 4.0 branch, the only issue is that branch is not ready for release, as it has a bunch of warning and nobody there seems to take care of that. We will see how that goes.

Another thread will be adding AFNetworking and replacing our network component, so we will be able to allow `NSURLSession`, requested by some of our users.

**Comment by bpoplauschi** [comment]
I reduced the list to 5 forks, one of which is yours. Here are the fixes I identified we should look at:
- from @mattjgalloway: #883 
- from @donholly: #906 
- from @harishkashyap: #999 
- from @timkoma: #1031 #1044 #1063

**Comment by mattjgalloway** [comment]
👍

I would love it if you could incorporate that PR from my fork. The fix is pretty important. Let me know if I can help out in any way.

**Comment by harishkashyap** [comment]
@bpoplauschi let me know what you need from my end.

**Comment by bpoplauschi** [comment]
About #999, it seems a big chunk from that was merged via #996. I am looking at the remaining code and see if we want to add it as well. 

@harishkashyap  I can see the remaining patch is actually a merge request into your fork: https://github.com/harishkashyap/SDWebImage/pull/1. What about this code? I see some good stuff here, but the way `NSMutableOrderedSet *prefetchURLs` and `NSMutableDictionary *unfinishedOperations` are used doesn't look too solid. Those are non-thread safe classes and most of the time they are accessed without a sync mechanism which makes it vulnerable to crashes. Any feedback here?

**Comment by harishkashyap** [comment]
@bpoplauschi There are a other changes committed by other developers. However, this commit (https://github.com/harishkashyap/SDWebImage/commit/cbc34337df46840927f9014db113c1b882d7e633) modifies the prefetching logic. It changes the logic from recursion to a loop and so will help remove overflows. I would recommend that this be merged in. You can take a look at it.

**Comment by bpoplauschi** [comment]
@harishkashyap thanks for the details. Could you and @mythodeia please review #1221, I've started a branch from your fork's master + reordered the methods in `SDWebImagePrefetcher.m` as they were before so the diff is easier to read and added some synchronization on the 2 non-thread safe collections `prefetchURLs` and `unfinishedOperations`.

**Comment by mythodeia** [comment]
@bpoplauschi my time will be limited for the next couple of weeks as my wife just gave birth to my son and i want to spend as much time as possible. But i will do my best :+1:

**Comment by bpoplauschi** [comment]
@mythodeia great news. Congrats and all the best to your wife and son. Get back when you can, I will keep going with 4.0 in the meantime.

**Comment by harishkashyap** [comment]
@bpoplauschi will take a look at it soon. Congrats to @mythodeia

**Comment by harishkashyap** [comment]
@bpoplauschi, these three can be cherry picked and reviewed. https://github.com/rs/SDWebImage/commit/ed64e00d4c0fda4344a3c08acb71eaedde85a5cb,
https://github.com/rs/SDWebImage/commit/ded305fb28ad55fdc1f39bc3c138ce386f221102
https://github.com/rs/SDWebImage/commit/cbc34337df46840927f9014db113c1b882d7e633

**Comment by bpoplauschi** [comment]
@harishkashyap I have create a branch with all your fixes plus some extra thread-safety. See #1221

**Comment by bpoplauschi** [comment]
By importing #883 in favour of #1069, this closes the items on this ticket. Closing
