### ISSUE TITLE
Application received signal SIGSEGV

### ISSUE THREAD

**Issue by fanpyi** [rs/SDWebImage#1219]
=> Start Application received signal SIGSEGV
	-> translating『 0x4c5319 』=>
	-> translating『 0x58519 』=> __72-[SDWebImageDownloader downloadImageWithURL:options:progress:completed:]_block_invoke136 /Users/fanpyi/Desktop/beequick project/ConsumerApp/Beequick/SDWebImage/SDWebImageDownloader.m: line 145
	-> translating『 0xdc5d7 』=> -[SDWebImageDownloaderOperation connectionDidFinishLoading:] /Users/fanpyi/Desktop/beequick project/ConsumerApp/Beequick/SDWebImage/SDWebImageDownloaderOperation.m: line 364
	-> translating『 0xdac6d 』=> -[SDWebImageDownloaderOperation start] /Users/fanpyi/Desktop/beequick project/ConsumerApp/Beequick/SDWebImage/SDWebImageDownloaderOperation.m: line 68
=> End Application received signal SIGSEGV

**Comment by bpoplauschi** [comment]
@fanpyi we need more info about this crash. a full stacktrace, how often does it repro, which library version, maybe create a demo project to demonstrate the crash.

**Comment by bpoplauschi** [comment]
Closing. Please reopen if you can provide the info required
