### ISSUE TITLE
sd_setImageWithURL: not cache gifs in UICollectionView 

### ISSUE THREAD

**Issue by purnimaSingh** [rs/SDWebImage#1220]
I am trying to load many gifs in UICollectionView but when i scroll UICollectionView up and down then loaded images gone and after some seconds they came. But like simple jpg and png from server not behave like this. Please suggest how to cache gifs and show in UICollectionView.
And the method is:

```
[weakCell.gifImageView sd_setImageWithURL:imgUrl placeholderImage:nil options:SDWebImageTransformAnimatedImage progress:^(NSInteger receivedSize, NSInteger expectedSize){
                                    cell.gifImageView.alpha = 0.0;
                                } completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                                    if (!image) {
                                        cell.loadingImage.hidden = NO;
                                        cell.defaultImage.hidden = NO;
                                    }
                                    else
                                    {
                                        [cell.loadingImage.layer removeAllAnimations];
                                        cell.loadingImage.hidden = YES;
                                        cell.defaultImage.hidden = YES;
                                        cell.gifImageView.alpha = 1.0;
                                    }
                                    
                                }];
```

**Comment by mythodeia** [comment]
maybe there is a delay until the gif is fully loaded. if your gif files are large in size check whether the same thing happens with smaller size gif files

**Comment by bpoplauschi** [comment]
GIF's are working lazy with our current version. In 4.0, we will replace the GIF component and most probably, those issues will go away

**Comment by purnimaSingh** [comment]
hey @bpoplauschi, Version 4.0 when will be live?
Please let me know ASAP.

**Comment by bpoplauschi** [comment]
It's going to take a while, as it's a lot of ground to be covered and I'm working alone on it. Can't give you a good estimate, but at least till the end of August.

**Comment by purnimaSingh** [comment]
hey @bpoplauschi any progress?
One more thing when gifs are loading in uicollectionview then memory size automatically increase and this memory leak increase the crash rate if you have any solution please suggest

**Comment by bpoplauschi** [comment]
We know about that issue as well and we will replace the existing GIF component.

**Comment by bpoplauschi** [comment]
@purnimaSingh We have replaced our GIF component with a library from Flipboard (FLAnimatedImage). Could you try our 4.x branch ([instructions](https://github.com/rs/SDWebImage/tree/4.x#animated-images-gif-support)) and see if it helps?

**Comment by graygrayh** [comment]
sd_setImageWithURL load gif ,but memorys can not  be released ,when back to last viewController . You met this problem ?

**Comment by bpoplauschi** [comment]
Closing. The FLAnimatedImage solution replacing our own GIF is integrated into the 4.x branch.
