### ISSUE TITLE
How to use cached image as placeholder when assigning new image url?

### ISSUE THREAD

**Issue by tounaobun** [rs/SDWebImage#1223]
I know it is strange but every time I use sd_setImageWithURL:placeholderImage: method on the same UIImageView instance,the placeholder just appears when downloading image from the Internet.How can I make the previous existing image cache as the placeholder so when changing the image url,the image transition looks good.

**Comment by johnxiao** [comment]
how？do you know how now？tsk

**Comment by sunbohong** [comment]
@johnxiao  You can use SDWebImageRefreshCached option.
