### ISSUE TITLE
load 3x gif in bundle

### ISSUE THREAD

**Issue by SummerTree** [rs/SDWebImage#1227]
sd_animatedGIFNamed can't load 3x gif for iPhone 6 plus，any plan for this issue?

**Comment by bpoplauschi** [comment]
I know. Our plan is that for version 4.0, we will replace our own GIF component with FLAnimatedImage from Flipboard. That should take care of your scenario as well.

**Comment by SummerTree** [comment]
Got it, thanks

**Comment by bpoplauschi** [comment]
We've added FLAnimatedImage support via #1575 into the 4.x branch. Try it out and let me know if your issue is resolved.
