### ISSUE TITLE
NSURLErrorDomain Code=403

### ISSUE THREAD

**Issue by Chren** [rs/SDWebImage#1228]
When using SDWebImage to download an jpg image from web, I got error below:
NSURLErrorDomain Code=403 "The operation couldn’t be completed
this is image url:
http://img5.imgtn.bdimg.com/it/u=3017210771,879699792&fm=11&gp=0.jpg
It shows ok in browser.

**Comment by qingmu213** [comment]
because is need User-Agent

in SDWebImageDownloader.m method init  replace by

- (id)init {
    if ((self = [super init])) {
        _operationClass = [SDWebImageDownloaderOperation class];
        _shouldDecompressImages = YES;
        _executionOrder = SDWebImageDownloaderFIFOExecutionOrder;
        _downloadQueue = [NSOperationQueue new];
        _downloadQueue.maxConcurrentOperationCount = 6;
        _URLCallbacks = [NSMutableDictionary new];
        
        NSString *userAgent = @"";
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgnu"
#if defined(__IPHONE_OS_VERSION_MIN_REQUIRED)
        // User-Agent Header; see http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.43
        userAgent = [NSString stringWithFormat:@"%@/%@ (%@; iOS %@; Scale/%0.2f)", [[[NSBundle mainBundle] infoDictionary] objectForKey:(__bridge NSString *)kCFBundleExecutableKey] ?: [[[NSBundle mainBundle] infoDictionary] objectForKey:(__bridge NSString *)kCFBundleIdentifierKey], [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleShortVersionString"] ?: [[[NSBundle mainBundle] infoDictionary] objectForKey:(__bridge NSString *)kCFBundleVersionKey], [[UIDevice currentDevice] model], [[UIDevice currentDevice] systemVersion], [[UIScreen mainScreen] scale]];
#elif defined(__MAC_OS_X_VERSION_MIN_REQUIRED)
        userAgent = [NSString stringWithFormat:@"%@/%@ (Mac OS X %@)", [[[NSBundle mainBundle] infoDictionary] objectForKey:(__bridge NSString *)kCFBundleExecutableKey] ?: [[[NSBundle mainBundle] infoDictionary] objectForKey:(__bridge NSString *)kCFBundleIdentifierKey], [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleShortVersionString"] ?: [[[NSBundle mainBundle] infoDictionary] objectForKey:(__bridge NSString *)kCFBundleVersionKey], [[NSProcessInfo processInfo] operatingSystemVersionString]];
#endif
#pragma clang diagnostic pop
        if (userAgent) {
            if (![userAgent canBeConvertedToEncoding:NSASCIIStringEncoding]) {
                NSMutableString *mutableUserAgent = [userAgent mutableCopy];
                if (CFStringTransform((__bridge CFMutableStringRef)(mutableUserAgent), NULL, (__bridge CFStringRef)@"Any-Latin; Latin-ASCII; [:^ASCII:] Remove", false)) {
                    userAgent = mutableUserAgent;
                }
            }
            [self setValue:userAgent forHTTPHeaderField:@"User-Agent"];
        }
        
        
#ifdef SD_WEBP
        _HTTPHeaders = [@{@"Accept": @"image/webp,image/*;q=0.8",@"User-Agent":userAgent} mutableCopy];
#else
        _HTTPHeaders = [@{@"Accept": @"image/*;q=0.8",@"User-Agent":userAgent} mutableCopy];
#endif
        _barrierQueue = dispatch_queue_create("com.hackemist.SDWebImageDownloaderBarrierQueue", DISPATCH_QUEUE_CONCURRENT);
        _downloadTimeout = 15.0;
    }
    return self;
}

**Comment by bpoplauschi** [comment]
Indeed, it seems this webserver requires a User-Agent before giving access to the image.
You don't need to modify the `SDWebImageDownloader` code.

Before downloading the image, do:
`[[SDWebImageDownloader sharedDownloader] setValue:userAgent forHTTPHeaderField:@"User-Agent"];` using an userAgent computed like in the example above.

**Comment by jiangyancong** [comment]
Excuse me, the solution works very well, but is there any plan to fix it in the branch?

**Comment by AndreaVitale** [comment]
Same problem with this sample url: https://static.pexels.com/photos/1475/food-vegetables-italian-restaurant-large.jpg.

Any helps?

**Comment by jiangyancong** [comment]
@AndreaVitale Have you tried qingmu213's solution above?

**Comment by AndreaVitale** [comment]
Yep, I tried setting the userAgent. It was loaded only for the first, second time. After that the server always return 403.
