### ISSUE TITLE
Gif disappeared when drag from left in UINavigationController

### ISSUE THREAD

**Issue by Onetaway** [rs/SDWebImage#1231]
When use system gesture to pull a navigation controller.Gif was disappeared. I think it should generate a static picture. The gesture is system gesture, drag from edge of the left screen, not a speciall one.

**Comment by bpoplauschi** [comment]
We are planning to replace our GIF component in 4.0 with FLAnimatedImage. Hopefully this will take care of your issue.

**Comment by Onetaway** [comment]
Yes   Thanks :+1:

**Comment by isaced** [comment]
:+1:

**Comment by aa57779111** [comment]
:+1:

**Comment by aa57779111** [comment]
:+1:

**Comment by bpoplauschi** [comment]
@Onetaway  We have replaced our GIF component with a library from Flipboard (FLAnimatedImage). Could you try our 4.x branch ([instructions](https://github.com/rs/SDWebImage/tree/4.x#animated-images-gif-support)) and see if it helps?

**Comment by bpoplauschi** [comment]
Closing. The FLAnimatedImage solution replacing our own GIF is integrated into the 4.x branch.
