### ISSUE TITLE
Enabling WebP with Carthage

### ISSUE THREAD

**Issue by Adlai-Holler** [rs/SDWebImage#1233]
Is there any way to do this?

**Comment by bpoplauschi** [comment]
@flovilmart could you take a look at this? I'm not sure how this would work.

**Comment by flovilmart** [comment]
yes, i'll have a look.

What's the problem here?

**Comment by bpoplauschi** [comment]
The question is how to enable WebP support via Carthage?

**Comment by flovilmart** [comment]
Check the PR, we could also add WebP support for everyone right into WebImage

**Comment by susieyy** [comment]
:+1:

**Comment by adly-holler** [comment]
:+1:

**Comment by flovilmart** [comment]
Do we want webP by default in every Carthage builds?

**Comment by Nirma** [comment]
:+1:

**Comment by bpoplauschi** [comment]
This should be solved now, the current framework targets include webp
