### ISSUE TITLE
Load Big Gif Will ReceiveMemoryWarning

### ISSUE THREAD

**Issue by wu736139669** [rs/SDWebImage#1234]
for example: http://bbs.xmfish.com/jq_ajax.php?action=showFace&size=s&uid=907565.
This gif will ReceiveMemoryWarning.
I don't know how to fix it.

**Comment by mythodeia** [comment]
please read [this]https://github.com/rs/SDWebImage/issues/945 
we are planning on replacing our GIF component with another one.
