### ISSUE TITLE
Received memory warnings when v have large images 

### ISSUE THREAD

**Issue by perlasivakrishna** [rs/SDWebImage#1235]
If i am using SDWebImageManager Im getting crash after scrolling multiple images 
If Using SDWebImageDownloader Mostly not getting any crash 

As I know SDWebImageDownloader will not save the image to cache, But I want to save the image to cache. How can i avoid memory issue 
Alos will the images store in disk or Memory ?
I want to store the images in disk instaed of memory.
Thank you...

**Comment by mythodeia** [comment]
@perlasivakrishna 
you can use the ```shouldCacheImagesInMemory``` and set it to NO so you only use disk cache.

you should have small thumbs for your tableview/collectionview because if you try to scroll with large images you will eventually cause a crash.

if you want in your case you can continue to use the ```SDWebImageDownloader``` and then save to cache in the completion block using this method below
```- (void)storeImage:(UIImage *)image forKey:(NSString *)key toDisk:(BOOL)toDisk;```

**Comment by perlasivakrishna** [comment]
K, I have thusands of urls, 
At present im using this method to reduce the reolsution of image and showing this in thumbs. 
-(UIImage *)imageWithImage:(UIImage *)image scaledToSize:(CGSize)newSize {
    //UIGraphicsBeginImageContext(newSize);
    // In next line, pass 0.0 to use the current device's pixel scaling factor (and thus account for Retina resolution).
    // Pass 1.0 to force exact pixel size.
    UIGraphicsBeginImageContextWithOptions(newSize, NO, 0.0);
    [image drawInRect:CGRectMake(0, 0, newSize.width, newSize.height)];
    UIImage *newImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return newImage;
}

Shall i need to maintain different urls for thumbins/original

**Comment by mythodeia** [comment]
this depends on your app's needs and how you have setup it up.
Some people have 2 urls, others have 1 and do a resize and cache both 
Its something you decide. If this works for you then leave it as is but be careful when resizing very large images as this takes memory as well.
You can use the demo project to test all options before you migrate to something new. 
good luck :+1:

**Comment by perlasivakrishna** [comment]
Also Can I get the Url from the completion block for "SDWebImageDownloader" like SDWebImageManager

**Comment by mythodeia** [comment]
you will need to be careful with cell reuse as the method does not return the url in the completion block.
why don't you use this: ``` [cell.imageView sd_setImageWithURL ```  
and use you can do the resize with this method:
```
- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;
```
the cached image will be the resized one.
Also do not forget to use the ```shouldCacheImagesInMemory``` option if you want to cache only to disk.

please use the demo project to test whatever configuration suits your needs

**Comment by perlasivakrishna** [comment]
k Thanks for info, I will try with  the demo project

**Comment by mythodeia** [comment]
:+1:

**Comment by perlasivakrishna** [comment]
:+1:

**Comment by vivekshah05** [comment]
I have the same memory issue in my app , so I store image to disk by 
`shouldCacheImagesInMemory = NO;`
But after that images in my tableView Flashes when i reload the table. Any work around for that ?
 Any help or guidance will be very helpful.
