### ISSUE TITLE
can't decode image with 8 integer bits/component; 16 bits/pixel

### ISSUE THREAD

**Issue by dami7786** [rs/SDWebImage#1237]
I find some issue in SDWebImageDecoder ,in pre version can download this image successful,but in new version it can't decode image whit 8 integer bits/component; 16 bits/pixel; 1-component color space
the e.g. url:
http://image.xcar.com.cn/upc/2015/2015080113_b65a428760201cd756efaoT517SlfPz8_176x132.jpg

**Comment by mythodeia** [comment]
@dami7786 please use the latest commit. i just tested it and it works fine
