### ISSUE TITLE
it can not show the image.

### ISSUE THREAD

**Issue by songdh** [rs/SDWebImage#1242]
I found it can not show the image:  http://img.stuhui.com/0aabd32eb066fb1a35065785402de576
the console show error message:<Error>: CGBitmapContextCreate: unsupported color space.

CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update

I found the problem result in this  function：+ (UIImage *)decodedImageWithImage:(UIImage *)image;

**Comment by mythodeia** [comment]
@songdh go to that method and change this
```
    CGContextRef context = CGBitmapContextCreate(NULL, width,
                                                 height,
                                                 CGImageGetBitsPerComponent(imageRef),
                                                 0,
                                                 (imageColorSpaceModel == -1 || imageColorSpaceModel == 0) ? RGBcolorSpace : CGImageGetColorSpace(imageRef),
                                                 kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedFirst);
```
to this
```
    CGContextRef context = CGBitmapContextCreate(NULL, width,
                                                 height,
                                                 CGImageGetBitsPerComponent(imageRef),
                                                 0,
                                                 (imageColorSpaceModel == -1 || imageColorSpaceModel == 0 || imageColorSpaceModel == 5) ? RGBcolorSpace : CGImageGetColorSpace(imageRef),
                                                 kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedFirst);
```
and it will work

**Comment by songdh** [comment]
thank you

**Comment by songdh** [comment]
In the same method in line 46, I got another error with the image: http://img.stuhui.com/b18d86248007bebbf0741a2298373406

The error message:<Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by mythodeia** [comment]
i do not get this error using the revised code i told you

**Comment by songdh** [comment]
i modify my code and the error is still exist.
this is my code:

                imgUrl = @"http://img.stuhui.com/b18d86248007bebbf0741a2298373406";
                [imgView sd_setImageWithURL:[NSURL URLWithString:imgUrl]
                           placeholderImage:Thumbnail
                                  completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                                      if (error) {
                                          DDLogError(@"show detail image error:%@.remove cache imageKey=%@",error.localizedDescription,key);
                                      }else {
                                          //图片下载成功。通知界面重新刷新
                                          NSValue* sizeValue = [NSValue valueWithCGSize:image.size];
                                          [slDNFC postNotificationName:topicDetailImageLoadFinishedNotification object:sizeValue];
                                      }
                                  }];

the error log is :show detail image error:Downloaded image has 0 pixels.remove cache imageKey=http://img.stuhui.com/b18d86248007bebbf0741a2298373406

**Comment by mythodeia** [comment]
sorry but i cannot replicate this error with the url you provided.
i am trying [this](http://img.stuhui.com/b18d86248007bebbf0741a2298373406) url
and i have replaced the code from line 38 in the ```decodedImageWithImage``` method with the one below and it works
```
    CGContextRef context = CGBitmapContextCreate(NULL, width,
                                                 height,
                                                 CGImageGetBitsPerComponent(imageRef),
                                                 0,
                                                 (imageColorSpaceModel == -1 || imageColorSpaceModel == 0 || imageColorSpaceModel == 5) ? RGBcolorSpace : CGImageGetColorSpace(imageRef),
                                                 kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedFirst);
```

**Comment by songdh** [comment]
I am sorry. I found the image has some problem.I can open the image in Chrome but safari and firefox. When I download it with Chrome, I can not open it with the "preview".
I am really puzzled by you cannot replicate the error.
here is my demo. There are two demos. They use the latest version and an old version,which i got one year ago. also, I have replaced the code you told me in the latest version.
The old-version demo only show the error message:image error:Downloaded image has 0 pixels.
The latest-version demo show the error message:

 ImageDemo_lastVersion[35908] <Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

2015-08-05 15:31:13.999 ImageDemo_lastVersion[35908:1891145] image error:Downloaded image has 0 pixels

Thank you.

the demo: http://pan.baidu.com/s/1c0AW0X6

**Comment by mythodeia** [comment]
In both of your demos i get the console messages you told me.
Now the weird part is this. Download the demo project of this library and replace all urls in the masterviewcontroller with only this [one](http://img.stuhui.com/b18d86248007bebbf0741a2298373406)
then run the demo. You will see that the image is downloaded successfully in both views.
Can you test that please?
By the way, the colorspacemodel for this image is kCGColorSpaceModelUnknown which i do not have much info

**Comment by songdh** [comment]
I run the demo and it can show the image correctly. I think there is something missed in my demo, or something wrong with my config. I will test it. Thanks a lot.

**Comment by kamabhavik** [comment]
i have tried all this thing but still some of images not showing in my application.

**Comment by mythodeia** [comment]
share some image urls. do you use the latest version?

**Comment by kamabhavik** [comment]
yes we are using the latest updated version. let me share you my code
 [imgView sd_setImageWithURL:url
                               placeholderImage:[UIImage imageNamed:@""]];

we have 3 diffrent url 
1. http://www.akerbrygge.no/wp-content/uploads/2015/06/L-86-2-1540-edit2.jpg
2.http://www.akerbrygge.no/wp-content/uploads/2015/06/b%C3%B8ker-mann.jpg
3.http://www.akerbrygge.no/wp-content/uploads/2015/06/Ark.jpg

The first image is some how now coming by changing the following code in SDWebImageDecoder.m
+ (UIImage *)decodedImageWithImage:(UIImage *)image {
    // do not decode animated images
    if (image.images) { return image; }
    
    CGImageRef imageRef = image.CGImage;
    
    CGImageAlphaInfo alpha = CGImageGetAlphaInfo(imageRef);
    BOOL anyAlpha = (alpha == kCGImageAlphaFirst ||
                     alpha == kCGImageAlphaLast ||
                     alpha == kCGImageAlphaPremultipliedFirst ||
                     alpha == kCGImageAlphaPremultipliedLast);
    
    if (anyAlpha) { return image; }
    
    size_t width = CGImageGetWidth(imageRef);
    size_t height = CGImageGetHeight(imageRef);
    
    // default RGB
    CGColorSpaceRef RGBcolorSpace = CGColorSpaceCreateDeviceRGB();
    
    // current
    //CGColorSpaceModel imageColorSpaceModel = CGColorSpaceGetModel(CGImageGetColorSpace(imageRef));
    
    CGContextRef context = CGBitmapContextCreate(NULL, width,
                                                 height,
                                                 CGImageGetBitsPerComponent(imageRef),
                                                 0,
                                                 RGBcolorSpace,
                                                 kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedFirst);
    
    // Draw the image into the context and retrieve the new image, which will now have an alpha layer
    CGContextDrawImage(context, CGRectMake(0, 0, width, height), imageRef);
    CGImageRef imageRefWithAlpha = CGBitmapContextCreateImage(context);
    UIImage *imageWithAlpha = [UIImage imageWithCGImage:imageRefWithAlpha];
    
    CGColorSpaceRelease(RGBcolorSpace);
    CGContextRelease(context);
    CGImageRelease(imageRefWithAlpha);
    
    return imageWithAlpha;
}
but still the 2nd and 3rd images not loading.if you can guide us.

Thanks & Regards

**Comment by mythodeia** [comment]
the code above is not the latest one. try this one:
```
+ (UIImage *)decodedImageWithImage:(UIImage *)image {
    // do not decode animated images
    if (image.images) { return image; }

    CGImageRef imageRef = image.CGImage;

    CGImageAlphaInfo alpha = CGImageGetAlphaInfo(imageRef);
    BOOL anyAlpha = (alpha == kCGImageAlphaFirst ||
                     alpha == kCGImageAlphaLast ||
                     alpha == kCGImageAlphaPremultipliedFirst ||
                     alpha == kCGImageAlphaPremultipliedLast);

    if (anyAlpha) { return image; }

    size_t width = CGImageGetWidth(imageRef);
    size_t height = CGImageGetHeight(imageRef);

    // current
    CGColorSpaceModel imageColorSpaceModel = CGColorSpaceGetModel(CGImageGetColorSpace(imageRef));
    CGColorSpaceRef colorspaceRef = CGImageGetColorSpace(imageRef);

    bool unsupportedColorSpace = (imageColorSpaceModel == 0
                                  || imageColorSpaceModel == -1
                                  || imageColorSpaceModel == kCGColorSpaceModelIndexed
                                  || imageColorSpaceModel == kCGColorSpaceModelCMYK);
    if (unsupportedColorSpace)
        colorspaceRef = CGColorSpaceCreateDeviceRGB();

    CGContextRef context = CGBitmapContextCreate(NULL, width,
                                                 height,
                                                 CGImageGetBitsPerComponent(imageRef),
                                                 0,
                                                 colorspaceRef,
                                                 kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedFirst);

    // Draw the image into the context and retrieve the new image, which will now have an alpha layer
    CGContextDrawImage(context, CGRectMake(0, 0, width, height), imageRef);
    CGImageRef imageRefWithAlpha = CGBitmapContextCreateImage(context);
    UIImage *imageWithAlpha = [UIImage imageWithCGImage:imageRefWithAlpha];

    if (unsupportedColorSpace)
        CGColorSpaceRelease(colorspaceRef);

    CGContextRelease(context);
    CGImageRelease(imageRefWithAlpha);

    return imageWithAlpha;
}
```
the only difference this code has with the latest version here is the check for CMYK colorspace

**Comment by kamabhavik** [comment]
Still it's not working. i am troubleshooting.

**Comment by mythodeia** [comment]
remove the app and try again...if you want add only the above 3 urls in the demo project and replace the code in the ```SDWebImageDecoder``` with the one i posted above.
