### ISSUE TITLE
How to reload image from network

### ISSUE THREAD

**Issue by onmyway133** [rs/SDWebImage#1243]
I'm using `SDWebImageManager` `downloadImageWithURL:options:progress:completed` to download image from network. But it always check for memory and disk cache, are there any options to force download and replacing the existing images, or we need to delete the images on disk first?

**Comment by mythodeia** [comment]
you could use the option ```SDWebImageRefreshCached```
unless you mean something else

**Comment by mythodeia** [comment]
either use the the option i stated above or delete the image in cache using the ```removeImageForKey``` method before you make another request for that url.
if you still need assistance let us know
