### ISSUE TITLE
disscuss about decompress image after download

### ISSUE THREAD

**Issue by luoyibu** [rs/SDWebImage#1244]
It is not a issue, I just have some test about how "decompress image" will affect with the performance, and then the result is confused. 

I test with 2 code:
A: I just call initWithContentOfFile: at background thread, and then setImage in the main thread.
B: I use SDWebImage to test the fps after the image was all downloaded.

The fps was almost the same at instrument, so I doubt the effect of decompressing image.

Then I test the time consuming of "initWithContentOfFile" and "drawImage" with 2 images, the one was undecompress, the other was decompressed(I call decodedImageWithImage function and save to file).
The result show that with different images, the "drawImage" consume the same time, but the "initWithContentFile" has a different time consuming.

Is it mean that the "decompress image" is occurred at "initWithContentOfFile", not the time we call "setImage" at main thread?
And, is it mean that we have no need to decompress image after download while we always call the "initWithContentOfFile" function at a background thread?

This confused me very much, I need your advice.

**Comment by luoyibu** [comment]
When I get fps of instrument, it always be high(bigger then 50) while scrolling. And some times I can see the delay, is it possible that the instrument is not exact. 
And how can I get the true fps while scrolling, any advice?

**Comment by luoyibu** [comment]
@bpoplauschi can you help with this issue?

**Comment by mythodeia** [comment]
@luoyibu for your fps question you can connect your device to XCode and open instruments and select Core Animation.

**Comment by bpoplauschi** [comment]
@luoyibu indeed, you can use CoreAnimation for real FPS measurements. Regarding the difference between `initWithContentsOfFile` and `drawImage`, I didn't take any measurements here, so I can't really have an opinion. The documentation on SDWebImage was written by @rs, so he should have the info on that. You can check out https://github.com/path/FastImageCache#the-problem, as it explains the classic problem with image decompression.
