### ISSUE TITLE
How to add multiple options to sd_setImageWithURL ?

### ISSUE THREAD

**Issue by felixchan** [rs/SDWebImage#1245]
```              
self.userImageView.sd_setImageWithURL(image_link, placeholderImage: imagePlaceholder, options: SDWebImageOptions.RetryFailed)
```

Is there any way to also add RefreshCached ?

Thanks!

**Comment by luoyibu** [comment]
SDWebImageOptions is defined by NS_OPTIONS,  so you can try this:   ".RetryFailed | .RefreshCached"

**Comment by VivekVithlani** [comment]
You set multiple options like this

`let sdWebImageOptions:SDWebImageOptions = [.progressiveDownload, .scaleDownLargeImages]
                    imgViewPostImage.sd_setImage(with: URL(string: "yourURL"), placeholderImage: UIImage(named: ImagePlaceHolder), options: sdWebImageOptions)`
