### ISSUE TITLE
dispatch_main_async_safe not needed.

### ISSUE THREAD

**Issue by ryo-ogata** [rs/SDWebImage#1246]
I think `dispatch_main_async_safe ` is not needed when exists `SDWebImageAvoidAutoSetImage ` in options.
If `completion` block have many heavy code(e.g. I use CoreGraphic), UITableView scrolling will be stop and jumpy.
Does anybody have any good idea?

**Comment by bpoplauschi** [comment]
We will refactor this part (`dispatch_main_async_safe`) in 4.0 anyway

**Comment by bpoplauschi** [comment]
I think we still need it. The heavy completion indicates other issues that with this library.

**Comment by pengxuyuan** [comment]
i see you do some change about dispatch_main_async_safe
#define dispatch_main_async_safe(block)\
    if ([NSThread isMainThread]) {\
        block();\
    } else {\
        dispatch_async(dispatch_get_main_queue(), block);\
    }

->

#ifndef dispatch_main_async_safe
#define dispatch_main_async_safe(block)\
    if (strcmp(dispatch_queue_get_label(DISPATCH_CURRENT_QUEUE_LABEL), dispatch_queue_get_label(dispatch_get_main_queue())) == 0) {\
        block();\
    } else {\
        dispatch_async(dispatch_get_main_queue(), block);\
    }
#endif

how this change can resolve this problem ？

**Comment by weipinglii** [comment]
@bpoplauschi I'am a little confused, why we need this macro dispatch_main_async_safe? 
. Call dispatch_async(dispatch_get_main_queue(), block) on main_queue seems fine for me since i won't block mainqueue like dispatch_sync(). Is this macro defined for performance or something else?

**Comment by weipinglii** [comment]
figure it out now,  the "safe" part is about execute the block directly on current queue, not about dispatch_async when current queue is main queue, am i right?
