### ISSUE TITLE
<Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 16 bits/pixel; 1-component color space; kCGImageAlphaPremultipliedFirst; 256 bytes/row.

### ISSUE THREAD

**Issue by daqiangge** [rs/SDWebImage#1249]
<Error>: CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 16 bits/pixel; 1-component color space; kCGImageAlphaPremultipliedFirst; 256 bytes/row.
<Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
<Error>: CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

Why report this waring?

**Comment by rcodddow** [comment]
I get a similar error when trying to prefetch a large number of images, namely 18,000. The first 4,100 images are fetched quickly and then badness happens. 

<Error>: CGBitmapContextInfoCreate: unable to allocate 1971200 bytes for bitmap data
<Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
<Error>: CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
Prefetched 4141 out of 18034 (Failed)
malloc: *** mach_vm_map(size=561152) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug

**Comment by mythodeia** [comment]
@daqiangge @rcodddow are you using the latest version of this library. there was a commit a couple of days back that was to correct some of those issues. Usually what this error means is that we are trying to create a bitmap context using wrong parameters because of unknown colorspace.

**Comment by rcodddow** [comment]
Yes, I updated yesterday.

**Comment by mythodeia** [comment]
please try [this](https://github.com/rs/SDWebImage/issues/1242#issuecomment-127499275) first and if this does not work share an image thats causing the issue

**Comment by mythodeia** [comment]
closing this. if you still encounter issues let us know

**Comment by aslam9691** [comment]
i'm also getting same issue. i'm using pod version (4.2.3)

**Comment by dreampiggy** [comment]
Your Application ouf of memory. Because when creating CGBitmapContext, it need to malloc memory buffer with bytePerRow * pixelWidth * pixelHeight bytes in memory.

If the CGBitmapContext create failed, we will only return nil and do dothing, no crash there. If you prefetch multiple large images, it recommend to use a custom manager which disable 'shouldDecompressImage'.

In 5.x, we may also add 'shouldDecompressImage' into 'SDWebImageOptions' to control single image request behavior.

**Comment by LucaIaconelli** [comment]
I'm also getting the same issue. I'm using pod version (5.0.1)

Anyone can help me? 

Thanks in advance

**Comment by dreampiggy** [comment]
@LucaIaconelli What’s the error log ? Such as the title above.

It’s not a OOM issue, actually. It about the wrong decoding params we used to call apple’s API

**Comment by LucaIaconelli** [comment]
Basically, my app works great but after download 100+ images, it gives me a memory pressure and after all requests to retrieve an image fail also the one that is in the cache. 
This is the error:

CGBitmapContextInfoCreate: unable to allocate 1971200 bytes for bitmap data

**Comment by dreampiggy** [comment]
OK...This `CGBitmapContextInfoCreate: unable to allocate 1971200 bytes for bitmap data` is memory issue. Seems we can not allocate enough memory for image bitmap...This is a topic we want to do optimize, but currently, seems only some basic solution in #2560 . (The `avoidDecodeImage` option may help)

And that `<Error>: CGBitmapContextCreate: unsupported parameter combination:` is not. It's developer bug that using the wrong args for API.

**Comment by LucaIaconelli** [comment]
Ok thanks.
