### ISSUE TITLE
How to remove image synchronously ?

### ISSUE THREAD

**Issue by onmyway133** [rs/SDWebImage#1251]
I see that we only have `- (void)removeImageForKey:(NSString *)key fromDisk:(BOOL)fromDisk withCompletion:(SDWebImageNoParamsBlock)completion` which is asynchronous, how to workaround this ?

**Comment by bpoplauschi** [comment]
With the current architecture, you can't do it synchronously. Please try async until we find a way to change the API

**Comment by onmyway133** [comment]
@bpoplauschi thanks, currently SDWebImage uses `ioQueue`, which is sufficient for me.

**Comment by mythodeia** [comment]
based on comments closing this

**Comment by plougy** [comment]
Please change the documentation about `removeImageForKey:`, it's marked as a method synchronous, but it is not...
