### ISSUE TITLE
How to download and replace existing images if any?

### ISSUE THREAD

**Issue by onmyway133** [rs/SDWebImage#1252]
I see that 

```
- (id <SDWebImageOperation>)downloadImageWithURL:(NSURL *)url
                                         options:(SDWebImageOptions)options
                                        progress:(SDWebImageDownloaderProgressBlock)progressBlock
                                       completed:(SDWebImageCompletionWithFinishedBlock)completedBlock
```

checks if images in cache first. I think the we should have an options to always download and replace existing images

**Comment by bpoplauschi** [comment]
You can set `SDWebImageRefreshCached` via the options param, but that will respect the HTTP response cache headers (i.e. Cache-Control). So if the webservice hosting the image says "cache it for 1 day", then we will not re-download it for 1 day.

**Comment by mythodeia** [comment]
you can use this ```SDWebImageRefreshCached``` option to always refresh the cached images

**Comment by onmyway133** [comment]
@bpoplauschi @mythodeia thanks, currently my workaround is to delete the images first, then download. SDWebImage uses serial `ioQueue` which is good for me so far
