### ISSUE TITLE
<Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. 

### ISSUE THREAD

**Issue by Agenric** [rs/SDWebImage#1254]
<Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. 
How can I do that? Thanks

**Comment by Agenric** [comment]
CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability.

**Comment by mythodeia** [comment]
@Agenric download the latest version as there have been changes in that area. if still you encounter issues provide a link to an image that produces this error

**Comment by mythodeia** [comment]
closing this. if you still need help please let us know
