### ISSUE TITLE
cachedImageExistsForURL return wrong result???

### ISSUE THREAD

**Issue by neil-wu** [rs/SDWebImage#1255]
Something seems strange in my Swift project. 
I modify the source code of SDWebImage, to use the function `diskImageDataBySearchingAllPathsForKey` to get NSData object. (make it as a public function)
Take a look of the following code:
```
var isInCache: Bool = SDWebImageManager.sharedManager().cachedImageExistsForURL(NSURL(string: imgURLString))
var data: NSData! = SDWebImageManager.sharedManager().imageCache.diskImageDataBySearchingAllPathsForKey(imgURLString)
```

`isInCache` is true, but the `data` is nil.

But after I load the image again, everything goes all all right. Only the first time, it goes wrong.

What happens? 

Is the image only in memory(not in disk) ? If so, how to get the NSData object of this image?

**Comment by mythodeia** [comment]
unless you are using this ```SDWebImageCacheMemoryOnly``` i cannot see any other reason why data is nil.

**Comment by neil-wu** [comment]
I used like this:
···
SDWebImageManager.sharedManager().downloadImageWithURL(imgurlpath!,
    options: SDWebImageOptions.ProgressiveDownload,
    progress: { (recvSize, totalSize) in
        //...
    }, completed: { (image, error, cacheType, finished, imgURL)  in
        //on image loaded
        if finished {
            //do something...
            //...
            //
            var isInCache: Bool = SDWebImageManager.sharedManager().cachedImageExistsForURL(NSURL(string: imgURLString))
            var data: NSData! = SDWebImageManager.sharedManager().imageCache.diskImageDataBySearchingAllPathsForKey(imgURLString)
        }
        
})
···

**Comment by mythodeia** [comment]
if you log the cacheType on the completion block what does it say?

**Comment by neil-wu** [comment]
It's 0 when data is nil

**Comment by neil-wu** [comment]
And it become 2 when data is not nil

**Comment by mythodeia** [comment]
0 is for SDImageCacheTypeNone
1 is for SDImageCacheTypeDisk
2 is for SDImageCacheTypeMemory

i think SDWebImageDownloader does not cache images. SDWebImageManager does

**Comment by neil-wu** [comment]
Is there any option to tell SDWebImageDownloader cache image?

**Comment by mythodeia** [comment]
on the completion block you can manually call the
```- (void)storeImage:(UIImage *)image forKey:(NSString *)key toDisk:(BOOL)toDisk;```
check ```SDImageCache.h``` file

**Comment by neil-wu** [comment]
thank you very much. :+1:

**Comment by mythodeia** [comment]
thanks. good luck with your app :+1:
