### ISSUE TITLE
SDWebImage/WebP' compilation issue using the latest cocoapods 0.38.2 in a swift project that has the option use_frameworks! 

### ISSUE THREAD

**Issue by crarau** [rs/SDWebImage#1261]
![image](https://cloud.githubusercontent.com/assets/1430145/9315795/57e8c90c-44ff-11e5-9c27-bcba4d049a56.png)

The compilation issue appears using the latest cocoapods 0.38.2 in a swift project that has the option use_frameworks! 

target '....' do
use_frameworks!
    
pod 'SDWebImage'
pod 'SDWebImage/WebP'
end

To reproduce the issue I've create this repository: https://github.com/crarau/SDWebImageWebPCompilationIssue

Please advice how to fix the issue.

A note:
without the use_frameworks! option there is no compilation issue. But we need this option since our main projects includes swift pods.

**Comment by mythodeia** [comment]
@crarau i cloned your repo and did a pod install and everything is working fine. The project compiles and runs just fine. Is there a step i am missing?

**Comment by crarau** [comment]
Are you using cocoapods 0.38.2? Run pod --version.
Thanks,
Ciprian.

**Comment by mythodeia** [comment]
i was using 0.38.0 and i had no issue. i updated to 0.38.2 and indeed there is an issue. thanks for reporting

**Comment by mythodeia** [comment]
@crarau i fixed it by replacing this:
```#import "webp/decode.h"```
with this
```#import <libwebp/webp/decode.h>```

**Comment by crarau** [comment]
Created a pull request to integrate into master from my fork.

**Comment by qingpengchen2011** [comment]
I encountes same problem.

**Comment by bpoplauschi** [comment]
Fixed by bf899e2

**Comment by strivingboy** [comment]
this issue recurrence after pod 'SDWebImage', '~> 3.7.3'
