### ISSUE TITLE
Crash when using sd_setImageWithURL in Tableview

### ISSUE THREAD

**Issue by nishan-guiddit** [rs/SDWebImage#1264]
Hi,

My Application is crashed when I load images in the Tableview using the method "sd_setImageWithURL", below crash is observed

"<Error>: ImageIO: CGImageSourceCreateWithData data parameter is nil"
"<Error>: ImageIO: CGImageSourceCopyPropertiesAtIndex image source parameter is nil"

While I scroll the tableview which contains images in it, this happens. Please help me out with this.

Thanks

**Comment by mythodeia** [comment]
@nishan-guiddit are you using the latest version? can you try the url of your images with the demo project and see if it crashes there as well?

**Comment by XCGit** [comment]
tableViewLoadOldData

**Comment by XCGit** [comment]
I have the same problem

**Comment by mythodeia** [comment]
@XCGit 
Are you using the latest version? Can you replicate the issue in the demo project using your urls?

**Comment by nishan-guiddit** [comment]
@XCGit how would I know that I'm using the old version of the files ? Since I have not used the whole project inside my Current project and  I have used used the files from "SDWebImage". How will I get to know that I'm using the old version ?

**Comment by mythodeia** [comment]
@nishan-guiddit download the latest version of this library and replace the files you use with the newer ones.

**Comment by mythodeia** [comment]
i will close this one. if you still face issues please reopen
