### ISSUE TITLE
Completed block not called if nested 

### ISSUE THREAD

**Issue by victorBaro** [rs/SDWebImage#1266]
Hello, 
I am trying to download a small image to use it as a placeholder while the large image is downloading. I have the following code:

```
    [self.productImageView sd_setImageWithURL:thumbnailURL
                                    completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL){

                                        [self.productImageView sd_setImageWithURL:largeImageURL
                                                                 placeholderImage:image
                                                                        completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL){
                                                                            //Not called!
                                                                        }];
                                        
                                    }];
```

The above code does not call the second completion block nor set the large image in the productImageView.

**Comment by victorBaro** [comment]
I have read other issues and it works okay using the following code:
```
    [self.productImageView sd_setImageWithURL:thumbnailURL
                                    completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL){
                                        [SDWebImageDownloader.sharedDownloader downloadImageWithURL:largeImageURL
                                                                                            options:0
                                                                                           progress:^(NSInteger receivedSize, NSInteger expectedSize)
                                         {
                                             // progression tracking code
                                         }
                                                                                          completed:^(UIImage *image, NSData *data, NSError *error, BOOL finished)
                                         {
                                             if (image && finished)
                                             {
                                                 self.productImageView.image = image;
                                             }
                                         }];

                                        
                                    }];
```

**Comment by bpoplauschi** [comment]
Interesting approach. We've never tried this scenario. So the one in the 2nd comment works? If so, we can close the issue

**Comment by victorBaro** [comment]
It works only if you have 1 image. But in case of using it on a tableView/collectionView it doesn't work. It is not a good solution.

**Comment by com314159** [comment]
I have met this problem too. In my case , the first load thumbnailURL is failed , and the second load complete block will not be called, and it will failed load image. It sees cancelled by the first load operation . my code is like this 


     - (void) loadImage:(UIImageView *) imageView withUrl:(NSString *)url buildUrl:(NSString *)buildUrl placeholderImage:(UIImage*)image loadingImageMode:(UIViewContentMode)mode successImageMode:(UIViewContentMode)loadMode  ani:(LoadImageAnimation)ani   success:(void(^)(SDImageCacheType cacheType))successblock failure:(void (^)(NSError *))failureblock {
    
    if (buildUrl == nil) {
        [self loadImage:imageView withUrl:url placeholderImage:image loadingImageMode:mode successImageMode:loadMode ani:ani success:successblock failure:failureblock];
        return ;
    }
    
    @weakify(self);
    [self loadImage:imageView withUrl:buildUrl placeholderImage:image loadingImageMode:mode successImageMode:loadMode ani:ani success:^(SDImageCacheType cacheType){
        
        
        if (successblock) {
            successblock(cacheType);
        }
        
    } failure:^(NSError *error) {
        KSLog(@"failure buildUrl %@",buildUrl);
        
        @strongify(self);
        
        [self loadImage:imageView withUrl:url placeholderImage:image loadingImageMode:mode successImageMode:loadMode ani:ani success:^(SDImageCacheType type) {
            
            KSLog(@" 第二次加载图片成功 %@",url);
            
            if (successblock) {
                successblock(type);
            }
            
        } failure:^(NSError *e){
            
            KSLog(@" 第二次加载图片失败 %@",url);
            
            if (failureblock) {
                failureblock(e);
            }
            
        }];
        
    }];
      }

       - (void) loadImage:(UIImageView *) imageView withUrl:(NSString *) url placeholderImage:   (UIImage*)image loadingImageMode:(UIViewContentMode)mode successImageMode:(UIViewContentMode)loadMode ani:(LoadImageAnimation)ani success:(void(^)(SDImageCacheType cacheType))success failure:(void (^)(NSError *))failure {
    
    if (imageView == nil) {
        if (failure) {
            NSError *error = [[NSError alloc] initWithDomain:@"ks" code:0 userInfo:@{@"error":@"imageView is nil"}];
            failure(error);
        }
        return ;
    }
    
    imageView.contentMode = mode;
    
    NSString *urlDecode = [url decodedURLString];
    
    if ([urlDecode isEqualToString:url]){
        url = [url encodedURLString];
    }
    
    [imageView sd_setImageWithURL:[NSURL URLWithString:url] placeholderImage:image completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        if (!error) {
            
            imageView.contentMode = loadMode;
            if (cacheType == SDImageCacheTypeNone) {
                [self aniImage:imageView ani:ani];
            }
            
            if (success) {
                success(cacheType);
            }
            
            KSLog(@"加载图片成功 %@",url);
        }
        else {
            KSLog(@"加载图片错误,Url:%@, 错误信息%@",url,error);
            if (failure){
                failure(error);
            }
        }
    }];
      }

**Comment by com314159** [comment]
I sovled it by add a dispath after, like this 

      if ([self isCacheExist:url]) {
            [self getCache:url done:^(UIImage *image) {
                imageView.image = image;
            }];
        } else {
                       dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)),     dispatch_get_main_queue()
                  // do second load image
        }
     }

**Comment by victorBaro** [comment]
Same here. Solved it with Dispatch after and forgot to post it.

**Comment by mythodeia** [comment]
closing based on comments above

**Comment by AntiMoron** [comment]
@mythodeia  This should be labeled a bug. And I don't think this should be closed with a 'workaround' instead of a 'bugfix'.

**Comment by mythodeia** [comment]
@victorBaro can you check using the latest version if you encounter the same issue?

**Comment by guidev** [comment]
still there in 3.8.1

**Comment by AntiMoron** [comment]
@mythodeia  Hey, why not reopen this issue and try to fix this ?

**Comment by bpoplauschi** [comment]
We have no official 4.0 release, that is still in progress. You can look at the 4.x branch out of curiosity :)
