### ISSUE TITLE
SDWebImage and Xcode 7

### ISSUE THREAD

**Issue by nickfl** [rs/SDWebImage#1267]
Hi,
I know that <b>Xcode 7</b> is still in beta and have some internal bugs,
but is it possible that Apple again "improved" something the way that 
<b>SDWebImage</b> will need considerable changes to make it work with Xcode 7, iOS 9?
I mean, at this moment it does not work with <b>beta4</b>.

**Comment by mythodeia** [comment]
i do not have it installed as its in beta . What seems to be the problem with XCode 7 and SDWebImage?

**Comment by nickfl** [comment]
Project[39121:248990] CFNetwork SSLHandshake failed (-9824)
Project[39121:248990] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)

**Comment by mythodeia** [comment]
its not this library that causes the issue
more [here](http://stackoverflow.com/questions/30720813/cfnetwork-sslhandshake-failed-ios-9) and [here](http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/)

**Comment by holgersindbaek** [comment]
@mythodeia @nickfl It's not working with me neither. How did you guys fix it?!

**Comment by mythodeia** [comment]
@holgersindbaek check the links above.

**Comment by holgersindbaek** [comment]
@mythodeia I have checked the links above... I need a "here's what you need to do to fix this problem"-link, not a "read these many pages and you might be able to google your way to a solution somewhere in the future"-link. Is this a fixable problem or?!

**Comment by mythodeia** [comment]
@holgersindbaek i think both the links i provided, excluding the Apple one, provide solutions.
the stackoverflow one provides a solution on the 2nd answer. The other does the same thing but explains why you should pay attention to something like this. If you need more assistance i am sure someone here will assist you if you are patient.

**Comment by holgersindbaek** [comment]
@mythodeia You're right... sorry for the impatience.

**Comment by mythodeia** [comment]
no worries. if you encounter issues with any of the solutions please reply back and hopefully we can work it out. :+1:
