### ISSUE TITLE
Add a multi-cache system for context options (image size, cache size, ...)

### ISSUE THREAD

**Issue by damienrambout** [rs/SDWebImage#1270]
Hi,

There's something I'm not able to achieve with SDWebImage at the moment: Transform and cache images based on their context.
The only information the `SDWebImageManagerDelegate` gets about an image is its url, which is not enough to determine what transform (size, filter, ...) should be applied to an image.

Let's say I have an app that displays a grid of images as first. Each cell of the grid is sized 80x80. Then, in a detail view, the image is sized **200x200**.

I cannot use **500x500** images for my grid because it would have a very bad impact on the scroll performances and memory usage. Same issue for my detail view.

What I want is to cache the grid images with a size of **80x80** (maybe even crop them), but just for my grid context. Also I probably need a specific cache size for this context (grid).
Then cache my detail images  with a size of **200x200**. I believe the global delegate in its current form would not be able to achieve such a thing, because it is global.

I have been using [Haneke](https://github.com/Haneke/Haneke), which defines [caches](https://github.com/Haneke/Haneke/blob/master/Haneke/HNKCache.h) which are in charge of:
- resizing images (upscale if specified)
- defining a cache size for its context
- ...

It would also be easier to applied custom transforms (such as filters) for each context.

If SDWebImage could add a context-based multi-cache system, it would make it so much more powerful in terms of flexibility, performance, memory usage, ...
Anyway, I know it's probably a lot to ask. I don't even know if it would be achievable with the current architecture...

Tell me what you think about it.

Cheers.

**Comment by damienrambout** [comment]
Just a quick note:

I'm aware of `SDImageCache` which can be instantiated with custom a namespace and cache size. But `sd_` extension methods will always use `[SDWebImageManager sharedManager]` which will always use `[SDImageCache sharedImageCache]`.

**Comment by bpoplauschi** [comment]
@damienrambout would you be interested in implementing this add creating a PR?

**Comment by tirrorex** [comment]
Bumping that.
I actually have the same problem, since haneke downloads the image for EVERY context, would be awesome to use sdwebimage and having a custom feature for this.

**Comment by tirrorex** [comment]
The method i finally used was to create a custom class which is directly link to sdwebimage.
Basically what i do is placing an imageKey, an imageURL and a transform method as parameter.
I will store both original and modified pictures and set the modify picture for my imageview.
This way i will try to query first the modify picture, if not set in cache query the original picture and if not set i will download.
Still have some issues to solve but so far so good.

**Comment by dreampiggy** [comment]
Use `SDWebImageExternalCustomManager` in View category, this can provide a `SDWebImageMangaer` instance, which retain a `SDImageCache` with your custom cache path.

But in 5.x. We will introduce a `SDWebImageContext` which may be useful for your proposal. You can specify more information instead of just a enum of `SDWebImageOptions`(This is acutally the suck of Objective-C, Swift can associate objects to enum)

**Comment by dreampiggy** [comment]
In 5.x, you can use a `id<SDWebImageTransformer` to transform the image to another image. We also provide some basic common transformer such as rounded corner, resize, rotation, CIFilter based transformer. See #2219 for more detail information

**Comment by dreampiggy** [comment]
@damienrambout I read your use case. In 5.x, you can pass a `id< SDWebImageTransformer>` to cache query method. Which will apply the transformer on the image, and then cache the resized image to disk.
