### ISSUE TITLE
Error: No such module WebImage when try to archive project

### ISSUE THREAD

**Issue by lial** [rs/SDWebImage#1271]
Hello,
I use your library in my project (Swift, iOS 8.0, Xcode 6.4), when I run project on deivce - no error occured, but when I tried to arcive project to add then in iTunesConnect I got error that No such module WebImage (row with import WebImage).

I tried add your module using as CocoaPods as directly via Add files to project - error persists.
How can I fix this error ?

**Comment by ashchan** [comment]
Perhaps try `import SDWebImage` instead.
