### ISSUE TITLE
Supporting NSURLCredential creation with credentialWithIdentity:certificates:persistence: also, not just using username and password 

### ISSUE THREAD

**Issue by madik05** [rs/SDWebImage#1272]
At this moment certificate support is implemented by using only the mentioned method:

if (wself.username && wself.password)
{
            operation.credential = [NSURLCredential credentialWithUser:wself.username password:wself.password persistence:NSURLCredentialPersistenceForSession];
}

Please implement the other way when you would like to use a local certifiacte:

 operation.credential = [NSURLCredential credentialWithIdentity:someIdentity certificates:someCerts persistence:somePersistence

And I mean not only certifiactes in form of cer or der but also p12 certificates (so you need a path to the file or using the main bundle with file name and extension, and a password for using SecPKCS12Import). Thanks!

**Comment by bpoplauschi** [comment]
@madik05 would you be interested in creating a PR?

**Comment by bpoplauschi** [comment]
You can always set `urlCredential` from `SDWebImageDownloader` to any value you need (it's exposed).
