### ISSUE TITLE
ld: framework not found

### ISSUE THREAD

**Issue by pmcguane** [rs/SDWebImage#1273]
ld: framework not found SDWebImage-3.3
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mythodeia** [comment]
how are you installing the library? follow the steps shown [here](https://github.com/rs/SDWebImage#installation)

**Comment by pmcguane** [comment]
Using CocoaPods

Podfile
platform :ios, '6.1'
pod 'SDWebImage', '~>3.7’


pod install
Updating local specs repositories

CocoaPods 0.39.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using SDWebImage (3.7.3)
Generating Pods project
Integrating client project
Sending stats

[!] The `CoffeeSVP User [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `CoffeeSVP User [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by mythodeia** [comment]
did you add the $(inherited) flag like the installation notes suggest?

**Comment by pmcguane** [comment]
solved by updating the platform iOS from 6.1 to 6.0
