### ISSUE TITLE
From network to no network, SDWebImageRefreshCached option, image cache not working

### ISSUE THREAD

**Issue by ssddss** [rs/SDWebImage#1275]
I wonder if there was bug or my misunderstanding of  SDWebImageRefreshCached option.
my method calling:
```
[self.userHeadButton sd_setImageWithURL:[NSURL URLWithString:imageUrl]
   forState:UIControlStateNormal 
   placeholderImage:ImageNamed(@"default_boy_photo") 
   options:SDWebImageRefreshCached 
   completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
}];
```
When the network is ok,it works ok.But when I close the network  the next moment,and I call my method again.This time the placeholderImage was loaded.But the cache has been stored,why the cache not loaded?If I open my app under the status of no network,the caches were loaded.I was confused whether it exist bugs or it works the right way?

Anybody knows,Please do tell me !

**Comment by mythodeia** [comment]
@ssddss the issue is with the failedUrl array being filled when it shouldn't.
[this](https://github.com/rs/SDWebImage/pull/1297) fixes it
just test 
waiting for merge
