### ISSUE TITLE
Excuse me ,how can I get the memory cache path when I use [SDWebImageManager downloadImageWithURL...]

### ISSUE THREAD

**Issue by KittenYang** [rs/SDWebImage#1277]
I can't find any available API .Do you have any idea? Thanks indeed.

**Comment by gongqiuwei** [comment]
memory cache using NSCache, in SDImageCache.m , it has a provide property named memCache, i think the author don not allow others to change the memory cache

**Comment by KittenYang** [comment]
@gongqiuwei  Thanks, but I get the image in [SDWebImageManager downloadImageWithURL...], but I don't need the image right now,I need the diskcache path and  send it to a UIWebView.How can I get the cache path in [SDWebImageManager downloadImageWithURL...]?

**Comment by mythodeia** [comment]
@KittenYang you can use the 
```
- (NSString *)cachePathForKey:(NSString *)key inPath:(NSString *)path;
```
to get the disk cache path

**Comment by KittenYang** [comment]
Hi,Thanks @mythodeia  What is the param path? I see the doc says `@param path : the cach path root  folder` ,but I don't know what's my `root folder`.Actually,I get disk cache path like this:

```objc
        [manager downloadImageWithURL:[NSURL URLWithString:_url] options:SDWebImageHighPriority progress:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
            if (image && finished) {
               
                NSString *key = [manager cacheKeyForURL:imageURL];
                NSString *source = [manager.imageCache defaultCachePathForKey:key];
            }
        }
```

But unluckily,the `source` may be nil. I think it's because the image not really cache in disk so I get nil.So how can I get disk cache path in `- (id <SDWebImageOperation>)downloadImageWithURL:(NSURL *)url
                                         options:(SDWebImageOptions)options
                                        progress:(SDWebImageDownloaderProgressBlock)progressBlock
                                       completed:(SDWebImageCompletionWithFinishedBlock)completedBlock;` this method? Does `- (NSString *)cachePathForKey:(NSString *)key inPath:(NSString *)path;` will face the some problem of `- (NSString *)defaultCachePathForKey:(NSString *)key;` which I met? Thanks for you help.

**Comment by mythodeia** [comment]
for me this works:
```
        SDWebImageManager *manager = [SDWebImageManager sharedManager];
        [manager downloadImageWithURL:self.imageURL
                                                        options:SDWebImageHighPriority
                                                       progress:nil
                                                      completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
            if (image) {
                NSString *key = [manager cacheKeyForURL:imageURL];
                NSString *source = [manager.imageCache defaultCachePathForKey:key];
                NSLog(@"%@",source);
            }
        }];
```

**Comment by mythodeia** [comment]
closing this. if you encounter issues let us know
