### ISSUE TITLE
Getting error "Downloaded image has 0 pixels"

### ISSUE THREAD

**Issue by takdol** [rs/SDWebImage#1278]
Hi!!!

First of all, awesome work on this framework. Kudos to you!!! 

Now to the issue. The library just can't process these images: 
"https://static.spuul.com/uploads/video/horizontal_cover/10838/large_d750932e74_75aa551c66_Ala_Modalaindi_950x400.jpg",
                    "https://static.spuul.com/uploads/video/horizontal_cover/10838/medium_d750932e74_75aa551c66_Ala_Modalaindi_950x400.jpg",
                    "https://static.spuul.com/uploads/video/horizontal_cover/10838/small_d750932e74_75aa551c66_Ala_Modalaindi_950x400.jpg",
                    "https://static.spuul.com/uploads/video/horizontal_cover/10838/xsmall_d750932e74_75aa551c66_Ala_Modalaindi_950x400.jpg",
                    "https://static.spuul.com/uploads/video/horizontal_cover/10838/d750932e74_75aa551c66_Ala_Modalaindi_950x400.jpg"

I've tried adding the option **SDWebImageRetryFailed** no luck. I'm using the method **sd_setImageWithURL:placeholderImage:options:completed:** to get these images. 

I've also tried it in the sample demo and still no luck. It's returning the error, **Downloaded image has 0 pixels**

**Comment by mythodeia** [comment]
@takdol are you using the latest version? several changes have been made regarding this issue

**Comment by takdol** [comment]
Yes, I've just cloned the repo yesterday

**Comment by mythodeia** [comment]
go to SDWebImageDecoder.m and replace this:
```
   bool unsupportedColorSpace = (imageColorSpaceModel == 0 || imageColorSpaceModel == -1 || imageColorSpaceModel == kCGColorSpaceModelIndexed);
```
with this:
```
    bool unsupportedColorSpace = (imageColorSpaceModel == 0
                                  || imageColorSpaceModel == -1
                                  || imageColorSpaceModel == kCGColorSpaceModelIndexed
                                  || imageColorSpaceModel == kCGColorSpaceModelCMYK);
```

**Comment by mythodeia** [comment]
closing this. please reopen if you still have issues

**Comment by takdol** [comment]
Works! Thanks @mythodeia!!!

**Comment by ibnusina** [comment]
Hi,
I have image with link : https://harper.bridestory.com/image/upload/fl_progressive,f_auto,c_scale,q_80,w_134,dpr_2/v1500286382/k9pjbfqfidjvp5ccfwhr.png, it can be accessed from browser but, it failed to load when using **sd_setImageWithURL:placeholderImage:options:completed:**.
I also get no image data in 
`SDWebImageDownloadToken *subOperationToken = [self.imageDownloader downloadImageWithURL:url options:downloaderOptions progress:progressBlock completed:^(UIImage *downloadedImage, NSData *downloadedData, NSError *error, BOOL finished) {
                __strong __typeof(weakOperation) strongOperation = weakOperation;
                if (!strongOperation || strongOperation.isCancelled) {
                    // Do nothing if the operation was cancelled
                    // See #699 for more details
                    // if we would call the completedBlock, there could be a race condition between this block and another completedBlock for the same object, so if this one is called second, we will overwrite the new data
                } else if (error) {
                    [self callCompletionBlockForOperation:strongOperation completion:completedBlock error:error url:url];`
Can you help me regarding to this problem? Thank you.

**Comment by mythodeia** [comment]
@ibnusina can you try the url in the demo project using the latest version?

**Comment by ibnusina** [comment]
@mythodeia ok, thanks for your help.

**Comment by VikasPrajapati27** [comment]
I am facing the same issue, getting "Downloaded image has 0 pixels" error message.
Using SDWebImage 4.3.3

**Comment by mythodeia** [comment]
@VikasPrajapati27 please try the url of the image you are facing a problem, with our latest demo project

**Comment by VictorZhang2014** [comment]
I have encountered the problem too, and my solution was done by ADDING `"SD_WEBP=1"` into your `SDWebImage` target -> `Build Settings` -> `Preprocessor Macros`.

<img width="897" alt="WX20210408-213028@2x" src="https://user-images.githubusercontent.com/6853884/114035986-3a05ee80-98b2-11eb-880e-17423c0a460b.png">
