### ISSUE TITLE
Cached Images Get Deleted without calling clearDisk

### ISSUE THREAD

**Issue by MohamedSaad** [rs/SDWebImage#1281]
I have issue that Cached Images sometimes get deleted without calling the clearDisk.

I have checked the logic and found that cached Images are saved to Library/Caches folder, which according to apple's documentation don't get deleted unless user do full restoration to device, and it's guaranteed to be available after app updates.

"Application_Home/Library/Caches Use this directory to write any application-specific support files that you want to persist between launches of the application or during application updates. Your application is generally responsible for adding and removing these files. It should also be able to re-create these files as needed because iTunes removes them during a full restoration of the device. In iOS 2.2 and later, the contents of this directory are not backed up by iTunes."

Do the SDWebImage delete any cached images under any situation ( e.g low disk space) or cached reached MaxCacheAge?

**Comment by MohamedSaad** [comment]
Also if "/Library/Caches" can be deleted by iOS for any reason, can i switch cache path for some of my images to Document folder instead Caches?

**Comment by mythodeia** [comment]
@MohamedSaad check [this](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDImageCache.m#L475) method.
it removes files that are older than the expiration date & if remaining disk cache exceeds a configured maximum size it deletes the older files first.
the ```cleanDisk``` method is called when this notification is received ```UIApplicationWillTerminateNotification``` & ```UIApplicationDidEnterBackgroundNotification```
the mem cache on the other hand is cleared when this is notification is received: ```UIApplicationDidReceiveMemoryWarningNotification```

check [this](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDImageCache.h#L95) if you want a custom cache path

**Comment by MohamedSaad** [comment]
Thanks!
