### ISSUE TITLE
disconnect from network, try download a image, connect back to network, and the url never loads because it is stored in the "failedURLs"

### ISSUE THREAD

**Issue by cristi1900** [rs/SDWebImage#1282]
So , when I am going offline with my app , and go over a few images that have not been downloaded yet while offline, when coming back, those images never download again. Because they are marked as failed urls and simply ignored from this point forward.
SDWebImageManager line 131.

**Comment by mythodeia** [comment]
@cristi1900 the code that checks whether the url should be added to the failedUrl array is [here](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.m#L195)
are you testing with the latest version?

**Comment by cristi1900** [comment]
@mythodeia  Thanks for the answer, I did not see that line. Yes, I have the latest version from the pod.
But there is the second condition   

<code>BOOL shouldBeFailedURLiOS7 = (NSFoundationVersionNumber > NSFoundationVersionNumber_iOS_6_1 && error.code != NSURLErrorInternationalRoamingOff && error.code != NSURLErrorCallIsActive && error.code != NSURLErrorDataNotAllowed);</code>

Which returns true , since the error code is -1009 for not connected to the internet,
and it checks if the code is neither of the [-1018,-1019,-1020] and i'm running this on iOS 8.1.

So we end up having one flag true, and the other one false in the following if 

shouldBeFailedURLAlliOSVersion = NO;
shouldBeFailedURLiOS7 = YES;

<code>if (shouldBeFailedURLAlliOSVersion || shouldBeFailedURLiOS7) {
                         @synchronized (self.failedURLs) {
                             [self.failedURLs addObject:url];
                         }
                    } 
</code>
                  
In the end , it just adds my urls to the failed urls, and never downloads them after I connect back to the internet, until I restart the app.

**Comment by mythodeia** [comment]
thanks for the report. if you have a fix please submit a PR

**Comment by mythodeia** [comment]
waiting for https://github.com/rs/SDWebImage/pull/1297
it has much cleaner implementation on failedUrl handling
