### ISSUE TITLE
Native Linking Error

### ISSUE THREAD

**Issue by fjorn** [rs/SDWebImage#1283]
I am getting several errors with Native linking:
Native linking failed, duplicate symbol: '_WebPInitUpsamplersNEON'

I looked for other 3rd party libraries that might use SDWebImage, but I do not think that any of them do.

**Comment by mythodeia** [comment]
@fjorn this is from ```UIImage+WebP.h``` [file](https://github.com/rs/SDWebImage/blob/master/SDWebImage/UIImage%2BWebP.h).
have you added the file twice? how are you installing the library?

**Comment by fjorn** [comment]
I added the library via visual studio through adding a component. The file
is added once to references.

**Comment by mythodeia** [comment]
visual studio in windows? i thought coding from visual studio was still in beta...
sorry i cannot help you in this as i have no knowledge of adding the library from visual studio.
i can only guess is that visual studio did not exactly clone the repository with all the dependencies.

**Comment by fjorn** [comment]
I will ask the question on the Xamarin forum. Thank you!

**Comment by mythodeia** [comment]
best of lucj :+1:
