### ISSUE TITLE
SDWebImage cannot get the image which has a comma

### ISSUE THREAD

**Issue by sushipan** [rs/SDWebImage#1284]
Hi,
help!
SDWebImage cannot get the image which has a comma 
example http://t11.baidu.com/it/u=3284650870,444980659&fm=22
but can get by Firefox or other web browser

**Comment by mythodeia** [comment]
@sushipan the error code for this url is:
```
Error Domain=NSURLErrorDomain Code=403 "The operation couldn’t be completed. (NSURLErrorDomain error 403.)"```

**Comment by sushipan** [comment]
@mythodeia 
I know , But if I get it with  Firefox or Safari , I can get the right image

**Comment by mythodeia** [comment]
@sushipan check [this](https://github.com/rs/SDWebImage/issues/1228)

**Comment by sushipan** [comment]
Thank you very much  !
