### ISSUE TITLE
UIImage Fix orientation

### ISSUE THREAD

**Issue by zhangyicococo** [rs/SDWebImage#1288]
This seems not working
```
image = [UIImage imageWithCGImage:image.CGImage scale:image.scale orientation:orientation];
```

**Comment by zhangyicococo** [comment]
UIImage+MultiFormat.m  should be changed like this

#import "UIImage+FixOrient.h"

+ (UIImage *)sd_imageWithData:(NSData *)data {
    if (!data) {
        return nil;
    }
    
    UIImage *image;
    NSString *imageContentType = [NSData sd_contentTypeForImageData:data];
    if ([imageContentType isEqualToString:@"image/gif"]) {
        image = [UIImage sd_animatedGIFWithData:data];
    }
#ifdef SD_WEBP
    else if ([imageContentType isEqualToString:@"image/webp"])
    {
        image = [UIImage sd_imageWithWebPData:data];
    }
#endif
    else {
        image = [[UIImage alloc] initWithData:data];
        UIImageOrientation orientation = [self sd_imageOrientationFromImageData:data];
        if (orientation != UIImageOrientationUp) {
            image = [image fixOrientation];
#if 0
            image = [UIImage imageWithCGImage:image.CGImage
                                        scale:image.scale
                                  orientation:orientation];
#endif
        }
    }


    return image;
}

**Comment by mythodeia** [comment]
@zhangyicococo to make that change we need to see the code behind the ```UIImage+FixOrient.m" file 
As i can see the ```fixOrientation``` method exists in a new category

**Comment by mythodeia** [comment]
closing this. if you have more info please reopen
