### ISSUE TITLE
How to setting different http headers

### ISSUE THREAD

**Issue by newbbydong** [rs/SDWebImage#1289]
Now,i'm meeting the problem that every picture has different http headers and i have to setting it before downloading:

SDWebImageDownloader *manager = [SDWebImageManager sharedManager].imageDownloader;
[manager @"value" forHTTPHeaderField:@"key];
[self.imageView sd_setImageWithURL:[NSURL URLWithString:str]];

But when i set many pictures,only the final picture i can load.How can i sovle this problem?

**Comment by mythodeia** [comment]
it can be done. check [this](https://github.com/rs/SDWebImage/pull/514)
