### ISSUE TITLE
NSURLConnection has been deprecated, please use NSURLSession

### ISSUE THREAD

**Issue by zdrjson** [rs/SDWebImage#1291]

**Comment by bpoplauschi** [comment]
We will achieve this by replacing our custom network component with AFNetworking which allows using `NSURLSession` or `NSURLConnection`

**Comment by hovox** [comment]
Why not to use raw NSURLSession ? I think there is no need to add dependency to other network for that

**Comment by macdrevx** [comment]
+1 against adding AFNetworking as a dependency.

**Comment by justindhill** [comment]
Another +1 against adding AFNetworking as a dependency.

**Comment by adle29** [comment]
+1 against adding AFNetworking as a dependency.

**Comment by arielelkin** [comment]
This has been going on for more than a year now.
https://github.com/rs/SDWebImage/issues/823
https://github.com/rs/SDWebImage/issues/1318

It would be good to have some clarity. We need to know if and when the migration to NSURLSession is planned for, and if it'll depend on AFNetworking. Could we please have an update?

**Comment by bpoplauschi** [comment]
I think the migration will be to AFNetworking, I hope I can find the time for that and the other things that need to be done

**Comment by kconner** [comment]
+1 against. I would probably find another image cache if SDWebImage depended on AFNetworking. NSURLSession is capable, won't add code size, and typically only requires you to call a convenience method or two.

**Comment by flightblog** [comment]
I agree with @kconner.

**Comment by prachigauriar** [comment]
I’d also find another image cache if AFNetworking were added as a dependency. Because NSURLConnection is deprecated, people will be migrating to NSURLSession anyway, so supporting both isn’t really that important, right?

**Comment by bpoplauschi** [comment]
Guys, help me out here. I was almost sure that not having to maintain networking code for this library is a good thing and relying on a library like AFNetworking for the network component would add value. Is adding a dependency the issue here?

**Comment by kconner** [comment]
Yeah, I'd say that adding AFNetworking as a dependency is the issue. The code you write for NSURLSession would be almost as short, if that helps. I'd rather not have child dependencies, because I use SDWebImage as a drop-in solution for fetching images. I like it because it feels fast and light and won't complicate my namespaces more than necessary. Libraries like AFNetworking are useful to me, some of the time, but I'd rather make that decision per-app. SDWebImage, on the other hand, I want to use in nearly every app, so I don't want it to feel like it will cost more code size, link time, security risk, etc.

**Comment by prachigauriar** [comment]
@bpoplauschi I avoid using AFNetworking in basically all my projects now. It’s a lot of code that doesn’t really do much that can’t also be accomplished with NSURLSession. But SDWebImage is still something I like and rely on. Having it bring along a huge dependency (and its potential bugs) makes SDWebImage less attractive. 

FWIW, I was able to strip all of AFNetworking out of a project and replace it with NSURLSession in about a day. AFNetworking’s value is much diminished at this point.

**Comment by bpoplauschi** [comment]
Ok, got it. I will rethink this and try to do it without AFNetworking. (The reasoning was to avoid all kinds of fixes for the networking component and I can definitely say AFNetworking is still properly maintained and has a good code quality, but I understand what you are saying).

**Comment by Ge0rges** [comment]
Seems like using AFNetworking would be more work then just fixing the single depreciation no?

**Comment by bpoplauschi** [comment]
Resolved by #1578

**Comment by bpoplauschi** [comment]
3.8.0 version was just released.

**Comment by arielelkin** [comment]
👍
