### ISSUE TITLE
Unable to animate local gif file?

### ISSUE THREAD

**Issue by snowywolfie** [rs/SDWebImage#1292]
I tried to load the gif file into UIImage, but it is not animating. Am I using a incorrect way to do this?

Here my code....

 UIImage *imageTest = [UIImage sd_animatedGIFNamed:@"dragon.gif"];
 [self.image1 setImage:imageTest];

**Comment by bpoplauschi** [comment]
We will replace the GIF component in the next version and everything should work.

**Comment by bpoplauschi** [comment]
@snowywolfie  We have replaced our GIF component with a library from Flipboard (FLAnimatedImage). Could you try our 4.x branch ([instructions](https://github.com/rs/SDWebImage/tree/4.x#animated-images-gif-support)) and see if it helps?
