### ISSUE TITLE
[QUESTION]: Next Release

### ISSUE THREAD

**Issue by portellaa** [rs/SDWebImage#1293]
Hello,

Do you have a date to the next release?
We have some crashes related with the callback call in the `SDWebImageDownloader` at line 145.

Many thanks

**Comment by brizzly** [comment]
I would like to know the release date too, as I get same kind of crash at line : 173

SDWebImageDownloader.m line 173
__72-[SDWebImageDownloader downloadImageWithURL:options:progress:completed:]_block_invoke102

https://github.com/rs/SDWebImage/issues/1299

**Comment by nsnutella** [comment]
Until the release comes out, we are using the `master` version.

**Comment by brizzly** [comment]
What is that ? I'm using the latest official release.

**Comment by nsnutella** [comment]
The version from `master`.
Instead of `pod 'SDWebImage', '~>3.7.3'` use `pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git', :branch => 'master'`

**Comment by brizzly** [comment]
didn't know! thx.

**Comment by bpoplauschi** [comment]
Version 3.7.4 is out.
