### ISSUE TITLE
UIApplication * app = [UIApplicationClass performSelector:@selector(sharedApplication)];

### ISSUE THREAD

**Issue by MuthurajMuthulingam** [rs/SDWebImage#1294]
I tried SDWebImage without cocoapods integration, Since I linked all source files of SDWebimage within my project, 
it returns me, Compile time error, status ARC semantic error, on above line. Please provide me a solution,
Kindly note, This only returns for Device build.

Thanks
![screen shot 2015-09-15 at 12 38 27 pm](https://cloud.githubusercontent.com/assets/10783559/9870170/6b4f78a6-5ba7-11e5-8f16-26ac78348eec.png)

**Comment by mythodeia** [comment]
how did you install the files? did you just copy them to your project?
whats the error you are getting exactly?

**Comment by MuthurajMuthulingam** [comment]
I copied all source files into my project and build for Device (not simulator, since simulator works fine).

![screen shot 2015-09-15 at 4 06 12 pm](https://cloud.githubusercontent.com/assets/10783559/9874568/6f62a612-5bc4-11e5-9ec5-5aefff1b7a34.png)

 [UIApplication performSelector:@selector(sharedApplication)];

**Comment by mythodeia** [comment]
can you replicate it in the demo project? i tried to build the demo project for device and it has no issues

**Comment by MuthurajMuthulingam** [comment]
Please find screenshot of Demo Project

![screen shot 2015-09-15 at 5 26 09 pm](https://cloud.githubusercontent.com/assets/10783559/9875900/a2acbd04-5bcf-11e5-8b1b-bc145d17f6a3.png)

**Comment by mythodeia** [comment]
you are building the framework WebImage and not the demo project

**Comment by MuthurajMuthulingam** [comment]
How Could I SDWebImage without pods dependancies, Since I need to maintain  pods free version of my custom framework.

What exactly the issue means ?

**Comment by mythodeia** [comment]
the 'no known class method for selector' means that the compiler cannot find the sharedApplication method to run. are you using the latest version of the library?

**Comment by mythodeia** [comment]
closing this. if you still face issues please reopen
