### ISSUE TITLE
SDWebImage - Image from url didn't replace placeholder image after it's finished download

### ISSUE THREAD

**Issue by Crementae** [rs/SDWebImage#1295]
I'm using SDWebImage to download and cache images in an UIImageView asynchronously but I'm facing some problems. 

In my project I create a pin marker which has a dialogue box that have UIImageView in it.

The problem that I face is the image from url didn't replace place holder image after it's finished download. The first click on pin marker will always display the place holder image.

The image from url will only display after I click pin marker for the second time.

I want to display image from the url in the first click what should I do?

here is my code
```
    -(UIView *)mapView:(GMSMapView *)mapView markerInfoWindow:(GMSMarker *)marker{
PlaceData *currentMarker = [self findDataByMarker:marker];

UIView *dialogView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 261, 95)];

// Create background image
UIImageView *dialogBackground = [[UIImageView alloc] initWithImage: [UIImage imageNamed:@"MapDialog.png"]];
[dialogView addSubview:dialogBackground];

UIImageView * thumbnail = [[UIImageView alloc] init];

[thumbnail sd_setImageWithURL:[NSURL URLWithString:currentMarker.thumbnail] placeholderImage:[UIImage imageNamed:@"placeholder.png"] options:SDWebImageRefreshCached];

NSLog(@"URL %@", currentMarker.thumbnail);
NSLog(@"thumbnail %@",thumbnail);

CGRect tmpFrame = thumbnail.frame;
tmpFrame.origin.x = 15;
tmpFrame.origin.y = 14;
tmpFrame.size.width = 55;
tmpFrame.size.height = 55;
thumbnail.frame = tmpFrame;
thumbnail.contentMode = UIViewContentModeScaleToFill;
[dialogView addSubview:thumbnail];

return dialogView;

```
PS. Please help me solve this problem and sorry for my english.

**Comment by mythodeia** [comment]
@Crementae 
the ```sd_setImageWithURL``` is asynchronous which means the code will continue beyond this method without waiting for the actual image to download. You can use the ```sd_setImageWithURL:placeholderImage:options:completed``` method and do what you need in the completion block

**Comment by Crementae** [comment]
@mythodeia thanks for your answer! I'm still a beginner programmer. Can you provide me some example please.

**Comment by mythodeia** [comment]
you could use the code below to know when the image has finished downloading and adjust your code logic based on that. if still you have issues please upload a demo project so we can check it out.
```
    [thumbnail sd_setImageWithURL:URL
                      placeholderImage:PLACEHOLDER
                               options:OPTIONS
                              completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
// This is the completion block of the method. 
// When this is called it means that the image has finished downloading
                              }];
```

**Comment by Crementae** [comment]
@mythodeia thanks for reply, i will upload my project demo later.

**Comment by mythodeia** [comment]
please give it a shot first and if you do not succeed then post the project so everyone can have a look and help.

**Comment by Crementae** [comment]
@mythodeia 
```
UIImageView * thumbnail = [[UIImageView alloc] init];
    NSURL *urlToPicture1 = [NSURL URLWithString:currentMarker.thumbnail];
    [thumbnail sd_setImageWithURL:urlToPicture1 placeholderImage:[UIImage imageNamed:@"placeholder.png"] options:SDWebImageProgressiveDownload completed:^(UIImage * image, NSError * error,SDImageCacheType cachedType, NSURL * imageURL){
           
        if(image){
            [thumbnail setImage:image];     
            NSLog(@"Complete = %d, error = %@",cachedType, error);

        }
    }];
```
From the code above I figured it out from NSLog that URL image will start download after I clicked pin marker for the first time.

Here is NSLog image after clicked pin marker for the first time.
![Image of first]
(http://s18.postimg.org/6npgsj6ex/first.jpg)

After I clicked pin marker for the second time it will display URL image that was downloaded after the first clicked. 
Here is NSLog image after clicked pin marker for the second time.
![Image of second]
(http://s2.postimg.org/qcfugnf8p/second.jpg)

What I need to do is I need to make UIImageView replace the place holder image to URL image after URL image finished download but I don't know how to do it.

**Comment by mythodeia** [comment]
you do not need this to display the image
```[thumbnail setImage:image];```
please upload a demo project so everyone can test

**Comment by Crementae** [comment]
@mythodeia  here is my project.
https://github.com/Crementae/-Project---Demo

**Comment by mythodeia** [comment]
1st of all ```currentMarker.thumbnail``` should be NSString or NSUrl not an NSArray.
2nd you are loading large images to use as thumbnails. You need to use smaller resolution for thumbnails.

According to google maps [documentation](https://developers.google.com/maps/documentation/ios-sdk/marker#info_windows):
```
The info window is rendered as an image each time it is displayed on the map. This means that any changes to its properties while it is active will not be immediately visible. The contents of the info window will be refreshed the next time that it is displayed.
```
Issue discussed [here](https://code.google.com/p/gmaps-api-issues/issues/detail?id=5559)

i also tried [this](http://stackoverflow.com/questions/27097712/how-to-refresh-marker-info-window-in-ios-google-maps-with-afnetworking-image-cac) workaround  and [this](http://stackoverflow.com/questions/17342320/how-to-force-refresh-contents-of-the-markerinfowindow-in-google-maps-ios-sdk?lq=1) which also do not work.

i will close this issue as this is not a problem with the library, rather than an issue with google maps framework

**Comment by Crementae** [comment]
@mythodeia ok, I got it. thanks for your answer.

**Comment by bpoplauschi** [comment]
@mythodeia thanks for investigating and clearing it up

**Comment by IlyaBaudin** [comment]
```
marker.tracksInfoWindowChanges = true
mapInfoView.configureMarker(withUser: markerData) { (complete) in
     if complete {
          marker.tracksInfoWindowChanges = false
     }
}
```

confiureMarker function with completionHandler
```
avaImage.sd_setImage(with: imageUrl,
                     placeholderImage: #imageLiteral(resourceName: "placeholder"),
                     options: SDWebImageOptions(rawValue: 0), 
                     completed: { (image, error, cacheType, imageUrl) in
                        completionHandler(true)
})
```

something like this.
found some information in stackoverflow and make my code.
simple and clear.

**Comment by NaiyerAghaz** [comment]
Please check the info.plist is added these code or not
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
    <key>NSExceptionDomains</key>
    <dict>
        <key>example.com</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
            <key>NSIncludesSubdomains</key>
            <true/>
        </dict>
    </dict>
</dict>
```
