### ISSUE TITLE
SDWebImageManager release crash in NSOperationQueue (QOS: USER_INITIATED)

### ISSUE THREAD

**Issue by brizzly** [rs/SDWebImage#1299]
In the last release 3.7.3 I get many crashes like that ..

SDWebImageDownloader.m line 173
__72-[SDWebImageDownloader downloadImageWithURL:options:progress:completed:]_block_invoke102

Crashed: NSOperationQueue 0x18017c50 :: NSOperation 0x182c2130 (QOS: USER_INITIATED)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x00000010

Thread : Crashed: NSOperationQueue 0x18017c50 :: NSOperation 0x182c2130 (QOS: USER_INITIATED)
0  libobjc.A.dylib                0x36d6f708 objc_release + 7
1  libsystem_blocks.dylib         0x372fcae1 _Block_release + 216
2  libsystem_blocks.dylib         0x372fcae1 _Block_release + 216
3  CoachGuitar                    0x00054cb1 __destroy_helper_block_31 (UIImageView+WebCache.m)
4  libsystem_blocks.dylib         0x372fcae1 _Block_release + 216
5  CoachGuitar                    0x000fa241 __destroy_helper_block_127 (SDWebImageManager.m)
6  libsystem_blocks.dylib         0x372fcae1 _Block_release + 216
7  CoreFoundation                 0x289a8e4d CFRelease + 600
8  CoreFoundation                 0x289c0f7f -[__NSDictionaryM dealloc] + 134
9  libobjc.A.dylib                0x36d6fd5f objc_object::sidetable_release(bool) + 166
10 CoreFoundation                 0x289a8e4d CFRelease + 600
11 CoreFoundation                 0x289bc4cf -[__NSArrayI dealloc] + 66
12 libobjc.A.dylib                0x36d6fd5f objc_object::sidetable_release(bool) + 166
13 CoachGuitar                    0x00127a93 __72-[SDWebImageDownloader downloadImageWithURL:options:progress:completed:]_block_invoke102 (SDWebImageDownloader.m:173)
14 CoachGuitar                    0x00069e8b -[SDWebImageDownloaderOperation connection:didFailWithError:] (SDWebImageDownloaderOperation.m:419)
15 CFNetwork                      0x285e5e29 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 56
16 CFNetwork                      0x285e5de3 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 182
17 CFNetwork                      0x285e5f05 -[NSURLConnectionInternal _withConnectionAndDelegate:] + 36
18 CFNetwork                      0x285d3829 _NSURLConnectionDidFail(_CFURLConnection*, __CFError*, void const*) + 84
19 CFNetwork                      0x2859879b ___ZN27URLConnectionClient_Classic17_delegate_didFailEP9__CFErrorU13block_pointerFvvE_block_invoke + 86
20 CFNetwork                      0x285970d5 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 60
21 CFNetwork                      0x284eaa35 RunloopBlockContext::_invoke_block(void const*, void*) + 60
22 CoreFoundation                 0x289b3c6d CFArrayApplyFunction + 36
23 CFNetwork                      0x284ea8ef RunloopBlockContext::perform() + 182
24 CFNetwork                      0x284ea7b5 MultiplexerSource::perform() + 216
25 CFNetwork                      0x284ea649 MultiplexerSource::_perform(void*) + 48
26 CoreFoundation                 0x28a69faf __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
27 CoreFoundation                 0x28a693bf __CFRunLoopDoSources0 + 218
28 CoreFoundation                 0x28a67a25 __CFRunLoopRun + 772
29 CoreFoundation                 0x289b4201 CFRunLoopRunSpecific + 476
30 CoreFoundation                 0x289fcf23 CFRunLoopRun + 98
31 CoachGuitar                    0x00068285 -[SDWebImageDownloaderOperation start] (SDWebImageDownloaderOperation.m:117)
32 Foundation                     0x297cefc7 __NSOQSchedule_f + 186
33 libdispatch.dylib              0x372c8729 _dispatch_queue_drain + 1468
34 libdispatch.dylib              0x372c2aad _dispatch_queue_invoke + 84
35 libdispatch.dylib              0x372c9f9f _dispatch_root_queue_drain + 394
36 libdispatch.dylib              0x372cb3c3 _dispatch_worker_thread3 + 94
37 libsystem_pthread.dylib        0x37427dc1 _pthread_wqthread + 668
38 libsystem_pthread.dylib        0x37427b14 start_wqthread + 8

**Comment by bpoplauschi** [comment]
Let's close this issue, see if it happens again with 4.0.0 (4.0.0-beta is available for download, 4.0.0 official release is on its way).
