### ISSUE TITLE
“Memory Warning” and Crash when load a GIF image.

### ISSUE THREAD

**Issue by developforapple** [rs/SDWebImage#1300]
[self.imageView sd_setImageWithURL:[NSURL URLWithString:@"http://netdna.webdesignerdepot.com/uploads7/7-secrets-for-enhancing-ux-with-micro-interactions/001b.gif"]];

Allocations 300+ MB memory after run this code;  App crash after a moment.

**Comment by mythodeia** [comment]
@developforapple please read #945 
we are planning on replacing our GIF component with another one.
closing this as there is no need to add another GIF issue.
thanks
