### ISSUE TITLE
completion handler called before image is save to disk

### ISSUE THREAD

**Issue by ghazel** [rs/SDWebImage#1301]
I'm using SDWebImage to fetch images to disk for QLPreviewController (which only accepts `file://` urls). However, often in the completion callback, the image has not made it to disk yet. This is because the save operation is queued and then the completion callback is called without waiting:

https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.m#L233

Any advice?

**Comment by ghazel** [comment]
https://github.com/rs/SDWebImage/issues/967 https://github.com/rs/SDWebImage/issues/339

**Comment by mythodeia** [comment]
@ghazel #967 talks about adding a filename extension to the cached file. [this](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.m#L233) shows that the completion block is fired using ```sync``` not ```async``` so it fires after the ```storeImage``` is made.

**Comment by ghazel** [comment]
storeImage appears to use `async`, not `sync`:

https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDImageCache.m#L209

**Comment by mythodeia** [comment]
missed that, you are right indeed! Can you propose a solution for that?

**Comment by ghazel** [comment]
Adding yet another even to the ioQueue for the completion would do it (as long as it's serial, which it is). Kinda hacky, but simple. Something like:

```objc
dispatch_async(self.ioQueue, ^{
    dispatch_main_sync_safe(^{
        if (!weakOperation.isCancelled) {
            completedBlock(downloadedImage, nil, SDImageCacheTypeNone, finished, url);
        }
    });
});
```

**Comment by ghazel** [comment]
The Right Way would probably be to add a completion callback to `storeImage`.

**Comment by mythodeia** [comment]
Both ways are fine since the queue is serial but i would add a completion block to the storeImage. @bpoplauschi what do you think?

**Comment by ghazel** [comment]
Although I should mention, another consideration here is the most users probably don't care about when the file written to the disk cache.  If you were, say, trying to set images on a UIImageView as quickly as possible, waiting for the file to write to disk would slow things down.

**Comment by zapjonny** [comment]
I need this. I need the path of the image for a local notification attachment.

**Comment by bpoplauschi** [comment]
@zapjonny this thread was sleeping :) let us know if we can help you in any way, but we won't be able to do much. Only if you have an idea on how to implement this

**Comment by zapjonny** [comment]
My idea was to save the uiimage to disk myself, if possible, then use that completion handler...

**Comment by bpoplauschi** [comment]
Looking at the latest version of SDWebImage, I know we have refactored the `SDImageCache.storeImage` methods to be async, so they support a completion block. The issue now is the calls from `SDWebImageManager` just pass nil as the completion block for the `storeImage` on disk. But that is for a sound reason, since it is harder to make sure we call the completion after both saving on disk and returning the image are complete.

You can try to save the `UIImage` yourself, that way you will have control over the completion block.

**Comment by dreampiggy** [comment]
I think this should be treated as a "feature". If you really want to ensure the completion block is called after the disk image cache saved, save it manually after the completion block called.

If you think that you need the original inage data and want to save the disk cache processing happend during a background queue without any extra waste, see that 'SDWebImageInternalSetImageGroupKey' in 'UIView+WebCache'. This may solve something :)
