### ISSUE TITLE
Add support for tvOS

### ISSUE THREAD

**Issue by renssies** [rs/SDWebImage#1302]
tvOS relies heavenly on images that come from servers so SDWebImage is perfect since the Photos framework is not support on tvOS. 

The core of SDWebImage seems to work fine when you run it on tvOS.

**Comment by rs** [comment]
What's the issue then?

**Comment by renssies** [comment]
When cocoapods supports tvOS it should add the ```s.tvos.deployment_target = '9.0'``` to the podspec and exclude the MapKit subspec for tvOS.

**Comment by aleph7** [comment]
It works with carthage as long as you delete files that reference MapKit

**Comment by hoseking** [comment]
The above PR adds a tvOS framework target, it is working for us using Carthage.

**Comment by maremmle** [comment]
Using a custom podspec so I could add `s.tvos.deployment_target = '9.0'` it also works seamless with Cocoapods.

**Comment by waterclock** [comment]
Does SDWebImage caching properly handle the lack of a persistent cache on tvOS?

**Comment by orta** [comment]
@waterclock - yeah it's working, I've been using it extensively on https://github.com/artsy/emergence - not looked too deep into the file image cache bits though

**Comment by orta** [comment]
Though the GM is giving me this error on the tv:

```
2015-10-22 09:25:23.842 Artsy Shows[173:6744] [/BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreUI/CoreUI-370.8/Bom/Storage/BOMStorage.c:517] <memory> is not a BOMStorage file
```

**Comment by orta** [comment]
To quote an [apple employee](https://forums.developer.apple.com/thread/21723): 

> Thanks for the build log, this is a harmless message that can be ignored.

**Comment by ehynds** [comment]
Also wondering if SDWebImage supports remote download of the new lsr layered images. A quick test shows that it does not, but haven't been able to dig into it too far.

**Comment by renssies** [comment]
I gave it go yesterday but it does not yet support it. If nobody is working on it, I might do it later. 

Currently I solved it by having my image locally, since it's only one image.

**Comment by bpoplauschi** [comment]
@renssies any help is appreciated :)

**Comment by ehynds** [comment]
@renssies when you gave it a go the other day, did you have any luck downloading a remote LSR at all? Even this super basic example produces a nil UIImage:

```swift
if let url = NSURL(string: "http://path/to/my/layered/image.lsr") {
    if let data = NSData(contentsOfURL: url) {
        let image = UIImage(data: data)
        imageView?.image = image
     }
 }
```

**Comment by syedabdulsamad** [comment]
Can some one guide me how i can integrate it in my TVOS project? I am writing this project in Swift? So some steps will be a great help.
Thanks

**Comment by waterclock** [comment]
Cocoapods won't work yet as far as I know. I simply copied the classes and manually added the frameworks. Works well on Simulator, haven't tested on actual device. As far as Swift, once integrated into the project it should be like accessing any other Objective-C code.

**Comment by orta** [comment]
Right now for CocoaPods support you'd need to use my gem to allow using a Pod on any platform. You're probably better off adding `tvos` to the podspec so it works for everyone.

**Comment by antoniocasero** [comment]
:+1:

**Comment by hoseking** [comment]
@syedabdulsamad the above PR has been merged, point your pod to 30e9e0b516cca03d9f2abe75a91512d75b846406 to get tvOS support.

**Comment by dWoeckel** [comment]
hi and thanks for adding tvos support :) could you please add the updated podspec to the CocoaPods spec repo? though the version number is the same, sadly the tvos support is still missing there. I would like to add SDWebImage as a dependency, but could not integrate it due to CocoaPods lacking support of git references. Thanks a lot! :)

**Comment by orta** [comment]
( @dWoeckel CocoaPods does [git references](https://guides.cocoapods.org/syntax/podfile.html#pod), e.g. `pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git', :commit => '082f8319af'`  )

**Comment by dWoeckel** [comment]
@orta thanks for your reply :) I know how it works in the podfile, but I need it in my podspec , because I'm trying to add SDWebImage as a dependency for a private pod I'm working on
