### ISSUE TITLE
ios9 SDWebImage 3.7.3 use tableView Load picture will have a lot of duplicate disk cache! Image URL is the same

### ISSUE THREAD

**Issue by Yexinglong** [rs/SDWebImage#1303]

**Comment by mythodeia** [comment]
can you replicate using the sample project?

**Comment by Yexinglong** [comment]
Sorry, I do not know SDWebImage problem, ios8 system data and presentation is normal, I look at the data in the cache simulator inside SDWebimage above, we found no repetition! But now the project which does not use any associated storage method, simply load SDWebImage big picture on the TableView, use ios9 real machine,
Example unable to show demo
Only code block
 WS(ws)
        __weak MiYiTagEditorImageView *weakImageView =tagEditorImageView;
        dynamicScrollView.imageRefreshBlock= ^(NSString * imageIndex ,id image)
        {       
        //Inside the operation did not use any storage

            [weakImageView removeTag];
            NSString *imageString =image;
            [weakImageView.previewsImage sd_setImageWithURL:[NSURL URLWithString:imageString] placeholderImage:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                [weakImageView imageTagFrame:YES];
                MiYiPostsImageSModel *model =[MiYiPostsImageSModel objectWithKeyValues:ws.postDetailsModel.images[[imageIndex intValue]]];
                for(int i =0 ; i<model.tags.count ;i++){
                    MiYiPostsImageTagIdsModel *tagModel = [MiYiPostsImageTagIdsModel objectWithKeyValues: model.tags[i]];
                    if (tagModel.tag_content.length!=0) {
                        [weakImageView addtagViewimageClickinit:CGPointZero isClick:NO mode:tagModel];
                    }
                }
            }];
        };

**Comment by mythodeia** [comment]
sorry i am a little bit confused. You experience issues only in IOS 9? Does it work in IOS 8?
The cache files are saved to disk using the MD5 of the url as a filename. So how do you mean duplicate disk cache?

**Comment by Yexinglong** [comment]
Sorry, not SDWebimage question, I seemingly found the problem! But I do not understand is that this document is doing?


2015-09-21 23:25:08.966 MiYi[2370:415781] dir /var/mobile/Containers/Data/Application/D3FF105B-8F1A-49CB-AE5F-B565B5804E84/tmp/stack-logs.2167.1004d8000.MiYi.mPFLnu.index subfiles (null)  att {
    NSFileCreationDate = "2015-09-21 14:20:58 +0000";
    NSFileExtensionHidden = 0;
    NSFileGroupOwnerAccountID = 501;
    NSFileGroupOwnerAccountName = mobile;
    NSFileModificationDate = "2015-09-21 14:22:54 +0000";
    NSFileOwnerAccountID = 501;
    NSFileOwnerAccountName = mobile;
    NSFilePosixPermissions = 384;
    NSFileProtectionKey = NSFileProtectionCompleteUntilFirstUserAuthentication;
    NSFileReferenceCount = 1;
    NSFileSize = 16523496;
    NSFileSystemFileNumber = 26564899;
    NSFileSystemNumber = 16777219;
    NSFileType = NSFileTypeRegular;
}
2015-09-21 23:25:08.967 MiYi[2370:415781] dir /var/mobile/Containers/Data/Application/D3FF105B-8F1A-49CB-AE5F-B565B5804E84/tmp/stack-logs.2240.100478000.MiYi.yolYij.index subfiles (null)  att {
    NSFileCreationDate = "2015-09-21 14:48:53 +0000";
    NSFileExtensionHidden = 0;
    NSFileGroupOwnerAccountID = 501;
    NSFileGroupOwnerAccountName = mobile;
    NSFileModificationDate = "2015-09-21 14:49:16 +0000";
    NSFileOwnerAccountID = 501;
    NSFileOwnerAccountName = mobile;
    NSFilePosixPermissions = 384;
    NSFileProtectionKey = NSFileProtectionCompleteUntilFirstUserAuthentication;
    NSFileReferenceCount = 1;
    NSFileSize = 9935376;
    NSFileSystemFileNumber = 26568525;
    NSFileSystemNumber = 16777219;
    NSFileType = NSFileTypeRegular;
}

**Comment by mythodeia** [comment]
the docs have nothing to do with this lib. these are just log files

**Comment by Yexinglong** [comment]
I found out what the reasons are, and also thank you for attention to my problem
This problem is the reason I opened MallocStack  (*^__^*) 嘻嘻…

**Comment by mythodeia** [comment]
:+1:
