### ISSUE TITLE
SDWebImageRefreshCached does not respect HTTP cache headers

### ISSUE THREAD

**Issue by serkrapiv** [rs/SDWebImage#1305]
I'm trying to figure out how to use HTTP cache-control headers to reload image when it expires. I've set up a sample project with OHHTTPStubs to test this case. My HTTP headers look like this:

Content-Type: image/png
Last-Modified: Sat, 19 Sep 2015 14:40:52 GMT 
ETag: "55fd73f4-3e53" 
Expires: Sat, 26 Sep 2015 14:44:13 GMT 
Cache-Control: max-age=604800

I'm using SDWebImageManager's method downloadImageWithURL:options:progress:completed: with SDWebImageRefreshCached | SDWebImageRetryFailed as options. Completed block is called two times: first time with cached image and cacheType=SDImageCacheTypeDisk, second time with new image and cacheType=SDImageCacheTypeNone.

Test project is here: https://github.com/serkrapiv/SDWebImageCacheTest

Am I doing something wrong with HTTP headers, or is this a bug similar to https://github.com/rs/SDWebImage/issues/821?

**Comment by mythodeia** [comment]
```SDWebImageRefreshCached``` always calls the server to get a new copy if any.

**Comment by serkrapiv** [comment]
@mythodeia Well, according to https://github.com/rs/SDWebImage/issues/1252, https://github.com/rs/SDWebImage/issues/821 and https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.h#L39 it should still respect HTTP cache headers. And, if they are correct, don't load new image.

**Comment by mythodeia** [comment]
@serkrapiv as i see [here](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloaderOperation.m#L214) the code checks for a 304 status code. In your sample i always get a 200 thats why it returns twice.
A nice solution would be to check the Etag or the Expires property in the header to see if the file has changed or not.
However this would also mean that we would need to keep that for each file as well.
What do you think?

**Comment by serkrapiv** [comment]
@mythodeia It seems that to get 304 status code we have to send last modified date in If-Modified-Since request header anyway, or ETag in If-None-Match. So, as I understand, there is no way to receive 304 status code with current implementation anyway? And yes, in that case we should store ETag and last modification date with each image.

**Comment by GBoyadziev** [comment]
Any progress on that issue, my app will benefit greatly if the ETag and last modification date are stored in disc cache?

**Comment by accatyyc** [comment]
I'm not sure this is an issue (anymore at least). When looking at the source code, using `SDWebImageRefreshCached` will make `SDWebImage` use `NSURLCache` for caching. This means that etags and last modified should be handled by `NSURLCache`, which should mean that they work.

Or am I missing something here?

**Comment by GBoyadziev** [comment]
The idea here is not to resort to `NSURLCache`, there are a number of issues with it. The more severe once are a race condition, leading to a crash and a problem with the cache size. Lately in my app I was forced to abandon it completely. It has some sort of a bug, there are filed radars about it. The cache does not take into account its size limit and grows uncontrollably or its grow behaviour is undefined. 

Here are links to some of the radars (there are many more):
https://openradar.appspot.com/29945424
http://www.openradar.me/28518369

**Comment by dreampiggy** [comment]
`OHHTTPStubs` Not works for `NSCachedURLResponse`. See their code [here](https://github.com/AliSoftware/OHHTTPStubs/blob/master/OHHTTPStubs/Sources/OHHTTPStubs.m#L366-L369). It seems a bug for this and you should report issue for the author.

This `SDWebImageRefreshCached` works for the real server response if your server response the correct headers.

The support header is actually implemented by Apple's URLSession. But I've test these:

+ `Last-Modified`
+ `Expires`
+ `ETag`

You can also run our demo, change the `MasterViewController.m`'s code options into `SDWebImageRefreshCached` and check that the completion block is called once from the `SDImageCache`
