### ISSUE TITLE
Not Showing Images after migrating to Swift 2.0

### ISSUE THREAD

**Issue by Fabs** [rs/SDWebImage#1307]
I have an IOS application I did not developed, but I am responsible to maintain, I have some experience as a Swift developer, but don't consider myself master on the subject either. Today, I had to make a small change on the interface because the APP was rejected on the apple store review, and since I got Xcode 7 as an update last week I had to migrate the app to Swift 2.0, which was partially done with the migration tool, and partially done manually.

Said that. I have the following issue. None of the images that are loaded via  `sd_setImageWithURL` appears to work. Their spaces on the layout continue there, but there are no images coming from s3. I am sure the urls are correct (I used the debugger for that), and I have the following setup:

**This is my latest pod update:**
Using CSStickyHeaderFlowLayout (0.2.5)
Using DACircularProgress (2.3.1)
Using HexColors (2.2.1)
Using MBProgressHUD (0.9.1)
Using MWPhotoBrowser (1.4.1)
Using PSTCollectionView (1.2.3)
Using RESideMenu (4.0.7)
Using Reachability (3.2)
Using SDWebImage (3.7.2)
Using TSMessages (0.9.12)
Using XDKAirMenu (1.1.0)

**I have a Dow-Bridging-Header.h* with the following**
```Objective-C
#import <SDWebImage/UIImageView+WebCache.h>
```

**And a code snipped of using it is**
```swift
    func receivedClient(notification: NSNotification) {
        let client = notification.object as! Client?
        
        if let url = client?.photo?.medium {
            imageView?.sd_setImageWithURL(NSURL(string:url))
            Utils.applyRoundedCornersToImageView(imageView)
        }
```

Many of the problems I had migrating the code was related to what I think was a bad use of swift's **optional** pattern.

Any help would be much welcome.

**Comment by Fabs** [comment]
I think this could be related:
http://stackoverflow.com/questions/32675319/sdwebimage-stopped-after-swift2

**Comment by Fabs** [comment]
I have disabled App Transport Security as stated here (http://www.fiveminutewatchkit.com/blog/?category=NSURLSession) and for me *it solved the problem*.

**Comment by bpoplauschi** [comment]
:+1:
