### ISSUE TITLE
Best setup when prefetching images and accessing cache when loading UITableViewCells

### ISSUE THREAD

**Issue by mitchellporter** [rs/SDWebImage#1309]
I have been using `SDWebImage` for a long time now, usually inside of `UITableViewCells`. Normally I just use the following method inside of the cell's load method:

`- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder;`

However, I've recently started working with the `SDWebImagePrefetcher` class and exploring more of the headers and seeing what's possible.

Prefetching works fine so far, but what I'm currently stuck on is how to best setup the `UIImageView` when the `UITableViewCell` loads. As far as I can tell, using the standard method I included above does NOT check the cache for the URL. It always downloads first, and then caches. Please correct me if I'm wrong.

Because I know that I am prefetching images every time the app runs, I realized that the above is not a good setup because you're always just re-downloading the image again, even if it's cached. So I changed my cell's load method to use something like this instead:

    // Check if thumbnail is cached
    if([[SDImageCache sharedImageCache] diskImageExistsWithKey:object.fields[@"Thumbnail_URL"]]) {
        
        // Set cached thumbnail image on imageview
        [self.videoThumbnail setImage:[[SDImageCache sharedImageCache] imageFromDiskCacheForKey:object.fields[@"Thumbnail_URL"]]];
        
    } else {
        
        // Not cached so lets download it
        [self.videoThumbnail sd_setImageWithURL:[NSURL URLWithString:[object.fields objectForKey:@"Thumbnail_URL"]] completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
            
        }];
    }

What this code does is check the cache for the image, and if it's cached then it retreives it from the cache and I set it on my `UIImageView`. If it's not cached, then I call `- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder;` to download it from the remote source.

This seemed like an ok rough draft, but after doing more research I came across this method:

    - (void)sd_setImageWithPreviousCachedImageWithURL:(NSURL *)url andPlaceholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageCompletionBlock)completedBlock;

Am I correct in thinking that this method is better than `- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder;`, because it automatically checks the cache first, before downloading the image from the remote source?

If I am correct, then it looks like I could replace the `if, else` code I shared above and simply use `sd_setImageWithPreviousCachedImageWithURL`. If I'm correct about all of this then what would be the point of ever using any other `sd_setImage` method since `sd_setImageWithPreviousCachedImageWithURL` is the only one that automatically checks the cache first, or am I wrong about this?

Just looking for some advice and input on this. Thanks.

**Comment by mythodeia** [comment]
@mitchellporter 
```sd_setImageWithURL ``` only downloads the image once and then caches it. On the second request it asks for the image using ```queryDiskCacheForKey``` which checks memory and disk and then returns that without performing the request (unless stated otherwise in options)

```sd_setImageWithPreviousCachedImageWithURL``` calls ```sd_setImageWithURL```
but has an issue #793

**Comment by mitchellporter** [comment]
Ok thanks for the info, and yes I was also looking at #793 it's too bad no progress has been made on that.
