### ISSUE TITLE
can I set image to an UIImageView by using sd_setImageWithURL twice?

### ISSUE THREAD

**Issue by funkyLover** [rs/SDWebImage#1311]
I get this problem
There is a `UIImageView`,
at frist, it will show a thumbnail image, 
at the same time show the loading and get the original image
but the thumbnail image also need request by giving url
I try 
```
[imageView sd_setImageWithURL:tURL //thumbnail url
    placeholderImage:placeholderImage
    options:SDWebImageRetryFailed
    progress:nil
    completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        //it will work fine here~
        [imageView sd_setImageWithURL:oURL //original url
             placeholderImage:image
             options:SDWebImageContinueInBackground
             progress:nil
             completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                  //weird, here will never be executed
                  if (error) {
                     NSLog(@"fails");
                  }
                  [_loading removeFromSuperview]; // remove loading
         }];
}];
```
but it dosen't work and I can't figure out why?

**Comment by mythodeia** [comment]
@funkyLover can you replicate it in the demo project? 
Please download the latest version of this library.
also you should ```__weak``` your imageview to use it inside the block again

**Comment by funkyLover** [comment]
@mythodeia the library is latest version,
and use the `__weak` doesn't make it work too,

**Comment by mythodeia** [comment]
did you try to replicate it with the demo project?
