### ISSUE TITLE
SDWebimage cache functioning

### ISSUE THREAD

**Issue by masterfego** [rs/SDWebImage#1313]
Hi, 
I have 3 questions:
1- What is the default maxCacheSize?
2- Can iOS delete SDCache to recover free space?
3- If I set cache directory to /DocumentsDir, can cleanner App delete my data cache?

**Comment by mythodeia** [comment]
@masterfego 
1 - The maximum size of the cache, in bytes.
2 - IOS will delete the content of caches when memory is low
3 - the lib SHOULD clean whichever folder you declare as your cache folder

**Comment by masterfego** [comment]
Okay, and for question 1, how many bytes by default or unlimited?

**Comment by mythodeia** [comment]
there is no default value for this. you should add one if you want
