### ISSUE TITLE
SDWebImageRefreshCached doesn't work on iOS 9

### ISSUE THREAD

**Issue by cherpake** [rs/SDWebImage#1314]
I'm not sure if this broke in iOS 9 or before ... but SDWebImageRefreshCached stopped working.

In SDWebImageDownloaderOperation class, when checking if we have cached response for request,
I get YES, and then completionBlock is called with empty image error and etc.

I checked and indeed the image was in the cache, and was returned by NSURLCache.

After setting sharedCache like this (to disable returning of cached response):
```objective-c
@interface NOURLCache : NSURLCache

@end

@implementation NOURLCache

- (NSCachedURLResponse *)cachedResponseForRequest:(NSURLRequest *)request {
    return nil;
}

@end

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [NSURLCache setSharedURLCache:[NOURLCache new]];
...
}
```

New image was fetched from network.

**Comment by mythodeia** [comment]
can you replicate in demo project?

**Comment by mythodeia** [comment]
@cherpake any updates on this?

**Comment by cherpake** [comment]
sorry man - we having holidays in my country, which doesn't leave with much of free time, once we return to work, will create a demo project, which isn't trivial- cause after initial cache, it will have to change the image on the server side...

**Comment by mythodeia** [comment]
@cherpake thanks :+1:

**Comment by webliupeng** [comment]
same problem +1
it doesn't work on iOS 9

**Comment by SuperMarioBean** [comment]
and I found the NSURLCache's subclass as a sharedCache, the method 

`- (NSCachedURLResponse *)cachedResponseForRequest:(NSURLRequest *)request`

will be called only on iOS 7.0.4, I found it can not be called on iOS 8.4.1 and iOS 9.3.1。

**Comment by bpoplauschi** [comment]
Please retry with 3.8.2 and the 4.0 release that is coming (now available on the 4.x branch).
