### ISSUE TITLE
Very long loading image

### ISSUE THREAD

**Issue by MarcSky** [rs/SDWebImage#1315]
I use the library in your project. Usually I upload images width and height of 750 pixels. SDWebImage or too does not load or loads when I scrolls. I do not know what to do because I need the speed.

     SDWebImageManager *manager = [SDWebImageManager sharedManager];
        [manager  downloadWithURL:fullImagePath delegate:self options:0 success:^(UIImage *image, BOOL dummy) {
            dispatch_async(dispatch_get_main_queue(), ^{
            cell.imageView.image = [self resizeImage:image :CGSizeMake(self.view.frame.size.width, 232)];
            });
        } failure:nil];

**Comment by mythodeia** [comment]
are you using it in a tableview? can you replicate in the demo project?

**Comment by MarcSky** [comment]
Yes, I use inside the table. I did not understand the second question. what could be the problem of speed?

**Comment by mythodeia** [comment]
i meant you should try your urls in the demo project of the library. 
Generally in a tableview you can use the ```sd_setImageWithURL``` method which will set the image automatically on the imageview. Check the sample project.
What do you mean by speed? If the image is large in size then it will delay showing until its fully downloaded.

**Comment by MarcSky** [comment]
If I use sd_setImageWithURL as I scale the image before the show.

**Comment by mythodeia** [comment]
if you want to scale an image and cache the scaled image instead you can use [this](imageManager:transformDownloadedImage:withURL) method. 
What it does is that it allows to transform the image immediately after it has been downloaded and just before to cache it on disk and memory.
As i said before if the image is large in size then it will delay showing until its fully downloaded.
Unless there is a problem with the library i will close the issue.
