### ISSUE TITLE
Installing library

### ISSUE THREAD

**Issue by MarcSky** [rs/SDWebImage#1316]
I decided to reinstall the library, I took it to another repository, and it is trimmed.
I decided to put via Pods but I got out after installation error - "ld: library not found for -lSDWebImage" I put in the OTHER FLAGS "$ (inhereted)". But the problem persists, I suspect that he did not see the installed library.
I decided to try through cloning a repository, but I could not understand what it means "In the dialog, select SDWebImage.framework:" because the "Link Binary With Libraries" not to see this framework. Maybe I'm wrong, but please help.
I would like to put through the repository because Pods do not like.

**Comment by mythodeia** [comment]
When you choose to add files to an existing project a dialog appears that lets you choose which files you want to add. There you can choose the SDWebImage.framework which you can either download from here or generate your own by building the library and choose that.

clone the repository.
do a pod install in the Tests folder.
When the pod installation is done open the SDWebImage.xcworkspace
build the SDWebImage Demo to test or choose the SDWebImageFramework to produce a framework to add to your own app.
