### ISSUE TITLE
Image Orientation problem when loading image with SDWebImage (Swift)

### ISSUE THREAD

**Issue by Farhaddc** [rs/SDWebImage#1317]
When an image gets loaded with SDWebImage the orientation of my image is wrong. But when I use pure NSURL converting it to NSData and assigning to UIImage, the Image looks perfectly fine.

Correct Orientation | Wrong Orientation
------------ | -------------
![Correct Orientation](http://s1.postimg.org/4r9avz4fz/Wild_Bird_Correct.gif) | ![Wrong Orientation](http://s17.postimg.org/lcn5ei467/Wild_Bird_Wrong.gif)

**Orientation of the photos in each scenario**
* AVFoundation UIImageView Preview  (Orientation: **OK**)
* On server (Orientation: **OK**)
* Uploading to other Social Media (Orientation: **OK**)
* In Browser  (Orientation: **OK**)
* In Desktop  (Orientation: **OK**)
* Loading Image to UIViewTableCell  with NSURL/NSData/UIImage  (Orientation: **OK**)
```
    let URLExtention = self.loadedData[indexPath.row].valueForKey("photoURL") as! String
    let imageURL = NSURL(string: "https://examples.com//\(URLExtention)")
    let imageData = NSData(contentsOfURL: imageURL!)
    let Image = UIImage(data: imageData)
```
* Loading Image to UIViewTableCell with SDWebImage  (Orientation: **FAILED**)
```
 cell.photo.sd_setImageWithURL(imageURL)
```

Also to mention, I use [ UIImageView+AFNetworking.h](https://github.com/AFNetworking/AFNetworking/blob/master/UIKit%2BAFNetworking/UIImageView%2BAFNetworking.h) and I get **wrong orientation** as well. 

I would really like to use SDWebImage, cause currently I use NSCache and don't like the performance even thought it solve the issue. Please help, Thank you.

## UPDATE:
Here is an Image taken with AVFoundation that goes into AWS S3 Bucket. **JPEG Format**

![Wrong Orientation](http://s23.postimg.org/kqvqoovpn/31348a193e9e010ec81a68203b7a8018.jpg)

**Comment by mythodeia** [comment]
does this happen with all images or with gif only?

**Comment by Farhaddc** [comment]
@mythodeia Update the Issue.

**Comment by mythodeia** [comment]
@Farhaddc this specific image has no exif metadata for orientation. I tried several online tools as well and no orientation key exists inside the EXIF metadata.
So SDWebImage in this method ```sd_imageOrientationFromImageData``` when it tries to get the orientation it returns ```UIImageOrientationUp``` which is the default one as no ```kCGImagePropertyOrientation``` is found inside the image. So there is no way to know which way is up

**Comment by Farhaddc** [comment]
I manage to fix it with **PHP ImageMagick** and erase the **EXIF** file and add new orientation to it. I believe SDWebImage is okay. Thank you anyway.

**Comment by superdev89** [comment]
I have same issue

**Comment by mythodeia** [comment]
@superdev89 which version of the library are you using? Are you loading the gif using FLAnimatedImage object?

**Comment by keegho** [comment]
@superdev89 I have the exact same issue....any solutions???
