### ISSUE TITLE
cache image not shown

### ISSUE THREAD

**Issue by MarcSky** [rs/SDWebImage#1319]
hi i still can not find a solution so please help. When I open the app, I loaded images. Now when I open the app on my site images emptiness, ie with the network is not loaded and the cache is not taken when I leaf table loaded pictures, but when you do not touch - it's empty, I do not loaded.

     dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0ul);
        dispatch_async(queue, ^{
            [cell.imageView sd_setImageWithURL:[NSURL URLWithString:path]
                              placeholderImage:[UIImage imageNamed:@"placeholder.png"]
                                     completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                                         dispatch_async(dispatch_get_main_queue(), ^{
                                             cell.imageView.image = [self resizeImage:image :CGSizeMake(self.view.frame.size.width, 255)];
                                         });

                                     }
             ];
        });

Please help because I do not know how to be. Can prompt what to see, where to fix it. I see here many of such problems but specific solutions have been found.

**Comment by MarcSky** [comment]
Please tell me how to run the demo project I wrote that there is no file in the folder vendor.

**Comment by mythodeia** [comment]
I am sorry but i cannot understand what you are saying.
why are you putting everything in s low priority queue? This is what might be causing the issues.
To install the demo project:
Clone the library in a folder and then open the SDWebImage.xcworkspace file with the SDWebImage demo project scheme

**Comment by MarcSky** [comment]
I'm trying to say is that when I run the application the images are not loading.

**Comment by mythodeia** [comment]
as i told you in my previous comment please see the demo project for example on how to use this lib in a tableview scenario

**Comment by MarcSky** [comment]
![2015-09-27 23 47 12](https://cloud.githubusercontent.com/assets/4164003/10125128/22decb6a-6572-11e5-9169-a2bbd64d94ad.png)

I really want to see the project, but can not open it because of these errors, there is no Podfile how to download dependencies.

**Comment by mythodeia** [comment]
The pod file is in the tests folder.but all you need to check is the code on the master & details view controller

**Comment by MarcSky** [comment]
All ! I'll see! I have one question - can there be a reason that the images are not loaded until I have to scroll the table - the choice RestKit framework? Just tell me to use AFNetworking but this is nonsense. By the way I looked at the code in your project, but it is currently copied my problem not solved, you are loaded very small pictures, and I have big - can be a problem - the image size (> 1 MB).

**Comment by mythodeia** [comment]
you should not use large images as thumbnails. Because if you have multiple requests/cells at the same time and each request is for an image larger than 1 MB then the user experience will not be good as the thumbs will not load fast enough. In my opinion you should use smaller thumbs for the tableview and larger images on demand when the user wants them.
if you see the demo project it only uses ```[cell.imageView sd_setImageWithURL:.... ``` without the use of dispatch_queue_t.
If you use smaller images you will see faster response

**Comment by MarcSky** [comment]
All good, my mistake - ignore placeholder image.
But I was faced with a new challenge when I put a placeholder image - it breaks my cell layout. That is the image - obtained from the cache starts to change its position, and errors appear in the console. As I put nil in the placeholder the layout is not broken but the image is almost not loaded from the cache.

(
    "<NSLayoutConstraint:0x146827a0 V:[UILabel:0x1466b560'\U0424\U041e\U0422\U041e\U041f\U0420\U041e\U0415\U041a\U0422\U042b'(21)]>",
    "<NSLayoutConstraint:0x14612330 V:[UIImageView:0x146853b0(255)]>",
    "<NSLayoutConstraint:0x14619bd0 V:[UILabel:0x1464bf50'\U0427\U0443\U043a\U043e\U0442\U043a\U0430. \U0417\U043d\U0430\U043a\U043e\U043c\U044b\U0435 \U0432\U0441\U0435 \U043b\U0438\U0441...'(62)]>",
    "<NSLayoutConstraint:0x146891e0 V:[UILabel:0x1467bc10'\U00ab\U0415\U0441\U043b\U0438 \U0437\U0432\U0435\U0440\U044c \U0442\U0435\U0431\U044f \U0437\U0430\U043c\U0435\U0442\U0438\U043b ...'(81)]>",
    "<NSLayoutConstraint:0x14689570 V:|-(0)-[UIImageView:0x146853b0]   (Names: '|':UITableViewCellContentView:0x1458b290 )>",
    "<NSLayoutConstraint:0x146610a0 V:[UIImageView:0x146853b0]-(NSSpace(8))-[UILabel:0x1466b560'\U0424\U041e\U0422\U041e\U041f\U0420\U041e\U0415\U041a\U0422\U042b']>",
    "<NSLayoutConstraint:0x14661160 V:[UILabel:0x1466b560'\U0424\U041e\U0422\U041e\U041f\U0420\U041e\U0415\U041a\U0422\U042b']-(NSSpace(8))-[UILabel:0x1464bf50'\U0427\U0443\U043a\U043e\U0442\U043a\U0430. \U0417\U043d\U0430\U043a\U043e\U043c\U044b\U0435 \U0432\U0441\U0435 \U043b\U0438\U0441...']>",
    "<NSLayoutConstraint:0x14647600 V:[UILabel:0x1464bf50'\U0427\U0443\U043a\U043e\U0442\U043a\U0430. \U0417\U043d\U0430\U043a\U043e\U043c\U044b\U0435 \U0432\U0441\U0435 \U043b\U0438\U0441...']-(NSSpace(8))-[UILabel:0x1467bc10'\U00ab\U0415\U0441\U043b\U0438 \U0437\U0432\U0435\U0440\U044c \U0442\U0435\U0431\U044f \U0437\U0430\U043c\U0435\U0442\U0438\U043b ...']>",
    "<NSLayoutConstraint:0x14685890 UITableViewCellContentView:0x1458b290.bottomMargin == UILabel:0x1467bc10'\U00ab\U0415\U0441\U043b\U0438 \U0437\U0432\U0435\U0440\U044c \U0442\U0435\U0431\U044f \U0437\U0430\U043c\U0435\U0442\U0438\U043b ...'.bottom - 2>",
    "<NSLayoutConstraint:0x14679f60 'UIView-Encapsulated-Layout-Height' V:[UITableViewCellContentView:0x1458b290(379.5)]>"
)
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x14612330 V:[UIImageView:0x146853b0(255)]>

**Comment by mythodeia** [comment]
thats an issue with your constraints. Please check your constraints set on your imageview or label

**Comment by MarcSky** [comment]
thanx ! all working wonderful!
