### ISSUE TITLE
iOS 9 https 

### ISSUE THREAD

**Issue by dimohamdy** [rs/SDWebImage#1320]
when i try to download image this message apper  
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824
 CFNetwork SSLHandshake failed (-9824)

i try this solution for ios9 but not work 
http://stackoverflow.com/questions/30739473/nsurlsession-nsurlconnection-http-load-failed-on-ios-9

**Comment by mythodeia** [comment]
read [this](http://www.fiveminutewatchkit.com/blog/?category=NSURLSession)
