### ISSUE TITLE
Wrong flash image when reloading tableview

### ISSUE THREAD

**Issue by mastermyx** [rs/SDWebImage#1325]
Hello,

I have a tableview with an UIImageView loading image asynchronously. Everything works great except when I have to reload it. I load the new array of URLs and reload tableview. The new image in my list has the image of the second (previously first before the reload) only for a flash moment.

I didnt find how to get out of this problem.

one of my try was inside the tableviewcell but it is not working too: "
  SDWebImageManager *manager = [SDWebImageManager sharedManager];
        self.imageOperation = [manager downloadWithURL:self.imageURL
                                               options:SDWebImageRetryFailed
                                              progress:nil
                                             completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished) {
                                                 if (image)
                                                     self.statusPicture.image = image;
                                             }]; 

any idea? 

Arthur.

**Comment by mythodeia** [comment]
try the prepareforreuse method in your tableviewcell subclass. you should nullify your image there

**Comment by mastermyx** [comment]
@mythodeia It's working, thank you!
