### ISSUE TITLE
Carthage bitcode issue

### ISSUE THREAD

**Issue by silver619** [rs/SDWebImage#1326]
There is an issue with this on carthage when using archive builds of a project using the created framework, You can check out this link https://github.com/Carthage/Carthage/issues/53 for more detail. Basically you need to add user-defined-setting of "BITCODE_GENERATION_MODE" set to "bitcode" in the framework project before it will be able to work from a carthage builds. I have already cleared this with the guys at Alamofire and it works.

**Comment by bpoplauschi** [comment]
Could you create a PR with this fix?

**Comment by bpoplauschi** [comment]
Should be fixed by #1593
