### ISSUE TITLE
A lot of warning warning: Could not resolve external type c:objc(cs)

### ISSUE THREAD

**Issue by nhatlee** [rs/SDWebImage#1328]
Hi all,
Please help me fix those warning when I build on Xcode 7, support iOS 8 and 9

warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:objc(cs)NSMutableArray
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:objc(cs)NSFileManager
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:@S@_NSRange
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:objc(cs)UIImage
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:objc(cs)NSOperation
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:@E@NSComparisonResult
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:objc(cs)NSURL
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:objc(cs)NSDirectoryEnumerator
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:objc(cs)NSDate
while processing /Users/letiennhat/Library/Developer/Xcode/DerivedData/KaptrProject-efrolczbwpynubaesvvikszzudqp/Build/Products/Debug-iphonesimulator/libSDWebImage.a(SDImageCache.o):
warning: Could not resolve external type c:objc(cs)NSMutableDictionary

**Comment by mythodeia** [comment]
@nhatlee are you using any other external 3rd party framework?

**Comment by nhatlee** [comment]
@mythodeia yes, I am using SDWebImage, as you can see it in the list warning message above.

**Comment by mythodeia** [comment]
i get that. i mean besides this library. did you check the link i gave you?

**Comment by mythodeia** [comment]
@nhatlee any updates?

**Comment by nhatlee** [comment]
@mythodeia Yes I checked the link you advice to check. But still get don't know why get those warning. I think it's relate to the SDWebImage library, cause as the message of the warning said.

**Comment by mythodeia** [comment]
check these build settings:
Precompile Prefix (GCC_PRECOMPILE_PREFIX_HEADER) = NO
Debug Information Format (DEBUG_INFORMATION_FORMAT) = DWARF with dSYM

**Comment by nhatlee** [comment]
@mythodeia I check those build setting and it right as you advice. But still cannot remove those warning :(

**Comment by mythodeia** [comment]
if you open the sample project does this issue occur there as well?

**Comment by nhatlee** [comment]
I don't know but I will return to your advice at weaken

**Comment by bpoplauschi** [comment]
Any updates here?

**Comment by ohadschn** [comment]
See here: https://forums.developer.apple.com/thread/17921. When generating DSYM (presumably for distribution to other machines) you should disable `CLANG_ENABLE_MODULES` and `CLANG_ENABLE_MODULE_DEBUGGING = NO`.

**Comment by mythodeia** [comment]
closing this. if you need further assistance please reopen
