### ISSUE TITLE
sd_setImageWithURL always returns error code 401

### ISSUE THREAD

**Issue by gregorpichler** [rs/SDWebImage#1329]
I'm using SDWebImage in my Swift 2.0 project. When running on iOS 9 it always returns the following error

`Error Domain=NSURLErrorDomain Code=401 "(null)"`

Using SDWebImage to load image from server

```
cell.backgroundImageView.sd_setImageWithURL(NSURL(string: "http://..."), placeholderImage: placeholderImg, options: SDWebImageOptions.RetryFailed, completed: {(image, error, type, url) -> Void in
   if error == nil {
      // do something with image          
   }
})
```
As it's an http:// request and running on iOS 9, I've also added this to my Info.plist file

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

**Comment by bpoplauschi** [comment]
Can you share an image url? 401 means `Unauthorized ` and this indicates an issue with the service providing the images (might require an authentication).

**Comment by gregorpichler** [comment]
You are right, it turned out that there needs to be authorization. I've tried it only in my browser, which had the login credentials cached. Cheers!

**Comment by bpoplauschi** [comment]
Great
