### ISSUE TITLE
iOS SDWebImage can not load PNG image

### ISSUE THREAD

**Issue by qq6931850** [rs/SDWebImage#1333]
TEST URL:http://api.buzz.cn/Public/Upload/pptpdf/2014/12/31/1420003484645/1420003509_1.png

**Comment by mythodeia** [comment]
@qq6931850 The error is about: Downloaded image has 0 pixels

**Comment by qq6931850** [comment]
But I use a browser to access is no problem.Sdwebimage before ios9 can also be accessed
