### ISSUE TITLE
did not get image

### ISSUE THREAD

**Issue by Piyush08** [rs/SDWebImage#1334]
-(void)viewDidAppear:(BOOL)animated
    {
        [super viewDidAppear:animated];  
        UIImageView *imgv=[[UIImageView alloc]init];
    
    [imgv sd_setImageWithURL:[NSURL URLWithString:@"http://static2.dmcdn.net/static/video/328/648/51846823:jpeg_preview_small.jpg?20121105214944"] completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {        
             NSLog(@"completed image");
         }];   
     }

This is not working for ver first time i.e. it is not working when view appear first time but it works for second time.

Help me to solve this

**Comment by mythodeia** [comment]
the image url is invalid. no image is found online [failed to load resource] - 404 error
check sample project ```DetailViewController.m ``` file for correct usage.

**Comment by Piyush08** [comment]
http://static2.dmcdn.net/static/video/328/648/51846823:jpeg_preview_small.jpg?20121105214944

please check this

**Comment by mythodeia** [comment]
this is what i am seeing
![51846823-jpeg_preview_small](https://cloud.githubusercontent.com/assets/1748458/10409898/7a99f55c-6f39-11e5-99ac-5189b8b0cae2.jpg)

**Comment by Piyush08** [comment]
hello @mythodeia 
it is for large.
by the way, it has valid image

**Comment by dhruv-russmediatech** [comment]
Hello @mythodeia ,

Please check your URL after opening.
Here is what you are seeing http://static2.dmcdn.net/static/video/328/648/51846823:jpeg_preview_small.jpg

But the way the Actual Image is this one and has ID appended. 
http://static2.dmcdn.net/static/video/328/648/51846823:jpeg_preview_small.jpg?20121105214944

**Comment by mythodeia** [comment]
@Piyush08 
![screen](https://cloud.githubusercontent.com/assets/1748458/10410254/8f3f0fe6-6f44-11e5-9e6e-0989586040a6.png)

@dhruv-russmediatech 
![screen2](https://cloud.githubusercontent.com/assets/1748458/10410257/b07ea748-6f44-11e5-81ae-317987534e77.png)

all report 404 in the browser and this is coming from the app:
```
Error Domain=NSURLErrorDomain Code=404 "The operation couldn’t be completed. (NSURLErrorDomain error 404.)```

**Comment by dhruv-russmediatech** [comment]
@mythodeia 
May be it is not working on your end.
![screenshot from 2015-10-10 14 38 52](https://cloud.githubusercontent.com/assets/6670433/10410349/c1f56c4c-6f5c-11e5-8a49-abb697c8bdf1.png)

:+1:

**Comment by mythodeia** [comment]
maybe its blocking countries or IPs. sorry maybe someone else that can see the image can help debug it. i would suggest to use the demo project that has an example in the viewdidload which works just fine and test from there
