### ISSUE TITLE
How can i get image in the https server?

### ISSUE THREAD

**Issue by Pluto-Y** [rs/SDWebImage#1336]
The image is in the https server.Something like 'https://my-domain/path/xxxxx.png'.
Does the SDWebImage support https?
What should i do for this scenario?

**Comment by mythodeia** [comment]
yes it does.  dont forget to read this when you target IOS 9 
http://www.fiveminutewatchkit.com/blog/?category=NSURLSession

**Comment by Pluto-Y** [comment]
I have disable the ATS, but the SDWebImage still not work.
This is what i have set.
        <key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>


```
Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." 
```
This is what i get.
The image url:https://i.cern.cc/moin_static197/common/moinmoin.png

**Comment by Pluto-Y** [comment]
```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```
This is what i have set.

**Comment by mythodeia** [comment]
the website prompts for a certificate acceptance

**Comment by Pluto-Y** [comment]
Yeah, I need load a image from this server, Does the SDWebImage can load image like this situation?

**Comment by mythodeia** [comment]
use this option SDWebImageDownloaderAllowInvalidSSLCertificates

**Comment by Pluto-Y** [comment]
Thanks, you save me!!!
