### ISSUE TITLE
I installed SDWebImage

### ISSUE THREAD

**Issue by byejuner** [rs/SDWebImage#1337]
![2015-10-14 6 23 25](https://cloud.githubusercontent.com/assets/14050706/10479766/33b0db36-72a1-11e5-8cd6-2c44598a620c.png)
but it occurred errors

thanks for your answer

**Comment by bpoplauschi** [comment]
What version of CocoaPods? Does it help if you upgrade to the latest one? (0.39)

**Comment by mythodeia** [comment]
if you remove this library's pod does it work?

**Comment by byejuner** [comment]
The version of CocoaPods is (0.39) but i got the errors

i removed this library's pod, but my project didn't works

**Comment by mythodeia** [comment]
Since it's not working even without this pod then it has something else to do with your pod/project, right?

**Comment by bpoplauschi** [comment]
This looks like an issue with CocoaPods itself. Maybe it is damaged or there is an issue with ruby. Please make sure those 2 are properly installed (maybe try reinstalling them).

**Comment by byejuner** [comment]
Thanks bpoplauschi  I solved the problem. It is an issue with ruby

**Comment by bpoplauschi** [comment]
:+1:
