### ISSUE TITLE
Support for status bar network indicator

### ISSUE THREAD

**Issue by mcicak** [rs/SDWebImage#1338]
It would be nice if there was optional support for this.
Maybe something like AFNetworking does with AFNetworkActivityIndicatorManager.

**Comment by mihaiserban** [comment]
SDWebImage already supports SDNetworkActivityIndicator. SDWebImageDownloader initialize function checks wether SDNetworkActivityIndicator exists and adds the indicator as observer for downloader start and stop operations.

**Comment by NKorotkov** [comment]
It works, but why would you not include SDNetworkActivityIndicator in the actual SDWebImage package? Seems like it would be needed almost every time.
