### ISSUE TITLE
Pdf support

### ISSUE THREAD

**Issue by ivampir** [rs/SDWebImage#1339]
Please add pdf images support

**Comment by lucare** [comment]
+1

**Comment by bpoplauschi** [comment]
I don't think we will be adding this feature in the near future.

**Comment by bpoplauschi** [comment]
Per #1991 you can now write your own decoder/encoder for PDF. Just have to conform to `SDWebImageCoder` protocol. Closing this PR as we will not add and maintain any PDF handling.
