### ISSUE TITLE
-[SDWebImageDownloaderOperation start] Crash in latest version

### ISSUE THREAD

**Issue by Monika-Tapadiya** [rs/SDWebImage#1342]
Hello, 
I have used SDWebImageCache to load images but it is crashing sometimes, I got line no. 

-[SDWebImageDownloaderOperation start]  (SDWebImageDownloaderOperation.m:96)
 self.connection = [[NSURLConnection alloc] initWithRequest:self.request delegate:self startImmediately:NO];

Please help me  to solve the issue.

Thanks

**Comment by bpoplauschi** [comment]
Probably a duplicate of https://github.com/rs/SDWebImage/issues/691

**Comment by bkvirendra** [comment]
@bpoplauschi I faced the issue! Is there something particularly to do with the way we use SDWebImage?

**Comment by skytraveler** [comment]
It contributes 1/2 of all crashes we've got. Could someone kindly fix it? Thx.

**Comment by sunbohong** [comment]
@skytraveler  is there a solid way to reproduce this crash?

**Comment by bpoplauschi** [comment]
Let's close this issue, see if it happens again with 4.0.0 (4.0.0-beta is available for download, 4.0.0 official release is on its way).
