### ISSUE TITLE
Support for watchOS framework, pod

### ISSUE THREAD

**Issue by sashagood** [rs/SDWebImage#1346]
Can't use SDWebImage with pods for watchOS target.

```
target ' WatchApp Extension' do
    platform :watchos, '2.0'
    pod 'Parse', :git => 'git@github.com:ParsePlatform/Parse-SDK-iOS-OSX.git', :branch => 'nlutsenko.watchOS'
    pod 'SDWebImage'
end
```

Getting error 

```
[!] The platform of the target `WatchApp Extension` (watchOS 2.0) is not compatible with `SDWebImage (3.7.3)`, which does not support `watchOS`.
```

**Comment by bpoplauschi** [comment]
Version 3.7.4 is out.

**Comment by buithuyen** [comment]
Same for me
```Objective-C
Analyzing dependencies
[!] The platform of the target `Watch Extension` (watchOS 2.0) is not compatible with `SDWebImage (3.7.4)`, which does not support `watchos`.
```

**Comment by bpoplauschi** [comment]
Sorry guys, I totally missed this, I've mistaken tvOS with watchOS. We have no watchOS support yet.

**Comment by Ge0rges** [comment]
What's necessary to implement until support for WatchOS is added?

**Comment by bpoplauschi** [comment]
I think the biggest dependency is NSURLSession, we are adding that as we speak in 3.8.0. As soon as that is merged in, I will start working on the WatchOS support.

**Comment by bpoplauschi** [comment]
Just merged the watchOS support into the 4.x branch. Will definitely be included in the next release. In the meantime, you can take it from there and see if it works for you

**Comment by bpoplauschi** [comment]
Just merged the `watchOS` support into the [4.x](https://github.com/rs/SDWebImage/tree/4.x) branch. Will definitely be included in the next release. In the meantime, you can take it from there and see if it works for you - please note that is in-progress work which breaks compatibility with the older versions of SDWebImage.
