### ISSUE TITLE
Transform image without flicker

### ISSUE THREAD

**Issue by bmurmistro** [rs/SDWebImage#1347]
I'm trying to use SDWebImage and apply some transformations to the image (rounded circle, border, etc). When I apply the transformations, they don't kick in for a brief second and cause a flickering effect in my table view. Here's is what I'm trying to do:

```
cell.imageView.sd_setImageWithURL(NSURL(string: picUrl)!, 
                                  placeholderImage: nil, 
                                  completed: { ( image:UIImage!, 
                                                 error: NSError!, 
                                                 cacheType:SDImageCacheType, 
                                                 imageURL: NSURL!) -> Void in
    cell.imageView.contentMode = UIViewContentMode.ScaleAspectFit
    cell.imageView.layer.cornerRadius = cell.imageView.frame.size.width / 2
    cell.imageView.layer.borderColor = UIColor.trPicBorderColor().CGColor
    cell.imageView.layer.borderWidth = 1.0
    cell.imageView.layer.masksToBounds = true
    cell.imageView.hidden = false // shouldn't transforms happen by now???
})
```

I even tried with the AvoidAutoSetImage option and got the same results. Any ideas?

**Comment by bmurmistro** [comment]
downloadImageWithURL solved my problem

**Comment by bmurmistro** [comment]
Using downloadImageWithURL doesn't appear to be caching any of the requests.

SDWebImageDownloader.sharedDownloader().downloadImageWithURL(NSURL(string: picUrl)!, options: .LowPriority, progress: nil, completed: {(image: UIImage?, data: NSData?, error: NSError?, finished: Bool)....

Any ideas?

**Comment by mythodeia** [comment]
@bmurmistro you can do all the transformations here while still using the ```sd_setImageWithURL``` method
```
- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;
```
more [info](https://github.com/rs/SDWebImage/blob/b185621812f90a4eb4f7f44e0f547014da4d1958/SDWebImage/SDWebImageManager.h#L127)

**Comment by bmurmistro** [comment]
Thank you @mythodeia
