### ISSUE TITLE
Cancel token

### ISSUE THREAD

**Issue by orta** [rs/SDWebImage#1351]
Hey there, congrats on being the [2nd most](https://gist.github.com/orta/1c607a2c46545244ab16) used 3rd party library in the Cocoa community. 

I was starting to think about ways to work on cancellable image downloads within the [Artsy iOS](https://github.com/artsy/eigen/) app. I want to be able to cancel networking for image thumbnails within a view controller on `viewDidDisappear` one of the methods that is looking like winning for me is tying our images together with a cancel token. This would mean creating an api like:

```
ARImageNetworkingToken *token =  [[ARImageNetworkingToken alloc] init];
[self.thumbnailImage ar_setImageWithURL:artwork.imageURL token:token];
```

With the aim that I can call `[token pause]` to kill all the networking requests when we go into another view controller. This also means having to create `[token restart]` when you get back into the viewController. 

Given that all of this is a problem that every other app can potentially have, is there interest in me creating this at SDWebImage level instead? Given that it has access to shared networking state

**Comment by alloy** [comment]
I wonder if a simplification could be to have `-[UIImageView sd_setImageWithURL:]` and friends just return the internal `SDWebImageOperation`? This way the user can control it as they see fit, in our case that would be keeping an array of operations on the VC that can be cancelled when the view disappears.

**Comment by bpoplauschi** [comment]
@orta thanks. Cancelling is an issue we are currently looking at. There are 2 proposals, please take a look at #1069 and #883

**Comment by orta** [comment]
Thanks @bpoplauschi - I bet I could build this on top of one of these #1069

**Comment by bpoplauschi** [comment]
@orta I'm actually looking at integrating #883, shouldn't take me more than a day or two to get that into master

**Comment by orta** [comment]
Cool, that's even better ( I just figured that #1069 was closer to being merged )

**Comment by bpoplauschi** [comment]
@orta very soon, right after 3.7.4 gets out (probably today), I will merge #883.

**Comment by orta** [comment]
No worries, I'm not trying to put pressure on you at all :+1: - you run one of the most popular libs, you can run it how you like

**Comment by bpoplauschi** [comment]
@orta Damn, I see now how long it took to get this merged. Finally, #883 is merged into our 4.x branch and we are full ahead towards a 4.x release. Do you still need this feature?

**Comment by orta** [comment]
hah - yeah, it's not _turn the ship around_ kind of thing, but it's _I'll take this into account on upcoming artsy/eigen priorities_  👍

**Comment by bpoplauschi** [comment]
👍

**Comment by bpoplauschi** [comment]
Guys, you can try the 4.0.0-beta version which is available via CocoaPods. An official release is on its way.

**Comment by orta** [comment]
Congrats!
