### ISSUE TITLE
SDWebImage   - (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder

### ISSUE THREAD

**Issue by WWLJ** [rs/SDWebImage#1352]
use this url    http://7xngft.com2.z0.glb.qiniucdn.com/thn.jpg
console print error 
<Error>: CGBitmapContextCreate: unsupported parameter combination: set CGBITMAP_CONTEXT_LOG_ERRORS environmental variable to see the details

**Comment by bpoplauschi** [comment]
There are already some issues with the same description (https://github.com/rs/SDWebImage/search?q=CGBitmapContextCreate&type=Issues&utf8=%E2%9C%93) that were already fixed. Please take a look at them (i.e. #371). We will reopen the issue if it still exists.

**Comment by WWLJ** [comment]
The issue is still exists. It is difference between this error with these error.
And some properties have changed.

**Comment by bpoplauschi** [comment]
Are you using the latest version of the library?

**Comment by WWLJ** [comment]
pod 'SDWebImage', '~> 3.7.3'

**Comment by WWLJ** [comment]
#1335

**Comment by WWLJ** [comment]
It is a same issue  #1335     
but i do not find  unsupportedColorSpace in SDWebImageDecoder.m
if (!context) {
        if (unsupportedColorSpace){
            CGColorSpaceRelease(colorspaceRef);
        }
        return image;
    }

**Comment by mythodeia** [comment]
@WWLJ i have the latest version and it works fine without issues using your image.
are you sure its that image thats causing the issue. tried it in simulator 8.4
the code stops here:
```if (anyAlpha) { return image; }```
as the anyAlpha is YES
