### ISSUE TITLE
"libwebp" and "use_frameworks!" make compiler error

### ISSUE THREAD

**Issue by 515783034** [rs/SDWebImage#1353]
here is my Podfile's contents.I need "use_frameworks!" because here is swift framework, but this makes libwebp error. the error is :"web/decode.h" file not found.
How can I do to fix it? tks so much

use_frameworks!
platform :ios,"8.0"
pod "AFNetworking", '~>2.6.0'
pod 'Masonry'
pod 'Bugtags'
pod 'MBProgressHUD'
pod 'ReactiveCocoa', '~> 4.0.2-alpha-1'
pod 'SDWebImage/WebP'

**Comment by frankpolkm** [comment]
same issue. I changed #import "webp/decode.h" to #import "libwebp/webp/decode.h" in file UIImage+WebP.m. Now, it works. I know it's not a good way, but .....   : )

**Comment by bpoplauschi** [comment]
Please try using the latest master. It should work fine.
I mean:

`pod 'SDWebImage/WebP', :head`

**Comment by 515783034** [comment]
tks a lot .I'll try it

**Comment by 515783034** [comment]
To be honest ,It does not fix..

**Comment by arthankamal** [comment]
Add **"User Header Search Paths"** in **"SDWebImage"** target which is in **"Pods"** project. 

**$(SRCROOT)/libwebp/src** with **recursive**

Also make sure, you've added *libwebp* pod in your **Podfile**

`pod 'SDWebImage/WebP'`

![screen shot 2016-01-27 at 11 00 45 pm](https://cloud.githubusercontent.com/assets/10445166/12621808/52fba9fe-c548-11e5-80de-4cd5a28284de.png)

**Comment by scinfu** [comment]
there is a pod solution ?
