### ISSUE TITLE
SDWebImage uses more memory when image is loaded for the first time

### ISSUE THREAD

**Issue by ejoebstl** [rs/SDWebImage#1354]
While working with SDWebImage, we observed that the initial download of an image takes more memory than loading the image from the disk cache. 

<img width="647" alt="screenshot 2015-10-29 14 36 34" src="https://cloud.githubusercontent.com/assets/1852126/10821569/fec12d76-7e4a-11e5-84f7-6b1a4c21e0f9.png">

The memory consumption can be seen in the above screenshot. The call was identical both times, the image was downloaded from the internet the first time, and then loaded from disk the second time.

In this case, the issue increased the memory consumption by about 50 MB. 

How could we work around this additional memory consumption?

**Comment by mythodeia** [comment]
is the image large in resolution or size?

**Comment by emiswelt** [comment]
Exactly. 4096 * 4096 pixels, jpeg.

**Comment by mythodeia** [comment]
That's a logical memory spike then.

**Comment by mythodeia** [comment]
Just a reference for the image used in your git:
Its size is 4096 width x 4096 height.
So for every pixel in an image 4 bytes are used. To calculate the memory:
height x width x 4 = total bytes in memory.
4096 * 4096 * 4 = roughly 64MB

**Comment by emiswelt** [comment]
That's true, but what's the reason for the spike to not occur when the image is loaded from the disk?

**Comment by emiswelt** [comment]
*bump* 
Is there anything I could do to help with this issue?

**Comment by bpoplauschi** [comment]
Not sure how to proceed here. Large images will do spikes, no matter what we do

**Comment by ejoebstl** [comment]
I agree, It's not logical. It's larger than it should be. It also happens for small images (the spike is just smaller).

**Comment by bpoplauschi** [comment]
I think this issue is similar to #538 and #586.
#787 and 00bf467 should give you a good solution for dealing with large images. Together with the GIF handled by FLAnimatedImage, this ticket should be done now.

Closing. Let's see how this is with 4.0.0
