### ISSUE TITLE
Feature: Preload disk cache to memory

### ISSUE THREAD

**Issue by johnboiles** [rs/SDWebImage#1355]
I have a number of icons in my app that load remotely. Because I want to cache those longer term than other images, I set up a separate `SDImageCache` for those icons.

It'd be nice to be able to also preload the entire disk cache into memory in the background at app startup. 

[Haneke](https://github.com/Haneke/Haneke#preload-policy) has this ability, for example.

I can probably find time to implement this, but just wanted to get some feedback / ideas first.

**Comment by dongyu430** [comment]
preload ? SDWebImagePrefetcher

**Comment by johnboiles** [comment]
SDWebImagePrefetcher loads a set of URLs. I want to load the a specific `SDImageCache`'s disk cache into memory.

This would work somewhat similar to `cleanDiskWithCompletionBlock` in that it'd iterate through all files in the `diskCachePath` and load them into memory. Maybe the method could be called `- (void)preloadDiskCacheWithCompletionBlock:(SDWebImageNoParamsBlock)completionBlock;`

**Comment by dreampiggy** [comment]
@johnboiles Current 4.x, `SDImageCache` contains a method called `addReadOnlyCachePath:`. To add the folder that `SDImageCache` will query secondlly after the original image cache path failed. However, your image's file name should be exact what `SDImageCache` using for cache key. It now using a MD5 of image cache key.

In 5.x, we introduce a more powerfull API `additionalCachePathBlock`. Which we pass the image cache `key` for you, you return a `file path` in the block, and we use that file path to query disk again. This can solve this issue.

And, we also support custom memory cache & disk cache in #2282 . You can create your own disk cache implementation add add a preload feature for your own business.

If you still have issue about it, feel free to reopen it :)
