### ISSUE TITLE
Images Not Scaled Properly

### ISSUE THREAD

**Issue by springstephen** [rs/SDWebImage#1356]
I noticed an issue with retina images rendering twice as large than expected when set as a background image for a UITabBar. I tracked down the issue to two classes. UIImage+MultiFormat was using method initWithData. Changing this to initWithData: scale: fixed the issue here. The other place was the SDWebImageCompat class. Here there is some logic for finding the range of a 2x or 3x string in the cache key. I removed this logic and simply pass in the [UIScreen mainScreen.scale value for the initWithCGImage: scale: orientation: method.

**Comment by bpoplauschi** [comment]
There were some fixes to scale issues in the latest versions. Could you update to the latest and recheck?
