### ISSUE TITLE
Solution to set images with animation only if they are not already cached in memory.

### ISSUE THREAD

**Issue by NKorotkov** [rs/SDWebImage#1357]
I've been struggling with this problem for a couple of days now. Previously I used AFNetworking category to load and cache images, but it doesn't provide a cache type in it's callbacks. So I used to keep track in each controller which images have been already loaded. I looked through SDWebImage and it provides exactly what I was looking for - `SDImageCacheType`.

Now i'm trying to come up with an easy to use (hopefully a one-liner) solution to load images in table and collection views with animation if they are downloaded or come from the disk cache. Basically these tasks take some time to get actual image, when memory cache provide images instantaneously, hence no animation needed when image comes from memory.

I've came up with this UIImageView category, and I would like someone more experienced to provide some feedback. It does seem to work as intended. I'm not sure that I'm reinventing the wheel here, or this approach might somehow backfire under certain circumstances.

In outline is does two separate things. In completion block, when image is ready to use, it sets animation duration depending on what cache level has been used. The second idea is for reusable cell mechanism, imageView keeps track of the loading operation with help of associated objects and if there's an ongoing task it cancels it. I don't like the fact, that operation is retained, it's not supposed to be, but associated objects don't provide a `__weak` type of reference afaik. `OBJC_ASSOCIATION_ASSIGN` key seems to make object `__unsafe_unretained` and leads to a bad access crash.

Any advice would be appreciated.

``` objective-c
static char kOperationKey;

- (id <SDWebImageOperation>)scrb_setImageAnimatedWithURL:(NSURL *)url {


    id <SDWebImageOperation> lastOperation = objc_getAssociatedObject(self, &kOperationKey);

    if (lastOperation) {
        [lastOperation cancel];
    }

   id <SDWebImageOperation> operation = [[SDWebImageManager sharedManager] downloadImageWithURL:url options:SDWebImageRetryFailed progress:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {

        if (finished && image) {

            NSTimeInterval duration = 0;

            if (cacheType == SDImageCacheTypeDisk || cacheType == SDImageCacheTypeNone) {
                duration = 0.2;
            }

            [UIView transitionWithView:self duration:duration options:UIViewAnimationOptionTransitionCrossDissolve animations:^{

                self.image = image;

            } completion:nil];

        }
    }];

    objc_setAssociatedObject(self, &kOperationKey, operation, OBJC_ASSOCIATION_RETAIN_NONATOMIC);

    return operation;

}
```

**Comment by NKorotkov** [comment]
With help from stackoverflow community I've changed my category to this:
```objective-c
- (void)scrb_setImageAnimatedWithURL:(NSURL *)url {
    
    [self sd_cancelCurrentImageLoad];
    
    self.alpha = 0;

    [self sd_setImageWithURL:url placeholderImage:nil options:SDWebImageRetryFailed completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        
        if (image) {
            
            BOOL animated = NO;
            
            if (cacheType == SDImageCacheTypeDisk || cacheType == SDImageCacheTypeNone) {
                animated = YES;
            }
            
            self.image = image;
            
            if (animated) {
                
                [UIView animateWithDuration:ANIMATION_DURATION animations:^{
                    
                    self.alpha = 1;
                    
                }];
                
            } else {
                
                self.alpha = 1;
                
            }
        }
 
    }];
  
}
```

Seems to work just as fine, but without nasty associated objects magic. The only downside is that UIImage view is hidden while image is loading, so you can't use it for background/placeholder purpose. But it's a minor issue and seems like a better solution overall.

**Comment by thedrick** [comment]
@NKorotkov if you'd like to use the UIImageView with a background color, you can use the `[UIView transitionWithView:duration:options:animations:]` method. Here's our category on UIImageView which does what you describe
```objc
- (void)md_setImageURL:(NSURL *)imageURL
      placeholderImage:(UIImage *)placeholderImage
              animated:(BOOL)animated
            completion:(void (^)(NSError *))completion {
  void (^safeCompletion)(NSError *error) = ^(NSError *error){
    if (completion) {
      completion(error);
    }
  };

  self.backgroundColor = [UIColor grayColor];

  if (!animated) {
    [self sd_setImageWithURL:imageURL
            placeholderImage:placeholderImage
                     options:SDWebImageRetryFailed
                   completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
      safeCompletion(error);
    }];
  } else {
    [self sd_setImageWithURL:imageURL
            placeholderImage:placeholderImage
                     options:SDWebImageRetryFailed
                   completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
      if (error) {
        NSLog(@"Error loading image with URL %@ -- %@", imageURL, error);
        safeCompletion(error);
      } else if (cacheType != SDImageCacheTypeNone) {
        // Don't animate in the image if it was cached
        self.backgroundColor = [UIColor clearColor];
        safeCompletion(nil);
      } else {
        [UIView transitionWithView:self
                          duration:0.20
                           options:UIViewAnimationOptionTransitionCrossDissolve
                        animations:^{
                          self.backgroundColor = [UIColor clearColor];
                          self.image = image;
                        } completion:nil];
        safeCompletion(nil);
      }
    }];
  }
}
```

**Comment by bpoplauschi** [comment]
Are you interested in creating a Pull Request?
