### ISSUE TITLE
Request new version for cocoapods

### ISSUE THREAD

**Issue by luanlaimobytelab** [rs/SDWebImage#1359]
Hi. I'm working download heavy images so I need not caching on memory. There was a commit for this but it has not been available in pod yet. I can't install by dragging to project because I'm using MWPhotoBrowser which include SDWebImage as subspec. So could you put a new version to pod contains this commit?
https://github.com/rs/SDWebImage/commit/df751e737b0236c942a3f9e10f63c968b2d54fdd

Thank you.

**Comment by bpoplauschi** [comment]
Version 3.7.4 is out.
