### ISSUE TITLE
SDImageCacheTypeDisk Slow Performance 

### ISSUE THREAD

**Issue by onurvarrrr** [rs/SDWebImage#1360]
Hi,

As you can see below, I'm using it in one my UITableView datasource's cellforrowatindex method.

![screen shot 2015-11-05 at 15 48 19](https://cloud.githubusercontent.com/assets/4017312/10968789/5ea6e754-83cc-11e5-987e-7d18285ddf30.png)

When fetching images for the first time (SDImageCacheTypeNone), it's working fine.
SDImageCacheTypeMemory also works fine.
![screen shot 2015-11-05 at 15 45 55](https://cloud.githubusercontent.com/assets/4017312/10968896/44913bf2-83cd-11e5-8c33-aaa5a388a931.png)

![screen shot 2015-11-05 at 15 43 53](https://cloud.githubusercontent.com/assets/4017312/10968888/3848a4fc-83cd-11e5-971c-fbeb173ba545.png)

But SDImageCacheTypeDisk seems like its waiting about 1s to get the images from Disk.
Is there any suggestions for this ?

Thanks.

**Comment by dongyu430** [comment]
SDImageCache ioQueue is serial

**Comment by onurvarrrr** [comment]
It's weird in some of my screens, it works perfectly ?
