### ISSUE TITLE
The 'UIApplication' method 'endBackgroundTask' may be called repeatedly

### ISSUE THREAD

**Issue by jackyzoufeng** [rs/SDWebImage#1362]
In the file:SDImageCache.m,method:backgroundCleanDisk

```
//code of - (void)backgroundCleanDisk
- (void)backgroundCleanDisk {
    Class UIApplicationClass = NSClassFromString(@"UIApplication");
    if(!UIApplicationClass || ![UIApplicationClass respondsToSelector:@selector(sharedApplication)]) {
        return;
    }
    UIApplication *application = [UIApplication performSelector:@selector(sharedApplication)];
    __block UIBackgroundTaskIdentifier bgTask = [application beginBackgroundTaskWithExpirationHandler:^{
        // Clean up any unfinished task business by marking where you
        // stopped or ending the task outright.
        NSLog(@"%@1:%u", NSStringFromSelector(_cmd), bgTask);
        [application endBackgroundTask:bgTask];
        bgTask = UIBackgroundTaskInvalid;
        NSLog(@"%@12:%u", NSStringFromSelector(_cmd), bgTask);
    }];

    // Start the long-running task and return immediately.
    [self cleanDiskWithCompletionBlock:^{
        NSLog(@"%@2:%u", NSStringFromSelector(_cmd), bgTask);
        [application endBackgroundTask:bgTask];
        bgTask = UIBackgroundTaskInvalid;
        NSLog(@"%@22:%u", NSStringFromSelector(_cmd), bgTask);
    }];
}
```
//log of the method
2015-11-10 09:50:44.159 testWeChat[1439:60b] backgroundCleanDisk2:6
2015-11-10 09:50:44.163 testWeChat[1439:3807] backgroundCleanDisk1:6
2015-11-10 09:50:44.168 testWeChat[1439:3807] Can't endBackgroundTask: no background task exists with identifier 6, or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
2015-11-10 09:50:44.171 testWeChat[1439:3807] backgroundCleanDisk12:0
2015-11-10 09:50:44.176 testWeChat[1439:60b] backgroundCleanDisk22:0

//I think we can use this code to replace
@synchronized(self) {
            if (bgTask != UIBackgroundTaskInvalid) {
                [application endBackgroundTask:bgTask];
                bgTask = UIBackgroundTaskInvalid;
            }
        }

**Comment by bpoplauschi** [comment]
This does not describe an issue with this library. Please use StackOverflow or a similar forum for those kind of questions.
