### ISSUE TITLE
SDWebImageManagerDelegate should have imageManager:shouldTransformImageForURL:

### ISSUE THREAD

**Issue by joshuafeldman** [rs/SDWebImage#1371]
This is not a bug but a feature request.

Currently the image manager delegate provides a method for transforming a downloaded image from a URL. But if you want to use the URL to determine if the image should be transformed there isn't a delegate method to indicate whether or not you want to actually transform the result. I know that you could simply return the same image in `-imageManager:transformDownloadedImage:` but that seems like a waste of resources since internally it will recompute for the transformed image.

I suggest adding a method to be called before to actually determine if the image for URL should be transformed. Since most people use the shared instance having this would allow for better integration when only trying to perform transformation on some of the downloaded images.

**Comment by bpoplauschi** [comment]
For now, there isn't a real need for that method. Thanks for the suggestion.
