### ISSUE TITLE
Using RefreshCached but still getting old image

### ISSUE THREAD

**Issue by andreaslindahl** [rs/SDWebImage#1374]
I'm using SDWebImage to download images from Amazon S3. The images are used as user profile images in the app, and will therefore be updated now and then, so it's important that i get the latest image if the image in the app is older than the one on the server. The filename stays the same on the server, but the actual image is updated when the user selects and uploads a new image.

I'm using RefreshCached to get the latest version from the server:

self.sd_setImageWithURL(imageUrl, placeholderImage: UIImage(named: "placeholder"), options: .RefreshCached, completed: { (image, error, cacheType, url) -> Void in
                })

It doesn't seem to work, however. Images are always loaded from the cache even if the image on the server is newer than the cached version.

How does SDWebImage determine if the image should be downloaded again? Which HTTP headers does it look at?

**Comment by yaliashkevich** [comment]
I have the same issue on iOS8.
On iOS9 it works like designed: each time you try to load image with refreshcached option it issues http request with proper cache-control (If-Modifed-Since, ETag in case of AmazonS3) headers and get new image back if it was modified or 304 if it wasn't.

On iOS8 no http request is issued, image is loading from the cache all the time until it is deleted (due to maxAge or maxSize settings) from there.

**Comment by andreaslindahl** [comment]
I'm still having problems with this. In iOS9 as well. Updated images aren't downloaded.

**Comment by andreaslindahl** [comment]
The problem seems to come and go. I reverted to 3.7.4 and things seem to work a little bit better in that version.

**Comment by ogezue** [comment]
I have the same problem and recognized that has to do with the server. Sometimes it works on all ios9 apps at the same time and sometimes not.

**Comment by BharatAgarSoftTech** [comment]
I have the same problem I am using Cloudinary and need to perform clear cache operation every time when user launch app otherwise it's not loading the latest image from URL.

let me know if anyone knows the solution.
Thanks :)

**Comment by bpoplauschi** [comment]
It might be a problem with your server. Make sure the cache policy flags are properly set and returned.

**Comment by yvesbastos** [comment]
@BharatAgarSoftTech same here using Cloudinary services. Did you find a solution for this?

**Comment by BharatAgarSoftTech** [comment]
@yvesbastos Nup, right now I am doing clear cache operation at app launch time so its load the latest image from Cloudinary.
