### ISSUE TITLE
Offline request blacklisted

### ISSUE THREAD

**Issue by olivierplante** [rs/SDWebImage#1376]
Hi,

If I request an image I doesn't already have in cache when I'm offline it's blacklisted.If I try to reload it when I'm online again it will not load except if I use SDWebImageRetryFailed. But in that case it will retry for every failed urls even the real bad urls. Is it possible to not blacklist offline request?

Thanks

**Comment by mythodeia** [comment]
are you using the latest version? i remember that we have made some changes regarding the blacklisting of urls when offline

**Comment by olivierplante** [comment]
Yes, I'm currently using the version 3.7.3 from cocoapod.

**Comment by mythodeia** [comment]
according to [this](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.m#L195) it should not add the url on the failedlist array

**Comment by jstart** [comment]
@olivierplante @mythodeia I am seeing the same thing on iOS 9.  What I am seeing is that when I am offline and make an image request shouldBeFailedURLAlliOSVersion == NO, but shouldBeFailedURLiOS7 == YES.  Then it does this check:

  if (shouldBeFailedURLAlliOSVersion || shouldBeFailedURLiOS7) 

It should be an && not an OR check correct?

**Comment by jstart** [comment]
@olivierplante @mythodeia This commit resolves the issue we are talking about. 
https://github.com/rs/SDWebImage/commit/60cab8b74cb59a79c69957368628c48a3f82a454

If you point to master, it will resolve the issue:
    pod 'SDWebImage', :git => 'git@github.com:rs/SDWebImage.git', :branch => 'master'

**Comment by olivierplante** [comment]
@jstart Thank you for your answer, that was exactly what I was looking for.

**Comment by jstart** [comment]
@mythodeia can we expect a 3.7.4 that contains this fix?

**Comment by mythodeia** [comment]
@bpoplauschi can you release 3.7.4 with that fix?

**Comment by bpoplauschi** [comment]
Coming soon.
