### ISSUE TITLE
ios 9 image loading significantly get slowed

### ISSUE THREAD

**Issue by intoxicated** [rs/SDWebImage#1377]
Recently i updated ios from 8.3 to 9.1 and I noticed loading image became too slow in ios 9. Does anyone experience similar problem? is this ios 9 issue or should I additionally handle things for ios 9 if i want to keep using sdwebimage..

**Comment by bpoplauschi** [comment]
Can you benchmark this and come up with some results of iOS 8.3 vs iOS 9.1 performance?

**Comment by bpoplauschi** [comment]
Closing due to no response
