### ISSUE TITLE
Avoid reloading UITableViewCells

### ISSUE THREAD

**Issue by slashburn** [rs/SDWebImage#1380]
I'm loading 54 images from a server.
However if I update my imageView with the downloaded image, it does not get updated in the tableView. So I call reloadRowsAtIndexPaths

cell.imageView?.sd_setImageWithURL(wellFormedImageURL, completed: {(image: UIImage?, error: NSError?, cacheType: SDImageCacheType!, imageURL: NSURL?) in
                        
                        
                   dispatch_async(dispatch_get_main_queue(), {
                         cell.imageView?.image = image
                            
                            if self.tableView.visibleCells.contains(cell) {
                                self.tableView.reloadRowsAtIndexPaths([indexPath], withRowAnimation: UITableViewRowAnimation.None)
                           
                            }
                            
                        })
                        
                    })

This finally leads to a memory issue and the app crashes. Is there any possibility to not call reloadRowsAtIndexPaths? If I only set the image (even if I do it on the main queue), the imageView does not get updated.

     sd_setImageWithURL(imageURL) 

does also not update my UITableViewCell

**Comment by mythodeia** [comment]
there shouldn't be any issues with this method. if you check the demo project you will see it works just fine (obj-c)

**Comment by slashburn** [comment]
In my case in Swift it doesn't, event though I've tried to call the exact same methods. The trick is to reload all cells in the callback as I did above but not on the main thread. Then the app does not crash. However this is kind of a workaround and not really tackling the problem. Maybe it's a Swift issue.
