### ISSUE TITLE
Gif images do not  load. 

### ISSUE THREAD

**Issue by desislavanikolovaWA** [rs/SDWebImage#1382]
We have issues with the latest master code -  Gif images do not load, and we detected the root of the cause for the issue in  the SDWebImageDecoder.m code, the following function:

+ (UIImage *)decodedImageWithImage:(UIImage *)image{....}

The function which decompresses the image is unable to create CGContextRef object and regenerate a UIImgae. If we escape this function we are able to retain the downloaded image. Can you guide us on how to solve the problem or review the code and possibly include a fix for the issue?

This is a link to the image we specifically experience issues with:
https://d262o8ek72aza.cloudfront.net/mimg/debenhams_125x125_2.gif

Thank you.

**Comment by mythodeia** [comment]
check this https://github.com/rs/SDWebImage/pull/1412
