### ISSUE TITLE
dispatch_main_async_safe look like synchronous.

### ISSUE THREAD

**Issue by L0omg** [rs/SDWebImage#1384]
dispatch_main_async_safe in main thread It will block the main thread.

**Comment by pengxuyuan** [comment]
why？ which you SD version? 3.X or 4.0.0?

**Comment by bpoplauschi** [comment]
I don't agree. `dispatch_main_async_safe` checks if the current queue is the main queue before doing dispatch_async. And even if the check wouldn't work properly, dispatch_async is not a blocker.

**Comment by bpoplauschi** [comment]
Latest definition
```
#ifndef dispatch_main_async_safe
#define dispatch_main_async_safe(block)\
    if (strcmp(dispatch_queue_get_label(DISPATCH_CURRENT_QUEUE_LABEL), dispatch_queue_get_label(dispatch_get_main_queue())) == 0) {\
        block();\
    } else {\
        dispatch_async(dispatch_get_main_queue(), block);\
    }
#endif

```

**Comment by cherpake** [comment]
Hi, this seems to cause crash on Mac OS X 10.8

0 | libsystem_c.dylib | strcmp + 80
1 | Remote for Mac | UIView+WebCache.m line 42-[NSView(WebCache) sd_internalSetImageWithURL:placeholderImage:options:operationKey:setImageBlock:progress:completed:]
2 | Remote for Mac | UIImageView+WebCache.m line 48-[NSImageView(WebCache) sd_setImageWithURL:placeholderImage:options:progress:completed:]

I guess one of the calls returns nil or something.

**Comment by bpoplauschi** [comment]
@cherpake the crash you described is not related to this issue. Please search for one that is or open a separate issue. Also, we need information like the SDWebImage version, how often does the crash occur, if you can replicate it with our demo project, ...

**Comment by cherpake** [comment]
Sorry,
I will open a separate issue with all the relevant information

**Comment by weipinglii** [comment]
@bpoplauschi as you said 
> dispatch_async is not a blocker
then why check currentQueue when use dispatch_async(dispatch_get_main_queue(), block)?
