### ISSUE TITLE
Support pdf images (New Feature)

### ISSUE THREAD

**Issue by AhmedOsamaOsman** [rs/SDWebImage#1385]
I need to use sdwebimage to download pdf image files.

**Comment by mythodeia** [comment]
@AhmedOsamaOsman  pdf images are not supported

**Comment by AhmedOsamaOsman** [comment]
I know thats not supported i'm asking about the ability to support it because it's really important.

**Comment by mythodeia** [comment]
right now v4 is more important. if you want you to help you can submit a PR to support pdf images and help this library progress.

**Comment by AhmedOsamaOsman** [comment]
ok i will add it as soon as possible

**Comment by mythodeia** [comment]
@AhmedOsamaOsman 
:+1:

**Comment by bpoplauschi** [comment]
Feel free to reopen
