### ISSUE TITLE
testRemoveImageForKey: wrong test

### ISSUE THREAD

**Issue by plougy** [rs/SDWebImage#1386]
Hi,

I wanted to know how you tested the method `removeImageForKey:` for `SDImageCache` class. I try to change the value of the key and the test is **always succeeded...**

```
- (void)testRemoveImageForKey{
    [self.sharedImageCache storeImage:[self imageForTesting] forKey:kImageTestKey];
    [self.sharedImageCache removeImageForKey:@"otherkey"];
    expect([self.sharedImageCache imageFromMemoryCacheForKey:kImageTestKey]).to.beNil;
    expect([self.sharedImageCache imageFromDiskCacheForKey:kImageTestKey]).to.beNil;
}
```

Can you confirm me that it's an error?

**Comment by bpoplauschi** [comment]
I'm not sure how it was tested, but I can tell you it's async, so after the `removeImageForKey` call, there is no guarantee the image was removed. Can you debug it? 
I suggest writing the test async and use the `removeImageForKey:withCompletion:`
