### ISSUE TITLE
get remote image dimensions whithout download them

### ISSUE THREAD

**Issue by bawn** [rs/SDWebImage#1389]
Can i get the height and width for the image before we download the image. Reason: i need to prepare the placeholder for the image use in dynamic cell

If before the tableview displays download all the images and then displays tableview, This is not a good user experience.

Anyone can help me?

**Comment by mythodeia** [comment]
the images of your tableview have different size?

**Comment by bawn** [comment]
@mythodeia Yes, I need display some different size imageview, they are the same width, but the height is determined by the picture itself. The imageview dimensions  ratio is `image.size.width / image.size.height`

**Comment by mythodeia** [comment]
as far as i know now you cannot get the size of the remote file before downloading it.
however you can check [this](https://github.com/siuying/IGFastImage)

**Comment by bawn** [comment]
@mythodeia Thanks
