### ISSUE TITLE
Incorrect caching gif images

### ISSUE THREAD

**Issue by CognitiveDisson** [rs/SDWebImage#1392]
I use delegate method for transform animated images.
```
- (UIImage *)imageManager:(SDWebImageManager *)imageManager
 transformDownloadedImage:(UIImage *)image
                  withURL:(NSURL *)imageURL
```

Method creates new animated image from source, and it works. But after restarting application cached gif image is no longer animated.

Problem consists in transforming the image to binary data.
```
- (void)storeImage:(UIImage *)image recalculateFromImage:(BOOL)recalculate imageData:(NSData *)imageData forKey:(NSString *)key toDisk:(BOOL)toDisk
```

imageIsPng is true! And because of this it is transformed as a png. //UIImagePNGRepresentation(image)

**Comment by bpoplauschi** [comment]
@patelmayank We have replaced our GIF component with a library from Flipboard (FLAnimatedImage). Could you try our 4.x branch ([instructions](https://github.com/rs/SDWebImage/tree/4.x#animated-images-gif-support)) and see if it helps?

**Comment by bpoplauschi** [comment]
Closing. The FLAnimatedImage solution replacing our own GIF is integrated into the 4.x branch.
