### ISSUE TITLE
push 3.7.4 tag

### ISSUE THREAD

**Issue by arielelkin** [rs/SDWebImage#1393]
the last tag 3.7.3 is almost six months old now, and several patches have been accumulating, it's probably time for a version bump. 

also, please update the cocoapod accordingly!

**Comment by Kirkis** [comment]
Agreed, that would be nice. Including ":head" as a dependency is not what I would recommend long-term.
Thanks,

**Comment by bpoplauschi** [comment]
Version 3.7.4 is out.

**Comment by Kirkis** [comment]
Thanks, worked like a charm.
