### ISSUE TITLE
UICollectionViewCell with wrong image

### ISSUE THREAD

**Issue by hilen** [rs/SDWebImage#1394]
I have a UICollectionView , when the data is okay, it will download 300+ images. But when you scroll the UICollectionView fast, the UICollectionViewCell's image is not right. I set `self.sd_cancelCurrentImageLoad()` and `set image nil` in `prepareForReuse()`, but it still not work. Here is my gist:https://gist.github.com/hilen/8ef4a810406051e8f0c1, so how to do it ? Is there a bug ?

**Comment by bpoplauschi** [comment]
Could you create a small project where the issue replicates easily?

**Comment by bpoplauschi** [comment]
Closing - no response.
