### ISSUE TITLE
TableViewCell reuse issue

### ISSUE THREAD

**Issue by mlijin9011** [rs/SDWebImage#1397]
If the network is not good, scroll the tableview fast up and down, then the image will not be set on the right cell after loading completed. Code as followed.
```
- (void)refreshWithModel:(Model *)model{
    [_userHeadImageView sd_setImageWithURL:[NSURL URLWithString:model.userPic] placeholderImage:[UIImage imageNamed:@"user_head_default"] options:SDWebImageRetryFailed];
}
...

- (void)prepareForReuse {
    [super prepareForReuse];
    [_userHeadImageView sd_cancelCurrentImageLoad];
    _userHeadImageView.image = nil;
}
```

**Comment by mythodeia** [comment]
@mlijin9011 can this be replicated in the demo project? if you remove the sd_cancelCurrentImageLoad from prepareforreuse does it still cause the reuse issue?

**Comment by levibostian** [comment]
Thank you @mythodeia. Your suggestion works well for me so far.

**Comment by mythodeia** [comment]
@mlijin9011 did this fix your issue?
