### ISSUE TITLE
decodedImageWithImage solve the problem CGBitmapContextCreate

### ISSUE THREAD

**Issue by LilyHZ** [rs/SDWebImage#1401]
CGBitmapContextCreate: unsupported parameter combination: 8 integer bits/component; 16 bits/pixel; 1-component color space; kCGImageAlphaPremultipliedFirst; 128 bytes/row.
CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
answer:
+ (UIImage *)decodedImageWithImage:(UIImage *)image {
    @autoreleasepool{
        // do not decode animated images
        if (image.images) { return image; }
        
        UIGraphicsBeginImageContextWithOptions(image.size, NO, image.scale); {
            CGRect imageRect = (CGRect){ CGPointZero, image.size };
            CGRect borderRect = CGRectInset(imageRect, 1, 1);
            UIBezierPath *path = [UIBezierPath bezierPathWithRoundedRect:borderRect
                                                       byRoundingCorners:UIRectCornerAllCorners
                                                             cornerRadii:CGSizeMake(0, 0)];
            [path addClip];
            [image drawAtPoint:CGPointZero];
        }
        UIImage *roundedImage = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
        return roundedImage;
}

**Comment by mythodeia** [comment]
@LilyHZ are you using the latest version? the code you have posted is not in the ```decodedImageWithImage``` method

**Comment by a13xb** [comment]
@mythodeia I see the same with `3.7.4` decoding a PNG image:

```
CGBitmapContextCreate: unsupported parameter combination:
 	16 integer bits/component;
 	64 bits/pixel;
	RGB color space model; kCGImageAlphaPremultipliedFirst;
	1024 bytes/row.
Valid parameters for RGB color space model are:
	16  bits per pixel,		 5  bits per component,		 kCGImageAlphaNoneSkipFirst
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipFirst
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipLast
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaPremultipliedFirst
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaPremultipliedLast
	64  bits per pixel,		 16 bits per component,		 kCGImageAlphaPremultipliedLast
	64  bits per pixel,		 16 bits per component,		 kCGImageAlphaNoneSkipLast
	128 bits per pixel,		 32 bits per component,		 kCGImageAlphaNoneSkipLast |kCGBitmapFloatComponents
	128 bits per pixel,		 32 bits per component,		 kCGImageAlphaPremultipliedLast |kCGBitmapFloatComponents
See Quartz 2D Programming Guide (available online) for more information.
```

**Comment by mythodeia** [comment]
@a13xb can you please share that image

**Comment by a13xb** [comment]
@mythodeia ![1](https://cloud.githubusercontent.com/assets/539049/12287369/47fcffa4-ba20-11e5-9396-08bac2dd4cf1.png)

**Comment by mythodeia** [comment]
@a13xb i will take a look at it thanks

**Comment by mythodeia** [comment]
the error you are getting is: 
unsupported parameter combination: 64 bpp RGB color space model; kCGImageAlphaPremultipliedFirst

according to the following table:
this combination is not supported.

<img width="740" alt="check" src="https://cloud.githubusercontent.com/assets/1748458/12287750/b024d9ec-b9d7-11e5-8630-8fbc158e2f18.png">

**Comment by a13xb** [comment]
@mythodeia Yes, it's not supported, but it happens when SDWebImage creating output context with the wrong pixel format (taking some parameters from input image, hard coding other parameters, so sometimes they don't match).

Moreover this image used to work on previous versions of SDWebImage, so it's definitely a regression.

**Comment by mythodeia** [comment]
@a13xb i will take a closer look later today. :+1:

**Comment by mythodeia** [comment]
@a13xb if you replace  CGImageGetBitsPerComponent(imageRef) with 8 it works fine. but i cannot hardcode this for these kind of images. A better solution would be to check if the bits per component result in an unsupported combination and if it does then roll back to hardcoded 8.

**Comment by mythodeia** [comment]
@a13xb does this pull solve your issues? https://github.com/rs/SDWebImage/pull/1496

**Comment by mythodeia** [comment]
fixed https://github.com/rs/SDWebImage/pull/1496
