### ISSUE TITLE
Large size Gif Image may crash in iphone but not in simulator

### ISSUE THREAD

**Issue by YYDD** [rs/SDWebImage#1406]
large size gif image may cause crash when use sdwebimage to load image.
there is a url(http://mmbiz.qpic.cn/mmbiz/Q0cm5xy6EbWTqHgwoA6te3RsXvjwnOt0dic5UPn8NNMP7bWnbmcZwpQqlWnHibaJEUQD9nxgX9Tme3ZI3AQ18ibcA/0?wx_fmt=gif) can cause crash .
so I add try catch in "+ (UIImage *)sd_animatedGIFWithData:(NSData *)data; " just for temporary.

tips:carch just in iphone not in simulator

**Comment by bpoplauschi** [comment]
@YYDD  We have replaced our GIF component with a library from Flipboard (FLAnimatedImage). Could you try our 4.x branch ([instructions](https://github.com/rs/SDWebImage/tree/4.x#animated-images-gif-support)) and see if it helps?

**Comment by YYDD** [comment]
ok ~  4.x branch works well. thanks

**Comment by bpoplauschi** [comment]
Great.
