### ISSUE TITLE
Can't show local png and gif files with UIImagePickerController

### ISSUE THREAD

**Issue by Rotemy** [rs/SDWebImage#1409]
I'm using `UIImagePickerController` to allow the user to pick png and gif files from his library.

I'm getting the `UIImage` and the `NSURL` like that:

    let selectedImage = info[UIImagePickerControllerOriginalImage] as! UIImage
    let mediaURL = info[UIImagePickerControllerReferenceURL] as! NSURL

The `NSURL` looks like that `assets-library://asset/asset.GIF?id=C1DF5564-A27A-4CE2-9010-AEA3E02BB651&ext=GIF`

I'm trying to make `SDWebImage` to show the image or animated gif like that:

    cell.contentImageView?.sd_setImageWithURL(localImage)

or

    cell.contentImageView?.sd_setImageWithURL(NSURL.fileURLWithPath(localImage.absoluteString))

but without any success.

I know that `SDWebImage` support ALAssets from [here][1]

Am I doing something wrong?

  [1]: https://github.com/rs/SDWebImage/pull/906

**Comment by mythodeia** [comment]
@Rotemy that pull was not merged. This lib does not support ALAssets.

**Comment by Rotemy** [comment]
Oh I didn't notice.

So do you have any thoughts about how can I display animated gif with `UIImagePickerController` ?
