### ISSUE TITLE
[self.memCache objectForKey:***] failed to get the value

### ISSUE THREAD

**Issue by GuoZhiQiang** [rs/SDWebImage#1411]
When I use the function sd_setImageWithURL: in my project , it does not load the image from the memoryCache . I find that the code of [self.memCache setObject:diskImage forKey:key cost:cost] has success performed ,but when it loads the image from cache by using [self.memCache objectForKey:myURL] ,the value is nil ! ! ! And it downloads the image from Internet again ! ! ! This is my URL (http://chogic-resource-test.oss.aliyuncs.com/activity/special/1451468380526.png?Expires=2902964732&OSSAccessKeyId=8Xja6X0JajxWmhWG&Signature=lY%2BaKYX4RG0tk81W1Bw447SVDLs%3D)

**Comment by mythodeia** [comment]
@GuoZhiQiang I got a couple of timeouts until i was able to see the image but i tried your url in the demo project and it works fine.

**Comment by GuoZhiQiang** [comment]
You mean it can load image form the memoryCache ? I used the function sd_setImageWithURL: in my tableView and it did load image from the Internet, but when i switched my iPhone into Flight Mode and scrolled the tableView ,the image disappeared. I debug the project and found that the value was nil when it loaded the image from cache by using [self.memCache objectForKey:myURL] in Flight Mode. So i scrolled the tableView and it loaded image from Internet again every time.

**Comment by GuoZhiQiang** [comment]
Does SDWebImage support the OSS url ？

**Comment by mythodeia** [comment]
did you try to replicate the issue in the demo project? for me it seems to be working.
are you using the latest version?
