### ISSUE TITLE
warning (libwebp): Multiple build commands for output file vp8li.h

### ISSUE THREAD

**Issue by jballer** [rs/SDWebImage#1413]
We're using `SDWebImage/WebP` v3.7.3 and getting the following warning on Xcode 7.2:
```
Warning: Multiple build commands for output file .../vp8li.h
```
This is apparently because there are two headers named `vp8li.h` (one in `/enc` and another in `/dec`), and the `libwebp` Podspec is telling Xcode to flatten the header files.

[Others have reported this in Google's WebP bug tracker](https://bugs.chromium.org/p/webp/issues/detail?id=279), but the Podspec is maintained by @bpoplauschi (apparently as part of this project).

I'm happy to help develop a fix for this, but don't know where I could submit a PR with an updated Podspec since I haven't been able to find a public repo for it.

**Comment by bpoplauschi** [comment]
@jballer you should continue the conversation on the WebP tracker tool, as this is not related to SDWebImage. I only published the libwebp releases via CocoaPods, I have no other relation to this great library.

**Comment by jballer** [comment]
@bpoplauschi Thanks for following up. As far as I can tell, this issue is particular to your release's Podspec and unrelated to the libwebp project.

The Podspec is telling the compiler to flatten the directory structure instead of preserving it, and this creates a naming conflict.

Are you suggesting that the libwebp project should rename these files?

**Comment by Ricardo1980** [comment]
@jballer  I have the same problem.
Can you tell me the link of that issue in the other tracker?
Thanks..

**Comment by barbaramartina** [comment]
@jballer I'm having the same issue. Was you able to solve it? I'm using SDWebImage/WebP 3.8.
