### ISSUE TITLE
Undefined symbols when trying to compile with framework with RoboVM.

### ISSUE THREAD

**Issue by butscanter** [rs/SDWebImage#1418]
Hi ! 

I am trying to use SDWebImage for Robovm - and binding the framework - to no avail so far ! I have tried different versions of the framework, built my own from the last release - I always end up with this : 

ERROR] Undefined symbols for architecture i386:
[ERROR]   "_CGPointZero", referenced from:
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]      (maybe you meant: _str_CGPointZero_00)
[ERROR]   "_kCGImagePropertyPixelHeight", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]      (maybe you meant: _str_kCGImagePropertyPixelHeight_00)
[ERROR]   "_CGSizeZero", referenced from:
[ERROR]       ___block_global_2 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]      (maybe you meant: _str_CGSizeZero_00)
[ERROR]   "_CGImageSourceCreateIncremental", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]   "_CGColorSpaceCreateDeviceRGB", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]      (maybe you meant: _str_CGColorSpaceCreateDeviceRGB_00)
[ERROR]   "_CGImageGetBitmapInfo", referenced from:
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]      (maybe you meant: _str_CGImageGetBitmapInfo_00)
[ERROR]   "_kCGImagePropertyPixelWidth", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]      (maybe you meant: _str_kCGImagePropertyPixelWidth_00)
[ERROR]   "_CGBitmapContextCreate", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]   "_CGImageGetBitsPerComponent", referenced from:
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]      (maybe you meant: _str_CGImageGetBitsPerComponent_00)
[ERROR]   "_CGImageSourceCopyPropertiesAtIndex", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]   "_CGImageSourceCreateImageAtIndex", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]   "_CGImageRelease", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]   "_CGBitmapContextCreateImage", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]   "_CGImageGetHeight", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]      (maybe you meant: _str_CGImageGetHeight_00)
[ERROR]   "_CGImageGetWidth", referenced from:
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]      (maybe you meant: _str_CGImageGetWidth_00)
[ERROR]   "_CGColorSpaceRelease", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]   "_CGColorSpaceGetNumberOfComponents", referenced from:
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]      (maybe you meant: _str_CGColorSpaceGetNumberOfComponents_00)
[ERROR]   "_CGImageSourceUpdateData", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]   "_CGContextDrawImage", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR]      (maybe you meant: _str_CGContextDrawImage_00)
[ERROR]   "_CGContextRelease", referenced from:
[ERROR]       ___59-[SDWebImageDownloaderOperation connection:didReceiveData:]_block_invoke_0 in SDWebImage(SDWebImageDownloaderOperation.o)
[ERROR]       +[UIImage(ForceDecode) decodedImageWithImage:] in SDWebImage(SDWebImageDecoder.o)
[ERROR] ld: symbol(s) not found for architecture i386
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app

The funny thing is it looks like missing symbols all come from CG (or ImageIO if i got that part well) - and only SOME symbols are missing. Can you help? I 'd love to get SDWebimage up and running for a RoboVM project :) Thanks in advance !

**Comment by bpoplauschi** [comment]
I advise you to try this question on StackOverflow, as it doesn't seem to be an issue with the library itself.
