### ISSUE TITLE
Update new Version to CocoaPods

### ISSUE THREAD

**Issue by mariohahn** [rs/SDWebImage#1421]
https://github.com/CocoaPods/Specs/tree/master/Specs/SDWebImage

**Comment by bpoplauschi** [comment]
The latest released version is on CocoaPods. As soon as we release the new 3.7.4, that will also be available via CocoaPods.

**Comment by mariohahn** [comment]
Ok thx. Because i would like to use it for TVOS (:

**Comment by bpoplauschi** [comment]
Version 3.7.4 is out.

**Comment by mariohahn** [comment]
thx (:
