### ISSUE TITLE
CGBitmapContextCreateImage: invalid context 0x0 - when downloading broken images

### ISSUE THREAD

**Issue by miraclebg** [rs/SDWebImage#1423]
If an image is broken (say for example the web server in my case returns garbage or html for an image - 500 error) in SDWebImageDownloaderOperation.m there is no check made for this and a nil image is passed to [UIImage decodedImageWithImage].

This should not be done as it results in an invalid context 0x0 (w/h of the image are zero):

Jan 10 08:37:53  EMDebug[68189] <Error>: CGContextDrawImage: invalid context 0x0. Backtrace:
	  <-[SDWebImageDownloaderOperation connectionDidFinishLoading:]+1274>
	   <__65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke+69>
	    <-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]+199>
	     <-[NSURLConnectionInternal _withActiveConnectionAndDelegate:]+48>
	      <___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke+104>
	       <___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClien
	        <_dispatch_client_callout+8>
	         <_dispatch_block_invoke+716>
	          <_ZN19RunloopBlockContext13_invoke_blockEPKvPv+24>
	           <CFArrayApplyFunction+68>
	            <_ZN19RunloopBlockContext7performEv+137>
	             <_ZN17MultiplexerSource7performEv+282>
	              <_ZN17MultiplexerSource8_performEPv+72>
	               <__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__+17>
	                <__CFRunLoopDoSources0+556>
	                 <__CFRunLoopRun+867>
	                  <CFRunLoopRunSpecific+488>
	                   <CFRunLoopRun+97>
	                    <-[SDWebImageDownloaderOperation start]+1868>
	                     <__NSOQSchedule_f+194>
	                      <_dispatch_client_callout+8>
	                       <_dispatch_queue_drain+2215>
	                        <_dispatch_queue_invoke+601>
	                         <_dispatch_root_queue_drain+1420>
	                          <_dispatch_worker_thread3+111>
	                           <_pthread_wqthread+1129>

**Comment by marksands** [comment]
I ran into this as well. +1 to the solution, the nil check fixed the error for me.

**Comment by mythodeia** [comment]
fixed with https://github.com/rs/SDWebImage/pull/1464
