### ISSUE TITLE
Cannot install it with carthage in tvOS

### ISSUE THREAD

**Issue by chinamty** [rs/SDWebImage#1424]
there is the log:

Build settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvos9.1

=== BUILD TARGET WebImage tvOS OF PROJECT SDWebImage WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvsimulator9.1

=== BUILD TARGET WebImage tvOS OF PROJECT SDWebImage WITH CONFIGURATION Release ===

Check dependencies
target 'WebImage tvOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform

**Comment by chinamty** [comment]
platform is tvOS

**Comment by bpoplauschi** [comment]
Not sure what to do here. We don't have in depth knowledge of Carthage. Did you find a solution?

**Comment by bpoplauschi** [comment]
Should be fixed by #1593
