### ISSUE TITLE
SDWebImagePrefetcher : Downloading stopped at maxConcurrentDownloads count

### ISSUE THREAD

**Issue by modLX4** [rs/SDWebImage#1425]
SDWebImagePrefetcher : Downloading stopped at maxConcurrentDownloads count (3) and completion block never called.

    if (remoteImageURLs.count > 0) {
        
        SDWebImagePrefetcher * prefetcher = [SDWebImagePrefetcher sharedImagePrefetcher];
        prefetcher.options = SDWebImageContinueInBackground;
        
        NSLog(@"Prefetch Images URL :: %@",remoteImageURLs);
        
        [prefetcher prefetchURLs:remoteImageURLs progress:^(NSUInteger noOfFinishedUrls, NSUInteger noOfTotalUrls) {
            
        } completed:^(NSUInteger noOfFinishedUrls, NSUInteger noOfSkippedUrls) {
            
            DDLogVerbose(@"mages Prefetcher :: Completed All Downloads");
            completed(YES,nil);
        }];
        
        return;
    }

**Comment by mythodeia** [comment]
can you check if the recent commit https://github.com/rs/SDWebImage/commit/cac21e106de23d25988905d6e5f293069d1d069a
fixes your issue. it rolled back a commit which caused issues with the prefetcher.
check https://github.com/rs/SDWebImage/pull/1350

**Comment by bpoplauschi** [comment]
@mythodeia I don't think cac21e1 fixes the issue.

**Comment by bpoplauschi** [comment]
I tried reverting 6406d8e, but I missed the part where on the download completion block, we trigger another `startPrefetchingAtIndex:`.

**Comment by bpoplauschi** [comment]
I've added a fix with commit a8fca65
