### ISSUE TITLE
Crash When  sliding TableView Very fast

### ISSUE THREAD

**Issue by chengchao12138** [rs/SDWebImage#1427]
crash at  SDWebImageDownloaderOperation.m                 CFRunLoopRun();
and Xcode give The warning  : could not load any Objective-C class information. This will significantly reduce the quality of type information available.

**Comment by chengchao12138** [comment]
Can someone help me ？

**Comment by ifbarrera** [comment]
I've experienced the same crash when scrolling a large tableView to the top. Fabric is reporting a crash at "-[SDWebImageDownloaderOperation start]" with a "EXC_BAD_ACCESS KERN_INVALID_ADDRESS" error.

I'm using the SDWebImageDownloader class independently to download images, and this happens in the cellForRowAtIndexPath method.

**Comment by chengchao12138** [comment]
Me too

**Comment by bpoplauschi** [comment]
Guys, we need more info here. Which SDWebImage version? Which OS version? Does it repro constantly? Can you repro the crash with our demo project? Can you create a demo project which makes it easy to repro?

**Comment by bpoplauschi** [comment]
Closing - not enough info
