### ISSUE TITLE
clang: error: no such file or directory:

### ISSUE THREAD

**Issue by AniOSDeveloper** [rs/SDWebImage#1428]
there are 4 errors when I run version 3.7.4 on xcode7.2 :

1]   clang: error: no such file or directory: '/Users/xxxxxxx/Downloads/SDWebImage-3.7.4/Vendors/libwebp/src/dsp/upsampling_neon.c'
clang: error: no input files

2]  clang: error: no such file or directory: '/Users/xxxxxxx/Downloads/SDWebImage-3.7.4/Vendors/libwebp/src/dsp/yuv_sse2.c'
clang: error: no input files

3] clang: error: no such file or directory: '/Users/xxxxxxx/Downloads/SDWebImage-3.7.4/Vendors/libwebp/src/utils/utils.c'
clang: error: no input files

4]  No input files

how to resolve these issues?

**Comment by bpoplauschi** [comment]
If you want to check out the project directly from git, you need to clone it recursively. See the details here: https://github.com/rs/SDWebImage#installation-by-cloning-the-repository

**Comment by AniOSDeveloper** [comment]
It works for me! Thanks very much!

**Comment by bpoplauschi** [comment]
:+1:
