### ISSUE TITLE
Crash on iPhone 4S

### ISSUE THREAD

**Issue by AlexChesters** [rs/SDWebImage#1429]
Hi,

`SDWebImage` is crashing on [this line](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloaderOperation.m#L117) on the iPhone 4S in the simulator. It works fine on other iOS 9 devices in the simulator.

**Comment by AlexChesters** [comment]
This also doesn't occur when running an iPhone 4S on iOS 8.4 in the simulator

**Comment by mythodeia** [comment]
this line you pointed is for IOS < 5 
r u sure thats the one causing the crash?

**Comment by mythodeia** [comment]
does the demo crash there as well with iPhone 4S IOS 4?

**Comment by AlexChesters** [comment]
I don't have an iOS4 simulator so I can't say. It's definitely specific to iOS 9 though, iPhone 4S on iOS 8 works fine

**Comment by mythodeia** [comment]
sorry my bad. i meant to write simulator iphone 4S IOS 8.4.i corrected my post.
i tried the demo project with simulator iphone 4S IOS 8.4 and IOS 9 and it works fine.

**Comment by AlexChesters** [comment]
I'm using 3.7.3, can you reproduce on iOS 9.0.0?

**Comment by mythodeia** [comment]
i am using IOS 9.2 - i do not have 9.0
can you try with the latest version and check again? can you replicate this with the demo project too?

**Comment by AlexChesters** [comment]
Just updated to 3.7.4 and its working fine, strange! Cheers :smile:

**Comment by mythodeia** [comment]
:+1:
