### ISSUE TITLE
i am  using xcode 7.1.1 and ios 9.2  when i am assigning the code in my ipad the i am getting an error"Could not find Developer Disk Image" ,how to over come this  issue without any updates

### ISSUE THREAD

**Issue by smilydronavalli** [rs/SDWebImage#1430]

**Comment by mythodeia** [comment]
@smilydronavalli thats not relevant with the library. maybe [this](http://stackoverflow.com/questions/32542036/xcode-7-with-ios-9-device-error-device-unavailable-could-not-find-a-developer) can help
