### ISSUE TITLE
Load GIF image may crash

### ISSUE THREAD

**Issue by CaiChenghan** [rs/SDWebImage#1432]
Load GIF image from service will use large memory and my app may crash。（加载网络gif图片会导致内存大量占用有可能使我的程序崩溃。）

**Comment by mythodeia** [comment]
duplicate https://github.com/rs/SDWebImage/issues/1406

**Comment by CaiChenghan** [comment]
Hi man , I find a good class to load gif image which wont use large memory. Here it's link https://github.com/ibireme/YYWebImage .

**Comment by bpoplauschi** [comment]
Closing, as a duplicate
