### ISSUE TITLE
filename's path extension might be too long

### ISSUE THREAD

**Issue by qiaoyan** [rs/SDWebImage#1433]
Hi,
consider the below long url being processed by the following code, the pathextension will be 517 characters which is too long for iOS.

- (NSString *)cachedFileNameForKey:(NSString *)key {
    const char *str = [key UTF8String];
    if (str == NULL) {
        str = "";
    }
    unsigned char r[CC_MD5_DIGEST_LENGTH];
    CC_MD5(str, (CC_LONG)strlen(str), r);
    NSString *filename = [NSString stringWithFormat:@"%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%@",
                          r[0], r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9], r[10],
                          r[11], r[12], r[13], r[14], r[15], [[key pathExtension] isEqualToString:@""] ? @"" : [NSString stringWithFormat:@".%@", [key pathExtension]]];

    return filename;
}
------------------
https://maps.googleapis.com/maps/api/staticmap?sensor=true&size=320x320&scale=2&markers=color:purple%7Clabel:A%7C31.211167,121.404&markers=color:purple%7Clabel:B%7C31.229861,121.459989&path=weight:5%7Ccolor:purple%7Cenc:y%7Cn%7DD_v~cV%5EkE?OCYGWI%5BYo@gB%7DCsFoK%7D%5Bem@g@oASe@Sk@%5BiAWoAaAkG%7D@aGAO@QBQFYBY?WSeV@gADqAFmCJiCLuDB%7BB@iB?c@Ac@Gs@KeAKgAKs@Mo@Wo@%5Bo@Wc@o@iBq@iDk@uCQiAEg@Ck@As@@y@H_BJ%7BANiBR_AhAwBBaAOmASeA?A?A?CCCEMUo@o@eBY%7D@Qe@k@%7BAg@%7BAGQGSEQAGAIEQ?GCSK_AIw@MkAEYMcAIW%5DcAm@aBc@kAKYMUUe@eAeCUi@ISYm@_BkEwAyDQUi@s@k@o@g@o@GGGKEKu@uB_@eAI%5BSs@Qo@Kc@Qk@_@%7B@_A%7DB_@_Ai@gAo@qACGGKQ%5Do@iA%5Dq@Qi@EUOq@E_@Eo@Iw@E_@KiA%5BeAEOYq@O%5BEIEIe@u@a@q@QUeAqBGOg@eAO%5Bk@_Bu@kCaBuE

**Comment by bpoplauschi** [comment]
Related to #1553 - to fix that issue, removed the query string from the url. This would strip your url to `https://maps.googleapis.com/maps/api/staticmap`

**Comment by bpoplauschi** [comment]
Because of #1589 we had to revert the fix for this issue. The remaining option is too use the `SDWebImageManager cacheKeyFilter` block param to override the default computation of they key in the library.
