### ISSUE TITLE
can't map file, errno=22 file '/Users/even/Documents/eBuGou/eBuGou/Lib/SDWebImage' for architecture i386

### ISSUE THREAD

**Issue by doudouhihi** [rs/SDWebImage#1434]
I download the source code of SDWebImage,and create a new project to build, and it runs succeed! But when i add the code to my project ,it report the errors of ‘can't map file, errno=22 file '/Users/even/Documents/eBuGou/eBuGou/Lib/SDWebImage' for architecture i386’ . Then I check the differences between the test project and my project，I find the same setting of Architectures and valid Architectures. So I don't know if some other configs may make this influence

**Comment by mythodeia** [comment]
did you follow these steps?
https://github.com/rs/SDWebImage#add-linker-flag
