### ISSUE TITLE
I got different size of image in different version with same setting

### ISSUE THREAD

**Issue by YJie** [rs/SDWebImage#1437]
I use 3.7.2 and over 3.7.2 got different size of image 
[texsxxxxx.zip](https://github.com/rs/SDWebImage/files/91657/texsxxxxx.zip)

**Comment by mythodeia** [comment]
you mean the downloaded cached image is different in 3.7.2 than in 3.7.4?
i tried in both and i get the same size images.

**Comment by YJie** [comment]
in the same image i got 220*220 in 3.7.4 but i got 440*440 in 3.7.2 the original is 440*440   the demo i send  you can change the version in Podfile you will find

**Comment by mythodeia** [comment]
in the 3.7.4 i got 440x440 in all images except one which was 800x800

**Comment by YJie** [comment]
but i got different size in demo what you said is the right size  i have tried many times in demo i just change the version i don't know why. i can find nothing difference except the verson of SDWebImage in3.7.2 is right but over3.7.3 is the wrong size

**Comment by mythodeia** [comment]
![screen](https://cloud.githubusercontent.com/assets/1748458/12353680/81620918-bb99-11e5-844c-6a9800c27b2a.png)

**Comment by YJie** [comment]
yeah i can got the image  you can find in simulator different version of SDWebImage you will find different size of image in simulator just tried 3.7.2 and over 3.7.3

**Comment by mythodeia** [comment]
i am sorry but i did not understand.

**Comment by YJie** [comment]
in jxphoto class the download image method you can find different size of image in complete block in different version of SDWebImage

**Comment by mythodeia** [comment]
maybe this is whats causing the change? [this](https://github.com/rs/SDWebImage/issues/576) 
commit: https://github.com/rs/SDWebImage/commit/dcde40fc01d2815070a2b4b496234aeb1b6d038e

**Comment by YJie** [comment]
maybe！ i just change the version of SD i will try later . No matter what thank you very much.

**Comment by mythodeia** [comment]
:+1:
