### ISSUE TITLE
I find a issue which appears in SDWebImageDecoder

### ISSUE THREAD

**Issue by yrx0910** [rs/SDWebImage#1441]
if the image is nil , the context be created also nil。So,I have the error: <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
(lldb) ;
In order to solve this problem, I add this code for the first line: 
```
if (!image) {
            return nil;
        } 
```

**Comment by mythodeia** [comment]
fixed with this https://github.com/rs/SDWebImage/pull/1464

**Comment by laojiawei** [comment]
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
what s happen?

**Comment by mythodeia** [comment]
@laojiawei are you using the latest commit?

**Comment by laojiawei** [comment]
yes,Using SDWebImage (3.7.5)

**Comment by mythodeia** [comment]
try using the latest commit not version.

**Comment by laojiawei** [comment]
I am such use :[self.pictureImageView sd_setImageWithURL:[NSURL URLWithString:status.cover_image_url]];
The ImageView is set  the Frame...

**Comment by laojiawei** [comment]
I using the latest commit now...

**Comment by mythodeia** [comment]
share the url of the image that produces the error

**Comment by laojiawei** [comment]
http://i.kuaikanmanhua.com/image/160202/a3ljbucwd.webp-w750

**Comment by mythodeia** [comment]
i tried it with the demo project and it works fine.

**Comment by laojiawei** [comment]
I try it again...Thx
