### ISSUE TITLE
sd_setimagewithurl don't show placeholderImage

### ISSUE THREAD

**Issue by liwuking** [rs/SDWebImage#1442]
[self.mImageView sd_setImageWithURL:[NSURL URLWithString:urlImage]
                      placeholderImage:placeImage options:SDWebImageLowPriority | SDWebImageRetryFailed];

firstly, placeholderImage don't show.No picture is blank before the download is complete

**Comment by bpoplauschi** [comment]
I don't understand the issue here. Closing. Feel free to reopen with a strong description: see what the issue should have here: https://github.com/rs/SDWebImage/blob/master/.github/ISSUE_TEMPLATE.md
