### ISSUE TITLE
 Crashed: NSOperationQueue 0x174431dc0 :: NSOperation 0x170338ec0 (QOS: USER_INITIATED)

### ISSUE THREAD

**Issue by madordie** [rs/SDWebImage#1443]
Thread : Crashed: NSOperationQueue 0x174431dc0 :: NSOperation 0x170338ec0 (QOS: USER_INITIATED)
0  libobjc.A.dylib                0x19805fbdc objc_msgSend + 28
1  UIKit                          0x18adfa864 -[UIImage dealloc] + 224
2  libsystem_blocks.dylib         0x198721910 _Block_release + 256
3  xxxxxxxxx                     0x100371a80 __destroy_helper_block_127 (SDWebImageManager.m:249)
4  libsystem_blocks.dylib         0x198721910 _Block_release + 256
5  CoreFoundation                 0x18625d0f8 CFRelease + 524
6  CoreFoundation                 0x18626aa20 -[__NSDictionaryM dealloc] + 156
7  CoreFoundation                 0x18625d0f8 CFRelease + 524
8  CoreFoundation                 0x1862651d8 -[__NSArrayI dealloc] + 88
9  xxxxxxxxx                     0x10036be90 __72-[SDWebImageDownloader downloadImageWithURL:options:progress:completed:]_block_invoke89 (SDWebImageDownloader.m:163)
10 xxxxxxxxx                     0x10036e8fc -[SDWebImageDownloaderOperation connectionDidFinishLoading:] (SDWebImageDownloaderOperation.m:398)
11 xxx                                    0x100a2b350 -[_priv_NBSClassForMultableInherit0 nbs0_connectionDidFinishLoading:] + 1538956
12 CFNetwork                      0x185dfd1e8 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 80
13 CFNetwork                      0x185dfd178 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 208
14 CFNetwork                      0x185dfd2f4 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 60
15 CFNetwork                      0x185ccfdfc ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 104
16 CFNetwork                      0x185d9a120 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 104
17 CFNetwork                      0x185cbbefc RunloopBlockContext::_invoke_block(void const*, void*) + 76
18 CoreFoundation                 0x18626097c CFArrayApplyFunction + 68
19 CFNetwork                      0x185cbbda8 RunloopBlockContext::perform() + 136
20 CFNetwork                      0x185cbbc5c MultiplexerSource::perform() + 312
21 CFNetwork                      0x185cbba88 MultiplexerSource::_perform(void*) + 68
22 CoreFoundation                 0x186337f8c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
23 CoreFoundation                 0x186337230 __CFRunLoopDoSources0 + 264
24 CoreFoundation                 0x1863352e0 __CFRunLoopRun + 712
25 CoreFoundation                 0x186260f74 CFRunLoopRunSpecific + 396
26 CoreFoundation                 0x1862b2ffc CFRunLoopRun + 112
27 xxxxxxxxx                     0x10036cf70 -[SDWebImageDownloaderOperation start] (SDWebImageDownloaderOperation.m:117)
28 Foundation                     0x187269f28 __NSOQSchedule_f + 228
29 libdispatch.dylib              0x1986c9954 _dispatch_client_callout + 16
30 libdispatch.dylib              0x1986d40a4 _dispatch_queue_drain + 1448
31 libdispatch.dylib              0x1986cca5c _dispatch_queue_invoke + 132
32 libdispatch.dylib              0x1986d6318 _dispatch_root_queue_drain + 720
33 libdispatch.dylib              0x1986d7c4c _dispatch_worker_thread3 + 108
34 libsystem_pthread.dylib        0x1988a921c _pthread_wqthread + 816
35 libsystem_pthread.dylib        0x1988a8ee0 start_wqthread + 4

**Comment by madordie** [comment]
xxx = project name

**Comment by bpoplauschi** [comment]
This looks like an issue with your code. Closing the issue due to missing activity. Feel free to reopen with additional info (SDWebImage version, repro rate, can you create a small demo project to show the crash).
