### ISSUE TITLE
Problem: 'libwebp/webp/decode.h' file not found

### ISSUE THREAD

**Issue by Ricardo1980** [rs/SDWebImage#1444]
I had this problem in the past
https://github.com/rs/SDWebImage/issues/1261
but after using that commit, the problem was fixed.

Now I am updating from cocoapods 0.39.0 to 1.0.0.beta.2.
With that version I cannot use:
pod 'SDWebImage/WebP', :head
but I use:
pod 'SDWebImage/WebP', :git => 'https://github.com/rs/SDWebImage.git', :commit => 'bf899e2'
and I see the changed explained in 
https://github.com/rs/SDWebImage/commit/bf899e222fb6e47a288977803bd16b1315c2297c

But I receive:
/Users/ricardoruizlopez/Desktop/wa-ios/Pods/SDWebImage/SDWebImage/UIImage+WebP.m:15:9: 'libwebp/webp/decode.h' file not found
And I see that the file is there.

So, I have no idea what's going on
Can you help me?

**Comment by mythodeia** [comment]
can you still replicate the issue?

**Comment by Ricardo1980** [comment]
Hello,
Are you talking about the last cocoapods beta? 1.0.0.beta.6
Or the last SDWebImage version?
Or both?
Thanks.

**Comment by mythodeia** [comment]
if you use the latest cocoapods version can you use pod 'SDWebImage/WebP', :head?
if no, how did you resolve the issue?

**Comment by barumrho** [comment]
I'm getting the same issue when using :head with `use_frameworks!` option for Cocoapods.
I'm using the latest beta 1.0.0.beta.6.

**Comment by alexito4** [comment]
I just tried pointing to the last commit in master and the issue is still happening (with cocoapods 1.0.0.beta.6)

`pod 'SDWebImage/WebP', :git => 'https://github.com/rs/SDWebImage', :commit => ‘0da78a4'`

**Comment by fen-x** [comment]
New version of CocoaPods [does not make symlinks of public headers](https://github.com/CocoaPods/CocoaPods/blob/1.0.0/lib/cocoapods/installer/file_references_installer.rb#L121) in case of frameworks used instead of static libraries (`use_frameworks!`).

Looks like that is why header is not found. So it is impossible to use `SDWebImage/WebP` over CocoaPods 1.0 in Swift projects.

**Comment by kenmaz** [comment]
My workaround is here:
https://github.com/kenmaz/SDWebImage/commit/5034c334be50765dfe4e97c48bcb74ef64175188

I solved it, but I think this workaround is too adhoc.

**Comment by fen-x** [comment]
@kenmaz Thanks a lot. It is great before official fix.

**Comment by liuyaodong** [comment]
Getting the same issue using cocoapods 1.0. It seems the only solution without workaround is downgrading cocoapods to 0.39. Will this be fixed officially?

**Comment by gonghao** [comment]
The same issue when using Cocoapods 1.0.0. Please fix it.

**Comment by bpoplauschi** [comment]
Yeap, it looks like the issue is caused by CocoaPods 1.0. Will fix it soon.
https://travis-ci.org/rs/SDWebImage/builds/130876102

**Comment by bpoplauschi** [comment]
Thanks guys for the info here. Thanks to @kenmaz, I was able to fix the issue.
