### ISSUE TITLE
UIButton may get a wrong image size

### ISSUE THREAD

**Issue by gliucn** [rs/SDWebImage#1446]
If image's original size is smaller than UIButton's bounds size, the image will be rendered in center mode, instead of "scale to fill" or some other selected modes.
Version 3.7.3 is OK.

**Comment by mythodeia** [comment]
i think the constraints here are at fault.
https://github.com/rs/SDWebImage/pull/1388

**Comment by bpoplauschi** [comment]
Closing, no response here.
