### ISSUE TITLE
No completedBlock will invoke

### ISSUE THREAD

**Issue by sunbohong** [rs/SDWebImage#1448]
I need to return true if the image is success download,so i use dispatch_semaphore_t to await it.But completedBlock couln't be invoked.
	
	__block BOOL sendSuccess = NO;
	dispatch_semaphore_t semaphore = dispatch_semaphore_create(0);
	[SDWebImageManager.sharedManager downloadImageWithURL:[NSURL URLWithString:thumbImageURL] options:SDWebImageRetryFailed progress:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
	if (finished && image) {
    	sendSuccess = true;
	} else{
	    sendSuccess = false;
	}
	dispatch_semaphore_signal(semaphore);
	}];
	dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);

**Comment by mythodeia** [comment]
did you try to post a notification instead?

**Comment by sunbohong** [comment]
@mythodeia  For some reason,i couln't use notification instead.Post a notification will increase the complexity.

**Comment by bpoplauschi** [comment]
Not sure what to do here.

**Comment by sunbohong** [comment]
I found the reason just now.
the doneBlock is called at main queue,so i can't wait a semaphore at main queue.
i have't to find a new solution to accomplish the goal.

            dispatch_async(dispatch_get_main_queue(), ^{
                doneBlock(diskImage, SDImageCacheTypeDisk);
            });

**Comment by bpoplauschi** [comment]
Great

**Comment by bluesky0109** [comment]
@sunbohong did you find a solution fix it?

**Comment by dreampiggy** [comment]
Using a semaphore to force transform a async function to sync one is a bad idea. And our most async function is called in main queue. Maybe a better solution is to create one sync version with the same feature. Can you create it by yourself ?

**Comment by bluesky0109** [comment]
@sunbohong @dreampiggy 
 
I found a solution, use dispatch_group for example:
```
__block BOOL sendSuccess = NO;
dispatch_group_t group = dispatch_group_create();
dispatch_group_enter(group);
[SDWebImageManager.sharedManager downloadImageWithURL:[NSURL URLWithString:thumbImageURL] options:SDWebImageRetryFailed progress:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
if (finished && image) {
    sendSuccess = true;
} else{
    sendSuccess = false;
}
dispatch_group_leave(group);
}];
dispatch_group_notify(group, dispatch_get_main_queue(), ^{
        if(sendSuccess) {
               // your logic  code
        }
});
```

wish help you 😊

**Comment by dreampiggy** [comment]
@bluesky0109 Oh, I forgot that GCD group. This will work because that this will not acutally block main queue. It will push current call queue(this case is main queue) to the GCD thread pool, and wait for that blocks in group to completed. After completed, it call `dispatch_group_leave` and GCD pop the call queue to go on execute. So this will not cause dead-lock like a lock or semaphore.

> This function schedules a notification block to be submitted to the specified queue when all blocks associated with the dispatch group have completed. If the group is empty (no block objects are associated with the dispatch group), the notification block object is submitted immediately.
