### ISSUE TITLE
Version 3.7.5 breaks semantic versioning (removes public API)

### ISSUE THREAD

**Issue by cdzombak** [rs/SDWebImage#1449]
[The 3.7.5 release](https://github.com/rs/SDWebImage/releases/tag/3.7.5) includes https://github.com/rs/SDWebImage/commit/5b05d6c3cc37df4b87d202a1b6ad6ee1f4d5c64c#diff-bdc7e3a487083b2ad4c00bdfc0345330 which removes a method from a public header. Per [semantic versioning](http://semver.org), this is a breaking API change which requires a new major version. This breaking change was instead released in a patch version.

The best route forward would be to re-add the old method's name (`sd_setImageWithPreviousCachedImageWithURL:andPlaceholderImage:options:progress:completed:`) to the interface, with an implementation that simply calls through to the new method.

Per [semantic versioning](http://semver.org), the next _minor_ release of SDWebImage may mark this old method as deprecated. It may then be _removed_ in the next major version of the library.

From [semver.org](http://semver.org)

> What do I do if I accidentally release a backwards incompatible change as a minor version?
>
> As soon as you realize that you’ve broken the Semantic Versioning spec, fix the problem and release a new minor version that corrects the problem and restores backwards compatibility. Even under this circumstance, it is unacceptable to modify versioned releases. If it’s appropriate, document the offending version and inform your users of the problem so that they are aware of the offending version.

**Comment by Mutix** [comment]
:+1:

**Comment by bpoplauschi** [comment]
Thanks @cdzombak for detailing this.
