### ISSUE TITLE
Certain URLS not working when setting image on 3.7.4-5

### ISSUE THREAD

**Issue by edalford11** [rs/SDWebImage#1457]
This is working on 3.7.3 but not on 3.7.4 or 3.7.5.

Example URL:
```objective-c
NSString *urlStr =  @"https://s3.amazonaws.com/st-avatars/production/23887/large-1284739798.png";
NSURL *url = [NSURL URLWithString:urlStr];
[self.userAvatar sd_setImageWithURL:url placeholderImage:nil];
```
The image never gets set.
The majority of URLS work, but some urls just don't. After downgrading to 3.7.3, they all work like they did before upgrading.

**Comment by ppaulojr** [comment]
Yes, it's happening on 3.7.5 and maybe it's related to https://github.com/rs/SDWebImage/issues/1123

**Comment by mythodeia** [comment]
this url produces a warning: 
```CGBitmapContextCreate: unsupported parameter combination```
check #1401 #1440 #1454 

as i have said before replacing the CGImageGetBitsPerComponent(imageRef) with 8 [here](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDecoder.m#L49) will make these images only work, but generate warnings for others.
a working solution would be to check if the bits per component result in an unsupported combination and if it does then roll back to the hardcoded 8.

**Comment by mythodeia** [comment]
@edalford11 @ppaulojr can you try this pull and let me know if it works for you? https://github.com/rs/SDWebImage/pull/1496

**Comment by ppaulojr** [comment]
It's working for me @mythodeia. Thanks!

**Comment by mythodeia** [comment]
fixed https://github.com/rs/SDWebImage/pull/1496
