### ISSUE TITLE
I don't want to load the gif,what can I do?

### ISSUE THREAD

**Issue by smallqiang** [rs/SDWebImage#1458]
Sometimes I will get the gif url from server.But I don't want to show the animation image.What can I do.

**Comment by mythodeia** [comment]
you can download a placeholder image and control the playback using something like [this](https://github.com/yfme/UIImageView-PlayGIF/blob/master/UIImageView-PlayGIF/UIImageView-PlayGIF/YFGIFImageView.m)

**Comment by sunbohong** [comment]
You can use `    imageView.image=image.images.firstObject;
` after you download the gif.
