### ISSUE TITLE
Make A GIF Only Show its First Frame..

### ISSUE THREAD

**Issue by akashyap99** [rs/SDWebImage#1463]
Hi Guys,
I've been using SDWebImage With swift and my app loads dribble shots, but sometimes when its a GIF it leaks the memory while loading and displaying it.. and sometimes if the Gif is too big it only shows the first frame. I've been using libraries like YLGIFImage and FLAnimatedImages but it hardly makes any difference .. can I please know how can I display a GIF but only its first frame showing and a small GIF logo which shows the user its a GIF. So I can prevent memory leaks.

Please mind, I am only 12 and fairly new to iOS Development.
Thanks in Advance Aryan

**Comment by mythodeia** [comment]
gif images is not the strong suit of this library. I have tried FLAnimatedImage and it works good without issues in most gif files. But if you want to get all images from a gif you can see [this](https://github.com/rs/SDWebImage/blob/master/SDWebImage/UIImage%2BGIF.m#L14) method.
take it apart and use it as you need. Modify it to get a single image to meet your needs.
