### ISSUE TITLE
 I want you to describe the correct copyright to UIIimage+GIF.h and UIImage+GIF.m

### ISSUE THREAD

**Issue by kirou** [rs/SDWebImage#1465]
Hi:

Since the copyright that has been described in these file is in the unknown, I want you to describe the correct copyright

https://github.com/rs/SDWebImage/blob/3.7.5/SDWebImage/UIImage%2BGIF.h#L6
https://github.com/rs/SDWebImage/blob/3.7.5/SDWebImage/UIImage%2BGIF.m#L6

**Comment by kirou** [comment]
We had to modify the copyright notation LBGIFImage.

https://github.com/larcus94/LBGIFImage/issues/8

This will also give me a fix.

**Comment by bpoplauschi** [comment]
Fixed with 94c1ec3e
