### ISSUE TITLE
carthage update creates an artefact called `WebImage.framework` — expected `SDWebImage.framework`

### ISSUE THREAD

**Issue by fatuhoku** [rs/SDWebImage#1467]
`SDWebImage` is the full name of this project, yet I'm surprised to find that the framework is called `WebImage`.

This causes any existing `#import <SDWebImage/*>` directives to fail for no good reason. I don't think it's right to force Carthage users to change these imports to  `#import <WebImage/*>`. This just isn't right.

**Comment by fatuhoku** [comment]
Bump — @rs any thoughts on this?

**Comment by flovilmart** [comment]
We could update that, PR welcom

**Comment by fatuhoku** [comment]
@flovilmart Hmmmmmm. I've actually come around to calling it `WebImage`. I'm sure it was done for good reason... was just surprised it wasn't written in any change log.

I wanted to put this out there to see if anyone else cares / prefers it one way over another.

I'll close this for now.

**Comment by briancaw** [comment]
Hey @sdwebimage,

We're running into issues with this name discrepancy, as it's making it less seamless for folks to transition between Cocoapods/Carthage, amongst things (and depending on how we solve this issues, could cause us to have to code around it in an undesirable way).  These issues would be solved if the Framework was named SDWebImage.  Is it possible to make that change?  Is there a compelling reason not to?

Thanks,
Brian
