### ISSUE TITLE
using SDWebImageManager with placeholder image?

### ISSUE THREAD

**Issue by Jackson0111** [rs/SDWebImage#1468]
First of all, thanks for such a fantastic framework! I've been using it ever since I started iOS programming. I'm using JSQMessageViewController for a chat app, which allows users to send text messages as well as images. The issue I'm encountering is when I load all messages (both texts and images), text messages obviously take much less time to load and images take longer. This behavior results in having messages in a wrong order. Text messages will be displayed before images even though the images were sent before texts. I was wondering if there's a work around to solve this, for example like a placeholder image? If not, any suggestions?

**Comment by bpoplauschi** [comment]
Could you make use of the `UIImageView` category methods? `sd_setImageWithURL:placeholderImage:completed:`?
