### ISSUE TITLE
SDWebImageManager downloadImageWithURL in retina device return image with half of original resolution

### ISSUE THREAD

**Issue by yongyeanng** [rs/SDWebImage#1470]
Hi , i having trouble to load the original image in retina device. The image return always in half of original size. Is this SDWebImage bug or iOS bug?

**Comment by mythodeia** [comment]
can you reproduce it with the latest version on the demo project?

**Comment by yongyeanng** [comment]
Here is the sample project i test with. I test on simulator for ipad air and ipad 2 the resolution return is different from the same image
[TestImageWebCache.zip](https://github.com/rs/SDWebImage/files/137533/TestImageWebCache.zip)

**Comment by mythodeia** [comment]
is this with the latest version of the library?

**Comment by yongyeanng** [comment]
yup, 3.7.5 rite ?

**Comment by mythodeia** [comment]
i checked your sample and the image that gets saved on disk is the correct size.
if you put a breakpoint in SDWebImageCompat.m on this:
```UIImage *scaledImage = [[UIImage alloc] initWithCGImage:image.CGImage scale:scale orientation:image.imageOrientation];```
you will see that the image that gets generated is half the size. this method generates a retina aware UIImage based on the scale of the device.
do another test. download the image locally and try this:
```
UIImage *tmp = [UIImage imageNamed:@"bf1ec0c3defa52e6f9d5ce466804187e"];
UIImage *scaledImage = [[UIImage alloc] initWithCGImage:tmp.CGImage scale:[UIScreen mainScreen].scale orientation:tmp.imageOrientation];
```
you will see again that the scaledImage is half the size again

**Comment by yongyeanng** [comment]
oh,  so is the ios issue. Thanks ya 

I think i have to use CGImageGetWidth and CGImageGetHeight for the actual size.

**Comment by mythodeia** [comment]
its not an issue of the IOS. the image that gets saved on disk is correct. The size is 1047 x 693 pixels.
When you log the size of the image using nslog the size you get is in points. you can read [this](http://www.idev101.com/code/User_Interface/sizes.html)
