### ISSUE TITLE
Getting custom Headers from response

### ISSUE THREAD

**Issue by beribas** [rs/SDWebImage#1471]
Hi,

great work you perform with this framework. I have a question: Is it possible to get (custom) response headers from a download operation? I need to evaluate them. 

As far as I understand, the only way would be to listen to `SDWebImageDownloadReceiveResponseNotification` and read response from the `SDWebImageDownloaderOperation` object.

Thanks

**Comment by beribas** [comment]
Ok, after a little bit more digging I found out that the response can be accessed through the downloadOperation which is returned by the downloadImageWithURL... call, eg:
`operation = SDWebImageManager.sharedManager().downloadImageWithURL(url, options: SDWebImageOptions(), progress: progressBlock, completed: completionBlock)`

In the completion block the full response can be accessed with operation.response

I close the issue.

**Comment by Insider77** [comment]
`... completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) { ...`

how to get the response from here?

**Comment by beribas** [comment]
Seems like there were some changes done since the time I opened this issue. I think there still must be a way to access the download operation and its response property.

**Comment by bpoplauschi** [comment]
Hmm, I'm not sure you can. At least from this level. you'll need access to the `SDWebImageDownloaderOperation` which has a `response` property.

**Comment by jeromeDms** [comment]
Hi There
Is there any news about this ?
I'm using sd_setImageWithURL to download an image, and I need to retrieve the session cookie, any tip to achieve this?
Any help would be greatly appreciated as I'm stuck on this issue.
Thanks

**Comment by dreampiggy** [comment]
Already available in 5.x via #2261

`SDWebImageCombinedOperation.downloadOperation.response.allHeaderFileds`. Use necessary force cast during this chain propery call.
