### ISSUE TITLE
SDWebImage 3.7.0 download and cache wrong image rarely

### ISSUE THREAD

**Issue by ahmedhussain** [rs/SDWebImage#1472]
hi,

Rarely i see that it loads wrong image eventhought it takes correct url, mainly notice this problem in iphone 6.

Can you please suggest me , which version solved this problem.

**Comment by rrallo** [comment]
#1123  & #1344 seem to be the same issue.

**Comment by sunbohong** [comment]
can you reproduce it with the latest version on the demo project?

**Comment by ppaulojr** [comment]
Yes we can.

**Comment by yingqiangh** [comment]
i have  the same problem in version 3.7.5

**Comment by mythodeia** [comment]
does this occur in v4 as well?

**Comment by mythodeia** [comment]
closing this. please reopen if you still face issues
