### ISSUE TITLE
Specify custom download queue.

### ISSUE THREAD

**Issue by jcampbell05** [rs/SDWebImage#1473]
I have a custom LIFO queue I am using for other network request, is there way of getting SDWebImage to use this as well ?

**Comment by mythodeia** [comment]
SDWebImage [these](https://github.com/rs/SDWebImage/blob/32923fa2e81a36513b2a0cd52e9bc615b08d2fb9/SDWebImage/SDWebImageDownloader.h#L54) to offer.
do you mean something else?

**Comment by jcampbell05** [comment]
@mythodeia  I was meaning the ability to pass it some custom NSOperationQueue for it to execute on.

**Comment by bpoplauschi** [comment]
At this point, there isn't such a possibility.
