### ISSUE TITLE
Threw error #201 (XML parsing failure)

### ISSUE THREAD

**Issue by lovemo** [rs/SDWebImage#1474]
CFDictionaryRef properties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, NULL);
<Error>: ImageIO: CreateMetadataFromXMPBufferInternal  Threw error 201 (XML parsing failure)

**Comment by mythodeia** [comment]
this is not an issue coming from the library rather than the image itself.the metadata of the image is causing the issue.
