### ISSUE TITLE
Images from web-url too small when using v. 3.7.4 and above

### ISSUE THREAD

**Issue by joridor** [rs/SDWebImage#1476]
Our QA found the issue.
Images downloaded from web-URL are only 1/2 size on retina devices and 1/3 size on iPhone 6(s)Plus, making for very tiny images on the 6(s) plus.
I think this was caused by setting scale on the UIImages.

Using:
[SDWebImageManager sharedManager] downloadImageWithURL:url
                                                   options:0
                                                  progress:
                                                 completed:

Works fine on 3.7.3
Cached images are correct.

**Comment by mythodeia** [comment]
The commit responsible for the change is [this](https://github.com/rs/SDWebImage/commit/f800a52f1c6eb409760bf14a5af5a636f3391100)
Similar issue #1470

**Comment by joridor** [comment]
@mythodeia So how can I get the original image without taking scale in mind?

**Comment by mythodeia** [comment]
if you are not interested in scale at all then revert the code in your ```SDWebImageDecoder.m``` file

**Comment by joridor** [comment]
@mythodeia That's a bit of a problem since we are using Cocoapods & the build server updates these on build. :)
Request: add an option/param for this

**Comment by mythodeia** [comment]
@bpoplauschi what do you think?

**Comment by davidear** [comment]
@mythodeia I have met the same issue, and I think I can understand the purpose of this change.  My concern is that since this change will influence many user's apps, so will you insist the change or revert back in future?

**Comment by wanghaihan** [comment]
Could you use a argument to enable it. And by default, it should be disabled.

**Comment by mythodeia** [comment]
i do not see any reason to revert back. also this commit was done quite a while back and we had no complains.

**Comment by nirsalon** [comment]
I also hit the issue, and it took me time to understand that SDWebImage is the cause. I'm not interested in scaling. I changed it back, but have the same concern as @davidear that next pod install would revert it.
I'd prefer a flag as well.

**Comment by mythodeia** [comment]
check the latest commit. the issue should now be resolved

**Comment by bpoplauschi** [comment]
Thanks guys, looks good with the revert.
