### ISSUE TITLE
Load and cache an image by API call - is it possible with SDWebImage?

### ISSUE THREAD

**Issue by EvgenyKarkan** [rs/SDWebImage#1477]
I have to download and cache an image not from its URL but by API calling. Is it possible? 
If so please give an example of how to do that.

**Comment by mythodeia** [comment]
the API you are referring to will return a url, right? then you can use SDWebImage to load that url and cache the image

**Comment by EvgenyKarkan** [comment]
@mythodeia ok, thanks that is clear, but what if API will return image data in bytes?

**Comment by mythodeia** [comment]
that would create a huge overhead. i do not think this is the best approach.
