### ISSUE TITLE
Image not loading from server?

### ISSUE THREAD

**Issue by mangireddy58** [rs/SDWebImage#1478]
```
NSString *mainBannerimage = [[responseArray objectAtIndex:indexPath.row]objectForKey:@"mainbanner"];
                    NSString *bannerImageURL  = [NSString stringWithFormat:@"demo.world.com/contest/banners/%@", mainBannerimage];
                    NSURL *imageURL = [NSURL URLWithString:bannerImageURL];
                    [cell.listBanner sd_setImageWithURL:imageURL
                                       placeholderImage:[UIImage imageNamed:@"profilepic_bg"]];
```
in this above code upto now i am getting the object into imageURL. after assigning to cell it is not loading. what is the problem in my code?
i checked with debugging when i am printing my [cell.listBanner ]setImageWithURL:imageURL
                                       placeholderImage:[UIImage imageNamed:@"profilepic_bg"]];
it is displaying like this in console "po [cell.listBanner sd_setImageWithURL:imageURL placeholderImage:[UIImage imageNamed:@"profile_bg"]];
error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=EXC_I386_GPFLT).
The process has been returned to the state before expression evaluation."

**Comment by ppaulojr** [comment]
It might be related to https://github.com/rs/SDWebImage/issues/1123

**Comment by mythodeia** [comment]
check the console for the value of this ```imageURL``` instead of what you did. Are you loading a correct url? does this occur in all your images? please use the demo project and debug your urls there. report back if there is an issue

**Comment by mangireddy58** [comment]
@mythodeia . you are correct!
