### ISSUE TITLE
How to display sdwebimage in scrollview?

### ISSUE THREAD

**Issue by mangireddy58** [rs/SDWebImage#1479]
In my app i want to display a image in scrollview using SDWebImage.
Here is my some of code

@try
    {
        if((NSNull *)[mainBannerScroll objectForKey:@"mainbanner"] != [NSNull null])
        {
            if([[mainBannerScroll objectForKey:@"mainbanner"] length] > 0)
            {
                NSString *mainBannerimage = [mainBannerScroll objectForKey:@"mainbanner"];
                NSString *bannerImageURL = [NSString stringWithFormat:@"http://demo.world.com/contest/banners/%@", mainBannerimage];
                NSURL *imageURL = [NSURL URLWithString:bannerImageURL];
                [self.scrollView sd_setImageWithURL:imageURL
                              //placeholderImage:[UIImage imageNamed:@"profilepic_bg"]];
            }
            else
            {
                //                    ivUserImage.image = [UIImage imageNamed:@"profilepic_bg"];
            }
        }
    }
    @catch (NSException *exception)
    {
        //            ivUserImage.image = [UIImage imageNamed:@"profilepic_bg"];
    }
i am getting error like this
![screen shot 2016-02-25 at 7 09 27 pm](https://cloud.githubusercontent.com/assets/14342272/13321159/55cea778-dbf3-11e5-82c4-ac9da76b87c6.png)

**Comment by mythodeia** [comment]
you should first place a UIImageView inside the scrollview. The method that crashes is because it only works with an imageview and not a scrollview
