### ISSUE TITLE
Bug feedback

### ISSUE THREAD

**Issue by a5978445** [rs/SDWebImage#1480]
![2016-02-29 3 29 26](https://cloud.githubusercontent.com/assets/11722240/13388238/55426bf6-def9-11e5-87ee-279b900f1150.png)
as shown in the figure，   When my equipment is in flight mode ， i  call "sd_setImageWithURL:" method 
then will feedback a  error obout this http request . but SDWebImageManager add  this url to  "failURLs" 

After that when i request the same URL ,it will be  Immediately return error， and  Not trying to network requests  。 

 so  i think   The following code is a bug :
 {

  BOOL shouldBeFailedURLAlliOSVersion = (error.code != NSURLErrorNotConnectedToInternet && error.code != NSURLErrorCancelled && error.code != NSURLErrorTimedOut);
                    BOOL shouldBeFailedURLiOS7 = (NSFoundationVersionNumber > NSFoundationVersionNumber_iOS_6_1 && error.code != NSURLErrorInternationalRoamingOff && error.code != NSURLErrorCallIsActive && error.code != NSURLErrorDataNotAllowed);
}

it  Does not take into account  All possible error.code value in offline mode .

**Comment by mythodeia** [comment]
from what i see in the image you are using an older version of the library. this has been resolved if you see [here](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.m#L196)

**Comment by a5978445** [comment]
thank you very much  !  i  will update SDWebImage .and then confirm again 。
