### ISSUE TITLE
crash some times

### ISSUE THREAD

**Issue by skytraveler** [rs/SDWebImage#1484]
0	libsystem_platform.dylib	0x00000001963d8dc8	_platform_memmove + 32
1	Foundation	0x000000018a21ed00	-[NSConcreteMutableData appendBytes:length:] + 500
2	Foundation	0x000000018a21b190	-[NSData(NSData) enumerateByteRangesUsingBlock:] + 96
3	Foundation	0x000000018a21eae4	-[NSConcreteMutableData appendData:] + 88
4	ourapp	0x00000001006a28b8	-[SDWebImageDownloaderOperation connection:didReceiveData:] (SDWebImageDownloaderOperation.m:253)
5	Foundation	0x000000018a21e898	___65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 80
6	Foundation	0x000000018a21e784	-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 232
7	Foundation	0x000000018a21e67c	-[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 80
8	Foundation	0x000000018a21ea80	__NSURLConnectionDidReceiveData + 80
9	CFNetwork	0x000000018934b2d8	invocation function for block in URLConnectionClient_Classic::_delegate_cacheTrifecta(_CFCachedURLResponse const*, void () block_pointer) + 432
10	CFNetwork	0x0000000189347698	invocation function for block in URLConnectionClient_Classic::_withDelegateAsync(char const*, void (_CFURLConnection*, CFURLConnectionClientCurrent_VMax const*) block_pointer) + 96
11	CoreFoundation	0x00000001896655e0	CFArrayApplyFunction + 68
12	CFNetwork	0x00000001892bca1c	RunloopBlockContext::perform() + 136
13	CFNetwork	0x00000001892bc898	MultiplexerSource::perform() + 288
14	CFNetwork	0x00000001892bc6d4	MultiplexerSource::_perform(void*) + 60
15	CoreFoundation	0x0000000189727644	___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
16	CoreFoundation	0x00000001897269a0	___CFRunLoopDoSources0 + 256
17	CoreFoundation	0x0000000189724c38	___CFRunLoopRun + 632
3	CoreFoundation	0x0000000189665c20	CFRunLoopRunSpecific + 452
19	CoreFoundation	0x00000001896bb2a8	CFRunLoopRun + 104
20	ourapp	0x00000001006a1adc	-[SDWebImageDownloaderOperation start] (SDWebImageDownloaderOperation.m:117)
21	Foundation	0x000000018a2d2a38	___NSOQSchedule_f + 76
22	libdispatch.dylib	0x0000000196247fd4	__dispatch_client_callout + 16
23	libdispatch.dylib	0x000000019624d654	__dispatch_async_redirect_invoke + 152
22	libdispatch.dylib	0x0000000196247fd4	__dispatch_client_callout + 16
25	libdispatch.dylib	0x000000019624f2b8	__dispatch_root_queue_drain + 556
26	libdispatch.dylib	0x000000019624f4fc	__dispatch_worker_thread2 + 76
27	libsystem_pthread.dylib	0x00000001963dd6bc	_pthread_wqthread + 344
1	libsystem_pthread.dylib	0x00000001963dd54c	__pthread_set_self + 8

**Comment by skytraveler** [comment]
there's lot of our users  suffers form this crash .  

for iPhone 5s   4s   iOS 7 users

**Comment by greatjam** [comment]
Signal info we got:SIGBUS (BUS_ADRALN)

**Comment by bpoplauschi** [comment]
Please try the latest version (3.8.2 which uses NSURLSession). Also, there is a 4.0 release coming. You should also try that when it's available.

**Comment by paulosigales** [comment]
News about this error? SDWebImageDownloaderOperation.m line 117
