### ISSUE TITLE
the default scale of method (SDScaledImageForKey) is wrong

### ISSUE THREAD

**Issue by Halley-Wong** [rs/SDWebImage#1487]
"CGFloat scale = [UIScreen mainScreen].scale; "cause image.size is smaller than downloaded image.size。
old version ，it is 1.0，so I guess ，it is wrong。

**Comment by mythodeia** [comment]
read this https://github.com/rs/SDWebImage/issues/1476

**Comment by mythodeia** [comment]
fixed with https://github.com/rs/SDWebImage/commit/29c9c5d68ace94c646292d2a647a558b5f87fbff
