### ISSUE TITLE
Issue with downloading Image

### ISSUE THREAD

**Issue by shashirbabu** [rs/SDWebImage#1490]
Hi i am  Using the below method for Image caching with tableview     
```
[cell.imageView sd_setImageWithURL:[NSURL URLWithString:postImage] placeholderImage:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
            cell.imageView.image =image;
        }];
```
But having an strange issue,when it is on device resolution of 320*568 ,the downloaded image size is coming correct (320 * 568) (original size is 640*1136),But if i do same on device resolution of 414*736,the downloaded image is coming as (320*410) (original size is 640*1136) Very strange please help me

**Comment by mythodeia** [comment]
if you revert [this](https://github.com/rs/SDWebImage/commit/f800a52f1c6eb409760bf14a5af5a636f3391100)
does it produce the result you want? if yes then read this #1476

**Comment by mythodeia** [comment]
check the latest commit. the issue should be resolved
