### ISSUE TITLE
Avoid placeholder image in case of SDImageCacheTypeDisk or SDImageCacheTypeMemory.

### ISSUE THREAD

**Issue by kidsid49** [rs/SDWebImage#1491]
I am using SDWebImageManager class to download the image and process it. When Image in disk or memory I get it instantly but its flickers for the moment as it sets placeholder first and then the image.
This is an issue when my app goes background and try to refresh the table view. 

What I want is the image is in disk or memory then I don't want to set the placeholder instead I want to  set the image directly. 

```
    SDWebImageManager *manager = [SDWebImageManager sharedManager];
    movieStoryCell.backdropImageView.image = [UIImage imageNamed:@"poster_placeholder_image"];
    [manager downloadImageWithURL:imageURL
                          options:SDWebImageAvoidAutoSetImage
                         progress:nil
                        completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
                            if (image) {
                                if(cacheType == SDImageCacheTypeNone || cacheType == SDImageCacheTypeDisk) {
                                    [UIView transitionWithView:movieStoryCell.backdropImageView
                                                      duration:0.35
                                                       options:UIViewAnimationOptionTransitionCrossDissolve | UIViewAnimationOptionCurveEaseInOut | UIViewAnimationOptionBeginFromCurrentState
                                                    animations:^{
                                                        movieStoryCell.backdropImageView.image = [GSStoryModel resizeBackdropImage:image];
                                                    } completion:NULL];
                                } else {
                                    movieStoryCell.backdropImageView.image = [GSStoryModel resizeBackdropImage:image];
                                }
                            }
                        }];
```

**Comment by mythodeia** [comment]
you said that when the image is cached on disk or in memory then you get it instantly but it flickers.
however you have this:
```if(cacheType == SDImageCacheTypeNone || cacheType == SDImageCacheTypeDisk) {```
which animates with a crossdissolve animation when the image is cached on disk or not at all.
In your else (memory cache type) statement you assign the UIImageView without animation.

**Comment by kidsid49** [comment]
@mythodeia  
If you look at afnetwork UIImageView cataogry. It takes care it very neat way.
So if you pass placeholder image to API, It will set only if image is downloaded from the web otherwise its sets the cached image directly. I do want to achieve the same thing here.
Eg. some check that can tell me that image is in memory or disk and I can avoid this line.
`movieStoryCell.backdropImageView.image = [UIImage imageNamed:@"poster_placeholder_image"];`

**Comment by bpoplauschi** [comment]
At this moment, I don't see this possible, as it is a trait of the framework to set the placeholder before querying the cache.
