### ISSUE TITLE
Prefetched images not transformed by SDWebImageManagerDelegate transform method

### ISSUE THREAD

**Issue by coryoso** [rs/SDWebImage#1492]
Prefetched images using SDWebImagePrefetcher do not go through `imageManager:transformDownloadedImage:withURL:` leading to a mix of transformed and untransformed images when being displayed in a collectionView using `sd_setImageWithURL`.

**Comment by runningfree100** [comment]
until other will answer, just want to add this info, -maybe- this will help :
 [SDWebImagePrefetcher sharedImagePrefetcher].manager.delegate is different 
then [SDWebImagePrefetcher sharedImagePrefetcher].delegate

I have a class the scale the images before cached in disk, and I set the object of this class to :
[SDWebImageManager sharedManager].delegate = [FBImageScaleBeforeSDWebImageCache sharedInstance];
[SDWebImagePrefetcher sharedImagePrefetcher].manager.delegate=[FBImageScaleBeforeSDWebImageCache sharedInstance];

this way, all photos are scaled before cache.
I'm not sure this solved your problem, but until other will answer, I thought maybe this will help

**Comment by coryoso** [comment]
How exactly do you scale images down with `SDWebImagePrefetcherDelegate`? 
`public func imagePrefetcher(imagePrefetcher: SDWebImagePrefetcher!, didPrefetchURL imageURL: NSURL!, finishedCount: UInt, totalCount: UInt)` does not allow transforming the image

**Comment by runningfree100** [comment]
1. [SDWebImagePrefetcher sharedImagePrefetcher].manager.delegate=YOUR_CLASS_OBJECT

2. YOUR_CLASS need to implement :
- (UIImage *)imageManager:(SDWebImageManager *)imageManager
 transformDownloadedImage:(UIImage *)image
                  withURL:(NSURL *)imageURL
{
    
   
    UIGraphicsBeginImageContext(imageSize); //imageSize = the scale size you want
    [image drawInRect:CGRectMake(0, 0, width, height)];
    image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}


this is how I did it and it works. maybe other have more info  about it.

**Comment by bpoplauschi** [comment]
@runningfree100 is correct, you just need to set your class as the delegate of both `[SDWebImagePrefetcher sharedImagePrefetcher].manager` and `[SDWebImageManager sharedManager]`
