### ISSUE TITLE
It contains GPL file to libwebp

### ISSUE THREAD

**Issue by ikitaki-gy** [rs/SDWebImage#1493]
Hi:

I want to use the SDWebImage but, following files of libwep within this library has hesitated to make use for the GPL license.

https://chromium.googlesource.com/webm/libwebp/+/v0.4.4/m4/ax_pthread.m4#72

That's GPL license, in the iOS app to be a re-distribution will be required to disclose the source code.

Since SDWebImage is a great library, but I want to use it by all means
It will not get served in the state that does not include the file of the GPL license.

**Comment by viljamik** [comment]
You should not be linking that file to your project so you should be fine.

**Comment by bpoplauschi** [comment]
Agree with @viljamik
