### ISSUE TITLE
can't install library successfully

### ISSUE THREAD

**Issue by nurmerey** [rs/SDWebImage#1494]
Hi everyone.
I've spent 2 days trying to install this library and I've tried everything i could google/find. I have followed https://github.com/rs/SDWebImage#add-linker-flag, and have installed it using cocoapods. 
My podfile looks like this:

> platform :ios, '7.1'
> pod 'SDWebImage', '~>3.7'
> 

I've looked at issues #885 and #862 and many others.

Basically problem starts as I put "-force_load $(TARGET_BUILD_DIR)/libPods.a" in. I doesn't compile and gives:

> ld: file not found: (project file path)-ggqxgurhsntrfegrcoocncawxiet/Build/Products/Debug-iphoneos/libPods.a
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 

Now, if I remove it, and leave only $(inherited), it compiles, but then it doesn't see any methods starting with "sd_". It does see other methods (ex: setImageWithURL:), however it gives warning to every one of them, saying that they are deprecated. 

> `'setImageWithURL:placeholderImage:' is deprecated: Method deprecated. Use `sd_setImageWithURL:placeholderImage:``

Last but not least, I've successfully installed the library by following instructions on a new objective c project. So I assume it has something to do with my existing libraries? 
My current list of other frameworks: Bolts, Fabric, Crashlytics, GAI, and Parse.

Does anyone have any idea what I can do to fix this?

N

**Comment by mythodeia** [comment]
did you try to add both force_load and inherited?

**Comment by nurmerey** [comment]
yes, i've tried all the combinations: using both, using one of each at the time. I've also tried 
`-force_load SDWebImage.framework/Versions/Current/SDWebImage
`
with and without $(inherited)

**Comment by mythodeia** [comment]
in order to see which library might be causing the issue what i would do is use the new project which you said you made it work and add one library at a time and see when it breaks. 
Then you can search if other users have had similar issues in the corresponding forum of that library.

**Comment by nurmerey** [comment]
Yep, that makes sense. I might give it a go. Thank you for your time @mythodeia!

**Comment by mythodeia** [comment]
please update this thread when you have more info :+1:

**Comment by nurmerey** [comment]
--------UPDATE--------
After further tweaking, before I finished testing with other libraries, I found solution that doesn't involve other libraries. 
Basically instead of using 
#import SDWebImage/UIImageView+WebCache.h
use 
#import "UIImageView+WebCache.h"

I've seen this fix before in other forums, but at the time when I tried it, it didn't help. So I assume its that and other settings that you need for stars to align:
In the Build Settings, under Other Linker Flags instead of having $(inherited) AND 
`-force_load $(TARGET_BUILD_DIR)/libPods.a
`
I only have $(inherited)
Also, current architecture is armv7 armv7s arm64, Build Active Architecture Only - Yes for Debug and No for release.

Hope this helps someone.

N

**Comment by mythodeia** [comment]
:+1:  thanks for the update

**Comment by RajaSaravanan** [comment]
UPDATE

I had the same issue, but I managed to get it worked without using
#import "UIImageView+WebCache.h"

- Actually my fix is that, I added the following in Other linker flags as mentioned in SDWebImage github site
-force_load $(TARGET_BUILD_DIR)/libPods.a
- but my libPods.a is libPods-SEED.a, where SEED is my project name.
- if you want to look your project's libPods.a file, look into image attached.
<img width="636" alt="screen shot 2016-04-08 at 9 48 53 pm" src="https://cloud.githubusercontent.com/assets/1026360/14385594/e45b0548-fdd3-11e5-8e25-0460e94ff740.png">
