### ISSUE TITLE
image downloading always stopped at  CFRunLoopRun();

### ISSUE THREAD

**Issue by nselimko** [rs/SDWebImage#1495]
I have Uitableview and for each cell I'm downloading image,but it's always stopping at  CFRunLoopRun() method

**Comment by mythodeia** [comment]
are you using the latest version?
please provide some code...or you can check the sample and then review your code.

**Comment by nselimko** [comment]
my version is 3.7, should i update the version ?

**Comment by mythodeia** [comment]
not necessarily. please check the code in the sample project with yours. does it produce any errors/warnings anything?

**Comment by nselimko** [comment]
This is my code. it's not producing error but debugging it's stoping always in this method,and sometimes it's crashing.
I think it's a problem,can you help me ?

    SDImageCache *imageCache = [[SDImageCache alloc] init];
    [imageCache queryDiskCacheForKey:carmodel.Id done:^(UIImage *image,SDImageCacheType cachetype)
    {
        // image is not nil if image was found
        if(image == nil)
        {
            [self.imageDownloader downloadImageWithURL:imagePath
                                                    options:SDWebImageDownloaderHighPriority
                                                   progress:^(NSInteger receivedSize, NSInteger expectedSize) {
                                                       // progression tracking code
                                                   }
                                                  completed:^(UIImage *image, NSData *data, NSError *error, BOOL finished) {
                                                      if (image && finished) {
                                                          cell.img.image = image;
                                                          [[SDImageCache sharedImageCache] storeImage:image forKey:carmodel.Id];
                                                          image = nil;
                                                      }
                                                  }];
            
            
        }
        else
        {
            cell.img.image = image;
        }

**Comment by mythodeia** [comment]
whats the crash message?

**Comment by nselimko** [comment]
As i saw it was "Run only on main thread" something like that.

**Comment by mythodeia** [comment]
something in your code is not running on main thread. check your code. as i said i tested it with the sample project and it works. So you must have something else that is running in backgorund
