### ISSUE TITLE
SDWebImage load webp image from a self-signed http2 server failed

### ISSUE THREAD

**Issue by zhujinlong** [rs/SDWebImage#1498]
My project is written in swift and I used 'SDWebImage' and 'SDWebImage/WebP' this 2 pods, my server is a self-signed http2 server and image request needs session token in header, so I wrote codes like belowing:

```
//set token in header
SDWebImageManager.sharedManager().imageDownloader.setValue(tokenString, forHTTPHeaderField: "TOKEN-HEADER")

//load webp image
imageView.sd_setImageWithURL(NSURL(string: url)!)

```
but print this error:

`NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)`

I already added belowing config in Info.plist,

```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>123.456.789.12</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
			</dict>
		</dict>
	</dict>
```

I noticed that there is an option `SDWebImageOptions.AllowInvalidSSLCertificates`, so I changed code like:

```
//set token in header
SDWebImageManager.sharedManager().imageDownloader.setValue(tokenString, forHTTPHeaderField: "TOKEN-HEADER")
            
//load webp image
imageView.sd_setImageWithURL(NSURL(string: url)!, placeholderImage: nil, options: .AllowInvalidSSLCertificates)
```

this code will not print error, but image cannot load into image view still.

Any good suggestions?

**Comment by mythodeia** [comment]
if you try to disable App Transport Security completely by doing this:
```
<key>NSAppTransportSecurity</key>  
 <dict>  
      <key>NSAllowsArbitraryLoads</key><true/>  
 </dict>
``` 
do you get the image?

**Comment by zhujinlong** [comment]
I already added NSAllowsArbitraryLoads in my Info.plist, as I post above, my Info.plist like belowing:

```
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
        <key>NSExceptionDomains</key>
        <dict>
            <key>123.456.789.12</key>
            <dict>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
            </dict>
        </dict>
    </dict>
```

I also did re-install, but still cannot get image.

Actually, when I use Alamofire to get json string from server, I also get this error, after I modified Info.plist like this, I can get json string successfully, but still cannot get image with SDWebImage.

**Comment by mythodeia** [comment]
@zhujinlong i meant to remove the NSExceptionDomains part and add only the NSAllowsArbitraryLoads key so i can see if the error comes from the exceptiondomains. 
Using Alamofire can you get the image ? Can you post a demo url along with a session token so we can test?

**Comment by zhujinlong** [comment]
Alamofire can get the image, it needs NSAllowsArbitraryLoads and sessionDidReceiveChallenge config, NSExceptionDomains is not necessary. Could you give me a personal email so I send you a demo project with url and session token to test?

**Comment by mythodeia** [comment]
i will email you on you Github email

**Comment by bpoplauschi** [comment]
Closing, due to lack of activity.
