### ISSUE TITLE
import SDWebImageManager.h have a error

### ISSUE THREAD

**Issue by wuzer** [rs/SDWebImage#1500]
I want to use SDWebImageManager cache image, just import header file error,tips "Block type deprecated. Use `SDWebImageCompletionWithFinishedBlock' ". i don't call this block ,only import header file.wish help me.

**Comment by mythodeia** [comment]
use this
```
       [[SDWebImageManager sharedManager] downloadImageWithURL:[NSURL URLWithString:@""]
                                                       options:SDWebImageContinueInBackground
                                                      progress:^(NSInteger receivedSize, NSInteger expectedSize) {

                                                      }
                                                     completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {

                                                     }];
```

**Comment by wuzer** [comment]
thanks for you reply me,i don't write code,only import header have a error

**Comment by mythodeia** [comment]
you mean you only included this ```#import SDWebImageManager.h"``` and its not working?

**Comment by wuzer** [comment]
@mythodeia yes

**Comment by wuzer** [comment]
@mythodeia delete `#import SDWebImageManager.h"` run ok

**Comment by mythodeia** [comment]
can you provide a sample project because i do not see this warning in mine. are you sure you are not calling it somewhere...

**Comment by wuzer** [comment]
@mythodeia jump to this code `#pragma mark - Deprecated
typedef void(^SDWebImageCompletedBlock)(UIImage *image, NSError *error, SDImageCacheType cacheType) __deprecated_msg("Block type deprecated. Use `SDWebImageCompletionBlock`");
typedef void(^SDWebImageCompletedWithFinishedBlock)(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished) __deprecated_msg("Block type deprecated. Use `SDWebImageCompletionWithFinishedBlock`");
`

**Comment by wuzer** [comment]
@mythodeia first i use newest version,but error,return 3.7 version

**Comment by mythodeia** [comment]
i see the deprecations but if you do not use them then you will not get any warnings

**Comment by wuzer** [comment]
@mythodeia yes,i mean,my project also use UIImage + webCache,is work right, today use SDWebImageManager show error. method not call.

**Comment by mythodeia** [comment]
if you tried to use the SDWebImageManager with the deprecated completionblock then thats why you got the warning. I am sorry if i am not understanding your issue. Please provide a demo project so i can see the error you are getting

**Comment by wuzer** [comment]
@mythodeia Thanks for you help,i try to find error by myself.

**Comment by wuzer** [comment]
@mythodeia i find my project have third framework MWPhotoBrowser,may be third framework conflict. have EMSDWebImageManager.h.

**Comment by mythodeia** [comment]
check if thats causing the issue then
