### ISSUE TITLE
SDWebImageManager gif loading issue in iPad Device

### ISSUE THREAD

**Issue by patelmayank** [rs/SDWebImage#1501]
My app has been receiving low memory warning because of I am loading the gif images in my app then after lost the connection in iPad device in simulator it works fine for me

Check this question for more info  

http://stackoverflow.com/questions/36077401/low-memory-warning-with-lost-connection-error-in-ipad-device

**Comment by bpoplauschi** [comment]
@patelmayank We have replaced our GIF component with a library from Flipboard (FLAnimatedImage). Could you try our 4.x branch ([instructions](https://github.com/rs/SDWebImage/tree/4.x#animated-images-gif-support)) and see if it helps?

**Comment by bpoplauschi** [comment]
Closing. The FLAnimatedImage solution replacing our own GIF is integrated into the 4.x branch.

**Comment by patelmayank** [comment]
@bpoplauschi  ok thanks i will check this and let you know

**Comment by bpoplauschi** [comment]
@patelmayank you can easily try using the 4.0.0-beta I released via CocoaPods.

**Comment by patelmayank** [comment]
Ok thanks @bpoplauschi
