### ISSUE TITLE
sd_setImageWithURL  can't show the image at the moment

### ISSUE THREAD

**Issue by Lidalu** [rs/SDWebImage#1502]
sd_setImageWithURL  With tableViewCell's imageView can't show the image at moment,and u have to touch cell, then the image show

**Comment by mythodeia** [comment]
please use the example project as reference. you might have missed something in your code.

**Comment by Lidalu** [comment]
[Uploading WebWork.zip…]()

**Comment by mythodeia** [comment]
you did not upload the zip correctly. try again

**Comment by Lidalu** [comment]
[WebWork.zip](https://github.com/rs/SDWebImage/files/182108/WebWork.zip)

**Comment by mythodeia** [comment]
[WebWork.zip](https://github.com/rs/SDWebImage/files/182262/WebWork.zip)

**Comment by Lidalu** [comment]
Why it can't work without a placeholderImage?
when I use  sd_setImageWithURL:  instead of sd_setImageWithURL:placeholderImage, the image also can't show at the moment , and need to click the cell

**Comment by mythodeia** [comment]
you should use with custom subclass if you want to use without a placeholder image.
or you can make a transparent placeholder image and use that one. this way the user will not see the placeholder at all

**Comment by Lidalu** [comment]
yeah，thank u
