### ISSUE TITLE
Cannot find cached images when update App

### ISSUE THREAD

**Issue by doingy** [rs/SDWebImage#1503]
Hi,
I cached image use follow code,
[[SDImageCache sharedImageCache] storeImage:image forKey:“some_image_url”];

read cached image,
[[SDImageCache sharedImageCache] imageFromDiskCacheForKey:“some_image_url”];

that's work well.

But, when my app update from 1.0 to 1.1, 1.1 can't open the cached images of 1.1.
How can I fix it? 
Thank you.

**Comment by mythodeia** [comment]
did you change anything in your app update? Did you change this library at all? Did you use the same version of this library in both of your versions?

**Comment by doingy** [comment]
Both version are used 3.7.5, and I haven't changed anything about sdwebimage.

**Comment by mythodeia** [comment]
how to you use the library? do you create any custom cache folders?

**Comment by sunbohong** [comment]
maybe,your image is expaired,the default cache age is one week.

> static const NSInteger kDefaultCacheMaxCacheAge = 60 * 60 * 24 * 7; // 1 week

**Comment by doingy** [comment]
@mythodeia using the library just for store images, and I haven't create any custom cache folders.

[[SDWebImageDownloader sharedDownloader]
  downloadImageWithURL:@"some_image_url"
  options:SDWebImageDownloaderContinueInBackground | SDWebImageDownloaderLowPriority | SDWebImageDownloaderAllowInvalidSSLCertificates
  progress:nil
  completed:^(UIImage *image, NSData *data, NSError *error, BOOL finished) {
    [[SDImageCache sharedImageCache] storeImage:image forKey:@"some_image_url"];
  }];

@sunbohong Maybe, have no idea about that.

**Comment by mythodeia** [comment]
@sunbohong might be right. Since you haven't changed versions of this library i think the cache age could be the culprit to your issues
