### ISSUE TITLE
image on custom tableViewCell cannot be shown,but just placeHolderImage

### ISSUE THREAD

**Issue by tangzzz-fan** [rs/SDWebImage#1505]
i used SDWebImage to load image for my custom cell like this:
//1 in cellForRow methods
//...
```
static NSString *cellIndentifier = @"LKIndexCell";
    LKJobIndexCell *cell = [tableView dequeueReusableCellWithIdentifier:cellIndentifier];
    if (!cell) {
        cell = [[LKJobIndexCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:cellIndentifier];
    }
    cell.job = self.jobsList[indexPath.row];
    return cell;
```
// 2 in cell's setter Model 
```
// jobHolderImgV is my custom imageView for cell
#import "UIImageView+WebCache.h"
- (void)setJob:(LKJobInfoModel *)job {
     _job = job;
     ...
    _job.jobHolderImgUrl = [_job.jobHolderImgUrl stringByReplacingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
     [self.jobHolderImgV sd_setImageWithURL:[NSURL URLWithString:_job.jobHolderImgUrl] placeholderImage:[UIImage imageNamed:@"place_holder"]];
}
```
at the end of show of cell.I just can see the placeHolder for cell'imageView ,i tried other methods as [self.jobHolderImgV sd_setImageWithURL:[NSURL URLWithString:_job.jobHolderImgUrl] placeholderImage:[UIImage imageNamed:@"place_holder"] options:SDWebImageRetryFailed]; and so on .failed too.
how can i solve this problem?

**Comment by mythodeia** [comment]
please check the sample project for more info

**Comment by tangzzz-fan** [comment]
well.i netted a project to show my difficulty in using SDWebImage ,maybe there are some mistakes.this is  the git url:https://github.com/tangzzz-fan/testUseSDWebImage.git .thankes for your help

**Comment by mythodeia** [comment]
you forgot to add these:
```
<key>NSAppTransportSecurity</key>  
     <dict>  
          <key>NSAllowsArbitraryLoads</key><true/>  
     </dict> 
```
in your info.plist file
more info [here](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33)

**Comment by tangzzz-fan** [comment]
thanks ,the question has been solved
