### ISSUE TITLE
Memory Leak with option SDWebImageRefreshCached

### ISSUE THREAD

**Issue by marcovanetti** [rs/SDWebImage#1506]
Hi, 
using the option SDWebImageRefreshCached, for example with with sd_setImageWithURL, I notice a consistent memory leak.
The leak is much more evident on the real device than the simulator. 
Here's a sample code to reproduce the leak:

```
- (IBAction)leakButton:(id)sender
{
    NSURL *imageUrl = [NSURL.alloc initWithString:@"https://avatars1.githubusercontent.com/u/68232?v=3&s=460"];
    SDWebImageOptions options = SDWebImageRefreshCached;
    for (int i = 0; i < 100; i++)
    {
        [imageViewToLoad sd_setImageWithURL:imageUrl placeholderImage:nil options:options completed:^(UIImage* image, NSError* error, SDImageCacheType cacheType, NSURL* imageURL) {
            NSLog(@"Completed.");
        }];
    }
}
```

![screen shot 2016-03-21 at 15 51 11](https://cloud.githubusercontent.com/assets/4971604/13922475/c45f7d88-ef7c-11e5-9884-a3667a86f6f2.png)

**Comment by bpoplauschi** [comment]
@marcovanetti the reason for the spike is that since the resource is https, it probably doesn't allow caching, so we keep downloading it every time, since that is what the `SDWebImageRefreshCached` is telling. You should try Allocations Instrument and see the what objects keep pilling up.
