### ISSUE TITLE
In Xcode 7.3 UIImageView+WebCache tips  ''cannot create __weak reference in file using manual reference counting''

### ISSUE THREAD

**Issue by Kemenger** [rs/SDWebImage#1508]
In Xcode 7.3 UIImageView+WebCache tips  ''cannot create __weak reference in file using manual reference counting''

**Comment by Kemenger** [comment]
The answer  is at https://forums.developer.apple.com/thread/38934

**Comment by bpoplauschi** [comment]
Sorry, but SDWebImage requires ARC.
