### ISSUE TITLE
when I come into detail Vc from tableView,and then back the tableView,the image reload once again,but before I came into the detail page ,the table cell image should be cached already.hope your reply

### ISSUE THREAD

**Issue by 1966767119** [rs/SDWebImage#1510]

**Comment by mythodeia** [comment]
please provide sample code. Can you reproduce it on the demo project?

**Comment by 1966767119** [comment]
I am sorry,the project is bigger,and I think I can describe it clearly.the problem is that ,I have a tableView ,and the cell has an image ,then set the image .
`[mainImgView sd_setImageWithURL:[NSURL URLWithString:dict[@"poster_img"]]placeholderImage:[UIImage imageNamed:@"pic"]];`
I scroll to the bottom ,(the table has about 50 rows ,that is to say it has 50 pics)
then  i select one row ,and then jump to the detail page,but when I back to the tableView ,I scroll to the top slowly,the pic in the row request from the web again. hope your help.
@mythodeia

**Comment by mythodeia** [comment]
can you replicate this issue in the demo project?

**Comment by 1966767119** [comment]
I will make a demo only for  that ,could you leave your email for me ?
@mythodeia

**Comment by mythodeia** [comment]
i think it would be easier to test the demo project. if the demo project works then there must be something wrong with your code. if you still cannot find it then you can post a sample demo project here so everyone can have a look and provide assistance

**Comment by 1966767119** [comment]
ok,wait a moment

**Comment by 1966767119** [comment]
I am very sorry for that ,I find the problem,some people in my team clear the image data,and not tell me .thank you for your help.@mythodeia
