### ISSUE TITLE
tvOS Framework build

### ISSUE THREAD

**Issue by mejim707** [rs/SDWebImage#1512]
Hi, we've been having considerable difficulty getting a framework compiled for support on tvOS devices and simulators. We've created the "fat" file that contains both simulator and device frameworks but when attempting to build for distribution or test flight testing we would receive the error that the framework is not compiled with full bit code. We then used the Xcode command line build function to create a framework with bit code enabled. We needed to use command line as doing it through the gui would strip bit code from the build. Once this was done we were able to begin uploading to iTunes but the upload will not complete, instead throwing errors that the SDWebImage framework is not valid and that it was not compiled using llib compiler. If possible can you provide a fully ready version of the tvOS framework for download that will support simulator, device and bit code? Thanks a lot

**Comment by bpoplauschi** [comment]
I'm not sure how to achieve this fat framework, but I think it's a generic question for packing frameworks and is not an issue with this library.

**Comment by GauravNamaWedig** [comment]
How did you created the Fat framework with Bit code enabled using command line function as I am also facing this problem.
