### ISSUE TITLE
Method in "SDWebImageDownloaderOperation.m" deprecated in Xcode 7.3

### ISSUE THREAD

**Issue by flyingbiz** [rs/SDWebImage#1515]
Hi,

I have updated my Xcode to version 7.3 recently and the warning message appeared afterwards. I hope there could be an update for the "SDWebImage" classes. 

Big thank you in advance :)

/SDWebImage/SDWebImageDownloaderOperation.m:96:52: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)

**Comment by bpoplauschi** [comment]
The deprecated `NSURLConnection` issue is handled in #823 and #1291
