### ISSUE TITLE
I use UIButton+WebCache, When the button highlighted the image get the wrong  direction 

### ISSUE THREAD

**Issue by perfectChao** [rs/SDWebImage#1520]
i use UIButton+WebCache, When i touch the button down make the button state turn to highlighted, there is some special image will change the image direction(such as url: http://www.bat360.cn/pics/72af292d-be5f-45f3-95b5-6773abb84550file33672947481238490124)

my button size is (258.0/3.0, 258.0/3.0)

my code at below:
          showImageBtn.sd_setBackgroundImageWithURL(NSURL(string: imgPath), forState: .Normal)

**Comment by mythodeia** [comment]
i hope you are not using the full image from that url as a background of the button. 
That image is 3042x4032  (width x height).

**Comment by perfectChao** [comment]
@mythodeia 

Thank you for your answer.
