### ISSUE TITLE
Image gets a clear row of pixels after being cached and returned by SDWebImageManager

### ISSUE THREAD

**Issue by pashaisthebest** [rs/SDWebImage#1522]
Here is a link to the image i'm caching with SDWebImageManager
http://46.101.27.143:8080/uploads/avatars/70/myfilname

After I do 
```
NSURL *newImageURL = [NSURL URLWithString:@"http://46.101.27.143:8080/uploads/avatars/70/myfilname"];
[[SDWebImageManager sharedManager] downloadImageWithURL:newImageURL options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) {
} completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
    weakAvatarNode.image = image;
}];
```
I put a breakpoint in the completion block and the image that i preview has a row of clear pixels on the right side. Here is the resulting image:

<img width="282" alt="407ce718-ff52-11e5-89a5-7cfa02458192-2" src="https://cloud.githubusercontent.com/assets/2697487/14411228/f9c5805e-ff52-11e5-8ca4-09923d3c51a5.png">

**Comment by mythodeia** [comment]
what do you mean by clear pixels? both images look the same to me

**Comment by pashaisthebest** [comment]
Yes they look the same, but in fact they are not the same. If you download and open the second image, you will see this. There is a 1-pixel wide row of pixels that are clear on the right side of the image, that is not present in the original.

![screen shot 2016-04-11 at 10 52 18](https://cloud.githubusercontent.com/assets/2697487/14420253/1880b106-ffdc-11e5-947a-050cd6a7932e.png)

**Comment by mythodeia** [comment]
i downloaded the original image and i still see this 1px line at the far right.
![pixel](https://cloud.githubusercontent.com/assets/1748458/14433575/72e58f14-0017-11e6-8d3c-41efe5f3beb9.png)

**Comment by pashaisthebest** [comment]
Wait, again - http://46.101.27.143:8080/uploads/avatars/70/myfilname here is the original image. Tried all kinds of browsers, everywhere I get no clear pixels for the original. 
https://youtu.be/C6Ki55ivnIc - video

**Comment by mythodeia** [comment]
again this is take from the original showing the 1 extra pixel at the right side:
![screen shot 2016-04-11 at 22 55 39](https://cloud.githubusercontent.com/assets/1748458/14440449/8a9e3f36-0038-11e6-9fea-a1d9fef7d906.png)
