### ISSUE TITLE
Null Response Issue

### ISSUE THREAD

**Issue by charbelhass** [rs/SDWebImage#1523]
Hello,

The api I am using has a feature that allow a user to remove his profile pic, he sends a request to the server so his photo is deleted.
But, in SDWebImage, it shows the last cached photo.
Note that i am using the option SDWebImageRefreshCached

this is my code 
`
NSURL *url = [NSURL URLWithString:[NSString stringWithFormat:@"%@%@?id=%@", API_HOST, API_SET_USER_PROFILE_PIC, [User currentUser].userId]];
`
`
[self.imageViewProfilePicture setShowActivityIndicatorView:YES];
`
`
[self.imageViewProfilePicture sd_setImageWithURL:url placeholderImage:[UIImage imageNamed:@"user_profile_icon"] options:SDWebImageRefreshCached];
`

Is there a way to remove a photo from cache in case the response received from sdwebimage was null

Thanks in advance

**Comment by mythodeia** [comment]
you can remove the image from cache using something like this:
```- (void)removeImageForKey:(NSString *)key fromDisk:(BOOL)fromDisk;``` from ```SDImageCache```
