### ISSUE TITLE
#292 problem seems reopen

### ISSUE THREAD

**Issue by yebw** [rs/SDWebImage#1524]
Now rendering a jpg image will alse cause blended layer.

**Comment by yebw** [comment]
why just use kCGImageAlphaNoneSkipLast in the CGBitmapContextCreate method?

**Comment by mythodeia** [comment]
What exactly is the issue? Do you have issues rendering jpg images? Can you provide sample jpg?

**Comment by yebw** [comment]
http://easyread.nos.netease.com/pic/2016/03/16/73955b4996d6411a96766592b35b263c.jpg

**Comment by yebw** [comment]
![image](https://cloud.githubusercontent.com/assets/1033003/14452864/08f287a8-00c4-11e6-9d5b-7687f283536c.png)
http://easyread.nos.netease.com/pic/2016/03/16/73955b4996d6411a96766592b35b263c.jpg

**Comment by mythodeia** [comment]
changing to kCGImageAlphaNoneSkipLast indeed solves this issue. 
However i do not know if it creates new issues with some other images.
change this line:
``` kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedFirst ```
to this
```kCGBitmapByteOrderDefault | kCGImageAlphaNoneSkipLast```
and let me know if that works for you in all your images

**Comment by yebw** [comment]
Yes，it works for me, I have tried dozens of images, and no new issues were created.
It seems that kCGImageAlphaNoneSkipLast is better than kCGImageAlphaPremultipliedFirst.
