### ISSUE TITLE
Queueing DiskIO can lead to memory overflow

### ISSUE THREAD

**Issue by eaglesnest3** [rs/SDWebImage#1528]
The disk write queueing behavior can be dangerous when the images are being cached at set intervals.  The problem is that if the workload was big enough to cause queueing once, it is likely to need it again on a subsequent run, and the system will get further and further behind.  The queueing causes SDWebImage to keep a reference to the images in memory, meaning that we run out of memory. 

Example that causes problem:
Image Size: 1920x1080
Number of Images: 20
Batch Interval: Every 1.5 seconds
Problems occur for us after 2 minutes of runtime

**Comment by bpoplauschi** [comment]
You can disable the memory caching and force SDWebImage to load from disk-cache everytime. Set `SDImageCache shouldCacheImagesInMemory` to `NO`.
