### ISSUE TITLE
Sometimes, App crash in SDWebImage Lib.(EXC_BAD_ACCESS KERN_INVALID_ADDRESS)

### ISSUE THREAD

**Issue by helloooideeeeea** [rs/SDWebImage#1530]
We have used SDWebImage Lib on Our App.(Version 3.7.2)
Recently, the app terminated abnormally sometimes. 
the following is stacktrace.

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0xxx

Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x180765bd0 objc_msgSend + 16
1  HOGE                      0x1002a94d8 -[SDWebImageDownloaderOperation cancelInternal] (SDWebImageDownloaderOperation.m:152)
2  HOGE                      0x1002a93ec -[SDWebImageDownloaderOperation cancel] (SDWebImageDownloaderOperation.m:138)
3  HOGE                      0x1002ad63c __69-[SDWebImageManager downloadImageWithURL:options:progress:completed:]_block_invoke131 (SDWebImageManager.m:245)
4  HOGE                      0x1002ae0f0 -[SDWebImageCombinedOperation cancel] (SDWebImageManager.m:321)
5  HOGE                      0x1002b5380 -[UIView(WebCacheOperation) sd_cancelImageLoadOperationWithKey:] (UIView+WebCacheOperation.m:44)
6  HOGE                      0x1002b0c74 -[UIButton(WebCache) sd_cancelImageLoadForState:] (UIButton+WebCache.m:144)
7  HOGE                      0x1002af578 -[UIButton(WebCache) sd_setImageWithURL:forState:placeholderImage:options:completed:] (UIButton+WebCache.m:54)
8  HOGE                      0x1002af3f8 -[UIButton(WebCache) sd_setImageWithURL:forState:placeholderImage:options:] (UIButton+WebCache.m:40)

Abort point is following.
[imageButton sd_setImageWithURL:[NSURL URLWithString:url] forState:UIControlStateNormal placeholderImage:nil options:SDWebImageRetryFailed];
(It's called Collection view cell 's layoutSubviews)

Why terminate abnormally?
(Is it Bad Access Memory?)

thanks!

**Comment by bpoplauschi** [comment]
Did you try updating to the latest version of SDWebImage?

**Comment by bpoplauschi** [comment]
No response. Closing
