### ISSUE TITLE
(NSURLErrorDomain error -1100) only with SDWebImage and HTTPS

### ISSUE THREAD

**Issue by sbiermanlytle** [rs/SDWebImage#1533]
This code works ok:

```
NSURL *imageURL = [NSURL URLWithString:@"https://i.groupme.com/638x640.jpeg.d4f31c747b534baca03d12db5a2b6193"];
NSData* theData = [NSData dataWithContentsOfURL:imageURL];
UIImage *image = [UIImage imageWithData:theData];
```

but this code fails with the error message **The operation couldn’t be completed. (NSURLErrorDomain error -1100.)**

```
[[SDWebImageManager sharedManager] downloadImageWithURL:imageURL options:SDWebImageRetryFailed progress:nil
    completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
        if (error){
            NSLog(@"[Util fetchPhoto] Error: %@", error.localizedDescription);
            if (completion)
                completion(NO, image);
            return;
        }
        if (completion)
            completion(YES, image);
    }];

```
Are there special settings I need to use for `HTTPS`?

Note that I am only seeing this issue with GroupMe images, but they are also the only ones with `https`. I am using SDWebImage for many other image sources in the same app and it works fine.

**Comment by mythodeia** [comment]
have you added any app transport security keys?
check [this](https://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/)

**Comment by sbiermanlytle** [comment]
Its an `HTTPS` url, so I shouldn't need to add exceptions.

I have a feeling its something to do with the URL format: `https://i.groupme.com/638x640.jpeg.d4f31c747b534baca03d12db5a2b6193`

maybe something in SDWebImage fails when the image extension is not at the end?

**Comment by mythodeia** [comment]
i used the url you provided in the demo project and it downloads and shows the image just fine.
the demo project has Allow Arbitrary Loads set to YES. Using https does not mean you should not use ATS correctly. App transport security requires a valid SSL which supports TLSv1.2
You can also read [this](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html?hl=fi) table 2 & 3
