### ISSUE TITLE
<Error>: CGContextDrawImage: invalid context 0x0

### ISSUE THREAD

**Issue by zhangmingjing** [rs/SDWebImage#1535]
总是出现这个警告

**Comment by mythodeia** [comment]
please use latest commit. there have been many changes in the ```SDWebImageDecoder.m``` file.
If still you face issues please reopen and provide a sample image so we can replicate

**Comment by zhangmingjing** [comment]
Tanks

**Comment by zhangmingjing** [comment]
Thanks
