### ISSUE TITLE
When I run pod install, return  [!] Unable to find a specification for `SDWebImage (~> 3.7)`

### ISSUE THREAD

**Issue by MISSAJJ** [rs/SDWebImage#1536]

**Comment by bpoplauschi** [comment]
This sounds like an issue with CocoaPods, not SDWebImage.
Can you provide more details?

For example, can you install other pods?

**Comment by MISSAJJ** [comment]
I can install other pos，for example AFNETWORKING，MBPROGRESSHUD，but SDWebImage……:-(

Warm Regards，

纯子(^_~)☆MISSAJJ

**Comment by mythodeia** [comment]
based on https://github.com/rs/SDWebImage/issues/1548#issuecomment-216945451
