### ISSUE TITLE
The operation got from downloadImageWithURL of SDWebImageDownloader cannot be cancelled?

### ISSUE THREAD

**Issue by leizh007** [rs/SDWebImage#1538]
```
- (id <SDWebImageOperation>)downloadImageWithURL:(NSURL *)url options:(SDWebImageDownloaderOptions)options progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageDownloaderCompletedBlock)completedBlock {
    __block SDWebImageDownloaderOperation *operation;
    __weak __typeof(self)wself = self;
    
    [self addProgressCallback:progressBlock completedBlock:completedBlock forURL:url createCallback:^{
            // configure operation
        }];
    
    return operation;
}
```

what function `    - (void)addProgressCallback:(SDWebImageDownloaderProgressBlock)progressBlock completedBlock:(SDWebImageDownloaderCompletedBlock)completedBlock forURL:(NSURL *)url createCallback:(SDWebImageNoParamsBlock)createCallback` does is it checkes if there's an operation downloading the image from url. If it is, then the  createCallback will never be called. So image a situation,  I first called `downloadImageWithURL` and get a operaion1, before the operation1 is done, I called `downloadImageWithURL` used the same url and get operation2, this time, the operaion2 is nil. So I cannot cancel the operation2.

**Comment by bpoplauschi** [comment]
This will be delivered in 4.0.0. See #883
