### ISSUE TITLE
 <Error>: CGContextDrawImage: invalid context 0x0.

### ISSUE THREAD

**Issue by laojiawei** [rs/SDWebImage#1541]
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Apr 26 21:06:56  LJWQuanZi[6574] <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
what s happen?

**Comment by mythodeia** [comment]
download the demo project and try it again. i used the url you provided and it works just fine.
please download the latest commits
