### ISSUE TITLE
Hi guys,I set url like follow format .but it does not work,it work well in the safari.  It is  a bug

### ISSUE THREAD

**Issue by niuxianbin** [rs/SDWebImage#1542]
The image Url is like this: http://image-demo.img-cn-hangzhou.aliyuncs.com/example.jpg@150w_150h_1e_1c_0i_100q_1x.jpg|watermark=1&object=cGFuZGEucG5n&t=51&p=9&x=10&y=10?spm=5176.docoss/oss-img-guide/style/visit.2.2.4xZw4k&file=example.jpg@150w_150h_1e_1c_0i_100q_1x.jpg|watermark=1&object=cGFuZGEucG5n&t=51&p=9&x=10&y=10

the image is in ALABAMA  cloud server . is this url string too long ? when i use SD to Download the image ,it does not work, I think this is maybe a BUG

**Comment by mythodeia** [comment]
i used the demo project and it works just fine. Try it there and let me know if you still encounter issues

**Comment by niuxianbin** [comment]
I am so sorry to Send wrong Image Url , this one I have double checked it ,it does not work well,  forward your reply~thanks :http://img.xm9m.com/static/XDkZia38/PRODUCT/xZgxgELK/xZgxgELK_1460714571202.jpg@1e_400w_400h_1c_0i_1o_1x.jpg|watermark=1&object=c3RhdGljL0RFRkFVTFQvUFJPRFVDVF9BUkVBL3Rlc3QyMDE2MDQwNC9MOEVTRmhOaF8xNDYwNDQzNDQwNzQxLnBuZw==&t=90&p=3&x=0&y=0

**Comment by mythodeia** [comment]
nope...works just fine. please the demo with your urls first
