### ISSUE TITLE
Images of tableView Flashes on reload

### ISSUE THREAD

**Issue by vivekshah05** [rs/SDWebImage#1543]
Hello ,
I am using SDWebImage but due to more memory consumption by my app, i used below line
`SDImageCache.sharedImageCache.shouldCacheImagesInMemory = FALSE;`
but after that my images of tableView Flashes on reload 

I tried below code to improve it , but still getting issue.
```
[cell.imgViewItem sd_setImageWithURL:url placeholderImage:[UIImage imageNamed:DEFAULT_ITEM_THUMBNAIL] options:SDWebImageRefreshCached completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            // do someting with image
            dispatch_sync(dispatch_get_main_queue(), ^{
                self.imgViewItem.image = image;
            });
        });

    }];
```

Can anybody help me on that ?

**Comment by bpoplauschi** [comment]
You are setting the image twice, probably that is causing the flash. `sd_setImageWithURL` will set the image automatically after the download is finished.

If you need to control setting the image, then use `SDWebImageManager downloadImageWithURL:options:progress:completed:` as follows:

```

[[SDWebImageManager sharedManager] downloadImageWithURL:url options:SDWebImageRefreshCached progress:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
...
}
```
