### ISSUE TITLE
Disabling caching for testing purposes...

### ISSUE THREAD

**Issue by ebalassanian** [rs/SDWebImage#1545]
Is there a way to disable caching all together for testing purposes?

**Comment by bpoplauschi** [comment]
I think there is. `SDImageCache shouldCacheImagesInMemory` should be set to `NO` to avoid memory caching. For the disk caching, you need to set `SDWebImageCacheMemoryOnly` as download option for `SDWebImageManager downloadImageWithURL:options:progress:completed:`. Let me know if this takes care of the caching.
