### ISSUE TITLE
SDImageCache queryDiskCacheForKey in collectionView

### ISSUE THREAD

**Issue by Sneakr** [rs/SDWebImage#1546]
Hi, 

This is my code to check for disk image in a collectionView inside a cell subclass:

[_cellImageCache queryDiskCacheForKey:mediaContentKey done:^(UIImage *image, SDImageCacheType cacheType) {
        if (image) {
            weakImageView.image = image;
        }

It works fine fetching the image from disk cache. But what happens is : 

When i scroll the collectionview fast, it seems to run all the "queryDiskCacheForKey" on all the cells that scroll by, and when I stop the scroll, the imageView.image sets to all the different images from all the querys until the correct cell image sets in.

Is there any way to cancel the disk query requests while im scrolling, for example in 
- (void)prepareForReuse ?

Edit:
I have tried to run the code outside the Cell subclass inside the "cellForItemAtIndexPath", but the results are the same.

**Comment by mythodeia** [comment]
in prepareforreuse you should nil your imageview's image.
e.g ```my_image_view.image = nil```

**Comment by Sneakr** [comment]
Hi , thanks for the quick reply,

I have tried that already, I set the imageView.image to nil, 

I also tried setting it hidden = YES and unhide it after the image is found and set in the queryDiskCacheForKey, it doesnt help neither. 

This problem is harder to reproduce on the latests iphones since the calculation is faster. If you try it on an iphone 6, you need to scroll down like 50 images, then I scroll really fast, or press the status bar for autoscroll to top. But If I try this on an older Ipad or 4s , you dont need to scroll as fast to generate the problem.

As I mentioned earlier, the queryDiskCacheForKey runs even when the cell is out of view, so the solution I think is to somehow stop the query if the cell is out of view, or in prepareForReuse (?)

I am testing this on Ipad, 4s, and iphone6 all latest iOS version.

**Comment by mythodeia** [comment]
can you reproduce it on the demo project?

**Comment by Sneakr** [comment]
I will give it a try now

**Comment by Sneakr** [comment]
Unfortunately I cant run the demo project it seems , since I import the class files manually to my project and not installed anything else other than Xcode. 

But the bug seems to take a couple times to reproduce, while scrolling 40+ images and letting all the images load so it saves to disk with :
[[SDImageCache sharedImageCache] storeImage:image forKey:mediaContentKey toDisk:YES];

After I have scrolled to the bottom, I just press the status bar for autoscroll to top, and the top cell image sometimes end up with the wrong image. Ive set a breakpoint in -

[_cellImageCache queryDiskCacheForKey:mediaContentKey done:^(UIImage *image, SDImageCacheType cacheType) {
        if (image) {
                _cellImageView.image = image;
                _cellImageView.hidden = NO;
        } 

When pressing the status bar to scroll to the top, above code seems to run 3-4 times seeing it with breakpoint. It isnt always reproducable and for the most part works fine, but occurs fairly enough to become a problem.

Further investigation to easier reproduce the problem:
When scrolling down and loading like 40+ images, I scroll back top, and i quickly scroll down and press the statusbar so it autoscrolls back to top WHILE i was in a fast scroll down. Then the top image sets to the wrong one. It is very easy to reproduce on older devices (iphone 4s , ipad etc) , but iphone 6 seems to calculate fast enough and have lower reproducable rates.

Is there any way to cancel the query request ? I tried assigning the SDImageCache to a property, and setting it to nil in "prepareForReuse", but it seems to have same issue.

**Comment by mythodeia** [comment]
you can try the demo project on its own on an older device too and check it out. no need to copy any files. just download the demo project by cloning the repo and run it on an older device.

**Comment by Sneakr** [comment]
@mythodeia I have now managed to try out the demo. I had to subclass the tableViewCell and the error is reproducable, even worse than on my own project.

Allso on the side note, i commented in the project youll see in MasterViewController.m , that on older devices, the didRecevieMemoryWarning causes app crash and black screen. (same with both my ipad and 4s testing devices) I had to set cache limit there as I show you in the demo project how to avoid that crash. I thought this only happened in my project but seem to happen in the demo project too. 

The demo-project is here:
https://www.dropbox.com/sh/62604g89td1x3d1/AABWBwoCzqfqms8wI79tqNo9a?dl=0

Thanks for your support and otherwise a great package!

**Comment by Sneakr** [comment]
Tutorial to reproduce error:

Visual error 1 (multiple changes in image, but correct image in the end gets set):
1: Scroll down to bottom, let all the images finish loading and get cached on the way.
2: Press status bar for quick scroll to top.

Visual error 2 (multiple changes in image, and wrong image sets in the end):
1: Scroll down to bottom, let all the images finish loading and get cached on the way.
2: Scroll back to top. 
3: Scroll down really fast, while scrolling, once press status bar and see the top image sets to wrong one.

**Comment by mythodeia** [comment]
why are you using ``` [[SDImageCache sharedImageCache] queryDiskCacheForKey``` instead of  ```[ [self.imageView sd_setImageWithURL:self.imageURL```

what happens if you run the demo as it is without subclassing the cell?

**Comment by Sneakr** [comment]
I missed out that the sd_setimage... had a progress count too, I tried to change the code to 

           [_mediaImageView sd_setImageWithURL:mediaurl placeholderImage:nil options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) {
            } completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
            }];

and now it works fine! Thank you :) Awesome!!!! I didnt know the sd_setImageWithUrl saves the file to disk (?) If it does, then everything is fine this way Ill change my code! Thanks again

**Comment by mythodeia** [comment]
yeap. it does all the heavy work for you.
👍

**Comment by Sneakr** [comment]
Awesome bro! Really great. Thanks again for taking your time! :)
