### ISSUE TITLE
Analyzing dependencies [!] Unable to find a specification for `SDWebImage`  [!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

### ISSUE THREAD

**Issue by MISSAJJ** [rs/SDWebImage#1548]
Analyzing dependencies
[!] Unable to find a specification for `SDWebImage`

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

**Comment by MISSAJJ** [comment]
Sorry, I have found that something wrong with my CocoaPods, after updated my pods, it had been run well....


1)    Do these:
 $ sudo rm -fr ~/Library/Caches/CocoaPods/
 $ rm -fr ~/.cocoapods/repos/master/
 $ sudo rm -fr Pods/
 $ sudo gem install cocoapods
 $ pod setup 
----------------
Setting up CocoaPods master repo
Updating 02f873f..1ee6599
Fast-forward
 Specs/GRKAnalytics/2.0.1/GRKAnalytics.podspec.json | 51 ++++++++++++++++++++++
 .../1.0.0/Segment-UrbanAirship.podspec.json        | 28 ++++++++++++
 2 files changed, 79 insertions(+)
 create mode 100644 Specs/GRKAnalytics/2.0.1/GRKAnalytics.podspec.json
 create mode 100644 Specs/Segment-UrbanAirship/1.0.0/Segment-UrbanAirship.podspec.json
From https://github.com/CocoaPods/Specs
   02f873f..1ee6599  master     -> origin/master
-----------------

2)    And then run the $ pod install 


Updating local specs repositories

Analyzing dependencies
Downloading dependencies
Using AFNetworking (2.6.0)
Installing DACircularProgress (2.3.1)
Installing MJExtension (2.5.12)
Installing MJRefresh (2.4.10)
Installing NJKWebViewProgress (0.2.3)
Installing SDWebImage (3.7.3)
Installing SVProgressHUD (1.1.3)
Installing pop (1.0.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 8 dependencies from the Podfile and 8 total
pods installed.


^_^

**Comment by MISSAJJ** [comment]
Sorry, I have found that something wrong with my CocoaPods, after updated my pods, it had been run well....


1)    Do these:
 $ sudo rm -fr ~/Library/Caches/CocoaPods/
 $ rm -fr ~/.cocoapods/repos/master/
 $ sudo rm -fr Pods/
 $ sudo gem install cocoapods
 $ pod setup 
----------------
Setting up CocoaPods master repo
Updating 02f873f..1ee6599
Fast-forward
 Specs/GRKAnalytics/2.0.1/GRKAnalytics.podspec.json | 51 ++++++++++++++++++++++
 .../1.0.0/Segment-UrbanAirship.podspec.json        | 28 ++++++++++++
 2 files changed, 79 insertions(+)
 create mode 100644 Specs/GRKAnalytics/2.0.1/GRKAnalytics.podspec.json
 create mode 100644 Specs/Segment-UrbanAirship/1.0.0/Segment-UrbanAirship.podspec.json
From https://github.com/CocoaPods/Specs
   02f873f..1ee6599  master     -> origin/master
-----------------

2)    And then run the $ pod install 


Updating local specs repositories

Analyzing dependencies
Downloading dependencies
Using AFNetworking (2.6.0)
Installing DACircularProgress (2.3.1)
Installing MJExtension (2.5.12)
Installing MJRefresh (2.4.10)
Installing NJKWebViewProgress (0.2.3)
Installing SDWebImage (3.7.3)
Installing SVProgressHUD (1.1.3)
Installing pop (1.0.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 8 dependencies from the Podfile and 8 total
pods installed.


^_^

**Comment by mythodeia** [comment]
👍
