### ISSUE TITLE
CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable. May  5 23:50:49  DT[2061] <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

### ISSUE THREAD

**Issue by MarkTangs** [rs/SDWebImage#1551]
if (!context) {
        if (unsupportedColorSpace){
            CGColorSpaceRelease(colorspaceRef);
        }
        return image;
    }

//after this call:

 CGContextRef context = CGBitmapContextCreate(NULL, width,
                                                 height,
                                                 CGImageGetBitsPerComponent(imageRef),
                                                 0,
                                                 colorspaceRef,
                                                 kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedFirst);

**Comment by MarkTangs** [comment]
in SDWebImageDecoder.m

**Comment by mythodeia** [comment]
try the latest commits. the code has changed and this issue was fixed.

**Comment by MarkTangs** [comment]
I was just updated

**Comment by mythodeia** [comment]
download the demo project and use the image url that produces this warning there. if you still face issues please reply
