### ISSUE TITLE
CGContextDrawImage: invalid context 0x0

### ISSUE THREAD

**Issue by jamezilla** [rs/SDWebImage#1552]
I'm seeing these errors running against the current 3.7.5 tag (ie. the cocoapods version). 
```
May  5 17:50:27  StageDebug[2362] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May  5 17:50:27  StageDebug[2362] <Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
```

There's some related closed issues which suggested testing these urls against the demo project, so I cloned `master` and indeed the problems seems to be fixed. Do you guys have an ETA for a 3.7.6 tag/cocoapods bump?

**Comment by bpoplauschi** [comment]
Not an exact ETA, but I am working on this

**Comment by bpoplauschi** [comment]
The 3.7.6 version is out
