### ISSUE TITLE
Cached file name with path extension UIWebView issue

### ISSUE THREAD

**Issue by danieltskv** [rs/SDWebImage#1553]
Since merging pull request #976 and appending the path extension to the hash filename, I experience issues with loading some images to UIWebView.

I use the cached disk images to show them in a UIWebView by loading an HTML String, like so:
`<img src='file://path_to_cached_image' />`
When loading images with a some path extensions, like this one: **http://nyppagesix.files.wordpress.com/2016/05/wp-thumb-72.jpg?quality=90&strip=all**

The cached image is stored with the filename: **2cabcbe083a662a651d1944304edc345.jpg?quality=90&strip=all** and the UIWebView canno't seem to load the image.

Is there a fix for this? Before #976 this never happen.
Thank you.

**Comment by bpoplauschi** [comment]
For iOS 7 and above, removed the query from the url using `NSURLComponents` (prior to iOS 7 the behaviour remains the same).

**Comment by bpoplauschi** [comment]
Because of #1589 we had to revert the fix for this issue. The remaining option is too use the `SDWebImageManager cacheKeyFilter` block param to override the default computation of they key in the library.
