### ISSUE TITLE
Question: Specify the scale of image regardless of key's extension

### ISSUE THREAD

**Issue by keepingitneil** [rs/SDWebImage#1554]
Is there any way to manually decide what the scale of an image should be? For example, I'm on a 2x device and the images I receive from my server are a bit larger than what I needed rendered so it scaled down.

Is there anyway I can manually tell SDWebImage that I want it to pretend the images are retina images so I get sharper rendering?

Would anybody else be interested in a PR with this functionality?

**Comment by bpoplauschi** [comment]
Like you noticed, we rely on the URL key to determine the scale of the images. If you can change the way the URLs are returned, you could add `@2x` in the name. 

Otherwise, a feature Pull Request should be created, offering a way to force a certain scale, even though I think that could cause more issues than help people.

**Comment by xiaoxiaoguang** [comment]
hello I want to know the function SDScaledImageForKey in SDScaledImageForKey.h;
why when the image.images.count == 0 need to do this
            if (key.length >= 8) {
                NSRange range = [key rangeOfString:@"@2x."];
                if (range.location != NSNotFound) {
                    scale = 2.0;
                }
                
                range = [key rangeOfString:@"@3x."];
                if (range.location != NSNotFound) {
                    scale = 3.0;
                }
            }

**Comment by xiaoxiaoguang** [comment]
key.length >= 8      how can i know

**Comment by bpoplauschi** [comment]
It's just a check. If the key contains `@2x` or `@3x`, it would look like `@2x.png` - this one has 7 characters. So we need at least 8 so it contains a name before `@2x`.

**Comment by dreampiggy** [comment]
Maybe in 4.x we have no ways to change (Since `SDWebImageOptions` is a Objective-C enum, which can only represent bool value :))

In 5.x, we can. See #2266

**Comment by dreampiggy** [comment]
In 5.x, you can use `SDWebImageContextImageScaleFactor` to specify the scale factor you desired. It works from View Category, Downloader, Cache and Coder. So this PR can be closed now. Wait for 5.0.0 release. :)
