### ISSUE TITLE
点击home键，进入后台；再重新进入。

### ISSUE THREAD

**Issue by Qingzhaowang** [rs/SDWebImage#1556]
let houseImageView = UIImageView()
houseImageView.sd_setImageWithURL(NSURL(string: item.housePicUrl))
不点击home键，可以获取到houseImageView.image。
点击home键，进入后台；再重新进入。houseImageView.image is nil.

**Comment by bpoplauschi** [comment]
Could you please translate to English?

**Comment by Qingzhaowang** [comment]
First ,click the home button, enter the background. Then enter again, has follow problem.
"
let houseImageView = UIImageView()
houseImageView.sd_setImageWithURL(NSURL(string: item.housePicUrl))"
houseImageView.image is nil.

**Comment by mythodeia** [comment]
can you replicate in the demo project?

**Comment by bpoplauschi** [comment]
Closing due to lack of information, per the [Contributing guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md).
