### ISSUE TITLE
Cannot change contentMode after image has been donwnloaded

### ISSUE THREAD

**Issue by intoxicated** [rs/SDWebImage#1557]
I'm using `sd_setImagewithURL:placeholderImage:options:completed:` method to load a image from web. The problem is I use different `contentMode` for placeholder and image from web, and `contentMode` did not apply after I changed it once the image has been downloaded. Sample code is following:

```
void(^completed)(UIImage *, NSError *, SDImageCacheType, NSURL *) = ^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) { 
    self.contentMode = UIViewContentModeScaleAspectFill;
}

self.contentMode = UIViewContentModeCenter;
 [self sd_setImageWithURL:url placeholderImage:[UIImage loadingSmall] options:SDWebImageRetryFailed completed:completed];
```

Is this normal behavior?

**Comment by khoren93** [comment]
+1

**Comment by bpoplauschi** [comment]
The issue here is that setting the `contentMode` must be done before doing other stuff like setting the image or the frame. In our case, when the completion is called, the image is already set, that's why setting the `contentMode` again doesn't have an effect. You can try to do
```
void(^completed)(UIImage *, NSError *, SDImageCacheType, NSURL *) = ^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) { 
    self.contentMode = UIViewContentModeScaleAspectFill;
    self.image = image;
}
```

**Comment by gorbat-o** [comment]
Hi, almost 3 years after this issue is still valid.
I did change the completed before checking up the issues and it does not work.

**Comment by gorbat-o** [comment]
Hi,
This issue is still valid. 
Last version on this library and it is still change the content mode for some reason.

Thanks
