### ISSUE TITLE
"sd_setImageWithURL " can not get image

### ISSUE THREAD

**Issue by Qingzhaowang** [rs/SDWebImage#1558]
housePicUrl = "http://7xrx6o.com1.z0.glb.clouddn.com/House-78348ed3-1188-4c67-bde5-788bbac73c3d_0_1_0_FD.png"
let houseImageView = UIImageView()
                houseImageView.sd_setImageWithURL(NSURL(string: housePicUrl))

then,  houseImageView.image = nil

why?

**Comment by bpoplauschi** [comment]
The image url doesn't work for me

**Comment by Qingzhaowang** [comment]
but ,open the url can see the image.
What requirement should the image url  satisfy？

**Comment by mythodeia** [comment]
@Qingzhaowang i tried the url on the demo project and it works fine.

**Comment by Qingzhaowang** [comment]
The problem has been solved. The solution is follow:
housePicUrl = "http://7xrx6o.com1.z0.glb.clouddn.com/House-78348ed3-1188-4c67-bde5-788bbac73c3d_0_1_0_FD.png"
let houseImageView = UIImageView()
houseImageView.sd_setImageWithURL(NSURL(string: housePicUrl), completed: { completed in
      //  Here, houseImageView.image is not  nil
})
