### ISSUE TITLE
Crash on SDWebImageDownloaderOperation.m line 117 -[SDWebImageDownloaderOperation start]

### ISSUE THREAD

**Issue by CavalcanteLeo** [rs/SDWebImage#1559]
I've got this crash tracked on Crashlytics:

SDWebImageDownloaderOperation.m line 117

     -[SDWebImageDownloaderOperation start]

<img width="1057" alt="captura de tela 2016-05-14 as 19 38 41" src="https://cloud.githubusercontent.com/assets/1735944/15271033/9cf835d2-1a0b-11e6-83fc-24ba171c0fcc.png">

<img width="1014" alt="captura de tela 2016-05-14 as 19 38 48" src="https://cloud.githubusercontent.com/assets/1735944/15271034/9cf85d5a-1a0b-11e6-965c-21e76ef5e070.png">

**Comment by mythodeia** [comment]
some of the duplicates #691 #1013 #1402 #1443 #1484

**Comment by patricktwenty20** [comment]
I'm having the same issue but getting a slightly different error message:

<img width="1024" alt="screen shot 2016-06-28 at 11 47 08 am" src="https://cloud.githubusercontent.com/assets/19782893/16428301/1e1bc826-3d26-11e6-9b71-a83587b69cc7.png">
