### ISSUE TITLE
Why there is a commit for “strong reference to UIImageView might cause a crash in the nested block”?

### ISSUE THREAD

**Issue by biluncloud** [rs/SDWebImage#1561]
I'm using an old version of SDWebImage but received a crash like this:

    0   libobjc.A.dylib                     0x000000019671bbd0 objc_msgSend + 16
    1   UIKit                               0x0000000189932eac -[UIView(Rendering) contentMode] + 316
    2   UIKit                               0x00000001899320e0 -[UIImageView _canDrawContent] + 144
    3   UIKit                               0x0000000189932bac -[UIImageView _updateState] + 36
    4   UIKit                               0x0000000189932b6c +[UIView(Animation) performWithoutAnimation:] + 88
    5   UIKit                               0x0000000189c6b340 -[UIImageView _updateImageViewForOldImage:newImage:] + 452
    6   UIKit                               0x0000000189932590 -[UIImageView setImage:] + 320
    7   xxxx                                0x0000000100927adc __85-[UIImageView(WebCache) setImageWithURL:placeholderImage:options:progress:completed:]_block_invoke + 100

The block where the crash is:

            __weak UIImageView *wself = self;
        id<SDWebImageOperation> operation = [SDWebImageManager.sharedManager downloadWithURL:url options:options progress:progressBlock completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished)
                                             {
                                                 __strong UIImageView *sself = wself;
                                                 if (!sself) return;
                                                 if (image)
                                                 {
                                                     sself.image = image;
                                                     [sself setNeedsDisplay];
                                                     [sself setNeedsLayout];
                                                 }
                                                 if (completedBlock && finished)
                                                 {
                                                     completedBlock(image, error, cacheType);
                                                 }
                                             }];

Then I found and fix of SDWebImage, the commit comment is: 
> Removed strong reference to UIImageView which was causing a crash in the nested block

Here is the [commit](https://github.com/rs/SDWebImage/commit/63d60d982601a3377fc0f3b8a15b3e7ea3f3bf08). The only change was removing the strong reference of the `UIImageView` in the block. 

[![The commit][1]][1]

Use strong reference in the block to keep the consistence is widely used, but why SDWebImage had this change. Why this might cause a crash? 

  [1]: http://i.stack.imgur.com/YHWhT.png

**Comment by biluncloud** [comment]
@bpoplauschi Do you have any idea?

**Comment by bpoplauschi** [comment]
I don't have any idea. Like you said, changing from a strong reference to a weak one is not an obvious fix for a crash. The issue here is this commit is super old (2013). I strongly suggest you use a newer version of SDWebImage.

**Comment by biluncloud** [comment]
@bpoplauschi I've already updated to the newer version, but this fix still seems strange to me.
