### ISSUE TITLE
about ipv6

### ISSUE THREAD

**Issue by huangping35** [rs/SDWebImage#1566]
apple ask for ipv6,so can support？

**Comment by JanzTam** [comment]
so can support？

**Comment by YangYouYong** [comment]
so can support ?

**Comment by bpoplauschi** [comment]
I'm not sure if our current networking code (based on `NSURLConnection`) supports ipv6, but we will rewrite that using `NSURLSession` in the 4.0 release, so I think ipv6 will be supported then.

**Comment by yu275184637** [comment]
excuse me，I would like to know SDWebImage 4 when it is expected to release?

**Comment by bpoplauschi** [comment]
We don't have a clear estimate, but aiming for this fall.

**Comment by JanzTam** [comment]
Thanks,man.

**Comment by tehnoir** [comment]
Starting June 1st (today/tomorrow), Apple requires all app submissions to support IPv6. Apps not supporting IPv6 may be rejected. https://developer.apple.com/news/?id=05042016a

**Comment by bpoplauschi** [comment]
We are working on the networking rewrite as we speak.

**Comment by bpoplauschi** [comment]
@tehnoir because of this June 1st milestone from Apple, I have made turned around our timeline and dedicated the 3.8.0 release for the `NSURLSession` support, so people can get it as soon as possible. A pull request is already open, we will test it properly and then release 3.8.

**Comment by bpoplauschi** [comment]
Resolved by #1578

**Comment by bpoplauschi** [comment]
3.8.0 version was just released.

**Comment by JanzTam** [comment]
Nice~

**Comment by HWSTS** [comment]
Hi there, my app was rejected 3 times for the IPV6 issue .
i only use Backendless  as backend & SDWebImage for download images (Vresion 3.8) from the Backend 
i just wanna be sure if any 1 still has this issue . the backendless support team replay ensure that their SDK fully support for IPV6

**Comment by ryandailey100** [comment]
Hi I am on the latest 4.0 version and I am having this problem. Apple rejects my app due to a lack of IPv6 support. When will this be fixed?

**Comment by bpoplauschi** [comment]
@ryandailey100 are you sure this is related to SDWebImage? Apple docs says `NSURLSession` supports IPv6.

**Comment by bpoplauschi** [comment]
https://developer.apple.com/news/?id=05042016a has details. We are ok by working with `NSURLSession`. There must be something different that you are doing, since a lot of people submit apps with SDWebImage included and do not get rejected (myself included).
