### ISSUE TITLE
sd_setImageWithURL in 3.7.6  is different from 3.7.5

### ISSUE THREAD

**Issue by iyakexi** [rs/SDWebImage#1567]
I updated my pod to version 3.7.6 and found that the image is twice bigger than before. Is this a bug or using the different strategy to deal with retina screen?

**Comment by mythodeia** [comment]
[this](https://github.com/rs/SDWebImage/commit/29c9c5d68ace94c646292d2a647a558b5f87fbff) was reverted
more info [here](https://github.com/rs/SDWebImage/issues/1517)
