### ISSUE TITLE
Unable to load animated webp

### ISSUE THREAD

**Issue by hw20101101** [rs/SDWebImage#1568]
`_objects = [NSMutableArray arrayWithObjects:
                    @"http://www.httpwatch.com/httpgallery/authentication/authenticatedimage/default.aspx?0.35786508303135633",     // requires HTTP auth, used to demo the NTLM auth
                    @"http://assets.sbnation.com/assets/2512203/dogflops.gif",
                    @"http://www.ioncannon.net/wp-content/uploads/2011/06/test2.webp",
                    @"http://www.ioncannon.net/wp-content/uploads/2011/06/test9.webp",
                    @"http://7x2wk4.com2.z0.glb.qiniucdn.com/magic_pic/dice/dice_anim_1.webp", //animated webp ,  Unable to load
                    
@"http://7x2wk4.com2.z0.glb.qiniucdn.com/magic_pic/dice/dice_1.webp", //static webp
                    nil];`

I would like to ask how to load the animated webp? thank you!

**Comment by bpoplauschi** [comment]
animated webp support is scheduled for the 4.0 release.

**Comment by hw20101101** [comment]
ok，thank you

**Comment by bpoplauschi** [comment]
Resolved by #1438
