### ISSUE TITLE
App crash on iOS 9.3

### ISSUE THREAD

**Issue by srinivasanVaradan** [rs/SDWebImage#1569]
App getting crashed on this line. UIImage+MultiFormat.m at line number 55 on tag version of 7.3.6. tested iOS version 9.3
 `CFDictionaryRef properties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, NULL);`

**Comment by mythodeia** [comment]
can you replicate the crash on the demo project? Do you have the image that causes this crash?

**Comment by bpoplauschi** [comment]
@srinivasanVaradan we need more information here: a stack trace and please try to replicate with our demo project.

**Comment by mythodeia** [comment]
closing this. please reopen when you have more info
