### ISSUE TITLE
Some of image can not load

### ISSUE THREAD

**Issue by Jasonmax1314** [rs/SDWebImage#1570]
The following image can not load, please help to find the root cause.
http://image.hnol.net/c/2012-12/30/16/20121230165305161-2089977.jpg

**Comment by Jasonmax1314** [comment]
I found out the root cause reason : I'm in china!!! sorry...

**Comment by zhujinlong** [comment]
This url can be load by SDWebImage correctly, and has no relationship with China's GFW, this url is not blocked.
