### ISSUE TITLE
crash on SDWebImageManager.m  line 64

### ISSUE THREAD

**Issue by lsflhuyy** [rs/SDWebImage#1573]
ios 7.1.1 
sdwebimage version 3.7.6

-[__NSConcreteURLComponents string]: unrecognized selector sent to instance 0x17dd1040

because 
`NS_CLASS_AVAILABLE(10_9, 7_0)
@interface NSURLComponents : NSObject <NSCopying>`
but  
`@property (nullable, readonly, copy) NSString *string NS_AVAILABLE(10_10, 8_0);`

@bpoplauschi

**Comment by bpoplauschi** [comment]
Good catch @lsflhuyy. Thanks.
