### ISSUE TITLE
Crash in iOS 7.1.1

### ISSUE THREAD

**Issue by Syhpox** [rs/SDWebImage#1574]
-[__NSConcreteURLComponents string]: unrecognized selector sent to instance 0x17ff58d0

**Comment by mythodeia** [comment]
duplicate? https://github.com/rs/SDWebImage/issues/1573
fixed with https://github.com/rs/SDWebImage/commit/22fded56cf832543f39283962d089d3f4d7d0f61

**Comment by Syhpox** [comment]
ok,I didn't notice,Thank you!
