### ISSUE TITLE
Canceling image loading with same URL cancels all image loadings with such URL.

### ISSUE THREAD

**Issue by bernikowich-cedoni** [rs/SDWebImage#1576]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 9.3
 SDWebImage Version      | 3.7.6
 Integration Method      | cocoapods
 Xcode Version           | Xcode 7.3.1
 Repro rate              | 80%, check warning in the project
 Demo project link       | http://rgho.st/8cYqy4j2F

### Issue Description and Steps

[imageView1 sd_setImageWithURL:URL];
[imageView2 sd_setImageWithURL:URL]:
[imageView1 sd_cancel];
// imageView2 will not receive image too.

**Comment by mythodeia** [comment]
👍  @bernikowich-cedoni

**Comment by bernikowich-cedoni** [comment]
@mythodeia Is it bug or feature? :)

I've found in SDWebImageDownloader.m:165-171 that all callbacks are removed when only one is canceled.

**Comment by mythodeia** [comment]
do you mean [this](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.m#L167-L171)

**Comment by bernikowich-cedoni** [comment]
Yes. :)

**Comment by mythodeia** [comment]
only one is removed,right?
```[sself.URLCallbacks removeObjectForKey:url];```

**Comment by bernikowich-cedoni** [comment]
@mythodeia removed all requests, but I expect removing one.
Maybe this is related: https://github.com/rs/SDWebImage/pull/883

**Comment by mythodeia** [comment]
@bernikowich-cedoni maybe. @bpoplauschi has made some commits in 4 branch regarding this issue from the post you linked. I will take a closer look later this week and i will reply if i find anything. If you want you can try this too https://github.com/rs/SDWebImage/pull/1575

**Comment by mythodeia** [comment]
@bernikowich-cedoni tested against the code in 4.x and it seems that this issue is fixed. please give it a go and let us know. thanks

**Comment by bpoplauschi** [comment]
Yeap. @mythodeia is right. Also, this issue was already reported #1113

**Comment by bernikowich-cedoni** [comment]
@mythodeia @bpoplauschi sorry for late answer. I've tested version 4.x and everything OK there. Thanks.
