### ISSUE TITLE
atal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

### ISSUE THREAD

**Issue by lfy-fly** [rs/SDWebImage#1577]
Analyzing dependencies
Downloading dependencies
Using AFNetworking (3.0.4)
Using MJRefresh (3.1.0)
Using Reachability (3.2)
Using SDCycleScrollView (1.61)
Installing SDWebImage 3.7.6 (was 3.7.6)
Installing libwebp (0.5.0)

[!] Error installing libwebp
[!] /usr/bin/git clone https://chromium.googlesource.com/webm/libwebp /var/folders/pr/q7dsv4rx0yv0hthtqpbw9j480000gn/T/d20160602-1438-1ptm78k --template= --single-branch --depth 1 --branch v0.5.0

Cloning into '/var/folders/pr/q7dsv4rx0yv0hthtqpbw9j480000gn/T/d20160602-1438-1ptm78k'...
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

**Comment by bpoplauschi** [comment]
This is an issue with the repo of libwebp, a dependency of SDWebImage. This repo is apparently not accessible in your country. You could instead install SDWebImage manually. See https://github.com/rs/SDWebImage#installation-by-cloning-the-repository

**Comment by lfy-fly** [comment]
but i see, you change the libwebp git url ,people from China can access it!

**Comment by bpoplauschi** [comment]
We have changed that url in our repo. But we cannot make that change in CocoaPods.

**Comment by 343415207** [comment]
If you are from china.

http://www.jianshu.com/p/b2f4df042e62

**Comment by manajay** [comment]
@343415207 文章已经被屏蔽了

**Comment by yunzixun** [comment]
new link: http://www.swifty.cc/2110.htm

**Comment by gujinku** [comment]
This web page helped me.
https://blog.csdn.net/qq_33487412/article/details/78458000

**Comment by wottery** [comment]
> If you are from china.
> 
> http://www.jianshu.com/p/b2f4df042e62

> 抱歉，你访问的页面不存在。
