### ISSUE TITLE
`SDWebImage (~> 3.8)` required by `Podfile`

### ISSUE THREAD

**Issue by hulizhen** [rs/SDWebImage#1580]
Hi.
I created a new Objective-C project with SDWebImage, but given the a dependency error when excuting `pod install`.
When I came back to version 3.7.6, everything was right again.

### Here is my Podfile
```
platform :ios, '9.0'
target 'MyApp' do
pod 'SDWebImage', '~>3.8'
end
```

### And the error message
```
[!] Unable to satisfy the following requirements:

- `SDWebImage (~> 3.8)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SDWebImage (~> 3.8)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 9.0
 SDWebImage Version      | e.g. 3.7.6
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 7.3.1
 Repro rate              | e.g. all the time (100%)

**Comment by bpoplauschi** [comment]
3.8 was not released yet. It will very soon, stay tuned.

**Comment by hulizhen** [comment]
Got it, thanks :)
