### ISSUE TITLE
SDWebImageManager.m crash at line 61

### ISSUE THREAD

**Issue by NSKevin** [rs/SDWebImage#1583]
* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description and Steps

I have a tableView with a lot of pictures. When I scrolled it fast, it crashed at SDWebImageManager.m line:61( method cacheKeyForURL: ) and the url is nil. So I add a safe check for url. It works. Hope it helpful. Thanks : )

**Comment by bpoplauschi** [comment]
@NSKevin please provide the other info from the template:

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. 8.0
 SDWebImage Version      | e.g. 3.7.6
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 7.3
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

**Comment by NSKevin** [comment]
@bpoplauschi First of all, thank you for working on SDWebImageView with  FLAnimatedImageView. Yesterday，I copyed your code(SDWebImage with FLAnimatedImageView) into my project and the SDWebImage is the newest one. Then I used your commit code to cover it (https://github.com/rs/SDWebImage/pull/1575/files). And I have a UITableView with a lot of gif. Then I scrolled it fast, it crashed at SDWebImageManager.m line 61. The log shows that url is nil. Then I add a safe check on url . Everything goes well.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        |  8.0
 SDWebImage Version      | 3.7.6
 Integration Method      | manually
 Xcode Version           |  Xcode 7.1
 Repro rate              | all the time 
 Repro with our demo prj | no
 Demo project link       | null
