### ISSUE TITLE
ImageView Flickering on a cell when reloadData

### ISSUE THREAD

**Issue by CavalcanteLeo** [rs/SDWebImage#1587]
### New Issue Checklist
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | ios |
| Platform Version | 9.0 |
| SDWebImage Version | 3.7.6 |
| Integration Method | cocoapods |
| Xcode Version | Version 7.3.1 (7D1014) |
### Issue Description and Steps

My imageView of a tableViewCell is flickering all the time I reload the tableview.
It only occurs using SDWebImage

on my tableViewCellForRow:

```
-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {

        AddUser_TableViewCell *cell;
        if (!cell) {
            cell = [tableView dequeueReusableCellWithIdentifier:@"UserAddCell" forIndexPath:indexPath];
        }
        User *user = searchModel.listOfUsers[indexPath.row];
        cell.delegate = self;
        cell.labelUsername.text    = user.username;
        cell.buttonAdd.selected    = user.following;
        cell.indexPath = indexPath;
        if(user.name){
            cell.name.hidden = NO;
            cell.name.text = user.name;
        }else{
            cell.name.hidden = YES;
        }

        [cell updateButtonUI];

        if(user.profilePictureURL){
            [cell.imageViewUser sd_setImageWithURL:user.profilePictureURL
                                  placeholderImage:nil
                                           options:SDWebImageProgressiveDownload];
        }else{
            cell.imageViewUser.image  = [UIImage imageNamed:@"avatar"];
        }

        return cell;

}
```

and the method to request the data from serve:

```
#pragma mark Search For Users
-(void)searchForUsers{
    if (searchModel.nextPageUsers == 0) {
        [self stopAnimationUsers];
        return;
    }
    if (self.searchBar.text.length <= 1 ) {
        timeHiRequestState = TimeHiRequestStateInactive;
        [searchModel.listOfUsers removeAllObjects];
        searchModel.listOfUsers = [NSMutableArray new];
        [self stopAnimationUsers];
        [self.tableViewUsers reloadSections:[NSIndexSet indexSetWithIndex:0] withRowAnimation:UITableViewRowAnimationNone];
        NSLog(@"*** reload data ***");
        return;
    }

    timeHiRequestState = TimeHiRequestStateLoading;
    [self.tableViewUsers reloadSections:[NSIndexSet indexSetWithIndex:0] withRowAnimation:UITableViewRowAnimationNone];

    [searchModel requestSearchPeopleWithName:self.searchBar.text success:^(AFHTTPRequestOperation *operation, id response, bool success){

        timeHiRequestState = TimeHiRequestStateSuccess;
        [self stopAnimationUsers];
        [self.tableViewUsers reloadSections:[NSIndexSet indexSetWithIndex:0] withRowAnimation:UITableViewRowAnimationNone];


    } failure:^(AFHTTPRequestOperation *operation, NSError *error) {
        timeHiRequestState = TimeHiRequestStateError;
        [self stopAnimationUsers];
        [self.tableViewUsers reloadSections:[NSIndexSet indexSetWithIndex:0] withRowAnimation:UITableViewRowAnimationNone];
    }];
}
```

I have tried with both [reloadData] and  [reloadSections withRowAnimation] and both are blinking the imageView

Here is the video of the issue:
[http://quick.as/r1w9tbYwR](http://quick.as/r1w9tbYwR)

**Comment by KanybekMomukeyev** [comment]
same here

**Comment by CavalcanteLeo** [comment]
no one?

**Comment by CavalcanteLeo** [comment]
it occurs on setShouldCacheImagesInMemory 

    just commented this line and it worked,
    [[SDImageCache sharedImageCache] setShouldCacheImagesInMemory:NO];


But if i don't use setShouldCacheImagesInMemory, SDWebImage will will be really be expensive, see https://github.com/rs/SDWebImage/issues/1544

**Comment by weiminghuaa** [comment]
SDWebImage will clear memory cache when app enter background. So, when app enter foreground, scroll tableView to refresh, and then reloadData, imageView in cell will flicker, even though data haven't changed. Right？
http://stackoverflow.com/questions/39960241/uiimageview-in-cell-flicker-when-tableview-reloaddata

**Comment by neilabdev** [comment]
+1

**Comment by sauchye** [comment]
@CavalcanteLeo  Hi, the same issues, but now version not method
``[[SDImageCache sharedImageCache] setShouldCacheImagesInMemory:NO];
``
Version 4.3.3 when i reload cell imageView Flickering, if you know please tell me, thank u :)

**Comment by sauchye** [comment]
@bpoplauschi @CavalcanteLeo Hi , same issues, but Version 4.3.3 not  this method 
``[[SDImageCache sharedImageCache] setShouldCacheImagesInMemory:NO];
``
if you know, please tell me ,thank u  :)
