### ISSUE TITLE
Fatal Exception: NSMallocException *** -[NSConcreteMutableData appendBytes:length:]: unable to allocate memory for length (22741011)

### ISSUE THREAD

**Issue by fysteven** [rs/SDWebImage#1588]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 7.0
 SDWebImage Version      | 3.7.5
 Integration Method      | cocoapods
 Xcode Version           | Xcode 7.3.1
 Repro rate              | only once
 Repro with our demo prj | no
 Demo project link       | 

### Issue Description and Steps

One of our users encountered this crash.

Fatal Exception: NSMallocException *** -[NSConcreteMutableData appendBytes:length:]: unable to allocate memory for length (22741011)

Fatal Exception: NSMallocException
0  CoreFoundation                 0x2f68ff4b __exceptionPreprocess
1  libobjc.A.dylib                0x39ad06af objc_exception_throw
2  CoreFoundation                 0x2f68fe8d -[NSException initWithCoder:]
3  Foundation                     0x2ffca879 _NSMutableDataGrowBytes
4  Foundation                     0x2ffca543 -[NSConcreteMutableData appendBytes:length:]
5  ImageIO                        0x303fced5 CGImageWriteSessionPutBytes
6  ImageIO                        0x30403d33 write_fn
7  ImageIO                        0x30404155 png_write_chunk_data
8  ImageIO                        0x30404097 png_write_complete_chunk
9  ImageIO                        0x30405a41 png_write_IDAT
10 ImageIO                        0x3040572f png_write_find_filter
11 ImageIO                        0x30404911 _cg_png_write_row
12 ImageIO                        0x304033f1 writeOnePng
13 ImageIO                        0x30402ad9 _CGImagePluginWritePNG
14 ImageIO                        0x303f50b7 CGImageDestinationFinalize
15 UIKit                          0x3200d9b5 UIImagePNGRepresentation
16 Branch                         0x18c3bd __72-[SDImageCache storeImage:recalculateFromImage:imageData:forKey:toDisk:]_block_invoke (SDImageCache.m:234)
17 libdispatch.dylib              0x39fb3d1b _dispatch_call_block_and_release
18 libdispatch.dylib              0x39fba273 _dispatch_queue_drain$VARIANT$mp
19 libdispatch.dylib              0x39fba06b _dispatch_queue_invoke$VARIANT$mp
20 libdispatch.dylib              0x39fbace1 _dispatch_root_queue_drain
21 libdispatch.dylib              0x39fbaf59 _dispatch_worker_thread2
22 libsystem_pthread.dylib        0x3a0f5dbf _pthread_wqthread
23 libsystem_pthread.dylib        0x3a0f5c84 start_wqthread

**Comment by bpoplauschi** [comment]
Was this a large image? Looks like the system could not allocate that memory. Not sure how to fix this.

**Comment by fysteven** [comment]
Not sure how large the image was, since the bug happened on a user's device.

**Comment by xxg90s** [comment]
我遇到了同样的问题，出现了4s设备上，图片大小106kb，只出现了一次，无法重现，有解决思路吗？

**Comment by fysteven** [comment]
咦？你怎么知道我是中国人？
暂时没有什么解决思路。可能是因为占用过多内存，然后就崩了。
因为内存占用情况没法重现，所以也不是每次都能崩溃。
另外一点是iOS 7可能比较老，这个问题可能被后续的版本修复了。

**Comment by bpoplauschi** [comment]
Please retry with 4.0.0 and reopen if it's still happening.
