### ISSUE TITLE
"Illegal Interface Qualifier" for SDWebImageOperation protocol on TVOS project

### ISSUE THREAD

**Issue by indieshack** [rs/SDWebImage#1592]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name        tvos
 Platform Version        ?
 SDWebImage Version      3.8
 Integration Method     cocoapods / manually
 Xcode Version          7.3

### Issue Description and Steps

Whichever way I bring SDWebImage into my previously compiling TVOS project I get an error in the SDWebImageOperation.h file: Illegal Interface Qualifier. The knockon is that there are three more errors from classes that can't use that interface. Currently a complete blocker.

**Comment by bpoplauschi** [comment]
Could you create a demo project with this issue?

**Comment by indieshack** [comment]
That's odd, I created a new TVOS project and imported SDWebImage source
files and don't see the error there. I wonder why I'm getting this error in
my code? Without SDWebImage my code compiles/runs fine. Any suggestions why
this particular protocol interface would bomb? I've even deleted the
SDWebImageOperation.h file and re-wrote it in case it was a file corruption
issue. But using SDWebImage either by manually installing or CocoaPods
gives the same issue.

On Fri, Jun 10, 2016 at 6:54 AM, Bogdan Poplauschi <notifications@github.com
> wrote:

> Could you create a demo project with this issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rs/SDWebImage/issues/1592#issuecomment-225187824>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AIJ455BNTUoBGzffcNwsQF1N_bS2I9hAks5qKWyCgaJpZM4Iy7Is>
> .
>



-- 
Greg Quinn
Indieshack Studios
Office: (858) 876-4023  Mobile: (760) 612 4808

**Comment by indieshack** [comment]
OK, my bad - another file (nothing to do with SDWebImage) had no closure. It's rank amateur time folks...
Apologies for the post.

**Comment by bpoplauschi** [comment]
Glad you found the issue
