### ISSUE TITLE
SDWebImageManager download image faild on iOS 8 Real test

### ISSUE THREAD

**Issue by 757388559** [rs/SDWebImage#1599]
Xcode Version 7.2 (7C68)
cocoapods 0.39.0
iOS 8.4 and 8.3
sdwebImage 3.7.3
Method:
````
NSURL *url = [NSURL URLWithString:@"http://img00.allinmd.cn/default/customer/190_190.jpg"];
[[SDWebImageManager sharedManager] downloadImageWithURL:url
                                                    options:SDWebImageRetryFailed|SDWebImageContinueInBackground
                                                   progress:^(NSInteger receivedSize, NSInteger expectedSize) {
                                                       
                                                   }
                                                  completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
                                                      if (error != nil) {
                                                          debugLog(@"头像----错误:%@" , error);
                                                      }
                                                      
                                                    if(image != nil && finished == YES)
                                                      {

                                                      }
                                                  }];
````
The error:
Error Domain=SDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels" UserInfo=0x17166a800 {NSLocalizedDescription=Downloaded image has 0 pixels}
but on ios 7 and 9 work good

**Comment by bpoplauschi** [comment]
@757388559 please fill all the info required, as stated in the [Contributing](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md#reporting-issues) doc. Also, please share the image url that is causing this.

**Comment by 757388559** [comment]
Xcode Version 7.2 (7C68)
cocoapods 0.39.0
iOS 8.4 and 8.3
Method:
NSURL *url = [NSURL URLWithString:@"http://img00.allinmd.cn/default/customer/190_190.jpg"];
[[SDWebImageManager sharedManager] downloadImageWithURL:url
options:SDWebImageRetryFailed|SDWebImageContinueInBackground
progress:^(NSInteger receivedSize, NSInteger expectedSize) {

                                               }
                                              completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
                                                  if (error != nil) {
                                                      debugLog(@"头像----错误:%@" , error);
                                                  }

                                                if(image != nil && finished == YES)
                                                  {

                                                  }
                                              }];

The error:
Error Domain=SDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels" UserInfo=0x17166a800 {NSLocalizedDescription=Downloaded image has 0 pixels}
but on ios 7 and 9 work good

**Comment by 757388559** [comment]
@bpoplauschi  i have update the problem

**Comment by mythodeia** [comment]
@757388559 i have tested your url with the demo project and it seems to be working just fine.
can you test it yourself in the demo project?

**Comment by 757388559** [comment]
@mythodeia  yeah ! i have tested another demo with real,it don't work also and  have the same error.
i use the real test.

**Comment by mythodeia** [comment]
please provide a sample project as i have tested the url/code you provided with the demo project and it works fine

**Comment by 757388559** [comment]
@mythodeia i have known the reasons, because of our searvers. very thanks for you
