### ISSUE TITLE
How can I get the sessionId when I use SDWebImage load an image?

### ISSUE THREAD

**Issue by Haoxueren** [rs/SDWebImage#1600]
How can I get the sessionId when I use SDWebImage load an image?

Thanks very much.

**Comment by bpoplauschi** [comment]
At this point, you can't. From 4.0 version (coming next), you will get back a token that can be used to cancel an image loading operation, but that's it. No access to the session.

**Comment by Haoxueren** [comment]
Thank you for you answer, if I can not get cookies directly, can I modify the source code to provide a enter method?

**Comment by bpoplauschi** [comment]
Feel free to make a pull request, but I'm not sure if this is something we need in the library.

**Comment by Haoxueren** [comment]
Sorry to trouble you again, I mean can I modify the local library or make wrapper to implement this fuction? 

can you give me a guide or demo? 

I know I ask for too much. So if you are busying now, Just Ignore my request.

Whatever, your are very nice, have a good day!

PS: I am a Java developer, I aks this question for our IOS developer.

**Comment by sunbohong** [comment]
Maybe,you can get it by assign your own's `operationClass`
