### ISSUE TITLE
I got NSURLErrorDomain error 415

### ISSUE THREAD

**Issue by gitspider** [rs/SDWebImage#1601]
I tried to download image using SDWebImageManager and I got error "The operation couldn’t be completed. (NSURLErrorDomain error 415.)".

This is the image url which is accessible by mobile devices.
http://limologs.com/uploads/diagrams/Q2FycGFzc2VuZ2VyLWNhci1rZXlsaW5lLTIyMjYzMzk2.jpg

What's the problem? I hope your help!

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 8.0
 SDWebImage Version      | 3.8.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 7.3

**Comment by mythodeia** [comment]
did you try to load this url in the demo project of 3.8.1 version?

**Comment by gitspider** [comment]
I've checked the url mentioned is working. Could you test with this one? http://api.limologs.com/v1/limo/vehicle_diagram?cls_id=3

**Comment by mythodeia** [comment]
this 
``` http://api.limologs.com/v1/limo/vehicle_diagram?cls_id=3 ```
redirects to this:
``` http://limologs.com/uploads/diagrams/SW50ZXJuYXRpb25hbCBNaW5pdmFuNA==.jpg ```
@bpoplauschi is there anything specific we need to know to make redirect urls work? I mean anything server side wise?

**Comment by gitspider** [comment]
I can download image from redirecting url by default methods such as NSData(contentsOfURL: url) or NSURLConnection.

I hope you will update the library to work with such redirecting urls.

**Comment by sunbohong** [comment]
Maybe,the server ride make some issue.

You can insert follow code before start a request.

    [[SDWebImageManager sharedManager].imageDownloader setValue:@"text/html" forHTTPHeaderField:@"Accept"];
