### ISSUE TITLE
-[SDImageCache storeImageDataToDisk:forKey:]: unrecognized selector sent to instance 0x17ee1ab0

### ISSUE THREAD

**Issue by HuiiChong** [rs/SDWebImage#1602]
hi，when I update the sdwebimage to latest, and use it to save a image to disk,like this:
```
NSData *_imageData = [NSData dataWithContentsOfURL:_url options:NSDataReadingMappedIfSafe error:nil];
[[SDImageCache sharedImageCache] storeImageDataToDisk:_imageData forKey:_imgUrl];
```
But, I get the message from Xcode:
`-[SDImageCache storeImageDataToDisk:forKey:]: unrecognized selector sent to instance 0x17ee1ab0`
I checked many times, the **_imageData** and **_imgUrl** is right.
and what happened?

**Comment by bpoplauschi** [comment]
@HuiiChong did you solve your issue?

**Comment by HuiiChong** [comment]
yes, when I clean the **Derived Data** and rebuild it. and it's ok now. this reason is I update form older version. so it's my misstake. I feel sorry about it.

**Comment by tzm529** [comment]
@HuiiChong Thank you very mach
