### ISSUE TITLE
Placeholder Image not shown in certain cases

### ISSUE THREAD

**Issue by salimgcet** [rs/SDWebImage#1603]
Hi Team,

I am new to SDWebImages.
Below are my findings
Case 1:
If I pass URL as nil placeholder image is not getting set.
Case 1:
If there is no internet connection, placeholder image is not getting set.

Please check below screenshots.
<img width="423" alt="screen shot 2016-06-24 at 2 32 48 pm" src="https://cloud.githubusercontent.com/assets/20122638/16329967/96319392-3a18-11e6-9d03-af2a4c985679.png">
### New Issue Checklist
- [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | e.g. ios / tvos |
| Platform Version | e.g. 8.0 |
| SDWebImage Version | e.g. 3.8.1 |
| Integration Method | e.g. carthage / cocoapods / manually |
| Xcode Version | e.g. Xcode 7.3.1 |
| Repro rate | e.g. all the time (100%) |
| Repro with our demo prj | e.g. does it happen with our demo project? -- Not tested in your demo |
| Demo project link | e.g. link to a demo project that highlights the issue -- I have created a demo project |
### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

Steps:
Table view contains image view which loads an image from URL.
Case 1:
1) Pass URL as nil  

case2:
1)Remove Cached image 
2) Turn off the internet connection and launch the application.

Looking forward for your inputs.

**Comment by salimgcet** [comment]
Can anyone update if you know the issue ?

**Comment by sunbohong** [comment]
can  you show some demo code?

**Comment by salimgcet** [comment]
Thanks for the quick response.

Please find the attached demo code for the issue.
[testCarApp.zip](https://github.com/rs/SDWebImage/files/338418/testCarApp.zip)

**Comment by sunbohong** [comment]
Please try follow code.
```
     [cell.carIcon sd_setImageWithURL:[NSURL URLWithString:[dict valueForKey:@"iconUrl"]] placeholderImage:[UIImage imageNamed:@"headImage"] completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
         if (image) {
             [cell.carIcon setImage:image];
             [cell.carIcon setNeedsLayout];
         }
     }];
```

**Comment by Wenzhi** [comment]
Reproduce the exact same issue in SDWebImage 4.0.0 in Xcode 8.2.1, integrated through Cocoapods. The above code doesn't fix the issue. Please let me know if you want more detail :)

**Comment by Wenzhi** [comment]
I found the reason, it was caused by my own code. Sorry for the false alarm!

**Comment by skyline75489** [comment]
Then I guess this issue can be safely closed?
