### ISSUE TITLE
gif webp is wrong  3.8.0

### ISSUE THREAD

**Issue by luomu0371** [rs/SDWebImage#1605]
http://p2.ycw.com/201510/31/e66ec43b2129a8f23ca2c00caf49c000_webp160

// Decode the WebP image data into a RGBA value array.
    if (WebPDecode(data.bytes, data.length, &config) != VP8_STATUS_OK) {
        return nil;
    }
here， return nil

**Comment by bpoplauschi** [comment]
It seems the image you provided is an animated webp image. It works now, due to #1438 that was merged into the 4.x branch. 4.0.0 release is coming
