### ISSUE TITLE
use_frameworks! Causes Compile Errors in SDWebImage Pod

### ISSUE THREAD

**Issue by aartivarma** [rs/SDWebImage#1606]
I get twelve compile errors in SDImageCache.h after adding "use_frameworks!" to my podfile. I am using 

pod 'SDWebImage', '3.8.0'

I also tried downgrading to 3.7.0 and 3.7.5, but I still get the issue. You can see some of the issues below... primarily they are "redefinition" and "duplicate interface" errors but searching my project I don't see any other instances of SDImageCacheType or SDImageCache.

When I remove the use_frameworks! line and pod update, everything is working perfectly and the errors go away. I could probably remove the library from my pod and add the raw files, but I would prefer to keep the pod.

![screen shot 2016-06-28 at 3 02 50 pm](https://cloud.githubusercontent.com/assets/2540568/16433892/6ae61434-3d41-11e6-8609-c0eae3d9a50d.png)

**Comment by sunbohong** [comment]
Have you try to reinstall CocoaPods from your project by `pod deintegrate &&  pod install`?

**Comment by bpoplauschi** [comment]
Or even delete the `DerivedData` folder. Looks like an Xcode issue.

**Comment by aartivarma** [comment]
Neither of those fixed the issue, even trying various permutations of closing xcode, deleting DerivedData, and pod install-ing. But I also suspect this is an Xcode issue. Thanks for the help!

**Comment by ikovalisko** [comment]
I've fixed these errors by using `@import SDWebImage;` everywhere in the project. Make sure you don't import a single header from this framework manually.
