### ISSUE TITLE
Cache some images and don't cache others 

### ISSUE THREAD

**Issue by nahlam** [rs/SDWebImage#1607]
I need to enable general caching but as some images are important but while navigating there are images in details pages that i don't want to cache either in memory nor in disk any idea how to do that?

**Comment by mythodeia** [comment]
check [this](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDImageCache.h#L53)
and [this](https://github.com/rs/SDWebImage/issues/1545)

**Comment by nahlam** [comment]
I don't want to disable for all images requests i need to cache only specific ones

**Comment by mythodeia** [comment]
you can remove the cached image on the completion block for those images you do not want to be cached. or use the ```SDWebImageDownloader``` and only cache the images you want on the completion block
