### ISSUE TITLE
images damaged

### ISSUE THREAD

**Issue by text2012** [rs/SDWebImage#1612]
I find there is some images damaged when I use SDWebImage, how to do ?
![img_1495](https://cloud.githubusercontent.com/assets/6036769/16576005/eb922a3c-42be-11e6-8434-5e8b3f8cd8b1.JPG)

**Comment by mythodeia** [comment]
download the latest version of the library and use the demo project to test the images and replicate the issue.

**Comment by lindow2009** [comment]
I've had the same problem.but when i clear cache and download again,it works done.so why and how to fix?

**Comment by yu275184637** [comment]
i've hd the same problem. half is gray.

**Comment by knighthb** [comment]
me too , my SDWebImage version is 3.7.1.  It's there a little chance that this situation will happen when  the network jitter，and reach the success callback, in this case imageData.length may less than self.exceptedSize ?

**Comment by wanrui** [comment]
@knighthb update

**Comment by flexih** [comment]
@yu275184637  Same problem, hard to replicate.
@knighthb the size is equal.

**Comment by yu275184637** [comment]
![image](https://cloud.githubusercontent.com/assets/13645233/20256176/bd99efae-aa7c-11e6-8215-14aee124c506.png)
point to the image

**Comment by wanrui** [comment]
@knighthb 讲中文的人在这里聊英文？

**Comment by zhouXiaoR** [comment]
me too,   but  we donnot find the reason.  is this a  BUG of "SDWebimage" ? The picture decode error sometimes.  help ! help! help !

**Comment by mythodeia** [comment]
can everyone test using the latest version?

**Comment by mythodeia** [comment]
please test using the latest version.
i am closing this for now. please reopen if you have more info.
