### ISSUE TITLE
the question of SDWebImageLowPriority

### ISSUE THREAD

**Issue by peakerWd** [rs/SDWebImage#1613]
when I scroll the UIScrollView ,I found the picture is still in the download, does it really work? could you explain for me?

    /**
     * By default, image downloads are started during UI interactions, this flags disable this feature,
     * leading to delayed download on UIScrollView deceleration for instance.
     */
    SDWebImageLowPriority = 1 << 1,

**Comment by bpoplauschi** [comment]
This means the download operation will use `NSOperationQueuePriorityLow` in the `NSOperationQueue` so other downloads have priority towards it. Look at the code for more clarification.
