### ISSUE TITLE
Ability to define the size of the image that will be cached

### ISSUE THREAD

**Issue by lunarbase** [rs/SDWebImage#1615]
It will be fine to be able to define the size of the image that will be cached.

I have a lot of remote images but I just want to have their thumbnails cached. 

So, I use SDWebImage to download that image but it will cache the full image, wasting a lot of space on memory and/or disk.

**Comment by mythodeia** [comment]
you can use this:
```- (UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL;
``` 
do your transforms inside and the result image will be the one that SDWebImage will cache

**Comment by lunarbase** [comment]
wow, great information, thanks!
