### ISSUE TITLE
CFNetwork internal error. Unable to load remote urls

### ISSUE THREAD

**Issue by kpavankotesh** [rs/SDWebImage#1617]
Error logs

```
8880: CFNetwork internal error (0xc01a:/BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork/CFNetwork-758.3.15/Loading/URLConnectionLoader.cpp:289)
```

Facing this issue while using https urls to load images. Issue was raised here as well ->  https://github.com/AFNetworking/AFNetworking/issues/3595 

Any help regarding fixing this issue?

**Comment by ad0ma** [comment]
how to resolve it?

**Comment by allanmacatingrao** [comment]
Any update on this?

**Comment by kpavankotesh** [comment]
Check this thread AFNetworking/AFNetworking#3595

**Comment by bpoplauschi** [comment]
I'm not sure how to approach this. The AFN thread does not describe a solution

**Comment by bpoplauschi** [comment]
No resolution here
