### ISSUE TITLE
SDWebImagePrefetcher crash

### ISSUE THREAD

**Issue by guidev** [rs/SDWebImage#1620]
<img width="1396" alt="screen shot 2016-07-16 at 23 08 56" src="https://cloud.githubusercontent.com/assets/1105813/16897183/4f84bd5e-4baa-11e6-8c71-cdcaaf0475db.png">

### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 8.0
 SDWebImage Version      | 3.8.1
 Integration Method      | cocoapods
 Xcode Version           |  Xcode 7.3
 Repro rate              |  100%
 Repro with our demo prj | no
 Demo project link       | 
### Issue Description and Steps

The app gets terminated by the os when the preloaded images don't fit into memory.  
When the app receives a memory warning, nothing happens, the cache continues to grow.

**Comment by guidev** [comment]
I believe that the best way to solve this is to disable the in-memory cache just for the prefetcher. Is there any way to do it?

**Comment by bpoplauschi** [comment]
Yes it is. Manually create the prefetcher, image manager and image cache and for this cache, set it not to use memory.

```
SDImageCache *cache = [[SDImageCache alloc] init];
cache.shouldCacheImagesInMemory = NO;
cache.shouldDecompressImages = NO;
SDWebImageDownloader *downloader = [[SDWebImageDownloader alloc] init];
SDWebImageManager *manager = [[SDWebImageManager alloc] initWithCache:cache downloader:downloader];
SDWebImagePrefetcher *prefetcher = [[SDWebImagePrefetcher alloc] initWithManager:manager];
```
