### ISSUE TITLE
SDWebImage not support iOS 7?

### ISSUE THREAD

**Issue by huynhbao** [rs/SDWebImage#1621]
I have added library SDWebImage with pod command, Xcode show error: requires iOS 8 and later
I used Xcode 7.3.1 Swift 2.2
Please tell me how to use SDWebImage for iOS 7 and later.
Thank you!

**Comment by bpoplauschi** [comment]
The current version of SDWebImage (3.8.1) works on iOS 7 and later. You just need to set your app to support iOS 7 as deployment target. Make sure your Podfile has `platform :ios, '7.0'`
