### ISSUE TITLE
error on loading images through https (v3.8.1)

### ISSUE THREAD

**Issue by pechn** [rs/SDWebImage#1624]
Dears,

I've encounter errors on loading images through **`https`** with options - **`SDWebImageAllowInvalidSSLCertificates`**.
After walking through the source codes, I found the below line (NO. 453) :

**`disposition = NSURLSessionAuthChallengeCancelAuthenticationChallenge;`**

in the method definition:

**`- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler`**

 of file **`SDWebImageDownloaderOperation.m`**.

If I change it to:

**`disposition = NSURLSessionAuthChallengePerformDefaultHandling;`**

Then everything run well.

Can anyone help me to clarify if it is a bug? 
And how to make correct configurations without changing the source codes if it wasn't a bug?

Thanks

**Comment by bpoplauschi** [comment]
Can you share the image causing the problem? I tried for instance with `https://www.ioncannon.net/wp-content/uploads/2011/06/test2.webp` which has an invalid SSL certificate and after setting `SDWebImageAllowInvalidSSLCertificates`, the download worked fine.

**Comment by bpoplauschi** [comment]
Closing. Please reopen if you have more info on this.

**Comment by stardustWK** [comment]
can you test for this url https://v4.api.kmg.goms.com.cn/public/images/weather/small/scattered_clouds.png

**Comment by mythodeia** [comment]
@stardustWK the url is working fine with the latest version. just tested in on the demo project

**Comment by stardustWK** [comment]
@mythodeia, I found work failed on simulator sometimes, work fine on device.
