### ISSUE TITLE
Sometimes something prevents us from getting current versions of images

### ISSUE THREAD

**Issue by brendanjerwin** [rs/SDWebImage#1625]
### New Issue Checklist
- [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | iOS |
| Platform Version | 9.x |
| SDWebImage Version | 3.8.1 |
| Integration Method | cocoapods |
| Xcode Version | Xcode 7.3.1 |
| Repro rate | sometimes. Have not yet found a pattern. |
| Repro with our demo prj | n/a |
| Demo project link | n/a |
### Issue Description and Steps

There are times when we seem to not get an updated image.

The effect, as seen by our users, is that an image at a URL appears to not update after a change. (we are downloading a fairly large image at a specific URL. Sometimes the image at that URL will change.)

We are calling SDWebImage like this:

```
static func loadImage(url: NSURL, completion: (image: UIImage, url: NSURL) -> Void) {
        let manager = SDWebImageManager.sharedManager()

        manager.downloadImageWithURL(url, options: [.RefreshCached], progress: nil) { (image, error, _, finished, _) in
            if let image = image where finished {
                completion(image: image, url: url)
            } else {
                DDLogError("While downloading: \"\(url.absoluteString)\" got: \(error)")
            }
        }
    }
```

We are using the following response headers and our servers are fronted by the cloud flare CDN:

```
Date:               Tue, 19 Jul 2016 18:27:51 GMT
Content-Type:       image/png
Transfer-Encoding:  chunked
Connection:         keep-alive
Set-Cookie:         __cfduid=d304992d6e96a57131af99cc58939ee8c1468952870; expires=Wed, 19-Jul-17 18:27:50 GMT; path=/; domain=.redacted.net; HttpOnly
Cache-Control:      max-age=0,must-revalidate
Etag:               "_lvPlDDoJWww6unMjZZAxQ-1242"
Last-Modified:      Tue, 19 Jul 2016 17:01:07 GMT
Via:                1.1 google
Alt-Svc:            clear
Server:             cloudflare-nginx
```

Our intent, with the `Cache-Control` and `Etag` headers is that the client will conditionally load the images. Usually we see that it works (both in end result behavior _and_ in what we see on the wire with a man-in-middle-proxy). We see conditional requests getting 304s, showing the cached image, and when we change the image the server responds with a 200 with a new Etag and the cycle repeats. Just like it should.

_Sometimes_, though, we see some very strange behavior:

1) We only ever get the _first_ callback from SDWebImage, the one containing the "old" version of the `UIImage`.
2) On the wire, we see _1_ request, with an `If-none-match` header, that has a non-current Etag. This gets a 200 response with a proper image payload. 

This is what we see once the thing is in a broken state. Once in this state, we never seem to get the second callback with the result of the server response. We also see that subsequent attempts to load the image seem to be stuck in this same pattern: only one callback, request contains an Etag, response is 200. While this is happening, we also note that the `If-none-match` value being sent does not seem to change _and_ is not the value being returned in the 200 responses' Etag header. 

Stopping the app does not seem to get us out of this state. Reinstalling it seems to help. 

My uninformed guess is that the disk cache is getting corrupt but, of course, that's just me. :)

**Comment by brendanjerwin** [comment]
The images were fairly large. ~1mb
Reducing the size helped, things seem to be behaving better once we made the images smaller. So, I think there is something going on here with the cache(s).

**Comment by choipd** [comment]
I have the same issue.  After entering this strange state, clear disk or memory not work. I've changed to 4.0 beta but still failed.

**Comment by dreampiggy** [comment]
This issue is not active for long time and may because of old version's issue. Feel free to reopen it if you're still interested in this issue.
