### ISSUE TITLE
loading image crash

### ISSUE THREAD

**Issue by yunjinghui123** [rs/SDWebImage#1626]
i have crash in UIImage+MultiFormat.h  line37,  image = [[UIImage alloc] initWithData:data];   data is have Data,but image is nil, device iPad 7.1.2

**Comment by JohnWickham** [comment]
I'm having this issue as well on iOS 8.4.1, iOS 9.3.3, and iOS 10.0 beta 3.

The crash occurs at `+[NSData sd_contentTypeForImageData:]:` and produces 

> reason: '+[NSData sd_contentTypeForImageData:]: unrecognized selector sent to class 0x37abb54c'

Like yunjinghui123, data is present, but `image` and `imageContentType` are both `nil`.

**Comment by bpoplauschi** [comment]
This should no happen, right now we have a check at the beginning of the `sd_imageWithData` function:
```
if (!data) {
        return nil;
    }
```
