### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by katriciab** [rs/SDWebImage#1627]
Will there be support for Swift 3.0?

**Comment by bpoplauschi** [comment]
Of course it will. Right now, since we don't have any explicit Swift code, I'm not sure if we need to do anything in particular for this.

**Comment by Tinghui** [comment]
There is a problem when using SDWebImage with Swift3.

After updating to Swift 3.0, the Swift compiler translates the ObjC headers for UIImageView+WebCache.h into Swift, then it occurs a naming collision.

Please see this stackoverflow question for more details: [http://stackoverflow.com/questions/38949214/ambiguous-use-of-sd-setimagewithplaceholderimagecompleted-with-swift-3](http://stackoverflow.com/questions/38949214/ambiguous-use-of-sd-setimagewithplaceholderimagecompleted-with-swift-3)

**Comment by joridor** [comment]
Any idea when this gets fixed? Or anyone have an idea for a temp workaround.

**Comment by gujinku** [comment]
Won't we need to do any adjustment to Swift3.0?

**Comment by gujinku** [comment]
Can you please take a look?  Not sure if you are ware of this. @bpoplauschi

**Comment by mac8878** [comment]
images are not loading anymore after updating to swift 3 ? am i at right place ?

**Comment by ducmaxime** [comment]
I confirm, it's not working with Swift 3.0, SDWebImageCompletionBlock not recognized. :(

**Comment by joridor** [comment]
@billionbucks Had the same for my list with images, the first ones were loaded, after a while it stopped loading pictures.
Set the options to low priority (eg. options: [.continueInBackground, .lowPriority]) and it seemed to be fixed.
Don't think it had something todo with Swift 3, maybe it's the iOS 10 SDK, or a combo.

**Comment by Toolenaar** [comment]
having the same issues after updating my app to swift 3.0 images stopped loading. Joridor's solution does not work for me. The completion block is fired but when the image that I get back wont seem to load into the UIImageView

**Comment by gujinku** [comment]
The completion block is called but the image is nil.

**Comment by bpoplauschi** [comment]
@billionbucks @ducmaxime @joridor can you provide some image urls that don't work for you so we can test?

**Comment by bpoplauschi** [comment]
PS: I just created a demo Swift 3 project, added SDWebImage and indeed got into the 'ambiguous method' issue, but I easily passed that by adding the `options` param and then everything worked fine (including downloading and showing the image). I used this url: `https://nr-platform.s3.amazonaws.com/uploads/platform/published_extension/branding_icon/275/AmazonS3.png`

**Comment by fmello** [comment]
Hi, is it possible you post this sample project. I am also having the same difficulty. tks

**Comment by joridor** [comment]
@bpoplauschi My situation: I have a tableview filled with images. The first +- 50 pictures were working correctly. But if you kept scrolling, the images would stop loading.
In the cells, I call .sd_cancelCurrentImageLoad() in prepareForReuse.
I used sd_setImage(with:placeholderImage:options:completed) to load an image url when setting up the cells.

To make the list work again, I had to specify the option [.continueInBackground, .lowPriority] in the options. (think previous value was: SDWebImageOptions(rawValue:0))

**Comment by supreetuf** [comment]
Hi @bpoplauschi I had the same issue, images are not loading in swift 3. I had an existing project in swift 2.3 and converted it to swift 3. After that, this issue started. In my case, it for few ImageViews the images were not while for others they were. After much try and debugging what worked was, to remove the ImageView from the storyboard not showing image and add the new ImageView, connect it to view controller and do the code. That fixed it for me.

**Comment by henry0475** [comment]
Recently i used swift 3.0 and also have same problem.

**Comment by bpoplauschi** [comment]
@henry0475 which version of SDWebImage?

**Comment by henry0475** [comment]
@bpoplauschi  Hi, I'm using 4.0.0 version. I don't know how to resolve this problem.My code:`SDWebImageManager.shared().imageDownloader?.downloadImage(with: photoURL, options: SDWebImageDownloaderOptions.allowInvalidSSLCertificates, progress: { (min: Int, max: Int, nil) in
                    print("loading……")
                    }, completed: { (image: UIImage, data: Data, error: NSError, finished: Bool) in
                        if image != nil {
                            print("finished")
                        } else {
                            print("wrong")
                       }
                })`. Then Xcode has error,likes above.

**Comment by henry0475** [comment]
@bpoplauschi Thanks!! Using your suggestion code, error has been solved. But Xcode showed a new waring,  "Expression of type 'SDWebImageDownloadToken?' is unused" .   :(

**Comment by bpoplauschi** [comment]
Here's my sample project: https://github.com/rs/SDWebImage/files/515471/Swift3TestSDWebImage.zip.

If your images are available via http, you need to add the `App Transport Security Settings/Allow Arbitrary Loads=YES` into your Info.plist to allow this unsecure connections.

Also, you can try the 4.0.0 (right now, beta2 is available via cocoapods, even though it's not an official release yet).

**Comment by Antilopez** [comment]
Hi!
I'm using your library on version 4.0.0 beta 2 (its great btw). And i was experiencing issues with swift 3.0 as well.
Tried all your options and while in most cases the problem was solved, the case where the profile picture had a circular corner radius kept showing an empty image.
I tackled the problem by removing the ciruclar radius layer and the library was working again. Maybe it helps you find the problem (or maybe its just my case i dont know).

This was my problematic code:
self.profileImageView.layer.cornerRadius = self.profileImageView.frame.size.width / 2; 

I solved the problem by removing that line and adding another image on top with static png croped circular (horrible, i know, but deadlines are my priority right now).

Hope it helps someone!

**Comment by gujinku** [comment]
@bpoplauschi Awesome work! I got the 4.0.0 beta2 and we love it!  We cannot wait to integrate it into our production app in next release.  So we would be grateful if you can provide the rough release ETA of SDWebImage 4.0.0.

**Comment by bpoplauschi** [comment]
@gujinku thanks. About an ETA, in think it will take a few more days to properly test and wrap up the documentation.

**Comment by chrisl777** [comment]
I had issues with the compiler finding "sd_setImage" until I added an "import WebImage" at the top of my file. Just an FYI if some people are having some build errors in their Swift 3 project.

**Comment by thedp** [comment]
Any update on this issue?
