### ISSUE TITLE
can you help me ?

### ISSUE THREAD

**Issue by qiaoming1990321** [rs/SDWebImage#1632]
when i used SDWebImageDownloader download images ,My project appeared some information  and the image download failed
<img width="879" alt="2016-07-22 3 48 38" src="https://cloud.githubusercontent.com/assets/10348145/17050356/feb697ba-5024-11e6-8c3e-3d22bb53345b.png">

**Comment by qiaoming1990321** [comment]
what can i do?Looking forward to your reply, thank you

**Comment by bpoplauschi** [comment]
This is an issue with autolayout (constraints) and it's not related to our library. Closing.
