### ISSUE TITLE
Image orientation should always up

### ISSUE THREAD

**Issue by jhrasco** [rs/SDWebImage#1633]
I've notice in UIImage+MultiFormat.m that there is a code that checks the image orientation, line 39. In line 42, should it be 
`image = [UIImage imageWithCGImage:image.CGImage
                                        scale:image.scale
                                  orientation:UIImageOrientationUp];`
instead of
`image = [UIImage imageWithCGImage:image.CGImage
                                        scale:image.scale
                                  orientation:orientation];`?

**Comment by bpoplauschi** [comment]
At that point (before checking) we already have an image from `image = [[UIImage alloc] initWithData:data];`. We recreate it only if it has a different orientation.
