### ISSUE TITLE
When dragging the UITableView, GIF will disappear in the cell

### ISSUE THREAD

**Issue by wangweijia** [rs/SDWebImage#1634]
When dragging the UITableView, GIF will disappear in the cell.

I have no ability to repair it, I can only provide a demo of errors.

[https://github.com/wangweijia/SDWebImageBugDemo.git](https://github.com/wangweijia/SDWebImageBugDemo.git)

Hope to be able to provide a little help to solve this problem

(Please forgive my helpless and English is not my native language, please forgive mistakes in grammar)

**Comment by bpoplauschi** [comment]
In the 4.x branch, you can find our new GIF solution based on FLAnimatedImage. Please try with that and see if the issue still occurs.
