### ISSUE TITLE
Newbie question for your library

### ISSUE THREAD

**Issue by kwstasna** [rs/SDWebImage#1635]
Hello.
I'm new to iOS dev. and i use Parse.com as a backend. So i've got a collectionview and i print some images on each cell. To be more specific i have a standard image and the image of the user. 

My scrolling sucks because with the code bellow i load the users image and i make it as a background image on a button.

```

let avatarImage = userPointer[USER_AVATAR] as? PFFile
  avatarImage?.getDataInBackgroundWithBlock({ (data, error) -> Void in
       if error == nil {
           if let imageData = data {
           cell.avatarOutlet.setImage(UIImage(data: imageData), forState: .Normal)
   } } })
```

So this makes the issue with the bad scrolling cause each time it's loading the image and until it loads it stucks for a bit. So i have 2 questions

1) I can get the url of the image from Parse, is this enough to make it smoother and to cache it so it doesnt have to load it all the time i scroll ?

2) Do you support Background images for buttons like this in my code?
Thanks a lot for your time reading!!

P.S. It would be awesome to have some examples in swift!

**Comment by bpoplauschi** [comment]
Yeah, you should only load the image once, not every time you scroll. We do support background images for buttons, look at our `UIButton+WebCache` category.
