### ISSUE TITLE
sd_setImage does not transition download operation from prefetching (low priority)

### ISSUE THREAD

**Issue by geoffmacd** [rs/SDWebImage#1637]
In our implementation of our collection view, we used UICV's -willDisplayCell callback to trigger -prefetchURLs to fetch images below the visible bounds. I discovered looking through the code, there is no upgrade path from which, after sd_setImage is called, the download task remains as Low Priority as it was set through -prefetchURLs. 

What I expected to happen was the operation would transition to a regular (Default priority) download. This probably causes slower than normal -sd_setImage downloads than one would expect when under high load.

**Comment by bpoplauschi** [comment]
Ideally, it should. But it's a bit more difficult to do

**Comment by bpoplauschi** [comment]
Fixed in latest 4.x releases, see #1638 for details.
