### ISSUE TITLE
Cannot load image with some url

### ISSUE THREAD

**Issue by formeforyouok** [rs/SDWebImage#1639]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. 8.0
 SDWebImage Version      | e.g. 3.7.5
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 7.3
 Repro rate              | e.g. all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

I cannot load webImage With the url "http://www.ctyle.com/system/cdn/services/redirect/mybesti-dev/ca5f6c6276b24544a182890f09fbff20/3ac255eae33e64a82c6703fbdedd654e/cp_file" 
Can anyone help me?

**Comment by mythodeia** [comment]
can you test the url in the demo project?

**Comment by formeforyouok** [comment]
@mythodeia 
I have already test the url in the demo project,but it doesn't work. 
Attach my demo:
[SDWebImageTest.zip](https://github.com/rs/SDWebImage/files/387843/SDWebImageTest.zip)

**Comment by luohui8891** [comment]
Hey, guys, I also have a redirect URL issue caused can't download the image with the 3.8.1.
Also tried the [URL](http://cx500forum.com/forum/attachment.php?attachmentid=14656&d=1408526626) in the demo app and no luck.

Also I tried add the following method in SDWebImage and found it won't be invoked.
`- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task willPerformHTTPRedirection:(NSHTTPURLResponse *)response newRequest:(NSURLRequest *)request completionHandler:(void (^)(NSURLRequest *))completionHandler`

Any suggestion @mythodeia ?

**Comment by mythodeia** [comment]
similar issue... [here](https://github.com/rs/SDWebImage/issues/1601)
@bpoplauschi any ideas?

**Comment by luohui8891** [comment]
Hmm, strange, for my [URL](http://cx500forum.com/forum/attachment.php?attachmentid=14656&d=1408526626), I tried to download it via `[NSData dataWithContentsOfURL:]` and it didn't work. 
But when I pasted it in chrome it could be downloaded.

**Comment by bpoplauschi** [comment]
I have no idea, but you should look at the actual NSError

**Comment by andyden9** [comment]
I tracked one of the [url](http://cx500forum.com/forum/attachment.php?attachmentid=14656&d=1408526626) and it seems remote server responses a correct 301 redirection message all time (below). But Safari, SDWebImage (on iPhone Simulator) and FireFox will NOT parse it correctly. Chrome and Opera handled it well. Is there any known problem has anything to do with this issue?

HTTP/1.1 301 Moved Permanently
Date: Wed, 31 Aug 2016 06:02:54 GMT
Server: Apache
X-Powered-By: PHP/5.4.45-0+deb7u4
Vary: User-Agent
Pragma: 
Cache-control: max-age=31536000, private
Expires: Thu, 31 Aug 2017 06:02:54 GMT
Last-Modified: Wed, 20 Aug 2014 09:23:46 GMT
ETag: "14656"
Accept-Ranges: bytes
Content-disposition: inline; filename="028.JPG"
Content-transfer-encoding: binary
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
Content-Length: 1754588
Location: http://cx500forum.com/forum/attachments/general-discussion/14656-ciao-tutti-dallitalia-028.jpg
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: image/jpeg

**Comment by andyden9** [comment]
Found the problem the url I posted, Safari, SDWebImage (on iPhone Simulator) and FireFox can't handle 301 properly. When I rewrite the response 301 to 302, everything works!

**Comment by mythodeia** [comment]
@andyden9 can you try [this](https://github.com/rs/SDWebImage/pull/1657) ?

**Comment by andyden9** [comment]
Sadly it didn't... Maybe something wrong with the 301 response inside?
<img width="735" alt="2016-09-01 12 02 29" src="https://cloud.githubusercontent.com/assets/14224413/18155066/549b18b8-703c-11e6-865e-257ae954d1d5.png">

**Comment by andyden9** [comment]
I also tried to change 301 response to 302, charles shows that the image is correctly downloaded (while if I didn't change, the image won't gets downloaded), but still, got exactly the same error with test I didn't change 301 to 302, I post below the error, hope it helps.

SDWebImageManagerTests.m:81: error: -[SDWebImageManagerTests testTestThatItCanDownloadAnImageWithARedirection] : expected: not http://cx500forum.com/forum/attachment.php?attachmentid=14656&d=1408526626, got: http://cx500forum.com/forum/attachment.php?attachmentid=14656&d=1408526626

**Comment by bpoplauschi** [comment]
Should be fixed now after merging #1657.
