### ISSUE TITLE
How to cancel specific the image downloading

### ISSUE THREAD

**Issue by pkc456** [rs/SDWebImage#1643]
I am asynchronously downloading images in a table view, with a button to cancel the image download like in whatsapp. How can I cancel the image downloading.

**Comment by brettFseven** [comment]
On the UIImageView, call 

`[self sd_cancelCurrentImageLoad];`

**Comment by bpoplauschi** [comment]
I think you could call `[imageView sd_cancelImageLoadOperationWithKey:@"UIImageViewImageLoad"]`
