### ISSUE TITLE
received Signal 11 was raised. SIGSEGV

### ISSUE THREAD

**Issue by devtofu** [rs/SDWebImage#1644]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 9.1
 SDWebImage Version      | 3.8.1
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 7.2.1
 Repro rate              |  sometimes 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Sorry, can not reproduce this problem demo available to you, because this is the crash release version of the report, the following information is the stack:

![image](https://cloud.githubusercontent.com/assets/12134966/17315793/27d028f8-58a1-11e6-89b0-2d19985fc855.png)

**Comment by iblacksun** [comment]
same issue here.

**Comment by bpoplauschi** [comment]
Looks the same with #1623

**Comment by bpoplauschi** [comment]
Closing as a duplicate.

**Comment by devtofu** [comment]
I will try the new version and give you feedback，thanks . @bpoplauschi

**Comment by devtofu** [comment]
@bpoplauschi pods didn't update the version number?

**Comment by bpoplauschi** [comment]
I did not create a new version, it's still 3.8.1. I only made a commit attempt on master branch, but I don't think it fixes the issue.

**Comment by bpoplauschi** [comment]
Should be fixed by e7bd5ab.
