### ISSUE TITLE
Version 3.8.1 as framework? (enable bitcode)

### ISSUE THREAD

**Issue by usk78dk** [rs/SDWebImage#1646]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 8.0-9.x
 SDWebImage Version      | 3.8.1
 Integration Method      | manually
 Xcode Version           | Xcode 7.3.1

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

Trying to follow the guide of manually importing the version 3.8.1 of the framework:

_Add the SDWebImage project to your project
Download and unzip the last version of the framework from the download page
Right-click on the project navigator and select "Add Files to "Your Project":
In the dialog, select SDWebImage.framework:
Check the "Copy items into destination group's folder (if needed)" checkbox_

However, on the the downloadsite (https://github.com/rs/SDWebImage/releases) the latest download of a build framework is 3.6 (SDWebImage-3.6.framework.zip).
Is it possible to get a newer version of the framework to download? We are particularly looking at enabling bitcode for our project, so was hoping the newer version supported this.

**Comment by Nestordu** [comment]
+1

**Comment by AndreaVitale** [comment]
+1

**Comment by bpoplauschi** [comment]
Guys, I strongly recommend you don't download that version. To get the 3.8.1, you just need to follow the instructions https://github.com/rs/SDWebImage#installation. I recommend you use CocoaPods or Carthage, makes everything easier.

As for the archived frameworks, we stopped doing them from version 3.6 which is more than 1 year old. Forget about that.
