### ISSUE TITLE
I guess AutoPurgeCache no need to listen MemoryWarningNotification and remove all cache objects

### ISSUE THREAD

**Issue by persenlee** [rs/SDWebImage#1647]
Because The NSCache class incorporates various auto-removal policies。

**Comment by bpoplauschi** [comment]
Please look at https://github.com/rs/SDWebImage/pull/1141 and http://stackoverflow.com/questions/19546054/nscache-crashing-when-memory-limit-is-reached-only-on-ios-7/19549090#19549090
