### ISSUE TITLE
Could not build Objective-C module 'UIActivityIndicator_for_SDWebImage'

### ISSUE THREAD

**Issue by gmansata6290** [rs/SDWebImage#1648]
@rs @bpoplauschi  SDWebImage Team, 

We really like the library you'll have built and have used it in multiple places but all of a sudden we are starting to see errors while building our codebase. 
 
### Issue Description and Steps

We were trying to build the project and we are getting 2 errors, no matter what we try.  
* First error is mentioned in the title of this post
* The second one is "UIImageView+WebCache.h' file not found" and they both seem to be linked.

### We tried the following 
1. Cleaned the Derived data, De-integrated Cocoapods from the project, pod clean, project clean and rebuild 
2. We also tried all of the above steps after uninstalling and re-installing XCode
3. We tried all of the steps in Point 1 after removing the .cocoapods and doing a pod setup again
4. We also tried changing the Enable Modules ( Objective C ) in the build settings to No
5. We also looked at a similar issue [here](https://github.com/rs/SDWebImage/issues/427)
6. The Podfile does have the following at the beginning

`source 'https://github.com/CocoaPods/Specs.git'`
`platform :ios, '8.0'`
`use_frameworks!`

We spent all day trying these different options and it's frustrating that none of these solutions work

Any help in trying to resolve this would be greatly  appreciated as it is affecting our critical deadlines.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 8.0
 SDWebImage Version      | 3.8.1
 Integration Method      |  cocoapods 
 Xcode Version           | Xcode 7.3.1
 Repro rate              | 100%

**Comment by bpoplauschi** [comment]
Does this happen on more than 1 dev machine?
Also, could you repro this in a new demo project you start from scratch? It looks very odd to me

**Comment by RajeshKumar7** [comment]
-Bridging-Header.h:12:9: 'SDWebImage/UIImageView+WebCache.h' file not found

Same issue.
