### ISSUE TITLE
SDWebImage not caching

### ISSUE THREAD

**Issue by MaeseppTarvo** [rs/SDWebImage#1649]
### New Issue Checklist

* [ *] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [* ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [* ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 9.0
 SDWebImage Version      | 3.7.6
 Integration Method      |cocoapods
 Xcode Version           | Xcode 8 beta 5
 Repro rate              | 100%

### Issue Description and Steps

I have loaded images from Firebase storage. First the images were in first place but I got it sorted out. Now there seems to be a problem that it is loading every image again after up and down scrolling. I noticed that while scrolling up and down something is caching into memory on every scroll but the disk is zero What to do? I also see that it is taking mobile data on every scroll I do. This is the code I am using:

let productImageref = productsValue[indexPath.row]["Products"] as? String
        
        
        cell.snusProductImageView.image = nil
        FIRStorage.storage().reference().child("\(productImageref!).png").downloadURLWithCompletion({(url, error)in
            if error != nil{
                print(error)
            }else{
                
                dispatch_async(dispatch_get_main_queue(), {
                    
                    cell.snusProductImageView.sd_setImageWithURL(url)
                })
                
            }
            })

**Comment by sunbohong** [comment]
can you give us some urls from this function?

**Comment by bpoplauschi** [comment]
Can you share some URLs? Not sure I see your issue, it's most probably in your code not SDWebImage.

**Comment by MaeseppTarvo** [comment]
I can say that I think the problem is with umlauts e.g(ä. ü, ö) since other images seems to be caching. Can you check the code and tell me if I am doing it right?

if productsValue[indexPath.row]["productUrl"] != nil {
            cell.snusProductImageView!.sd_setImageWithURL(NSURL(string: productsValue[indexPath.row]["productUrl"] as! String)!)
        }
        else {
            let productImageref = productsValue[indexPath.row]["Products"] as! String
            
            let decomposedPath = productImageref.decomposedStringWithCanonicalMapping
            
            cell.snusProductImageView.image = nil
            
            
            FIRStorage.storage().reference().child("\(decomposedPath).png").downloadURLWithCompletion({(url, error)in
                
                FIRDatabase.database().reference().child("Snuses").child(decomposedPath).child("productUrl").setValue(url!.absoluteString)
                
                let resource = Resource(downloadURL: url!, cacheKey: decomposedPath)
                
                cell.snusProductImageView.sd_setImageWithURL(url)
                
            })

The url for example one item with umlaut is: https://firebasestorage.googleapis.com/v0/b/snuspedia.appspot.com/o/Go%CC%88teborgs%20Prima%20Fint%20Loose.png?alt=media&token=511fe6c4-19ad-4416-a877-ef399d1a5ed1

And without umlaut some other: https://firebasestorage.googleapis.com/v0/b/snuspedia.appspot.com/o/Catch%20Dry%20Eucalyptus%20White%20Mini.png?alt=media&token=2cab8682-d936-4d81-a325-a6402fa23863
