### ISSUE TITLE
Support setShowActivityIndicatorView for UIButtons

### ISSUE THREAD

**Issue by jlubeck** [rs/SDWebImage#1651]
### New Issue Checklist
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

setShowActivityIndicatorView works great on UIImageViews, but it looks like it's not implemented on the UIButton category.

Any chance of adding support for that?

**Comment by bpoplauschi** [comment]
Not for the near future. Feel free to add it.

**Comment by jlubeck** [comment]
Thanks for the response!

Is closing the issue the proper way to handle this? I'll try to add it myself, but in case I don't get around to it, maybe someone else can see it and do it if it's open.. don't you think?

**Comment by bpoplauschi** [comment]
I know, you're right. My issue is there are so many open issues and I can't seem to close them down. It's confusing for me and for other people as well.

**Comment by jlubeck** [comment]
Totally understand. I'm going to try to implement this when I get a chance... Thanks for re-opening

**Comment by kirpa** [comment]
@jlubeck I've added PR for this feature, not sure if you got notification about it

**Comment by jlubeck** [comment]
Oh nice @kirpa ! I wasn't notified about it. Weird. I'm going back to this project by the end of the week, so I'm going to try it and let you know!
Thanks!

**Comment by bpoplauschi** [comment]
Should be available in 4.0.0 version due to the `UIView+WebCache` category
