### ISSUE TITLE
Images on initial (non-scrolled) cells of table view not displayed until scrolling down and back again

### ISSUE THREAD

**Issue by thomstark** [rs/SDWebImage#1652]
I'm pulling avatars into the image on a uiTableView cell.

When the table first loads, the images are not visible on the cells that are immediately in the scope of the phone's dimensions. When you scroll down, the other images are already loaded (even if you scroll down immediately). Then when you scroll back, the images at the top of the table are now visible. If you never scroll down and back, the images at the top will never appear. 

Using xcode 7.3.1 with Swift 2.

**Comment by mythodeia** [comment]
can this be replicated in the demo project as well?

**Comment by thomstark** [comment]
What is the demo project?

**Comment by mythodeia** [comment]
when you download the library there is a demo project that you can test it with. check it out

**Comment by thomstark** [comment]
Ah. Gotchya. Will test and get back to you.

**Comment by thomstark** [comment]
I couldn't get that working but I found a duplicate of my issue here: https://github.com/rs/SDWebImage/issues/9

Changing: `cell.imageView!.sd_setImageWithURL(NSURL(string:` self.Avatars[indexPath.section][indexPath.row]))` 

To: `cell.imageView!.sd_setImageWithURL(NSURL(string:` self.Avatars[indexPath.section][indexPath.row]), placeholderImage: UIImage(named:"add-user"))` 

solved the problem.
