### ISSUE TITLE
kCFStreamErrorDomainSSL -9813

### ISSUE THREAD

**Issue by devineed** [rs/SDWebImage#1653]
Hi,
i tried load https image but i got:
**NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)**

I use NSAllowsArbitraryLoads.
The images can be loaded with firefox i tested.
Please help whats wrong.
Thank you

-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 9.3
 SDWebImage Version      | 3.8.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 7.3.1
 Repro rate              | all the time (100%)

**Comment by mythodeia** [comment]
i am loading https images just fine. check the demo project and see that it loads https amazon images without any issue. are you sure everything is setup correctly in your server side?
check [this](http://timekl.com/blog/2015/08/21/shipping-an-app-with-app-transport-security/) for more info on how to check your ssl
