### ISSUE TITLE
Compiled Framework for tvOS

### ISSUE THREAD

**Issue by FastSword** [rs/SDWebImage#1656]
### Issue Info

 Platform Name           tvos
 Platform Version        9.2
 SDWebImage Version     3.8
 Integration Method      manually
 Xcode Version         Xcode 7.3

### Issue Description

   Hello. I wanted to compile SDWebImage framework for tvOS but it does not generate like when compiling for iOS. I am generating the framework with for iOS: 

xcodebuild -project ./SDWebImage.xcodeproj -target SDWebImageFramework -configuration Release 

and for tvOS:

xcodebuild -project ./SDWebImage.xcodeproj -target "WebImage tvOS" -configuration Release

For iOS it is compiled fine and it generates the corresponding file structure.

--- SDWebImage.framework
------- Headers
------- SDWebImage
------- Versions
------- A
--------- Headers
--------- **SDWebImage (simple file)** -> this is actually what I need the most
------- Current

For tvOS it generates this:
         
--- WebImage.framework
------ _CodeSignature
------ Headers
------ Info.plist
------ Modules
------ WebImage (exec)

When compiling with -target SDWebImageFramework when adding it in my project on iOS it works fine but on tvOS it displays a linker error saying that its platform is set for iOS.

Do I need to let the -target in the xcodebuild command SDWebImageFramework and change some build settings in the project or should I let it "WebImage tvOS" ?
Or is this an issue ?

Some help ?

Thanks !

**Comment by bpoplauschi** [comment]
This issue is fixed on the 4.x branch, but that is still in progress. You can try it from there, but keep in mind it's not released yet.
