### ISSUE TITLE
diskImageDataBySearchingAllPathsForKey method is not public

### ISSUE THREAD

**Issue by zfha** [rs/SDWebImage#1658]
SDImageCache:
- (NSData *)diskImageDataBySearchingAllPathsForKey:(NSString *)key

why the method is not public? In the old version, we can use it!

**Comment by zfha** [comment]
I ever used NSURLProtocol then used SDImageCache to get image data.
but now ,there is not this API, i can only get the UIImage.
then, because UIImage has many formats.
I don't know how to convert UIImage to NSData.
jpg, jpeg, use                  imageData = UIImageJPEGRepresentation(image, 1.0);
pnd          use                  imageData = UIImagePNGRepresentation(image);
but what for webp?gif?

**Comment by bpoplauschi** [comment]
The method is not public because it shouldn't be used directly :)
With the latest versions of SDWebImage, you also get the NSData in the completion, along with the UIImage, so feel free to use that.

**Comment by Mina-R-Meshriky** [comment]
Dears, Relating To that Question, If I already have the image data (webp case) and want to use sdwebImage to show it.... is there is a way?

**Comment by bpoplauschi** [comment]
@Mina-R-Meshriky if you have the image already, just assign it to the imageView `imageView.image = image`. I don't think you need SDWebImage for that, what this lib does is download and cache

**Comment by Mina-R-Meshriky** [comment]
@bpoplauschi , yes but as I mentioned it is webP formate.. and iOS does not natively support that ... I am using SDWebImage in getting images from the internet as you said "download and cash", but I have only one use case where the image comes encoded within a JSON response, I can decode it easily but then it is not recognizable by imageView.image

**Comment by bpoplauschi** [comment]
Inside `SDWebImage`, we are supporting `webP` images by using `libwebp`, you should look into that. (PS: regarding what you said, sending images or any binary data into JSON is a bad idea, you should use a CDN like setup where you can access images directly via a url).
