### ISSUE TITLE
Cannot initiate SDWebImageManager with cache and downloader in Swift

### ISSUE THREAD

**Issue by Jeyhey** [rs/SDWebImage#1659]
In objective-c, I can instantiate SDWebImageManager with:
`SDWebImageManager * m = [[SDWebImageManager alloc] initWithCache:nil downloader: [SDWebImageDownloader sharedDownloader] ];`

However, in Swift there seems to be no instantiator taking the cache and the downloader. The following method leeds to an error:
 `SDWebImageManager(cache: nil, downloader: SDWebImageDownloader.sharedDownloader)`

**Comment by bpoplauschi** [comment]
I think the error is because cache cannot be nil
