### ISSUE TITLE
Can't fetch image from PHAsset local identifier in upgraded version

### ISSUE THREAD

**Issue by prashantkrishnan94** [rs/SDWebImage#1661]
```
[imageManager downloadImageWithURL:[NSURL URLWithString:downloadURL] options:0 targetLocalAssetSize:targetSize progress:nil completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) { 

}];
```
This function is removed from new SDWebImage , is their any other substitute method to do this ??

**Comment by mythodeia** [comment]
@prashantkrishnan94 i do not remember this at all. SDWebImage does not support PHAsset.
Unless you are talking about [this](https://github.com/rs/SDWebImage/pull/906)
