### ISSUE TITLE
retain cycle in SDWebImageDownloader.m

### ISSUE THREAD

**Issue by fuer4869** [rs/SDWebImage#1663]
SDWebImageDownloader.m :154
capturing 'self' strongly in this block is likely to lead to a retain cycle
                                                        inSession:self.session

**Comment by wcxdell** [comment]
I found in SDWebImageDownloaderOperation.m :103

            __weak __typeof__ (self) wself = self;
            UIApplication * app = [UIApplicationClass performSelector:@selector(sharedApplication)];
            self.backgroundTaskId = [app beginBackgroundTaskWithExpirationHandler:^{
                __strong __typeof (wself) sself = wself;
                 ..........
}

Will this lead to retain cycle?
On other place like this,the block is not hoding by self.

**Comment by bpoplauschi** [comment]
This is fixed on the 4.x branch.
