### ISSUE TITLE
CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

### ISSUE THREAD

**Issue by nilotic** [rs/SDWebImage#1668]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 9.0
 SDWebImage Version      | 3.8.2
 Integration Method      | cocoapods
 Xcode Version           |  Xcode 7.3.1
 Repro rate              | all the time (100%) 

In SDWebImageDecoder.m,  line: 86
error message :  CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

If color profile is NikonD800-Generic, always occurred 
-Sample image-
![profile-nikond800-generic](https://cloud.githubusercontent.com/assets/4756783/18430039/b92311f4-7911-11e6-86e4-211a4a8d07db.jpg)

**Comment by mythodeia** [comment]
the issue appears to be with the Nikon colour profile. I removed the NikonD800-Generic colour profile and the image shows correctly now.

**Comment by nilotic** [comment]
@mythodeia  Thank you for your reply.
Unfortunately, I can't check and change all photos color profile in server. Because those photos were uploaded by user. 
I think,  Adding exception handler is better solution than changing color profile
Like this
```
        // kCGImageAlphaNone is not supported in CGBitmapContextCreate.
        // Since the original image here has no alpha info, use kCGImageAlphaNoneSkipLast
        // to create bitmap graphics contexts without alpha info.
        CGContextRef context = CGBitmapContextCreate(NULL,
                                                     width,
                                                     height,
                                                     bitsPerComponent,
                                                     bytesPerRow,
                                                     colorspaceRef,
                                                     kCGBitmapByteOrderDefault|kCGImageAlphaNoneSkipLast);

        // Exception handling
        if (context == NULL) {
            return image;
        }
```

**Comment by bpoplauschi** [comment]
@nilotic does this code you posted work?
