### ISSUE TITLE
Cashing wrong image

### ISSUE THREAD

**Issue by Nikiraf** [rs/SDWebImage#1669]
Hi, I have problem with loading image. Here is my code that sometimes shows wrong image

`let url = NSURL(string: friend.profileImage as String)
            let block: SDWebImageCompletionBlock! = {(image: UIImage!, error: NSError!, cacheType: SDImageCacheType, imageURL: NSURL!) -> Void in }
            self.friendImage.sd_setImageWithURL(url, completed: block)`

When I try to load image without SDWebImage it show valid image. Code example:

`let url = NSURL(string: friend.profileImage)
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {
                let data = NSData(contentsOfURL: url!) //make sure your image in this url does exist, otherwise unwrap in a if let check
                dispatch_async(dispatch_get_main_queue(), {
                    self.friendImage.image = UIImage(data: data!)
                });
            }`

Reusable cell is not a problem. All cells can fit on the screen

Platform Name	ios / 
Platform Version	9.3.5
SDWebImage Version	3.8.2
Integration Method	cocoapods
Xcode Version	Xcode 7.3.1
Repro rate	sometimes 10%
Repro with our demo prj	No

**Comment by bpoplauschi** [comment]
Please make the issue conform to the issue template: https://github.com/rs/SDWebImage/blob/master/.github/ISSUE_TEMPLATE.md
