### ISSUE TITLE
How do i know when all the downloaders finished? 

### ISSUE THREAD

**Issue by vinguan** [rs/SDWebImage#1670]
I know there's a IsRunning on sharedManager, But there's a handler or callback fired when all the downloads ended?

**Comment by bpoplauschi** [comment]
@vinguan there is no other way at this point.

**Comment by vinguan** [comment]
There is another way that i can hide an ActivityIndicator or another loading when all downloads finished? I am using a reference for all downloads that had started and checking a count for a NSArray.
