### ISSUE TITLE
The option "progressiveDownload" not work

### ISSUE THREAD

**Issue by superk589** [rs/SDWebImage#1671]
In xcode 8 and Swift3, using SDWebImage 3.8.2
When using sd_setImage and set options "progressiveDownload", the image is not display progressively as before.

**Comment by bpoplauschi** [comment]
Can you add some extra details? See the [ISSUE TEMPLATE](https://github.com/rs/SDWebImage/blob/master/.github/ISSUE_TEMPLATE.md). Does it happen with our demo project? Any image or just a particular one? ...

**Comment by superk589** [comment]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.2
 SDWebImage Version      | 3.8.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.2
 Repro rate              | all the time (100%) 
 Repro with our demo prj | no
 Demo project link       | https://github.com/superk589/SDWebImageDemo_ProgressiveDownloadIssue

### Issue Description and Steps
When using sd_setImage and set options "progressiveDownload", the image is not displayed progressively(use a large web image here and make sure it's not cached before), but shows suddenly after download finished. 
Using simulator of iOS 9.x or 8.x in the same environment, "progressiveDownload" works correctly.

**Comment by bpoplauschi** [comment]
Thanks for the info @superk589, will look into this

**Comment by mythodeia** [comment]
@superk589 can you try with the latest version and let me know?

**Comment by superk589** [comment]
@mythodeia 
I tried in iOS 10.3, the bug disappeared. Everything works fine just as in iOS 9.x.

**Comment by bpoplauschi** [comment]
great to hear that. closing
