### ISSUE TITLE
setObjectForKey: object cannot be nil

### ISSUE THREAD

**Issue by pengkun** [rs/SDWebImage#1672]
*** setObjectForKey: object cannot be nil (key: file:///private/var/mobile/Containers/Data/Application/AC589DB7-F921-4A59-8C71-3F88DECC1B73/Library/Caches/default/com.hackemist.SDWebImageCache.default/250dbd82f8920a64b6b170e04e791a6d.jpg)

System version :iOS  10.0.1

**Comment by bpoplauschi** [comment]
@pengkun please follow the issue template and provide us with all the info required there: https://github.com/rs/SDWebImage/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by bpoplauschi** [comment]
Should be fixed in the latest 4.x.
