### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Gantaios** [rs/SDWebImage#1675]
after installation from cocoapods unable to 
#import <SDWebImage/UIImageView+WebCache.h>
 file not found

**Comment by bpoplauschi** [comment]
@Gantaios please provide all the info required by https://github.com/rs/SDWebImage/blob/master/.github/ISSUE_TEMPLATE.md.

**Comment by bpoplauschi** [comment]
Closing. Feel free to reopen with the required info.
