### ISSUE TITLE
sd_setImageWithURL - no Image

### ISSUE THREAD

**Issue by armandsavotins** [rs/SDWebImage#1680]
### Issue Info
 Platform Name           | ios
 Platform Version        | 10.0
 SDWebImage Version      | e.g. 3.8.1
 Integration Method      | manually
 Xcode Version           | e.g. Xcode 8.0
 Repro rate              | all the time (100%)

### Issue Description and Steps

Facing problem to set image from URL.  Everything works fine on older iOS versions (just iOS10).

// SDWebImage 3.8.2 - not working
    //[cell.cover sd_setImageWithURL:[NSURL URLWithString:imageURLString] placeholderImage:[UIImage imageNamed:@"BookDefault"]];

// Test - works fine
    dispatch_async(dispatch_get_global_queue( DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^(void){
        //Background Thread
        [cell.cover setImage:[UIImage imageWithCIImage:[CIImage imageWithContentsOfURL:[NSURL URLWithString:imageURLString]]]];
        dispatch_async(dispatch_get_main_queue(), ^(void){
            //Run UI Updates
            [cell.cover setNeedsDisplay];
        });
    });

**Comment by mythodeia** [comment]
can you replicate in the demo project?

**Comment by armandsavotins** [comment]
Not tested with Demo project. Just tested with new clean project and random image url from web. Same results, everything works fine in iOS8 and iOS9, in iOS10 image not set, at least does not shows up in imageView.
p.s. getting same results with UIKit+AFNetworking setImageWithURL

**Comment by armandsavotins** [comment]
Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure.

**Comment by mythodeia** [comment]
👍
