### ISSUE TITLE
XCode8 run app With CocoaPod install SDWebImage and Webp, But define  SD_WEBP unavailable

### ISSUE THREAD

**Issue by ansonlo** [rs/SDWebImage#1682]
Xcode 8 

Pod file 
{
pod 'SDWebImage', '3.8.2'

pod 'SDWebImage/WebP'
}

But when i run app,  the code   #ifdef SD_WEBP unavailable ,  But in Xcode7 it's ok. I'm so confused.

**Comment by bpoplauschi** [comment]
@ansonlo I just tried creating a demo Swift 3.0 project with Xcode 8, using 3.8.2 and WebP. Everything worked fine.

Please note that there might be issues with HTTP urls, but those are OS specific and are not related to SDWebImage.
