### ISSUE TITLE
[SDImageCache cleanDiskWithCompletionBlock:] crash

### ISSUE THREAD

**Issue by pclion** [rs/SDWebImage#1683]
0   CoreFoundation                  0x00000001838781c0 ___exceptionPreprocess :124 (in CoreFoundation)
1   libobjc.A.dylib                 0x00000001822b055c _objc_exception_throw :56 (in libobjc.A.dylib)
2   CoreFoundation                  0x000000018375979c -[__NSDictionaryM setObject:forKey:] :928 (in CoreFoundation)
3   Alibaba                         0x0000000100413a38 __45-[SDImageCache cleanDiskWithCompletionBlock:]_block_invoke SDImageCache.m:670 (in Alibaba)
4   libdispatch.dylib               0x0000000182701200 __dispatch_call_block_and_release :24 (in libdispatch.dylib)
5   libdispatch.dylib               0x00000001827011c0 __dispatch_client_callout :16 (in libdispatch.dylib)
6   libdispatch.dylib               0x000000018270f444 __dispatch_queue_serial_drain :928 (in libdispatch.dylib)
7   libdispatch.dylib               0x00000001827049a8 __dispatch_queue_invoke :652 (in libdispatch.dylib)
8   libdispatch.dylib               0x000000018270f940 __dispatch_queue_override_invoke :360 (in libdispatch.dylib)
9   libdispatch.dylib               0x000000018271138c __dispatch_root_queue_drain :572 (in libdispatch.dylib)
10  libdispatch.dylib               0x00000001827110ec __dispatch_worker_thread3 :124 (in libdispatch.dylib)
11  libsystem_pthread.dylib         0x00000001829092c8 __pthread_wqthread :1288 (in libsystem_pthread.dylib)
12  libsystem_pthread.dylib         0x0000000182908db4 _start_wqthread :4 (in libsystem_pthread.dylib)

NSDictionary *resourceValues = [fileURL resourceValuesForKeys:resourceKeys error:NULL];
It may return nil object when call resourceValuesForKeys:resourceKeys:error: method, so cause set nil object error.Please fix this issue.

**Comment by bpoplauschi** [comment]
Same crash as #1619. #1676 and 7940577 should have fixed this.
