### ISSUE TITLE
UIImageView & MKAnnotationView import in swift bridging header causes redefinition errors

### ISSUE THREAD

**Issue by GeRyCh91** [rs/SDWebImage#1686]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 9.3
 SDWebImage Version      | 3.7.6
 Integration Method      |  manually
 Xcode Version           | Xcode 7.3
 Repro rate              | all the time (100%) / sometimes x% / only once
 Repro with our demo prj | Unable to reproduce. Your demo in Objective - C

### Issue Description and Steps

Hey!
I'm using your incredible library in one of my apps that's written in Swift. I created bridging header file, where I added this:

```
#import <SDWebImage/UIImageView+WebCache.h>
#import <SDWebImage/MKAnnotationView+WebCache.h>

```
As a result many "redefinition of" errors received. 
I need both categories, for UIImageView & MKAnnotationView in my project. Where the right place to import these categories so I can use them both?
Thanks a lot!

**Comment by diejmon** [comment]
Just use `import SDWebImage` in `.swift` files.

**Comment by GeRyCh91** [comment]
Thanks. I used CocoaPods to achieve this.
