### ISSUE TITLE
images not show on load view

### ISSUE THREAD

**Issue by psnt143** [rs/SDWebImage#1688]
### New Issue Checklist

* [ ] images not show on when view did load but in tableview when i scroll it hidden row images are show and when i scroll again all images are show,but the problem is that when  call viewdidload then images not showed in view. ]

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 10.0
 SDWebImage Version      | not sure
 Integration Method      |  manually
 Xcode Version           | e.g. Xcode 8.0
 Repro rate              | e.g. all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps
For e.g. i used this method
NSURL* url1 = [NSURL URLWithString:[NSString stringWithFormat:@"%@",[[ArrObj objectAtIndex:indexPath.row]valueForKey:@"img"]]];
    [cell.Feedimg sd_setImageWithURL:url1
                       placeholderImage:nil options:indexPath.row == 0 ? SDWebImageRefreshCached : 0];

**Comment by mythodeia** [comment]
can this be replicated in the demo project?

**Comment by psnt143** [comment]
Your Sincerely,
*Prashant Patel*
iOS Developer
+91 97129 91261

**Comment by bpoplauschi** [comment]
@psnt143 we cannot understand what you are saying.

**Comment by psnt143** [comment]
hello,
         when i run the app viewdidload are call and view are open but
images not load,but when i scroll all images load and show.

Your Sincerely,
*Prashant Patel*
iOS Developer
+91 97129 91261

**Comment by psnt143** [comment]
i attach my source code in above mail please check them.

Your Sincerely,
*Prashant Patel*
iOS Developer
+91 97129 91261

**Comment by tylerjames** [comment]
I think I'm having a similar problem, but I'm not sure SDWebImage is the culprit.

Have a custom UITableViewCell subclass. In it I have a UIImageView which is embedded in a UIView that is used as a coloured background to the image. 

When I attempt to configure the cell, either in `cellForRowAtIndexPath:` or in `willDisplayCell:` the initial size of the subviews is shown as 1000x1000. I try to set an image into the image view using `[self.iconView sd_setImageWithURL:iconURL placeholderImage:placeholder];` I also set a background colour of the enclosing UIView.

The result is that the image does not get set and even the background colour of the UIView does not get set until the cells are dequeued a second time, either by scrolling or switching to a different view. 

It seems like the cells are not ready to be configured. I bet it's a quirk of iOS 10, but man is it annoying.

**Comment by codalamanp** [comment]
Just call this method [self.iconView layoutIfNeeded] before make it circle.

**Comment by psnt143** [comment]
thanks for your support.it's run well.

Your Sincerely,
*Prashant Patel*
iOS Developer
+91 97129 91261

**Comment by tylerjames** [comment]
If you're going to add code that accesses the layers of the such as adding a corner radius you can add that code into the cell's `-layoutSubviews` method and everything should work. 

It seems that accessing the layer, or at least settings `masksToBound=YES` from inside `willDisplayCell:` or `cellForRowAtIndexPath:` will cause the image view to not load properly on the first pass. Putting it in `-layoutSubviews` works.

**Comment by JPROFFICIAL** [comment]
I spent three days of development trying to figure out why my image was not setting after it loaded using the SDCompletionBlock. After tried and true testing - Calling a `setNeedsLayout` - `layoutIfNeeded` - even manually updating the `ReusableHeaderView` for my `collectionView` using a layout context; @tylerjames answer did the trick. Unsure if this is an xCode bug or if this is by design, but changing my sublayer work (`cornerRadius` - `contentMode`) from my `cellForRow` to `layoutSubviews` did the trick. Thanks for a helpful thread guys. PS. SDWebImg is a rockstar.
