### ISSUE TITLE
Image cache deleted every 7 days

### ISSUE THREAD

**Issue by Jeyhey** [rs/SDWebImage#1689]
### Issue Info
 Platform Name: iOS 10
 SDWebImage Version 3.8.1     
 Integration Method: cocoapods
 Xcode Version: Xcode 8

### Issue Description and Steps

My app fetches images from a http-server which are then deleted from the server. I use SdWebImage to fetch and persistently store the images. Now I noticed that the cache of SdWbImage is deleted every 7 days. I tried to change the location of the cache:

`let documents = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
        let fileURL = documents.appendingPathComponent("images")
        MediaService.sharedInstance.sdImageCache = SDImageCache(namespace: "com.myapp.images", diskCacheDirectory: fileURL.path)`

But the cache is still deleted every 7 days.

My question is: Can I do something about it? And: Is SdWebImage meant to persistently store images, or should I handle the storage separately myself?

**Comment by bpoplauschi** [comment]
I think you should be able to avoid the deletion by working with `maxCacheAge` config from `SDImageCache`. It's default to 1 week, but you can change it.

**Comment by Jeyhey** [comment]
Thanks a lot. Did miss that configuration.
