### ISSUE TITLE
sd_setImage and webp fails with error: Downloaded image has 0 pixels (Swift 3.0)

### ISSUE THREAD

**Issue by nateboxer** [rs/SDWebImage#1691]
### New Issue Checklist
- [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | ios |
| Platform Version | 9.0 |
| SDWebImage Version | 3.8.2 |
| Integration Method | carthage |
| Xcode Version | Xcode 8.0 |
| Repro rate | 100% |
| Repro with our demo prj | Happens with new project and only SDWebImage |
### Issue Description and Steps

After upgrading to Xcode 8 and Swift 3, SDWebImage fails to load all webp images using sd_setImage(). All images are hosted at Amazon's S3 and are loadable via URL (load with Chrome to see them render in browser). EG:

https://stela-playground.s3.amazonaws.com/assets/series/4e00b1ac-c071-44e4-b146-5da5741ccf4e/large_square/1242x1242_3__1__copy_vol2_2f2ec7ff857455501649ffa4c08fd486.webp

After struggling with my app, I decided to create a new project, add only the SDWebImage framework (via Carthage: github "rs/SDWebImage") and write only the code needed to reproduce the problem:

``` swift
    override func viewDidLoad() {
        super.viewDidLoad()

        let imageView = UIImageView();
        view.addSubview(imageView)
        imageView.frame = CGRect(x: 0, y: 0, width: 200, height: 200)

        let url = URL(string: "https://stela-playground.s3.amazonaws.com/assets/series/e9355358-092c-4bc0-986d-7a25650eb337/large_rectangle/621x441_result_fde6e8ba700a71993eb50f9de481a123.webp")
        imageView.sd_setImage(with: url, placeholderImage: nil, options: [SDWebImageOptions.continueInBackground, SDWebImageOptions.lowPriority, SDWebImageOptions.refreshCached, SDWebImageOptions.handleCookies, SDWebImageOptions.retryFailed]) { (image, error, cacheType, url) in
            if error != nil {
                print("Failed: \(error)")
            } else {
                print("Success")
            }
        }
    }
```

I've tried all the information I've found pertaining to this issue online (StackOverflow, this repo, etc.) to no avail. Any help you can provide would be greatly appreciated as my app uses almost exclusively webp images. I'll need to find an alternate framework if I can't resolve this. Thanks!

**Comment by bpoplauschi** [comment]
Hmm. Strange. I just created a demo project with Xcode 8, Swift 3 and everything works fine, even with the image URLs you provided. Here's the demo project.
[Swift3TestSDWebImage.zip](https://github.com/rs/SDWebImage/files/515471/Swift3TestSDWebImage.zip)

One thing to check would be the libwebp version, as libwebp 0.5.1 was released this September. Make sure you use that.

**Comment by nateboxer** [comment]
I'm a little confused. I've never had to add libwebp directly to my project before. Is it a separate framework? I see it in your project added via pods, but the instructions for adding SDWebImage via Carthage simply say to add the github "rs/SDWebImage" directive and that's all. I must be missing something. Thanks!

**Comment by bpoplauschi** [comment]
It's a separate framework, a dependency of SDWebImage. You need version 4.0.0 for this. 4.0.0-beta2 is available and an official release is very close.

**Comment by nateboxer** [comment]
I updated my main app and my simple test project to use the latest 4.0.x release of SDWebImage and I still get the zero pixels error on all webp images.

**Comment by bpoplauschi** [comment]
Can you share with us the simple test project where your issue appears?

**Comment by nateboxer** [comment]
I ran your sample project and the images did load. I ran the carthage command with several options and nothing helped. I still can't load webp images. Here is my simple project:

[ZeroPixels.zip](https://github.com/rs/SDWebImage/files/529970/ZeroPixels.zip)

thanks!

**Comment by nateboxer** [comment]
So others are having this issue. It seems like it should be reopened.

**Comment by nateboxer** [comment]
I finally got it to work correctly. I was going down the path of building SDWebImage manually and ran across a link to an older version of the framework (WebImage instead off SDWebImage). I corrected all references including the list of frameworks under Build Phases/Link Binary With Libraries and especially the carthage copy-frameworks script. All webp images are now downloading correctly.

**Comment by bpoplauschi** [comment]
This seems fixed - no idea why it's still open

**Comment by Cao-Yu** [comment]
go to sd_imageWithData method, try to confirm "image/webp" branch is executed right. If not, clean xcode DerivedData.

**Comment by borzh** [comment]
Follow this steps:

- Update pod SDWebImage to version 5
- remove pod SDWebImage+Web
- use instead pod SDWebImageWebPCoder

This will fix everything wrong with WebP
