### ISSUE TITLE
Same URLs didn't cancel download

### ISSUE THREAD

**Issue by JiaoYingBo** [rs/SDWebImage#1693]
`[imgView sd_setImageWithURL:url1];`
When the `url1` is downloading , I replaced it with `url2`.
`[imgView sd_setImageWithURL:url2];`
Then `url2` started to download , but `url1` didn't be canceled.

I found that `weakSubOperationToken` which in `cancelBlock` is nil when the block invoked.
It works when I replace `weakSubOperationToken` with `subOperationToken` in `[self.imageDownloader cancel:weakSubOperationToken]`.

    __weak typeof(subOperationToken)weakSubOperationToken = subOperationToken;
    operation.cancelBlock = ^{
        [self.imageDownloader cancel:weakSubOperationToken];
        __strong __typeof(weakOperation) strongOperation = weakOperation;
        [self safelyRemoveOperationFromRunning:strongOperation];
    };
SDWebImageManager.m line 230     
SDWebImage  4.0.0 Beta 2

**Comment by bpoplauschi** [comment]
Thanks @JiaoYingBo
