### ISSUE TITLE
using sd_setImageWithURL cannot show Image from url 

### ISSUE THREAD

**Issue by NancyZY** [rs/SDWebImage#1698]
### New Issue Checklist

* [ Yes] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ Yes] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ Yes] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues/1680) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.0.2
 SDWebImage Version      |  3.8.2
 Integration Method      | cocoapods
 Xcode Version           | 8.0 
 Repro rate              |   all the time (100%)

### Issue Description and Steps
Facing problem to set image from URL. I write the code like this:

 ```
NSLog(@"图片的路径是%@", newData.avatar_mid);
        [_newShowView.HeadView sd_setImageWithURL:[NSURL URLWithString:newData.avatar_mid] placeholderImage:[UIImage imageNamed:@"Img_default"]
                                          options:0 completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                                              NSLog(@"========error=%@", error);
                                          }];
```
and  the console print the infomation:
图片的路径是https://apic.douyucdn.cn/upload/avatar/010/58/54/12_avatar_middle.jpg
========error=(null)

I spent a lot of time on it, but still not work. Hope you can help me .  Thanks!

**Comment by bpoplauschi** [comment]
I just tried with the demo project and the image url you supplied and it works fine. To debug properly, you can also print the image in the completion block, but it should be non-nil. Also check the data type of `newData.avatar_mid` to make sure it's a `NSString` and not something else.

**Comment by NancyZY** [comment]
I am sorry for reply so late. I try to print the image and the data type of newData.avatar_mid, it shows not-nil and NSString, respectively.
