### ISSUE TITLE
NSImage+WebCache.h not add status when update from 3.8.1 to 4.0.0-beta2

### ISSUE THREAD

**Issue by OliverYao** [rs/SDWebImage#1699]
Our project use SDWebImage with cocoa pods.When we update version from 3.8.1 to 4.0.0-beta2, the file which name is "NSImage+WebCache.h" is not add status in git. How to resolve it?

**Comment by bpoplauschi** [comment]
Do a `git add`. This is not related to our project, it's a git usage question.
