### ISSUE TITLE
Race Condition occurs in SDWebImagePrefetcher.m at startPrefetchingAtIndex 

### ISSUE THREAD

**Issue by freshnitesh** [rs/SDWebImage#1701]
### New Issue Checklist
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
- [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
### Issue Info

| Info | Value |
| --- | --- |
| Platform Name | iOS |
| Platform Version | 10.1.0 |
| SDWebImage Version | 3.8.1 |
| Integration Method | cocoapods |
| Xcode Version | Xcode 8.0 |
| Repro rate | sometimes |
| Repro with our demo prj | no |

 Calling SDWebImagePrefetcher.shared().prefetchURLs(prefetchUrls) with this code produces the race condition/crash:

let dispatchQueue = DispatchQueue.global(qos: DispatchQoS.QoSClass.default)
        // test the dispatch async bug with race conditions and array index out of bounds
        for i in (0 ... 40).reversed() {
            let prefetchUrls = [URL](repeating: URL%28string:)!, count: i)
            dispatchQueue.async {
                SDWebImagePrefetcher.shared().prefetchURLs(prefetchUrls)
            }
        }
### Issue Description and Steps

When calling SDWebImagePrefetcher.shared().prefetchURLs(prefetchUrls) from a background queue repeatedly, we can see a race condition occur in func startPrefetchingAtIndex. Though the func checks that the index is valid on one line, after that point the array could have been modified, so in the [self.manager downloadImageWithURL:self.prefetchURLs[index]... line, an index out of bounds error can occur.

Crash:
fatal error: Array index out of range

Stack Trace:
Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x1086dddc0 _TTSf4s_s_d_d___TFs18_fatalErrorMessageFTVs12StaticStringS_S_Su_T_ + 40
1  libswiftCore.dylib             0x108732778 _TPA__TFFCs40_SwiftNativeNSArrayWithContiguousStorage13objectAtIndexFSiPs9AnyObject_U_FGSRPS0___PS0__ + 134
2  libswiftCore.dylib             0x10873256c _TPA__TTRXFo_dGSRPs9AnyObject___dSizoPs9ErrorType__XFo_dGSRPS____iSizoPS0___ + 84
3  libswiftCore.dylib             0x1087346e0 _TPA__TTRXFo_dGSRPs9AnyObject___oPS__zoPs9ErrorType__XFo_dGSRPS____iPS__zoPS0___ + 12
4  libswiftCore.dylib             0x1086b4454 _TTSg5Ps9AnyObject____TFCs21_SwiftDeferredNSArray25withUnsafeBufferOfObjectsurfzFzGSRPs9AnyObject__xx + 668
5  libswiftCore.dylib             0x1086b3780 _TToFCs40_SwiftNativeNSArrayWithContiguousStorage13objectAtIndexfSiPs9AnyObject_ + 304
6  SDWebImage                     0x1012dd620 -[SDWebImagePrefetcher startPrefetchingAtIndex:](SDWebImagePrefetcher.m:60)
7  libdispatch.dylib              0x184a6d200 _dispatch_call_block_and_release + 24
8  libdispatch.dylib              0x184a6d1c0 _dispatch_client_callout + 16
9  libdispatch.dylib              0x184a71d6c _dispatch_main_queue_callback_4CF + 1000
10 CoreFoundation                 0x185b8ff2c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
11 CoreFoundation                 0x185b8db18 __CFRunLoopRun + 1660
12 CoreFoundation                 0x185abc048 CFRunLoopRunSpecific + 444
13 GraphicsServices               0x187542198 GSEventRunModal + 180
14 UIKit                          0x18baa72fc -[UIApplication _run] + 684
15 UIKit                          0x18baa2034 UIApplicationMain + 208
16 LinkedIn                       0x1000c9628 main (AppDelegate.swift:27)
17 libdispatch.dylib              0x184aa05b8 (Missing)

Solution:
In the following function: 
- (void)prefetchURLs:(nullable NSArray<NSURL *> *)urls
           progress:(nullable SDWebImagePrefetcherProgressBlock)progressBlock
          completed:(nullable SDWebImagePrefetcherCompletionBlock)completionBlock {

simply wrap the entire function body in 
dispatch_async(self.prefetcherQueue, ^{
  // code
});

**Comment by bpoplauschi** [comment]
This should be fixed in version 4.0.0.
