### ISSUE TITLE
carthage build for webp 

### ISSUE THREAD

**Issue by Zengzhihui** [rs/SDWebImage#1703]
https://github.com/Zengzhihui/SDWebImageWebp

**Comment by nateboxer** [comment]
I am having this problem too.

**Comment by skyline75489** [comment]
@nateboxer What's the problem exactly?

**Comment by nateboxer** [comment]
When I install SDWebImage via Carthage, webp images fail to download with the "image has 0 pixels" error. I opened an issue about this: https://github.com/rs/SDWebImage/issues/1691 - but it was closed immediately as fixed in v4.0.0. I have tried v4.0.0 but the problem persists.

**Comment by nateboxer** [comment]
As I noted in #1691, I fixed this problem by removing all references to the old pre 4.0 version of SDWebImage. It was confusing as the the framework name I was using was slightly different and I had both in my project settings.

**Comment by bpoplauschi** [comment]
Closing based on the last comment.
