### ISSUE TITLE
[Release 3.8.2] Crash in SDWebImageDownloaderOperation.m:431

### ISSUE THREAD

**Issue by IvanChan** [rs/SDWebImage#1704]
Thread 17 Crashed:
0   libobjc.A.dylib                     0x216c068a objc_retain + 10
1   MyApp                              0x000d271b -[SDWebImageDownloaderOperation URLSession:task:didCompleteWithError:](SDWebImageDownloaderOperation.m:431)
2   MyApp                              0x000d72a7 -[SDWebImageDownloader URLSession:task:didCompleteWithError:](SDWebImageDownloader.m:307)
3   CFNetwork                           0x224d66fd **51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke170 + 77
4   Foundation                          0x226fe84d __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK** + 9
5   Foundation                          0x2265f87f -[NSBlockOperation main] + 147
6   Foundation                          0x22651f8f -[__NSOperationInternal _start:] + 775
7   Foundation                          0x22700b0d __NSOQSchedule_f + 193
8   libdispatch.dylib                   0x21a85e7f _dispatch_queue_drain + 1763
9   libdispatch.dylib                   0x21a7ee17 _dispatch_queue_invoke + 283
10  libdispatch.dylib                   0x21a8720d _dispatch_root_queue_drain + 401
11  libdispatch.dylib                   0x21a8707b _dispatch_worker_thread3 + 95
12  libsystem_pthread.dylib             0x21c1ae0d _pthread_wqthread + 1025
13  libsystem_pthread.dylib             0x21c1a9fc start_wqthread + 8

**Comment by skyline75489** [comment]
Can you provide an example that reproduces this crash?

**Comment by IvanChan** [comment]
@skyline75489 that crash in my app, appstore version from other user, so ...

**Comment by bpoplauschi** [comment]
Should be fixed in version 4.0.0.

**Comment by SongDaBei** [comment]
Also meet in release 4.0.0.
