### ISSUE TITLE
How to enable webp using cocoapods?

### ISSUE THREAD

**Issue by IvanChan** [rs/SDWebImage#1705]
How to enable webp using cocoapods?

there is a marco define webp in SDWebImage & pod miss that

**Comment by xiaoqi1503928** [comment]
[https://github.com/rs/SDWebImage#subspecs](https://github.com/rs/SDWebImage#subspecs)

**Comment by IvanChan** [comment]
@xiaoqi1503928 could build, but decode webp fail? image always nil
