### ISSUE TITLE
Custom Activity Indicator

### ISSUE THREAD

**Issue by unittesting0** [rs/SDWebImage#1710]
How can I add my custom Activity Indicator instead of the default one.

For example I want to use this https://github.com/ninjaprox/NVActivityIndicatorView.

Any help what to change.

Thanks in advance.

**Comment by bpoplauschi** [comment]
Just add the control you want over or as a subview of the UIImageView.

**Comment by Rahulpatel8** [comment]
> Just add the control you want over or as a subview of the UIImageView.

Will it hide that added subview automatically OR need to manage it manually?
