### ISSUE TITLE
Compilation Problems with -ObjC

### ISSUE THREAD

**Issue by ruizrica** [rs/SDWebImage#1718]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  **iOS**
 Platform Version        |  **10.0**
 SDWebImage Version      |  **3.8.2**
 Integration Method      |  **cocoapods** 
 Xcode Version           |  **Xcode 8.1**
 Repro rate              |  **(100%)**
 Repro with our demo prj | NO

### Issue Description and Steps

Hi, thanks in advance for helping.  I am using the latest AWS Mobile Hub SDK with my project and that is causing a compilation problem using the -ObjC in the linker flags.  I have read the documentation [here](http://cocoadocs.org/docsets/SDWebImage/3.8.2/) regarding compilation errors and the use of -ObjC:

> Alternatively, if this causes compilation problems with frameworks that extend optional libraries, such as Parse, RestKit or opencv2, instead of the -ObjC flag use:
`-force_load SDWebImage.framework/Versions/Current/SDWebImage`

![Example 1](https://s3-us-west-1.amazonaws.com/kl-store1/example1.jpg)

I still get get compilation errors using this.

![Example 2](https://s3-us-west-1.amazonaws.com/kl-store1/example2.jpg)

I also tried this:

> If you're using Cocoa Pods and have any frameworks that extend optional libraries, such as Parsen RestKit or opencv2, instead of the -ObjC flag use:
`-force_load $(TARGET_BUILD_DIR)/libPods.a` 
and this:
`$(inherited)`

Same error.  Am I using it wrong?  If you need any more info let me know.  Cheers and thanks again.

**Ricardo**

**Comment by bpoplauschi** [comment]
Does SDWebImage build properly? You need to look at the build console in detail to see what is wrong.

**Comment by mythodeia** [comment]
due to lack of response i will close this. please reopen with more info
