### ISSUE TITLE
SDWebImage randomly not showing in UITableViewCell

### ISSUE THREAD

**Issue by gujinku** [rs/SDWebImage#1719]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found one BUT IT WAS CLOSED --> https://github.com/rs/SDWebImage/issues/363

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 8.0 ~10.0
 SDWebImage Version      | e.g. 3.8.1
 Integration Method      | cocoapods
 Xcode Version           | e.g. Xcode 8.0
 Repro rate              | e.g.  sometimes 20%
 Repro with our demo prj | e.g. does it happen with our demo project? hard to reproduce
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

SDWebImage randomly not showing in UITableViewCell even if I switch to other views and back, scroll the table view to trigger the dequeuing of the cells.

**Comment by mythodeia** [comment]
can you replicate it on the demo project as well?

**Comment by gujinku** [comment]
@mythodeia , Sorry for the late reply. 
 Unfortunately I cannot reproduce it, it appears occasionally. And now I've added some logs to debug what happened under the hood.

**Comment by mythodeia** [comment]
please reopen if you are still face issues. Also please download and test the latest version
