### ISSUE TITLE
downloadImageWithURL with same URL twice 100% crash

### ISSUE THREAD

**Issue by JianboYan** [rs/SDWebImage#1720]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 8.2
 SDWebImage Version      | 3.7.3.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.1
 Repro rate              | 100%

### Issue Description and Steps

very sample code:
add code blow to didFinishLaunching:
```
[[SDWebImageManager sharedManager] downloadImageWithURL:URL(@"https://ssl.gstatic.com/gb/images/i2_2ec824b0.png") options:SDWebImageRetryFailed progress:nil completed:nil];
[[SDWebImageManager sharedManager] downloadImageWithURL:URL(@"https://ssl.gstatic.com/gb/images/i2_2ec824b0.png") options:SDWebImageRetryFailed progress:nil completed:nil];
```

100% crash.

**Comment by JianboYan** [comment]
the good news is, i pass a empty completion block, won't crash, it may be a bug, better fix it!

**Comment by mythodeia** [comment]
can you test using the latest version?
i think the correct method is:
```
  [[SDWebImageManager sharedManager] loadImageWithURL:<#(nullable NSURL *)#> options:<#(SDWebImageOptions)#> progress:<#^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL)progressBlock#> completed:<#^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL)completedBlock#>
  ```

**Comment by IOSDeveloperProgrammer** [comment]
@mythodeia  Hi.. !!! Thank you for given great lib.i has been developing chat app.I need to send image with progress like whatsapp. Here, 1. first image sending perfectly with progress. 2. Progress calling repeatedly,while sending 3rd , 4th etc.. image to friend. 3. what did i wrong here please help me
my code here: 

 SDWebImageManager *manager = [SDWebImageManager sharedManager];
    [manager downloadImageWithURL:url1
                          options:SDWebImageRefreshCached
                         progress:^(NSInteger receivedSize, NSInteger expectedSize) {
                            CGFloat domandeFloat = [[NSNumber numberWithInt:(int) receivedSize] floatValue];
                             CGFloat corretteFloat = [[NSNumber numberWithInt: (int)expectedSize] floatValue];
                             
                             
                             float currentProgress = domandeFloat/corretteFloat;
                             
                                                         [self.circleProgressBar setProgress:currentProgress animated:YES];
                         }
                        completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
                            
                                self.circleProgressBar.hidden=YES;
                                [self.circleProgressBar stopAnimation];
                                
                                msg.thumbnail=image;
                                
                                if (_isNewMessage==YES) {
                                    _isNewMessage=NO;
                                }
                               
                            
                            else
                                
                            {
                                self.circleProgressBar.hidden=YES;
                                [self.circleProgressBar stopAnimation];
                            
                                NSData *imageLoadingData = [[NSData alloc] initWithBase64EncodedString:placeholderData options:NSDataBase64DecodingIgnoreUnknownCharacters];
                                
                                msg.thumbnail=[UIImage imageWithData:imageLoadingData];
                            }
                       
                          
                        }];

**Comment by mythodeia** [comment]
did you try with the latest version of the library?

**Comment by IOSDeveloperProgrammer** [comment]
@mythodeia  is it 3.8 latest version ?

**Comment by mythodeia** [comment]
the latest tag is v3.8.2 but there are 2 pre-releases of v4 which you can try if you want

**Comment by IOSDeveloperProgrammer** [comment]
@mythodeia  Thank you for the response. FYI,  I updated v3.8 (was in  3.7. ) but I having same problem. how to solve it. and one more thing  how to show image without blur effect after completed progress. ? Why it's calling again again using block method. please help me

**Comment by mythodeia** [comment]
can you upload a small sample project that replicates the issue so everyone can have a look?

**Comment by holyhan** [comment]
Yon did not pass the "completedBlock" param. Is to want to prefetch image? you can use [SDWebImagePrefetcher prefetchURLs] method retry.

**Comment by mythodeia** [comment]
closing.please reopen if the problem persists
