### ISSUE TITLE
 SDWebImage4.0 load webp animation

### ISSUE THREAD

**Issue by thsseek** [rs/SDWebImage#1723]
I use SDWebImage4.0 load webp animation, there are two different results address pictures, chrome can be normal loading
Success: http://res.cloudinary.com/demo/image/upload/fl_awebp/bored_animation.webp
Failure: http://www.oss.img.yuanquanapp.com/sticker/10001/animated_uri/1.webp
Why failure, how to solve

**Comment by bpoplauschi** [comment]
@thsseek you did not conform to the issue template and provide all the info.

**Comment by mythodeia** [comment]
@thsseek  please try again with the latest version

**Comment by mythodeia** [comment]
closing this due to lack of response. please reopen if you have more info
