### ISSUE TITLE
Do you have a UIImage Category? 

### ISSUE THREAD

**Issue by kuyazee** [rs/SDWebImage#1724]
### New Issue Checklist

* [/] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [/] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [/] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        |  8.0
 SDWebImage Version      | 3.8.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8
Language      | Swift 2.3

By any chance will there be a UIImage Category for SDWebImage? for example I'll initialize an Image 
what I'm doing right now is this

```
var someImage:UIImage = UIImage()
UIImageView().sd_setImageWithURL(NSURL(string: "someUrl")) { (image, error, _, _) in
     someImage = image
}
```
        
will there be something like this?

```
let someImage = UIImage(NSURL(string: "someUrl"))
```

**Comment by bpoplauschi** [comment]
@kuyazee there is no `UIImage` category because it doesn't make sense. `UIImage` is not a view, so I don't think we need that category.
