### ISSUE TITLE
Gif disappear

### ISSUE THREAD

**Issue by EverMe** [rs/SDWebImage#1727]
When navigation interactivePopGestureRecognizer work , imageView shows placeholderImage or backgroundColor but not gif.

Xcode: 8.1                     SDWebImage: 3.8.1

![sdbug_small](https://cloud.githubusercontent.com/assets/11309814/20344533/1328f0de-ac2e-11e6-926f-4968f3bab765.gif)

**Comment by CodeLife2012** [comment]
Seems this is caused by the system.
Currently gif is just multi images in `UIImage`, and will disappear in transition.

**Comment by bpoplauschi** [comment]
Please retry with 4.0.0, we are using `FLAnimatedImage` for the GIF images.

**Comment by wwwjfy** [comment]
The bug is still here, though it's not related to SDWebImage or FLAnimatedImage.
I found that it's a UIImage bug, that if the UIImage is created by `UIImage`'s `animatedImageWithImages:duration:` i.e. UIImage.images is set, during interactive pop gesture, it'll become blank, or a pre-set UIImage (if any, in SDWebImage case, maybe a placeholder image)

I've filed a bug report to Apple.

JFYI if anyone meets the same issue.

**Comment by PerfectShen** [comment]
我也发现这个问题  这个应该怎么处理呢

**Comment by szqxjf** [comment]
怎么处理呢。

**Comment by PerfectShen** [comment]
这个问题 我用iphone6 ios10.3 测试的会有这个问题，ios11 没有这个问题，目前我实现gif用的是其他方式，对内存和cpu占用都做了优化

**Comment by szqxjf** [comment]
用那个第三方库 是没有问题的。但是我们位置是乱变的。粉坑。

**Comment by PerfectShen** [comment]
位置乱变？帧变化的时候混乱了吗

**Comment by szqxjf** [comment]
不是的。还是消失的。 用第三方FLAnimatedImage 这个应该没有问题的。但是得升级版本。我的版本 还是 3.8.2的。升级的成本很高啊。也不懂哪个版本比较稳定。

**Comment by PerfectShen** [comment]
FLA没有问题 要升级什么版本？

**Comment by szqxjf** [comment]
sd 得升级到4.0.0.  。就是不懂 4.0.0-4.2.3 哪个版本比较稳定。

**Comment by PerfectShen** [comment]
好吧 我建议直接使用fla会好一点，fla展示gif图时对内存做了优化。 sd只是初始化一个 UIIamge，并没有对显示做优化，如果显示帧数在100多张的gif图时，内存占用会很高，尤其是列表里显示的时候可能会导致 应用闪退

**Comment by szqxjf** [comment]
恩。关键 我们的位置不固定的。再uicollectionview的，还有各种样式、位置是不固定。不然我就可以下载下来。然后用fla接管了。    改动很大。 所以 才想直接用 sd 4.0.0版本起。

**Comment by dreampiggy** [comment]
from SD 4.2, we provide custom coder plugin. The SDWebGIFCoder offer the previous version's GIF decoding using [UIImage animatedImageWithDuration:]. But it's not enable by default. To make FL work without extra cost.

If you nees both UIImageView or FL works for GIF, you can add that coder and that may work...
