### ISSUE TITLE
Load network image address, white edge fill

### ISSUE THREAD

**Issue by srxboys** [rs/SDWebImage#1729]
When  imageView.backColor = [UIColor Clear]; 
Load network imageURL  (The picture(JPEG) is round and the background is transparent.), a white background fill。

Clean up the memory, restart app, there is no white background fill. After loading the N time(imageURL), it appears again.

**Comment by mythodeia** [comment]
does this happen to a specific image only? if yes please share the image url or a demo project

**Comment by srxboys** [comment]
My project, there are many such pictures. for example:
https://raw.githubusercontent.com/srxboys/RXImages/master/GHS/play.png

**Comment by srxboys** [comment]
Now every time from the new download (SDWebImageRefreshCached).

**Comment by mythodeia** [comment]
did you try it on the demo project as well?

**Comment by srxboys** [comment]
yes!

**Comment by mythodeia** [comment]
i tried it with the demo project and it does not fill with white. which version are you using?

**Comment by srxboys** [comment]
Not every time to add a white background, my project a lot of pictures loaded just 20 downloads, if fast browsing app will be more.
The version I use is the latest.

**Comment by bpoplauschi** [comment]
Sounds like an issue with your code. Make sure you have the proper background set manually.
