### ISSUE TITLE
SDWebImage & gif

### ISSUE THREAD

**Issue by mistak** [rs/SDWebImage#1730]
load pic from the link,
sometimes ,it's a gif. 
I dont't want to load gif pic , because it lead to memory explosion.
 What can I do？

**Comment by mythodeia** [comment]
which version are you using?

**Comment by mistak** [comment]
3.7.3 @mythodeia

**Comment by mistak** [comment]
i need update ? it's can reslove my problem?

**Comment by mythodeia** [comment]
read [this](https://github.com/rs/SDWebImage#animated-images-gif-support)
you can download the latest version and try again or 
you can download v4.0 beta [here](https://github.com/rs/SDWebImage/tree/4.0.0-beta2)
