### ISSUE TITLE
I find a bug ,when I download the same URL so much,then crash.

### ISSUE THREAD

**Issue by steven0610** [rs/SDWebImage#1731]
please see my github,

https://github.com/steven0610/SDWebImageMutableCancelCrashDemo.git

A demo that makes much same url download ,the SDWebImageDownloader has some error.

There are 2 problem.

1. When the url cancel, then [self.URLOperations removeObjectForKey:token.url] ,but it will use in the task sometimes.  So,it crashed.

2.And the other , in the function 

- (void)URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask didReceiveData:(NSData *)data {

the same reason, crashed sometimes.

I think it should be in the  self.barrierQueue .

**Comment by mythodeia** [comment]
can you try it with [v4](https://github.com/rs/SDWebImage/releases/tag/4.0.0-beta2)?

**Comment by steven0610** [comment]
Sure,I already use the latest version,in the master.
I think there was some thing wrong. The url to be used in the dictionary for key,Then the task is not to be done, released.

**Comment by steven0610** [comment]
You can try my demo project,you will see it.

**Comment by mythodeia** [comment]
i tried your demo project but i did not get a crash. let me know how to replicate it
