### ISSUE TITLE
EXC_BAD_ACCESS (code = 1, address = 0 * 73)    crash

### ISSUE THREAD

**Issue by xiaolinmao** [rs/SDWebImage#1733]
![Uploading 4A885353-7185-4932-81A6-DCF47499C3B5.png…]()

**Comment by xiaolinmao** [comment]
[self.imageView sd_setImageWithPreviousCachedImageWithURL:photo.url placeholderImage:photo.sourceImageView.image options:SDWebImageRetryFailed progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) {
            
            
        } completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
            
            
             [weakSelf setMaxAndMinZoomScales];
        }];

**Comment by xiaolinmao** [comment]
[self.imageView sd_setImageWithPreviousCachedImageWithURL:photo.url placeholderImage:photo.sourceImageView.image options:SDWebImageRetryFailed progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) {
            
            
        } completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
            
            
             [weakSelf setMaxAndMinZoomScales];
        }];



crash

**Comment by mythodeia** [comment]
can you please reupload the image and write something about the issue your are facing?
