### ISSUE TITLE
to many crash about this

### ISSUE THREAD

**Issue by z306007236** [rs/SDWebImage#1736]
*** setObjectForKey: object cannot be nil (key: file:///private/var/mobile/Containers/Data/Application/8AFE6753-A8FC-442C-87D1-CFE051AFCBB1/Library/Caches/com.hackemist.SDWebImageCache.default/7721e5f7e553768750de1f7f4ec626e2_real)

**Comment by bpoplauschi** [comment]
Please reopen with the proper info as requested in the [issue](../tree/master/.github/ISSUE_TEMPLATE.md)
