### ISSUE TITLE
Problem displaying prefetched images in offline mode

### ISSUE THREAD

**Issue by burakkilic** [rs/SDWebImage#1740]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | IOS
 Platform Version        | 9.3.5
 SDWebImage Version      | 3.7.6
 Integration Method      |  cocoapods 
 Xcode Version           | 8.1
 Repro rate              | sometimes
 Repro with our demo prj | Don't know

### Issue Description and Steps

I' m getting issue reports from my clients who are using our app offline.

First, I'm prefetching images and showing Loading screen. After that they start to use the app in offline mode. 

In several days, they say that images are gone like in the image below.

![image](https://cloud.githubusercontent.com/assets/123382/20878332/047e2114-bad7-11e6-8eb9-a1aa80475ba2.png)

This is my prefetching code:

https://gist.github.com/burakkilic/9b1aa920a5e3f9a5d27eac75b4729f41

And in collection view, I use it like:

https://gist.github.com/burakkilic/a12abd9c0b2ca19b25a773e19dd110f9

Am I doing something wrong?

**Comment by mythodeia** [comment]
the default maxCacheAge (found in SDImageCacheConfig) is 1 week. Maybe the images are getting invalidated afterwards?

**Comment by burakkilic** [comment]
Can it be? I will test immediately.

**Comment by burakkilic** [comment]
I tested it with 3.7.6 and yes, it is because maxCacheAge. Customers who doesn't connect to internet more than 1 week, cannot see the images.

But in 4.0.0, I couldn't set the maxCacheAge. How can I set that?

**Comment by mythodeia** [comment]
https://github.com/rs/SDWebImage/issues/746#issuecomment-264840104
