### ISSUE TITLE
image path extension bug

### ISSUE THREAD

**Issue by wolangerxing** [rs/SDWebImage#1745]
### New Issue Checklist

*  I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
*  I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
*  I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS 
 Platform Version        |  10.0
 SDWebImage Version      | 3.8.2
 Integration Method      |  cocoapods
 Xcode Version           |  Xcode 8.0
 Repro rate              | all the time (100%)
 Repro with our demo prj |no
 Demo project link       | 

### Issue Description and Steps

Hi, I have found a bug when using SDWebImage in WKWebView. When download a image from URL like xxx.com/xxx, I found that although the image downloaded and stored all right, but the image can not show in a WKWebView. The reason is the image path extension is ".com/xxx" in this case and in WKWebView a image named like this can not be read correctly. Also, I found the pull request: #976 which brought this bug.

I have added a pull request https://github.com/rs/SDWebImage/pull/1742 to resolve this problem, simply prescribe the proper image path extension that should be added to file name, and problem resolved.

**Comment by bpoplauschi** [comment]
Closing - please see #1759 for details.
