### ISSUE TITLE
Data race in SDWebImageCombinedOperation class

### ISSUE THREAD

**Issue by Agarunov** [rs/SDWebImage#1748]
### Issue Info

 Platform Name           iOS
 Platform Version        10.0
 SDWebImage Version      3.8.2
 Integration Method      cocoapods 
 Xcode Version           Xcode 8.1
 Repro rate              only once

### Issue Description

Xcode Thread Sanitizer catch data race in SDWebImageCombinedOperation class. 
In getter [SDWebImageCombinedOperation isCancelled]  and setter [SDWebImageCombinedOperation setCancelled:] 

==================
WARNING: ThreadSanitizer: data race (pid=94112)
  Write of size 1 at 0x7d080015ace8 by main thread:
    0 -[SDWebImageCombinedOperation setCancelled:] SDWebImageManager.m (SDWebImage+0x00000002b1f7)
    1 -[SDWebImageCombinedOperation cancel] SDWebImageManager.m:342 (SDWebImage+0x00000002aedd)
    2 -[UIView(WebCacheOperation) sd_cancelImageLoadOperationWithKey:] UIView+WebCacheOperation.m:44 (SDWebImage+0x00000004498b)
    3 -[UIImageView(WebCache) sd_cancelCurrentImageLoad] UIImageView+WebCache.m:141 (SDWebImage+0x00000004118f)
    4 -[UIImageView(WebCache) sd_setImageWithURL:placeholderImage:options:progress:completed:] UIImageView+WebCache.m:45 (SDWebImage+0x00000003cbf4)
    5 -[UIImageView(WebCache) sd_setImageWithURL:placeholderImage:options:] UIImageView+WebCache.m:29 (SDWebImage+0x00000003c641)
    6 -[UIImageView(ImageCache) setDoorImageWithDoorDesignAsset:] UIImageView+ImageCache.m:54 (Knock+0x0001002b0036)
    7 _TFC5Knock10KNDoorView9configurefT4withCSo20KNUserDoorAttributes_T_ KNDoorView.swift:65 (Knock+0x000100fad29f)
    8 _TFC5Knock14KNDoorUserView9configurefT4withCSo20KNUserDoorAttributes_T_ KNDoorUserView.swift:69 (Knock+0x000100ed17ed)
    9 _TFC5Knock15KNDoorSmallView9configurefT4withCSo20KNUserDoorAttributes_T_ KNDoorSmallView.swift:48 (Knock+0x0001010ec4ac)
    10 _TFC5Knock24KNDoorCollectionViewCell9configurefT_T_ KNDoorCollectionViewCell.swift:75 (Knock+0x000100e78b72)
    11 _TToFC5Knock24KNDoorCollectionViewCell9configurefT_T_ KNDoorCollectionViewCell.swift (Knock+0x000100e78bf3)
    12 -[KNDoorGridController collectionView:cellForItemAtIndexPath:] KNDoorGridController.m:190 (Knock+0x000100b6f714)
    13 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] <null>:160 (UIKit+0x00000096997f)
    14 start <null>:141 (libdyld.dylib+0x00000000468c)

  Previous read of size 1 at 0x7d080015ace8 by thread T6:
    0 -[SDWebImageCombinedOperation isCancelled] SDWebImageManager.m:14 (SDWebImage+0x00000002b15c)
    1 __69-[SDWebImageManager downloadImageWithURL:options:progress:completed:]_block_invoke.102 SDWebImageManager.m:189 (SDWebImage+0x000000025523)
    2 __72-[SDWebImageDownloader downloadImageWithURL:options:progress:completed:]_block_invoke.111 SDWebImageDownloader.m:183 (SDWebImage+0x000000013ccc)
    3 -[SDWebImageDownloaderOperation URLSession:task:didCompleteWithError:] SDWebImageDownloaderOperation.m:431 (SDWebImage+0x00000001e10b)
    4 -[SDWebImageDownloader URLSession:task:didCompleteWithError:] SDWebImageDownloader.m:307 (SDWebImage+0x00000001666b)
    5 __51-[NSURLSession delegate_task:didCompleteWithError:]_block_invoke.185 <null>:168 (CFNetwork+0x00000027f2fb)
    6 _dispatch_client_callout <null>:159 (libdispatch.dylib+0x00000002c0cc)

  Location is heap block of size 32 at 0x7d080015ace0 allocated by main thread:
    0 calloc <null>:220 (libclang_rt.tsan_iossim_dynamic.dylib+0x000000040672)
    1 class_createInstance <null>:136 (libobjc.A.dylib+0x00000000f33f)
    2 -[UIImageView(WebCache) sd_setImageWithURL:placeholderImage:options:progress:completed:] UIImageView+WebCache.m:62 (SDWebImage+0x00000003d0c1)
    3 -[UIImageView(WebCache) sd_setImageWithURL:placeholderImage:options:] UIImageView+WebCache.m:29 (SDWebImage+0x00000003c641)
    4 -[UIImageView(ImageCache) setDoorImageWithDoorDesignAsset:] UIImageView+ImageCache.m:54 (Knock+0x0001002b0036)
    5 _TFC5Knock10KNDoorView9configurefT4withCSo20KNUserDoorAttributes_T_ KNDoorView.swift:65 (Knock+0x000100fad29f)
    6 _TFC5Knock14KNDoorUserView9configurefT4withCSo20KNUserDoorAttributes_T_ KNDoorUserView.swift:69 (Knock+0x000100ed17ed)
    7 _TFC5Knock15KNDoorSmallView9configurefT4withCSo20KNUserDoorAttributes_T_ KNDoorSmallView.swift:48 (Knock+0x0001010ec4ac)
    8 _TFC5Knock24KNDoorCollectionViewCell9configurefT_T_ KNDoorCollectionViewCell.swift:75 (Knock+0x000100e78b72)
    9 _TToFC5Knock24KNDoorCollectionViewCell9configurefT_T_ KNDoorCollectionViewCell.swift (Knock+0x000100e78bf3)
    10 -[KNDoorGridController collectionView:cellForItemAtIndexPath:] KNDoorGridController.m:190 (Knock+0x000100b6f714)
    11 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] <null>:160 (UIKit+0x00000096997f)
    12 start <null>:141 (libdyld.dylib+0x00000000468c)

  Thread T6 (tid=6698775, running) created by thread T-1 at:
    0 pthread_create <null>:220 (libclang_rt.tsan_iossim_dynamic.dylib+0x000000023b60)
    1 InitCGInterfacesOnAnotherThread <null>:194 (vImage+0x00000034ca2e)
    2 dispatch_once_f <null>:220 (libclang_rt.tsan_iossim_dynamic.dylib+0x00000005cff6)
    3 LoadCGInterfaces <null>:194 (vImage+0x00000034c94f)
    4 convert_icc <null>:174 (CoreGraphics+0x00000003d49b)
    5 start <null>:141 (libdyld.dylib+0x00000000468c)

SUMMARY: ThreadSanitizer: data race SDWebImageManager.m in -[SDWebImageCombinedOperation setCancelled:]

==================

**Comment by bpoplauschi** [comment]
Please retry with the latest 4.0 version and let us know if this issue still exists.

**Comment by mythodeia** [comment]
due to lack of response i will close this. please reopen if you have more info
