### ISSUE TITLE
sd_setImage Cannot loading image 

### ISSUE THREAD

**Issue by daizim** [rs/SDWebImage#1749]
In v3.8.2, I use 
[someImageView sd_setImageWithURL:[NSURL URLWithString:@"http://img.dx168.com/hi/20157/27/283/280/90a85da0d4.png"]];
the image cannot loading

**Comment by mythodeia** [comment]
Test the url with the demo project and reply back. Also check your ATS settings in your plist.
please use the latest version if you want.
