### ISSUE TITLE
Why SDWebImageManager not use weakSelf in block ？

### ISSUE THREAD

**Issue by ziwen** [rs/SDWebImage#1751]
i find weakSelf in sd_setImageWithURL of UIImageView (WebCache) ,which has block ,but not use weakSelf in downloadImageWithURL of SDWebImageManager ,which has block and use self in block ,I don`t know why ?

**Comment by 0xdatou** [comment]
where? Why don't you capture?

**Comment by bpoplauschi** [comment]
Ideally, the weak-strong pattern should be used in all places, to be super-safe. But since `SDWebImageManager` is a singleton, we don't really need to worry about it in that case.
