### ISSUE TITLE
SDWebImageAllowInvalidSSLCertificates

### ISSUE THREAD

**Issue by yupuyang** [rs/SDWebImage#1752]
SDWebImageAllowInvalidSSLCertificates 在 iOS 10下不起作用

**Comment by FelixYin66** [comment]
可使用 SDWebImageContinueInBackground 可下载图片，ATS环境下

**Comment by yupuyang** [comment]
https://ii.pod100.com/uf/UploadFiles/20160301/8c763ec4ccb34a3c83684dbd9d503975.jpg

Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x1741198f0>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<cert(0x100882c00) s: pod100.com i: Symantec Basic DV SSL CA - G1>",
    "<cert(0x100883400) s: Symantec Basic DV SSL CA - G1 i: VeriSign Class 3 Public Primary Certification Authority - G5>"
), NSUnderlyingError=0x17405a9a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x1741198f0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x100882c00) s: pod100.com i: Symantec Basic DV SSL CA - G1>",
    "<cert(0x100883400) s: Syman

**Comment by CoderFM** [comment]
same to you @yupuyang

**Comment by mythodeia** [comment]
@yupuyang i tested the url in the demo project and it works fine.

**Comment by FelixYin66** [comment]
https://ii.pod100.com/uf/UploadFiles/20160301/8c763ec4ccb34a3c83684dbd9d503975.jpg  这个图片链接有问题，不是https而是http... 浏览器会给出提示为非安全链接。。。。 如果图片是https的链接，也无需单独配置

**Comment by yupuyang** [comment]
@FelixYin66 如何 非安全链接也能 加载出来？，接口 就可以加载出来啊
