### ISSUE TITLE
[Question] Is it possible to open a API for custom image decode?

### ISSUE THREAD

**Issue by IvanChan** [rs/SDWebImage#1753]
In **UIImage+MultiFormat.m**, SD only support **webp** & **gif** & **default**

In my case, I have my own content-type & image decode-logic

foe example I might have a image type call **sobp** in content-type **image/sobp**, I have my own decode logic in my app.

**How about open a api for user to handle some specific content-type & image-decode ?** 

Maybe before `sd_imageWithData`,  pass **content-Type** & **image data** to a delegate for a **UIImage** object, if return nil,  then run `sd_imageWithData`?

Currently, only way to achieve this is 
1.  using `SDWebImageDownloader` to download image instead of `SDWebImageManager `
2. hanlde data -> image process,  achieve **UIImage+MultiFormat.m** my own
3. cache Image to `SDWebImageManager ` manually when got image from `SDWebImageDownloader`

It's quite wasteful duplication of work.

**Comment by bpoplauschi** [comment]
@IvanChan it is a good idea, but us the maintainers will not have the time to do this in the near future. Feel free to work on a pull request

**Comment by bpoplauschi** [comment]
@IvanChan see #1991. I think it's pretty close to what you asked here. And it will be included into the next (4.2.0) release.
