### ISSUE TITLE
the func "sd_imageWithWebPData" of the header “UIImage + WebP.h”  is not work

### ISSUE THREAD

**Issue by theSouthOfSummer** [rs/SDWebImage#1755]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 9.0
 SDWebImage Version      | e.g. latest version
 Integration Method      | e.g.  cocoapods 
 Xcode Version           | e.g. Xcode 8.1
 Repro rate              | e.g. all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

 I import the header "UIImage + WebP.h" no any promlems  , but when I use the func  "sd_imageWithWebPData" to init a UIImage with WebpData , there are not any tip to init ,and write sd not work either , my English  is not well , For example 
UIImage *Image = [UIImage sd_imageWithWebPData:date];
it warning :not exit this func like sd_imageWithWebPData 
I don't know how to do  this ,thanks;
 

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by IvanChan** [comment]
@theSouthOfSummer 
If you are using pod, use
   ` pod 'SDWebImage/WebP'`

instead of 
    `pod 'SDWebImage'`

**Comment by bpoplauschi** [comment]
This was changed in the 4.0.0 release. Please retry

**Comment by theSouthOfSummer** [comment]
Thank

2017-01-28 3:23 GMT+08:00 Bogdan Poplauschi <notifications@github.com>:
