### ISSUE TITLE
iOS 9.3.3 Https can't loading image,NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

### ISSUE THREAD

**Issue by Tweiwei497435786** [rs/SDWebImage#1757]
just iOS 9.3.3 Https can't loading image,9.3.4,10.01,10.02 can loading image,showing error message :NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802) ,AFNetworing  also can working on https。

**Comment by mythodeia** [comment]
did you check the ATS settings in your plist? if your ssl is not valid you can add the SDWebImageAllowInvalidSSLCertificates option
