### ISSUE TITLE
The func 'cachedFileNameForKey' in 'SDImageCache' class does not return what I had in mind.

### ISSUE THREAD

**Issue by eggswift** [rs/SDWebImage#1758]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS Simulator
 Platform Version        | iOS 10.1
 SDWebImage Version      | 3.8.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.2.1(8C1002)
 Repro rate              | all the time (100%)

### Issue Description and Steps

Our image server has many images URL like 'https://nimg.ws.126.net/?url=http%3A%2F%2Fimg1.126.net%2Fchannel4%2F201600%2F1080624_1223.jpg&thumbnail=750x1600&type=webp&quality=75'

When SDWebImage system download images or read caches from this kind of urls,  it will call `- (NSString *)cachedFileNameForKey:(NSString *)key;` method to get cache file's name.

```objective-c

- (nullable NSString *)cachedFileNameForKey:(nullable NSString *)key {
    const char *str = key.UTF8String;
    if (str == NULL) {
        str = "";
    }
    unsigned char r[CC_MD5_DIGEST_LENGTH];
    CC_MD5(str, (CC_LONG)strlen(str), r);
    NSString *filename = [NSString stringWithFormat:@"%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%@",
                          r[0], r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9], r[10],
                          r[11], r[12], r[13], r[14], r[15], [key.pathExtension isEqualToString:@""] ? @"" : [NSString stringWithFormat:@".%@", key.pathExtension]];

    return filename;
}

```

**Wrong return may happend**
**Param key**:
https://nimg.ws.126.net/?url=http%3A%2F%2Fimg1.126.net%2Fchannel4%2F201600%2F1080624_1223.jpg&thumbnail=750x1600&type=webp&quality=75

**Function retrun**:
851477e64fd3e90c18f3431e034785bd.jpg&thumbnail=750x1600&type=webp&quality=75

**I had in mind**:
851477e64fd3e90c18f3431e034785bd

It seems that ` [someString pathExtension]` function is unauthentic.

This change may fix it:
 
```objective-c
- (nullable NSString *)cachedFileNameForKey:(nullable NSString *)key {
    const char *str = key.UTF8String;
    if (str == NULL) {
        str = "";
    }
    unsigned char r[CC_MD5_DIGEST_LENGTH];
    CC_MD5(str, (CC_LONG)strlen(str), r);
    NSString *pathExtension = @"";
    // Initializes and returns a newly created NSURLComponents with a URL string. If the URLString is malformed, nil is returned.
    NSURLComponents *commpoents = [NSURLComponents componentsWithString:key];
    if (commpoents && commpoents.path) {
        pathExtension = [commpoents.path pathExtension];
    } else {
        pathExtension = [key pathExtension];
    }
    NSString *filename = [NSString stringWithFormat:@"%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%@",
                          r[0], r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9], r[10],
                          r[11], r[12], r[13], r[14], r[15], [key.pathExtension isEqualToString:@""] ? @"" : [NSString stringWithFormat:@".%@", key.pathExtension]];

    return filename;
}

```

I have commited a pull request for this issue.

**Comment by eggswift** [comment]
#1745

**Comment by bpoplauschi** [comment]
Closing - See #1759 for details
