### ISSUE TITLE
 What you are using tools drawing？

### ISSUE THREAD

**Issue by leer168** [rs/SDWebImage#1761]
Hi, I want to know what you are using tools drawing the SDWebImageClassDiagram.png and  SDWebImageSequenceDiagram.png.

Thank you very much!

**Comment by al-liu** [comment]
I also want to know.

**Comment by littlesome** [comment]
Guess it's StarUML, since there's a SDWebImage.mdj file in Docs directory (mdj = metadata-json).

**Comment by al-liu** [comment]
Hello, You're right. This is the StarUML. Thank you very much.

littlesome <notifications@github.com>于2017年1月24日 周二12:53写道：
