### ISSUE TITLE
open ATS, cannot load https image err:kCFStreamErrorDomainSSL, -9802

### ISSUE THREAD

**Issue by gaopeipeiok** [rs/SDWebImage#1762]
I download the newest ver of sdwebimage, but cannot load https image when I open ATS.err desc NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

**Comment by mythodeia** [comment]
did you set your ATS keys in your plist file? check the demo

**Comment by gaopeipeiok** [comment]
do you mean this key? in 2017,the key cannot use,and must open ATS.
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
