### ISSUE TITLE
Pass custom Header for download image 

### ISSUE THREAD

**Issue by Tejas-narola** [rs/SDWebImage#1763]
I need to pass custom `HTTPHeader` for fetch image but getting error 401. same token is working for other api.

I attached image of debugging mode. 
![screen shot 2017-01-02 at 11 52 42 am](https://cloud.githubusercontent.com/assets/5028455/21585655/fa6b8fca-d0ea-11e6-940d-7c33ca19e20d.png)

Other api is working well with same token and email id. 
and also get image in postman tool.
 
I am passing custom headers like below code. 

    SDWebImageDownloader *manager = [SDWebImageManager sharedManager].imageDownloader;
    [manager setValue:[DefaultsValues getStringValueFromUserDefaults_ForKey:kTokenKey] forHTTPHeaderField:@"authToken"];
    [manager setValue:[DefaultsValues getStringValueFromUserDefaults_ForKey:kUserEmail] forHTTPHeaderField:@"email"];
    [manager downloadImageWithURL:[NSURL URLWithString:@"URL STRIng"] options:SDWebImageDownloaderUseNSURLCache progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) {
        NSLog(@"%tu",receivedSize);
        
    } completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, BOOL finished) {
        if (error == nil) {
            cell.profileImage.image = image;
        }
    }];
can you please help me out with this issue ?
Thanks in advance.

**Comment by bpoplauschi** [comment]
You need to find a way to make the same request as with postman.
