### ISSUE TITLE
SDWebImage 3.8 -1005

### ISSUE THREAD

**Issue by leejtom** [rs/SDWebImage#1765]
Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSUnderlyingError=0x1702460f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=http://famulei.6655.la:80/cert/1483497579195.png, NSErrorFailingURLKey=http://famulei.6655.la:80/cert/1483497579195.png, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-4, NSLocalizedDescription=The network connection was lost.}

thk.

**Comment by mythodeia** [comment]
as it says on the error message the network connection was lost during the request. Also the url is not reachable now that i am trying it.
