### ISSUE TITLE
How To Pre-download image without using UIImageView

### ISSUE THREAD

**Issue by ryandailey100** [rs/SDWebImage#1771]
I want to be able to download and cache the image from a url before applying the image to a UIImageView, so that when I want the ImageView to display the image, the image will already be cached and instantly displays the picture. How would I go about doing this? 

### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        |  8.0
 SDWebImage Version      |  3.7.6
 Integration Method      |  cocoapods
 Xcode Version           | Xcode 8.2.1
 Repro rate              | all the time (100%)
 Repro with our demo prj |  yes
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by bpoplauschi** [comment]
@ryandailey100 look at `SDWebImagePrefetcher`
