### ISSUE TITLE
NSAllowsArbitraryLoadsForMedia

### ISSUE THREAD

**Issue by charliefancelli** [rs/SDWebImage#1777]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.0
 SDWebImage Version      | ~>3.8
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.2

### Issue Description and Steps

Hi, 

We have an issue with the security protocol in iOS 10 and iOS9.
We set `NSAllowsArbitraryLoadsForMedia` and `NSAllowsArbitraryLoadsInWebContent` in the `Info.plist` as like Apple required. But we have the error form sd_image.

```
The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
```

We already add `NSAllowsArbitraryLoads` but normally in iOS9 and iOS10 the key is skip if the others are set.

Thanks,

**Comment by bpoplauschi** [comment]
I don't know what the exact issue is (I never used `NSAllowsArbitraryLoadsForMedia`), but If you have set `NSAllowsArbitraryLoads` inside `NSAppTransportSecurity` in the plist, then your non-https connections should work.
The issue doesn't seem to be a direct problem with the library, so I'll close the issue.

**Comment by charliefancelli** [comment]
Hi,

If you check the Apple official documentation you will see that we need to use these news keys on ios 10. Normally the `NSAllowsArbitraryLoads` limit use was in January 2017 (but they announced to add a delay), so in future the key will be removed.

[https://developer.apple.com/library/prerelease/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33](url)

**Comment by bpoplauschi** [comment]
I see. But those are settings for your application. Not really related to our project, right?

**Comment by charliefancelli** [comment]
I don't think saw, in next month, `NSAllowsArbitraryLoads` will be remove and only `NSAllowsArbitraryLoadsForMedia` (and  will work `NSAllowsArbitraryLoadsInWebContent`).
And actually with these keys this library not working.

**Comment by bpoplauschi** [comment]
Can you share a demo project where this happens?

**Comment by charliefancelli** [comment]
Yes of course, i will send it in the week (i can't send this project so i need time to create a demo app)

**Comment by mythodeia** [comment]
closing this. please reopen if you have more info
