### ISSUE TITLE
CFBundleVersion is not valid for all platforms

### ISSUE THREAD

**Issue by ivan-konov** [rs/SDWebImage#1780]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS
 Platform Version        | 10.2.1
 SDWebImage Version      | 4.0.0
 Integration Method      | carthage
 Xcode Version           | Xcode 8.2.1
 Repro rate              | 100%
 Repro with our demo prj | No

### Issue Description and Steps

When submitted to iTunes Connect/TestFlight the archive is rejected because the CFBundleVersion does not have a value in the Info.plist. 
"ERROR ITMS-90056: This bundle is invalid. Payload/_YOUR_APP_HERE_/Frameworks/SDWebImage.framework Info.plist file is missing the required key: CFBundleVersion"
I saw in the project that it is set to 1 for some platforms and is missing for others - especially iOS. It seems Apple have some new more strict rules for the provisioning and bundles metadata effective since yesterday. I'd suggest you maintain a better versioning for the project and it's targets.

**Comment by dunqi** [comment]
Same problem here

**Comment by bpoplauschi** [comment]
Let's see how we can fix this. I assume it's just missing from the Info.plist, even if that plist was generated by Xcode.

**Comment by ivan-konov** [comment]
Yeah. I'd suggest you just go over all of the different targets' Build Settings and chamge Current Project Version value or go to the Info.plist an change it there. Just make sure all targets have one of these set to something meaningful to your progress on the project.

**Comment by omatty198** [comment]
Same problem...
I screamed and directly it edited. 😱 
`$(SRCROOT)/Carthage/Build/iOS/SDWebImage.framework/info.plist`

<img width="725" alt="2017-02-04 21 22 46" src="https://cloud.githubusercontent.com/assets/3251428/22618463/1c70436e-eb20-11e6-87f6-2f87d54904ab.png">

**Comment by dunqi** [comment]
So, do I have to change it manually?

**Comment by ivan-konov** [comment]
@omatty198 I did the same thing :)

**Comment by bpoplauschi** [comment]
Can any of you guys create a PR with this change?

**Comment by JKercheval** [comment]
I am using Carthage and am hitting this exact error - ERROR ITMS-90056: "This bundle .../SDWebImage.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."
Is there a workaround for this?  Branch, fix - need help :)

**Comment by dunqi** [comment]
I checked out the pull request #1784
Worked fine for me

**Comment by bpoplauschi** [comment]
Great guys.
@ivan-konov PR was merged into master.
Closing this.

**Comment by ivan-konov** [comment]
Sure, glad to help!

**Comment by jfsagasti** [comment]
I've updated with latest version, but still happening...

**Comment by jfsagasti** [comment]
I've modified the Info.plist manually to make the upload as @omatty198 pointed out.

**Comment by ivan-konov** [comment]
@jfsagasti by "update to the latest version" you mean cloning master branch or downloading latest release?

**Comment by jfsagasti** [comment]
You are right. Carthage picked the latest release I guess (I don't have "master" specified in the cartfile). Sorry for the oversight!

**Comment by ivan-konov** [comment]
@jfsagasti If you are in a rush and need to submit soon I would suggest you stick to the manual change solution and not really rely on master as a stable codebase.

**Comment by jfsagasti** [comment]
That's exactly what I did, thanks! I needed to submit a new version today 👍

**Comment by mitch10e** [comment]
I had this same problem today. Manually edited the SDWebImage.framework/Info.plist file to set the CFBundleVersion
