### ISSUE TITLE
Dynamic paginated Collectionview & or TableView with Sdwebimage How? Best setup?

### ISSUE THREAD

**Issue by alexrmacleod** [rs/SDWebImage#1782]
1: I only find out the **image height after SDWebimage has loaded** the photo from a url. 

2: However the height of the image isn't the correct height I need since every photos width is set to `(width: self.view.bounds.width)`. **I need to find out how high the photo needs to be relative to that width** to see the entire picture.

3: I am thinking about doing a background thread forloop that loads the images with sdwebimage then calculates correct heights relative to the set width. Then puts them into an array, then present the cells with the correct heights cached. Humm how to do this? A little stuck.

4: Also looking for an awesome **Collectionview that has a great paginated feature**. currently my pagination kinda sucks because when I get to the bottom of a set of data and there is on more data to query, it will keep trying to query more data and cause interference with user scrolling.   

5: Check out my iOS app called [Tipped][1]. You can download to understand this question better. 

Current solution I have tried found below. **It's not working well. Scrolling is very jittery** because I resize the cell using `sizeForItemAt indexPath`. Looking for a solution to this problem. I believe people must have solved this one before.  

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        let layout: UICollectionViewFlowLayout = self.collectionView?.collectionViewLayout as! UICollectionViewFlowLayout
        layout.itemSize = CGSize(width: self.view.bounds.width, height: self.view.bounds.height / 2)
        
        activityIndicator.frame = CGRect(x: 0, y: 0, width: self.view.bounds.width, height: self.view.bounds.height / 2)
        blackActivityFadeView.frame = CGRect(x: 0, y: 0, width: self.view.bounds.width, height: self.view.bounds.height / 2)
    }
    

    override func queryForCollection() -> PFQuery<PFObject> {
        let secondsInWeek = 7 * 24 * 60 * 60
        let secondsInMonth = 30.4167 * 24 * 60 * 60
        
        let weekAgo:Date = Date(timeIntervalSinceNow: -secondsInMonth)
        //    print(weekAgo.timeIntervalSince1970)
        let query = super.queryForCollection()
        query.cachePolicy = PFCachePolicy.networkElseCache
        //    query.orderByDescending("timedecay_popularity_score")
        query.order(byDescending: "popularity_score")
        query.includeKey("tumblr")
        query.whereKey("timestamp", greaterThan: weekAgo.timeIntervalSince1970)
        query.whereKey("visible", notEqualTo: false)
        return query
    }
    
    override func objectsDidLoad(_ error: Error!) {
        
        for photo in self.objects {
            
        }
        
        if scrollViewPoint < blackActivityFadeView.frame.height {
            //            print("error24: - \(error)")
            activityIndicator.stopAnimating()
            blackActivityFadeView.alpha = 0.2
            UIView.animate(withDuration: 1.5, animations: { () -> Void in
                self.activityIndicator.alpha = 0
                self.blackActivityFadeView.alpha = 0
            }, completion: { (success:Bool) -> Void in
                if success == true {
                    //                    self.blackActivityFadeView.hidden = true
                }
            })
        }
    }
    
    //Footerview size
    override func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForFooterInSection section: Int) -> CGSize {
        
        
        return CGSize(width: self.view.bounds.width, height: 49)
    }
    
    override func numberOfSections(in collectionView: UICollectionView) -> Int {
        return 1
    }
    //More FooterViewStuff
    override func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
        
        var reusableview: UICollectionReusableView!
        //        println("kind:- \(kind)")
        
        if kind == UICollectionElementKindSectionFooter {
            
            let footerView: UICollectionReusableView = collectionView.dequeueReusableSupplementaryView(ofKind: UICollectionElementKindSectionFooter, withReuseIdentifier: "popularFooterView", for: indexPath)
            
            reusableview = footerView
        }
        return reusableview
    }
    
    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath, object: PFObject?) -> PFCollectionViewCell? {
        let photo = object as! TumblrPhoto
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: reuseIdentifier, for: indexPath) as? PhotoCollectionViewCell
        cell?.delegate = self
        cell?.delegateContainerView = self
        cell?.parentDropdown = parentDropdown
        cell?.photo = photo
        cell?.defaultConfiguration()
        cell?.parentViewController = self
        
        //Adding decending interger on popular stream and removing the likes view for this Collectioview
        cell?.photoRankLabel.text = String(indexPath.row + 1)
        //    cell?.likesCountView.hidden = true
        
        cell?.photoImageView.sd_setImage(with: URL(string: photo.standardResolutionImageULR)!, completed: { (image:UIImage?, error:Error?, cacheType:SDImageCacheType, url:URL?) -> Void in
            
            if (image == nil) {
                print("missing photo")
                print(url)
                
                self.removeItem(photo)
                self.collectionView?.reloadData()
                
                photo["visible"] = false
                photo.saveInBackground()
                
                
            }
            self.collectionView?.collectionViewLayout.invalidateLayout()
        })
        return cell
    }
    
    override func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        
        var cell:PhotoCollectionViewCell?
        var height:CGFloat = self.view.bounds.height / 2
        
        if self.collectionView?.cellForItem(at: indexPath) != nil {
            cell = collectionView.cellForItem(at: indexPath) as? PhotoCollectionViewCell
            
            if cell!.photoImageView.image != nil {
                height = cell!.photoImageView.image!.size.height
            }
        }
        return CGSize(width: self.view.bounds.width, height: height)
    }
    
    let transitionManager = DetailPageTransitionManager()
    var lastScrollPoint:CGPoint?
    
    override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        
        lastScrollPoint = CGPoint(x: 0.0, y: scrollViewPoint)
        
        let gallery = UIStoryboard(name: "PhotoDetail", bundle: nil).instantiateViewController(withIdentifier: "gallery") as! PhotoGalleryViewController
        
        gallery.parentCollection = self
        gallery.photos = self.objects as! [TumblrPhoto]
        gallery.selectedPhotoIndexPath = indexPath
        
        gallery.delegateContainerView = self
        
        gallery.modalPresentationStyle = .fullScreen
        gallery.transitioningDelegate = self.transitionManager
        //*************************
        gallery.fromIgProfile = false
        //*************************
        
        self.transitionManager.destinationGalleryViewController = gallery
        
        self.present(gallery, animated: true, completion: nil)
    }

  [1]: https://itunes.apple.com/us/app/tipped/id1048996999?mt=8

I know this thread is only of SDwebimage related issues. But I feel this is also the best place to ask such a question because of all the SDwebimage users who have probably solved this issue already. Having no luck with stackoverflow. Anyways any help appreciated.

**Comment by skyline75489** [comment]
There is no easy way to improve app performance. I think you'll need to profile you app with Instruments to get a better understanding of the exact cause of performance bottleneck.

**Comment by mythodeia** [comment]
Since this is not an SDWebImage related issue i will need to close this. If you have any issues with the library please do not hesitate to open an issue.
