### ISSUE TITLE
How to set image cache config after update to 4.0.0 ?

### ISSUE THREAD

**Issue by qmkCamel** [rs/SDWebImage#1786]
After update to 4.0.0 , I find there is not a appropriate way to set SDImageCacheConfig .
The property config of SDImageCache is readonly .
![image](https://cloud.githubusercontent.com/assets/5952752/22674749/a2d66106-ed1c-11e6-9159-2ffddde17f0f.png)
Can I only set that like this ?
![image](https://cloud.githubusercontent.com/assets/5952752/22674780/c72743a4-ed1c-11e6-8caa-f0680993e5cb.png)

**Comment by bpoplauschi** [comment]
@qmkCamel the idea was not to be able to change the config instance, but only its properties. 
We take care of creating the `SDImageCacheConfig` instance.
You should only alter the configs you want.
For example:
```
_exportImageCache.config.shouldDecompressImages = NO;
_exportImageCache.config.shouldCacheImagesInMemory = YES;
_exportImageCache.config.maxCacheAge = 3600;
```
Makes sense?

**Comment by qmkCamel** [comment]
thanks
