### ISSUE TITLE
Does not work with xcode 8, swift 3

### ISSUE THREAD

**Issue by SylarRuby** [rs/SDWebImage#1789]
```

Swift 3,
XCode 8
platform :ios, '8.0'
pod 'SDWebImage', '~>3.8'

```

Now in controller:

<img width="432" alt="screen shot 2017-02-08 at 05 48 33" src="https://cloud.githubusercontent.com/assets/7381195/22725036/519d889a-edc2-11e6-8177-7abc133bc137.png">

Have I missed a step? Not 100% compatible with Swift 3?

**Comment by bpoplauschi** [comment]
@SylarRuby when you created a new issue, an issue template was pre-filled. We need that info in order to understand your issue.

Especially in this case, what is the compiler error you are getting?
Also, note that we have a 4.0 version, so you should try that.

**Comment by SylarRuby** [comment]
@bpoplauschi I'll pre-fill if v4 is the same. Will update in a bit. Thanks.

**Comment by SylarRuby** [comment]
@bpoplauschi Apologies for the new issue. My incompetence got the best of me this morning. I forgot to build my project before importing :(
