### ISSUE TITLE
Setting global cache size

### ISSUE THREAD

**Issue by Binusz** [rs/SDWebImage#1791]
How can we set app image cache size ? 

When i try to use "[SDImageCache sharedImageCache].config.maxCacheSize = 65 * 1024 * 1024", i got "[SDImageCache config]: unrecognized selector sent to instance " error

**Comment by bpoplauschi** [comment]
@Binusz make sure you are using the 4.0 version of the library.
For an older version, if you cannot upgrade, use `[SDImageCache sharedImageCache].maxCacheSize = ...`

**Comment by Binusz** [comment]
Sorry. it's my fault that i didn't mention which version i use. 
Yes, i've already upgraded to 4.0.0

**Comment by bpoplauschi** [comment]
@Binusz Upgrading to 4.0.0 fixed your issue?

**Comment by Binusz** [comment]
I said that i'd already upgraded. Eventually, i modifed podfile and that problem fixed. (adding use_frameworks!)
