### ISSUE TITLE
[!] An unexpected version directory `FLAnimatedImage` was encountered for the `/Users/lv/.cocoapods/repos/rs/SDWebImage` Pod in the `SDWebImage` repository.

### ISSUE THREAD

**Issue by cryboyofyu** [rs/SDWebImage#1800]
pod search SDWebImage

return error:[!] An unexpected version directory `FLAnimatedImage` was encountered for the `/Users/lv/.cocoapods/repos/rs/SDWebImage` Pod in the `SDWebImage` repository.

**Comment by bpoplauschi** [comment]
this must be an issue with your local cocoapods repository. Try cleaning it up.
