### ISSUE TITLE
UIActivityIndicator view creation on background thread when setting URL for UIImageViews on background thread results in degraded user experience (sometimes crashes).

### ISSUE THREAD

**Issue by jimmaye** [rs/SDWebImage#1801]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 8.0+
 SDWebImage Version      | 4.0.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.2.1
 Repro rate              | 100%
 Repro with our demo prj | No
 Demo project link       | N/A

### Issue Description and Steps
Enable activity indicator as per documentation on main thread for any given UIImageView.
Set one or more image URL's on a background thread for the imageview(s), and observe that the UI stack get's corrupt (either by crashing, Xcode console output and/or UIAnimations fail afterwards (e.g like pushing a viewcontroller)).

Seems like the creation of the UIActivityIndicator sometimes happens on the background thread, hence the poor user experience afterwards.

**Comment by bpoplauschi** [comment]
Fixed by #1802
