### ISSUE TITLE
a question of code304 handle in SDWebImageDownloaderOperation class

### ISSUE THREAD

**Issue by Yuzeyang** [rs/SDWebImage#1803]
I read the latest code, but i have a question of code304 handle in SDWebImageDownloaderOperation class, it calls `cancelInternal`, and `cancelInternal` calls `reset`, it will removes all object in callbackBlocks.

I imagine if I download many images, and one image is return 304, it will remove all callbackBlocks, if the other images cannot callback?

**Comment by bpoplauschi** [comment]
Please note we have an instance of `SDWebImageDownloaderOperation` for each image download. So if one images gets a 304, it will not affect the other images.

**Comment by Yuzeyang** [comment]
`we have an instance of SDWebImageDownloaderOperation for each image download`, why you name `callbackBlocks`, name `callbackBlock` is the better?

**Comment by bpoplauschi** [comment]
It's a problem from a previous refactoring - `callbackBlocks` used to be a property of `SDWebImageDownloader` and it made sense to be an array, as it hold the callbacks for multiple urls. It was moved to `SDWebImageDownloaderOperation` in #883 and persisted as an array of dictionaries, when it should be just a dictionary.

**Comment by Yuzeyang** [comment]
thanks for your explain😁
