### ISSUE TITLE
[Question] gif played issue when slide to pop vc

### ISSUE THREAD

**Issue by welsonxue** [rs/SDWebImage#1808]
Hi All,

We are having an issue when playing a gif image. 
We find the gif image simply disappeared when we are trying to pop a view controller to the controller which contains the gif image using gestures.

Suppose there is a gif image playing on view controller A, then we push another view controller B on top of it. It is perfectly fine if we click the back button on the navigation bar, but when we try to use the sliding gesture to pop the view controller, the gif image on the previous page disappears during the panning. 

Anyone have seen this issue? Many thanks for help.

**Comment by mythodeia** [comment]
which version of this library are you using? do you use the FLAnimatedImageView to render the gif? can you replicate it on the demo project?

**Comment by welsonxue** [comment]
SDWebImage version is 3.8.2, yet most of my code is still using sd instead of FLAnimatedImageView. Here is my simple demo, I'd appreciate it very much if this problem could be solved, or at least let me known the reason about this phenomenon.
[IssueAboutGifDemo.zip](https://github.com/rs/SDWebImage/files/779322/IssueAboutGifDemo.zip)

**Comment by mythodeia** [comment]
can you try with the latest version 4.0.0 and let us know?
also maybe [this](https://github.com/rs/SDWebImage/pull/1810) ?

**Comment by welsonxue** [comment]
ok i'll have a try soon later with 4.0.0, but i think maybe it's not the key point.

**Comment by mythodeia** [comment]
closing this. please reopen when you have more info
