### ISSUE TITLE
Crash issue on UIImage+MultiFormat

### ISSUE THREAD

**Issue by siliconprime-hoangho** [rs/SDWebImage#1809]
Hi Dev team, I have a crash issue on my project. And It comes from UIImage+MultiFormat.m (line 37)

## Version info
  - SDWebImage version: 3.8.2
  - iOS version: 9.3.5
  - Device: iPad 3, 320 MB free disk

## Logs
Exception Type:  NSInvalidArgumentException
Crashed Thread:  11

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** NSAllocateMemoryPages(582137) failed'

Thread 11 Crashed:
0   CoreFoundation                0x243b391b  __exceptionPreprocess + 61554815
1   libobjc.A.dylib               0x23b4ee17  objc_exception_throw + 61554727
2   CoreFoundation                0x243b3861  [NSException initWithCoder:] + 61554689
3   Foundation                    0x24b6edf5  NSAllocateMemoryPages + 61554781
4   Foundation                    0x24b46635  _NSDataCreateVMDispatchData + 61554713
5   Foundation                    0x24b15739  [_NSPlaceholderData initWithBytes:length:copy:deallocator:] + 61554909
6   Foundation                    0x24b15653  [NSData(NSData) initWithBytes:length:copy:freeWhenDone:bytesAreVM:] + 61554767
7   Foundation                    0x24b22d93  [NSData(NSData) copyWithZone:] + 61554807
8   UIKit                         0x28a84e35  _UIImageRefFromData + 61555009
9   UIKit                         0x28c108cf  [UIImage(UIImagePrivate) _initWithData:preserveScale:cache:] + 61554779
10  UIKit                         0x28a84cf1  [UIImage initWithData:] + 61554717
13  AppName                		  0x3bde53    [UIImage(MultiFormat) sd_imageWithData:] (UIImage+MultiFormat.m:37)
14  AppName                		  0x3b6df1    [SDWebImageDownloaderOperation URLSession:task:didCompleteWithError:] (SDWebImageDownloaderOperation.m:417)
15  AppName                		  0x3b4d7d    [SDWebImageDownloader URLSession:task:didCompleteWithError:] (SDWebImageDownloader.m:307)
17  CFNetwork                     0x2499d505  [NSURLSession delegate_task:didCompleteWithError:]_block_invoke170] + 61554765
18  Foundation                    0x24bc5679  __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 61554697

I don't know why NSAllocateMemoryPages exception was thrown because the device still have about 320 MB free disk space

**Comment by mythodeia** [comment]
can you try using the latest version (4.0.0)

**Comment by siliconprime-hoangho** [comment]
Thank @mythodeia , I'll try it.

So I'll close this issue now and inform you if any update.

Thanks.
