### ISSUE TITLE
after I update SDWebImage,find the method always dowload image ,Not like that before the cache, then read the cache

### ISSUE THREAD

**Issue by songxing10000** [rs/SDWebImage#1811]
```
[[SDWebImageDownloader sharedDownloader] downloadImageWithURL:_photo.url options:SDWebImageRetryFailed| SDWebImageLowPriority progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) {
      
        } completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, BOOL finished) {
            
        }];
```

**Comment by mythodeia** [comment]
i am sorry but i cannot understand whats the issue. can you please elaborate?

**Comment by songxing10000** [comment]
@mythodeia I want to say means the method
 [[SDWebImageDownloader sharedDownloader] downloadImageWithURL:(nullable NSURL *)url                                                       options:(SDWebImageDownloaderOptions)options
progress:(nullable SDWebImageDownloaderProgressBlock)progressBlock
completed:(nullable SDWebImageDownloaderCompletedBlock)completedBlock


 is the latest ,before the version 
[[SDWebImageManager sharedManager] downloadImageWithURL:(NSURL *)url
                                         options:(SDWebImageOptions)options
                                        progress:(SDWebImageDownloaderProgressBlock)progressBlock
                                       completed:(SDWebImageCompletionWithFinishedBlock)completedBlock

will be cached, and now the latest version of the method is not cached, as if it is real-time download

**Comment by songxing10000** [comment]
When I returned to the 3.8.2 version, everything actually normal, but once the switch to 4.0.0, there is a problem, how is it, ah, is my use is wrong?

**Comment by bpoplauschi** [comment]
@songxing10000 please follow the [Migration Guide to 4.0](https://github.com/rs/SDWebImage/blob/master/Docs/SDWebImage-4.0-Migration-guide.md), as some entities got renamed/removed.
