### ISSUE TITLE
-Wconditional-uninitialized

### ISSUE THREAD

**Issue by 5SMNOONMS5** [rs/SDWebImage#1812]
Installation via **Carthage**, when I run below code 
```bash
carthage update --platform iOS
```
It appears this warning 

<img width="1280" alt="screen shot 2017-02-18 at 12 46 49 am" src="https://cloud.githubusercontent.com/assets/8379901/23076865/b3504e56-f574-11e6-817c-d06b1798a301.png">

also I tried to build my code, it appear this error 

<img width="1280" alt="screen shot 2017-02-18 at 12 57 03 am" src="https://cloud.githubusercontent.com/assets/8379901/23076989/3692fde0-f575-11e6-9a6f-1fb7fe705586.png">

**Comment by skyline75489** [comment]
The warning is about libwebp and basically irrelevant in most cases.

**Comment by bpoplauschi** [comment]
Closing, it's not an issue with SDWebImage.
