### ISSUE TITLE
A problem about 'set image for UIButton'

### ISSUE THREAD

**Issue by gaowanli** [rs/SDWebImage#1814]
Use this method to set the image for UIButton
```objectivec
- (void)sd_setImageWithURL:(nullable NSURL *)url forState:(UIControlState)state placeholderImage:(nullable UIImage *)placeholder;
```
When the url is nil, The placeholderImage can not be displayed correctly!
If the UIButton in UITableViewCell,there will be a reusable problem!

...

I remember that was not the case before

**Comment by bpoplauschi** [comment]
@gaowanli can you please conform to the [ISSUE_TEMPLATE](../blob/master/.github/ISSUE_TEMPLATE.md) on this project?

**Comment by skyline75489** [comment]
@bpoplauschi Fact: People just gonna keep ignoring ISSUE_TEMPLATE until Github enforces it. I'm telling you how I found out though. That's a secret. 😉

**Comment by mythodeia** [comment]
closing this. please reopen with all the necessary info filled in. thanks
