### ISSUE TITLE
Image scale out in UIButton imageview

### ISSUE THREAD

**Issue by geoffery009** [rs/SDWebImage#1815]
```
[[SDWebImageManager sharedManager] loadImageWithURL:myImageUrl options:SDWebImageRetryFailed progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) {
            
        } completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL) {
                NSLog([NSString stringWithFormat:@"%@",image.scale]);
                [myButton setImage:image forState:UIControlStateNormal];
        }];
```

Image name same as "image@2x.png",means that i want show in scale 2x screen ,and it scale out in UIButton when download it ,logout image scale value is 1.

How do i fix it in UIButton?

ps: now i have to combine UIImageView with UILabel instead of UIButton

**Comment by WangRuiChn** [comment]
I have the same problem in 3.8.2.

**Comment by skyline75489** [comment]
@geoffery009  Please fill in the issue template otherwise we wouldn't have enough information about issues like this.

**Comment by mythodeia** [comment]
closing this. please reopen with all the relevant info.
