### ISSUE TITLE
SDWebImageFromCacheOnly

### ISSUE THREAD

**Issue by futuretap** [rs/SDWebImage#1818]
I'd like to see a new SDWebImageOption to prevent any network activity for a given fetch. So I'd like to load the image only if it's already in the cache (disk or memory).

I used to implement this by checking with `-cachedImageExistsForURL:` first. However, since the synchronous variant of this call was removed in 4.0.0, it would be a nightmare to integrate this into my conditional logic now.

**Comment by skyline75489** [comment]
Just out of curiosity, when would we want to load image only if it's already in cache?

**Comment by futuretap** [comment]
My use case is a Spotlight indexer for POIs where I want to use a POI image if already fetched. Otherwise I use a default image to improve indexing performance and save network bandwidth.

**Comment by dreampiggy** [comment]
This sync version will be come back in 5.0 :) Maybe you can use that instead for check.

Currently, you can write a category to support this. Or if you only care about the image but not a value of bool or not, you can use the sync version API `-[SDImageCache imageFromCacheForKey:]`

```objective-c
@implementation SDImageCache (SDAdapter)

- (BOOL)sda_diskImageExistsWithKey:(NSString *)key
{
    BOOL exists = NO;
    
    // this is an exception to access the filemanager on another queue than ioQueue, but we are using the shared instance
    // from apple docs on NSFileManager: The methods of the shared NSFileManager object can be called from multiple threads safely.
    exists = [[NSFileManager defaultManager] fileExistsAtPath:[self defaultCachePathForKey:key]];
    
    // fallback because of https://github.com/rs/SDWebImage/pull/976 that added the extension to the disk file name
    // checking the key with and without the extension
    if (!exists) {
        exists = [[NSFileManager defaultManager] fileExistsAtPath:[[self defaultCachePathForKey:key] stringByDeletingPathExtension]];
    }
    
    return exists;
}

@end
```

**Comment by dreampiggy** [comment]
Do you consider using `shouldDownloadImageForURL:` delegate method in `SDWebImageManager` currentlly ?

Or if not, we can simply add one option to `SDWebImageOptions`. See #2186

**Comment by dreampiggy** [comment]
#2186 Merged. Availble on SD 4.3.0
