### ISSUE TITLE
cached UIImage has large byte size on disk

### ISSUE THREAD

**Issue by hashemp206** [rs/SDWebImage#1819]
I have an image url: 
[image](https://static.delino.com/Image/Restaurant/Cover/ga5wkcge.jc2_normal.jpg)

first I open this image with browser and save it on disk, image size is : **140 KB**
then I download and cache it with `SDWebImageCache`. I look up for it in app cache directory and its size is **449 KB**.

this huge difference comes from where? any idea?

this issue causes the app cache directory consume hundreds of megabytes on device disk.

<img width="523" alt="screen shot 2017-02-25 at 6 48 10 pm" src="https://cloud.githubusercontent.com/assets/3206748/23332232/8225c51e-fb8b-11e6-9a3d-a7ad158bc7eb.png">

**Comment by mythodeia** [comment]
i just tested the url you posted and i got the same size 140 kb in both situations. please check your code and see if you are doing anything else to the image.

![screenshot](https://cloud.githubusercontent.com/assets/1748458/23849077/bcfa760e-07e2-11e7-86c9-fc4dbab94b51.png)
