### ISSUE TITLE
Background disk clean up cause battery usage in background

### ISSUE THREAD

**Issue by paktree** [rs/SDWebImage#1822]
Hi,

Our app does not perform any background task; however, when we go to settings -> battery usage, we notice that our app is showing background usage. When we search through our code, we see that SDWebImage clearing disk during app background as a background task.

Is there a way to disable the background disk clean up? If so, what's the best alternative place to call disk cleanup?

Please advise! Thank you!

**Comment by skyline75489** [comment]
There seems to be no straight way to disable this feature. How long is the background usage are we talking about here? It shouldn't be very noticeable unless you have a large amount of cached files.

**Comment by paktree** [comment]
We are seeing something like for 8 minutes screen time of the app, it was running 2 minutes in background.

**Comment by mythodeia** [comment]
@paktree check if your cache is large in size like @skyline75489 suggested. 
Also do a test with fewer images e.g with the demo project and let us know if you still see significant background usage time.
closing this. please reopen when you have more info
