### ISSUE TITLE
How can I prevent cache from specific image?

### ISSUE THREAD

**Issue by IvanChan** [rs/SDWebImage#1823]
For example, I don't want to cache gif in memory, how could I achieve it?

Or, I don't want to cache big image in memory.

even more,  I download images a, b ,c, d, e, f, g, I don't want to cache c & e.

**Comment by mythodeia** [comment]
there is no direct way of doing this as far as i know but what you can do is on the completion block to erase that image from disk.

**Comment by IvanChan** [comment]
@mythodeia  no api found to erase that image from memory.

**Comment by edisongz** [comment]
@IvanChan  In SDImageCache,

`/**`
 `* Remove the image from memory and optionally disk cache asynchronously`
 `*`
 `* @param key      The unique image cache key`
 `* @param fromDisk Also remove cache entry from disk if YES`
 `*/`
`- (void)removeImageForKey:(NSString *)key fromDisk:(BOOL)fromDisk;`

**Comment by mythodeia** [comment]
thanks @edisongz
