### ISSUE TITLE
[Question] sd_setImage bliniking with collectionView

### ISSUE THREAD

**Issue by BBurzec** [rs/SDWebImage#1824]
Hi! I use latest version of SDWebImage and swift 3 with collection view and reusable cells my problem looks like this: 

I fill imageView inside collectionViewCell with custom image saved on device. When i received remote data with url to new image i try set image for cell using `cell.photoImageView.sd_setImage(with: URL(string: url))` it works but for 2-3 sec image view becomes white and next correct image is inserted. This case occurs only one time when i change cell image from my custom image to  webimage, rest work fine. 

fragment cellForRow: 
```
  if data.imageStoredLocally  {
                    let image = CacheManager.cachedImage(imageName)
                    cell.photoImageView.image = image
                } else  {
                    cell.photoImageView.sd_setImage(with: URL(string: url))
                }

```

**Comment by mythodeia** [comment]
please try and replicate with the demo project. if you can replicate this then please reopen
