### ISSUE TITLE
Being crashed in SDWebImageDownloaderOperation and SDWebImageDownloader

### ISSUE THREAD

**Issue by neeschal** [rs/SDWebImage#1827]
Being crashed in SDWebImageDownloaderOperation and SDWebImageDownloader

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
<img width="1352" alt="screen shot 2017-03-02 at 1 03 53 pm" src="https://cloud.githubusercontent.com/assets/4628552/23496896/bdfb564c-ff48-11e6-9d0f-bc8f20da8ec0.png">
<img width="1354" alt="screen shot 2017-03-02 at 1 04 05 pm" src="https://cloud.githubusercontent.com/assets/4628552/23496897/c0be9984-ff48-11e6-9719-6cf83bfd8889.png">

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iPhone 6 +
 Platform Version        |  9.3.4
 SDWebImage Version      |  3.8
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.2.1
 Repro rate              | sometimes 30% 
 Repro with our demo prj | nope
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by mythodeia** [comment]
does this happen with the latest version 4.0?

**Comment by mythodeia** [comment]
closing this. please reopen if you have more info

**Comment by huipengo** [comment]
![tmp58f4aafb](https://cloud.githubusercontent.com/assets/9402895/25698635/2b8fc29e-30f2-11e7-851b-3147bba9c70e.png)

hi, I also met it, how resolve ?

**Comment by mythodeia** [comment]
@huipengo which version of this library are you using?

**Comment by neeschal** [comment]
I have been using 'SDWebImage', '~>3.8'

**Comment by mythodeia** [comment]
@neeschal please update the library to the latest version and try again
