### ISSUE TITLE
SDWebimage Pod installation Error

### ISSUE THREAD

**Issue by rahulgupta6485** [rs/SDWebImage#1829]
Hi,

I am trying to install SDwebimage using cocoa Pods(pod 'SDWebImage', '~>3.8') but I am getting below Issue:- 

[!] Unable to satisfy the following requirements:

- `SDWebImage (~> 3.8)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SDWebImage (~> 3.8)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

Thanks

**Comment by skyline75489** [comment]
It's very clear that you should run `pod repo update`

**Comment by mythodeia** [comment]
closing this. please reopen if you need more info

**Comment by akshayAtDWI** [comment]
i am facing the same issue and pod repo update doesn't work for me.
