### ISSUE TITLE
I think the method(storeImage:imageData:forKey:toDisk:completion) should not be passed a nil value in SDWebImageManager.

### ISSUE THREAD

**Issue by flyingdog1** [rs/SDWebImage#1830]
It's a suggest personally.
I have a demand of getting a diskPath when completed block of loadImageWithURL:options:progress:completed: be called. So i can pass the diskPath to webView, in which way the webView has no need to redownload the image with its url.

But, your storeImage:withData:forKey:toDisk:completion method is async. Also With no completion block passed into in SDWebImageManager.  

See,SDWebimageManager Line:213 Line:220, all completion block were passed nil.

[self.imageCache storeImage:transformedImage imageData:(imageWasTransformed ? nil : downloadedData) forKey:key toDisk:cacheOnDisk completion:nil];
[self.imageCache storeImage:downloadedImage imageData:downloadedData forKey:key toDisk:cacheOnDisk completion:nil];

For easy, I just delete this: dispatch_async(self.ioQueue, ^{}; (Line: 220 of SDImageCache) to realize my demand. I'm testing my code, worrying about some mistake caused by my operation considering your concept of async download.

<img width="811" alt="async" src="https://cloud.githubusercontent.com/assets/23551803/23595223/30724310-025b-11e7-89df-47a6ab405a2b.png">
![Uploading mianThreadNeverBlocked.png…]()

I wonder if you can let users get the completion block of storeImage:withData:forKey:toDisk:completion. So my problem can be resolved.

Looking forward to your reply and suggestions of coders in GitHub.

**Comment by bpoplauschi** [comment]
@flyingdog1 there is another issue open on our project where we have discussed this (I can't find it now) :)  - you are right, but the problem there is we want to give the control back to the user as soon as possible, so the completion block of the `SDWebImageManager load*` is called right after we get the image - which sometimes is before the image is stored to disk. I don't see a good way to fix this, but I'm open to suggestions

**Comment by dreampiggy** [comment]
Dumplicated for #1301. So now we close it. If you find the solution in #1301 not suitable for this issue, maybe we can try to add a new SDWebImageOption for this use case(This use case looks really rare).
