### ISSUE TITLE
[Question] Last images not loading

### ISSUE THREAD

**Issue by JCarlosR** [rs/SDWebImage#1832]
### New Issue Checklist

* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 8.0
 SDWebImage Version      | 3.8.2
 Integration Method      | cocoapods
 Repro rate              | all the time

### Issue Description and Steps
I have several UIImageView's in a UITableView. 
The first images are loading well, but the images that appear after scrolling never load, and the placeholder is always shown.

I tried to use:

```
    let block: SDWebImageCompletionBlock = {(image, error, cacheType, imageURL) -> Void in
        categoriesTableView.reloadData()
    }
```
But within that block, the attributes of the class can't be used. So I can't use the ```categoriesTableView```reference.

There is some option parameter to always load **all** the images?
The ```sd_setImage``` is called for each image url, but it is not working for the images that are not shown initially.

Thank you in advance. Please give me some ideas.

**Comment by mythodeia** [comment]
can you replicate the problem with the demo project?

**Comment by JCarlosR** [comment]
@mythodeia The demo project is in Objective-C, right?

I am learning Swift but I have never used Objective-C.

I read that the images that are after scrolling are not loading because iOS stops the loading for performance.

So I am trying to avoid that and load all the images initially:
```
    public func tableView(_ tableView: UITableView, prefetchRowsAt indexPaths: [IndexPath]) {
        let urls = indexPaths.map { categories[$0.row].image }
        print(urls)
        SDWebImagePrefetcher.shared().prefetchURLs(urls)
    }
```

Only the latest images are not loading.
Can you give me some idea please?

**Comment by mythodeia** [comment]
just clone the demo project and try it on a device or the simulator. 
if the issue does not appear there then please check your code for anything that might be causing this. closing this for now. please reopen if you still encounter issues
