### ISSUE TITLE
WebImage instead SDWebImage

### ISSUE THREAD

**Issue by WE-St0r** [rs/SDWebImage#1833]
### New Issue Checklist

* [x ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.2
 SDWebImage Version      | 3.8.2
 Integration Method      | carthage
 Xcode Version           | Xcode 8.2
 Repro rate              | 100
 Repro with our demo prj | unknown
 Demo project link       |

### Issue Description and Steps

I create my own library which used SDWebImage. My library used CocoaPods and Carthage as package managers. If I install SDWebImage with CocoaPods, I need import SDWebImage, but install with Carthage, I need import WebImage. Why SDWebImage needs different import statements with different package manager?

**Comment by mythodeia** [comment]
check #1703 and #1691 
maybe you are using an older version? can you try with the latest one?

**Comment by WE-St0r** [comment]
I use SDWebImage v3.8.2 and now i need version with backward compatibility
