### ISSUE TITLE
URLOperations in SDWebImageDownloader visit by multithread without lock cause crash

### ISSUE THREAD

**Issue by wangqianzhou** [rs/SDWebImage#1835]
#URLOperations in SDWebImageDownloader visit by multithread without lock cause crash

### New Issue Checklist

* [ √ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ √ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ √ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 8.0
 SDWebImage Version      | 4.0.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.2
 Repro rate              | sometimes
 Repro with our demo prj | none
 Demo project link       | none

### Issue Description and Steps
![issuse](https://cloud.githubusercontent.com/assets/3773428/23883129/080669b0-08a0-11e7-98c9-f3609682209b.png)

**Comment by bpoplauschi** [comment]
Fixed by #1911
