### ISSUE TITLE
How can I use UIImageView to display gif images like version 3.xx in version 4.xx

### ISSUE THREAD

**Issue by eggswift** [rs/SDWebImage#1836]
It seems that this method:
``` objective-c
/**
 *  Compatibility method - creates an animated UIImage from an NSData, it will only contain the 1st frame image
 */
+ (UIImage *)sd_animatedGIFWithData:(NSData *)data;
```
Only return 1st frame image in it's `images`.

So, why do these changes? And how can I use UIImageView+SDWebImage to display gifs.

@bpoplauschi
@mythodeia
@harishkashyap

Please take a look. Thanks!

**Comment by bpoplauschi** [comment]
Conversation on #1575 since it has more visibility. Closing this one.
