### ISSUE TITLE
Problem when Validating and Uploading to app store with XCODE

### ISSUE THREAD

**Issue by pavlem** [rs/SDWebImage#1844]
Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 10.0
 SDWebImage Version      | e.g. 4.0.0
 Integration Method      | e.g. carthage 
 Xcode Version           | e.g. Xcode 8.2.1
 Repro rate              | e.g. all the time (100%) 

### Issue Description and Steps

I installed via Carthage the latest version and When I try to upload to app store or validate I get an error:
"This bundle Payload/Laptop Support.app/Framework/SDWebImage.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion"

I googled in Vain and only found

https://forums.developer.apple.com/thread/23778
http://stackoverflow.com/questions/21525124/error-itms-9000-this-bundle-is-invalid-apple-is-not-currently-accepting-appli

Can you please help me with this?

<img width="827" alt="screen shot 2017-03-27 at 9 19 07 pm" src="https://cloud.githubusercontent.com/assets/14887690/24377007/25866d02-133e-11e7-85a1-2d12ba1ad4c0.png">

**Comment by mythodeia** [comment]
this should already be resolved #1780 #1784

**Comment by danrudolf1** [comment]
I can confirm that this is still an issue in V 4.0.0
