### ISSUE TITLE
Wich version has support for [imageView sd_setShowActivityIndicatorView:YES]; [imageView sd_setIndicatorStyle:UIActivityIndicatorViewStyleGray];

### ISSUE THREAD

**Issue by cbedoy** [rs/SDWebImage#1845]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

**Comment by mythodeia** [comment]
did you try the latest version?i think in the demo project you can find what you are looking for.

**Comment by cbedoy** [comment]
Yes, I tried but I can available to import #import <SDWebImage/UIView+WebCache.h>

I was compiling with 3.8

**Comment by mythodeia** [comment]
the latest version is 4. try with that one
