### ISSUE TITLE
images not cached from this urls

### ISSUE THREAD

**Issue by AmeerChand** [rs/SDWebImage#1846]
thumbnail = ["http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-1.jpg","http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-2.jpg","http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-4.jpg","http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-6.jpg","http://www.nust.edu.pk/PublishingImages/pdc-apr17-ws-7.jpg"]

This is an array of url .
i am unable to get image just get placeholderimage.

imageV.sd_setImage(with: url, placeholderImage: imgFullView.image)

**Comment by mythodeia** [comment]
did you try the urls in the demo project? what version are you using?have you setup ATS in your plist?

**Comment by AmeerChand** [comment]
i don't about ATS.
i send you Array of images.
can you make a try to check these.

Thanks.

**Comment by mythodeia** [comment]
please check the demo project and test the images there. i am closing the issue for now. if you still encounter issues after you tested with the demo project please let me know.

**Comment by AmeerChand** [comment]
i download form https://github.com/rs/SDWebImage
i tried my best to solve this issue but i can't.

The whole issue is in Attachment.

**Comment by mythodeia** [comment]
please clone the repository using ```git clone --recursive https://github.com/rs/SDWebImage.git``` and then open the demo project, remove the demo urls and add your own. Run the project in a simulator or device and let me know if the images appear in the tableview

**Comment by AmeerChand** [comment]
still error.
i already Tried this command

**Comment by mythodeia** [comment]
whats the error you are getting when you git clone the repository in your terminal?

**Comment by mythodeia** [comment]
i tried it just now and the repository cloned just fine. 
i also tried the image urls you posted in the demo project just now and all appear in the tableview. See screenshot. Please check the options in my 1st post.

![screenshot](https://cloud.githubusercontent.com/assets/1748458/24492303/97a01676-1533-11e7-97b1-de59b9b4ca37.png)

**Comment by AmeerChand** [comment]
destination path 'SDWebImage' already exists and is not an empty directory

**Comment by mythodeia** [comment]
this means you already have SDWebimage in the destination folder you cloned it to. As you can see from my previous post the images appear just fine.

**Comment by AmeerChand** [comment]
why i am getting this one error

**Comment by mythodeia** [comment]
as i have told you in my previous post you already have this library downloaded in your destination folder where you are trying to clone it to. i am sorry i cannot provide more info since i just tested the urls and they seem to work fine. please check your code

**Comment by AmeerChand** [comment]
i saw that you have done this.
but why i am getting this error.

can you assist me on this problem?

**Comment by mythodeia** [comment]
please check my comment. the error you posted ```destination path 'SDWebImage' already exists and is not an empty directory``` means that you might already have this library downloaded in your destination folder where you are trying to clone it to

**Comment by AmeerChand** [comment]
![error](https://cloud.githubusercontent.com/assets/26761721/24500147/b68c17d6-155d-11e7-936b-49a52da5d44f.png)

i know it's worked well in  your device.
as you above show Image thats well.
but why i am getting still same issue?

i will be very thank full.

**Comment by mythodeia** [comment]
its not an issue with the library. 
you are trying to download the library and the library is already downloaded in your desktop. please remove the library from your desktop and run the command again. Also close the demo project before doing all that.

**Comment by AmeerChand** [comment]
ok. i admit this is not issue of library.
 The issue is 
Apple LLVM 8.0 error.
No Input file.
what are these error??

**Comment by mythodeia** [comment]
if you read the whole error you will see that it tries to find a missing file. this means that the repository has not been cloned correctly and some files are missing

**Comment by AmeerChand** [comment]
can you send me link of demo account excluding Github.

i tried alot but i can't solve this error.

i tried many to download from Github.
but unable to solve LLVM 8.0 error.

**Comment by mythodeia** [comment]
send me your email address so i can send you a weTransfer link

**Comment by AmeerChand** [comment]
ameerchand11@gmail.com

**Comment by mythodeia** [comment]
use the link in my post above

**Comment by AmeerChand** [comment]
![screen shot 2017-03-30 at 7 29 54 pm](https://cloud.githubusercontent.com/assets/26761721/24537794/65874c10-15fe-11e7-97a3-79dc87ddeffb.png)
![screen shot 2017-03-30 at 7 35 12 pm](https://cloud.githubusercontent.com/assets/26761721/24537793/6583ff42-15fe-11e7-82b5-ef14ab6ff48b.png)

**Comment by mythodeia** [comment]
did you use the same image urls you posted above?

**Comment by AmeerChand** [comment]
yes
