### ISSUE TITLE
SDWebImageManager.m crash at line 67 

### ISSUE THREAD

**Issue by ywqqqqq** [rs/SDWebImage#1848]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.2.1
 SDWebImage Version      | 3.8.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.2.1
 Repro rate              | only once
 Repro with our demo prj | no
 Demo project link       | null

### Issue Description and Steps

I got crash report from fabric that crash happened in a tableView with two types of cell , single pic cell and two pics cell. But I have no idea how to reproduce the bug. Have somebody worked it arround? I need help.

fabric: http://crashes.to/s/a3d1e62699a

Refer to [#1583](https://github.com/rs/SDWebImage/issues/1583)
I check the method "- cacheKeyForURL: " and the fixed code have existed, so I think it's not the same issue.

    - (NSString *)cacheKeyForURL:(NSURL *)url {
        if (!url) {
            return @"";
        }
    
        if (self.cacheKeyFilter) {
            return self.cacheKeyFilter(url);
        } else {
            if (NSClassFromString(@"NSURLComponents") && [NSURLComponents 
    instancesRespondToSelector:@selector(string)]) {
                NSURLComponents *urlComponents = [[NSURLComponents alloc] initWithURL:url 
    resolvingAgainstBaseURL:NO];
                urlComponents.query = nil; // Strip out query parameters.
                return [urlComponents.URL absoluteString];
            } else {
                return [url absoluteString];
            }
        }
    }

**Comment by bpoplauschi** [comment]
Please upgrade, as this issue was fixed. You can upgrade to 3.8.2 if you want to avoid migrating the code using our library, but I recommend our latest version 4.0.0 (which is a major update and requires some migration on your code).
