### ISSUE TITLE
Can't show image for special HTTPS 

### ISSUE THREAD

**Issue by Asution** [rs/SDWebImage#1850]
https://dn-youplus-app2.qbox.me/o_1bck0nfjb29rbitku01s8k1q3ec.jpg

This image I can't show in my ImageView, But another HTTPS URL can show, I don't know why.

**Comment by mythodeia** [comment]
can you test this url in the demo project?

**Comment by Asution** [comment]
I know now~ it's my sdwebimage version is not new. OMG!   My version is '3.7.3' , It can't load this URL, but the new version can load. Thanks bro!

**Comment by mythodeia** [comment]
👍
