### ISSUE TITLE
why is dispatch_barrier_sync instead of dispatch_barrier_async in addProgressCallback:andCompletedBlock:forURL:createCallback?

### ISSUE THREAD

**Issue by g-enius** [rs/SDWebImage#1852]
Could anyone help me explain why the author use dispatch_barrier_sync instead of dispatch_barrier_async in the line 186 of SDWebImageDownloader.m (addProgressCallback:andCompletedBlock:forURL:createCallback) ?

Because actually these codes are running on main thread as a fact of system optimization and there are not other codes wait to execute and variables to return.

**Comment by bpoplauschi** [comment]
I haven't written that code, but I assume it's because we need to return `token` which is created on the `barrierQueue`. Mutating `URLOperations` is not thread safe, so we are synchronizing the that using the `barrierQueue`.

**Comment by g-enius** [comment]
Thank you for the reply, but I think that's not the function I was asking for. In latest code of "addProgressCallback: completedBlock: forURL: createCallback", there is really a token need to be returned. but I was asking "addProgressCallback:andCompletedBlock:forURL:createCallback", which maybe has been deleted. I paste the following code in version 3.7.1, there was no token to return or code wait to execute.

- (void)addProgressCallback:(SDWebImageDownloaderProgressBlock)progressBlock andCompletedBlock:(SDWebImageDownloaderCompletedBlock)completedBlock forURL:(NSURL *)url createCallback:(SDWebImageNoParamsBlock)createCallback {
    // The URL will be used as the key to the callbacks dictionary so it cannot be nil. If it is nil immediately call the completed block with no image or data.
    if (url == nil) {
        if (completedBlock != nil) {
            completedBlock(nil, nil, nil, NO);
        }
        return;
    }

    dispatch_barrier_sync(self.barrierQueue, ^{
        BOOL first = NO;
        if (!self.URLCallbacks[url]) {
            self.URLCallbacks[url] = [NSMutableArray new];
            first = YES;
        }

        // Handle single download of simultaneous download request for the same URL
        NSMutableArray *callbacksForURL = self.URLCallbacks[url];
        NSMutableDictionary *callbacks = [NSMutableDictionary new];
        if (progressBlock) callbacks[kProgressCallbackKey] = [progressBlock copy];
        if (completedBlock) callbacks[kCompletedCallbackKey] = [completedBlock copy];
        [callbacksForURL addObject:callbacks];
        self.URLCallbacks[url] = callbacksForURL;

        if (first) {
            createCallback();
        }
    });
}

**Comment by bpoplauschi** [comment]
I don't know the details of that code in particular, but it's probably synchronizing the whole operation.
