### ISSUE TITLE
Heif support ?

### ISSUE THREAD

**Issue by tirrorex** [rs/SDWebImage#1853]
Since it seems SDWebImage supports webP i was wondering if there was a way to support heif format which is superior to webP in every way?
If so could you point me on ressources that will help me do that?
Thank you

**Comment by mythodeia** [comment]
are you referring to [this](https://github.com/nokiatech/heif)?

**Comment by tirrorex** [comment]
Yes, precisely this

**Comment by mythodeia** [comment]
more info on js implementation [here](https://github.com/nokiatech/heif/wiki/IV.-HEIF-Reader-JavaScript-Implementation)

**Comment by tirrorex** [comment]
Sorry i don't get why you are linking something about a javascript reader.

**Comment by mythodeia** [comment]
you asked for resources on implementing heic support. i linked the js library that reads these kind of images so you can check the code and whats needed.

**Comment by tirrorex** [comment]
Oh i get it, implement it myself :)
Guess it makes sense, thanks

**Comment by mythodeia** [comment]
As i see it, implementing heic support will surely need time and lots of tests. 
Most of the collaborators here spend their free time supporting this library and we could always need some help with new features/bugs etc. If you want to support this library you can always send a pull request and we will be happy to check it out. 
👍

**Comment by bpoplauschi** [comment]
@tirrorex it is better to keep things separated. So in my opinion, creating a project/lib to deal with the `HEIF` format makes a lot of sense, because all the stuff related to `HEIF` will be there (code, issues, ...). The scope of SDWebImage is to handle download and caching of images. 
If you look at the way we support `WebP` format, we just plug-in the support from `libwebp` which is a library from Google that handles exactly this file format.

**Comment by bpoplauschi** [comment]
Good luck

**Comment by tirrorex** [comment]
Thanks, will update if and when i have issues to plug my framework, keep up the good work :)

**Comment by tirrorex** [comment]
bumping this, since ios 11 will support heif out of the box, is this now in the roadmap for swift 4 version of the framework?

**Comment by dreampiggy** [comment]
Wait for iOS11 SDK final release and to check the usage of HEIF image format. After that we can consider this feature. 😪

**Comment by bpoplauschi** [comment]
Fixed by #2080
