### ISSUE TITLE
SDWebImageDownloaderProgressBlock

### ISSUE THREAD

**Issue by JxbSir** [rs/SDWebImage#1854]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.3
 SDWebImage Version      | 3.8.2
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 8.3
 Repro rate              | all the time (100%) 
 Repro with our demo prj | yes
 Demo project link       | null

### Issue Description and Steps

How can I get the received data in SDWebImageDownloaderProgressBlock?
The picture in our server which support interlace, so I want to get the received data.

**Comment by mythodeia** [comment]
the ```SDWebImageDownloaderProgressBlock ``` sends back progress related info ```NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL```
i do not think there is a way to get the data from there.
However ```SDWebImageDownloaderCompletedBlock``` this sends back ```UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, BOOL finished``` so i think you can use this to get the data.
