### ISSUE TITLE
Internet address errors or incorrect images, waiting for the loading pictures don't show

### ISSUE THREAD

**Issue by taojeff** [rs/SDWebImage#1855]
Internet address errors or incorrect images, waiting for the loading pictures don't show

**Comment by mythodeia** [comment]
please be a little more specific with the issue you are having. can you replicate it on the demo project? please conform with the [ISSUE TEMPLATE](https://github.com/rs/SDWebImage/blob/master/.github/ISSUE_TEMPLATE.md)
