### ISSUE TITLE
Using RefreshCached but getting wrong images

### ISSUE THREAD

**Issue by liuliangju** [rs/SDWebImage#1861]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS 
 Platform Version        | 10.3
 SDWebImage Version      | 4.0.0
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 8.3.1
 Repro rate              |  all the time (100%) 
 Repro with our demo prj | YES
 Demo project link       | null

### Issue Description and Steps
In your demo DetailViewController.m  I change options with SDWebImageRefreshCached i find that still get old images 

``` objc
- (void)configureView {
    if (self.imageURL) {
        __block UIActivityIndicatorView *activityIndicator;
        __weak UIImageView *weakImageView = self.imageView;
        [self.imageView sd_setImageWithURL:self.imageURL
                          placeholderImage:nil
                                   options:SDWebImageRefreshCached
                                  progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL *targetURL) {
                                      if (!activityIndicator) {
                                          [weakImageView addSubview:activityIndicator = [UIActivityIndicatorView.alloc initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray]];
                                          activityIndicator.center = weakImageView.center;
                                          [activityIndicator startAnimating];
                                      }
                                  }
                                 completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
                                     [activityIndicator removeFromSuperview];
                                     activityIndicator = nil;
                                 }];
    }
}
```

<img width="774" alt="1" src="https://cloud.githubusercontent.com/assets/21209545/24847004/c52b7048-1df0-11e7-8b7a-51fdb8113b9e.png"><br>
<img width="768" alt="2" src="https://cloud.githubusercontent.com/assets/21209545/24847009/ce6d2e58-1df0-11e7-9fe8-18c6654aaaa2.png">

same to #1818

**Comment by mythodeia** [comment]
the images you uploaded are not working. can you please conform to the [ISSUE_TEMPLATE](../blob/master/.github/ISSUE_TEMPLATE.md) on this project?

**Comment by liuliangju** [comment]
@mythodeia 
In line 175 completed  the downloadedImage or downloadedData  is nil but finished is YES, there is anything wrong?

**Comment by rushabh55** [comment]
This has happened to me too

**Comment by SimonCY** [comment]
When I use SDWebImageRefreshCached as the  option key in a viewcontroller,  it worked in the first time, but in second time  I open the viewcontroller ,the imageView showed nothing, the url is still right.

**Comment by bpoplauschi** [comment]
@dreampiggy I think our latest 4.1.1 changes will fix this issue as well. What do you think?

**Comment by dreampiggy** [comment]
@bpoplauschi SD 4.1.1 now use that NSData to compare the response data with cache data, If the data is same it will never call twice. Previously we use a little hack code to detect whether the image data is from NSURLCache or download from the server, but it not really accurate. I think this one is better.

**Comment by dreampiggy** [comment]
@bpoplauschi SD 4.1.1 now use that NSData to compare the response data with cache data, If the data is same it will never call twice. Previously we use a little hack code to detect whether the image data is from NSURLCache or download from the server, but it's not really accurate. I think this one is better.

**Comment by dreampiggy** [comment]
@SimonCY Sorry. This is a bug introduced during SD4.1 and will be fixed in SD4.1.1

**Comment by bpoplauschi** [comment]
Thanks @dreampiggy
