### ISSUE TITLE
Download image failed NSURLErrorDomain Code=-999

### ISSUE THREAD

**Issue by ringlong** [rs/SDWebImage#1862]
### New Issue Checklist

* [x ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 8.0
 SDWebImage Version      |  3.8.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.3
 Repro rate              | all the time (100%) 

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

My image url is http://image.bitautoimg.com/wapimg-1536-757/appimage/cms/20170411/w750_h370_c97787f5a8df4a00b1cbee3bd7e92842.jpg , it successed to use this url.
 Then I used ip(`42.62.1.150`,  `ping  image.bitautoimg.com`) to request and set host to `image.bitautoimg.com`. Like this
```
http://42.62.1.150/wapimg-1536-757/appimage/cms/20170411/w1530_h755_63fad0b70d67492ba339d90240ea4c24.jpg
GET /wapimg-1536-757/appimage/cms/20170411/w1530_h755_63fad0b70d67492ba339d90240ea4c24.jpg HTTP/1.1
Host	image.bitautoimg.com
Accept	image/webp,image/*;q=0.8
User-Agent	qichehui/8.1.1 CFNetwork/711.1.12 Darwin/14.0.0
Accept-Language	zh-cn
Accept-Encoding	gzip, deflate
Connection	keep-alive
```
It successed in iPhone but faild in iPad, reported this
```
Error Domain=NSURLErrorDomain Code=-999 "已取消" UserInfo=0x17966bc00 {NSErrorFailingURLKey=http://42.62.1.150/wapimg-1536-757/appimage/cms/20170411/w750_h370_c97787f5a8df4a00b1cbee3bd7e92842.jpg, NSLocalizedDescription=已取消, NSErrorFailingURLStringKey=http://42.62.1.150/wapimg-1536-757/appimage/cms/20170411/w750_h370_c97787f5a8df4a00b1cbee3bd7e92842.jpg}
```

**Comment by mythodeia** [comment]
can you try the same url in the demo project using an iPad?

**Comment by Shanti-SR** [comment]
I have the same problem.
* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.3
 SDWebImage Version      | 3.8.2
 Integration Method      | cocoapods
 Xcode Version           | 8.3.1
 Repro rate              | all the time (100%)
 Demo project link       | https://github.com/Shanti-SR/test-SDWebImage

### Issue Description and Steps

My image url is https://api.emscloud.eu/uploads/5900577fc910e 
From a web browser I can download the image but from SDWebImage I can not and I get the following error:

```Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://api.emscloud.eu/uploads/5900577fc910e, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=https://api.emscloud.eu/uploads/5900577fc910e}```

My  setup ATS:
```<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>``

**Comment by mythodeia** [comment]
@Shanti-SR i just tested your url with the demo project and the latest version and it works just fine.

**Comment by Shanti-SR** [comment]
@mythodeia thank you very much.
