### ISSUE TITLE
Progress Indicator Issue

### ISSUE THREAD

**Issue by magonicolas** [rs/SDWebImage#1866]
Hi, Im trying to add a progress indicator for my image download, but When I write: imageView.sd_setShowActivityIndicatorView(true)
imageView.sd_setIndicatorStyle(.Gray)
 
Says that UImage doesn't have a sd_setShow.... Member. and the same with sd_setIndica...

Bests!

**Comment by mythodeia** [comment]
can you please conform to the [ISSUE_TEMPLATE](../blob/master/.github/ISSUE_TEMPLATE.md) on this project?
which version are you using? please download the latest version.

**Comment by bpoplauschi** [comment]
@magonicolas look at the headers of SDWebImage from the version you have installed and they will show you what the methods signatures are.
Also, we recommend that you upgrade to the latest version (where indeed you can use the code you pasted).
