### ISSUE TITLE
Version Rejected by Apple due to Image no show In ipv6 network

### ISSUE THREAD

**Issue by 03128crz** [rs/SDWebImage#1867]
### Issue Info
 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 10.3.1
 SDWebImage Version      | 4.0.0

### Issue Description and Steps

Hi, I came for China and my app main page content showing image through API data. Now the API request quickly and return image data for showing. But SDWebImage loading image very slow. What wrong?

API and image in the same server.

PS:  App reply:
We discovered one or more bugs in your app when reviewed on iPad running iOS 10.3.1 on Wi-Fi connected to an IPv6 network.

The app could not load content in the main page.

Please see attached screenshots for details

**Comment by mythodeia** [comment]
have you setup ATS correctly in your plist?

**Comment by 03128crz** [comment]
@mythodeia yes, Testing is ok

**Comment by mythodeia** [comment]
The reply from Apple states that "the app could not load content on the main page". What is your main page? Do you load images? Is there any way that the images could not be loaded because of a server side problem?

**Comment by gpluscat** [comment]
@03128crz 你现在解决了吗？我现遇到你的问题

**Comment by bpoplauschi** [comment]
Guys, I'm pretty sure SDWebImage does not cause this issue. Thousands apps use it and don't have issues at submission (including a few I saw with my own eyes). There must be something with your own setup (app or server).
