### ISSUE TITLE
SDWebImagePrefetcher: Ambiguous reference to member 'prefetchURLs'

### ISSUE THREAD

**Issue by liruqi** [rs/SDWebImage#1868]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.3.1
 SDWebImage Version      | SDWebImage/GIF (4.0.0)

### Issue Description and Steps
Swift project build error:
SDWebImagePrefetcher: Ambiguous reference to member 'prefetchURLs'

I suggest to replace `SDWebImagePrefetcher` `prefetchURLs` property with `fetchURLs` or `queuedURLs`, to avoid naming collision in Swift.

**Comment by bpoplauschi** [comment]
@liruqi are you interested in making a pull request with this change?

**Comment by dreampiggy** [comment]
Which of Swift version your project build? I tried Swift 3 with SDWebImage/GIF and it works well.
