### ISSUE TITLE
Can't customize NSURLSessionConfiguration used by session in `sharedDownloader`/`sharedManager`

### ISSUE THREAD

**Issue by Westacular** [rs/SDWebImage#1870]
We have a requirement that the `networkServiceType` used in an app be `NSURLNetworkServiceTypeBackground`.

It seems straightforward enough to just specify that in the NSURLSessionConfiguration used to initialize the SDWebImageDownloader, however:

- `[SDWebImageDownloader sharedDownloader]` is hardcoded to use `defaultSessionConfiguration`
- `[SDWebImageManager sharedManager]` is hardcoded to use `sharedDownloader`
- Consequently, in order to make this one small customization, we'll be forced to create our own separate SDWebImageDownloader and SDWebImageManager instances, and can't use the UIKit extensions, which all reference `[SDWebImageManager sharedManager]`.

Proposals:

- Make SDWebImageManager's `imageDownloader` property publicly `readwrite`. It's privately readwrite in SDWebImageManager (unnecessarily so: the only assignment there uses the ivar directly) and the only thing that could break by reassigning it later is the cancelling of current download operations; documentation could make explicit that it should not be changed when there are active operations.
- Eliminate `[SDWebImageDownloader sharedDownloader]` and `[SDImageCache sharedImageCache]` in favour of always referencing the corresponding properties of `[SDWebImageManager sharedManager]`. (As it stands, the only reference to sharedDownloader inside SDWebImage itself is where it's used in the init of SDWebImageManager)

For our specific problem, this would let us solve it by creating our own SDWebImageDownloader instance and assigning that to sharedManager's imageDownloader in our app startup.

Alternately:
- a way to assign sharedManager, or
- allow a manager created _before_ sharedManager is called to automatically be the sharedManager instance.

**Comment by bpoplauschi** [comment]
@Westacular I agree about the interface not being open here.
Let's fix that, but let's also keep backwards compatibility - we don't want to break a lot of our users' code.
- We can expose the `sessionConfiguration` or if that opens potential problems, add a method to be able to set a new `sessionConfiguration` (where we can also create a new `NSURLSession`).
- I would not change the `shared` objects that are heavily used

Are you interested in creating a PR?

**Comment by Westacular** [comment]
Fair enough.

According to `NSURLSession` documentation,
> Changing mutable values within the configuration object has no effect on the current session, but you can create a new session with the modified configuration object.

So I think what would make sense is to expose a readwrite computed `sessionConfiguration` property, where
- the getter just returns `self.session.configuration`
- the setter calls `finishTasksAndInvalidate` on the current self.session and creates a new one with the specified configuration to replace it.

I can go ahead an create a PR with this change.

**Comment by bpoplauschi** [comment]
Sounds good, thanks

**Comment by bpoplauschi** [comment]
#1891 was merged - closing this
