### ISSUE TITLE
broken image

### ISSUE THREAD

**Issue by tigerZhang86** [rs/SDWebImage#1872]
I set image for my UIImageView using following code

- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder completed:(SDWebImageCompletionBlock)completedBlock;

Sometime i got broken image like this:
![img_0073](https://cloud.githubusercontent.com/assets/8126502/25324430/656f7ba0-28f8-11e7-83ec-a046f641f6ad.PNG)

**Comment by mythodeia** [comment]
can you share the image url that produces this broken image?

**Comment by tigerZhang86** [comment]
@mythodeia  
This is image url that produces this broken image :
https://www.vlor.net/airing/o/files?fileId=58dddc36165b0dab74c395bb

**Comment by mythodeia** [comment]
have you tried this with the demo project and the latest version of this library?

**Comment by mythodeia** [comment]
i just tried it myself on the simulator and it seems to be working just fine.
