### ISSUE TITLE
Create thumbnail from video URL

### ISSUE THREAD

**Issue by AbhishekChourasia16690** [rs/SDWebImage#1873]
Hello,

Thank you for the amazing library you made. Can I have the below feature:

-Create thumbnail from video URL.

Thanks.

**Comment by AbhishekChourasia16690** [comment]
Hey,

When can we have that feature. I have code for creating thubnail from video url.

Thanks.

**Comment by mythodeia** [comment]
@AbhishekChourasia16690 if you want you can create a pull request and we will check it out

**Comment by bpoplauschi** [comment]
@AbhishekChourasia16690 I don't think creating a thumbnail from a video or any video related features are in scope of our library. We only handle images download and caching. Please look at other libraries that might be doing that (https://cocoapods.org/?q=video), or, you can start a new project with this scope.
