### ISSUE TITLE
[Feature] Decouple view categories from fetching of images

### ISSUE THREAD

**Issue by younata** [rs/SDWebImage#1874]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

n/a (Current)

### Issue Description and Steps

For all sorts of reasons (testability, [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle), I have strong opinions about MVC), I would like to decouple the downloading and caching part of SDWebImage from the category on UIImageView part of SDWebImage.

This feature request would manifest as the domain logic for the `-sd_setImage:[...]` category methods on UIView/UIImageView/UIButton/etc being moved to a separate object (Maybe an `SDWebImageFetcher`?), which I can then new up and use wherever I want. Then, the various `-sd_setImage:[...]` calls would just use an `SDWebImageFetcher` to do their duties, while I feel nice knowing that my views are dumb and my controllers can handle actually fetching the data.

Note that most of the work involved is handled by SDWebImageManager, with the exception of the correct thread handling, error handling, basically, the entire implementation of [`-sd_internalSetImageWithURL:placeholderImage:options:operationKey:setImageBlock:progress:completed:`](https://github.com/rs/SDWebImage/blob/master/SDWebImage/UIView%2BWebCache.m#L30-L91), and the methods called from it.

Essentially:

I want an object NOT UIImageView/UIButton/MKAnnotationView/UIView that I can call something like `-fetchImage:completionHandler:` with a NSURL and a completion block that'll handle downloading/caching as well as threading translation and such so that I can handle placing the image on the desired view.

**Comment by bpoplauschi** [comment]
@younata I see. I recently moved all that logic inside the `UIView` category so it's not duplicated with every `UIView`. But we can take one step further and separate it into a new component and some leftover UI code that will remain in `UIView` category.
Are you interested in making a PR?

**Comment by dreampiggy** [comment]
So....Actually I think current design is correct. Most of the property using in View Category is tied to `UIView`. So if your custom instance even is not a `UIView` subclass, most logic for this is really useless. (You don't need image indicator, image transition and many other feature we add).

So, why don't use just use `SDWebImageManager loadImageWithURL:` ? In 5.x we also provide the same `context` arg acrossing the View Category to Manager. You can build you logic without not much code.
