### ISSUE TITLE
sdwebimage4.0 支持ipv6吗？

### ISSUE THREAD

**Issue by gpluscat** [rs/SDWebImage#1875]
为什么我上传app store，被拒了，Guideline 2.1 - Performance，求解决

Guideline 2.1 - Performance

We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 10.3.1 on Wi-Fi connected to an IPv6 network.

Specifically, your app still did not respond to tap on any 拼图 in app. Additionally, same kitten puzzles were listed in app.

Please see attached screenshots for details.

Next Steps

To resolve this issue, please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify any issues, then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue. For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue.

Resources

For information about supporting IPv6 Networks, please review Supporting IPv6 DNS64/NAT64 Networks and About Networking.

**Comment by mythodeia** [comment]
version 4 supports ipv6. also here https://github.com/rs/SDWebImage/issues/1566

**Comment by writer0713** [comment]
@gpluscat do you think others can understand chinese question? 怎么直接写中文呢。。？

**Comment by bpoplauschi** [comment]
As I commented on #1867 
> Guys, I'm pretty sure SDWebImage does not cause this issue. Thousands apps use it and don't have issues at submission (including a few I saw with my own eyes). There must be something with your own setup (app or server).

**Comment by mythodeia** [comment]
closing this
