### ISSUE TITLE
fatal: reference is not a tree: 3d97bb75144147e47db278ec76e5e70c6b2243db

### ISSUE THREAD

**Issue by kurostyle5** [rs/SDWebImage#1882]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.3.1
 SDWebImage Version      | 4.0.0
 Integration Method      | carthage
 Xcode Version           | Xcode 8.3.1
 Repro rate              | all the time (100%) 
 Repro with our demo prj | 100%

### Issue Description and Steps
I'm getting this error when I update with Carthage for iOS.  It happens with tag 4.0.0 and master.
```
A shell task (/usr/bin/env git checkout --quiet 3d97bb75144147e47db278ec76e5e70c6b2243db) failed with exit code 128:
fatal: reference is not a tree: 3d97bb75144147e47db278ec76e5e70c6b2243db 
```

**Comment by rileygelwicks** [comment]
Can confirm I am also getting this when running carthage.

**Comment by ThorinHanson** [comment]
Same issue

**Comment by evliu** [comment]
ditto

**Comment by bpoplauschi** [comment]
It should be fixed now, Google reverted this change.
