### ISSUE TITLE
loosing scale after cache reload

### ISSUE THREAD

**Issue by tirrorex** [rs/SDWebImage#1884]
### Issue Info

 Platform Name           ios
 Platform Version        10.1
 SDWebImage Version      3.8.2
 Integration Method      cocoapods
 Xcode Version           Xcode 7.3.1
 Repro rate             all the time (100%)

### Issue Description and Steps

I implemented a custom cache allowing me to cache both the original image and the modified version, this way i can avoid downloading the same image again.
So i eventually store the modified image, setting the image to my imageView, working great, scale of the image is the scale of my device (currently iphone 7+ so 3.0).

Problem is when i kill the app and reloading it thus reloading the cache, the images i fetch from my cache are now recognized as images with a scale of 1.0, the system will then upscale those images destroying all my layout.

I bumped into some issues related to this and i am not sure which path i should follow.
Apparently i am supposed to precize the scale of my device somehow when i am storing the image into cache.

In order to be able to store both original and modified image i am modifying the url, happending a custom string to it, should i happen the scale of the device too?
This is not clear for me.

I store the images simply : 

    `        let imageCache = SDImageCache.sharedImageCache() 
     imageCache.storeImage(modifiedImage, forKey: modifiedImageKey!)`

and i retrieve the modified image with this : 
`guard let image = imageCache.imageFromDiskCacheForKey(imageKey) else { return } `

I thought using optionnal parameters for the image will allow me to bypass this but no, using 
    `                       imageCache.storeImage(image, recalculateFromImage: false, imageData: nil, forKey: originalImageKey, toDisk: true)`
isn't working in this case. (I may have misunderstood the purpose of recalculateFromImage)

After some additionnal testing and breakpoints added into SDWebImageCompat it would seem that the 3x image will be upscale and then store at 1x?
What i don't get is why it doesn't affect images with a height constraint on imageview.
In this specific case, the images are resized to fit screen width according to their height.
They are displaying in an imageView with a content mode set to ScaleToFill which is in turn inside a scrollView

My current workaround is to implement scaling in my set method : 
    `private static func setImageWithAnimation(imageView: UIImageView, image: UIImage) {
      
      // set image to imageView with animation
        UIView.transitionWithView(imageView, duration: 0.2, options: .TransitionCrossDissolve, animations: {

            let screenScale = UIScreen.mainScreen().scale
            if image.scale != screenScale {
                let scaledImage = UIImage(CGImage: image.CGImage!, scale: screenScale, orientation: image.imageOrientation)
                imageView.image = scaledImage
            } else {
                imageView.image = image
            }
            }, completion: nil)
    }`

But if it can be deal with natively by SDWebImage that would be great

possible reference to #576

**Comment by dreampiggy** [comment]
Because your `modifiedImageKey` isn't follow the scale format. See `SDScaledImageForKey`. You should have either `@2x.` or `@3x.` to preserve the scale.

And also, I don't know whether SD 3.x has some extra logic for this. You can also try to upgrade to SD 4.x and have a check

**Comment by dreampiggy** [comment]
Maybe in 4.x we have no ways to change (Since `SDWebImageOptions` is a Objective-C enum, which can only represent bool value :))

In 5.x, we can. See #2266

**Comment by dreampiggy** [comment]
In 5.x, you can use `SDWebImageContextImageScaleFactor` to specify the scale factor you desired. It works from View Category, Downloader, Cache and Coder. So this PR can be closed now. Wait for 5.0.0 release. :)
