### ISSUE TITLE
Project with SDWebImage won't compile

### ISSUE THREAD

**Issue by MiguelArber** [rs/SDWebImage#1886]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.3.1
 SDWebImage Version      |  3.7.6
 Integration Method      | manually
 Xcode Version           | Xcode 8.3.2
 Repro rate              | all the time (100%)
 Repro with our demo prj | Looks like it compiles OK but it doesn't open up in the simulator nor in my iPhone
 Demo project link       | e.g. -

### Issue Description and Steps

At compiling it shows a message saying SDWebImage/Vendors/libwebp/examples/tiffdec.h:15:10: 'webp/types.h' file not found. I downloaded the project from github using the recursive clone method even tho I'm not sure if I might be missing any file. Thanks for your help!

**Comment by bpoplauschi** [comment]
You need to clone recursive, so git will also bring `libwebp`. Check out https://github.com/rs/SDWebImage/blob/master/Docs/ManualInstallation.md which explicitly says `git clone --recursive https://github.com/rs/SDWebImage.git`

**Comment by MiguelArber** [comment]
Sure, as I stated above I cloned the project recursively using coping and pasting the line from the ManualInstallation, but it just won't work. I did it several times with the same result... :/

**Comment by bpoplauschi** [comment]
@MiguelArber there was a downtime for the libwebp clone on Github, which is not handled by our group. Now it's back, so that probably explained why it didn't work at first, but now works again.
