### ISSUE TITLE
Memory Size of memCache? 

### ISSUE THREAD

**Issue by ankitkapasi** [rs/SDWebImage#1890]
I see that I can easily get the size of the diskspace, but I was wondering if I can do the same for the memCache?

Thanks!

**Comment by bpoplauschi** [comment]
@ankitkapasi Here's the situation: we are using `NSCache` inside `SDImageCache` for the memory cache. This doesn't expose a valid mechanism for the total size of the cache and more than that, it has the liberty to evict the objects from that cache depending on the system status, so I wouldn't rely on that.
