### ISSUE TITLE
GIF podspec deployment_target error

### ISSUE THREAD

**Issue by zhungxd** [rs/SDWebImage#1892]
subspec GIF requires iOS 8+,but the podspec deployment_target is 

`  gif.ios.deployment_target = '7.0'`

it leads to a  misguidance

**Comment by bpoplauschi** [comment]
> subspec GIF requires iOS 8+

you mean the deployment target from the Xcode proj?

**Comment by dreampiggy** [comment]
But actually FLAnimatedImage podspec set deployment_target 
 to 6.0: https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage.podspec#L20
And I also tried a project with deployment target 7.0 and intergrated well. If you still have issue, maybe you should try create an pull request to FLAnimatedImage ?

**Comment by bpoplauschi** [comment]
I'm confused, @zhungxd what are you referring to?
