### ISSUE TITLE
SDWebImageManager should have a function to just cancel a specific operation

### ISSUE THREAD

**Issue by REWNing** [rs/SDWebImage#1895]
Currently there's only one cancel function:
- (void)cancelAll;
Which causes bug because it is possible to cancel all operations in the queue caused by quickly added operations(user tapped too fast), and actually should keep the last operation. 
With this method, can cancel just the specific image downloading task, which can be hold as a property to get access to.

- (void)cancelOperation:(SDWebImageCombinedOperation *)operation {
    @synchronized (self.runningOperations) {
        [operation cancel];
        [self.runningOperations removeObject:operation];
    }
}

**Comment by bpoplauschi** [comment]
There is no need for this method. If you have the instance of the operation, you can call `cancel` on it directly.

**Comment by REWNing** [comment]
@bpoplauschi Thanks your reply.
I tried to call cancel, but the operation block is still actioning after cancel on certain condition: tapping very fast. App crashed because of Zombie action: action send to dealloced object.

**Comment by bpoplauschi** [comment]
@REWNing it will probably crash with the method you described as well. Can you take a look with Zombies and see which object is crashing and why? If you could create a PR, a number of people would benefit from that
