### ISSUE TITLE
Error of FlAnimatedImageView.h file not found please help

### ISSUE THREAD

**Issue by aaaamruta** [rs/SDWebImage#1896]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info
 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | IOS
 Platform Version        | 9.0
 SDWebImage Version      | e.g. 3.7.6
 Integration Method      |  manually
 Xcode Version           | Xcode 8
 Repro rate              |  all the time (100%) 
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps
After copied the files of SDWimage i m getting FLAnimatedImageView.h not found in an integrated project while i created the different project only with SDWimage files its working .please help unable to proceed

[SideMenu.zip](https://github.com/rs/SDWebImage/files/989644/SideMenu.zip)

**Comment by mythodeia** [comment]
how did you install SDWebimage? did you check [this](https://github.com/rs/SDWebImage#animated-images-gif-support)

**Comment by bpoplauschi** [comment]
@aaaamruta FLAnimatedImage was only introduced in version 4.0 of our library. If you're using 3.7.6 (as you say in the description), you need to upgrade.

**Comment by aaaamruta** [comment]
@bpoplauschi :Sorry its not 3.7.6

**Comment by aaaamruta** [comment]
@mythodeia yes i had checked the same.please help

**Comment by mythodeia** [comment]
which version of this library are you using? how did you install this library in your project?

**Comment by aaaamruta** [comment]
version is 4.0,I installed this library by adding the files manually dragging the files manually and then importing in the bridge header file

**Comment by aaaamruta** [comment]
version 4.0 ,I tried installing through terminal via pod install still getting the same issue ...please help cant proceed without this ..below is the code in  pod file 

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'SideMenu' do

pod 'SDWebImage', '~> 4.0’

end

**Comment by bpoplauschi** [comment]
@aaaamruta if you read the install instructions https://github.com/rs/SDWebImage#animated-images-gif-support you can see you need to specify the `GIF` subspec:
`pod 'SDWebImage/GIF'`

**Comment by aaaamruta** [comment]
It got resolved yesterday thanks guys..

**Comment by feibufei** [comment]
请问你是怎么修复的，我也遇到了同样的问题
