### ISSUE TITLE
What is sdwebimage max disk size and how to override it?

### ISSUE THREAD

**Issue by tirrorex** [rs/SDWebImage#1897]
SDWebImage Version    3.8.2

Hi, trying to fine tuning sdwebimage a bit, i search into the code a bit but couldn't find where the size was defined.
The idea is to customize this if size is too big, and maybe implement something to clear the disk at an appropriate time if the app size becomes too big also.

**Comment by ytmoye** [comment]
@tirrorex hello, i found that in latest version. It is declared in "SDImageCacheConfig.h". You can update your version, but there are some unsolved crashes.
