### ISSUE TITLE
SDWebImageDownloaderOperation partial Image filled with gray background instead of transparent

### ISSUE THREAD

**Issue by zhouhesheng** [rs/SDWebImage#1899]
in SDWebImageDownloaderOperation, image created from partialImageRef always has a gray background, while we often need the unloaded part to be transparent. we can make it by replacing:

CGImageSourceRef imageSource = CGImageSourceCreateWithData((__bridge CFDataRef)self.imageData, NULL);

to the following 2 lines:
CGImageSourceRef imageSource = CGImageSourceCreateIncremental(NULL);
        CGImageSourceUpdateData(imageSource, (__bridge CFDataRef)self.imageData, (totalSize == self.expectedSize) ? true : false);

**Comment by yutiandesan** [comment]
If I want the images that unloaded completely do not display. What should I do?

**Comment by dreampiggy** [comment]
#1987 Refactor code here, also change that [self.imageData copy] to ensure immutable object

**Comment by piercifani** [comment]
I also saw this behaviour and I agree with @yutiandesan that ideally, it should not display. Any ETA on this?

**Comment by dreampiggy** [comment]
@yutiandesan @piercifani Just use `SDWebImageOptions` without `SDWebImageProgressiveDownload` (also, it's not set unless you provide)

**Comment by dreampiggy** [comment]
Fixed via #2040.
Because we need to release 4.1.1 soon, that WebP progressive download feature will be available in 4.2.0 since it's not really urgent for most people.
