### ISSUE TITLE
GIF performance problem

### ISSUE THREAD

**Issue by Silence-GitHub** [rs/SDWebImage#1901]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.3
 SDWebImage Version      | 4.0.0
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 8.3.2
 Repro rate              | 100%
 Demo project link       | https://github.com/Silence-GitHub/GIFDemo

### Issue Description and Steps

When using FLAnimatedImageView in table view cell, displaying too many GIF images may lead to performance problem. I think creating FLAnimatedImage in main thread leads to the problem. Creating FLAnimatedImage in global queue (not in main queue) solves the problem, and makes scrolling smoothly.

My test test demo (written in Swift) is here: https://github.com/Silence-GitHub/GIFDemo
I forked and submitted a pull request: https://github.com/Silence-GitHub/SDWebImage

**Comment by dreampiggy** [comment]
I create an PR for your commit (Since you commit these changes in your own fork but not SD's repo 😅 )

#2047

**Comment by bpoplauschi** [comment]
#2047 was finally merged, this ticket can be closed.

@Silence-GitHub 4.2.0 will be released soon and it contains this fix. Thanks for the original idea.
