### ISSUE TITLE
Cache Key Filter called on main thread

### ISSUE THREAD

**Issue by jordanebelanger** [rs/SDWebImage#1902]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 10.0
 SDWebImage Version      | 4.0.0
 Integration Method      | carthage
 Xcode Version           | Xcode 8.3.2
 Repro rate              | 100%

### Issue Description and Steps

The SDWebImageManager has a cacheKeyFilter block that is called to allow for removing the dynamic parts of a url before using it as a cache key. The cacheKeyFilter block is executed on the main thread, I think it should be moved to a background thread.

Shaving off a url usually involve getting creating a URLComponents object, filtering the params you don't want from the URLComponent instance and then instantiating a new url. This can be rather costly depending on the url and the number of images you are trying to download at the same time. 

For example

    SDWebImageManager.shared().cacheKeyFilter = { url in
                let shavedUrl = url?.urlByRemovingQueryParam(named: "authorization")
                return shavedUrl??.absoluteString
    }

I suggest changing this so the cacheKeyFilter block is called on a background thread.

**Comment by bpoplauschi** [comment]
Since it should contain trivial computation and that people are already used to being called on the main queue, I would leave it as it is.
PS: it's not guaranteed to be called from the main queue.
