### ISSUE TITLE
MKAnnotationView Category Not Available in 4.0.0 CocoaPod

### ISSUE THREAD

**Issue by dannypier** [rs/SDWebImage#1903]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10
 SDWebImage Version      | 4.0.0
 Integration Method      | cocoapods
 Xcode Version           | 8.3
 Repro rate              | 100%
 Repro with our demo prj | NA
 Demo project link       | NA

### Issue Description and Steps

In the 4.0.0 version of the SDWebImage Pod, the MKAnnotationView+WebCache category is not available.

**Comment by dannypier** [comment]
After digging deeper, it appears that most of the MKAnnotationView methods have been deprecated for 4.0.0. I was mistaken in that the category did not exist in the Pod.

However, I'm unable to extract the replacement behavior given the documentation. For example, when setting the annotation image, my best option appears to be

```
            if let profileImagePath = sproutAnnotation.user?.profileImageUrlSmall, let profileImageUrl = URL(string: profileImagePath) {
                annotationView?.sd_internalSetImage(with: profileImageUrl, placeholderImage: #imageLiteral(resourceName: "tab_bar_family_unselected"), options: [], operationKey: nil, setImageBlock: nil, progress: nil, completed:nil)
            }
```

but this produces no results. If I set the image in the completion block as follows, the image will appear, but this does not seem like the intended use of this category

```
            if let profileImagePath = sproutAnnotation.user?.profileImageUrlSmall, let profileImageUrl = URL(string: profileImagePath) {
                annotationView?.sd_internalSetImage(with: profileImageUrl, placeholderImage: #imageLiteral(resourceName: "tab_bar_family_unselected"), options: [], operationKey: nil, setImageBlock: nil, progress: nil, completed: { (image, error, type, url) in
                    annotationView?.image = image
                })
            }
```

**Comment by bpoplauschi** [comment]
You should not call the `sd_internalSetImage` methods directly, but instead use the ones from `MKAnnotationView+WebCache` like `sd_setImageWithURL`
