### ISSUE TITLE
HPE Fortify Scan reports an issue with 'GET' Request.

### ISSUE THREAD

**Issue by deepakcmbi** [rs/SDWebImage#1904]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | iOS 9 and above
 SDWebImage Version      | 2.0 and above
 Integration Method      | manually
 Xcode Version           | Xcode 8.2.1
 Repro rate              | all the time (100%)
 Repro with our demo prj | Yes it will happen with your project too.
 Demo project link       | You can scan your project with HPE Fortify Audit workbench

### Issue Description and Steps

I have to run HPE fortify security scan with my project, Fortify report this issue.
"The call to initWithRequest:options:progress:completed:cancelled:() at SDWebImageDownloader.m uses the HTTP GET instead of POST method to send data to the server.

**Explanation: By Fortify**

HTTP requests which utilize the GET method allow the URL and request parameters to be cached in the browser's URL cache, intermediary proxies, and server logs. This could expose sensitive information to individuals who do not have appropriate rights to the data.

**Recommendations: By Fortify**

Use the HTTP POST method in conjunction with HTTPS to send data to the server. This limits the exposed data in the request to the URL. Request parameters should be sent in the POST body. Sensitive data should not be placed in URL request parameters as they will still be exposed in HTTP POST requests.

Avoid using NSURLRequest and explicitly set the HTTP method to POST when making HTTP requests.

I hope i explain the issue correctly. When i change initWithRequest:options:progress:completed:cancelled:() to use 'POST' instead of 'GET' it does not load images.

Can you please look into this issue?

**Comment by bpoplauschi** [comment]
This doesn't make sense. Requesting a HTTP resource is by standard a GET request. This is exactly so we can cache in the response and other benefits. POST is for submitting info. I don't think we can even change this inside the library.
