### ISSUE TITLE
GIF Orientation problem when loading image with SDWebImage

### ISSUE THREAD

**Issue by superdev89** [rs/SDWebImage#1907]
When loading gif file from the SDWebImage, it loads the gif correctly, but when reloads it again, it shows in wrong orientation.
Here is the gif file I used: http://imgur.com/gallery/UvbQ8WY

**Comment by mythodeia** [comment]
@superdev89 which version of the library are you using? Are you loading the gif using FLAnimatedImage object?

**Comment by superdev89** [comment]
@mythodeia I am using the latest version using cocoapod and yes I am using FLAnimatedImage. Gifs are showing fine but sometimes in wrong orientation.

**Comment by dreampiggy** [comment]
GIF does not support EXIF orientation. So this is a little strange (Since it should always show orientationUp)
You can try to provide a demo or to post a issue to FLAnimatedImage proejct
