### ISSUE TITLE
Crash on multiple concurrent downloads when accessing self.URLOperations dictionary

### ISSUE THREAD

**Issue by disaabler** [rs/SDWebImage#1909]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |ios 
 Platform Version        |10.3
 SDWebImage Version      |4.0.0
 Integration Method     |cocoapods
 Xcode Version           |Xcode 8.3.2
 Repro rate             |sometimes

### Issue Description and Steps

`completionHandler` of `SDWebImageDownloaderOperation` is not synchronised by access to `self.URLOperations`. This causes sometimes bad access in different places of the access to `self.URLOperations`.

**Comment by disaabler** [comment]
Patch file with the suggested fix is here: https://drive.google.com/open?id=0BwOwqtvU2djzY3VMYnlERGhWclE

**Comment by bpoplauschi** [comment]
Should be fixed by #1911
