### ISSUE TITLE
Does it utilizes LRU strategy?

### ISSUE THREAD

**Issue by grundmanise** [rs/SDWebImage#1912]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description and Steps

Does this library utilizes LRU strategy?

**Comment by ytmoye** [comment]
@grundmanise  hello, it desn't utilizes LRU strategy. It's memory cache is implemented by NSCache.

**Comment by aksamitsah098** [comment]
import SDWebImage

class ImageCacheManager {
    static let shared = ImageCacheManager()
    
    private let imageCache = SDImageCache.shared
    private let imageManager = SDWebImageManager.shared
    private let accessOrderKey = "ImageCacheAccessOrder"

    /// Dictionary to track access order per category (persists in UserDefaults)
    private var accessOrder: [String: [String]] = [:] {
        didSet {
            saveAccessOrderToDisk() // Save whenever updated
        }
    }

    /// Image categories with storage limits
    enum ImageType: String {
        case profile
        case feed
        case other

        var limit: Int {
            switch self {
            case .profile: return 1
            case .feed: return 1000
            case .other: return 1000
            }
        }
    }

    private init() {
        loadAccessOrderFromDisk() // Load saved order when app starts
    }

    private func cacheKey(for url: URL, type: ImageType) -> String {
        return "\(type.rawValue)_\(url.absoluteString)"
    }

    /// Fetch image from cache or download if not available
    func fetchImage(url: URL, type: ImageType, completion: @escaping (Result<UIImage, Error>) -> Void) {
        let cacheKey = cacheKey(for: url, type: type)

        imageCache.queryImage(forKey: cacheKey, options: [.queryMemoryData], context: nil) { cachedImage, _, _ in
            if let cachedImage = cachedImage {
                self.updateAccessOrder(for: cacheKey, type: type)
                completion(.success(cachedImage))
            } else {
                self.imageManager.loadImage(with: url, options: [.highPriority], progress: nil) { image, data, error, _, _, _ in
                    if let image = image, let data = data {
                        self.storeImage(image: image, data: data, cacheKey: cacheKey, type: type)
                        completion(.success(image))
                    } else if let error = error {
                        completion(.failure(error))
                    }
                }
            }
        }
    }

    /// Cache an image without displaying it
    func cacheImage(url: URL, type: ImageType) {
        let cacheKey = cacheKey(for: url, type: type)

        imageManager.loadImage(with: url, options: [.highPriority], progress: nil) { image, data, _, _, _, _ in
            if let image = image, let data = data {
                self.storeImage(image: image, data: data, cacheKey: cacheKey, type: type)
            }
        }
    }

    /// Store an image in cache with LRU eviction
    private func storeImage(image: UIImage, data: Data, cacheKey: String, type: ImageType) {
        imageCache.store(image, forKey: cacheKey)
        imageCache.storeImageData(toDisk: data, forKey: cacheKey)

        updateAccessOrder(for: cacheKey, type: type)

        if let count = accessOrder[type.rawValue]?.count, count > type.limit {
            removeLeastUsedImage(for: type)
        }
    }

    /// Update access order for LRU tracking
    private func updateAccessOrder(for cacheKey: String, type: ImageType) {
        let category = type.rawValue

        if accessOrder[category] == nil {
            accessOrder[category] = []
        }

        if let index = accessOrder[category]?.firstIndex(of: cacheKey) {
            accessOrder[category]?.remove(at: index)
        }

        accessOrder[category]?.append(cacheKey)
    }

    /// Remove the least recently used image when cache exceeds limit
    private func removeLeastUsedImage(for type: ImageType) {
        let category = type.rawValue

        if let leastUsedKey = accessOrder[category]?.first {
            accessOrder[category]?.removeFirst()
            imageCache.removeImage(forKey: leastUsedKey, fromDisk: true)
        }
    }

    /// Save access order to UserDefaults
    private func saveAccessOrderToDisk() {
        UserDefaults.standard.setValue(accessOrder, forKey: accessOrderKey)
    }

    /// Load access order from UserDefaults
    private func loadAccessOrderFromDisk() {
        if let savedOrder = UserDefaults.standard.dictionary(forKey: accessOrderKey) as? [String: [String]] {
            accessOrder = savedOrder
        }
    }

    /// Get total cache size for a specific image type
    func getCacheSize(for type: ImageType, completion: @escaping (UInt) -> Void) {
        imageCache.calculateSize { totalSize, _ in
            completion(totalSize)
        }
    }

    /// Clear cache for a specific image type
    func clearCache(for type: ImageType, completion: (() -> Void)? = nil) {
        let category = type.rawValue
        accessOrder[category]?.forEach { key in
            imageCache.removeImage(forKey: key, fromDisk: true)
        }
        accessOrder[category]?.removeAll()
        saveAccessOrderToDisk()
        completion?()
    }

    /// Clear all cache
    func clearAllCache(completion: (() -> Void)? = nil) {
        imageCache.clear(with: .all) {
            self.accessOrder.removeAll()
            UserDefaults.standard.removeObject(forKey: self.accessOrderKey)
            completion?()
        }
    }
}

**Comment by ytmoye** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
