### ISSUE TITLE
Where is SDWebImageCombinedOperation?

### ISSUE THREAD

**Issue by tirrorex** [rs/SDWebImage#1913]
I currently have an issue with reusable cells.
My problem lies with the fact that i created a separate imageCacheManager which i am using everywhere in my app.
What i want to accomplish here is a way to prevent the image from being set without actually cancelling the download. I thought SDWebImageCombinedOperation could do that but though it is in the github diagram i cannot find it in the pod, is it still there?

Also i have to use SDImageCache because SDWebImageManager download method checks the disk, a behaviour i cannot have since i do a manual check to reuse my original image if existing in disk.

**Comment by tirrorex** [comment]
For those interested i added an extension with computed properties to UIImageView, i then compare the value i have as parameter and the property store in my UIImageView before setting the image.
Dirty but does the trick

**Comment by bpoplauschi** [comment]
`SDWebImageCombinedOperation` is not public.
To answer the bigger questions, this lib was made for easy usage that most our users need. You are trying to reuse some components while shutting off some behavior. It's not easy :) Feel free to propose any PR and we will discuss there, we've been open to exposing things people need

**Comment by tirrorex** [comment]
I needed to customize the caching behaviour, to put it simply we reuse a lot our images but with different format, so in order to improve performances and reduce data consumption we cache both the original and the modified image, a behaviour i couldn't get to work without customizing everything.
So yup, i ended up shutting a lot of behaviour :) 
Might try to fork in the future if i have more time (i'm also open to a different solution to the original problem) and if we do not move to react-native.

**Comment by bpoplauschi** [comment]
@tirrorex 

> What i want to accomplish here is a way to prevent the image from being set without actually cancelling the download

Have you tried using `SDWebImageAvoidAutoSetImage`? It will not set the image after it's retrieved from network/cache.

> Also i have to use SDImageCache because SDWebImageManager download method checks the disk, a behaviour i cannot have since i do a manual check to reuse my original image if existing in disk.

I think you can subclass `SDImageCache` and alter some of the behaviour. Maybe we should clean up its interface a bit.

Does this help?

**Comment by tirrorex** [comment]
@bpoplauschi i didn't need to subclass anything, instead i call directly SDImageCache and SDWebImageDownloader
The code is done and working, but it's not what i would call clean though.
I will not set the image only if the current cell is not the one that initiated the download, i am not using UIImage related functions and instead use lower level functions provided by sdwebimage.

**Comment by bpoplauschi** [comment]
@tirrorex ok. Is there anything we can change that would make your customisation work easier or your code cleaner?

**Comment by tirrorex** [comment]
Will think about it and get back to you as soon as we have time to work on this project again.
Thanks
