### ISSUE TITLE
SDCacheCostForImage not right

### ISSUE THREAD

**Issue by DikeyKing** [rs/SDWebImage#1914]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. 9.0
 SDWebImage Version      | e.g. 3.7.6
 Integration Method      | e.g.  cocoapods 
 Xcode Version           | e.g. Xcode 8.3.2
 Repro rate              | e.g. all the time (100%)  

### Issue Description and Steps

<img width="993" alt="screen shot 2017-05-24 at 09 29 48" src="https://cloud.githubusercontent.com/assets/7019111/26383429/33aa4328-4065-11e7-9b82-eaef814c1110.png">

In my projuct , read the cached disk image always return nil , and I checked the source code ,I found if SDImageCache calculate the cost for image and store image with  

- (void)setObject:(ObjectType)obj forKey:(KeyType)key cost:(NSUInteger)g;

but 

 - (void)setObject:(ObjectType)obj forKey:(KeyType)key; // 0 cost

works fine.

And  may [Mattt ThompsonMattt 's blog about NSCache](http://nshipster.com/nscache/) be right ?

**Comment by bpoplauschi** [comment]
What part from the blog post are you referring to?
And I've rechecked with the latest version and the cost is correctly computed
