### ISSUE TITLE
Animated GIFs don't seem to work in since version 4.0

### ISSUE THREAD

**Issue by antonbremer** [rs/SDWebImage#1917]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.0 and higher
 SDWebImage Version      | 4.0
 Integration Method      | cocoapods
 Xcode Version           | 8.3.2
 Repro rate              | 100%
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Summary**
Animated GIFs don't seem to work in since version 4.0

**Steps to reproduce**
1. Load an animated GIF with SDWebImage in an ImageView

**Expected Result**
You see the GIF animating

**Actual Result**
Only the first frame of the GIF is being shown

**Comment by mythodeia** [comment]
@antonbremer does this happen in the demo project too? Did you use [FLAnimatedImage](https://github.com/rs/SDWebImage#animated-images-gif-support) for the gif?

**Comment by antonbremer** [comment]
Hi Konstatinos,

Thanks for your quick response.
I had not seen this part in the documentation.
I will go and try this out straight away, and get back to you when I have the results

Thanks again,
Anton

**Comment by antonbremer** [comment]
Hi Konstatinos

I am very happy to tell you that using FLAnimatedImage it works.
Sorry I missed that part of the documentation


Cheers,
Anton

**Comment by antonbremer** [comment]
I did not use use FLAnimatedImage. 
Using [FLAnimatedImage](https://github.com/rs/SDWebImage#animated-images-gif-support) it works.
