### ISSUE TITLE
when I called "sd_cancelCurrentImageLoad" ,the progressBlock still called  

### ISSUE THREAD

**Issue by SCriminal** [rs/SDWebImage#1918]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          | ios
 Platform Version        |  8.0
 SDWebImage Version      |3.8.2
 Integration Method      | cocoapods
 Xcode Version           | e.g. Xcode 7.3
 Repro rate              |all the time

### Issue Description and Steps

When I use"sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageCompletionBlock)completedBlock",the progressBlock still called  after sd_cancelCurrentImageLoad called.

**Comment by dreampiggy** [comment]
Please try our latest SDWebImage 4.x version and to see if this issue still occur.

**Comment by dreampiggy** [comment]
Please try our latest SDWebImage 4.x version and to see if this issue still occur.

**Comment by dreampiggy** [comment]
This issue is not active for long time and may because of old version's issue. Feel free to reopen it if you're still interested in this issue.
