### ISSUE TITLE
Consider adopting libwebp 0.6.0 ?

### ISSUE THREAD

**Issue by Nonepse** [rs/SDWebImage#1923]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.0
 SDWebImage Version      | 4.0.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.3.2
 Repro rate              | 100%
 Repro with our demo prj | N/A
 Demo project link       | N/A

### Issue Description and Steps

`SDWebImage` has been using `libwebp` v. 0.5.1 [for 8 months](https://github.com/rs/SDWebImage/commit/836c15bccff60e0eebc182b159b102b36051b39f).
v 0.6.0 was released [5 months ago](https://github.com/webmproject/libwebp/releases/tag/v0.6.0).
Is there any plan to adopt it?

Currently when integrating `SDWebImage/WebP` using CocoaPods, Xcode gives me this warning:
[https://bugs.chromium.org/p/webp/issues/detail?id=279](https://bugs.chromium.org/p/webp/issues/detail?id=279)
As @jzern mentions in this ticket, the warning is fixed by v. 0.6.0

I can confirm that after forking `SDWebImage` and updating `libwebp` to 0.6.0, the warning is gone.

**Comment by bpoplauschi** [comment]
Done via 2d9c812 - release 4.1.0 available
