### ISSUE TITLE
A lot of errors occur on my device when I build my project, but everything is OK on the simulator

### ISSUE THREAD

**Issue by NineCity** [rs/SDWebImage#1926]
I create en empty project,and install SDWebImage(4.0.0) with cocoapods. A lot of errors occur on my device when I build my project, but everything is OK on the simulator.What happened? The errors like this: Cannot define category for undefined class 'UIButton'、Cannot find interface declaration for 'UIButton'...

 Platform Name          iOS
 Platform Version        8.0
 SDWebImage Version     4.0.0
 Integration Method        cocoapods
 Xcode Version          Xcode 8.1
 Repro rate              all the time (100%) 

![jietu20170608-113143error](https://user-images.githubusercontent.com/19357504/26911147-1dbd5aac-4c3e-11e7-8289-01cf7a43989e.jpg)

**Comment by bpoplauschi** [comment]
I just rechecked, the CocoaPods installation works fine - closing. If your issue still persists, you should look into the CocoaPods project for similar problems
