### ISSUE TITLE
SDWebImage crashing repeatedly in SDWebImageDownloaderOperation implementation

### ISSUE THREAD

**Issue by octopusbaba** [rs/SDWebImage#1928]
<img width="1377" alt="screen shot 2017-06-11 at 10 56 52 am" src="https://user-images.githubusercontent.com/4969242/27008567-f198c3ae-4e94-11e7-9b5f-ea0221ae5482.png">

**Comment by skyline75489** [comment]
Have you seen #1883 and #1925 ?

**Comment by mythodeia** [comment]
closing this. please refer to the other open tickets for this issue. thanks
