### ISSUE TITLE
crash: [UIImage sd_imageOrientationFromImageData]

### ISSUE THREAD

**Issue by maplelover** [rs/SDWebImage#1929]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        |  10.3.2 (14F89)
 SDWebImage Version      | e.g. 3.7.6
 Integration Method      | manually
 Xcode Version           | 8.3.1
 Repro rate              | only once
 Repro with our demo prj | no
 Demo project link       | none

### Issue Description and Steps

Thread 28#0	(null) in objc_msgSend ()
1	(null) in CGImageMetadataMerge ()
2	(null) in PNGReadPlugin::init() ()
3	(null) in PNGReadPlugin::InitWithOffset(CGImagePlugin*, unsigned long, unsigned long, unsigned long) ()
4	(null) in IIOImageSource::makeImagePlus(unsigned long, __CFDictionary const*) ()
5	(null) in IIOImageSource::getPropertiesAtIndexInternal(unsigned long, __CFDictionary const*) ()
6	(null) in IIOImageSource::copyPropertiesAtIndex(unsigned long, __CFDictionary const*) ()
7	(null) in CGImageSourceCopyPropertiesAtIndex ()
8	(null) in +[UIImage(MultiFormat) sd_imageOrientationFromImageData:] at SDWebImage/UIImage+MultiFormat.m:51
9	(null) in +[UIImage(MultiFormat) sd_imageWithData:] at SDWebImage/UIImage+MultiFormat.m:34
10	(null) in -[SDImageCache diskImageForKey:] at SDWebImage/SDImageCache.m:265 
11	(null) in __42-[SDImageCache queryDiskCacheForKey:done:]_block_invoke at ThirdParty/SDWebImage/SDImageCache.m:303
12	(null) in _dispatch_call_block_and_release ()
13	(null) in _dispatch_client_callout ()
14	(null) in _dispatch_queue_serial_drain ()
15	(null) in _dispatch_queue_invoke ()
16	(null) in _dispatch_queue_override_invoke ()
17	(null) in _dispatch_root_queue_drain ()
18	(null) in _dispatch_worker_thread3 ()
19	(null) in _pthread_wqthread ()
20 (null) in start_wqthread ()

**Comment by mythodeia** [comment]
please try using the latest version of the library
