### ISSUE TITLE
How to intercept the response to check header fields?

### ISSUE THREAD

**Issue by evyasafm** [rs/SDWebImage#1933]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.0
 SDWebImage Version      | latest
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.3

### Issue Description and Steps

Hi,
Is there a way to intercept the response header fields?
in case response failed (400 Bad Request) with header field name "X-Error-Code", is there a way to get the field value?

**Comment by skyline75489** [comment]
Technically there is a way but SDWebImage isn't designed to be a full-featured HTTP client. You may have to implement this on your own.

**Comment by mythodeia** [comment]
closing this.
