### ISSUE TITLE
Can't fetch image from url that contain "\\"

### ISSUE THREAD

**Issue by tanpengsccd** [rs/SDWebImage#1937]
SDWebImage (3.7.6) 
Can't fetch image from url that contain "\\",
Like " [HOST]/2017-06-15\\2687e783-6fbd-46bd-b7ed-f5e16ea33270.jpg".

-----
if i change it to [HOST]/2017-06-15//2687e783-6fbd-46bd-b7ed-f5e16ea33270.jpg, it will be  done.

**Comment by mythodeia** [comment]
you can encode the backslash and then request the url. try that
