### ISSUE TITLE
I get Error Domain=NSURLErrorDomain Code=-1100

### ISSUE THREAD

**Issue by snailedMan** [rs/SDWebImage#1943]
I get a error:Domain=NSURLErrorDomain Code=-1100 when I use SD_WebImage, I check my Internet is worked and image is existed，so what should i do

**Comment by mythodeia** [comment]
which version are you using? did you try the problematic url with the demo project?

**Comment by bpoplauschi** [comment]
Feel free to reopen with all the info required by the issue template.

**Comment by linZsama** [comment]
how did you fix it ,i'cant solve this, i try to set options with retryFailed,but it dose't work.can u help me.
