### ISSUE TITLE
SDWebImageDownloader memory leaks when not use singleton

### ISSUE THREAD

**Issue by dourgulf** [rs/SDWebImage#1944]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.0
 SDWebImage Version      | 4.0
 Integration Method      | cocoapods
 Xcode Version           | 8.3.3
 Repro rate              | all the time (100%) 

### Issue Description and Steps

```
SDWebImageDownloader *downloader = [[SDWebImageDownloader alloc] init];
downloader.downloadTimeout = timeout;
[downloader downloadImageWithURL:url options:SDWebImageDownloaderHighPriority progress:nil completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, BOOL finished) {
}];
downloader = nil;
```

I read the implementation of SDWebImageDownloader, and find the problem is:

```
- (nonnull instancetype)initWithSessionConfiguration:(nullable NSURLSessionConfiguration *)sessionConfiguration {
    if ((self = [super init])) {
    	//	...
        self.session = [NSURLSession sessionWithConfiguration:sessionConfiguration
                                                     delegate:self
                                                delegateQueue:nil];
    }
    return self;
}
```

by the document:
The session object keeps a strong reference to the delegate until your app exits or explicitly invalidates the session. If you do not invalidate the session by calling the invalidateAndCancel or finishTasksAndInvalidate method, your app leaks memory until it exits.

although SDWebImageDownloader's dealloc do     [self.session invalidateAndCancel]; but because the cycle reference, it's dealloc method will never called.

**Comment by guidev** [comment]
+1

**Comment by taylorwrynn** [comment]
+1

**Comment by dreampiggy** [comment]
Any reason that you use the manually alloc `SDWebImageDownloader` but not the shared instance.

If you really want to use the self alloc `SDWebImageDownloader`, currently you can only use KVC or runtime method to get the `session` property(:D). maybe we need a new method to just call `invalidateAndCancel` to break retain cycle.

**Comment by dourgulf** [comment]
I want to use an individual timeout option for my download(maybe very short,like only 3s).
And I want to cancel previous downloading progress, when other download request is comming. So I need manually allloc SDWebImageDownloader, is there any other choise?

**Comment by dreampiggy** [comment]
@dourgulf Currently we do not have an public API to invalid the `SDWebImageDownloader.session` property. So currently you need KVC or runtime hack to get that property and call the invalidate function.

```objectivec
    SDWebImageDownloader *downloader = [[SDWebImageDownloader alloc] init];
    NSURLSession *session = [downloader valueForKey:@"session"];
    if ([session isKindOfClass:[NSURLSession class]]) {
        [session invalidateAndCancel];
    }
```

 If this propose is adopted by some users, we can add an API such as AFNetworkinig`s `- (void)invalidateSessionCancelingTasks:(BOOL)cancelPendingTasks`. And it's welcomed to provide an pull request related to this feature.

**Comment by dreampiggy** [comment]
Well...A long time passed but seems no one create a PR. So I create one 😂 #2116

**Comment by dreampiggy** [comment]
#2116 Merged. So you can use that `invalidateSessionAndCancel:` API to invalidate session and break retain cycle.
