### ISSUE TITLE
sd_cancelCurrentImageLoad doesn't work (with firebase)

### ISSUE THREAD

**Issue by MicMat68** [rs/SDWebImage#1945]
Hi,

I use SDWebImage with Firebase.
In a tableview, i use it simply :

`cell.image.sd_setImage(with: reference, placeholderImage: placeholder_image)`

It's work fine.
But cancel loading doesn't work :

```
func tableView(_ tableView: UITableView, didEndDisplaying cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell") as! MyCell
        cell.image.sd_cancelCurrentImageLoad()
    }
```

Is it a bug from firebase?

Thks

**Comment by jeffersonsetiawan** [comment]
what version do you use @MicMat68 ?
I even can't use method 
```cell.image.sd_setImage(with: reference, placeholderImage: placeholder_image)```

the error is:
```Cannot invoke 'sd_setImage' with an argument list of type '(with: StorageReference, placeholderImage: UIImage?)'```

**Comment by MicMat68** [comment]
It's with firebase :
Installed with :
 pod 'FirebaseUI/Storage'

import SDWebImage
import FirebaseStorageUI

**Comment by jeffersonsetiawan** [comment]
Thanks @MicMat68 !! never know there should be another dependency for it.

**Comment by bpoplauschi** [comment]
@MicMat68 you say the `sd_cancelCurrentImageLoad` method doesn't work. What is the error?
Also, it's important you fill the required info from the issue template, otherwise we keep guessing here :)

**Comment by MicMat68** [comment]
Hi,

No error, function don't stop loading.
