### ISSUE TITLE
EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

### ISSUE THREAD

**Issue by guidev** [rs/SDWebImage#1950]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 10.3.2
 SDWebImage Version      | e.g. 3.7.6
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.3.3
 Repro rate              | sometimes
 Repro with our demo prj | no
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

The app randomly crashes when trying to download images using SDWebImagePrefetcher, the urls to load are always the same.

![crash](https://user-images.githubusercontent.com/1105813/27655391-7accdb66-5c45-11e7-8b4a-3dc5a337ccd4.png)

**Comment by guidev** [comment]
Apparently this has already been fixed (https://github.com/rs/SDWebImage/pull/1911), but not yet on master.

**Comment by bpoplauschi** [comment]
Now merged into master
