### ISSUE TITLE
Fatel Exception: NSInvalidArgumentException in SDImageCache.m line 549

### ISSUE THREAD

**Issue by AIHELP-NET** [rs/SDWebImage#1957]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.0
 SDWebImage Version      | 3.8.2
 Integration Method      | manually
 Xcode Version           |  Xcode 8.3.2
 Repro rate              | sometimes x% 
 Repro with our demo prj | e.g. does it happen with our demo [project?](url)
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by CS30-NET** [comment]
![image](https://user-images.githubusercontent.com/19989274/27813146-693366ee-60a6-11e7-9393-975ca13cee70.png)

**Comment by CS30-NET** [comment]
I only change the file name , class name and variable related to Elva+xxx, can anyone find me a solution, thanks a lot

**Comment by bpoplauschi** [comment]
Not sure what the issue is, but you can debug it if you can reproduce it. The method changed in release 4.0, so upgrading might fix it - needs to be tested.
