### ISSUE TITLE
SDWebImage download image using imageview variable

### ISSUE THREAD

**Issue by saran1985** [rs/SDWebImage#1959]
Hello,
I am using sd webimage to fetch images from api.i dont have IBOutlet created for imageview,instead i created a imageview programatically and fetching the webimage using downloadImage(with url:URL) function.This imageview will have to keep replacing with new images each time i click on the image.The issue i click on the new image,then this new image is been overlapped on the existing image.It does not replace the old image.My question is does downloadimage function always work this way or is there any issue in the way im doing it.

if (vtype[i] == "OtherView") && (cattypelink == "Image")
                {
                    
                    print("i is \(i)")
                    imagestrng = demoarray[i]
                    self.imgtag = i
                    self.tag = self.imgtag
                    print("imagestring is sswqqwqew \(imagestrng)")
                    let actualURL = URL(string: imagestrng)
                    self.downloadImage(with: actualURL!)
                   
                }

func downloadImage(with url:URL) {
        print("inside download image")
        SDWebImageManager.shared().downloadImage(with: url, options: SDWebImageOptions(rawValue: 0), progress: nil) { (image, _, _, _, _) in
            if let _ = image {
                print("image downloaded")
                
                 if self.tag == self.imgtag
                 {
                  var finalimage: UIImage = image!
                  print("finalimage is \(finalimage)")
                  self.othersimg = UIImageView(frame: self.oview.frame)
                  self.othersimg?.image = nil
                  self.othersimg?.image = finalimage
                  self.oview = UIView(frame: CGRect(x:0,y:0,width:self.sigeImg.width,height:self.sigeImg.height))
                  self.mainview.addSubview(self.oview)
                  self.oview.addSubview(self.othersimg!)
                  self.othersimg?.tag = self.imgtag
                  print("othersimg is \(self.othersimg?.tag)")
                }
                else
                 {
                  print("nothing")
                  }
          
            }
            else {
                print("not downloaded '")
                // Try to download again (optional)
                self.downloadImage(with: url)
            }
        }
    

}

**Comment by bpoplauschi** [comment]
I did not understand the issue. Please reformat your issue and provide the issue template required details so we can properly respond.
