### ISSUE TITLE
Why SDWebImageDownloader maxConcurrentOperationCount = 6?

### ISSUE THREAD

**Issue by yjh1313** [rs/SDWebImage#1961]
When i compared SD with TIP(twitter image pipeline),i found the TIP was faster than SD in how soon an image is visible. And i found the key is the number of max concurrent download operations.

**Comment by bpoplauschi** [comment]
Feel free to change this setting via experimentation. We found this value to be a good value for all the supported devices, a higher value would just overuse the CPU.
