### ISSUE TITLE
Duplicate issue (#1602): [SDImageCache storeImage:forKey:toDisk:completion:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by sonnyback** [rs/SDWebImage#1962]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 10.3.2
 SDWebImage Version      | e.g. 4.0
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 8.3.3
 Repro rate              | e.g. all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project? NA
 Demo project link       | e.g. link to a demo project that highlights the issue NA

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

Hello! This is the same issue at #1602, where I'm getting the unrecognized selector when calling storeImage:forKey:toDisk:completion:, after migrating to SDWebImage 4.0. The reason I'm posting is that the person who opened the original issue did not clarify how to resolve it. I have been using this framework for awhile on the various 3.x versions in the same app and it worked flawlessly. However, after upgrading to 4.0, I'm not getting the below error...

`-[SDImageCache storeImage:forKey:toDisk:completion:]: unrecognized selector sent to instance 0x174282e90`

Here is the code...

```
@property (strong, nonatomic) SDImageCache *imageCache;
// lazy instantiate imageCache
- (SDImageCache *)imageCache {
    
    if (!_imageCache) {
        _imageCache = [[SDImageCache alloc] initWithNamespace:NAME_SPACE_IMAGE_CACHE];
        // BELOW LINE NO LONGER WORKS WITH 4.0.0
        //[_imageCache setMaxCacheAge:ONE_HOUR_IN_SECONDS * 3]; // cache age limit set to 3 hours (in seconds)
    }
    
    return _imageCache;
}
**/* This is the line that throws the error */**
[[SDImageCache sharedImageCache] storeImage:[UIImage imageWithContentsOfFile:coffeeImageData.imageURL.path] forKey:coffeeImageData.imageURL.absoluteString toDisk:YES completion:^{
                                    NSLog(@"INFO: CID Image cached successfully!");
                                }];
```

Also, I'm on the latest version of OS X and XCode. Please help me resolve this! A working app is now completely broken after migrating to 4.0. Thank you!

**Comment by mythodeia** [comment]
clean your derived data folder and then try to rebuild

**Comment by sonnyback** [comment]
I'm not sure which folder is the derived data. I did do a clean, then build and that did not make any difference.

**Comment by mythodeia** [comment]
~/Library/Developer/Xcode/DerivedData

**Comment by sonnyback** [comment]
Thanks!

**Comment by mythodeia** [comment]
if this solved your issue let me know so i can close the ticket

**Comment by sonnyback** [comment]
Yep, that worked...thanks!
