### ISSUE TITLE
Allow developer to choose maximum size of decoded image when SDWebImageScaleDownLargeImages is set

### ISSUE THREAD

**Issue by christopherhwood** [rs/SDWebImage#1963]
60 MB is still too large for a page with multiple images. On older devices the app will crash. Every developer's requirements for image size may be different, so I recommend that this property be set with a default property but is also able to be altered by the developer.

**Comment by bpoplauschi** [comment]
@christopherhwood feel free to create a PR.

**Comment by dreampiggy** [comment]
@christopherhwood Implemted in 5.x. You can use an extra arguments for our `UIImage+ForceDecode` category, as well as that `SDWebImageCoderHelper` methods.

```objective-c
UIImage *largeImage;
UIImage *scaleDownImage = [SDWebImageCoderHelper decodedAndScaledDownImageWithImage:image limitBytes:1024*1024*10];
```
