### ISSUE TITLE
placeholder don't display

### ISSUE THREAD

**Issue by MysteryRan** [rs/SDWebImage#1964]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 9.0
 SDWebImage Version      | latest
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.3
 Repro rate              | 100%
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

 Platform Name           ios 
 Platform Version        9.0
 SDWebImage Version      latest
 Integration Method     cocoapods
 Xcode Version           Xcode 8.3
 Repro rate              all the time (100%) 

two same invalid image url   UIImgageView shows the placeholder but the button doesn't show placeholder

**Comment by UmaMadhavi** [comment]
@MysteryRan .. how can i display gif using SDWebImage can u please  help me in achieving this?

**Comment by MysteryRan** [comment]
the offical introduction 
![2017-07-26 2 53 08](https://user-images.githubusercontent.com/17866688/28608310-7bc9f5ca-7212-11e7-96c2-400f77ecab69.png)

**Comment by dreampiggy** [comment]
YES. This is known issue. According to git log, it break this behavior to 4.0 (Previous version, `UIButton` will set placeholder image even if the `url` is nil in advance).

The related PR is here: #1790 #1721

Maybe we should ask someone to check or revisit this behaviour ?

**Comment by dreampiggy** [comment]
Fixed via #2043 in 4.1.1

**Comment by bpoplauschi** [comment]
👍
