### ISSUE TITLE
decodedImageWithImage crash

### ISSUE THREAD

**Issue by Asution** [rs/SDWebImage#1965]
<img width="1277" alt="2017-07-17 10 35 20" src="https://user-images.githubusercontent.com/9418118/28254047-d3f742d6-6adb-11e7-930b-325c7a881936.png">

when I load this image, I got crash for 

```
if (!image.images) {
                    if (self.shouldDecompressImages) {
                        image = [UIImage decodedImageWithImage:image];  // this row
                    }
                }
```

**Comment by Asution** [comment]
The image is here.
![](https://user-images.githubusercontent.com/9418118/28254063-f9d0a1f0-6adb-11e7-9fcb-b788288e96c1.jpg)

**Comment by Asution** [comment]
The image information.
![](https://user-images.githubusercontent.com/9418118/28254080-16ec56da-6adc-11e7-84f7-4e5df3bbd1c7.png)

**Comment by mythodeia** [comment]
@Asution which version are you using? can you try the image in the demo project (latest version) and let us know if it still crashes?

**Comment by Asution** [comment]
@mythodeia When i use github demo reload this image that can't crash, But my Podfile use SDWebImage like this pod 'SDWebImage'  Using SDWebImage (3.8.2).

**Comment by mythodeia** [comment]
you are using an older version of the library. download the latest one v4.0.0
