### ISSUE TITLE
SDWebImageDownloader operation crash

### ISSUE THREAD

**Issue by 4bb3** [rs/SDWebImage#1967]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 SDWebImage Version      | e.g. 4.0.0
 Integration Method      | e.g. carthage 
 Xcode Version           | e.g. Xcode 8.3
 Repro rate              | e.g. only once

### Issue Description and Steps

```
for product in products {
            SDWebImageDownloader.shared().downloadImage(with: URL(string: APIMode.BackofficeRoot + product.img_url), options: [], progress: nil, completed: { (image, data, error, bool) in
                if let image = image {
                    SDWebImageManager.shared().saveImage(toCache: image, for: URL(string: APIMode.BackofficeRoot + product.img_url))
                }
            })
        }
```
![Crash example](https://i.stack.imgur.com/JFSX7.png)
![Crash example](https://i.stack.imgur.com/oBC6v.png)

**Comment by bpoplauschi** [comment]
No idea. Can you replicate it with any conditions (our demo project, another project, anything)?
