### ISSUE TITLE
SDWebImage/WebP can't install

### ISSUE THREAD

**Issue by xuchuandong** [rs/SDWebImage#1973]
I'm sorry to interrupt you, due to the special environment of China, download need to use VPN, I use pod 'SDWebImage/WebP' command to download, but always failed download, even without VPN is no good, or I changed the HOST or not;What's the problem?What should I do with it?
An error is as follows:

[!] Error installing libwebp
[!] /usr/bin/git clone https://chromium.googlesource.com/webm/libwebp /var/folders/nj/__7c26kx2d5c5f64pkts0mzc0000gn/T/d20170724-15438-59117j --template= --single-branch --depth 1 --branch v0.5.0
Cloning into '/var/folders/nj/__7c26kx2d5c5f64pkts0mzc0000gn/T/d20170724-15438-59117j'...
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

**Comment by bpoplauschi** [comment]
If this url is not available to you https://chromium.googlesource.com/webm/libwebp, I don't know how to get passed that. That is the URL which is used by libwebp to publish via CocoaPods.

Maybe you can try Carthage instead

**Comment by xuchuandong** [comment]
I have dealed this problem which is I used an error SVN tool(Lantern) by my friend,when I redownload a SVN tool(RedSVN) from  Mac App Store,and reinstall cocoapods, it works. Thanks for you help.
