### ISSUE TITLE
memoryLeaks

### ISSUE THREAD

**Issue by ZB0106** [rs/SDWebImage#1974]
When use ( - decodedAndScaledDownImageWithImage) decode image,   I found memoryleak for "void* destBitmapData = malloc( bytesPerRow * destResolution.height )",

**Comment by bpoplauschi** [comment]
@ZB0106 see #1860 - this is a duplicate. Closing

**Comment by ZB0106** [comment]
when i test use instrument ,i found that it is still has memory leak with the following code(- decodedAndScaledDownImageWithImage), although has released memory with the following code(f( destContext == NULL ) {
        free( destBitmapData ); 
        return image
    }        
), however, i think that  we should release memory when release destcontext  ,the code is like this （   CGImageRef destImageRef = CGBitmapContextCreateImage(destContext);
        CGContextRelease(destContext);
        if (destImageRef == NULL) {
        free( destBitmapData ); 
            return image;
        }
）
the test ihone is iphone6  system is 10.2.1

**Comment by bpoplauschi** [comment]
@ZB0106 please check out #1976 it should fix those leaks.
