### ISSUE TITLE
Ability to enable/disable image caching.

### ISSUE THREAD

**Issue by partho-maple** [rs/SDWebImage#1979]
Is there currently any feature/API to enable/disable image caching completely?  I want to download image but don't want to store it in any cache(disk or memory).

**Comment by bpoplauschi** [comment]
`SDWebImageCacheMemoryOnly` will disable the disk cache, `SDImageCache.config.shouldCacheImagesInMemory = NO` should disable the memory cache.

**Comment by chanonly123** [comment]
SDImageCache.shared.config.shouldCacheImagesInMemory = false

**Comment by bristolking1** [comment]
where does this code go? in what file or folder?
