### ISSUE TITLE
SDWebImage can not load below url link

### ISSUE THREAD

**Issue by wenshao1018** [rs/SDWebImage#1982]
str = http://img0.imgtn.bdimg.com/it/u=2110656969,2505995779&fm=26&gp=0.jpg

[sd_setImageWithURL:[NSURL URLWithString:str]];

that done not work, how can I do to load the url image.

**Comment by bpoplauschi** [comment]
I have tried your image with the demo project and it returns a 403 error. There is something wrong with that API providing the image.

PS: When you hit "new issue" on this project you get a template with all the info we need to investigate an issue, including testing with the demo project. Why did you decide to ignore that?

**Comment by tlb123456** [comment]
I met the same issue

**Comment by bpoplauschi** [comment]
@tlb123456 what issue? are you loading the same image? :) I doubt that.
Please properly describe your problem here if it is the same, search for a proper issue if there is one, or just open a new one otherwise.
