### ISSUE TITLE
sd_setImage and animated webp fails with error: Downloaded image has 0 pixels only for some special animated webp urls

### ISSUE THREAD

**Issue by btxkenshin** [rs/SDWebImage#1989]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.1
 SDWebImage Version      | 4.0.0
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 9.0 beta 2 (9M137d)
 Repro rate              | 100%
 Repro with our demo prj | does it happen with our demo project? YES.
```
  - SDWebImage (4.0.0):
    - SDWebImage/Core (= 4.0.0)
  - SDWebImage/Core (4.0.0)
  - SDWebImage/GIF (4.0.0):
    - FLAnimatedImage (~> 1.0)
    - SDWebImage/Core
  - SDWebImage/WebP (4.0.0):
    - libwebp
    - SDWebImage/Core
```
### Issue Description and Steps

I know and I have read #1691 , but they are totally different. Because my problem is about the animated webp image, not the statics one, and also I have done some debug work.

Here are the URLs that can not be read:
http://s1.wmlives.com/data/dongci/opus_cover/20170807142940kKtadx
http://s1.wmlives.com/data/dongci/opus_cover/20170807140438ZFvCQ9
http://s1.wmlives.com/data/dongci/opus_cover/20170807041753vj2p8k

But, most URLs is just ok, like these:
http://s1.wmlives.com/data/dongci/opus_cover/2017080416_11176_ZxnLNlz6Gk.webp
http://s1.wmlives.com/data/dongci/opus_cover/2017080418_10065_vLeZsU6jcm.webp

The image below gets nil:
```
@implementation UIImage (MultiFormat)

+ (nullable UIImage *)sd_imageWithData:(nullable NSData *)data {
...
...
#ifdef SD_WEBP
    else if (imageFormat == SDImageFormatWebP)
    {
        image = [UIImage sd_imageWithWebPData:data];
    }
#endif
```
Continue debug shows that the image from `+ (nullable UIImage *)sd_blendWebpImageWithOriginImage:(nullable UIImage *)originImage iterator:(WebPIterator)iter` got nil image.

```
do {
        UIImage *image;
        if (iter.blend_method == WEBP_MUX_BLEND) {
            image = [self sd_blendWebpImageWithOriginImage:[images lastObject] iterator:iter];
        } else {
            image = [self sd_rawWepImageWithData:iter.fragment];
        }
        
        if (!image) {
            continue;
        }
        
        [images addObject:image];
        duration += iter.duration / 1000.0f;
        
    } while (WebPDemuxNextFrame(&iter));

```
First , the first time the do while loop run, it goto `if (iter.blend_method == WEBP_MUX_BLEND) {`, and there is not any image in the images, so `[images lastObject]` is nil obviously, which will return nil in `+ (nullable UIImage *)sd_blendWebpImageWithOriginImage:(nullable UIImage *)originImage iterator:(WebPIterator)iter`

Second, i have changed `if (iter.blend_method == WEBP_MUX_BLEND)` to `if (iter.blend_method == WEBP_MUX_BLEND && images.count > 0)` which will prevent it from goto nil for the first time, but the second time it gose to `+ (nullable UIImage *)sd_blendWebpImageWithOriginImage:(nullable UIImage *)originImage iterator:(WebPIterator)iter`,  it still get nil

Is there something wrong with the image itself(although the image can be played in Chrome), what can I do? Thanks!

**Comment by btxkenshin** [comment]
sorry, didn't saw the new version 4.1.0 which exactly solved the problem

**Comment by bpoplauschi** [comment]
@btxkenshin 👍

**Comment by bpoplauschi** [comment]
Related to #1952
