### ISSUE TITLE
loadImagecrashes

### ISSUE THREAD

**Issue by ghost** [rs/SDWebImage#1992]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info            sdwebImage        | Value    3.7.6                          |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 8.0
 SDWebImage Version      | e.g. 3.7.6
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 8.3
 Repro rate              | e.g. all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

When I use sdwebImage loading a lot of pictures, the memory will always increase, retired from the current VC, memory is not reduced, reload the picture memory will continue to increase, until the program crashes, this kind of situation only on iPhone7 and iphone7p appeared, look at the trouble.

**Comment by bpoplauschi** [comment]
@OnlineYoung please fill in the info required above in the issue template.
