### ISSUE TITLE
CancelImageLoadOperation may cause this bug?

### ISSUE THREAD

**Issue by VioletHill** [rs/SDWebImage#1996]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        | 9.0
 SDWebImage Version      | 3.8.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.3.2
 Repro rate              | all the time (100%) /
 Repro with our demo prj |
 Demo project link       | 

### Reset the URL for UIImageViewA will cause empty Image for UIImageViewB?

I've read the `SDWebImage` code, and found a bug(maybe) for SDWebImage. 

```
- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageCompletionBlock)completedBlock {
    [self sd_cancelCurrentImageLoad];
    //...
}
```
the problem is that what if UIImageViewA and UIImageViewB got the same URL, and then UIImageViewA  set a new URL, but UIImageViewB didn't change the URL. 

Because UIImageViewA set a new URL. the first thing it will do is cancel the `NSOperation`. but this operation is shared with UIImageViewB. So UIImageViewB will got the cancel operation and will not get the image.

To test that,  the following code will show that `self.imageViewB` could not get the image:

```
    NSArray *image = @[
                       @"http://www.weipet.cn/bixiong/images/pic/43.jpg",
                       @"http://www.weipet.cn/bixiong/images/pic/9086309.jpg",
                       @"http://c1.cdn.goumin.com/cms/petschool/day_141210/20141210_8ae7939.png",
                       @"http://desk.fd.zol-img.com.cn/t_s1680x1050c5/g5/M00/02/03/ChMkJ1bKxtqIXy1OAAi9LK5qQwgAALHrQK3PAoACL1E420.jpg",
                       @"http://www.redmaplenews.com/bbs/data/attachment/forum/201301/30/223812ejfibjevvj3n3ldh.jpg",
                       @"http://www.weipet.cn/bixiong/images/pic/b2-1.jpg",
                       @"https://4.bp.blogspot.com/-Uc1cshYSKy0/VyFnyanxMqI/AAAAAAAAAGM/JB2IH9UuTSIJ1CCqLHwOFIGIIUL7GRlVACKgB/s1600/201404211123518834.jpg"];
    for (int i = 0; i < image.count; i++) {
        UIImageView *imageView = [[UIImageView alloc] init];
        [imageView sd_setImageWithURL:image[i]];
    }
//make sure the  imageViewA's operation and imageViewB's operation doesn't execute

     [self.imageViewA sd_setImageWithURL:@"https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1502713596019&di=81318f5c8b5383978012eccad023ca31&imgtype=0&src=http%3A%2F%2Fatt.bbs.duowan.com%2Fforum%2F201406%2F20%2F114126lmv3zmpnozckkllq.jpg"];
  
    [self.imageViewB sd_setImageWithURL:@"https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1502713596019&di=81318f5c8b5383978012eccad023ca31&imgtype=0&src=http%3A%2F%2Fatt.bbs.duowan.com%2Fforum%2F201406%2F20%2F114126lmv3zmpnozckkllq.jpg"];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 1 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
        [self.imageViewA sd_setImageWithURL:@"https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1502713596019&di=ba893d856490e04de7bc5a800b21c167&imgtype=0&src=http%3A%2F%2Fimg3.duitang.com%2Fuploads%2Fitem%2F201202%2F24%2F20120224114616_wxxGx.jpg"];   
      //reset the imageViewA's URL will also cancel imageViewB's operation. So is this a bug?
    });
```

**Comment by lujie001122** [comment]
show your code

**Comment by dreampiggy** [comment]
Your worry about this case will not happens in SD 4.0. I check the code, for each URL, we will actually create only one NSOperation. But it can hold an array of callbacks for each progress block and completion block which passed by `sd_setImageWithURL:`.

For example, the code you provide will create an shared NSOpeartion `op` for actual download.

`UIImageViewA`'s completion block `blockA` will cause `op.callbacks[0] = blockA` (In fact, we have progress block and completion block so the item is an tuple like NSDictionary<NSString, dispatch_block_t>, but we keep things simple here).

`UIImageViewB`'s completion block `blockB` will cause `op.callbacks[1] = blockB`.

When one call cancel, it will check whether the `op.callbacks.count > 0` and only if it's empty, we cancel the internal NSURLSessionTask. So the example code above will not cause bugs.

You can check the code here : https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloaderOperation.m#L111

**Comment by dreampiggy** [comment]
Sadly it seems that old version SD 3.8.x do not have this consideration for this edge case. It just cancel the NSURLSessionTask whenever it received cancel call. So it may cause the bug you show.

You can see the code here:
https://github.com/rs/SDWebImage/blob/3.8.2/SDWebImage/SDWebImageDownloaderOperation.m#189

**Comment by bpoplauschi** [comment]
@VioletHill it's very important for us that you fill in the issue template, not leave the default values there. Please update it so we know which version you are talking about and more

**Comment by VioletHill** [comment]
@bpoplauschi Sorry for that didn't fill the issue template well. I will update soon
and  thanks for @dreampiggy.
