### ISSUE TITLE
-[UIImageView setImageWithURL:completed:]: unrecognized selector sent to instance 0x7fdb1ac69af0

### ISSUE THREAD

**Issue by coolboy-ccp** [rs/SDWebImage#2003]
'setImageWithURL:completed:'crash
the reason is '-[UIImageView setImageWithURL:completed:]: unrecognized selector sent to instance 0x7fdb1ac69af0'
happened on 
 "[_cardImg setImageWithURL:[NSURL URLWithString:str] completed:nil];"
'_cardImg' is kindof UIImageView.And it not nil

**Comment by dreampiggy** [comment]
Maybe `sd_setImageWithURL:completed:` ?

**Comment by bpoplauschi** [comment]
This looks like a crash on an older version of the library that probably needs a cleanup.
