### ISSUE TITLE
Too many gifs make the memory increases all the time,and then app crashed.

### ISSUE THREAD

**Issue by seanLee** [rs/SDWebImage#2004]
### New Issue Checklist

* [✅] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [✅ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [✅ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 8.0+
 SDWebImage Version      | 4.1.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 8.3.3
 Repro rate              | sometimes
 Repro with our demo prj | do not test

### Issue Description and Steps

Every time loads gif image make the memory increased.It seems make the iOS system kill down the app, but there is not crash log producing.Have run app in instruments,no memory leaps are shown.I dun know how to solve this problem.

**Comment by seanLee** [comment]
I check the steps of showing gifs,every time i set the ```animatedImage of FLAnimatedImageView ``` it wll gain the memory.

**Comment by dreampiggy** [comment]
https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImage.m#L239

If you create `FLAnimatedImage` with GIF data, acually it already do not retain the `UIImage` instance for each frame and keep it in the memory. It just check whether the image is valid and only save the first frame to use as poster image. The other CGImageRef will be released after each loop end. So I can't figure out why `gain the memory` will happen. But

**Comment by dreampiggy** [comment]
@seanLee Sorry, you means `set animatedImage to FLAnimatedImageView instance` ? This step you have that `FLAnimatedImage` instance. So the issue is why `FLAnimatedImageView` render consume a lot of memory. In fact, this may related to FLAnimatedImage, we can not fix that in SD side. Maybe you should consider to create an issue to [FLAnimatedImage issues](https://github.com/Flipboard/FLAnimatedImage/issues)

**Comment by seanLee** [comment]
@dreampiggy Ok~I will check again.Thanks very much.
