### ISSUE TITLE
"Other Linker Flags" setting is not found

### ISSUE THREAD

**Issue by Taillook** [rs/SDWebImage#2012]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description
["Other Linker Flags"](https://camo.githubusercontent.com/605afda81ea172bf876f8c52a7002ffebb27dd3a/687474703a2f2f646c2e64726f70626f782e636f6d2f752f3132333334362f5344576562496d6167652f31305f6f746865725f6c696e6b65725f666c6167732e6a7067) in https://github.com/rs/SDWebImage#installation-by-cloning-the-repository is 404(not found).
where should I access to see latest document?

**Comment by dreampiggy** [comment]
`Other Linker Flags` is just right on Xcode -> Project -> Build Settings -> Linking -> Other Linker Flags:

<img width="1280" alt="2017-09-04 10 30 32" src="https://user-images.githubusercontent.com/6919743/30030628-be2daf6a-91c0-11e7-8b5c-e0ac92d16b80.png">

Or simple: Go to Build Settings, use Command + F to search "Other Linker Flag" is faster.

**Comment by Taillook** [comment]
Thank you
The problem was solved.

If you have plenty of time, update the image please.

**Comment by dreampiggy** [comment]
Added this image into the tutorial.

**Comment by bpoplauschi** [comment]
Fixed by #2030
