### ISSUE TITLE
How to avoid SDWebImage scales gif image which load from bundle resource automatically

### ISSUE THREAD

**Issue by silenceleewq** [rs/SDWebImage#2015]
When I load a gif image from bundle resource use `UIImage+GIF.h`, my GIF image has shrunked 3 times.
so how to avoid this problem, is there any way to set some preference to avoid that shrink?

`
UIImage+GIF.m
[images addObject:[UIImage imageWithCGImage:image scale:[UIScreen mainScreen].scale orientation:UIImageOrientationUp]];
`

**Comment by dreampiggy** [comment]
`UIImage+GIF.h` now only contain the 1st frame image in SD 4.0. So please do not use this to decode GIF images.

If you prefer to use the 3.7.x version. Maybe you should change back the scale by yourself:

```objectivec
UIImage *gifImage; // Which created by that UIImage+GIF
SDScaledImageForKey(nil, gifImage);
```

`SDWebImageCompat` will set all the images frame scale to 1 if `url` is nil and maybe this can help you.
