### ISSUE TITLE
download image Issue

### ISSUE THREAD

**Issue by effortcheep** [rs/SDWebImage#2017]
like this url "http://img2.imgtn.bdimg.com/it/u=2129909692,4186700444&fm=27&gp=0.jpg"
can't download image,because this url has ","  ~ XD~

**Comment by dreampiggy** [comment]
The URL you provide is OK on our demo project(Simply change the URL in `MasterViewController.m` and run). In fact, SD use NSURL to constuct from the NSString. Please check the issue again, thanks.
