### ISSUE TITLE
How to download the file`SDWebImage iOS static`

### ISSUE THREAD

**Issue by jiexishede** [rs/SDWebImage#2018]
How to download the file`SDWebImage iOS static`

Now, I am using the React native. I run the command, this file isn't found.

**Comment by dreampiggy** [comment]
`xcodebuild clean build -workspace SDWebImage.xcworkspace -scheme 'SDWebImage iOS static' -sdk iphoneos -configuration Release`

Or to run Archive command in Xcode for that `SDWebImage iOS static` scheme.
