### ISSUE TITLE
2 compiler warning in Xcode 9 GM with Swift 3.2 project

### ISSUE THREAD

**Issue by ghowen** [rs/SDWebImage#2022]
Latest pod (4.1.0)

./Pods/SDWebImage/SDWebImage/SDWebImageCompat.h:98:39: This block declaration is not a prototype
`typedef void(^SDWebImageNoParamsBlock)();`

./Pods/SDWebImage/SDWebImage/SDWebImageDownloader.m:227:94: This block declaration is not a prototype
`- (nullable SDWebImageDownloadToken *)addProgressCallback:(SDWebImageDownloaderProgressBlock)progressBlock
                                           completedBlock:(SDWebImageDownloaderCompletedBlock)completedBlock
                                                   forURL:(nullable NSURL *)url
                                           createCallback:(SDWebImageDownloaderOperation *(^)())createCallback {`

**Comment by tsheaff** [comment]
Looks like this has been fixed here: https://github.com/rs/SDWebImage/commit/4d99ca6c86493003e44d4ecb5c69f31eb9303655

@DwayneCoussement can we get a new version with these changes pushed up to cocoapods?

**Comment by dreampiggy** [comment]
Added in 4d99ca6 and 05dfa6c. Will be available in 4.1.1

**Comment by bpoplauschi** [comment]
#2027
