### ISSUE TITLE
I access one problem that .refreashCache doesn't work

### ISSUE THREAD

**Issue by dtzxdf** [rs/SDWebImage#2029]
### New Issue Checklist

* [Y] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [Y] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [Y] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0
 SDWebImage Version      | latest
 Integration Method      | carthage
 Xcode Version           | Xcode9.0
 Repro rate              | 
all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps
![1](https://user-images.githubusercontent.com/20106102/30690211-fce8d652-9ef5-11e7-989f-902eaefd1806.png)
Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by dreampiggy** [comment]
You are right, this is a bug that the second time you load with`refreshCached` will receive an error. related issue is here: #1993. And the Fix is in master branch.

**Comment by dtzxdf** [comment]
Good job

**Comment by dtzxdf** [comment]
When can i fix this bug by Carthage?I use "Carthage update --platform iOS" there is nothing happend...
