### ISSUE TITLE
iOS 11 crash in table

### ISSUE THREAD

**Issue by GBChain** [rs/SDWebImage#2037]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 11
 SDWebImage Version      | e.g. 4.0.0
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 9
 Repro rate              | e.g. all the time (100%) 

### Issue Description and Steps

 tableCell  with 640*640  images，when download and display， image = [UIImage decodedImageWithImage:image]; will cost too much resource and lead
 to crash and also lead to block

**Comment by GBChain** [comment]
remove this line  will make zhe table smooth and fast

**Comment by dreampiggy** [comment]
set `shouldDecompressImages` to NO for `SDWebImageDownloader.sharedDownloader`. This is used for decoding the image from data to bitmap before rendering in tableview to increase a little frame rate. But it will cost more memory.
