### ISSUE TITLE
 iPhone7 and above models discharged live format photos, is ". Heic" format

### ISSUE THREAD

**Issue by PengfeiWang666** [rs/SDWebImage#2038]
### New Issue Checklist

* [ yes] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [yes ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ yes] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        | 11.0
 SDWebImage Version      | e.g. 3.7.6
 Integration Method      | manually
 Xcode Version           | Xcode 9.0

iPhone7 and above models discharged live format photos, is ". Heic" format, after repeated verification, the judgment is feasible, that ImageData is not nil, but the first character is nil

Here show the code！

NSData+ImageContentType.h

+ (SDImageFormat)sd_imageFormatForImageData:(nullable NSData *)data {
    if (!data) {
        return SDImageFormatUndefined;
    }
    
    uint8_t c;
    [data getBytes:&c length:1];
    switch (c) {
        case 0xFF:
            return SDImageFormatJPEG;
        case 0x89:
            return SDImageFormatPNG;
        case 0x47:
            return SDImageFormatGIF;
        case 0x49:
        case 0x4D:
            return SDImageFormatTIFF;
        case 0x52:
            // R as RIFF for WEBP
            if (data.length < 12) {
                return SDImageFormatUndefined;
            }
            
            NSString *testString = [[NSString alloc] initWithData:[data subdataWithRange:NSMakeRange(0, 12)] encoding:NSASCIIStringEncoding];
            if ([testString hasPrefix:@"RIFF"] && [testString hasSuffix:@"WEBP"]) {
                return SDImageFormatWebP;
            }
    }
    if (!c) {
        return SDImageFormatHEIC;
    }
    return SDImageFormatUndefined;
}

**Comment by dreampiggy** [comment]
So this image format will fail for that HEIC format. We currently not support that image format here. Could you please provide one image data here(let use download) and to check that magic bytes(The first byte) ?

**Comment by PengfeiWang666** [comment]
Sorry I have no heic format image url, because the current social software does not support the format, but you can use iPhone 7 + iOS11 shooting "live" format picture, that is heic format

**Comment by PengfeiWang666** [comment]
Although the current SDWebImage does not support downloading heic format images, but I can use the scene is this: send the original image, I through the Category to determine the type of picture, if it is ". Heic" format picture, I will be converted to jpg format

**Comment by dreampiggy** [comment]
@PengfeiWang666 Start with iOS 11, HEIC is a implementation of that HEIF. This is natively support by iOS's CGImage and transparentlly supporet all UIKit interface. When you call `[UIImage imageWithData:]` with an HEIC image file, it can sucessfully be decoded and produce an UIImage. So infact, SDWebImage nativelly support this format in previous version.

But now, we just do not have that imageFormat enum. So I can add one and update the related things.(For example, our Image IO coder mark `canDecodFromFormat` with a switch case. Ready for SD 4.2. (Attension, you can download and decoding HEIC in previous release with no issues. Only need your device run iOS 11)

**Comment by bpoplauschi** [comment]
@dreampiggy ok. I think this is a duplicate for #1853

**Comment by bpoplauschi** [comment]
Fixed by #2080
