### ISSUE TITLE
iOS 11 image can't store "SDWebImageRefreshCached"

### ISSUE THREAD

**Issue by ominfowaveIOS** [rs/SDWebImage#2041]
our code is working fine ios 10 
but IOS 11 not work SDWebImageRefreshCached 

 **image loading  code :** 

[images sd_setImageWithURL:[NSURL URLWithString:encodedUrl]
                          placeholderImage:[UIImage imageNamed:@"topicon"]
                                   options:SDWebImageRefreshCached];

**Comment by dreampiggy** [comment]
Dumplicated for #1993 . We have merge the fix commit this to master. Maybe we should release 4.1.1 soon.
