### ISSUE TITLE
No visible @interface for 'SDWebImageManager' declares the selector 'downloadImageWithURL:options:progress:completed:'

### ISSUE THREAD

**Issue by HTOne** [rs/SDWebImage#2045]
No visible @interface for 'SDWebImageManager' declares the selector 'downloadImageWithURL:options:progress:completed:'

**Comment by dreampiggy** [comment]
Please use our issue template and provide the information about SD Version, OS Version and more others.

This issue is about header files. Try check whether you have import that `SDWebImageManager` or that `SDWebImage.h` umbrella header.

**Comment by mtf211** [comment]
I had this issue as well, that selector is now called loadImageWithURL and the completion block adds an NSData *data return.

**Comment by dreampiggy** [comment]
@HTOne This method selector has been renamed during 4.0. You can check that [SDWebImage-4.0-Migration-guide](https://github.com/rs/SDWebImage/blob/master/Docs/SDWebImage-4.0-Migration-guide.md)
