### ISSUE TITLE
Apple rejected build because it links against MapKit and not uses it

### ISSUE THREAD

**Issue by cp3hnu** [rs/SDWebImage#2056]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | mac 
 Platform Version        | 10.12
 SDWebImage Version      | 4.1.0
 Integration Method      | carthage
 Xcode Version           | Xcode 8.3.3

Guideline 2.1 - Performance

Your app links against the MapKit framework but does not appear to include Maps functionality. 

Next Steps

If your app does include Maps functionality, please respond to this message in Resolution Center with steps on how to locate it within your app.

If you do not intend to use Maps, please unlink the MapKit framework. If you would like to use Maps, please add the "com.apple.developer.maps" entitlement and submit an updated binary for review.

Resources

For information on Maps, please review the Location and Maps Programming Guide.

If you are using a third-party framework that links against the MapKit framework, you may want to contact the third-party framework provider for help on unlinking from it.

**Comment by bpoplauschi** [comment]
@cp3hnu please fill in the issue template info above. Also, are you sure this is about SDWebImage? We do link against MapKit, but only if you explicitly picked the MapKit subcomponent of our project.

**Comment by cp3hnu** [comment]
I found in MKAnnotationView+WebCache.h
#import <MapKit/MapKit.h>

**Comment by bpoplauschi** [comment]
@cp3hnu I see you are using Carthage. From what I know, Carthage doesn't allow selecting subcomponents from a framework and since our targets include all the files, they will contain MapKit.
One option I see right away is to integrate SDWebImage via CocoaPods. There you have the option to use `pod SDWebImage/Core` which doesn't contain any of the MapKit files.
