### ISSUE TITLE
completed: completion block not called

### ISSUE THREAD

**Issue by thechaudharysab** [rs/SDWebImage#2062]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 10.3
 SDWebImage Version      | e.g. 4.1.2
 Integration Method      |  cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | 
 Repro with our demo prj | No
 Demo project link       | 

### Issue Description and Steps

There are similar but that didn't have proper answers and are very old.
I've a string in which I've comma separated images URL and I'm splitting it into array as: l`et imagesLinks = imageLins.components(separatedBy: ",")`. Next by using for loop I'm storing the downloaded images in an imagesArray as:

```
for imag in imagesLinks
        {
            let img = UIImageView()
            let activityIndicator: UIActivityIndicatorView = UIActivityIndicatorView.init(activityIndicatorStyle: .white)
            let refreshBarButton: UIBarButtonItem = UIBarButtonItem(customView: activityIndicator)
            self.navigationItem.rightBarButtonItem = refreshBarButton
            activityIndicator.startAnimating()
            let imgURL: URL = URL(string: "\(baseReportImageURL)\(imag)")!
            img.sd_setImage(with: imgURL, completed: {
                (image, error, cacheType, url) in
                activityIndicator.stopAnimating()
                imagesArray.append(image!)
                self.photoCollection.reloadData()
            })
//            img.sd_setImage(with: imgURL, placeholderImage: nil,options: SDWebImageOptions(rawValue: 0), completed: { (image, error, cacheType, imageURL) in
//                //activityIndicator.stopAnimating()
//                imagesArray.append(image!)
//                self.photoCollection.reloadData()
//            })
        }
```
Now the issue is that it send the call but did the completed: block is not called. If I go back and push the view controller again it goes in the completed: block instantly. So my assumption is that it might have downloaded and cache the images and when it is again called it check the images are already downloaded so it run the block at that time. **But why is it skipping it for the first time?**

Secondly I'm calling a custom function from `viewDidLoad()` in a custom function called `func` `downloadAndUpdateImagesAarray()` inside this I've the for loop. Also `self.photoCollection.reloadData()` is a collection view on which the cell only have an image.

**Comment by bpoplauschi** [comment]
@thechaudharysab you need to debug in detail and bring some more info. Right now it's too vague. Also, you should try it with out demo project and see if you can repro the issue there.

**Comment by dreampiggy** [comment]
@thechaudharysab Could you please more detail information since this looks strange. Our demo project work well with that completion block.

**Comment by thechaudharysab** [comment]
@dreampiggy I'm not using it in table view. For tableView this works great you can say I'm downloading the image from web and when it is downloading I'm storing it in a UIImage array.

**Comment by dreampiggy** [comment]
I think it's because the image instance is dealloc because we do not keep a strong reference for UIView instance. Since you create a temp imageView instance during a loop, this could happen.
