### ISSUE TITLE
custom header for sd_setImage 

### ISSUE THREAD

**Issue by santhoshs5** [rs/SDWebImage#2063]
How can I pass custom header for the following method

  imageView.sd_setImage(with: photoURL, placeholderImage: UIImage(named: "default")

**Comment by bpoplauschi** [comment]
The only way to set/pass headers is via `SDWebImageDownloader setValue:forHTTPHeaderField:`.
Example:
```
[[SDWebImageDownloader sharedDownloader] setValue:@"image/*" forHTTPHeaderField:@"Accept"];
```

**Comment by JuanCepeda** [comment]
@bpoplauschi I can´t see the setValue:@"image/*" forHTTPHeaderField in swift, can you please help me?

**Comment by bpoplauschi** [comment]
@JuanCepeda see https://sdwebimage.github.io/Classes/SDWebImageDownloader.html#/c:objc(cs)SDWebImageDownloader(im)setValue:forHTTPHeaderField:

```swift
SDWebImageDownloader.shared.setValue("image/*", forHTTPHeaderField: "Accept"]
```

Hope I got it right
