### ISSUE TITLE
V4.0 not support webp format，which version start support webp？

### ISSUE THREAD

**Issue by Tracydeng** [rs/SDWebImage#2065]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS
 Platform Version        | 11.0.3
 SDWebImage Version      |  4.0
 Integration Method      |  cocoapods 
 Xcode Version           |  Xcode 9.0

### Issue Description and Steps

when i debug， found this code in `UIImage+MultiFormat.m`，but this version contains ``UIImage+WebP``：

    #ifdef SD_WEBP
        else if (imageFormat == SDImageFormatWebP)
        {
            image = [UIImage sd_imageWithWebPData:data];
        }
    #endif

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by bpoplauschi** [comment]
@Tracydeng we are supporting WebP format for quite a while (even our 3.x versions have WebP), but you need to be explicit with CocoaPods: `pod 'SDWebImage/WebP'`. This is because WebP is a subspec with its own dependencies and not everybody wants it.

**Comment by Tracydeng** [comment]
Get, thanks 。
