### ISSUE TITLE
Memory issues when setting image with URL

### ISSUE THREAD

**Issue by juliusbtesh** [rs/SDWebImage#2072]
I have been trying to search for an an answer for this for a little while now but I am having no such luck. I am using the below function to set an image from a url into my cells. But as I am scrolling through more and more results and more of these functions get called, the device memory shoots up and up and up. (following through Xcode)

`[self sd_setImageWithURL:url
            placeholderImage:[UIImage imageNamed:placeHolder]
                     options:SDWebImageScaleDownLargeImages];`

However if I use a simple code for downloading images like below, I don't notice any memory jumps. (The only problem is the sluggish loading and non cached images)

`NSData *imageData = [NSData dataWithContentsOfURL:url];
self.image = [UIImage imageWithData:imageData];`

Can someone please explain to me why the SDWebImage option is causing such a huge memory spike?

**Comment by bpoplauschi** [comment]
@juliusbtesh there are a few things to consider:
- by default, we keep all images in the memory cache which may increase memory usage, but also increases performance and this memory cache is evicted when memory is low
- but you can disable this
- also, we decompress the images on a background thread, which also takes up resources, so they are faster to display. When you use `UIImage imageWithData:`, the image is not decompressed, so when you add that image to a `UIImageView` it will be decompressed on the main thread which makes the FPS drop. It's a trade-off. 
- this decompressing can also be disabled.
- there are a few issues on this project that describe how to deal with memory consumption (it's a trade-off from app to app) - just search for them

PS: never ever use `NSData *imageData = [NSData dataWithContentsOfURL:url];`. It's a synchronous API that blocks the current thread until all the data is downloaded. :)

**Comment by juliusbtesh** [comment]
Well I wasn't going to use `NSData *imageData = [NSData dataWithContentsOfURL:url];` - I know that it would not work right. I just wanted to see memory comparison between the two of them.

I'm not entirely sure the memory was being evicted though because I was seeing a lot of Out-Of-Memory crashes and I can only assume this was due to the memory usage from these images. I have checked out the other areas of the app and I can't place it on any other area.

**Comment by lastcc** [comment]
@juliusbtesh This is because the image is too large and iOS may have hardware limitations and too many draw calls can crash the app. 
@bpoplauschi 
There are ways to down scale a large image into a smaller version without decoding. You can use ImageIO APIs. And you can serialized draw calls if the images are really really large. 

Are u loading large images from high speed network?

**Comment by dreampiggy** [comment]
@lastcc Yes. FOr scale down image for Image/IO supported format(JPEG, PNG, GIF and so on, without WebP). We can use Image/IO's API `CGImageDestinationAddImageFromSource` and scale down the image format. But our built-in coder has previously a decoding and decompressing logic which we just keep it. If you need this , you can try our 4.2.0 and above version ,which support custom coder and you can build your own.

**Comment by dreampiggy** [comment]
Actually, `[UIImage imageWithData:] do nothing without just leave a placeholder to indicate that this image bitmap is not ready. When you se this kind of UIImage to `UIImageView`. It will try to decoding immediately and your memory usage will increase.

But SDWebImage its most case is to directlly set image on UIImageView and we do not want this `decoding` happended on main queue to block UI. So we introduce `shouldDecompress` option, which will decompress image on the background queue before set image. So you will see the memory increase.

`SDWebImageScaleDownLargeImages` is based on `shouldDecompress` and will try to scale the large resolution image (only JPEG format) to small resolution image. (But this code seems not update to the latest iOS devices :) )
