### ISSUE TITLE
The image corresponds to the same url and the picture resource has changed

### ISSUE THREAD

**Issue by xiu619544553** [rs/SDWebImage#2075]
When the url does not change, the image resource of the url changes.I has set up 'options:SDWebImageRefreshCached',but the UI doesn't refresh.How to solve this problem?

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 8.0
 SDWebImage Version      | e.g. 4.1.1
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 9.0
 Repro rate              | e.g. all the time (100%) 

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by bpoplauschi** [comment]
Please try upgrading to the latest version 4.1.2 which has a fix for exactly this problem.

**Comment by xiu619544553** [comment]
Currently my pods version is 1.3.1, but I can't search for SDWebImae latest version 4.1.2.   The version I searched for was 4.1.1

**Comment by bpoplauschi** [comment]
@xiu619544553 please fill in the table info in the description so I know which version are you using and which installation method. Note that 4.1.2 is released already.

**Comment by snamrata007** [comment]
I also have same problem & trying with latest version but unfortunately its not working.
