### ISSUE TITLE
Compiler warning in SDWebImage 4.2.0

### ISSUE THREAD

**Issue by ghowen** [rs/SDWebImage#2086]
### New Issue Checklist

* [ x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11
 SDWebImage Version      | 4.2.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.0.1
 Repro rate              | e.g. all the time (100%)
Swift 4 project

### Issue Description and Steps

Using the pod in a Swift 4 project triggers this Swift Compiler Warning:

/myapp<module-includes>:1:1: Umbrella header for module 'SDWebImage' does not include header 'SDWebImageDecoder.h'

**Comment by bpoplauschi** [comment]
@ghowen try clean-build or even refresh CocoaPods. This file `SDWebImageDecoder.h` does not exist.

**Comment by ghowen** [comment]
Thanks. Clean-build did it.
