### ISSUE TITLE
What the function of SDWebImageDownloaderOperation‘s start: method?

### ISSUE THREAD

**Issue by Beyond-Chao** [rs/SDWebImage#2087]
The method '- (void)start' in SDWebImageDownloaderOperation.m file seems none caller. What function of that method ? Thanks for you reply!

**Comment by bpoplauschi** [comment]
@Beyond-Chao `SDWebImageDownloaderOperation` is a subclass of `NSOperation`. The `start` method is defined there and is called when the `NSOperation` is started (in our case when added to the `NSOperationQueue`).
