### ISSUE TITLE
Completion block called asynchronously when image is in memory cache

### ISSUE THREAD

**Issue by pmiaskiewicz** [rs/SDWebImage#2092]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 11.1
 SDWebImage Version      | 4.2.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.1
 Repro rate              | 100%

### Issue Description and Steps
Memory cache enabled.

1. Load image from network
2. Load it again

Observed:
For blink of an eye placeholder is visible

Expected:
After calling ```sd_setImage``` if image is in memory cache, completion block should be called in same run loop.

After some investigation I think issue is in this file:
UIView+WebCache.m

```objc
dispatch_queue_t targetQueue = shouldUseGlobalQueue ? dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0) : dispatch_get_main_queue();

dispatch_async(targetQueue, ^{
     [sself sd_setImage:targetImage imageData:targetData basedOnClassOrViaCustomSetImageBlock:setImageBlock];
     dispatch_main_async_safe(callCompletedBlockClojure);
});
```

for example when commenting out first dispatch_async, all works as expected.

```objc
dispatch_queue_t targetQueue = shouldUseGlobalQueue ? dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0) : dispatch_get_main_queue();

// dispatch_async(targetQueue, ^{
     [sself sd_setImage:targetImage imageData:targetData basedOnClassOrViaCustomSetImageBlock:setImageBlock];
     dispatch_main_async_safe(callCompletedBlockClojure);
// });
```

Maybe I am missing something but one solution I see is to not double dispatch it:

```objc
// Just store final block that later will be either dispatched or just executed
 void (^completionBlock)(void) = ^{
     [sself sd_setImage:targetImage imageData:targetData basedOnClassOrViaCustomSetImageBlock:setImageBlock];
     dispatch_main_async_safe(callCompletedBlockClojure);
};

 if (shouldUseGlobalQueue) {
     dispatch_queue_t targetQueue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0);
     dispatch_async(targetQueue, ^{
          completionBlock();
     });
} else {
     completionBlock();
}
```

Worth to mention I was not testing it with GIF images (only place when shouldUseGlobalQueue is true). I am not sure if in any case we should push completion in the next run loop when image is already in memory.

**Comment by dreampiggy** [comment]
Maybe this is true. This code was changed during last 4.2.0 refactor which increase the GIF performance by moving set-image-block to global queue. But at that time we didn't find this internal changes to queue order.(We dispatch that queue instead of check current thread) This should be changed to this:

```objectivec
            if (shouldUseGlobalQueue) {
                dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
                    [sself sd_setImage:targetImage imageData:targetData basedOnClassOrViaCustomSetImageBlock:setImageBlock];
                    dispatch_main_async_safe(callCompletedBlockClojure);
                });
            } else {
                dispatch_main_async_safe(^{
                    [sself sd_setImage:targetImage imageData:targetData basedOnClassOrViaCustomSetImageBlock:setImageBlock];
                    callCompletedBlockClojure();
                });
            }
```

**Comment by dreampiggy** [comment]
@pmiaskiewicz Please have a look at this #2093

**Comment by bpoplauschi** [comment]
Fixed by #2093

**Comment by yichengchen** [comment]
I found when we use the FLAnimateedImageView which enable shouldUseGlobalQueue by default still cause imageview blink and flash when tableview/collection reload. especially obviously in iOS9. I thought it's bette to make it user configurable.

**Comment by dreampiggy** [comment]
@yichengchen Could you please create another issue and provide a little demo. I think maybe we enter something wrong with last performance enhancement.

**Comment by yichengchen** [comment]
@dreampiggy I have create issue here #2102
