### ISSUE TITLE
Image can not show

### ISSUE THREAD

**Issue by chengyinglpl** [rs/SDWebImage#2094]
I have a image url with "http://ibwp6w.natappfree.cc:80/realty/image/20171103/150969678804800005.jpg".
I try to use  
 [imageView sd_setImageWithURL:[NSURL URLWithString:@"http://ibwp6w.natappfree.cc:80/realty/image/20171103/150969678804800005.jpg"]]; 
to show the image ,but it can't.
when I use webview it can show , what's wrong with me?

**Comment by dreampiggy** [comment]
```
> po error.localizedDescription
The operation couldn’t be completed. (NSURLErrorDomain error 404.)
```

You should replace that `:80`, use `http://ibwp6w.natappfree.cc/realty/image/20171103/150969678804800005.jpg` instead

**Comment by chengyinglpl** [comment]
Thank you for your answer，
But why does a port appear 404 .
I found that android can load images.

**Comment by dreampiggy** [comment]
> contact to that image server provider to identify the issue.(I think it's Web backend proxy's issue since the request header is actually valid)

This is not what a bug or something. The request has sent to your server, but it respond 404. You can check the difference between two client using Charles or Wireshark(Network Debuggin tool) and find the reason.

**Comment by bpoplauschi** [comment]
Closing based on the response above
