### ISSUE TITLE
Why does this method "diskImageExistsWithKey with completionBlock" not callback?

### ISSUE THREAD

**Issue by Daemonson** [rs/SDWebImage#2098]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 9.0
 SDWebImage Version      | e.g. 4.2.0
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 9.0
 Repro rate              | e.g. all the time (100%)
 Repro with our demo prj | e.g. No
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps
![image](https://user-images.githubusercontent.com/7628550/32530001-9650cdcc-c476-11e7-88c6-916e19d25377.png)

The line 278 of source code "SDImageCache.h" does not execute. I called the  method "diskImageExistsWithKey:completion:" on didFinishLaunchingWithOptions.

**Comment by dreampiggy** [comment]
Can not reproduced. What's your usage or a demo project ?

**Comment by Daemonson** [comment]
I resolved my problem。Before the completionBlock callback, Application has thrown an exception because of not set a root view controller at the end of application launch.
