### ISSUE TITLE
For Background color, how can we set this url to image?

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [rs/SDWebImage#2099]
Thanks for the great library. Its working great. But, I have following issue

```
For imageview, we are setting like

                        eventImageView.sd_setImage(with: URL(string: imageUrl), placeholderImage: UIImage(named: "placeholder.png"))

but, for uicolor with image,

self.scrollView.backgroundColor = UIColor(patternImage: image!)

```
how to call that method?

**Comment by bpoplauschi** [comment]
@AnilkumarRabhasa you can try to download the image using `SDWebImageManager` and use that image inside the completion block to create and set the `UIColor`:
```
SDWebImageManager.shared().loadImage(with: url) { (image, data, error, cacheType, done, _) in
  self.scrollView.backgroundColor = UIColor(patternImage: image)
}
```

**Comment by AnilkumarRabhasa** [comment]
I tried, but showing "SDWebImageManager" is not declared identifier like that, for that do I need to download any other pod from SDWebImage?

**Comment by bpoplauschi** [comment]
I don't understand how `SDWebImageManager` is not a declared identifier. This class is in the library from the beginning.
