### ISSUE TITLE
How to set custom cache key, not use url as key?

### ISSUE THREAD

**Issue by junestchick** [rs/SDWebImage#2103]
Hi, 
I use a collectionView to load images in cells. Urls are from S3, they are always changes, not static urls. So I want to set a custom cache key for each cell(like cell's "\(indexPath.row)+\(indexPath.section)" ). 
Anyway to do that? Thanks.

**Comment by bpoplauschi** [comment]
@junestchick there is one mechanism for customising the way we compute the cache key:
```
[[SDWebImageManager sharedManager] setCacheKeyFilter:^(NSURL *url) {
    ...
    return keyAsString;
}];
```
But the thing is this is a block you set once and you can only use the url to make the computation, but maybe you can keep a map structure like (url, row/section) and go from there.

**Comment by dreampiggy** [comment]
For 5.x user, use the request modifier:

```
```swift
let requestModifier = SDWebImageDownloaderRequestModifier {
    var request = $0
    request.setValue("MyValue", forHTTPHeaderField: "MyHeader")
    return request
}
let context: [SDWebImageContextOption: Any] = [.downloadRequestModifier: requestModifier]
imageView.sd_setImage(with: url, context: context)
```
