### ISSUE TITLE
When I download the image and the "expectedSize" has always been 0, why is that?

### ISSUE THREAD

**Issue by BirdsAndFish** [rs/SDWebImage#2104]
When I download the image and the "expectedSize" has always been 0, why?
![snip20171114_1](https://user-images.githubusercontent.com/13975743/32774793-6c6fbb16-c968-11e7-8fc5-91afa04b48cf.png)

**Comment by bpoplauschi** [comment]
@BirdsAndFish probably because the response from the server is missing `Content-Length` HTTP header field. We are getting the expected size from that. See #334
