### ISSUE TITLE
Can't access ioQueue from swift

### ISSUE THREAD

**Issue by shaljam** [rs/SDWebImage#2108]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0.3
 SDWebImage Version      | 4.2.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.1
 Repro rate              | n/a
 Repro with our demo prj | n/a
 Demo project link       | n/a

### Issue Description and Steps

How can I access `SDImageCache`'s `ioQueue` from swift?

**Comment by dreampiggy** [comment]
You should not acess even in Objective-C...Well, unless you use KVC or Runtime methods.

What's your use case to acess that `ioQueue`? its should be used internal but not public.

**Comment by shaljam** [comment]
I'm trying to only cache image data with `storeImageData`. For now I'm using `store(UIImage(), imageData:  forKey: , toDisk: ,completion: nil)` with a dummy `UIImage`.

**Comment by dreampiggy** [comment]
Well...You do not want to save image into memory? Just data ? 
`storeImageDataToDisk:forKey` have a strange `checkIfQueueIsIOQueue`...I do not know why it just log something but not `assert`. So maybe you counld not use this for async function call.

`SDImageCache` is not a common mem-disk cache from its design. But you can just use that `NSFileManager` API with `defaultCachePathForKey` to save any `NSData` to disk. Can this solve your problem?

Or, if you do not have any other ways. Try to use KVC in swift `value(forKey:)` to acess that one. Attention this is internal property so it can be changed at any update version.(Though I think this may not change in nearly future)

**Comment by shaljam** [comment]
@dreampiggy Yes, that's encrypted image data.
Thanks for the info. I think I should go for a general data cache.
