### ISSUE TITLE
startPrefetchingAtIndex accident crash. SingleObjectArray object at index.

### ISSUE THREAD

**Issue by lolgear** [rs/SDWebImage#2110]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 11.1.2
 SDWebImage Version      | 4.1.0
 Integration Method      |  cocoapods
 Xcode Version           | Xcode 9.1.1
 Repro rate              |  sometimes ?%

### Issue Description and Steps

I've got a crash.

```
#2 -[__NSSingleObjectArrayI objectAtIndex:]
#3 SDWebImage: __48-[SDWebImagePrefetcher startPrefetchingAtIndex:]_block_invoke
```

```objective-c
            [self.delegate imagePrefetcher:self
                            didPrefetchURL:self.prefetchURLs[index] // <- here
                             finishedCount:self.finishedCount
                                totalCount:self.prefetchURLs.count];
```

**Comment by dreampiggy** [comment]
Counld you please provide the full stacktrace for us to analysis this issue ?
I think maybe it's about some race condition that the `prefetchURLs` property has been changed when `loadImageWithURL` completion called. Do you call `cancel` outisde main queue ?

**Comment by lolgear** [comment]
@dreampiggy maybe it is better to copy url instead?

```objective-c
NSURL *currentURL = [self.prefetchURLs[index] copy];
```

**Comment by dreampiggy** [comment]
@lolgear Maybe not. `NSArray` already retain your `NSURL` instance. So a copy will not work for any lifecycle improvement. So just capture is OK :)

**Comment by lolgear** [comment]
@dreampiggy notes to your previous question:

I call 

```objective-c
[self.prefetcher prefetchURLs:urls];
```

in core data private context ( a.k.a background ).

**Comment by dreampiggy** [comment]
@lolgear I see. The `loadImageWithURL` completion block is always called on main queue (currently, but now doc point this out). So if you try acess that `prefetchURLs` properties outside main queue, there may be a multi-thread race condition.

**Comment by lolgear** [comment]
@dreampiggy so, the current fix would be dispatching invocation of set prepared urls on main thread?

**Comment by dreampiggy** [comment]
@lolgear The fix I provided #2111 will use atomic lock to ensure multi-thread-safe and retain the `NSURL` by advance to avoid that prepared urls changes and NSArray out of bounds. Maybe a better way is welcomed, but this fix seems `simple and crude` :)

**Comment by lolgear** [comment]
@dreampiggy I mean the fix on current version.

**Comment by dreampiggy** [comment]
@lolgear 😅 You can use `prefetcherQueue` to ensure all the operation happened on main queue to avoid this. (Don't worry, network request is always happended on background queue using NSURLSession)...But I think a better way is to wait for a new patch version release.

**Comment by dreampiggy** [comment]
@bpoplauschi Any plan to review the patches for 4.2.3 ? :)

**Comment by dreampiggy** [comment]
Merged. Wait for 4.2.3 release :)
