### ISSUE TITLE
Crash in method implementation of sd_cancelImageLoadOperationWithKey

### ISSUE THREAD

**Issue by itatawy** [rs/SDWebImage#2113]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.1.2
 SDWebImage Version      | 4.2.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.1
 Repro rate              | sometimes 50,000 crash in a week for half million users 
 Repro with our demo prj | NO

### Issue Description and Steps
App crashes randomly in this method 
- (void)sd_cancelImageLoadOperationWithKey:(nullable NSString *)key;
At this line 
id operations = operationDictionary[key];
Telling EXC_Bad_ACCESS
it happens alot and don't know what's cause and how to solve it. It's a very annoying issue and been for a while

**Comment by dreampiggy** [comment]
Hi. Coundl you please attach some stack trace for us to analysis ? (Maybe from your app's crash log or some third-party service like Fabric)

**Comment by itatawy** [comment]
I'm not using Fabric and I'm sure it's not because of any other thing 
Here is where it crashes
![screen shot 2017-11-23 at 5 13 26 pm](https://user-images.githubusercontent.com/28898227/33179322-b25d976e-d071-11e7-8134-0e8f9c6d6496.png)

**Comment by dreampiggy** [comment]
This looks like a multi-thread issue. That `SDOperationsDictionary` should have a lock or make acesss into the same queue.

Does the previous version SDWebImage also have this crash ? And also about the crash ratio ?(50,000 per week seems really big)

**Comment by itatawy** [comment]
Yes, it's been there forever but from version 4.1.2 it became much more than before. 
Here is a chart about last week that increase was after updating to version 4.1.2 

![screen shot 2017-11-23 at 6 25 26 pm](https://user-images.githubusercontent.com/28898227/33182220-c0d049d6-d07b-11e7-87c8-ebc05fe0ac13.png)

**Comment by dreampiggy** [comment]
@itatawy Well...We can fix it soon by make all the acess(read and write) to that `SDOperationsDictionary` thread-safe. Maybe in next patch version 4.2.3. I'll create a pull request it later.

**Comment by itatawy** [comment]
Good. I just need to know is there any timeline for that fix. As as you see there is a lot of crashes and our customers are complaining so, We want to take a decision if it's going to be a quick fix will wait if not will downgrade to 4.0.0 till the fix is done.

**Comment by dreampiggy** [comment]
@itatawy If you can ensure that the earily version crash ratio is lower, you can have a try. The patch version may be released in week.

Or if you really need hot fix, you can try to swizzle that method using Objective-C runtime(really not encouraged, but it's a way). You can check the #2114 for the fix. :)

**Comment by dreampiggy** [comment]
Wait...I have a question. Do you call any `UIView+WebCache`/`UIView+WebCacheOperation` methods from background queue ? If all the operattion happended on main queue. There should not have any multi-thread problem.

**Comment by itatawy** [comment]
No we don't What i call is just 
imageView.sd_setImage(with: Foundation.URL(string: encodedURL)!, placeholderImage: placeholderImage, options: SDWebImageOptions.retryFailed , completed: { (image, error, type, url)
from UIView I'll make it in a main block to be 100% sure but it's a straight forward call from CollectionVIewCell

**Comment by dreampiggy** [comment]
Fixed via #2132
