### ISSUE TITLE
Download Image and store to cache for key 

### ISSUE THREAD

**Issue by lemarian** [rs/SDWebImage#2117]
I want to store the image in a key and fetch image later. This is my block of code :

    SDWebImageManager.shared().imageDownloader?.downloadImage(with: URL.init(string: url), options: SDWebImageDownloaderOptions.highPriority, progress: { (receivedSize:Int,expectedSize:Int,url : URL?) in
      print("progressing here in this block ")
    }, completed: ({(image : UIImage, data : Data,error : Error, finished : Bool)  in
      print("reached in the completion block ")
    
      if finished {
        SDImageCache.shared().store(image, forKey: "d", toDisk: true, completion: nil)
      } else {
        print(error.localizedDescription)
        showAlert(viewController: self, title: "", message: error.localizedDescription)
      }           
    } as? SDWebImageDownloaderCompletedBlock))

However, the completion block is never called. 
Took reference from : https://stackoverflow.com/questions/14902835/sdwebimage-download-image-and-store-to-cache-for-key

**Comment by dreampiggy** [comment]
Please use `cacheKeyFilter` property in `SDWebImageManager` instead of this. It's more suitable and more easy to use.

And this completion block should be called. Don't you get something error in log ?
