### ISSUE TITLE
SDWebImageDownloader and canceled operations...

### ISSUE THREAD

**Issue by JoshJacobAtHanson** [rs/SDWebImage#2118]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 10.0
 SDWebImage Version      | e.g. 4.2.2
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 9.1
 Repro rate              | e.g. sometimes
 Repro with our demo prj | e.g. no
 Demo project link       | e.g. n/a

### Issue Description and Steps

Our app uses a UICollectionView with SDWebImage loading image views in the collection view cells. We occasionally see the placeholder remaining when scrolling the cell in, out and then back into view. The same image would never load even when the collection view cell and image view would be recreated.

Note that we do call `sd_cancelCurrentImageLoad` when the cell disappears off screen.

After isolating/debugging we discovered that in the method:

```
- (nullable SDWebImageDownloadToken *)
    addProgressCallback:(SDWebImageDownloaderProgressBlock)progressBlock
    completedBlock:(SDWebImageDownloaderCompletedBlock)completedBlock
    forURL:(nullable NSURL *)url
    createCallback:(SDWebImageDownloaderOperation *(^)(void))createCallback
```

canceled operations were sometimes returned here:

```
dispatch_barrier_sync(self.barrierQueue, ^{
        SDWebImageDownloaderOperation *operation = self.URLOperations[url];
        if (!operation) {
```

This resulted in a growing callbackBlocks array for the operation that was never going to finish. To resolve, we added a check for finished/canceled operations:

```
dispatch_barrier_sync(self.barrierQueue, ^{
         SDWebImageDownloaderOperation *operation = self.URLOperations[url];
         if ((!operation) || (operation.isFinished) || (operation.isCancelled)) {
```

This allowed a new operation to be created for the URL. In our app this resolved the issue. I have this committed to a fork if it's something the maintainers would like (although that single line is the extent of it).

Thanks for your continued work on a great library!

- josh jacob

**Comment by dreampiggy** [comment]
It seems that our logic is wrong in some cases. This looks a easy fix but not the internal reason.

`URLOperations` is an array of operations. Each operations, when it be canceled or finished, it will removed from that array. See line 212 and line 243.

Could you please provide more information about what the case you use will  trigger this BUG ? Maybe we should review the logic more carefully and find a better way to fix this :)

**Comment by JoshJacobAtHanson** [comment]
That makes sense. This fix recovers from a flaw but doesn't prevent the flaw. I'll try to get some logging in place to see why a canceled operation would be left in the array. Thanks for the feedback!

- josh jacob

**Comment by dreampiggy** [comment]
@JoshJacobAtHanson Thanks for your enthusiasm. And I can also review the current implementation later. I hope that we can find something related and solve this issue.

**Comment by dreampiggy** [comment]
Well. I'm come back again. 😅 After your decription, I'm doubting the actual reason for this.

Firstly, your decription that `canceled operations were sometimes returned here` is the designed behavior. SDWebImageOperation is `reused` for multiple callbacks, each callbacks is represented by a `token`.

So if you call `cancel:` on a operation with the token, it will remove the current token, and check if callbacks array is empty, then actually cancel the operation. In this cases, sometimes you may get the same operation at that function call because the callbacks array is not empty.

But question is: `This resulted in a growing callbackBlocks array for the operation that was never going to finish`, this should not happended. Because if the operation is `reused`, then we just add new token to that operation. So, if the call to `add` and `cancel` is equal, this will be no problems.

I think that this is a little hard to reproduce. If you can find a way to make it reproducable, maybe I can try to help with it 👍

**Comment by dreampiggy** [comment]
#2177 may provide fix for the `runningOperations` array. This happended when you scroll a big collection view really fast and the image are all in disk cache. If the query cache opertaion completion called duraing the cell disappear and trigger a `cancel`(This is for cell reuse), the race condition may occur and that operation may keep their and leaked. So now we do not use that `cancelBlock` design. We keep a weak reference to the manger instance and let manager to cancel. This can ensure the cancel to the operation entry is the same(Previouslly, the cancel may from cancelBlock or cancel method, this two entrys may not share the same lock)
