### ISSUE TITLE
最新的版本我的应用里面加载大量图片的时候800多兆就崩溃了不知道怎么优化

### ISSUE THREAD

**Issue by johnchen** [rs/SDWebImage#2121]

**Comment by taylorwrynn** [comment]
As I know, `SDImageCache` will auto purge cached image on `UIApplicationDidReceiveMemoryWarningNotification`.
And you can use `[SDImageCache clearMemory]` if you still want to clear memory.

**Comment by dreampiggy** [comment]
Please provide more information in our issue template. Such as system version, framework version. Or we can not help with it. You can reopen this issue when you finishing this :)
