### ISSUE TITLE
This block declaration is not a prototype

### ISSUE THREAD

**Issue by cesarcarlos75** [rs/SDWebImage#2124]
Platform Name           ios
 Platform Version        10.3
 SDWebImage Version      3.8.2
 Integration Method      cocoapods
 Xcode Version           Xcode 9.2

I'm working on an IOS app and I'm using SDWebImage. When I compile I get a warning that reads:

`This block declaration is not a prototype`

This error refers to the line

`typedef void(^SDWebImageNoParamsBlock)();`

in the SDWebImageCompat.h file.

Is there a way to fix this? I tried updating the pod but this seems to be the latest version.

**Comment by dreampiggy** [comment]
It has been fixed in SD 4.1.1(But I suggest update above 4.1.2 because 4.1.1 contains a serious bug), see: https://github.com/rs/SDWebImage/releases#4.1.1
