### ISSUE TITLE
Vertical bar appearing on all images.

### ISSUE THREAD

**Issue by nikhilchaurasia** [rs/SDWebImage#2126]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        |  8.0
 SDWebImage Version    | e.g. 4.0.0
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 9.0
 Repro rate              | e.g.  sometimes 5% 
 Repro with our demo prj | does it happen with our demo project?

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

I have start using SDWebImage cache. But we are facing an issue for some users. The vertical bar are appearing on every image loaded by library. The issue I very hard to reproduce
 and we are unable to find out the root cause. Please find attached screenshot.
<img width="455" alt="vertical bar" src="https://user-images.githubusercontent.com/5187656/34030444-0aa19cf4-e193-11e7-93f3-b1aab50929fe.png">

**Comment by nikhilchaurasia** [comment]
Any update on this issue?

**Comment by dreampiggy** [comment]
What's your use case ? (The description say that you only use SDImaegCache, but not SDWebImage UIView category or manager ?). Maybe a sample line of code can make it more suitable for check the reason.

And, could you please provide more information, such as image url sample, a demo project to reproduce is better.

**Comment by nikhilchaurasia** [comment]
I m using

 **[self.imageView sd_setImageWithURL:content.imageURL placeholderImage:[UIImage imageNamed:@"Placeholder-background"]]**

to load image. It is reproducible every time when user user kill app app 20-30 times and opens again.

**Comment by dreampiggy** [comment]
@nikhilchaurasia What's that `vertical bar` actually ?  Can you use Xcode's `View Debug` to see the view hierarchy, or can you try to use [FLEX](https://github.com/Flipboard/FLEX) to check whether the imageView(which appear a `vertical bar`)'s image contains some visual effect ?
