### ISSUE TITLE
only top 2 images are loading 

### ISSUE THREAD

**Issue by kbhat968** [rs/SDWebImage#2134]
hi I am using Collection View using Objective-c, and using following at cellforRowatIndex, its load only 2 images, I am using XML for data source and able to get rest of the details

[cell.image setImageWithURL:[NSURL URLWithString:item.image]];

Could you please let me know, why only two images,

**Comment by mythodeia** [comment]
@kbhat968 can you post your code or setup a demo project? which version of the library are you using?
