### ISSUE TITLE
width and Height 

### ISSUE THREAD

**Issue by HuangXiaoxing** [rs/SDWebImage#2137]
##
 Before i request a image from the remote server with SDWebImage on a tableview cell, i do not know the width and height of the image.After downloaded the image, i need reset  frame of the imageView,but the cell height alread has seted,if the image height is not equeal to the cell height, tableview will be deranged. How can i do it.

**Comment by dreampiggy** [comment]
:) If you really need to specify size through image itself but not the UI design max height. You should try to reload tableViewCell in completion block in `sd_setImageWithURL`

**Comment by JamesHealdUK** [comment]
How do I resize the images? They take up the full height of the `UITableViewCell` which is undesired behaviour.

Id like to have a set width and height for every image so it doesnt collide with my labels.

https://i.imgur.com/aOezIpK.png

**Comment by dreampiggy** [comment]
You don't need to resize `UIImage`(actually you can), you just need to change the `UIImageView`'s frame and the correct `contentMode`.

In the most cases, we set the imageView size to a fixed size(according to UI design), and then set image to it. Let image itself scale or clip.

If you want to keep the imageView acutally fit the image size(sometimes this may happened), just grap the `UIImage.size` and update the imageView's frame.
