### ISSUE TITLE
Xcode 9.2 Analyze Compiler Warning and Logic Errors

### ISSUE THREAD

**Issue by iNoles** [rs/SDWebImage#2142]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.2
 SDWebImage Version      | 4.2.x
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.2
 Repro rate              | all the time (100%) 
 Repro with our demo prj | Most likely would
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

In Xcode 9.2, If you do Product > Analyze, then you get these issues.

<module-includes>:1:1: Umbrella header for module 'SDWebImage' does not include header 'SDWebImageDecoder.h'

SDWebImageGIFCoder.m:80:17: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
SDWebImageGIFCoder.m:102:9: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
SDWebImageGIFCoder.m:106:13: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue

**Comment by dreampiggy** [comment]
`SDWebImageDecoder` this class is not available in SD 4.2.x(see https://github.com/rs/SDWebImage/releases/tag/4.2.0), I remember this is a file used in 4.1.x and replaced with `UIImage+ForceDecode`.

I always profile and analysis the current master branch ,it shows now warning(only 1 from libwebp dependency), so could you please the commit-id or tag for the project you tested ?

<img width="1027" alt="2017-12-29 11 51 31" src="https://user-images.githubusercontent.com/6919743/34429098-a602d644-ec8e-11e7-9f4d-c7a62f3461c1.png">

**Comment by iNoles** [comment]
I believe it was 4.2.2 from cocoapods.

**Comment by dreampiggy** [comment]
This seems a new *feature* from Clang Static Analyzer, for the number object(including `NSNumber`, `CFNumber`, `OSNumber`), you should write as these code-style instead of normal object

```objective-c
    NSNumber *number = @(1);
    if (number) {
        //warning
    }
    if (number != nil) {
        //good
    }
```

Since it's from Clang Static Analyzer but not Xcode itself's **contraband**, it looks persuasive, I'll replace the one used in our project. (Sadly, I run analysis from project will not show this warning, but for new project it shows, a little strange).

But for `SDWebImageDecoder.h`, there is no this file in whole project, so I don't know where it come from. :)

**Comment by dreampiggy** [comment]
#2143 You can review this one and add a `+1` so I'll merge this :)

**Comment by dreampiggy** [comment]
Merged.
