### ISSUE TITLE
`UIImageView sd_setImageWithURL: placeholderImage:` does not set the placeholder image when the image url is nil

### ISSUE THREAD

**Issue by hanton** [rs/SDWebImage#2144]
### New Issue Checklist

* [√ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ √] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [√ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 8.0
 SDWebImage Version      | 3.7.6
 Integration Method      | cocoapods
 Xcode Version           | Xcode 7.3
 Repro rate              | all the time (100%)
 Repro with our demo prj | `[self.imageView sd_setImageWithURL:nil placeholderImage:[UIImage imageNamed:@"placeholder"]];`
 Demo project link       | a demo project of the SDWebImage

### Issue Description and Steps

When the imageURL is nil, `[self.imageView sd_setImageWithURL:nil placeholderImage:[UIImage imageNamed:@"placeholder"]];` does NOT set the placeholder image.

**Comment by dreampiggy** [comment]
This issue is not active for long time and may because of old version's issue. Feel free to reopen it if you're still interested in this issue.
