### ISSUE TITLE
The operation couldn’t be completed. (NSURLErrorDomain error 403.)

### ISSUE THREAD

**Issue by Anonymous-Monk** [rs/SDWebImage#2165]
[imageView sd_setImageWithURL:[NSURL URLWithString:@"http://img4.imgtn.bdimg.com/it/u=3116492793,2003075867&fm=27&gp=0.jpg"] placeholderImage:[UIImage imageNamed:@"猜大小"] completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
            imageView.image = image;
        }];

(lldb) po error.localizedDescription
The operation couldn’t be completed. (NSURLErrorDomain error 403.)

**Comment by mythodeia** [comment]
@Anonymous-Monk Please provide more information in our issue template.
Which version of the library are you using?
Did you try the url on the latest version in our demo project?
Did you search through issues similar to this?
You are loading an image through insecure HTTP channel. Have you enabled ATS?

**Comment by adityativ-issart** [comment]
@mythodeia I have the same issue. When I login in my app it works correct. But after force stop the app,  **sd_setImageWithURL:** is returning this error. I'm using https channel for images.

**Comment by mythodeia** [comment]
@adityativ-issart can you replicate your issue in our demo project using the latest version?

**Comment by adityativ-issart** [comment]
@mythodeia where can I find your demo project?

**Comment by mythodeia** [comment]
download the latest version of the library and play with the demo

**Comment by adityativ-issart** [comment]
@mythodeia I need this files: http://take.ms/D1tLv

**Comment by mythodeia** [comment]
@adityativ-issart follow [the instructions here](https://github.com/rs/SDWebImage/blob/master/Docs/ManualInstallation.md)

**Comment by adityativ-issart** [comment]
@mythodeia I found problem in mu code. I need to call     [SDWebImageDownloader.sharedDownloader setValue:tokenString forHTTPHeaderField:@"X-Access-Token"]; every time when token is setting. But I called it one time.

**Comment by mythodeia** [comment]
👍
