### ISSUE TITLE
implicit declaration of function 'WebPFree' is invalid in C99.

### ISSUE THREAD

**Issue by OceanHorn** [rs/SDWebImage#2167]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 10.0
 SDWebImage Version      | e.g. 4.2.3
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 9.2
 Repro rate              | e.g. all the time (100%) 
 Repro with our demo prj | e.g. does it happen with our demo project? No.
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps
1. Add `SDWebImage` and `iOS-WebP`.
```
pod "SDWebImage", "~> 4.2.2", :subspecs => [
  "Core",
  "GIF",
  "WebP"
  ]
pod 'iOS-WebP'
```

2. Both need `libwebp` , but `iOS-WebP` needs a version `~> 0.5.0`.
After `pod install` and `Command+B`, then meets:
```
/Users/OceanHorn/SourceTree/mobile-agent/ios/Pods/SDWebImage/SDWebImage/SDWebImageWebPCoder.m:411:9: error: implicit declaration of function 'WebPFree' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        WebPFree(data);
        ^
1 error generated.
```

3.  The function `WebPFree` does not exist in `libwebp` version `~> 0.5.0`. Maybe we can use `WebPSafeFree` instead. Also need to define the version of `libwebp` in `.podspec` file. 

Expecially, the version of `libwebp` in this repository now is too old.

**Comment by dreampiggy** [comment]
This is because that we actually use libwebp 0.6.0, you can check that git submodule tag is 0.6.0.

But our podspec did not add the version to libwebp, then it fallback into libwebp 0.5.0.

`WebPSafeFree` is not available in 0.6.0, replaced by `WebPFree`, so this is why you compile failed.

Maybe you should ask `iOS-WebP` to update their dependency, and we can also add the version to point it need `libwebp`,  `~> 0.6.0`

**Comment by OceanHorn** [comment]
@dreampiggy Thanks! That's my fault.

**Comment by dreampiggy** [comment]
I found that if you specify `iOS-WebP` with git tag:  0.5.0, it can compile success :) 

The podspec file does not update to CocoaPods Trunk, it's that something wrong ?

https://cocoapods.org/?q=iOs-webp

**Comment by dreampiggy** [comment]
#2169 merged. We specify `libwebp ~> 0.5`. If you still use `iOS-WebP` below 0.5, please upgrate to the 0.5 version. If you cann't install(Currently I find that the spec file has not been uploaded to CocoaPods Trunk), use the following syntax:

```ruby
pod 'iOS-WebP', :git => 'git@github.com:seanooi/iOS-WebP.git', :tag => '0.5'
```
