### ISSUE TITLE
Fade animation not working for GIFs in 4.2.3

### ISSUE THREAD

**Issue by JEKos** [rs/SDWebImage#2179]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 11.0~
 SDWebImage Version      | 4.2.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | 100%
 Repro with our demo prj | yes
 Demo project link       | -

### Issue Description and Steps

After the release of 4.2.3 version, and the fix of that blink and flash when GIFs reload in FLAnimatedImageView, fade animation doesn't work. With 4.2.2 version, it's working, but it blinks after the animation. In version 4.1.2 it's working without any problem, but it's lagging when you scroll, in 4.2.0 you fixed that lag issue but then that blink problem started. It is possible to have fade animation when you load GIFs in the latest version?

**Summary:**
**4.1.2** version: fade animation works, but it's lagging when you scroll
**4.2.0**-**4.2.2** version: scroll lagging fixed, but blink problem starts after fade animation ends.
**4.2.3**: blink problem fixed but no longer fade animation works.

**Comment by dreampiggy** [comment]
😅 It looks like the idea we want to improve the performance is totally **wrong**. Maybe we should totally roll back to the original implementation...

Anyway, I will check this issue and maybe find a way to fix it(maybe not :)). In tomorrow.

Another word, this `FLAnimatedImageView` will be moved into a seperate Pod, we will try our own `SDAnimatedImageView`, which is a `UIImageView/NSImageView` subclass. And we use a `SDAnimatedImage` which is a `UIImage/NSImage` subclass to work with the memory cache. See #2140

**Comment by dreampiggy** [comment]
Could you please provide some code to do this `fade animation` as your decription ? A demo project is more welcomed :)

**Comment by dreampiggy** [comment]
If I can't fix this issue, maybe we should do a really trick logic: Bind `UIImage` an assciated object `FLAnimatedImage`, but this will consume more memory and that's why I do not want to do this during SD 4.2.3. But anyway, this is the last choice :)

**Comment by JEKos** [comment]
I think will be better to use your own method for GIFs like back then 3.x.x version without the need to use different class for GIFs. I'll upload the demo soon.

**Comment by JEKos** [comment]
Demo is done! You can download it [here](https://github.com/JEKos/gifsfadeanimdemo/tree/master)

**Comment by dreampiggy** [comment]
Well...Why you can `sd_setImage` again in the completion block ? You'd better use `AvoidAutoSetImage` to do a transition.

**Comment by JEKos** [comment]
I can't use your pod, like that
```
pod 'SDWebImage'
pod 'SDWebImage/GIF', :git => 'git@github.com:dreampiggy/SDWebImage.git', :branch => 'trick_code_fix_FLAnimatedImageView_fade'
```
It says: 
```
[!] There are multiple dependencies with different sources for `SDWebImage` in `Podfile`:

- SDWebImage
- SDWebImage/GIF (from `git@github.com:dreampiggy/SDWebImage.git`, branch `trick_code_fix_FLAnimatedImageView_fade`)
```
and I use only 
`pod 'SDWebImage/GIF', :git => 'git@github.com:dreampiggy/SDWebImage.git', :branch => 'trick_code_fix_FLAnimatedImageView_fade'`

It says:
```
[!] Error installing SDWebImage
[!] Failed to download 'SDWebImage'.
```

**Comment by dreampiggy** [comment]
:) Use the both of two with the git repo

```ruby
	pod 'SDWebImage', :git => 'git@github.com:dreampiggy/SDWebImage.git', :branch => 'trick_code_fix_FLAnimatedImageView_fade'
	pod 'SDWebImage/GIF', :git => 'git@github.com:dreampiggy/SDWebImage.git', :branch => 'trick_code_fix_FLAnimatedImageView_fade'
```

**Comment by JEKos** [comment]
It keeps saying 
```
[!] Error installing SDWebImage
[!] Failed to download 'SDWebImage'.
```

**Comment by dreampiggy** [comment]
@JEKos Network issue ? or you can clone the repo and use `:file` to this :)

```bash
git clone -b trick_code_fix_FLAnimatedImageView_fade git@github.com:dreampiggy/SDWebImage.git
// then use pod 'SDWebImage', :path => 'path/to/that/git/repo'
```

**Comment by JEKos** [comment]
Something is very weird...
```
JEKs-iMac:Documents jek$ git clone -b trick_code_fix_FLAnimatedImageView_fade git@github.com:dreampiggy/SDWebImage.git
Cloning into 'SDWebImage'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by JEKos** [comment]
I changed from `git@github.com:dreampiggy/SDWebImage.git`  to `https://github.com/dreampiggy/SDWebImage.git` and fixed

**Comment by JEKos** [comment]
@dreampiggy What exactly want me to test with our branch? Can you give me an example?

**Comment by dreampiggy** [comment]
@JEKos Whatever demo or actual product application contains this problem, test it with this branch code, just build and run.

**Comment by JEKos** [comment]
Oh, ok , I tested and there is not any difference

**Comment by dreampiggy** [comment]
Maybe you should give up this way... `FLAnimatedImageView` is a third-part lib we integrated. And this will be removed in the 5.x so we maybe we will not take more time on it

But I create a new feature called Image Transition. You just need to use that instead for basic transition animation. This can avoid you to call something trick code `sd_setImageWithURL:` again in your completion block.

See #2182, you can run our demo to check the effect

**Comment by dreampiggy** [comment]
@JEKos See the demo there. The `MasterViewController.m`'s `cellForRowAtIndexPath:` method. It's easy like UIKit's `transition(with:)` methods.

If you don't know about Objective-C, just use as normal:

```swift
let transition = SDWebImageTransition.init()
transition.duration = 0.5
transition.animations = [.transitionCrossDissolve]
cell.imageView.sd_setImage(with: URL(string: img[indexPath.item]), placeholderImage: nil, transition:transition, progress: nil, completed: nil)
``` 

Currently API seems not really convenient. But we will use class property to make the generated interface more easy to use in 5.x(Because it needs Xcode 8, but now our current Xcode min version is Xcode 7.3, suck)

**Comment by JEKos** [comment]
It gives that error :
![alt text](https://image.prntscr.com/image/GfVcExrFTT_fLph2qbTGEA.png)

**Comment by dreampiggy** [comment]
@JEKos `animationOptions`

**Comment by JEKos** [comment]
Yes! It works!!

**Comment by JEKos** [comment]
FLAnimatedImageView is very laggy when you scroll a Grid of Photos or Gifs in collectionView, better to get rid of it. But the fade animation works.

**Comment by dreampiggy** [comment]
@JEKos That branch does not contains the `trick_code_fix_FLAnimatedImageView_fade` code, which may benefit the frame rate because now we do not need to query the disk cache each time your cell reuse. (Crazy ? But that how previous version so far works). After one of this merge, you can try again

**Comment by dreampiggy** [comment]
@JEKos You can now use the syntax sugar on transition using class property.

```swift
let transition = SDWebImageTransition.fade
transition.duration = 0.5
cell.imageViewDisplay.sd_setImage(with: URL(string: img[indexPath.item]), placeholderImage: nil, transition:transition, progress: nil, completed: nil)
```

**Comment by dreampiggy** [comment]
@JEKos Try again with the `feature_image_transition`, the tricky code for FLAnimatedImage is merged. You may get little performance enhancement for it.

**Comment by dreampiggy** [comment]
#2182 Merged. Through maybe you can still use your previous code to do transition(the fix for FL may force it work like UIImageView). But we strongly recommand to use the new image transition feature.
