### ISSUE TITLE
Placeholder replaces imageview in other cells

### ISSUE THREAD

**Issue by sahibhussain** [rs/SDWebImage#2187]
### New Issue Checklist

* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none
* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 8.0 and above
 SDWebImage Version      | 4.x
 Integration Method      | cocoapods
 Xcode Version           | Xcode 7.3 and above
 Repro rate              | all the time (100%)

### Issue Description and Steps

i am using a collection view inside table view and in collection view  i am making a gallery but if the images are above 4 then it starts to behave abnormally as it starts to replace other cell image placeholder with the cached image of other cells and it is even replacing the placeholder image of AVPlayerLayer. I could not give you the code as the project is in production you can check it on app store for silverwool.

**Comment by dreampiggy** [comment]
Are you using SD 3.7.6 version? This version is too old and maybe we does not maintain. Could please try to upgrate to the latest version or at least using the 3.8.x version to check if this issue happend ? I do not face this issue in 4.x release.

**Comment by sahibhussain** [comment]
Sorry for the mistyping but i am already using the latest version as i am cocoapods so don't really keep track of the version.

**Comment by Asinox** [comment]
I'm facing the same thing using a table View...

**Comment by bpoplauschi** [comment]
@sahibhussain could you create a demo project where this issue replicates? It would help us reproduce and isolate the problem.

**Comment by bpoplauschi** [comment]
Does this issue still apply? Any updates?
