### ISSUE TITLE
How does the UIButton background support the GIF？

### ISSUE THREAD

**Issue by lewis15** [rs/SDWebImage#2192]
How does the UIButton background map support the GIF ？ I use this method [myButton sd_setImageWithURL:[NSURL URLWithString:@"http://xx/xx.gif" ]forState:UIControlStateNormal placeholderImage:placeImage]，but  it's show only the first frame。

**Comment by dreampiggy** [comment]
`UIButton` only support `UIImage`'s build-in animated images. By default, we do not add GIF coder. You should add this manurally and start using.

```objective-c
// in AppDelegate or somewhere, once is enough
[[SDWebImageCodersManager sharedManager] addCoder:[SDWebImageGIFCoder sharedCoder]];
```

**Comment by dreampiggy** [comment]
I just close this issue because there are already some solution here and lack of response. Feel free to reopen it if you still facing this issue 😃
