### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by pengshengsongcode** [rs/SDWebImage#2194]
0	libobjc.A.dylib
objc_msgSend + 16
1	HBCGAPP
__38-[SDWebImageDownloaderOperation reset]_block_invoke (SDWebImageDownloaderOperation.m:227)
2	libdispatch.dylib
__dispatch_call_block_and_release + 24
3	libdispatch.dylib
__dispatch_client_callout + 16
4	libdispatch.dylib
__dispatch_queue_concurrent_drain + 1372
5	libdispatch.dylib
__dispatch_queue_invoke + 892
6	libdispatch.dylib
__dispatch_queue_override_invoke + 344
7	libdispatch.dylib
__dispatch_root_queue_drain + 540
8	libdispatch.dylib
__dispatch_worker_thread3 + 124
9	libsystem_pthread.dylib
_pthread_wqthread + 1096

**Comment by dreampiggy** [comment]
Please fill the issue template or we could not provide any help. At least about platform , OS version, library version and the issue description

**Comment by dreampiggy** [comment]
From the `SDWebImageDownloaderOperation.m:227`, it seems the code is not SD 4.2.0 version. There is a thread-safe issue previously in `SDWebImageDownloaderOperation`, see #2011 #1998 . You can update to the lastest version and check again. So now I just close the issue. Feel free to reopen it if you still have the issue.
