### ISSUE TITLE
- [SDWebImageDownloaderOperation cancelInternal] objc_msgSend() selector name: retain SDWebImageDownloaderOperation.m, line 207

### ISSUE THREAD

**Issue by mauryabip** [rs/SDWebImage#2198]
Thread 0 Crashed:
--
1 | libobjc.A.dylib | objc_msgSend + 16
2 | Foundation | +[NSConcreteNotification newTempNotificationWithName:object:userInfo:] + 128
3 | Foundation | -[NSNotificationCenter postNotificationName:object:userInfo:] + 36
4 | ShareYourConnections | __47-[SDWebImageDownloaderOperation cancelInternal]_block_invoke (SDWebImageDownloaderOperation.m:207)
5 | libdispatch.dylib | _dispatch_call_block_and_release + 20

**Comment by dreampiggy** [comment]
Please fill the issue template. We need the information about OS version, Library version, Xcode version to check the issue.

This code to post notification in SD 4.2.3 is a `weakSelf`. So maybe it will not cause not the issue

**Comment by sikandarali307** [comment]
SDWebImageDownloaderOperation.m - Line 207
__47-[SDWebImageDownloaderOperation cancelInternal]_block_invoke + 207
Xcode Version 13.3
iOS 15.4.1
iPhone 12 Pro Max
if you need more information  I will be provide you
<img width="951" alt="Screenshot 2022-05-25 at 12 02 24 PM" src="https://user-images.githubusercontent.com/35461226/170200534-f20cb50a-4a2c-4c22-8a33-acf326e54389.png">

**Comment by sikandarali307** [comment]
if (self.dataTask) {
        [self.dataTask cancel];
        dispatch_async(dispatch_get_main_queue(), ^{
            [[NSNotificationCenter defaultCenter] postNotificationName:SDWebImageDownloadStopNotification object:self];
        });

        // As we cancelled the connection, its callback won't be called and thus won't
        // maintain the isFinished and isExecuting flags.
        if (self.isExecuting) self.executing = NO;
        if (!self.isFinished) self.finished = YES;
    }
