### ISSUE TITLE
Does the disk image cache increase the size of image?

### ISSUE THREAD

**Issue by zhumi108** [rs/SDWebImage#2207]
I set an `image` to an `imageView` using the `sd_setImageWithURL` method,  then I use the `[[NSData alloc] initWithContentsOfURL] ` to load the image, the data length was 308666. Then I use the `[[SDImageCache sharedImageCache] imageFromDiskCacheForKey: imageUrl]` to get the image from the disk, the image size was 1488 * 1984, equal to 2952192 . Does this mean the image has been magnified?

**Comment by dreampiggy** [comment]
The image data is a compressed format but not raw bitmap data. See [Wiki-Image file formats](https://en.wikipedia.org/wiki/Image_file_formats)

And SDWebImage cache itself does not add or modify the image data from the network. But excepted only one case when using `SDWebImageScaleDownLargeImages` and the image is actually scaled down. However this case is really misunderstanding and will deprecated in 5.x.
