### ISSUE TITLE
It is not clear how to reuse table view cells when some of the rows might not have images to display

### ISSUE THREAD

**Issue by mnvr** [rs/SDWebImage#2209]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        |  11
 SDWebImage Version      | master
 Integration Method      |carthage
 Xcode Version           | Xcode 9
 Repro rate              | all the time (100%)
 Repro with our demo prj | yes, see attached diff
 Demo project link       | diff attached

### Issue Description and Steps

The documentation does not specify how to handle reusable table view cells. I have
found a way to do it, but I am not sure if this is the way it is expected to be done, so
it would be helpful if one of the maintainers could ACK this (and perhaps mention
this in the documentation).

There are a lot of posts in the issue tracker which give the (outdated?) advice
of adding the following to override for `prepareForReuse`:

    [self.customImageView sd_cancelCurrentImageLoad];
    self.customImageView.image = nil;

Not only does that not work, it is also ill-advised since [Apple recommends
not changing the content there](https://developer.apple.com/documentation/uikit/uitableviewcell/1623223-prepareforreuse):

> For performance reasons, you should only reset attributes of the cell that are not related to content, for example, alpha, editing, and selection state. The table view's delegate in tableView(_:cellForRowAt:) should always reset all content when reusing a cell.

What works is, setting the sd_setImageWithURL to `nil` in the `cellForRowAtIndex` path
if the corresponding row has no image to display.

    [cell.customImageView sd_setImageWithURL:nil];

The issue can be reproduced by applying the following diff to the example project. It intersperses
the table view content with rows that do not have any associated URL. If you build and run with these
changes, you will see that there are new empty rows. However, if you uncomment the `[cell.customImageView sd_setImageWithURL:nil];` line, then these empty cells will start incorrectly showing up the image from the previous row's content.

```
diff --git a/Examples/SDWebImage Demo/MasterViewController.m b/Examples/SDWebImage Demo/MasterViewController.m
index 5e2b37b..58dd94e 100644
--- a/Examples/SDWebImage Demo/MasterViewController.m	
+++ b/Examples/SDWebImage Demo/MasterViewController.m	
@@ -33,6 +33,16 @@
     return self;
 }
 
+// THIS DOESN'T WORK
+/*
+- (void)prepareForReuse {
+    [super prepareForReuse];
+
+    [self.customImageView sd_cancelCurrentImageLoad];
+    self.customImageView.image = nil;
+}
+*/
+
 @end
 
 @interface MasterViewController ()
@@ -74,6 +84,9 @@
 
         for (int i=0; i<100; i++) {
             [self.objects addObject:[NSString stringWithFormat:@"https://s3.amazonaws.com/fast-image-cache/demo-images/FICDDemoImage%03d.jpg", i]];
+            for (int j = 0; j < 20; j++) {
+                [self.objects addObject:[NSNull null]];
+            }
         }
 
     }
@@ -124,9 +137,22 @@
     [cell.customImageView sd_setIndicatorStyle:UIActivityIndicatorViewStyleGray];
     
     cell.customTextLabel.text = [NSString stringWithFormat:@"Image #%ld", (long)indexPath.row];
-    [cell.customImageView sd_setImageWithURL:[NSURL URLWithString:self.objects[indexPath.row]]
+    id url = self.objects[indexPath.row];
+    if ([url isKindOfClass:[NSNull class]]) {
+        // THIS DOESN'T WORK EITHER
+        /*
+        [cell.customImageView sd_cancelCurrentImageLoad];
+        cell.customImageView.image = nil;
+         */
+
+        // THIS DOES
+        [cell.customImageView sd_setImageWithURL:nil];
+
+    } else {
+    [cell.customImageView sd_setImageWithURL:[NSURL URLWithString:url]
                             placeholderImage:placeholderImage
                                      options:indexPath.row == 0 ? SDWebImageRefreshCached : 0];
+    }
     return cell;
 }
 ```

**Comment by dreampiggy** [comment]
The View Category including `UIImage+WebCache`, `UIView+WebCache` or some other categories support cell resue in the implementation. The behavior is not so magic and it's all in the source code (However, seems there are no detail documentation for this)

1. When you call `sd_setImageWithURL:`, we will firstly set the placeholder(including nil if you do not specify any placeholder) to the current imageView's image before any cache or network request. Unless you specify `SDWebImageDelayPlaceholder`. See [here](https://github.com/rs/SDWebImage/blob/master/SDWebImage/UIView%2BWebCache.m#L70-L78)

2. If the image fetched in memory cache, the callback from manager is synchonized and in the same queue from you call `sd_setImageWithURL:`. So it will immediately set the result image to override the placeholder. UIKit draw all the views in the same runloop depended on their first state and last state. The state we set the placeholder(or nil) will be totally ignored and will not even rendering. If you do not understand this behavior, see [Understanding UIKit Rendering](https://developer.apple.com/videos/play/wwdc2011/121/)

3. If the image fetched in disk cache, the callback is asynchronously and dispatched from the cache queue to the main queue. So the placeholder (or nil) will be rendered with a little short time(depend on the IO speed and decoding time. Maybe like a flash). And then replaced by the final image

4. If the image fetched from network, the callback is asynchronously and dispatched from the downloader session queue to the main queue. So the placeholder (or nil) will be rendered with a long time(depend on the Network speed and decoding time). And then replcaed by the final image.

5. If you use `SDWebImageDelayPlaceholder`, we will use the placeholder as target image after the fetch finished if the image is nil.  For normal process, the placeholder is just used in the beginning of `sd_setImageWithURL`.

**Comment by dreampiggy** [comment]
So actually, for most of usage. All you need to do to work with cell reuse in `UITableView`, `UICollectionView` and `NSTableView` or `NSCollectionView` is quite simple, just use:

```objective-c
[cell.imageView sd_setImageWithURL:url placeholder:[UIImage imageNamed:@"placeholder"]];
```

**Comment by mnvr** [comment]
@dreampiggy Thank you for that detailed explanation!

You've clarified the issue for me. I've opened a PR with a link to your comment from
the documentation, you can merge it if you think it is useful, otherwise feel free to close
it too 👍🏼, or reword it as you see fit.

Thank you again, for your work on such a useful library.

**Comment by bpoplauschi** [comment]
The PR @mnvr mentioned is #2210

**Comment by internalG** [comment]
So the final conclusion is:
sd_cancelCurrentImageLoad is deprecated, use sd_setImageWithURL:nil in cellForRowAtIndex instead?

**Comment by StephanWalters** [comment]
> sd_cancelCurrentImageLoad

Still wondering as well

**Comment by inPhilly** [comment]
What's the final answer for this?
