### ISSUE TITLE
When I use webp ,some errors appear

### ISSUE THREAD

**Issue by BakaYang** [rs/SDWebImage#2211]
When I use webp,some errors appear
<img width="581" alt="d1623b6f-3960-4af3-a481-afd1e627ecd3" src="https://user-images.githubusercontent.com/23470990/35839344-e0ddeef6-0b2a-11e8-85d2-dadbb0dbec4c.png">

**Comment by dreampiggy** [comment]
First, when you submit the issue, please keep and provide the issue template about the framework version, platform version(iOS ? macOS ? version ?), and Xcode version. Or we could not help to find the potential solution.

And, maybe you're using a old version of [libwebp](https://github.com/webmproject/libwebp) and compile as a static library by yourself. You can try two solution, the recommend one is using CocoaPods with [libwebp](https://cocoapods.org/pods/libwebp) and enable `WebP` subspec.

If you are using manually build framework or carthage, just make sure to not change any project configuration.

**Comment by BakaYang** [comment]
I'm sorry I didn't provide some important information.The following are detailed information:
xcode version 9.2,and libwebp  I manually downoad from google ,
<img width="420" alt="63c87fa4-ed2d-4c52-b15d-57771b70ef99" src="https://user-images.githubusercontent.com/23470990/35847519-a89d82e2-0b55-11e8-8445-42da6b409a06.png">

Then I manually imported it into the project
<img width="252" alt="3fb33400-a914-4bfe-b76f-f914d0f90a6b" src="https://user-images.githubusercontent.com/23470990/35847546-b509a25e-0b55-11e8-9812-3adec424bd21.png">

then i add it to libraries

<img width="547" alt="3d268dd2-e172-4101-9b3c-449fa010a58f" src="https://user-images.githubusercontent.com/23470990/35847566-c2d7898c-0b55-11e8-8fd4-6415046770cd.png">


and I change project configuration :target－>build setting－>preprocessor add SD_WEBP=1
<img width="720" alt="5f7c54b4-1686-4381-a041-71906144ef86" src="https://user-images.githubusercontent.com/23470990/35847632-07865d42-0b56-11e8-8775-aa5d181959ca.png">


 I download SDWebImageWebPCoder(.h.m) and  UIImage+WebP(.h.m) from github,then I add they to my project,
<img width="255" alt="b26847b4-4037-485a-8d86-760bfa21e0ca" src="https://user-images.githubusercontent.com/23470990/35847742-75c6f154-0b56-11e8-8fe4-b89cfaa33671.png">
command + b   ,then appear errors

**Comment by dreampiggy** [comment]
You should not use the use the "Precompiled WebP framework for iOS" from libwebp's page. Because that is a custom cut framework but not the code we used. The headers files is different from the source code in their original repo or [GitHub mirror](https://github.com/webmproject/libwebp)

You should try to compile that to iOS or macOS by yourself to produce a `libwebp.framework`, and drag that instead into the project. See [WebP-building](https://developers.google.com/speed/webp/docs/compiling#building) and the cocoapods spec's toturial for [libwebp](https://github.com/CocoaPods/Specs/blob/master/Specs/1/9/2/libwebp/0.6.0/libwebp.podspec.json) to use Cocoapods to automatically generate the build config.

**Comment by BakaYang** [comment]
I run `iosbuild.sh`,genertate `WebP.framework` and `WebPDecoder.framework` ,but  I can't find `mux.h ` and `demux.h` inside.
<img width="604" alt="21ab6900-dfc0-4f0c-a6a6-65dc51d80a53" src="https://user-images.githubusercontent.com/23470990/35901066-e3b84276-0c0f-11e8-82df-cbf4210d7a6d.png">

**Comment by dreampiggy** [comment]
@BakaYang I means that `iosbuild.sh` does not define the USE_MUX to let animated WebP decoding/encoding works. And so the header files or sources files does not been compiled. You can check their [makefile](https://github.com/webmproject/libwebp/blob/master/src/Makefile.am#L4-L9)

We need `mux.h` and `demux.h` to do animated WebP decoding & encoding. So you should customize the [build script here](https://github.com/webmproject/libwebp/blob/master/iosbuild.sh#L59) with `configure --enable-libwebpmux --enable_libwebpdemux`

 If you're not famillar with makefile or shell script, you can [learn](https://learnxinyminutes.com/docs/make/) here.

**Comment by BakaYang** [comment]
Thank you for your answer，but I am not familiar with makefile and shell script.I try to change `iosbuild.sh` with `configure --enable-libwebpmux --enable_libwebpdemux`,but in the end it failed.Can you tell me more detailed steps or send `iosbuild.sh` to my mailbox.

**Comment by bpoplauschi** [comment]
@BakaYang this later question is `webp` related, so you should address this on the webp project. We are just referencing it. I also strongly recommend you use the recommended install via CocoaPods.

**Comment by zhangjingfeng** [comment]
@BakaYang this framework [file](https://github.com/weiman152/TestSDWebImage/tree/master/TestSD_2/TestAAAA/TestAAAA/WebP.framework) may help you
