### ISSUE TITLE
Resize Server Image and Show in Tableview - Increase memory and App Crash Randomly

### ISSUE THREAD

**Issue by kushaseum** [rs/SDWebImage#2213]
Hello,

I am displaying image using below code.

`cell.imgPackage.sd_setImage(with: URL(string: "MY URL STRING")! as URL, placeholderImage: UIImage(named: "testPlaceholder.png"), options: .refreshCached)`

**need to resize width and height of server image and set in tableview cell image.**

my server image resolution is around
width - 1519
height - 950

and tableview having - 
width - 320
height - 150

let me know if you need any clarification.

**Comment by mythodeia** [comment]
you should consider 2 options:
1st -> download the large resolution image and write code to make it smaller after download
2nd -> ask your server to give you smaller images in the 1st place

**Comment by dreampiggy** [comment]
For the 1st case, you can Use (-[SDWebImageManagerDelegate imageManager:transformDownloadedImage:withURL:])[https://github.com/rs/SDWebImage/blob/1749666720401ff129212631886c4af7531e6584/SDWebImage/SDWebImageManager.h#L144-L154] to do  custom resizing for your case if you find the image size is larger than excepted.

**Comment by kushaseum** [comment]
@dreampiggy Thanks for replay.

I want to go ahead for 1st case.
can you please give example code for swift 3.

**Comment by dreampiggy** [comment]
@kushaseum  You can do with the delegate methods to resize if need(Such as for specify URL, for size which larger than the limit). The Objective-C code is actuall no difference with Swift code :)

```swift
class ViewController: UIViewController, SDWebImageManagerDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        SDWebImageManager.shared().delegate = self
        SDWebImageManager.shared().loadImage(with: URL(string: "http://foo/large.png"), options: [], progress: nil) { (image, data, error, cacheType, finished, url) in
            // Do something
        }
    }
    
    func imageManager(_ imageManager: SDWebImageManager, transformDownloadedImage image: UIImage?, with imageURL: URL?) -> UIImage? {
        guard let image = image, let imageURL = imageURL else {
            return nil
        }
        if (imageURL.lastPathComponent == "large" && (image.size.width > 1000 || image.size.width > 1000)) {
            let targetSize = CGSize(width: 1000, height: 1000)
            UIGraphicsBeginImageContextWithOptions(image.size, !SDCGImageRefContainsAlpha(image.cgImage), image.scale)
            image.draw(in: CGRect(origin: .zero, size: targetSize))
            
            let scaledImage = UIGraphicsGetImageFromCurrentImageContext()
            UIGraphicsEndImageContext()
            return scaledImage
        } else {
            return image
        }
    }
}
```

**Comment by kushaseum** [comment]
Hello,

Thanks for swift Reply. 

getting one issue - Please check screen sort

I had write below code.

`SDWebImageManager.shared().delegate = self
        SDWebImageManager.shared().loadImage(with: URL(string: (arrInternationPackageModel.object(at: indexPath.row) as! NSDictionary).value(forKey: "image") as! String)!, options: [], progress: nil) { (image, data, error, cacheType, finished, url) in
            // Do something
            cell.imgPackage.image = image
        }`

`func imageManager(_ imageManager: SDWebImageManager, transformDownloadedImage image: UIImage?, with imageURL: URL?) -> UIImage? {
        let targetSize = CGSize(width: 320, height: 150)
        UIGraphicsBeginImageContextWithOptions((image?.size)!, !SDCGImageRefContainsAlpha(image?.cgImage), image!.scale)
        image?.draw(in: CGRect(origin: .zero, size: targetSize))
        
        let scaledImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return scaledImage
    }`


![img_3180](https://user-images.githubusercontent.com/29673185/35905046-9bc43a14-0c0b-11e8-846a-5a8138c9db19.PNG)

**Comment by dreampiggy** [comment]
Mistake. Change the 'image.size' to 'targetSize' in UIGraphicsBeginImageContext

**Comment by bpoplauschi** [comment]
We already have some code that handles image resize, but it's called only when `SDWebImageScaleDownLargeImages` option is set and the image is large enough (over 60 MB of memory for a decompressed image). See [SDWebImageIOCoder 
 sd_decompressedAndScaledDownImageWithImage](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageImageIOCoder.m#L269)
