### ISSUE TITLE
Does Library Clear Disk Cache After Time Or Size?

### ISSUE THREAD

**Issue by mikemike396** [rs/SDWebImage#2214]
I am curious if this library auto clears disk cache? We have some code in our app that on app upgrade it clears the cache but I am wondering if this happens already? If it doesnt is there anyway we can check the size of the disk cache and then clear?

    [MTMigration applicationUpdateBlock:^{
        [self.imageCache clearMemory];
        [self.imageCache clearDiskOnCompletion:NULL];
        [self.imageCache deleteOldFilesWithCompletionBlock:NULL];
     }];

**Comment by dreampiggy** [comment]
`clearDiskOnCompletion` will remove all the disk cache whatever the files outdated or not.
`deleteOldFilesWithCompletionBlock` will be called when your application entering the background  to remove the outdated files.

**Comment by mikemike396** [comment]
Do either of these get ran automatically? Also has there been any thoughts of running these once the size gets to a default amount to keep things cleaned up?

**Comment by dreampiggy** [comment]
@mikemike396 `deleteOldFilesWithCompletionBlock` will be called each time your application entering the background(iOS & tvOS).

`clearDiskOnCompletion` will not automatically been called until you manually do this.

**Comment by mikemike396** [comment]
Ah okay I see now you have the expiration date set to 7 days. 

    static const NSInteger kDefaultCacheMaxCacheAge = 60 * 60 * 24 * 7; // 1 week

Thanks again for all the info. This helps greatly! Amazing library!
