### ISSUE TITLE
There are some notsmooth frames in the main thread when call sd_cancelImageLoadOperationWithKey:

### ISSUE THREAD

**Issue by mg459046365** [rs/SDWebImage#2215]
<img width="954" alt="2018-02-09 9 31 15 2" src="https://user-images.githubusercontent.com/4360057/36007219-782db900-0d7c-11e8-9e8f-97f26d2cf927.png">

**Comment by dreampiggy** [comment]
What your means ? It's just a lock. Must ensure the other thread is blocked until the lock released. I don't know what about this "There are some notsmooth frames"

**Comment by dreampiggy** [comment]
I see the stacktrace. There is no 'dispatch_barrier_sync' in SD 4.3.0. We use a 'dispatch_semaphore' to lock it to ensure thread-safe. You can try to upgrade to the new version and have a try.
