### ISSUE TITLE
sd_setImageWithURL set HTTP headers

### ISSUE THREAD

**Issue by balkarov** [rs/SDWebImage#2221]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.2
 SDWebImage Version      | 3.8.2
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 9
 Repro rate              | all the time (100%)
 Repro with our demo prj | 
 Demo project link       | 

### Issue Description and Steps

Hello. Thank you for your library. How to add authorization headers to sd_setImageWithURL?

I tried
```
SDWebImageManager *manager = [SDWebImageManager sharedManager];
[manager.imageDownloader setValue:"secret" forHTTPHeaderField:@"x-secret"]; 
```
But this works only for `manager.imageDownloader downloadImageWithURL`
But `downloadImageWithURL` does not have **SDImageCacheType**. 
I want check in success block 
```
completed:^(UIImage* image, NSError* error, SDImageCacheType cacheType, NSURL* imageURL) {
if (image && cacheType == SDImageCacheTypeNone) {
 // set image
}
```

**Comment by dreampiggy** [comment]
Hi.

For SDWebImage 4.x(Currrently 4.3.0), you can use `headersFilter` in `SDWebImageDownloader`. If you need to specify some specify URLs from View Category, many you need write some switch case or check code.

```objective-c
SDWebImageManager.sharedManager.imageDownloader.headersFilter = ^SDHTTPHeadersDictionary * _Nullable(NSURL * _Nullable url, SDHTTPHeadersDictionary * _Nullable headers) {
    if ([url.path isEqualToString:@"auto"]) {
        SDHTTPHeadersMutableDictionary *authHeaders = [headers mutableCopy];
        [authHeaders setValue:@"foo" forKey:@"Authorization"];
        return [authHeaders copy];
    } else {
        return headers;
    }
};
```

If you are using standard HTTP user & password authorization, you can simply use `username` and `password` property in `SDWebImageDownloader`.


But however, in SD 5.x, we introduce a options to allow directlly pass the HTTP header fileds from View Category. So you do not need a central manager to filter the HTTP headers. See #2020. And we can introduce this feature(HTTP headers only but not HTTP response) into 4.x if more peopel really need this feature.

**Comment by balkarov** [comment]
@dreampiggy thank you for your answer.
Will be send http headers in sd_setImageWithURL after use headersFilter?
If yes, I will update version in my project and will check it.

**Comment by balkarov** [comment]
@dreampiggy thank you very much. 
I will be wait new releases with this feature.

**Comment by dreampiggy** [comment]
@balkarov I check and 3.8.2 also contains this [headersFilter](https://github.com/rs/SDWebImage/blob/3.8.2/SDWebImage/SDWebImageDownloader.h#L127-L133) property. If you do not want to upgrade, you can use that instead. :)

**Comment by balkarov** [comment]
@dreampiggy but I saw source code and I think for `sd_setImageWithURL` http headers do not use.
Http headers use for `manager.imageDownloader downloadImageWithURL`  
Maybe I wrong?

**Comment by dreampiggy** [comment]
@balkarov All View Category APIs finally call `downloadImageWithURL` if the cache retrieve failed and start to download. So this should work. Or....Maybe bugs :)

**Comment by balkarov** [comment]
@dreampiggy thank you!
So.... `setValues forHTTPHeaderField` and `headerFilter` is different things?

**Comment by dreampiggy** [comment]
@balkarov Historical reason. That `setValues:forHTTPHeaderField:` are static way to add the `default value for headers` for all requests.

However, since many people need some logic code to check before apply the headers for URLs (Not all URLs need this default headers) . So then they introduce the `headersFilter` :)

**Comment by bpoplauschi** [comment]
Indeed this is a bit weird, but as @dreampiggy said, `setValues:forHTTPHeaderField:` will update the  `HTTPHeaders` array used for all the downloads for a certain downloader. `headersFilter` is a block called for each download where you can do something with the headers (should be filtering, but given the interface of the API, you can return any dictionary as long as it matches the type).

**Comment by dreampiggy** [comment]
I just close this issue because there are already some solution here and lack of response. Feel free to reopen it if you still facing this issue 😃

**Comment by johnwylie70** [comment]
> If you are using standard HTTP user & password authorization, you can simply use `username` and `password` property in `SDWebImageDownloader`.
> 
> But however, in SD 5.x, we introduce a context option to allow directlly pass the HTTP header fileds from View Category(When you call `sd_setImageWithURL:placeholderImage:options:progress:completed:context:` API). So you do not need a central manager to filter the HTTP headers. See #2166. And we can introduce this feature(HTTP headers only but not HTTP response) into 4.x if more peopel really need this feature.

Can you please give an example of setting the header via the new context parameter on  sd_setImageWithURL?

**Comment by dreampiggy** [comment]
@johnwylie70 Wiki is your friend. Please have a check at: [How-to-use-Request-Modifier](https://github.com/SDWebImage/SDWebImage/wiki/How-to-use#use-request-modifier-50)
