### ISSUE TITLE
gifv support

### ISSUE THREAD

**Issue by Steven4294** [rs/SDWebImage#2222]
Does this support .gifv (gif-video)?

**Comment by dreampiggy** [comment]
Our lib is aim to be open and for common usage. So if you need new image format support, see [Custom Coder Support](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#custom-coder-420) and write your own decoder for this GIF-Video format :)

**Comment by dreampiggy** [comment]
@Steven4294 I check the description about that `gifv`. It's just a H264 based acutal video format which store in a GIFV container. This is more like a video decoding. If you need to write a custom coder, you can use Apple's [VideoToolbox](https://developer.apple.com/documentation/videotoolbox) or [ffmpeg](https://www.ffmpeg.org/) to support this.

Our build-in coder aim to based on the existing toolchain, such like Apple's Image/IO framework or libwebp (For WebP). So for more specify image format, write it for yourself and maybe you can create a cococapods for the user who need the same use case :)

**Comment by bpoplauschi** [comment]
Agree with @dreampiggy. Closing the issue

**Comment by dreampiggy** [comment]
This use case, can now supported by using the 5.3.0's feature: [Animated Player](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-player-530).

The player is a component, which does not care where the frames from (For this case, it's a Video URL, or AVPlayerItem). And it does not care how you consume the frames (For this case, you can create any UIView and render the frames on that layer).

So, checkout that wiki and some demo in our repo, you can found the solution to split each gifv(MP4, video format) frames, and render it on layer to play animation.

But to be serious, a Video format, it's better to use Video Media solution to play that, all the people and exist framework already provide a native and better support for that. This just a showcase how the player can works in so common use cases.
