### ISSUE TITLE
crash at CFDictionaryRef properties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, NULL);

### ISSUE THREAD

**Issue by swinpa** [rs/SDWebImage#2229]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios 
 Platform Version        | 10.3.1
 SDWebImage Version      | 4.2.3
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 9 
 Repro rate              | sometimes 
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

![1519615292209](https://user-images.githubusercontent.com/12831010/36652066-4af7f5a4-1ae7-11e8-8945-86be3f66fc0c.jpg)

crash at CFDictionaryRef properties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, NULL);

**Comment by kinarobin** [comment]
#3149
