### ISSUE TITLE
[SDWebImageManager.sharedManager saveImageToCache:image forURL:imageURL] can't remove imageURL from failedURLs

### ISSUE THREAD

**Issue by KiritoBeater** [rs/SDWebImage#2235]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 11.0
 SDWebImage Version      |  4.2.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.2
 Repro rate              | all the time (100%) 
 Repro with our demo prj | maybe
 Demo project link       | nothing
### Issue Description and Steps

After downloading image failed and saving a image to cache, [SDWebImageManager.sharedManager saveImageToCache:image forURL:imageURL] can't remove imageURL from failedURLs

**Comment by dreampiggy** [comment]
When the completionBlock in `SDWebImageManager.sharedManager.loadImageWithURL` called, the cache sync to disk operation is not finished becuase it's an async operation. Current behavior does not wait the store to disk operation finished and then call your completionBlock. We just callback as soon as the image is valid.

There is also a discussion about this, see #1301.

If your business logic is relay on the store to disk operation finished. You can try using [SDWebImageCacheMemoryOnly](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.h#L27-L30) and manually call image cache to store it after the completion block called.

**Comment by KiritoBeater** [comment]
Sorry, something wrong you understand. I mean that  I want to save another image to the cache with the same cache key when imageURL is bad. But `SDWebImageManager.sharedManager` can't remove imageURL from failedURLs when `[SDWebImageManager.sharedManager saveImageToCache:image forURL:imageURL]`. So Next time, `[imageView sd_setImageWithURL: imageURL]` is still failed. It is not that I want.

**Comment by dreampiggy** [comment]
@KiritoBeater Sorry for that I misunderstanding your question. For that `failedURLs` case, actually current implementation is tied to the internal process. In 5.x we change this to allow custom delegate method to decide whether the `Error` should be marked as failed. And maybe we can also expose the ability to remove that `failedURLs list`.

**Comment by dreampiggy** [comment]
Maybe we can add this feature to 4.x branch since this will not cause API-break. But there maybe some other issue to considered such like `whether we should also allow ADD a custom URL to blacklist but only REMOVAL ?`)

**Comment by KiritoBeater** [comment]
Thanks. Expectedly.
