### ISSUE TITLE
WebP images not loading when app opened from launcher, but load when opened from Xcode

### ISSUE THREAD

**Issue by noticeboard-priyansh** [rs/SDWebImage#2238]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | all
 SDWebImage Version      | 4.3.2 (latest)
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | 100%
 Repro with our demo prj | No
 Demo project link       | Cant give

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

Hi
Facing a weird issue here. I have many webp images uploaded to my cloud image provider.
Integrated sdwebimage into my project, with the latest version, and the webp images fail to display.
All other image formats are displaying properly.
The problem is, webp images are failing to display when I open the app normally through the launcher, but they load perfectly fine when running from Xcode.

Can anyone help me out?

**Comment by dreampiggy** [comment]
Weird. Could you please set a breakpoint at this line of [code for static WebP](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageWebPCoder.m#L105) and [code for animated WebP](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageWebPCoder.m#L145) to see whether the image instance available ? You can use Xcode's build-in view image button to preview the image.

If not, are you using some debuger options specify for debug running ? See `Run Scheme -> Debug -> Arguments Passed On Launch & Environments Variables`

**Comment by noticeboard-priyansh** [comment]
Hi

While running from Xcode, it works fine, so while debugging it works.
When app launched from the launcher, they arent loading.
I am getting this error as -
"Downloaded image has 0 pixels."

Also, I checked in the debug scheme and I am not passing any arguments.

**Comment by bpoplauschi** [comment]
@noticeboard-priyansh this issue sounds pretty weird, so here are a few ideas:
- is the app launched from launcher the same debug one installed with Xcode?
- are you using the device or simulator?
- you can try installing the app, starting it and then attaching the debugger :)

**Comment by filipealva** [comment]
I'm facing the `Downloaded image has 0 pixels` error too often. I can't relate to launching it via Xcode or launcher,  but it is happening a lot and I can't find any reason.

**Comment by dreampiggy** [comment]
@filipealva Could you please set a breakpoint at "Downloaded image has 0 pixels" error [line](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloaderOperation.m#L444). Then using lldb check the URL request and paste  the image URL here.
