### ISSUE TITLE
When i load 200 or more images in tableview using SDWebImage getting Message from debugger: Terminated due to memory issue, and after app is crashing.

### ISSUE THREAD

**Issue by janardhanmupparaju** [rs/SDWebImage#2241]
When i load 200 or more images in tableview using SDWebImage getting Message from debugger: Terminated due to memory issue, and after app is crashing.

**Comment by dreampiggy** [comment]
Please provide more information such as your iOS platform version, SDWebImage version and some crash log. Or maybe we can not do much help for this :)

**Comment by janardhanmupparaju** [comment]
now using iOS-11.2, Xcode-9.2 and 'SDWebImage', '~> 4.0'. when i load 200 images using SDWebImage its downloading all after app calling applicationDidReceiveMemoryWarning() method and getting this Message from debugger: Terminated due to memory issue and after app crashing.

This is my code

   cell.ReportImage.sd_setImage(with: imageURL, placeholderImage: UIImage(named: "docImage"))

**Comment by mythodeia** [comment]
@janardhanmupparaju what kind of images are you downloading? i mean size in bytes and/or resolution

**Comment by janardhanmupparaju** [comment]
jpg, jpeg, png and sizes in bytes 34184, 10366947, 7945, ...

**Comment by mythodeia** [comment]
generally you should avoid showing images that are 10mb in size. either download and scale them down or ask the server for smaller ones. 
Also did you try your image urls in the demo project using the latest version? does this crash too?

**Comment by dreampiggy** [comment]
Maybe this is OOM during the background decoding. Can you try disable `shouldDecompress` in cache, manager and download operation. After that then check the same image request, will this OOM occur ?

**Comment by BlessNeo** [comment]
image size more than 500k cause app crashed, same reason:memory issue

**Comment by janardhanmupparaju** [comment]
I find the solution. loading high resolution images into tableview, so that is the problem.

**Comment by ankittlp** [comment]
@janardhanmupparaju What you did to solve ?

**Comment by mbhanen** [comment]
What you did to solve ?

**Comment by Rohit737-star** [comment]
What a fuck @janardhanmupparaju  where is the solution. you said I have fixed it in the above conversation but how????

**Comment by janardhanmupparaju** [comment]
I reduced the resolution of image and added the pagination with that it was working for me

**Comment by Rohit737-star** [comment]
Thanks for reply @janardhanmupparaju
