### ISSUE TITLE
Webp animation is missing on latest SDWebImage

### ISSUE THREAD

**Issue by haipengzhang** [rs/SDWebImage#2251]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        |  11.0
 SDWebImage Version      |  lastest
 Integration Method      |  cocoapods
 Xcode Version           | Xcode 9
 Repro rate              |  all the time
 Repro with our demo prj | no
 Demo project link       | no

### Issue Description and Steps

1.  I
<img width="1179" alt="wx20180313-135133 2x" src="https://user-images.githubusercontent.com/7854821/37324769-e5149310-26c5-11e8-82e0-01f7ce6ce9a8.png">
mageView's animating is missing, when imageView scroll out from screen. 

![5e8f8c5a-7f44-4d39-b082-a10ce8a46ade](https://user-images.githubusercontent.com/7854821/37324678-78d70944-26c5-11e8-840e-4345dc76667c.png)

**Comment by dreampiggy** [comment]
@haipengzhang What's your usage? I try the demo project in our repo and the WebP animated image render is correct. When the cell scroll our of screen and re-enter, everything works well.

Could you please provide a demo or code snippet that can reproduce this issue ? And for that `latest`, do you means the `4.3.3` version ? Please provide more information, thanks :)
