### ISSUE TITLE
Data Encryption

### ISSUE THREAD

**Issue by SSDIAshokPathak** [rs/SDWebImage#2254]
Dear ,

Thank you for your support.

I just want to know that is this library using any Data Encryption processing (like "AES", "3DES", "RSA", "DH" etc), if yes could you please give some information about it, if possible.

Thanks in advance.

**Comment by dreampiggy** [comment]
NO. If you want to implement this, you can consider using these function together to build your own.

### [Cache Serializer](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageManager.h#L217-L235)
### [Custom Coder](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#custom-coder-420)
### [Custom Download Operation](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#custom-download-operation-40)

**Comment by SSDIAshokPathak** [comment]
Thanks you for your reply.

Your information is helped me.
