### ISSUE TITLE
Request error shown Cancelled while loading image with SDWebImage

### ISSUE THREAD

**Issue by vinayakpal** [rs/SDWebImage#2258]
im using this library for display async images in my table view but sometime image request got cancelled especially .png images or http:// images. please help

**Comment by mythodeia** [comment]
@vinayakpal can you replicate the issue in the demo project with your own images? 
which version of the library are you using?

**Comment by vinayakpal** [comment]
@mythodeia i'm currently using SDWebImage (4.3.3) version via pods. i will revert back to you after check in demo project. Thanks for responding

**Comment by dreampiggy** [comment]
Could you please provide more information about your use case ? This description is a little inaccuracy.

If you mean when you using `UIImageView` with `UITableViewCell`, when the cell reused, all the previous request will be cancelled. And so `NSURLSession` will produce a error identify that the task is cancelled.

If you mean that all your image request can not finished, even for single `UIImageView`, maybe you sohuld check that error information or your network config, such as [App Transport Security](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html)

**Comment by vinayakpal** [comment]
@dreampiggy  Yes im using an UIImage which is in my UITableView Cell in an table view.
here's the sample of the particular image

 `cell.feedImage.sd_setImage(with: URL(string : "http://res.cloudinary.com/purnesh/image/upload/f_auto/v1520249635/shiv-tikki-wala-final-header-1.png"), completed: { (image, error, type, url) in

                        print(String(describing: error?.localizedDescription))
                        print(String(describing: error.debugDescription))
                        print(type)
                        print(url!)
                        print(image!)
                    })`

**Comment by dreampiggy** [comment]
@vinayakpal So. Does that means your receive a cancelled error when you scroll and the cell is disappear and reused ? It's a designed behavior to let the SDWebImage's View category work with the `UITalbViewCell` and `UICollectionViewCell` reusing mechanism.

**Comment by vinayakpal** [comment]
Other images in my table view are loading correctly well I have issue with previous mention URL as i tested in a demo app as well but with this URL I'm not able to load the image as well.

**Comment by mythodeia** [comment]
@vinayakpal i tried the url (http://res.cloudinary.com/purnesh/image/upload/f_auto/v1520249635/shiv-tikki-wala-final-header-1.png) in the browser and got an error as well. this does not seem to be a problem with the library

![screenshot](https://user-images.githubusercontent.com/1748458/37814570-4d2d3cf4-2e73-11e8-83ee-c1b6c1434c0d.png)
