### ISSUE TITLE
Example usage describes an error

### ISSUE THREAD

**Issue by webMing** [rs/SDWebImage#2264]
In SDWebImageManager.h file 
/**
 * The cache serializer is a block used to convert the decoded image, the source downloaded data, to the actual data used for storing to the disk cache. If you return nil, means to generate the data from the image instance, see `SDImageCache`.
 * For example, if you are using WebP images and facing the slow decoding time issue when later retriving from disk cache again. You can try to encode the decoded image to JPEG/PNG format to disk cache instead of source downloaded data.
 * @note The `image` arg is nonnull, but when you also provide a image transformer and the image is transformed, the `data` arg may be nil, take attention to this case.
 * @note This method is called from a global queue in order to not to block the main thread.
 * @code
 SDWebImageManager.sharedManager.cacheKeyFilter = ^NSData * _Nullable(UIImage * _Nonnull image, NSData * _Nullable data, NSURL * _Nullable imageURL) {
    SDImageFormat format = [NSData sd_imageFormatForImageData:data];
    switch (format) {
        case SDImageFormatWebP:
            return image.images ? data : nil;
        default:
            return data;
    }
 };
 * @endcode
 * The default value is nil. Means we just store the source downloaded data to disk cache.
 */

 SDWebImageManager.sharedManager.cacheKeyFilter should  be modified to  SDWebImageManager.sharedManager.cacheSerializer 
My English is not good, so the expression may not be very clear☺

**Comment by dreampiggy** [comment]
😅 You're right. Maybe this is documentation issue. We'll update and fix it. Thanks for your report.

**Comment by dreampiggy** [comment]
Fixed in 0f36f97

**Comment by webMing** [comment]
fast.  en ..en .   I will make myself as good as you. come on

**Comment by webMing** [comment]
fast. en ..en . I will make myself as good as you. come on  @dreampiggy
