### ISSUE TITLE
cache is 0kb

### ISSUE THREAD

**Issue by XiaoYiS** [rs/SDWebImage#2269]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0 
 SDWebImage Version      | 4.2.0 
 Integration Method      |  / cocoapods /
 Xcode Version           | Xcode 9
 Repro rate              |  all the time (100%)

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

SDWebimage 4.0.0,
CGFloat sizeLength = (CGFloat)[[SDImageCache sharedImageCache] getSize]/1024/1024;
sizeLength = 0;
I can't get cache size, is what I need to set up,please reply me,thanks

**Comment by bpoplauschi** [comment]
@XiaoYiS please fill in the issue template info.

**Comment by dreampiggy** [comment]
Can you open your simulator's sandbox to check the actual cache size ? (You can check it on `~/Application/Library/Caches/default/com.hackemist.SDWebImageCache.default/`)

And also, are you sure you're get the correct size but lose the precision ? Be careful that `NSUInteger` division will clip to 0 if the actual size is `1024 * 1024 - 1`.

**Comment by XiaoYiS** [comment]
my SDWebImage version is 4.2.2 , 
code ://缓存文件大小读取
- (NSString *) getFileSize
{
    //缓存大小读取
    CGFloat sizeLength = (CGFloat)[[SDImageCache sharedImageCache] getSize]/1024/1024;
    if (sizeLength == 0) {
        return @"0.0M";
    }
    return [NSString stringWithFormat:@"%.2f M",sizeLength];
}
in simulator, I can  get sizeLength is not zero, but in my iPhone  6s(device) sizeLength is zero, so I can't make clean memory.

I update template information

**Comment by dreampiggy** [comment]
@XiaoYiS You write some code to manually check that folder size firstly. And you can also dump you sandbox folder of real device (Through Xcode -> Devices -> Right Click App -> Download Container), check whehther that `/Caches/default/com.hackemist.SDWebImageCache.default` folder is actual empty or not.

This API just using `NSFileManager`'s API, nother special for simulator or read device. If you find something strange, you can reply here.

**Comment by XiaoYiS** [comment]
@dreampiggy ,   I find folder that you say the path,but I can't find com.hackemist.SDWebImageCache.default, I just find com.hackemist.xxxSDWebImageCache.default, maybe I use the third party led to the conflict SDWebimageCache, what can I do setting ?

**Comment by XiaoYiS** [comment]
![b2a762ab-0568-477f-94d9-a96058e087ee](https://user-images.githubusercontent.com/15341057/40033518-526955d6-582b-11e8-8f85-76561cf78b22.png)

**Comment by dreampiggy** [comment]
@XiaoYiS See the code here: [SDImageCache](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDImageCache.m#L158). It's now hard-coded a prefix string `com.hackemist.SDWebImageCache.`. So maybe someone swizzle your code about SDWebImage or you're using a modified version of SDWebImage. You can check it again :)

In 5.x, we add a config to allow customize the prefix instead of hard-coded. Maybe at that time you don't need this...

**Comment by XiaoYiS** [comment]
@dreampiggy , I try to revise SDImageCache source code , it is clean success. can you give me better advice?

**Comment by dreampiggy** [comment]
...If you're using a modified version of SDWebImage, you should try to find your own way to solve this. You can using `NSFileManager` to manually remove the cache folder. You can check cache folder from the modified version of SDWebImage, or something other way

**Comment by XiaoYiS** [comment]
@dreampiggy ,ok  thanks for your patience
