### ISSUE TITLE
SDWebImageScaleDownLargeImages for disk images

### ISSUE THREAD

**Issue by LiuDeng** [rs/SDWebImage#2273]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           ios
 SDWebImage Version      4.2.0

SDWebImageScaleDownLargeImages now is just working for network image , and i have a lot of large images in local disk , hope SDWebImageScaleDownLargeImages can take effect for disk images.
Thank you for your great work.
Best Regards.

**Comment by dreampiggy** [comment]
😅There will be more and more options in `SDImageCahceOptions`...

We can done this in 4.x. Is this feature really necessary for you ? How does the image in cache come from ? If the image is from our `SDWebImageManger` and download from network, it should has already beeen decompressed. Isn't it ?

**Comment by LiuDeng** [comment]
@dreampiggy This is really necessary. When i have a lot of large image in local and want to show it in a UICollectionView, then it broken. Hope you can add this support for disk image~
Best Regards.
Thank you for you great work~

**Comment by LiuDeng** [comment]
@dreampiggy This really necessary and i think it is better to make the option to work for both for local and network.Thank you~

**Comment by dreampiggy** [comment]
@LiuDeng So...If you already have some disk files contains big images, why not directlly scale down it before you query the disk ? I means to preprocess it before your application using them.

Currently `SDWebImageScaleDownLargeImages` implementation is not works well for most common cases, which just useful if your images is huge (likes 1000*1000 RGBA and above). So maybe even I introduce this feature, this may not solve your problem.

The best practice for network large images, in 4.x you should use `imageManager:transformDownloadedImage:withURL:` to custom scale down the images if need. (In 5.x you can use our built-in transformer instead). For disk large images, preprocess the images before you load it, but not load the large images into memory and consume CPU to scale it down. This may be bad on performance and we'll not sync back the disk images again. (Which means each time you query the new disk images, you'll have to scale it down)

**Comment by LiuDeng** [comment]
@dreampiggy Thank you very much~I will try it later and feedback to you~

**Comment by LiuDeng** [comment]
@dreampiggy I have download your branch and try it. I have a image original size is {1054, 12663} and after sd_decompressedAndScaledDownImageWithImage called the return image size is still {1054, 12663}. So the scale here is not scale the size but reduce the quality？

**Comment by dreampiggy** [comment]
@LiuDeng Just decompress the original large images to reduce memory usage, without effect the image resolution, like the force decode(`shouldDecompressImages`) feature.

If you need to resize the image to lower resolution, you should use image transformer featuer. In 4.x you can use `imageManager:transformDownloadedImage:withURL:` with some image trransfom third party library, like [UIImage-Additions](https://github.com/vilanovi/UIImage-Additions) or [YYCategories](https://github.com/ibireme/YYCategories)

In 5.x, we introduce common built-in image transformer and category. See [SDWebImageTransformer](https://github.com/rs/SDWebImage/blob/5.x/SDWebImage/SDWebImageTransformer.h#L79-L87) and [UIImage+Transform](https://github.com/rs/SDWebImage/blob/5.x/SDWebImage/UIImage%2BTransform.h#L37-L45) and #2219

**Comment by LiuDeng** [comment]
@dreampiggy Thank you so much for your replay， currently i will scale the image in complete block and will replace it after 5.x release. 
Best Regards.

**Comment by dreampiggy** [comment]
@LiuDeng Yes you can . But attention if you `Scale down` (I think your means is `resize down resolution` in completion block, you should remember that completion block from manager or view category are always called from main queue. So this process may block your main queue. We recommend to use a global queu to do this. 4.x's `imageManager:transformDownloadedImage:withURL:` will dispatch a global queue to let you do transform, 5.x's tranformer always process on a global queue.

**Comment by chiahsien** [comment]
Hi @dreampiggy ,

Say I want to download a hi-res progressive JPEG and want to `resize down resolution` before displaying it progressively, can `SDWebImageProgressiveDownload` option work with `imageManager:transformDownloadedImage:withURL:`?

**Comment by dreampiggy** [comment]
@chiahsien Seems the current implementation, that `imageManager:transformDownloadedImage:withURL:` delegate not forbid progressive image loading. So you can do some image processing during progressive image loading.

However, since progressive image loading will callback your completion multiple times depend on network speed, it may become really performance-related task. So take care of your image process code (Use high-performance code and keep thread-safe). Or if you can, try let your image server to pre-scale down the image, before it send back to the client.
