### ISSUE TITLE
“pod spec lint” Error

### ISSUE THREAD

**Issue by shenjuneng** [rs/SDWebImage#2298]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0 
 SDWebImage Version      | 4.2.0
 Integration Method      | carthage / cocoapods / manually
 Xcode Version           | Xcode 9
 Repro rate              | all the time (100%)
 Repro with our demo prj | e.g. does it happen with our demo project?
 Demo project link       | e.g. link to a demo project that highlights the issue

### Issue Description and Steps

Terminal execute: 
pod spec lint SJInfiniteScrollView.podspec 

Error Information:
-> SJInfiniteScrollView (0.1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS] xcodebuild:  SDWebImage/SDWebImage/SDWebImagePrefetcher.h:64:1: error: property with 'retain (or strong)' attribute must be of object type
    - NOTE  | [iOS] xcodebuild:  SJInfiniteScrollView/SJInfiniteScrollViewDemo/SJInfiniteScrollView/SJInfiniteScrollView.m:11:9: fatal error: could not build module 'SDWebImage'

**Comment by dreampiggy** [comment]
You are not enable ARC for disaptch object like `dispatch_queue_t`, which cause our framework not works.

See [stackoverflow-does-arc-support-dispatch-queues](https://stackoverflow.com/questions/8618632/does-arc-support-dispatch-queues)

**Comment by shenjuneng** [comment]
Thanks Dreampiggy. You said right. In pod spec file, add "s.platform     = :ios, "9.0"", the error is gone.

**Comment by dreampiggy** [comment]
You're welcome ;)
