### ISSUE TITLE
How do I get the HTTP Header for the image?

### ISSUE THREAD

**Issue by honbolau** [rs/SDWebImage#2300]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 SDWebImage Version      |3.7.2
 Integration Method      |  cocoapods 
 Xcode Version           |Xcode 9

How do I get the HTTPHeader for the image?

**Comment by dreampiggy** [comment]
If you means you need to specify some HTTP headers before image request, using [Headers filter](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.h#L169-L175) or [Headers set/get method](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.h#L184-L190). These two are the dynamic/static way to specify HTTP headers.

If you means to get the HTTP response's header information, this feature is not available in 4.x. But is already done in the 5.x via #2261 . If you need this, you can wait for 5.x release
