### ISSUE TITLE
error: can't allocate region

### ISSUE THREAD

**Issue by onato** [rs/SDWebImage#2309]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info
When downloading a large image I receive a crash at the following line:
https://github.com/rs/SDWebImage/blob/e549e1abebeac704b69ae920889dfe465015637b/SDWebImage/SDWebImageImageIOCoder.m#L162

```
malloc: *** mach_vm_map(size=48775168) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```

The error does not occur in version 4.3.0. It started happening in version 4.3.1 and still occurs in 4.3.3

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 11.0
 SDWebImage Version      | e.g. 4.3.1, 4.3.2, 4.3.3
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 9
 Repro rate              | e.g. all the time (100%)
 Demo project        | Run the demo project at this fork https://github.com/onato/SDWebImage.

### Issue Description and Steps

<img width="1552" alt="screen shot 2018-05-01 at 12 28 29 pm" src="https://user-images.githubusercontent.com/107999/39456544-57ecdc62-4d3b-11e8-954d-af3fceecdb3d.png">
<img width="1552" alt="screen shot 2018-05-01 at 12 28 54 pm" src="https://user-images.githubusercontent.com/107999/39456543-57b439ca-4d3b-11e8-8b4f-9a7df31de6c5.png">

This is the image I am downloading:
![largeimage](https://user-images.githubusercontent.com/107999/39456872-b76f79f4-4d3d-11e8-98aa-08fee224ec4e.jpeg)

**Comment by dreampiggy** [comment]
I guess this seems bug from Image/IO.

It seems you're using progressive image load feature. And if I set a breakpoint at that line. I see these output:

> 2018-05-03 23:28:17.922559+0800 SDWebImage iOS Demo[73708:4848777] imageBlockSetCreate:759: *** buffer height mismatch: rect:{0,0,4032,1008}  size:{4032,3024}

This `Workaround for iOS anamorphic image` is kept for historical reason. From 5.x this code already been deleted. See #2303.

I can check it again to test if iOS 7 still need it. If need, I will add a `if (< iOS 8) { // workaround}` condition check. If iOS 7 does not nedd it, I will delete this code.

**Comment by dreampiggy** [comment]
Confirmed...I test with a iOS 7 Real Device iPhone with litte trick in Xcode 9.. 😅 

iOS 7 Image/IO does not have this bug, so this worksaround code can be removed in iOS 7 as well.

See the result:

<img width="1552" alt="2018-05-04 3 55 32" src="https://user-images.githubusercontent.com/6919743/39617972-5560f7e6-4fb4-11e8-96c2-9fb60ca545dc.png">


I decide to pick that merge request to 4.x branch as well. So this crash will not happen.

**Comment by dreampiggy** [comment]
@onato Merged...Wait for 4.3.4 release and no longer Image/IO progressive loading need this workaround.
