### ISSUE TITLE
Get original DATA：- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error

### ISSUE THREAD

**Issue by NorthDogLi** [rs/SDWebImage#2324]
Thank you so much for providing this great framework

I have a problem here, my image URL is an encrypted binary file
So I need to get the original data and then decrypt it before converting to a picture

In this case I can't easily replace the data in this method (-(void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error).

I hope the author can provide you with a raw data for us to use

**Comment by dreampiggy** [comment]
Well. To say, to achieve this goal, current you have 2 different ways to solve it.

1. Create your custom image coder. You can find the [Wiki - custom coder](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#custom-coder-420). All you need to do just like a proxy to firstlly decrypt the original image data to the unencryped image data. Then secondlly feed it to our `SDWebImageCodersManager` to your desired image decoder.

2. Create your custom download operation. You can find the [Wiki - custom download operation](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#custom-download-operation-40). You can just create a subclass of `SDWebImageDownloadOperation`, then override the `-[NSURLSessionDataDelegate URLSession:dataTask:didReceiveData:]`. Do your own decrypt process and finally call our image coder. Maybe you need to copy some code from the super class implementation (But anyway, we're open sourced...)


In the 5.x of SDWebImage, you have the third way to solve this. You can create your custom image loader totally. Which open all of posibility for you to load the image from the original URL. (Regard of the URL is http or any other schema such as Photos framework URL). You can integrate your own implementation about image downloading and decrypting for advacend user.

Hope these advices can help you :)
