### ISSUE TITLE
Build failure when project uses both SDWebImage and SDWebImage/GIF

### ISSUE THREAD

**Issue by ngAvaddon** [rs/SDWebImage#2337]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS 
 Platform Version        | 11.0
 SDWebImage Version      | 4.3.3
 Integration Method      | cocoapods
 Xcode Version           | 9.3.1 (9E501)
 Repro rate              | sometimes during build/archive
 Repro with our demo prj | no
 Demo project link       | [sdwebimage_build_issue](https://github.com/ngAvaddon/sdwebimage_build_issue)

### Issue Description and Steps

Project fails to archive if `pod 'SDWebImage'` and `pod 'SDWebImage/GIF'` are being used for a different targets. 
Run into this issue because another pod used in main target was using `pod 'SDWebImage/GIF'` so there was no intention to use SDWebImage and SDWebImage/GIF at the same time in described way.
Not sure if it's an issue of Xcode build or SDWebImage in a first place but it's good to have it reported.
There is more info in demo project README.

To reproduce:

```pod install```
Xcode -> Product -> Archive

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/SDWebImage-Core-GIF-umbrella.h"
        ^
/Users/user/Library/Developer/Xcode/DerivedData/TestApp1-eudslplchqkplofpqvoxvnskgbzp/Build/Intermediates.noindex/ArchiveIntermediates/TestApp1/BuildProductsPath/Debug-iphoneos/SDWebImage/SDWebImage.framework/Headers/SDWebImage-Core-GIF-umbrella.h:40:9: note: in file included from 
/Users/user/Library/Developer/Xcode/DerivedData/TestApp1-eudslplchqkplofpqvoxvnskgbzp/Build/Intermediates.noindex/ArchiveIntermediates/TestApp1/BuildProductsPath/Debug-iphoneos/SDWebImage/SDWebImage.framework/Headers/SDWebImage-Core-GIF-umbrella.h:40:
#import "FLAnimatedImageView+WebCache.h"
        ^
/Users/user/Library/Developer/Xcode/DerivedData/TestApp1-eudslplchqkplofpqvoxvnskgbzp/Build/Intermediates.noindex/ArchiveIntermediates/TestApp1/BuildProductsPath/Debug-iphoneos/SDWebImage/SDWebImage.framework/Headers/FLAnimatedImageView+WebCache.h:16:9: error: 'FLAnimatedImage.h' file not found
#import "FLAnimatedImage.h"
        ^
/Users/user/Projects/sdwebimage_build_issue/TestApp1Framework/TestApp1Framework/ImageTest.swift:2:8: error: could not build Objective-C module 'SDWebImage'
import SDWebImage
       ^
```

### Resolution
Simply changing all moving parts to use `pod 'SDWebImage/GIF'` in Podfile solves the issue because then `pod install` adds all required components to framework search paths and only one framework is used in a project.

**Comment by dreampiggy** [comment]
When switching target between different dependency using `SDWebImage/GIF`, `SDWebImage/Core`, run `Xcode -> Product -> Clean` and `Xcode -> Product -> Clean Build Folder` to clean the folder....It seems a issue cause by Xcode.

**Comment by ngAvaddon** [comment]
Hey @dreampiggy, we use Bitrise.io and it spins completely new virtual machine for each build - no need to clean anything. 
Issue is probably related to new build improvements\optimizations Apple is doing. 
You can check out linked GitHub project for more details.

I just wanted to share experience in case you'll have to dig it deeper like I did.  :)

**Comment by dreampiggy** [comment]
@ngAvaddon Oh...I'm checking that demo now..Seems a interesting issue

**Comment by bpoplauschi** [comment]
This will probably no longer apply with the 5.0 release, because we are moving all the `FLAnimatedImage` support to a dedicated repo
