### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by anhmuonnoi** [rs/SDWebImage#2341]
<img width="977" alt="screen shot 2018-05-29 at 14 47 19" src="https://user-images.githubusercontent.com/6723051/40645139-a8d932b8-634f-11e8-88fb-ab7d7ef4bef8.png">

**Comment by mythodeia** [comment]
@anhmuonnoi Please fill the issue template regarding platform, iOS version, library version and some detail about the issue.

**Comment by dreampiggy** [comment]
Seems like a OOM issue. The device is out of memory and cause malloc failed. There is no ways to solve this case and just let the application exit. You can try to profile and reduce the memory usage for your application.
