### ISSUE TITLE
[SDWebImageDownloader] Race condition where downloader sometimes fails to call completion block when requesting the same image url

### ISSUE THREAD

**Issue by master-nevi** [rs/SDWebImage#2344]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.3.1
 SDWebImage Version      | 4.3.3 & 4.4.0 (no others tested)
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.3.1
 Repro rate              | 99.9% using a stress test
 Repro with our demo prj | Available (see comments)
 Demo project link       | https://github.com/master-nevi/SDWebImage/tree/download-race-repro

### Issue Description and Steps

The best way to repro is to make several attempts at requesting the same image in very close succession. After debugging and adding a bunch of logs I discovered that there's a very small window of opportunity for the completion block from `SDWebImageDownloader downloadImageWithURL:options: progress:completed:` to not get called. When using this method a subsequent time for the same URL, if the `SDWebImageDownloaderOperation` has finished for the first call but hasn't been taken out of the  `SDWebImageDownloader.URLOperations` dictionary yet, the handlers for the subsequent call **will be added to the finished download operation instance**. The download operation along with the newly added handlers will then soon be discarded when [[sself.URLOperations removeObjectForKey:url];](https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.m#L287) is actually called shortly after.

There essentially needs to be some form of protection from adding handlers to an operation which has already finished, when there's no other opportunity to call its handlers again.

As you can guess, the completion not getting called can cause issues with any component that expects it to be called, from the SDWebImageManager to the view itself that requested the image.

**Comment by master-nevi** [comment]
I was able to stress test the downloader from within the SDWebImage demo project (iOS).

**Please checkout and run this branch using the iOS simulator:**
https://github.com/master-nevi/SDWebImage/tree/download-race-repro

**Diff:**
https://github.com/rs/SDWebImage/compare/master...master-nevi:download-race-repro?expand=1

Basically attempts 1000 downloads of the same URL and there's consistently 1-4 cases where the completion block never returns.

**Comment by hulizhen** [comment]
@master-nevi I downloaded and built the demo project, it seems there's a problem in the first place.

You can't just dispatch the examination code, that finds out which completion blocks aren't called, to the main queue. Almost right after the last(1000th) `-[SDWebImageDownloader downloadImageWithURL:options:progress:completed]` is called, in the next `-[MasterViewController recurse:]`, the examination code is executed on the main queue. This may cause the completion block, which also runs on main queue, to be called after the examination code. So the test result might be unreliable.

I put two breakpoints in the `-[MasterViewController recurse:]` method: one at the line of `NSLog(@"MISSING COMPLETIONS FOR THE FOLLOWING DOWNLOAD INDEXES:%@", string);`, another at the line of `NSLog(@"Completion called for download with index: %ld", (long)tempIndex);`, and indeed find there's a chance the completion block is called after the test has finished.

So, for the sake of getting a reliable test result, I dispatch the examination code to a global queue. Unfortunately, the completion-block-not-called bug still exists. But the result is more convincible.

**Comment by dreampiggy** [comment]
@master-nevi I try the demo, change the URL into different URl, even change the repeat times to 10000. But however, I can not reproduce this issue 😕 

As you say, I check the code there, the only opportunity that this `race condition window` can occur, it because of this two line of code.

```objective-c
// SDWebImageDownloadOperation.m
[self done]; // -> should trigger `NSOperation.completionBlock`, then call `[sself.URLOperations removeObjectForKey:url];` in `SDWebImageDownloader.m`


// SDWebImageDownloader
SDWebImageDownloaderOperation *operation = [self.URLOperations objectForKey:url]; // Get a nonnull operation
// Then add the new progressBlock & completionBlock, however, this operation is already marked as finished and could not recovery again ?
id downloadOperationCancelToken = [operation addHandlersForProgress:progressBlock completed:completedBlock];
```

From the theory, this race condition can happen. Maybe we should check that the operation we get is not marked as finished. Only this case we can `reuse` this operation for download and call for completion. If is already finished, directlly create a new one instead.

**Comment by dreampiggy** [comment]
@master-nevi See #2346

**Comment by master-nevi** [comment]
Confirmed https://github.com/rs/SDWebImage/pull/2346 appears to fix the issue. Closing this issue. @dreampiggy do you have an approximation for when 4.4.1 would be released?

**Comment by dreampiggy** [comment]
@master-nevi Before this weekend. After all the issue on https://github.com/rs/SDWebImage/milestone/26 finished.

This time because of one emergency issue #2347 so the patch version release for 4.4.0 will be released quickly. 😅

**Comment by dreampiggy** [comment]
@master-nevi 4.4.1 released...You can upgrade for this fix right now.
