### ISSUE TITLE
Cannot display WebP image on iOS 12.0 beta

### ISSUE THREAD

**Issue by d-date** [rs/SDWebImage#2347]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.0 beta
 SDWebImage Version      | 4.4.0 (master)
 Integration Method      | manually
 Xcode Version           |  Xcode 10.0 beta
 Repro rate              | all the time (100%)
 Repro with our demo prj | You can see in Demo project in this repo
 Demo project link       | https://github.com/rs/SDWebImage/tree/master/Examples/SDWebImage%20Demo

### Issue Description and Steps

In iOS 12.0 beta, WebP image download cannot display.

In demo project in [this repo](https://github.com/rs/SDWebImage/tree/master/Examples/SDWebImage%20Demo), the image 3 and 4, which are WebP image, might be empty as below.

![simulator screen shot - iphone x - 2018-06-06 at 15 31 42](https://user-images.githubusercontent.com/20222809/41021242-b46e36ee-69a0-11e8-948f-b7d5b22a3510.png)

image 5 - 7 are also WebP, but these are gif images so that see as well.

**Comment by dreampiggy** [comment]
Try the lastest version (4.4.0) firstlly. Not the previous release

**Comment by d-date** [comment]
@dreampiggy  Sorry for my misunderstanding, this is occurred on the latest.

**Comment by dreampiggy** [comment]
@d-date Seems works on the iPhone simulator. Does this cause issue on the real device ?

**Comment by d-date** [comment]
@dreampiggy Yes, I've checked on my iPhoneX and also happened.

**Comment by d-date** [comment]
This is run on my iPhone X.

![img_0094](https://user-images.githubusercontent.com/20222809/41022290-0586c7fa-69a4-11e8-8dc2-77488e9083b0.PNG)

**Comment by d-date** [comment]
@dreampiggy  `5.x` branch works well for me!

Simulator:

![simulator screen shot - iphone x - 2018-06-06 at 17 31 55](https://user-images.githubusercontent.com/20222809/41026660-1208a960-69b0-11e8-9673-985091dcb94b.png)

Physical Device (iPhone X): 

![img_0095](https://user-images.githubusercontent.com/20222809/41026688-20c5b3ee-69b0-11e8-9d39-3b99fedc9741.PNG)

**Comment by dreampiggy** [comment]
@d-date Conformed seems a bug that because of using the wrong arg in `CGImageCreate`. However, this seems does not cause issue in the previous iOS release 😅 

See #2348

**Comment by dreampiggy** [comment]
@d-date You can test the master branch now. It should been fixed.

**Comment by d-date** [comment]
@dreampiggy LGTM😎Thank you for your great job!

**Comment by dreampiggy** [comment]
4.4.1 version release. Anyone here please upgrade if you're using WebP images.

**Comment by siddheshC** [comment]
Hello guys, 

I am facing the same problem. v4.4.1 - Whose version are you talking about?

What should I do to get away from this issue?
