### ISSUE TITLE
How can I store image permanently?

### ISSUE THREAD

**Issue by SerhiiMatvieiev** [rs/SDWebImage#2351]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        |  11.0 
 SDWebImage Version      | 4.2.0 
 Integration Method       | cocoapods
 Xcode Version           |  Xcode 8

### Issue Description and Steps

I need to download image and store it permanently for using in offline mode? 
And one more question, how can I store image to my own folder?

Thanks!

**Comment by dreampiggy** [comment]
One way, if you don't want to build some more code about image store & load, you can create a standalone `SDImageCache` instance with a custom filepath location. You can check `SDImageCache` initilizer to do this.

Then specify this cache instance to a new `SDWebImageManager` instance, which will use the standalone cache to query disk. Last, using `sd_internalSetImageWithURL:` with the custom manager using `SDWebImageExternalCustomManagerKey` key.


If you want more control for download & cache & load, you can directlly using `SDWebImageDownloader` to download the image firstlly, then store to your permanent file path. When you need to display the image, grab the disk path in global queue and using `UIImage+MultiFormat.h` to decode it, then set it back. You can build your own logic as you want by using the SDWebImage as a toolkit.

**Comment by lohenyumnam** [comment]
can you please give a sample code in swift?
