### ISSUE TITLE
Failed to decode some webp images in iOS12.0

### ISSUE THREAD

**Issue by luochaojing** [rs/SDWebImage#2354]
![31-1 3x](https://user-images.githubusercontent.com/13879378/41335896-07477dcc-6f1d-11e8-8744-6df13698a2cf.jpg)

but in google chrome is good;
YYWebImage which uses libWebp library is good .

**Comment by dreampiggy** [comment]
Dumplicated for #2347 . And it's already been fixed in [4.4.1 version](https://github.com/rs/SDWebImage/releases/tag/4.4.1)

Please using GitHub issue search before you fire the issue, thanks !

**Comment by luochaojing** [comment]
thanks a lot!
