### ISSUE TITLE
Cache Age not working

### ISSUE THREAD

**Issue by lohenyumnam** [rs/SDWebImage#2355]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        |   11.0  
 SDWebImage Version      | 4.3.3
 Integration Method      |  carthage  
 Xcode Version           |  Xcode 9 

### Issue Description and Steps

Guys I am using this framework to download and cache the image, using the url which will never change
example url path http://example.com/app/common/images/00108/28.jpg (Not real URL)

The problem is after few mins or hour the Image download again

I tried using 

```
 	// Setting disk cache
        SDImageCache.shared().config.maxCacheSize = 1000 * 1000 * 500 // 100 MB
        
        // Setting disk cache age
        SDImageCache.shared().config.maxCacheAge = 60 * 60 * 24 * 7 // 7 days
```

But it keeps requesting for new image from same old path

**Comment by dreampiggy** [comment]
@lohenyumnam Current implementation, the cache expire removeal process is only happened when your application is entering background. It use a long-term background task to check the expired cache data and remove them.

So if you do not enter background mode, just keep download and store image, the expired cache data will not been cleaned.

**Comment by lohenyumnam** [comment]
Thanks for the reply, 
all I want is to download the image once then use the image from the cache for as long as I can.
I don't want to re-download the image again and again.

even if I set the cache age to 7 days or longer, in my app it lasts for like few hours and then it starts downloading the image again. am I missing something here?

```
// Setting disk cache age
SDImageCache.shared().config.maxCacheAge = 60 * 60 * 24 * 7 // 7 days
```

**Comment by bpoplauschi** [comment]
@lohenyumnam it depends on the HTTP headers of the response as well. If the server providing the image returns Expires or similar headers, the system may calculate the image needs to be re-downloaded. We can inspect those flags if you provide some test image, otherwise, you need to inspect them yourself. My assumption is this is a setup problem on your server.

**Comment by bpoplauschi** [comment]
@lohenyumnam feel free to reopen or just continue the conversation, I am curious if we can figure it out
