### ISSUE TITLE
Use of SDImageCacheAccessedDate

### ISSUE THREAD

**Issue by paulosaure** [rs/SDWebImage#2356]
### New Issue Checklist

* ☑  I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* ☑ I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* ☑ I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none but I found a pull request

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version         |  11.0 
 SDWebImage Version  | 4.3.3
 Integration Method    |   cocoapods 
 Xcode Version        |       Xcode 9 

### Issue Description and Steps

Hello,

I'm back to the subject but I would like to know why the pull request #940 has never been merged ?
I checked in `SDImageCache.m` file  and we still can not use `SDImageCacheAccessedDate`

**Comment by dreampiggy** [comment]
Seems we finally can release 4.4.2 😅 Close this issue.

**Comment by bpoplauschi** [comment]
Ok. I will go ahead and release 4.4.2

**Comment by bpoplauschi** [comment]
4.4.2 is now available via CocoaPods

**Comment by paulosaure** [comment]
Awesome.
Thank you !
