### ISSUE TITLE
Crash when I download ftp image

### ISSUE THREAD

**Issue by hejinggen** [rs/SDWebImage#2369]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 11.0 / 10.13.0 / 11.0 / 4.0
 SDWebImage Version      4.3.3
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode `9.4`

### Issue Description and Steps
```
SEGV_ACCERR
CFNetwork | NetConnection::requestIsComplete(void*) + 32
-- | --
1 CFNetwork | _FTPStreamClose(void const*, _CFFTPStreamContext*) + 280
2 CFNetwork | _FTPStreamClose(void const*, _CFFTPStreamContext*) + 280
3 CFNetwork | CoreStreamBase::_streamInterface_Close() + 96
4 CoreFoundation | __CFStreamClose + 112
5 CFNetwork | FTPProtocol::destroyReadStream() + 48
6 CFNetwork | FTPProtocol::~FTPProtocol() + 64
7 CoreFoundation | __CFRelease + 216
8 CFNetwork | ___ZNK18QCoreSchedulingSet12performAsyncEU13block_pointerFvvE_block_invoke+ 52
9 libdispatch.dylib | __dispatch_call_block_and_release + 24
10 libdispatch.dylib | __dispatch_client_callout + 16
11 libdispatch.dylib | __dispatch_queue_serial_drain$VARIANT$mp + 608
12 libdispatch.dylib | __dispatch_queue_invoke$VARIANT$mp + 336
13 libdispatch.dylib | __dispatch_queue_serial_drain$VARIANT$mp + 280
14 libdispatch.dylib | __dispatch_queue_invoke$VARIANT$mp + 336
15 libdispatch.dylib | __dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
16 libdispatch.dylib | __dispatch_workloop_worker_thread$VARIANT$mp + 668
17 libsystem_pthread.dylib | _pthread_wqthread + 860
```

**Comment by bpoplauschi** [comment]
@hejinggen the stack trace doesn't show any SDWebImage code.
Can you reproduce this crash easily? Can you setup a demo project (simple) where it's reproducible?

**Comment by bpoplauschi** [comment]
Closing due to lack of response. @hejinggen feel free to reopen if you have more info.
