### ISSUE TITLE
Does this supports .svgz extension urls 

### ISSUE THREAD

**Issue by satheeshkumar8186** [rs/SDWebImage#2375]
I want to load image from from url, Images with .jpg,png i can show but .svgz I cant load .svgz how to do that,
eg: https://cfs22.simplicdn.net/ice9/course_images/160x160/Introduction_to_CodeIgniter.svgz

**Comment by mythodeia** [comment]
@satheeshkumar8186 svgs are not supported. also [here](https://github.com/rs/SDWebImage/issues/1365)
