### ISSUE TITLE
sd_setImageWithURL loading wrong image

### ISSUE THREAD

**Issue by x2rider** [rs/SDWebImage#2383]
### New Issue Checklist

* [X] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [X] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [X] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 11.4
 SDWebImage Version      | e.g. 4.4.1
 Integration Method      | e.g. manually
 Xcode Version           | e.g. Xcode 9
 Repro rate              | e.g. sometimes 20%
 Repro with our demo prj | e.g. does it happen with our demo project? No
 Demo project link       | N/A

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

I have an application that's been around for a few years, but this problem has come up and it's really bad now.  The application is like a contacts application with a set list of users.  The list will pull the photograph of each person from one of 2 web apis.  The first api is for a high res image, and if there is not an image for the person there, then it goes to another web api to pull a lower res image.

In my `UIImageView+WebCache`, I have a method called `loadImageForUser(User *user)`
It calls `sd_setImageWithURL` from webapi1
within the completion block, I check the image, if none comes back, then call `sd_setImageWithURL` again with the low res web api call.

The images are displayed in a `UICollectionView`

When the `sd_setImageWithUrl` is called, it calls `[self sd_cancelCurrentImageLoad]` first then makes a call for the image.

The result is, random cells show the same image for different people.  The names are correct, but the images are wrong, so we see mens pictures for women's names, and vice versa.  Sometimes adjacent cells have the same image.

I've also tried putting
```objective-c
[self.staffPhoto sd_cancelCurrentImageLoad];
self.staffPhoto.image = nil;
```
into the `prepareForReuse` method in the cell, which does get called, however, I don't think this is needed since the call above is calling `cancelCurrentImageLoad`.  Adding this did not change functionality.

During my testing, I've actually seen the wrong image come back for the url being called.  not sure how this happened.

**Comment by dreampiggy** [comment]
`sd_setImageWithURL:` will always firstlly reset your current imageView's image to the placeholder (or nil). So if you see sometimes two different cell get the same image. There must be that the URL you provide for different cells actually get the same image.

Could you please provide a demo, or show some pseudocode, for example, what view (UIImageView?FLAnimatedImageView?UIButton?) you use and how `sd_setImageWithURL:` was called. So that we can check it more easily.

**Comment by x2rider** [comment]
Hope this explains it.

`/**** PersonCollectionViewController ****/
PersonCollectionViewController : UIViewController<UICollectionViewDataSource,UICollectionViewDelegate,UICollectionViewDelegateFlowLayout,UISearchBarDelegate>

- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath{
    
    PersonCell *cell=[collectionView dequeueReusableCellWithReuseIdentifier:@"MyCell" forIndexPath:indexPath];
    
    Person * person = self.people[indexPath.row];
    
    [cell.personPhoto loadImageForPerson:person];
    
    cell.personName.text=person.FullName;
    cell.personTitle.text=person.title;
   
    return cell;
}



/**** UIImageView+LoadPersonImage.m ****/

-(void) loadImageForPerson:(Person *)person {

UIImage *photoNotAvailableImage = [UIImage imageNamed:@"PhotoNotAvailable.jpg"];

[self sd_setImageWithURL:person.hiResImageURL
		placeholderImage:photoNotAvailableImage
				 options:SDWebImageRefreshCached
			   completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
				   if(image != nil){
					   self.image = image;
					   NSLog(@"Hi Res Image Loaded from '%@'", imageURL);
				   }
				   else
				   {
					   NSLog(@"2 Photo Not Available, fetch '%@'", person.loResImageUrl);

					   [self sd_setImageWithURL:person.loResImageUrl
							   placeholderImage:photoNotAvailableImage
										options:SDWebImageRefreshCached
									  completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL) {
										  if(image != nil)
										  {
											  NSLog(@"Lo Res Image Loaded by %ld from '%@'", (long)cacheType, imageURL);
											  self.image = image;
										  }
										  else
										  {
										      self.image = photoNotAvailableImage;
										  }
									}];
					}
				}];
}
`

**Comment by dreampiggy** [comment]
@x2rider You're using `SDWebImageRefreshCached`. Which may call your completion block twice (when the cache is refreshed), once from the cache and another from the downloader. So the logic in your completion block must handle this. If you don't handle this, you may finally result 2 * 2 == 4 times of final `"Lo Res Image Loaded by...`

And to say, if you don't want to auto-set the image, you should provide `SDWebImageAvoidAutoSetImage`. Because by default we will trigger `[self setNeedsDisplay]` after loaded and trigger you imageView be rendered. Which maybe not you want because you have custom logic to set image during completion block

**Comment by x2rider** [comment]
Ok, so are you saying that I should not attempt to assign image if it comes back as status SDImageCacheTypeNone?  Since a refresh of the cache from the downloader would update the image?

**Comment by bpoplauschi** [comment]
@x2rider yes, that is what we are saying. Can you try it out and let us know?

**Comment by bpoplauschi** [comment]
Closing, @x2rider feel free to continue the conversation/reopen.

**Comment by x2rider** [comment]
I did get it working by setting SDWebImageAvoidAutoSetImage

// if image not in cache/expired
[self sd_setImageWithURL:person.hiResImageURL
    placeholderImage:photoNotAvailableImage
                      options:SDWebImageAvoidAutoSetImage
                 completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *hiResImageURL)
                {
                    if(image == nil){
                        [self sd_setImageWithURL:person.loResImageURL
                                placeholderImage:photoNotAvailableImage
                                         options:SDWebImageAvoidAutoSetImage
                                       completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, NSURL *imageURL)
                         {
                             if(image != nil)
                             {
                                 NSLog(@"Lo Res Image Loaded by %ld from '%@'", (long)cacheType, loResImageURL);
                                 self.image = image;
                             }
                             else
                             {
                                 self.image = photoNotAvailableImage;
                             }
                         }
                         ];
                        });
                    }
                    else
                    {
                        self.image = image;
                        NSLog(@"Hi Res Image Loaded from '%@'", hiResImageURL);
                    }
}
