### ISSUE TITLE
An error occurred in the SDWebImageImageIOCoder

### ISSUE THREAD

**Issue by yunjinghui123** [rs/SDWebImage#2401]
Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 8.3 or 9.3.2
 SDWebImage Version      |4.4.1
 Integration Method      |  cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | sometimes 
 Repro with our demo prj | No, it happen with our own app

### Issue Description and Steps

The following is the infomation of the crash.

```
vImage | 0x00000001815a0000 + 169520
1 vImage | vImagePermuteChannelsWithMaskedInsert_ARGB8888 + 304
2 vImage | vImagePermuteChannelsWithMaskedInsert_ARGB8888 + 304
3 CoreGraphics | _CGSConvertBGRX8888toRGBA8888 + 160
4 CoreGraphics | _argb32_image + 3232
5 libRIP.A.dylib | _ripl_Mark + 32
6 libRIP.A.dylib | _RIPLayerBltImage + 928
7 libRIP.A.dylib | _ripc_RenderImage + 260
8 libRIP.A.dylib | _ripc_DrawImage + 688
9 CoreGraphics | CGContextDrawImage + 408
10 Y | -[SDWebImageImageIOCoder sd_decompressedImageWithImage:] (SDWebImageImageIOCoder.m:233)
11 Y| -[SDWebImageImageIOCoder decompressedImageWithImage:data:options:] (SDWebImageImageIOCoder.m:180)
12 Y| -[SDWebImageCodersManager decompressedImageWithImage:data:options:] (SDWebImageCodersManager.m:124)
13 Y | __70-[SDWebImageDownloaderOperation URLSession:task:didCompleteWithError:]_block_invoke.279 (SDWebImageDownloaderOperation.m:0)
14 libdispatch.dylib | __dispatch_call_block_and_release + 24
15 libdispatch.dylib | __dispatch_client_callout + 16
16 libdispatch.dylib | __dispatch_queue_drain + 1448
17 libdispatch.dylib | __dispatch_queue_invoke + 132
18 libdispatch.dylib | __dispatch_root_queue_drain + 720
19 libdispatch.dylib | __dispatch_worker_thread3 + 108
20 libsystem_pthread.dylib | _pthread_wqthread + 816
```
Not often, but there are also probabilities.

**Comment by dreampiggy** [comment]
It seems a OOM issue, during `CGContextDrawImage`.

If you're facing this issue, on low-memory device (such like iPhone 4S/iPhone 5). I suggest to firstlly disable the decompress feature.

```objective-c
SDImageCache.sharedImageCache.config.shouldDecompressImage = NO;
SDWebImageDownloader.sharedDownloader.shouldDecompressImages = NO;
```

**Comment by yunjinghui123** [comment]
I turned on the image hard-coder to play the gif in the UIImageView, which seems to be because by this reason.i don't want to use the FLAnimatedImage frameworks,because it will replace UIImageView in project

**Comment by bpoplauschi** [comment]
@yunjinghui123 please see similar issues marked with [OOM label](https://github.com/rs/SDWebImage/labels/OOM)
Basically, if you are decoding big images, the app will run out of memory. You need to stop de decompression like instructed above, or use our options for scaling down large images to smaller ones.

**Comment by yunjinghui123** [comment]
Thank you very much, I will take your suggestions to optimize the code.
