### ISSUE TITLE
SDWebImagePrefetcher option to only store the loaded images in the disk cache (not memory)

### ISSUE THREAD

**Issue by edenman** [rs/SDWebImage#2403]
### New Issue Checklist

* [yup] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [yup] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [yup] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.4.1
 SDWebImage Version      | 4.3.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9
 
### Issue Description and Steps

I love SDWebImagePrefetcher: I have some very large images that I know I'll need to download if the user goes to a particular screen in my app.  I'd like to ensure those images are downloaded, but I _don't_ want to keep them in memory unless the user actually goes to that screen.  I see `.cacheMemoryOnly` as an option....any chance a `.cacheDiskOnly` option could be added?  Happy to submit a PR if you're open to it.

**Comment by dreampiggy** [comment]
See 5.x's [SDWebImagecStoreCacheType]
(https://github.com/rs/SDWebImage/blob/5.x/SDWebImage/SDWebImageDefine.h#L204-L208) feauture. You can pass `.disk` and let it store disk cache only.

```swift
imageView.sd_setImage(withURL: url, placeholderImage: nil, context: [.storeCacheType: .disk])`
```

In 4.x, however we have no plan to add this.

**Comment by dreampiggy** [comment]
Close this issue due the the solution above.
