### ISSUE TITLE
Can not load image with Url whitch contains ","

### ISSUE THREAD

**Issue by ghostfeng** [rs/SDWebImage#2408]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 11.0 / 10.0
 SDWebImage Version      | 4.4.1
 Integration Method      | cocoapods
 Xcode Version           |  Xcode 9.4
 Repro rate              | all the time (100%)
 Repro with our demo prj | it happen with your demo project

### Issue Description and Steps
Issue: Can not load image with Url whitch contains ","
sample url: http://img2.imgtn.bdimg.com/it/u=4158051125,1333702261&fm=21&gp=0.jpg

**Comment by mythodeia** [comment]
@ghostfeng can you provide a sample url? did you try the url in the demo project? which version of the library are you using? please fill the issue template when you add issues

**Comment by ghostfeng** [comment]
@mythodeia Thank you for your reply,I have completed the issues info and provide the sample url.I had an urge to solve the problem，Thanks~

**Comment by dreampiggy** [comment]
The image url can be downloaded correctlly. So maybe it's no a issue. Can I close this ?

**Comment by ghostfeng** [comment]
@dreampiggy This image can be open by the browser, I use SDWebImage to load image on iOS,now it can not show correctly, What should I do to load this image ? Any other settings should be set?

**Comment by zhongwuzw** [comment]
@ghostfeng comma is the reserved character, so it would not produce any issue.
Can you post some code? demo project would be the best if you can.

**Comment by ghostfeng** [comment]
@zhongwuzw  this is a demo:   https://git.coding.net/LiuYongfeng/SDWebImageDemo.git

**Comment by zhongwuzw** [comment]
@ghostfeng 403 forbidden, I think the reason is `User-Agent`. Server forbid the request `SDWebImage` make.

**Comment by kinarob** [comment]
`statusCode` is 403  ？

![wechatimg333](https://user-images.githubusercontent.com/29303030/43445516-29a7b170-94d9-11e8-9b28-fa0ceeefecf1.jpeg)

[http://img2.imgtn.bdimg.com/it/u=4158051125,1333702261&fm=21&gp=0.jpg](http://img2.imgtn.bdimg.com/it/u=4158051125,1333702261&fm=21&gp=0.jpg)

**Comment by dreampiggy** [comment]
Don't you try our demo ? The image url can be downloaded correctly, I said. Maybe it's the issue during you own downloader configuration. You can try some network debugger tools like [Charles](https://www.charlesproxy.com/) to identify the issue.

<img width="457" alt="2018-07-31 5 16 46" src="https://user-images.githubusercontent.com/6919743/43450544-84abf1c4-94e5-11e8-9c36-5a7e593f8cfb.png">

**Comment by zhongwuzw** [comment]
@dreampiggy You be treated by the project you tested 😂 . You use the `SDWebImage`'s demo, and `NSURLSession`'s default `User-Agent` contains the bundle name. Fortunately, the demo contains the string `iOS` like below. You can try after modify the bundle name to remove the string `iOS`.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/5061845/43450965-77720254-94e6-11e8-96a6-9d3d218bc208.png">

**Comment by desperadocarl** [comment]
@zhongwuzw  Yes ,it is actually a problem and works like you said.
@dreampiggy  You can try use a new demo.

 [[SDWebImageDownloader sharedDownloader] setValue:@"iPhone" forHTTPHeaderField:@"User-Agent"];
we can use above  to solve the problem，YYImage have the same problem，but  I don't know the deep reason
