### ISSUE TITLE
Add topics for SDWebImage

### ISSUE THREAD

**Issue by zhongwuzw** [rs/SDWebImage#2422]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Description and Steps

Currently, we don't set any topics for `SDWebImage`, `Github` provides a [topics](https://github.com/topics) feature that can help people find project more easily, e.x. people search `iOS` or `Image` `objective-c`, `Github` would suggest user what he most likely want. Other words, maybe we only can be searched by user when input `SDWebImage`. 😂 

@dreampiggy @bpoplauschi @skyline75489 @mythodeia , what's your guys think? 🤔 

Some topics:
[iOS](https://github.com/topics/ios?o=desc&s=stars)
[Objective-C](https://github.com/search?o=desc&q=objective-c&s=stars&type=Repositories)

**Comment by bpoplauschi** [comment]
Good point @zhongwuzw, I've also noticed this but didn't act upon it, my bad.
We need to figure out a list and then Olivier can set them

**Comment by zhongwuzw** [comment]
Some topics I think maybe we can add:
macos、ios、mobile、image、sdwebimage、objective-c、swift

**Comment by dreampiggy** [comment]
This seems adoptable...We can list some topic here and ask Olivier to add one because this need the repo owner to add :)

**Comment by bpoplauschi** [comment]
Let's look at similar projects and their topics:
- Nuke uses: cache, image, swift, webp, gif, progressive-jpegs
- Haneke and HanekeSwift: no topics
- FLAnimatedImage: no topics
- PINCache: carthage, cocoapods, objective-c, ios, cache
- Alamofire: networking, urlsession, urlrequest, httpurlresponse, request, response, swift, xcode, certificate-pinning, public-key-pinning, parameter-encoding, alamofire, cocoapods, carthage, swift-package-manager

So my proposals are:
- macos, ios, watchos, tvos
- image, jpg, jpeg, png, gif, webp
- cache
- objective-c, swift
- cocoapods, carthage

**Comment by zhongwuzw** [comment]
@bpoplauschi 👍 These topics you post already cover what the `SDWebImage` can do.

**Comment by bpoplauschi** [comment]
We will need this link when we ask Olivier to set the topics (once agreed): https://help.github.com/articles/classifying-your-repository-with-topics/

**Comment by bpoplauschi** [comment]
@dreampiggy do you agree with the list above?

**Comment by dreampiggy** [comment]
I remember the topic has a limitation of total count. Can we list the most important top 5 (or more) in all of above ?

My personal choice are `image`,  `cache`, `ios`, `sdwebimage` (This one is interesting...)

**Comment by bpoplauschi** [comment]
Alamofire has 15 topics, I also proposed 15, I guess that should work. All those topics are beneficial from a SEO point of view, since they will make our project even more easy to discover.

**Comment by zhongwuzw** [comment]
@bpoplauschi @dreampiggy Seems we reach the decision, let's do it ! 🍻

**Comment by bpoplauschi** [comment]
I reviewed the list a bit and I think we don't need `jpg` since we have `jpeg`.
I keep the proposal for 14 topics: `macos, ios, watchos, tvos, image, jpeg, png, gif, webp, cache, objective-c, swift, cocoapods, carthage`.

@rs please note our conversation here, do you think adding those topics to the project is a good idea? If so, can you please do it? You're the only one with permissions.

**Comment by rs** [comment]
done

**Comment by bpoplauschi** [comment]
Thank you @rs.
