### ISSUE TITLE
Error getting image

### ISSUE THREAD

**Issue by turkeyaa** [rs/SDWebImage#2436]
This is our online picture access address:

1. http://app.whhealth.gov.cn/yyzlWS/getImage.action?imageName=nolevel441628856%40%23%4032
2. http://app.whhealth.gov.cn/yyzlWS/getImage.action?imageName=nolevel441628856%40%23%40119

Two different images, accessed through the browser, are normal. But in the project, the picture was not shown correctly and the feeling was overwritten

<img width="371" alt="2018-08-10 11 47 01" src="https://user-images.githubusercontent.com/7940089/43940287-813518ae-9ca1-11e8-88e5-9a7f1d183656.png">

Client code：
[_iconView sd_setImageWithURL:[NSURL URLWithString:avatar_url] placeholderImage:[UIImage imageNamed:@"avator.png"]];

Looking forward to your reply

**Comment by bpoplauschi** [comment]
@turkeyaa I assume you found your answer. If not, feel free to reopen the issue and let us organize it a bit by providing the issue template info - I added the template, just fill in
