### ISSUE TITLE
Not Caching to disk 

### ISSUE THREAD

**Issue by bradmuzza** [rs/SDWebImage#2446]
### New Issue Checklist

* [ ] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ ] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ ] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 11.2
 SDWebImage Version      | 4.0
 Integration Method      |cocoapods 
 Xcode Version           | Xcode 9
 Repro rate              | 
 Repro with our demo prj |
 Demo project link       | 

### Issue Description and Steps

I am using  the following code to set the image in a tableview cell
```swift
 Image.sd_setImage(with:URL(string: imageUrl), placeholderImage: #imageLiteral(resourceName: "image"), options:[.continueInBackground,.scaleDownLargeImages])
```
however, after a  short period of time(I am assuming when the memory cleared) my images need to be download again. My assumption is that the images are not saving to disk and or my disk is getting purged  too often. 

I have tried adding and remove the gobal functions for maxCache and Age etc without any success. 

Have i missed something in my code

**Comment by dreampiggy** [comment]
Hi. Did you setup a `maxCacheSize` or `maxCacheAge` ? This is the control for disk cache only (The other two like `maxMemoryCost` && `maxMemoryCount` is about memory cache). When you setup these options, it will effect the cache age for expiration for disk image. We check the cache expiation each time when your application enter the background mode.

**Comment by bradmuzza** [comment]
Not not initially , but then I set these property in my app delegate see of it would fix the issues ,however, it didn't so I have since removed

**Comment by bradmuzza** [comment]
also updated the post  with the categories I understand

**Comment by bpoplauschi** [comment]
@bradmuzza thanks for your interest in our project and creating an issue.
Regarding the situation you are describing, sounds very weird. Can you create a small demo project where this issue replicates and share it with us?

**Comment by bpoplauschi** [comment]
Closing due to lack of response. @bradmuzza feel free to reopen and continue the conversation
