### ISSUE TITLE
SDWebImageFrame not correct.

### ISSUE THREAD

**Issue by daydayfree** [rs/SDWebImage#2455]
Caused by [this commit](https://github.com/rs/SDWebImage/commit/8a034a403b2f117b5ad5e7f149b2b25f3abe313f)

```
- UIImage *image = [[UIImage alloc] initWithCGImage:imageRef scale:scale orientation:UIImageOrientationUp];
+ UIImage *image = [[UIImage alloc] initWithCGImage:imageRef];
```

**Comment by daydayfree** [comment]
@dreampiggy Thank you for your reply.

When I use `UIImageView` display a local gif image which size is 40 * 40.

Example:

```
UIImageView *imageView = [[UIImageView alloc] init];
NSData *data = [NSData dataWithContentsOfFile:@"/path/to/gif"];
imageView.image = [UIImage sd_animatedGIFWithData:data];
imageView.frame = CGRectMake(0, 0, 20, 20);

UIBarButtonItem *item = [[UIBarButtonItem alloc] initWithCustomView:imageView];
```

imageView's size will changed to 40 * 40.

It's correct when using `FLAnimatedImageView`. I think this has nothing to do with `SDWebImage`. So I closed the issue.

**Comment by dreampiggy** [comment]
@daydayfree Are you using the `UIBarButtonItem` for navigation bar or tab bar ? The frame for your custom view, it's not controlled by yourself. It's controlled by the navigationBar or the TabBar. Your custom view will receive frame change from UIKit internal method.

**Comment by daydayfree** [comment]
@dreampiggy Yes. But it's worked fine with 4.2.2. Maybe the navigationBar draw `UIBarButtonItem` custom view by image's scale.
