### ISSUE TITLE
release 模式下url 为空会莫名其妙崩溃，debug模式没有问题

### ISSUE THREAD

**Issue by cuiyu8580** [rs/SDWebImage#2457]
写中文应该没有问题吧，竟然遇到这个莫名其妙的问题

**Comment by kinarob** [comment]
Maybe you should run Demo to test this problem!

**Comment by cuiyu8580** [comment]
嗯，我调试确实没有问题，就是线上的崩了。我查看了一下就是url给空了，调试的时候能正确显示placeholderImage

**Comment by dreampiggy** [comment]
Please use the English to fire the issue. Because our colleborator are from across the country.

And please fill the issue template, instead of totally removing it. Or there is not enough concept to investigate this issue.
