### ISSUE TITLE
Image cannot add rounded corners, or how to?

### ISSUE THREAD

**Issue by netgfx** [rs/SDWebImage#2484]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        |11.0
 SDWebImage Version    |4.1.0
 Integration Method      |cocoapods
 Xcode Version          |Xcode 9
 Repro rate              |all the time (100%)

### Issue Description and Steps

Is there a reason why an image wouldn't add rounded corners with the following code?

```
coverImageView.sd_setImage(with: episode.episodeCoverImage, completed: { image, error, cacheType, imageURL in
                    self.coverImageView.layer.cornerRadius = 16
                    self.coverImageView.layer.masksToBounds = true
                    self.coverImageView.clipsToBounds = true
                    self.layoutIfNeeded()
                })
```

The image is contained within a Custom TableView Cell.

**Comment by bpoplauschi** [comment]
@netgfx no idea. I recommend you do a visual debug (using Xcode) and see what the composition of the layers is.

**Comment by pandapancake** [comment]
I think you might did something wrong? Mine code is working.

    `cell.newsImageView.sd_setImage(with: URL(string: newsArticles[indexPath.row].thumbnail ?? ""), placeholderImage: UIImage(named: ""))
        
        cell.newsImageView.layer.cornerRadius = 10
        cell.newsImageView.layer.masksToBounds = true`


![screen shot 2018-09-14 at 1 42 19 am](https://user-images.githubusercontent.com/32947517/45531808-70913080-b7bf-11e8-94ba-818feca8f33f.png)
