### ISSUE TITLE
Installation through Carthage fails with Xcode 10

### ISSUE THREAD

**Issue by ivan-konov** [rs/SDWebImage#2489]
### New Issue Checklist

* [ y] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [ y] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [ y] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS
 Platform Version        | 12.0
 SDWebImage Version      | 4.4.2
 Integration Method      | Carthage 0.30.1
 Xcode Version           | Xcode 10(final and betas)
 Repro rate              | all the time (100%) 
### Issue Description and Steps

I get the following error when I try to update and build with Carthage:

```
*** Building scheme "SDWebImage iOS" in SDWebImage.xcworkspace
*** Building scheme "SDWebImage watchOS" in SDWebImage.xcworkspace
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -workspace /Users/user/Documents/work/application/Carthage/Checkouts/SDWebImage/SDWebImage.xcworkspace -scheme SDWebImage\ watchOS -configuration Release -derivedDataPath /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/SDWebImage/4.4.2 -sdk watchsimulator -destination platform=watchOS\ Simulator,id=B35EB6D9-8741-4DE3-9C02-D7D3D60AE244 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/user/Documents/work/application/Carthage/Checkouts/SDWebImage)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/l6/4zrqf_m91mzcx175p7t8klq40000gn/T/carthage-xcodebuild.6LPWsm.log
```
Thanks!

**Comment by dreampiggy** [comment]
I try to use Carthage to build SDWebImage 4.4.2 with Xcode 10. It works without any issue. Could you please paste your console output to show what cause this issue ?


```shell
➜  SwiftDemo git:(master) ✗ xcode-select --print-path
/Applications/Xcode 10.app/Contents/Developer
➜  SwiftDemo git:(master) ✗ carthage update --platform watchos --configuration DEBUG --verbose
...
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/lizhuoli/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/SDWebImage/4.4.2/Build/Products/Release-watchsimulator/SDWebImage.framework

Touch /Users/lizhuoli/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/SDWebImage/4.4.2/Build/Products/Release-watchsimulator/SDWebImage.framework (in target: SDWebImage watchOS)
    cd /Users/lizhuoli/Documents/Demo/SwiftDemo/Carthage/Checkouts/SDWebImage
    /usr/bin/touch -c /Users/lizhuoli/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/SDWebImage/4.4.2/Build/Products/Release-watchsimulator/SDWebImage.framework

** BUILD SUCCEEDED **
```

**Comment by zhongwuzw** [comment]
@ivan-konov Seems `Carthage` bug, please see [2561](https://github.com/Carthage/Carthage/pull/2561).

**Comment by ivan-konov** [comment]
@zhongwuzw thanks for the clarification!
