### ISSUE TITLE
Stop webp animation

### ISSUE THREAD

**Issue by animis93** [rs/SDWebImage#2499]
I have a webp animated image that should only do one loop, but it does not stop. How can I stop the animation?

**Comment by dreampiggy** [comment]
`UIImage` itself only contains the image [frames](https://developer.apple.com/documentation/uikit/uiimage/1624117-images?language=objc) and image [frame duration](https://developer.apple.com/documentation/uikit/uiimage/1624155-duration?language=objc) information. The frame loop count information is only available in the `UIImageView` level via [animationRepeatCount](https://developer.apple.com/documentation/uikit/uiimageview/1621070-animationrepeatcount?language=objc) property.

We keep the animated image loop count information in the [sd_imageLoopCount](https://github.com/rs/SDWebImage/blob/master/SDWebImage/UIImage%2BMultiFormat.h#L24) category property. So if you think the image loop count is important for your use case, you should set it to the imageView by yourself after image is loaded.

You also can check the developer documentation about the animated image usage, here I just show your simple code about it.

```objectivec
    [imageView1 url placeholderImage:nil options:SDWebImageRetryFailed completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
        // Check whether it's a `UIAnimatedImage`
        if (image.images) {
            imageView1.animationImages = image.images; // specify frames
            imageView1.animationDuration = image.duration; // specify duration
            imageView1.animationRepeatCount = image.sd_imageLoopCount; // specify loop count
            imageView1.image = image.images.lastObject; // specify what image to display when animation stop
        } else {
            imageView1.animationImages = nil;
            imageView1.animationDuration = 0;
            imageView1.animationRepeatCount = 0;
            imageView1.image = image;
        }
    }];
```

**Comment by dreampiggy** [comment]
If you're using the `SDAnimatedImageView` introduced in 5.x, you don't need this check because by default we follow the image loop count from the `SDAnimatedImage`. However, you can still specify a custom loop count instead of loop count from original image format. Set the `shouldCustomLoopCount` to YES and then use the `animationRepeatCount` property.

```objective-c
SDAnimatedImageView *imageView2;
imageView2.shouldCustomLoopCount = YES;
imageView2.animationRepeatCount = 1;

[imageView2 sd_setImageWithURL:url placeholderImage:nil options:SDWebImageRetryFailed completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
    NSAssert([image conformsToProtocol:@protocol(SDAnimatedImage)], @"should be a custom animated image class");
    NSUInteger loopCount = ((id<SDAnimatedImage>)image).animatedImageLoopCount; // The loop count from original image meta information
    NSAssert(loopCount == 0, @"custom loop count, not equal to specified imageView loop count");
}];
```

**Comment by dreampiggy** [comment]
Maybe we can also add this to the wiki page if there are more people ask this question. Although you can find it on the developer documentation, there may be some developer who don't read carefully about it :)

So I just close this issue, if you have any more question, feel free to reopen this issue.
