### ISSUE TITLE
如何修改缓存图片的key

### ISSUE THREAD

**Issue by puhahalx** [rs/SDWebImage#2501]
当我调用- (void)sd_setImageWithURL:(nullable NSURL *)url placeholderImage:(nullable UIImage *)placeholder方法时,默认会使用完整的url来作为缓存的key.现在有一种情况就是每次刷新url的参数都会变(如https:www.XXX.com/app.png?signDate=XXXX  signDate每次刷新都会变),但是图片是同一张图片,所以能不能有没有一个方法是调用sd_setImageWithURL方法时根据url的path作为缓存的key(即https:www.XXX.com/app.png)

**Comment by dreampiggy** [comment]
Check [Using cache key filter](https://github.com/rs/SDWebImage/wiki/How-to-use#using-cache-key-filter). You can provide a custom logc to generate the cache key for URLs

**Comment by puhahalx** [comment]
> Check [Using cache key filter](https://github.com/rs/SDWebImage/wiki/How-to-use#using-cache-key-filter). You can provide a custom logc to generate the cache key for URLs

Thank you for your prompt and effective reply
