### ISSUE TITLE
Images in webp format cannot be loaded properly on devices in iOS12 system.

### ISSUE THREAD

**Issue by tanghaiyang1992** [rs/SDWebImage#2504]
Images in webp format cannot be loaded properly on devices in iOS12 system.

**Comment by dreampiggy** [comment]
Duplicated for #2347 . Upgrade to [v4.4.1](https://github.com/rs/SDWebImage/releases/tag/4.4.1) to solve this problem.

Note: Please using GitHub search before fire the issue. And please **FILL THE ISSUE TEMPLATE**. We'll auto-close the issue without valid issue template in the future.
