### ISSUE TITLE
Does it supports interlaced png?

### ISSUE THREAD

**Issue by JuanMunhoesJr** [rs/SDWebImage#303]
I would like to know something curious. This class has a support for a progressive download. But if i save interlaced png in web and download will i have the effect interlaced png?

just to see something what i'm talking about take a look to this demo:
http://www.codinghorror.com/blog/2005/12/progressive-image-rendering.html

example 1 its exactly what progressive does. But and with example 2?

Gratz

**Comment by pedro380085** [comment]
Is it supported now?

**Comment by bpoplauschi** [comment]
I don't think it's supported. Someone should check and make sure

**Comment by davidseek** [comment]
any updates?

**Comment by dreampiggy** [comment]
Please use `SDWebImageOptions` with `SDWebImageProgressiveDownload` on and check the result.

The actual standard `interlaced` support(sometime it called `progressive` for JPEG format) is in #1987 . The image will look like 'mosaic' and then become more clearity. Such as this one:
![](https://blog.codinghorror.com/content/images/uploads/2005/12/6a0120a85dcdae970b0128776fcadb970c-pi.gif)

The previous version also support the common `interlaced` png loading. It will look like `baseline` multiple times and will keep an grey background. Check: #1899 for detail.
![](https://blog.ibireme.com/wp-content/uploads/2015/11/image_interlaced.gif)

You can grab some interlaced png files and try the demo with that URL.

**Comment by dreampiggy** [comment]
The interlaced png image is here:

![mew_interlaced](https://user-images.githubusercontent.com/6919743/30281527-433bbf4c-9745-11e7-935f-f0eccdb3848e.png)

**Comment by dreampiggy** [comment]
This is available in 4.1.2. Please have a try.
