### ISSUE TITLE
iCloud - Disable backup for images (NSURLIsExcludedFromBackupKey)

### ISSUE THREAD

**Issue by NitWitStudios** [rs/SDWebImage#343]
I recently submitted an app update to the app store after adding your library and it was rejected for:
"2.23: Apps must follow the iOS Data Storage Guidelines or they will be rejected - In particular, we found that on launch and/or content download, your app stores 22.84 MB."

I had this problem before when storing the images myself (not using SDWebImage library). I just had to set the key 'NSURLIsExcludedFromBackupKey' to 'YES' on each image as I saved them and Apple approved it.

I was wondering if there is a simple way to do this for your library, how to do it, and if it is going to cause any issues with caching, etc? I haven't dived into the code yet, but wanted to post this in case it turns out to be more complicated.

**Comment by kevindelord** [comment]
We have the problem for one of our app. Same code 6 or 7 apps and one got randomly rejected for the same reason.
I applied a workaround without modifying the library. This is what I did (swift code):
````
// Just download the image
SDWebImageDownloader.sharedDownloader().downloadImageWithURL(url, options: .allZeros, progress: nil) { (image: UIImage!, data: NSData!, error: NSError!, finished: Bool) in
    if (image != nil && finished == true) {
          // Store it on the disk
         SDImageCache.sharedImageCache().storeImage(image, forKey: thumb)
         // Get the path and add the backup attribute - as explained everywhere on the web :)
          if let path = SDImageCache.sharedImageCache().defaultCachePathForKey(thumb) {
               AssetsManager.addSkipBackupAttributeToItemWithFileName(path)
         }
    }
}
````

**Comment by XBeg9** [comment]
Any updates? SDWebImageDownloader should support this.
