### ISSUE TITLE
ImageIO is faster

### ISSUE THREAD

**Issue by Constantine-Fry** [rs/SDWebImage#386]
I have done performance test ImageIO vs NSData. I opened 95 files with 800x800 pixels on my iPod5.
NSData+UIImage = 1.498098 (your current implementation of reading image file from disk)
NSData+ImageIO = 1.637306
ImageIO = 0.429998

ImageIO is 3x faster. 

ImageIO

```
int count = 0;
CFAbsoluteTime st = CFAbsoluteTimeGetCurrent();
for (NSURL *fileURL in fileEnumerator){
    count ++;
    @autoreleasepool {
    CGImageSourceRef imageSource = CGImageSourceCreateWithURL((__bridge CFURLRef)fileURL,
                                                              NULL);

    CGImageRef image = CGImageSourceCreateImageAtIndex(imageSource,
                                                       0,
                                                       NULL);
    UIImage *im = [UIImage imageWithCGImage:image];
    CFRelease(image);
    CFRelease(imageSource);

    }
}
NSLog(@"time:%f",CFAbsoluteTimeGetCurrent() - st);
NSLog(@"%d",count);
```

NSData+ImageIO

```
int count = 0;
CFAbsoluteTime st = CFAbsoluteTimeGetCurrent();
for (NSURL *fileURL in fileEnumerator){
    count ++;
    @autoreleasepool {

    NSData *data = [NSData dataWithContentsOfURL:fileURL];
    CGImageSourceRef imageSource = CGImageSourceCreateWithData((__bridge CFDataRef)(data), NULL);

    CGImageRef image = CGImageSourceCreateImageAtIndex(imageSource,
                                                       0,
                                                       NULL);
    UIImage *im = [UIImage imageWithCGImage:image];
    CFRelease(image);
    CFRelease(imageSource);

    }
}
NSLog(@"time:%f",CFAbsoluteTimeGetCurrent() - st);
NSLog(@"%d",count);
```

NSData+UIImage

```
int count = 0;
CFAbsoluteTime st = CFAbsoluteTimeGetCurrent();
for (NSURL *fileURL in fileEnumerator){
    count ++;
    @autoreleasepool {

    NSData *data = [NSData dataWithContentsOfURL:fileURL];
    UIImage *i = [UIImage imageWithData:data];

    }
}
NSLog(@"time:%f",CFAbsoluteTimeGetCurrent() - st);
NSLog(@"%d",count);
```

**Comment by bpoplauschi** [comment]
Is anyone here interested in trying this approach in a Pull Request?

**Comment by CodeLife2012** [comment]
Maybe image created by `ImageIO`  is lazy load it's content.

**Comment by skyline75489** [comment]
@CodeLife2012  `UIImage` is kind of `lazy loaded` in its nature. No matter how you create it, `UIImage` won't do the decompression thing until it's being displayed in `UIView`.

Here in the example `UIImage` is just created. If you're doubting the equality of the test, I don't think there's a point, since all those methods are just doing the same instance-creation part.

**Comment by CodeLife2012** [comment]
I said `Lazy load`  is not about `decompression `, it just the load of the image. When create a source with `CGImageSourceCreateWithURL`, actually the file isn't loaded, maybe `mmap` to the file. The file is loaded into memory when first access.

So there is no difference between `NSData+ImageIO` and `NSData+UIImage`.

**Comment by CodeLife2012** [comment]
I have create a [demo](https://github.com/CodeLife2012/TestImageLoad) for test, you can see clearly the real memory consumed between two approaches(3.4m->160m). So when use  `CGImageSourceCreateWithURL ` the file is actually not loaded into memory instantly.

@skyline75489

**Comment by skyline75489** [comment]
@CodeLife2012 Interesting. Looks like `ImageIO` is merely a trade-off between speed and memory. In that case, I'm not sure that #1707 is really that necessary. CC @bpoplauschi

**Comment by bpoplauschi** [comment]
Guys, based on #1991 now we can add another coder with the suggestions here. Or people can directly do that inside their projects, as now we can plugin the coders

**Comment by bpoplauschi** [comment]
Per my last comment, closing
