### ISSUE TITLE
Caching images in disk only, but not in memory. Is that possible?

### ISSUE THREAD

**Issue by yorkwang** [rs/SDWebImage#391]
My app takes up a lot of memory already, I want to reduce memory usage as much as possible.

**Comment by marcelosalloum** [comment]
+1

**Comment by maha-ghonam** [comment]
+1

**Comment by mythodeia** [comment]
everyone interested should try [this pull](https://github.com/rs/SDWebImage/pull/1130)

**Comment by Savankumar-vaishnav** [comment]
+1

**Comment by mythodeia** [comment]
@Savankumar-vaishnav this is already done via https://github.com/rs/SDWebImage/pull/1217

**Comment by gmogames** [comment]
+1

**Comment by bpoplauschi** [comment]
@gmogames This feature was added in 3.7.4 release. You just need to use the `shouldCacheImagesInMemory` property from `SDImageCache` and set it to NO.

**Comment by AlfredDuck** [comment]
+1

**Comment by bcattle** [comment]
In case this saves anyone else time, in recent SDWebImage this property has moved to `SDImageCache.config. shouldCacheImagesInMemory `

**Comment by trannguyenvu91** [comment]
`SDImageCache.config.shouldCacheImagesInMemory = NO` doesn't work for me :(

**Comment by Arrabidas92** [comment]
Here is the new syntax to use `SDImageCache.shared().config.shouldCacheImagesInMemory = false`
