### ISSUE TITLE
Support for ALAssets

### ISSUE THREAD

**Issue by Glnn** [rs/SDWebImage#45]
I've been working with the ALAssetsLibrary for the past few days, and it is really horrible in terms of (fast) asynchronous image fetching.

I've build a couple of classes inspired by SDWebImage to have proper caching and asynchronous image fetching.

Would it be interesting to have support for ALAssets built into SDWebImage? I'd find it very useful if I could provide an asset:// URL instead of a http:// URL and it would automatically retrieve the image from a singleton ALAssetsLibrary.

Looking forward to hearing what you guys think.

Glenn

**Comment by iossaif** [comment]
Hello sir ,
@bpoplauschi  is asseturl functionality supported now?
I am using sd_setImage function for getting images from photo library.url is something like this
 assets-library://asset/asset.PNG?id=D0282AEB-C86F-4422-B404-132BCCFE44DD&ext=PNG
Image is never fetched from library and I cross checked imageview's image in cell its nil.
Please reply as soon as possible.I would be grateful to you.Kudos to your team
Thank you

**Comment by mythodeia** [comment]
@iossaif Asset Urls are not supported

**Comment by dreampiggy** [comment]
Seems long time passed. ALAsset is not long supoort from iOS 8. And our SDWebImage 5.x has already drop the iOS 7 support. Many oneday we can add PHAsset support. Thansks for all of you who is interested about this issue. We can create a new PR for PHAsset request :)
