### ISSUE TITLE
the thread dead

### ISSUE THREAD

**Issue by erlangzhang** [rs/SDWebImage#466]
the thread dead again in the newest code..test in ios5

**Comment by shiwensong** [comment]
I have some questions you want to ask, I used to set the value SDWebImage UIImageView, but this time APP crash, crash CFRunLoopRun (); I printed out the image links, image links is wrong, no pictures. If the URL is not a formal link, it will not crash it! Great God enlighten request.

**Comment by shiwensong** [comment]
Consult this information:  bool _WebTryThreadLock(bool), 0x16149910: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...

**Comment by gph1991** [comment]
What has happened ？

**Comment by steewsc** [comment]
I have the same problem as @shiwensong (happens on iPhone 6s). 
Any fix/workaround?
Thanks

**Comment by bpoplauschi** [comment]
@steewsc We'll look into this. A possible cause is the difference between main queue and main thread described here: http://blog.benjamin-encz.de/post/main-queue-vs-main-thread/

**Comment by bpoplauschi** [comment]
Let's close this issue, see if it happens again with 4.0.0 (4.0.0-beta is available for download, 4.0.0 official release is on its way). We have solved the main queue vs main thread issue
