### ISSUE TITLE
semaphore_wait_trap encountered when initializing large number of downloads.

### ISSUE THREAD

**Issue by joshuafeldman** [rs/SDWebImage#491]
When trying to download a large number of files with SDWebImageManager using -downloadWithURL:options:progress:completed the application's main UI is locked with semaphore_wait_trap which I believe is encountered when you exceed the maximum number of threads.

It is worth noting that I have changed the maxConcurrentDownloads to NSOperationQueueDefaultMaxConcurrentOperationCount. Simply doing this though should not cause the operating system to trap all thread execution.

**Comment by mythodeia** [comment]
closing this. feel free to reopen if you still encounter issues with the latest version of the lib
