### ISSUE TITLE
Crash -[SDWebImageDownloaderOperation start]

### ISSUE THREAD

**Issue by cherpake** [rs/SDWebImage#506]
Thread 12 Crashed:
0   libobjc.A.dylib                     0x3778fb66 _objc_msgSend + 6
1   Foundation                          0x2ddd560f __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 55
2   Foundation                          0x2ddd5551 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 205
3   Foundation                          0x2ddd546d -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 61
4   Foundation                          0x2ddd57bd _NSURLConnectionDidReceiveData + 81
5   CFNetwork                           0x2d1053fd ___ZN27URLConnectionClient_Classic29_delegate_didReceiveDataArrayEv_block_invoke + 169
6   CFNetwork                           0x2d104c67 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 55
7   CFNetwork                           0x2d136397 ___ZNK17CoreSchedulingSet13_performAsyncEPKcU13block_pointerFvvE_block_invoke + 19
8   CoreFoundation                      0x2d3cdf71 _CFArrayApplyFunction + 37
9   CFNetwork                           0x2d09cf15 RunloopBlockContext::perform() + 165
10  CFNetwork                           0x2d09cde5 MultiplexerSource::perform() + 221
11  CFNetwork                           0x2d09cc75 MultiplexerSource::_perform(void*) + 49
12  CoreFoundation                      0x2d465f27 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
13  CoreFoundation                      0x2d4653ef __CFRunLoopDoSources0 + 207
14  CoreFoundation                      0x2d463bdf __CFRunLoopRun + 631
15  CoreFoundation                      0x2d3ce541 _CFRunLoopRunSpecific + 525
16  CoreFoundation                      0x2d4121ab _CFRunLoopRun + 99
17  App                            0x001f60ff -[SDWebImageDownloaderOperation start] + 487
18  Foundation                          0x2de6dafd __NSOQSchedule_f + 61
19  libdispatch.dylib                   0x37c7d4bf _dispatch_async_redirect_invoke + 111
20  libdispatch.dylib                   0x37c7e7e5 _dispatch_root_queue_drain + 225
21  libdispatch.dylib                   0x37c7e9d1 _dispatch_worker_thread2 + 57
22  libsystem_pthread.dylib             0x37da8dff __pthread_wqthread + 299

**Comment by bpoplauschi** [comment]
Let's close this issue, see if it happens again with 4.0.0 (4.0.0-beta is available for download, 4.0.0 official release is on its way).
