### ISSUE TITLE
GIF Memory Leak - VM: ImageIO_GIF_Data

### ISSUE THREAD

**Issue by mattdonnelly** [rs/SDWebImage#548]
Hi, I'm using SDWebImage on iOS 7 and am noticing a very high increase in memory usage any time a GIF is loaded from a URL. I'm not sure if it's a problem with SDWebImage or just iOS 7, as I can't find the exact like the allocations occur at but I have noticed that the problem doesn't occur when a cached version is loaded instead.

Here's a screenshot after inspecting it in Intsruments:

![screen shot 2013-11-07 at 23 09 42](https://f.cloud.github.com/assets/342412/1496867/0ab575c8-4802-11e3-831e-c0bd73ee3542.png)

**Comment by amazingmanthere** [comment]
Same issue.
I suspect that some gif images have many image frames so that using UIImageView to render and show these frames requires a lot of memory.
Now my solution is that limit gif data size in method `+(UIImage*)sd_imageWithData:(NSData*)data`.

```
+(UIImage*)sd_imageWithData:(NSData*)data
{
    UIImage *image;
   if([data sd_isGIF] && data.length < GifLimitSize)
````

**Comment by exherb** [comment]
I created a swizzle for SDWebImage + FLanimatedImage and works great.

https://gist.github.com/exherb/1257263e350831d6c205

**Comment by bpoplauschi** [comment]
We have replaced our GIF component with a library from Flipboard (FLAnimatedImage). Could you try our 4.x branch ([instructions](https://github.com/rs/SDWebImage/tree/4.x#animated-images-gif-support)) and see if it helps?

**Comment by bpoplauschi** [comment]
Closing. The FLAnimatedImage solution replacing our own GIF is integrated into the 4.x branch.
