### ISSUE TITLE
How to solve the memory consumption for the decodedImageWithImage

### ISSUE THREAD

**Issue by SpaceTimeLoop** [rs/SDWebImage#586]
![sdwebimage](https://f.cloud.github.com/assets/3761063/1731039/417bc268-62f8-11e3-932b-9cb96179b5a7.png)

![screenshoot](https://f.cloud.github.com/assets/3761063/1731086/9375f236-62f9-11e3-99bd-1bdeffc00199.png)

**Comment by rromanchuk** [comment]
This is indeed a problem here. But I'm less worried about the memory pressure this creates, but i am worried because it seems it's never released until persisted memory reaches above 300mb. Is this an enumeration-without-an-autorelease problem?  I haven't jumped into the source yet, but this expansion somehow has seems to be worse than previous versions.  I'm seeing long lived `CGDataProviderCreateWithCopyOfData` caused by `decodedImageWithImage`  Maybe i'm only seeing it now because of larger devices, larger photos, etc. 

Wasn't there just a recent change on maximum concurrent downloads? I could see that exacerbating this issue.

**Comment by rromanchuk** [comment]
Maybe we are conflating this issue with something else. I see no problem with a huge VM CG Raster Data, but i'm noticing a lot more memory warning than the past. Let me try and isolate the didReceiveMemory events, maybe it's more related to prefetching

**Comment by rromanchuk** [comment]
Actually it looks like a lot has already been done on this front

https://github.com/rs/SDWebImage/pull/996
https://github.com/rs/SDWebImage/pull/884

**Comment by rromanchuk** [comment]
And again here https://github.com/rs/SDWebImage/issues/602

**Comment by rromanchuk** [comment]
@bpoplauschi  you should close all these duplicates already being tracked https://github.com/rs/SDWebImage/issues/538

**Comment by KanybekMomukeyev** [comment]
same here, this takes a lot of memory, and don not release. 

![screen shot 2015-02-03 at 13 03 31](https://cloud.githubusercontent.com/assets/866641/6015962/3221f94e-aba5-11e4-8de7-cded63524068.png)
+ (UIImage *)decodedImageWithImage:(UIImage *)image 
{
}

**Comment by daveklotz** [comment]
We are having the same problem. Short circuiting decodeImageWithImage with a "return image" seems to solve our problem, and hasn't seemed to cause any problems. At least not yet.

This seems to have been open for a while. Any chance of this being addressed @rs ? I don't want to have to use some separate fork, or ditch SdWebImage altogether, but we can't live with this as an issue.

**Comment by harishkashyap** [comment]
We did some modifications to it and is working for us; fixes the crash.https://github.com/harishkashyap/SDWebImage

**Comment by vivekseth** [comment]
This appears to still be buggy on 3.7.3. I'm loading a total of 30 images and seeing a roughly 300mb allocation from this method

**Comment by luosky** [comment]
same here

**Comment by krupanshu** [comment]
is there any workaround to solve this memory issue ? Any help or guidance will be very helpful.

**Comment by mythodeia** [comment]
@krupanshu 
shouldDecompressImages available for both
SDImageCache & SDWebImageDownloader
```
[[SDImageCache sharedImageCache] setShouldDecompressImages:NO];
[[SDWebImageDownloader sharedDownloader] setShouldDecompressImages:NO];
```

**Comment by donholly** [comment]
Is anyone actually seeing crashes as a result of this?

I'm fairly confident that ImageIO is smart enough to manage it's own cache and the increase in perceived memory usage is actually okay. It will purge as necessary. It seems to be a little greedy, but that's actually fine so long as it's not being "too" greedy and crashing your app as a result of this.

**Comment by bpoplauschi** [comment]
Same as #538. 
#787 and 00bf467 should give you a good solution for dealing with large images. Together with the GIF handled by FLAnimatedImage, this ticket should be done now.
