### ISSUE TITLE
Need to use setImageWithURL for local file

### ISSUE THREAD

**Issue by abheyrajbsb** [rs/SDWebImage#697]
I have a few images from a URL and a few local images, so I am passing the file path in the setImageWithURL method but its not working. Any tips?

**Comment by Akki9326** [comment]
@bpoplauschi  is not Working 

> You could try to add the path to the local images using [SDImageCache addReadOnlyCachePath:]. Then try to use setImageWithURL: by constructing the URL like this:
> 
> NSURL *fileURL = [[NSURL alloc] initFileURLWithPath:path isDirectory:NO];

**Comment by bpoplauschi** [comment]
thanks @Akki9326. Will look into this, not sure if we planned to support this.

**Comment by mythodeia** [comment]
@bpoplauschi do we have plans for supporting local image urls or should i close this?

**Comment by bpoplauschi** [comment]
@mythodeia We don't plan for that. Our library is supposed to do image download and caching. If the image is already local, there is no point in that. I would close this.

**Comment by alejandro-menendez** [comment]
I found the image gets loaded with following code. But, it's size is changed badly when it loads for the first time. After that, it works well.
```
SDImageCache.sharedImageCache().addReadOnlyCachePath(absoluteStr)
imagePreview.sd_setImageWithURL(URL, placeholderImage: nil, options: .CacheMemoryOnly)
imagePreview.layer.masksToBounds = true
```

**Comment by MilkerLiu** [comment]
youcan custom`SDWebImageDownloaderOperation`, 

step 1, wirte a subclass `MPImageDownloaderOperation`
```
@interface MPImageDownloaderOperation: SDWebImageDownloaderOperation

- (void)callCompletionBlocksWithImage:(nullable UIImage *)image
                            imageData:(nullable NSData *)imageData
                                error:(nullable NSError *)error
                             finished:(BOOL)finishe;

- (void)done;

@end

@implementation MPImageDownloaderOperation {
}
// this method run in sub-thread
- (void)start {
    NSString *url = self.request.URL.absoluteString;
    if ([url hasPrefix:@"http"]) {
        // network remote image, use sdwebimage solution
        [super start];
    } else {
        // local image
        UIImage *image = [UIImage imageWithContentsOfFile:self.request.URL.absoluteString];
        [self callCompletionBlocksWithImage:image imageData:image.sd_imageData error:nil finished:YES];
        [self done];
    }
}
@end
```
step 2, replace `SDWebImageDownloaderOperation`
```
[[SDWebImageManager sharedManager].imageDownloader setOperationClass:[MPImageDownloaderOperation class]];
```
finished!!

you can use sdwebimage's cache, transform, thread-manager load local images

**Comment by dreampiggy** [comment]
Actually, you don't need this.

`NSURLSession` have fully support for fileURL. Which means, you can create the URL using

```
NSURL *url = [NSURL fileURLWithPath:"/tmp/a.png"];
[SDWebImageManager.sharedManager loadImageWithURL:url completed:^{
  // blabla
}];
```

**Comment by xjbeta** [comment]
Avoid generating duplicate original-size images for local images in the disk cache path 
`SDImageCache.shared.diskCachePath`

``` swift
SDImageCache.shared.additionalCachePathBlock = { path -> String in
	if path.starts(with: "file:///") {
		return String(path.dropFirst(7))
	} else {
		return path
	}
}
```

**Comment by dreampiggy** [comment]
> Avoid generating duplicate original-size images for local images in the disk cache path `SDImageCache.shared.diskCachePath`
> 
> ```swift
> SDImageCache.shared.additionalCachePathBlock = { path -> String in
> 	if path.starts(with: "file:///") {
> 		return String(path.dropFirst(7))
> 	} else {
> 		return path
> 	}
> }
> ```

I guess this can be optimized for our default `cacheKey` logic ?
