### ISSUE TITLE
Crash when cancelAll by SDWebImageManager.

### ISSUE THREAD

**Issue by maeji** [rs/SDWebImage#809]
In tableView, I used SDWebImageManager. When I was try to cancel all download, My app was crashed at "self.cancelBlock = nil;" in SDWebImageManager.m (317 line).

I think that is released object problem.

SDWebImageCombinedOperation has cancelBlock. And It set like that,
```
operation.cancelBlock = ^{
     [subOperation cancel];
                @synchronized (self.runningOperations) {
                    [self.runningOperations removeObject:weakOperation];
                }
};
```
Also it was copied by below function in code.
```
- (void)setCancelBlock:(void (^)())cancelBlock {
    if (self.isCancelled) {
        if (cancelBlock) cancelBlock();
    }
    else {
        _cancelBlock = [cancelBlock copy];
    }
}
```
It was crashed at "self.cancelBlock = nil;" in cancel function in SDWebImageCombinedOperation. In my thought that was SDWebImageCombinedOperation was released before set nil.
```
- (void)cancel {
    self.cancelled = YES;
    if (self.cacheOperation) {
        [self.cacheOperation cancel];
        self.cacheOperation = nil;
    }
    if (self.cancelBlock) {
        self.cancelBlock();
        self.cancelBlock = nil;
    }
}
```
When I removed "self.cancleBlock = nil;". It was working perfect. Is it right?

**Comment by timkoma** [comment]
I'm using 3.7.1 and I'm still getting crash.
Why it was closed ?

**Comment by mythodeia** [comment]
@timkoma this issues is not closed
you got confused of the reference of the other issue. this is still open

**Comment by timkoma** [comment]
I think that in my case it is a concurency problem. I called [[SDWebImagePrefetcher sharedImagePrefetcher] prefetchURLs:url];
several  times  from background threads. 
I wasn't aware of the cancelAll at the beginning of the prefetchURLs. Also there is no warning in the doc that I have to call prefetchURLs from main thread. Anyway I think that prefetchURLs should work in the background  (at least it will be very nice feature).
