### ISSUE TITLE
WebP: UIImageView can't be set to opaque

### ISSUE THREAD

**Issue by RobertBiehl** [rs/SDWebImage#812]
I have a problem with webp images. They seem to always be decoded with an alpha channel, which forces the UIImageView to draw the image in a semitransparent manner, even if there are no transparent pixels in the image.
I'd like to find a way to remove the transparency and force the UIImageView to draw opaque.

It seems like there is no way to tell UIImage+WebP.m to ommit the alpha channel, is there?

Thank you

Rob

**Comment by bpoplauschi** [comment]
Closing due to lack of response.
