### ISSUE TITLE
transformation of image not saved after restore from cache

### ISSUE THREAD

**Issue by ivan-golub** [rs/SDWebImage#815]
If save transformed image (flipped) to cache:
`UIImage* flippedImage = [UIImage imageWithCGImage:sourceImage.CGImage
                                                    scale:sourceImage.scale
                                              orientation:UIImageOrientationUpMirrored];`
then it will be still flipped if get from memory, but not flipped when get from disk.

**Comment by bpoplauschi** [comment]
I think this one is now fixed by #2034
