### ISSUE TITLE
Caching of dynamic images with SDWebImageRefreshCached

### ISSUE THREAD

**Issue by knuxel** [rs/SDWebImage#821]
The option "SDWebImageRefreshCached" does not respect the cache-control header and reloads the image every time:
I'm loading dynamic images from our web server with the UIImageView+WebCache Category (options:SDWebImageRefreshCached | SDWebImageRetryFailed). The Response-Header "Cache-Control" is "private, max-age=604800", but if I download the image the second time, SDWebImage connects to the server again. This doesn't happen for static images.
Dynamic example URL: http://dev.youpickit.de/file/productimageorframeofstores?productid=118120&storeids=19312&maxHeight=200&maxWidth=200&fill=true
Static example URL: http://dev.youpickit.de/Content/images/Favourites.png

I put a sample project on github: https://github.com/knuxel/SDWebImageRefreshCached-Test

Response-Header for dynamic image:
![bildschirmfoto 2014-07-18 um 14 55 19](https://cloud.githubusercontent.com/assets/1543778/3626227/bab7f556-0e7a-11e4-97fa-d06a590a7c6f.png)

Response-Header for static image:
![bildschirmfoto 2014-07-18 um 14 55 30](https://cloud.githubusercontent.com/assets/1543778/3626231/cd1eca30-0e7a-11e4-9921-253ed3540186.png)

Thanks for your help.

**Comment by bpoplauschi** [comment]
Is anyone interested in making a Pull Request with this?

**Comment by bpoplauschi** [comment]
@knuxel I think this is actually correct. Cache-control private means "do not cache". See: https://www.w3.org/Protocols/HTTP/Issues/cache-private.html
