### ISSUE TITLE
Crash in swift, when I use self.xxxx in the completed block

### ISSUE THREAD

**Issue by ZuYuanZhou** [rs/SDWebImage#833]
```
self.imageView.sd_setImageWithURL(MYIMAGEURL
            , placeholderImage: nil
            , options: SDWebImageOptions.RetryFailed
            , progress: {(receivedSize: Int!, expectedSize: Int!) in

            }
            , completed:{(image: UIImage?, error: NSError?, cacheType: SDImageCacheType!, imageURL: NSURL?) in
                if image {
                    UIView.transitionWithView(self.imageView
                        , duration: 0.3
                        , options: UIViewAnimationOptions.AllowUserInteraction | UIViewAnimationOptions.TransitionCrossDissolve
                        , animations: {

                        }
                        , completion: {(finished) in

                        })
                }
            })
```

**Comment by forlooper** [comment]
I tried the optional binding technique suggested by @lubert , but still get the EXC_BAD_ACCESS error

```
self.manager.downloadImageWithURL(url,
			options: nil,
			progress: nil,
			completed: { [weak self] (image: UIImage!, error: NSError!, cacheType: SDImageCacheType!, finished: Bool!, imageURL: NSURL!) in
				if let wSelf = self {
					// self is TableViewController
					// previewView is Content View of a Table View Cell
					wSelf.previewView.backgroundColor = UIColor(patternImage: image)
				}
		})
```

May I know if a solution is coming along, or any other ideas? Thanks :)

**Comment by kmcgill88** [comment]
I'm seeing the same crash. Has anyone found a solution for this? I'm using Swift and Xcode 6.1.1.

**Comment by alexdd55** [comment]
this works fine for me

SDManager.downloadImageWithURL(url, options: nil, progress: {
                receivedSize, expectedSize in
					if receivedSize != expectedSize {
					
					}
                }, completed: {
                    image, error, a , c ,s in
                    if image != nil {
                        cell.imageView?.image = image
                    }
            })

**Comment by oanaandreea** [comment]
I also had the same issue mentioned by forlooper. My code still crashed even if I used weak self. The solution I came up with was to declare a global variable having the same type as my controller and assigning the "self" object to this variable. The global variable can be accessed from the completion block. I am new to mobile development so I'm not sure how global variables impact the memory, but this works for me for now.
Sample code: 
var globalSetController: SettingsViewController!
class SettingsViewController: UIViewController {
     var blurView: FXBlurView!
      override func viewDidLoad() {
            globalSetController = self
            backgroundImgView.sd_setImageWithURL(urlImage, completed: { (image: UIImage!, error: NSError!, cacheType: SDImageCacheType!, imageURL: NSURL!) -> Void in
                globalSetController.blurView.updateAsynchronously(true, completion: nil)
            })
   ...
}

**Comment by renatosc** [comment]
Same problem here with Swift. Looking at ZuYuanZhou/testSD repo (Thanks for the example) as mentioned, I noticed that the function call needs to be: 

sd_setImageWithURL()

and not

setImageWithURL()

as described in the README. Please update it, if possible.

**Comment by Voidozzer** [comment]
What worked for me was creating SDHelper in Obj-C, implementing sd_setimagewithurl there and call helper instance method from my Swift viewcontroller

**Comment by codingrogue** [comment]
Same problem here with EXC_BAD_ACCESS. Exception breakpoint halts on line 202 at `dispatch_barrier_sync(self.barrierQueue, ^{` in `SDWebImageDownloader.m`

**Comment by mythodeia** [comment]
based on comments above i am closing this
