### ISSUE TITLE
[Question] Multiple caches in a single app

### ISSUE THREAD

**Issue by shifu** [rs/SDWebImage#841]
Our app is fairly big and uses many SDKs.  Each SDK uses SDWebImage to cache images.  I wonder if there is a way to clear the SDWebImage cache for a single SDK without affecting others.

If not, could we add support for that?

**Comment by dreampiggy** [comment]
This is actually what SDK author should do. They can use `-[SDImageCache initWithNamespace:]` to specify a special name space just for their cache, but not directlly use the shared cache :)
