### ISSUE TITLE
Download/Caching of image seems to block main thread

### ISSUE THREAD

**Issue by Jasonvdm** [rs/SDWebImage#843]
Hi alll,

I currently have an app that has a tableview acting as a "feed". One of the views in each cell is a UIImageView (displaying an image that is 800x800). We are having scrolling issues as the scrollview "halts" slightly as it begins to fetch the image for the next cell, even though I am using SDWebImage (and the cache). The issue is not the number of views in each cell - when I remove all views apart from the UIImageView, the scroll issue still appears. 

I've tried using the SDWebImageManager on its on as well as just using setImageWithUrl. Both have the same result. It seems like the main thread is being blocked because the UI jumps everytime an image begins to be downloaded.

What could be causing this?? Thanks!

**Comment by bpoplauschi** [comment]
Please retry with 4.0.0. No longer using dispatch_sync and other improvements.
