### ISSUE TITLE
-downloadImageWithURL:options:progress:completed: completion block not called in some cases

### ISSUE THREAD

**Issue by rsanchezsaez** [rs/SDWebImage#847]
Not sure what's causing it, but:      

    - (id <SDWebImageOperation>)downloadImageWithURL:(NSURL *)url
                                     options:(SDWebImageOptions)options
                                    progress:(SDWebImageDownloaderProgressBlock)progressBlock
                                   completed:(SDWebImageCompletionWithFinishedBlock)completedBlock;

is sometimes not calling the completion handler. This problem surfaced when updating from *SDWebImage* 3.6 to 3.7.1, but not sure which particular code change caused to make it happen.

We are heavily using the `SDWebImagePrefetcher` in parallel to the aforementioned method.

See #781 for my initial report.

**Comment by timkoma** [comment]
@rsanchezsaez +1

**Comment by dongyu430** [comment]
+1 same problem

**Comment by bpoplauschi** [comment]
I think this should be fixed due to #883. Please retest after we release 4.0 (right now the fix is on the 4.x branch).
