### ISSUE TITLE
Is it possible to use SDWebImage in an application extension?

### ISSUE THREAD

**Issue by barfoon** [rs/SDWebImage#859]
Currently I'm getting 
> 'sharedApplication' is unavailable: not available on iOS (App Extension)

as `SDWebImageDownloaderOperation.m` contains references to `[UIApplication sharedApplication]`:
https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloaderOperation.m#L74

Is is possible to use SDWebImage with application extensions right now?

**Comment by Arthraim** [comment]
I'm compiling my project on Travis CI and facing the same issue here.
Is there a released version can help me avoid the issue?

**Comment by aelam** [comment]
AFNetworking doesn't fix the issue totally 
why don't just use this 

    #if !(defined(__has_feature) && __has_feature(attribute_availability_app_extension))
    #endif

**Comment by auibrian** [comment]
We could change it to use that as well. Looks like a good find: http://stackoverflow.com/a/29076070

**Comment by auibrian** [comment]
I haven't updated this PR with @aelam 's suggested fix because it won't build under Xcode 6.1, I don't know if that is a concern for users of SDWebImage or not. I'm happy to change to using the __has_feature macro if Xcode 6.1 is not a concern.

**Comment by RuiAAPeres** [comment]
Any update on this?

**Comment by mythodeia** [comment]
@RuiAAPeres check here https://github.com/rs/SDWebImage/issues/1082
they are waiting for an app to be approved(or not) based on the code found in that thread

**Comment by mythodeia** [comment]
closing this. everyone redirect towards https://github.com/rs/SDWebImage/issues/1082

**Comment by RuiAAPeres** [comment]
@mythodeia I have an app that has been approved without any issue.
