### ISSUE TITLE
Caching to DISK is wrong when using transformDownloadedImage delegate from downloadImageWithURL

### ISSUE THREAD

**Issue by CrazyKoala** [rs/SDWebImage#878]
Hi guys.
Facing an issue with the caching of files on the disk.

* Scenario:
- I set the delegate of the shared SDWebImagemanager so that it responds to 
(UIImage *)imageManager:(SDWebImageManager *)imageManager transformDownloadedImage:(UIImage *)image withURL:(NSURL *)imageURL

- download a picture using - (id <SDWebImageOperation>)downloadImageWithURL:(NSURL *)url
                                         options:(SDWebImageOptions)options
                                        progress:(SDWebImageDownloaderProgressBlock)progressBlock
                                       completed:(SDWebImageCompletionWithFinishedBlock)completedBlock

- When the image is downloaded successfully, it actually goes through the transformation delegate when I apply my custom modifications of the picture BEFORE it gets cached.

=> Result 

- The picture in memory is correct (i.e. present the modifications I did in the transform delegate)
- The picture in *disk* is wrong. I do a simple rounding of the picture, but the picture on disk presents a white background instead of transparent background.

How I fixed this : 

- In SDWebImagerManager.m, I changed this line

 [self.imageCache storeImage:transformedImage recalculateFromImage:imageWasTransformed imageData:data forKey:key toDisk:cacheOnDisk];

to 

 [self.imageCache storeImage:transformedImage recalculateFromImage:YES imageData:nil forKey:key toDisk:cacheOnDisk];

This way I aways recompute the image to cache from the transform image.

And with that change, BOTH disk and memory cached pictures are correct.

Now the reason why I'm posting is because, until now I was using the 3.6 release. And I thought this issue was fixed by now, but I realise it's still there in 3.7.1 release.

Also because everytime I update my PODS , it would overwrite my modifications, it would be nice if this bug was fixed on your end.

Thx a lot for the help.

Cheers.

**Comment by mythodeia** [comment]
anyone facing this issue can try [this](https://github.com/rs/SDWebImage/pull/1121)

**Comment by bpoplauschi** [comment]
Closing based on the last comments
