### ISSUE TITLE
Open Large Size Image

### ISSUE THREAD

**Issue by TalhaAkkas** [rs/SDWebImage#880]
Hello 
I noticed and solved a problem 
When we try to open large images while decoding the image for a few milliseconds  causes high memory usage and of course chrashes the app.
![screen shot 2014-08-27 at 16 53 40](https://cloud.githubusercontent.com/assets/632596/4060646/95f94350-2df1-11e4-86c9-01767ce601d6.png)
for my implementation i patched SDWebImageDecoder
i can share it if you want

**Comment by rromanchuk** [comment]
this should be closed, being tracked here https://github.com/rs/SDWebImage/issues/538

**Comment by mythodeia** [comment]
closing this. go to https://github.com/rs/SDWebImage/issues/538 instead
