### ISSUE TITLE
Can't use self on completion

### ISSUE THREAD

**Issue by Tom29** [rs/SDWebImage#905]
```
downloadimg.sd_setImageWithURL(NSURL.URLWithString("\(apifileurl)"), placeholderImage: nil, completed: {(image: UIImage?, error: NSError?, cacheType: SDImageCacheType!, imageURL: NSURL?) in
            if (image != nil) {
                 UIImageWriteToSavedPhotosAlbum(image, self, Selector("image:didFinishSavingWithError:contextInfo:"), nil)
                self.DownloadButton.alpha = 1.0
                myActivityIndicatorView.removeFromSuperview()
            }
        })
```
~> Error , i can't use self. here. So how can i access to other object?

**Comment by belgianwolfie** [comment]
same here ... anything (so not just limited to references to 'self') I put in the completion block makes the app crash. (same error as everyone else)

 let completedBlock: SDWebImageCompletionBlock! = {(image: UIImage?, error: NSError?, cacheType: SDImageCacheType!, imageURL: NSURL?) -> Void in
                //indicator.stopAnimating()// Crashing 
            }

**Comment by mythodeia** [comment]
#833 has some pointers on solving this
