### ISSUE TITLE
Console Warning on iPad  <Error>: ImageIO: CreateMetadataFromXMPBufferInternal  Threw error #203 (Duplicate property or field node) <Error>: ImageIO: CreateMetadataFromXMPBufferInternal  Threw error #203 (Duplicate property or field node)

### ISSUE THREAD

**Issue by msmobileapps** [rs/SDWebImage#943]
When running on my iOS7 iPad I get this error and an exception break point stops in line 51 of  UIImage+MultiFormat.m

**Comment by richardreyes** [comment]
May I ask for an update on this?

**Comment by msmobileapps** [comment]
Sent from Acompli




On Wed, Jan 28, 2015 at 7:54 PM -0800, "Richard Reyes" <notifications@github.com> wrote:












May I ask for an update on this?

**Comment by msmobileapps** [comment]
Not solved as far as I know 

Sent from Acompli




On Wed, Jan 28, 2015 at 7:54 PM -0800, "Richard Reyes" <notifications@github.com> wrote:












May I ask for an update on this?

**Comment by jlmendezbonini** [comment]
@mythodeia Are you still looking for an image that triggers that exception and console message?  

Here you go: https://letote-staging-product-images.s3.amazonaws.com/uploads/banner_photo/45/banner_layerup_banner.jpg

**Comment by mythodeia** [comment]
@jlmendezbonini thanks for the image. i did a quick test and the warning appears when this fires:
```CFDictionaryRef properties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, NULL);```
i cannot guess what Apple might be doing under the hood but its whats causing the issue. Since its a warning and not a crash i think you are ok. 
I will close this as this is not something SDWebImage is responsible for or able to fix any other way.

**Comment by fmaylinch** [comment]
Maybe some interesting info here:

http://stackoverflow.com/questions/21933837/imageio-createmetadatafromxmpbufferinternal-threw-error

**Comment by mythodeia** [comment]
@fmaylinch thanks for the link 

The exif is what's causing the issue.since it's a warning you do not need to worry about it.

**Comment by fmaylinch** [comment]
Thanks @mythodeia, it's good to know!

Maybe a "try/catch" would avoid the stopping in the iOS simulator? Just in case you want to consider that. Thanks anyway!
