### ISSUE TITLE
Drop our GIF support and integrate a 3rd party solution

### ISSUE THREAD

**Issue by bpoplauschi** [rs/SDWebImage#945]
Hi @rs, @mythodeia ,

I think you both know our GIF support is pretty sucky (consumes a lot of memory #548 #538 and also blocks the main thread #933, doesn't work on disk retrieval #916). I've tried a few approaches, but none seems to fix it.

In #733 someone suggested we look at [FLAnimatedImage](https://github.com/Flipboard/FLAnimatedImage) a library developed by Flipboard. I also found [YLGIFImage](https://github.com/liyong03/YLGIFImage).

Now given those 2 libraries know their way with GIFs (low CPU and memory footprint), since they are already focused on GIF, making patches and maintaining their code, I strongly suggest we remove our GIF code and create a subspec that supports integration with one of them. Basically via CocoaPods, we will be referencing one of those 2 libraries.

Let me know if you agree with me so far.

Now deciding which one:
- both work very well on the simulator, I still need to test on a few devices
- FLAnimatedImage has the advantage of being maintained by a team which handles working with images a lot (Flipboard), releases often (yesterday was their last release). The big disadvantage is `FLAnimatedImage` is not an `UIImage` subclass, but a `NSObject` subclass, which could make it harder for us to integrate.
- YLGIFImage is built by Yong Li, developer at Facebook, so he must also have a good experience with images. The lib was not updated in the past 6 months. The advantage is their `YLGIFImage` is a `UIImage` subclass.

If you agree with this, I can play with an integration. I think it's our best option.

**Comment by zhw511006** [comment]
When we will integrate a 3rd party solution for Gif? Thx!

**Comment by WangHengHeng** [comment]
I modified the methods in file "UIImage+GIF" to return a "YLGIFImage", and modified the method in file"SDWebImageCompat" to do nothing with 'gif' data.

It looks work well.

**Comment by mythodeia** [comment]
@bpoplauschi FLAnimatedImage has an active UIImage subclass branch...
[check it out](https://github.com/Flipboard/FLAnimatedImage/tree/uiimage-subclass)

**Comment by bpoplauschi** [comment]
Thanks @mythodeia, I will look at this again.

**Comment by maha-ghonam** [comment]
@bpoplauschi  i have the same problem here .. did you reach a solution?

**Comment by bpoplauschi** [comment]
No solution yet, I will look at the new FLAnimatedImage variant and take it from there.

**Comment by peterpaulis** [comment]
Any progress on this?

**Comment by peterpaulis** [comment]
the solution for https://github.com/liyong03/SDWebImage-YLGIFImage no longer works for current sdwebimage

**Comment by neil-wu** [comment]
I modify some SDWebImage's source code. And work with FLAnimatedImage very well.
[Here is a demo project](https://github.com/neil-wu/SDImageCacheWithGifDemo)

**Comment by yuvalDeri** [comment]
I don't know if this is known but Brewer Herb gives a nice solution of using FLAnimatedImage with SDWebImage using swizzlling
https://gist.github.com/exherb/1257263e350831d6c205

**Comment by hjanuschka** [comment]
@yuvalDeri  thx for the hint?! - but it actually does not animate the gif, it is loaded but does not run.
any idea how to start the animation?

using the following original sd method to load the image from web

    sd_setImageWithURL:placeholderImage:options:SDWebImageCacheMemoryOnly completed:

**Comment by yuvalDeri** [comment]
@hjanuschka
I simply added those 2 files to my project and added a load method under the implementation part like this
@implementation SDImageCache (Swizzle)

+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [self swizzle];
    });
}
 .....
@end

make sure you are calling 
sd_setImageWithURL:placeholderImage:options: completed:
on a FLAnimatedImageView object and not an UIImageView.

It works for me, even the completion block holds a FLAnimatedImage instead of an UIImage when GIFs are involved.
good luck

**Comment by hjanuschka** [comment]
@yuvalDeri - MANY THX - changing the type from uiimageview to flanimatedimageview did the trick, also nice with the +load() thx - someone should do a POD of this

**Comment by hilen** [comment]
Take a look at this -> https://gist.github.com/hilen/8ef4a810406051e8f0c1

**Comment by bpoplauschi** [comment]
By merging #1575 into the 4.x branch, I think we can close this thicket. Feel free to test it and let us know if it works.
