### ISSUE TITLE
Images were not downloading for static URL's

### ISSUE THREAD

**Issue by sourcebits-mahesh** [rs/SDWebImage#951]
Hi,

   In my app,User having profile page with photo and the user details, here with using SDWebImage framework ,download and cache the image its working perfectly.The user has an option to change profile photo, when user changes the pic, I was posting the updated image to server .When the user come back to the profile page ,the framework not downloading the updated image showing the previous image.The issue was back end people providing the static Url's but with updated content ,so I used SDWebImageRefreshCached, for refresh but no use.Please can you sort of this issue?.Thank you very much.

**Comment by mythodeia** [comment]
@GabrielCartier any updates on this? does this still happen on your side?

**Comment by GabrielCartier** [comment]
Haven't got the chance to check it and the project has changed since then. I'll see if I can validate that it works with an updated version.

Anyhow, thanks!

**Comment by rokridi** [comment]
@mythodeia i am facing the same exact problem as @GabrielCartier

**Comment by mythodeia** [comment]
@rokridi are you using the ```SDWebImageRefreshCached``` option?

**Comment by rokridi** [comment]
@mythodeia yes i am using SDWebImageRefreshCached option.

**Comment by mythodeia** [comment]
@rokridi 
i used the demo project. removed all example files and added 1 image i uploaded to my server.
on the ```detailsviewcontroller``` i added the refreshcached property like this
```[self.imageView sd_setImageWithURL:self.imageURL
                          placeholderImage:nil
                                   options:SDWebImageProgressiveDownload|SDWebImageRefreshCached.....```
opened the simulator and run the project. tapped the 1st cell to see the details view.
then i uploaded a new image with the same name as the previous one and replaced the old one online.
then i hit back on the nav bar and again tapped on the 1st cell. The new image loaded successfully.

**Comment by rokridi** [comment]
@mythodeia i have checked again and it is working now. Sometimes, the image (with static url) is not refreshed even when using SDWebImageRefreshCached. The cache returns the cached image and then  i wait for the download of the new image but i get the old one (may be its is related to backend). I will investigate till i recognize the exact scenario to reproduce this systematically. Thanks for help.

**Comment by andreaslindahl** [comment]
I'm also having this problem. I'm using SDWebImageRefreshCached but I'm not getting the updated image from the server.

**Comment by andreaslindahl** [comment]
is it possible to remove the SDWebImageDownloaderUseNSURLCache option without changing something in SDWebImage? I'm using cocoapods and do not want to make changes to any of the code in the pods.

Also, is there a reason mythodeia's fix hasn't been included? Surely, that how it should be if you use SDWebImageRefreshCached?

**Comment by bpoplauschi** [comment]
@andreaslindahl you can set 0 as options or another value, instead of the UseNSURLCache one.

**Comment by bpoplauschi** [comment]
Closed, based on the comment from @mythodeia

**Comment by HannuL** [comment]
In some cases images are stored to "NSURLCache sharedCache" and it causes problems. To empy it  -> call [[NSURLCache sharedURLCache] removeAllCachedResponses]

**Comment by nitishmakhija** [comment]
@mythodeia i had the same issue and adding this ` if (image && options & SDWebImageRefreshCached) {
                // force progressive off if image already cached but forced refreshing
                downloaderOptions &= ~SDWebImageDownloaderProgressiveDownload;
                // remove SDWebImageDownloaderUseNSURLCache flag
                downloaderOptions &= ~SDWebImageDownloaderUseNSURLCache;
                // ignore image read from NSURLCache if image is cached but force refreshing
                downloaderOptions |= SDWebImageDownloaderIgnoreCachedResponse;
            }`

didn't do any trick can you help me out please

**Comment by mythodeia** [comment]
@nitishmakhija can you replicate it in the demo project?

**Comment by nitishmakhija** [comment]
@mythodeia sure
`[self.profilePictureButton sd_setBackgroundImageWithURL:[NSURL URLWithString:imagePath] forState:UIControlStateNormal placeholderImage:[UIImage imageWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"placeholder" ofType:@"png"]] options:SDWebImageRefreshCached];`

i am doing something like this in my controller

**Comment by standers67** [comment]
I see the same issues as mentioned by others:
Even if specifying SDWebImageRefreshCached, the images are not refreshed even when they have been updated on the backend servers. There are no requests sent to the server to check if the images have actually been updated or not. This was the behaviour in previously projects where we also have used SDWebImage if I remember it correctly.

Previously in this thread, there are suggestions to add a line of code to the method downloadImageWithURL:options:progress:completed.

`//remove SDWebImageDownloaderUseNSURLCache flag`
`downloaderOptions &= ~SDWebImageDownloaderUseNSURLCache;`

This seems to cause the images to be refreshed from the server backend, without checking if they have actually been updated or not.

Could it be changes to iOS that cause these problems when it comes to refreshing images based on the date they were updated in the backend?

**Comment by danielbenedykt** [comment]
this is still happening to me
