### ISSUE TITLE
Speed is low for showing gif.

### ISSUE THREAD

**Issue by zhw511006** [rs/SDWebImage#964]
I download a gif and show it , the speed is really low, gif is about 2mb. I test this on iPhone6.

It's normal, or can be improved? Thx!

**Comment by ymsheng** [comment]
In UIImage+GIF.m file, if the gif image each duration not the same(like:0.1s,0.1s,0.1s,2s).when play the image with same duration will show slow. so i add this code:

+ (UIImage *)sd_animatedGIFWithData:(NSData *)data {
    if (!data) {
        return nil;
    }

    CGImageSourceRef source = CGImageSourceCreateWithData((__bridge CFDataRef)data, NULL);

    size_t count = CGImageSourceGetCount(source);

    UIImage *animatedImage;

    if (count <= 1) {
        animatedImage = [[UIImage alloc] initWithData:data];
    }
    else {
        NSMutableArray *images = [NSMutableArray array];

        NSTimeInterval duration = 0.0f;

        for (size_t i = 0; i < count; i++) {
            CGImageRef image = CGImageSourceCreateImageAtIndex(source, i, NULL);
            float eachDuration = [self sd_frameDurationAtIndex:i source:source];
            duration += eachDuration;
            if (eachDuration>0.1) { //if duration larger than 0.1; repeat input this duration image
                int repeatCount = eachDuration/0.1;
                for (int k=0; k<repeatCount; k++) {
                    [images addObject:[UIImage imageWithCGImage:image scale:[UIScreen mainScreen].scale orientation:UIImageOrientationUp]];
                }
            }
            else{
               [images addObject:[UIImage imageWithCGImage:image scale:[UIScreen mainScreen].scale orientation:UIImageOrientationUp]];
            }

            CGImageRelease(image);
        }

        if (!duration) {
            duration = (1.0f / 10.0f) * count;
        }

        animatedImage = [UIImage animatedImageWithImages:images duration:duration];
    }

    CFRelease(source);

    return animatedImage;
}

**Comment by bpoplauschi** [comment]
@zhw511006  We have replaced our GIF component with a library from Flipboard (FLAnimatedImage). Could you try our 4.x branch ([instructions](https://github.com/rs/SDWebImage/tree/4.x#animated-images-gif-support)) and see if it helps?

**Comment by bpoplauschi** [comment]
Closing. The FLAnimatedImage solution replacing our own GIF is integrated into the 4.x branch.
