### ISSUE TITLE
Consider using NSProgress instead of progress blocks (requires iOS7)

### ISSUE THREAD

**Issue by joeljfischer** [rs/SDWebImage#970]
[NSProgress API](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSProgress_Class/index.html#//apple_ref/occ/cl/NSProgress)

I know it's iOS 7+ only, so that might be a dealbreaker, but the API is quite nice. The canceling api would be significantly better than using an NSOperation returned from a method. 

An alternate idea for cancelation that doesn't require iOS7+ is to use a `BOOL *` in the progress block. When the user sets that to YES, the download stops. Exactly like how [NSArray enumerateObjectsUsingBlock: works](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSArray_Class/index.html#//apple_ref/occ/instm/NSArray/enumerateObjectsUsingBlock:) does it

**Comment by skyline75489** [comment]
I think this would be nice in 5.0 release. I'll take a look at it. @bpoplauschi @dreampiggy

**Comment by dreampiggy** [comment]
NSProgress API is supported by #2172. This will be available in 4.3.0 version :)
