### ISSUE TITLE
transform Image larger than original downloadImage

### ISSUE THREAD

**Issue by XiangqiTu** [rs/SDWebImage#972]
a question about transformImage,it is  larger than the resource downloaded from server.

for example, an image data is 200KB,but when use SDWebImage,the imageView.image, size become 1.3MB

<pre><code>- (UIImage *)diskImageForKey:(NSString *)key {
    NSData *data = [self diskImageDataBySearchingAllPathsForKey:key]; //here is 200KB
    if (data) {
        UIImage *image = [UIImage sd_imageWithData:data];
        image = [self scaledImageForKey:key image:image];
        image = [UIImage decodedImageWithImage:image];
        return image; //here is 1.3MB
    }
    else {
        return nil;
    }
}
</code></pre>

it makes my app become slowly... is there a solution to solve the question about performance？

**Comment by bpoplauschi** [comment]
It's normal for the decodedImage to take up more memory. Because it's decompressed by force. You should look at the original image after being rendered on screen. They should have the same size.
