### ISSUE TITLE
Getting crash with Report : *** -[CALayer needsDisplayOnBoundsChange]: message sent to deallocated instance 0x160f4c60

### ISSUE THREAD

**Issue by hareshagile** [rs/SDWebImage#975]
Getting the crash when my ImageView is out of memory and it still exicutes the success block in ARC.

The funtion that crashes is 
- (void)sd_setImageWithURL:(NSURL *)url placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options progress:(SDWebImageDownloaderProgressBlock)progressBlock completed:(SDWebImageCompletionBlock)completedBlock
 
in Completeion block my imageview is out of memory but it still executes the completion block to set image

**Comment by bpoplauschi** [comment]
Could you help us reproduce this issue? Maybe create a demo project where it repros constantly.
