### ISSUE TITLE
custom diskCachePath

### ISSUE THREAD

**Issue by ghazel** [rs/SDWebImage#977]
To support iOS extensions, images need to be written to a different directory than `NSCachesDirectory`. As a user of SDWebImage, it would be nice to be able to set the `diskCachePath` directly (bonus points for using `NSURL`, too, instead of `NSString`).

`addReadOnlyCachePath` is not sufficient, since it's read-only.

**Comment by luna-moonfang** [comment]
That would be nicer!
I'm using it to download and cache images for a html. So it has to place the images to the relative position of the js file. So the js code could find the images easily.

**Comment by nicolasmuller** [comment]
That would be nicer!
+ 1

**Comment by mythodeia** [comment]
something like that? https://github.com/rs/SDWebImage/issues/977
a bit old though

**Comment by bpoplauschi** [comment]
Implemented with #1041
