### ISSUE TITLE
crash in NSData+ImageContentType sd_contentTypeForImageData

### ISSUE THREAD

**Issue by vickieduong** [rs/SDWebImage#978]
Thread : Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                                                                                  0x2891e5f7 __exceptionPreprocess + 126
1  libobjc.A.dylib                                                                                 0x364a8c77 objc_exception_throw + 38
2  CoreFoundation                                                                                  0x28923abd __methodDescriptionForSelector
3  CoreFoundation                                                                                  0x28921999 ___forwarding___ + 712
4  CoreFoundation                                                                                  0x28852b88 _CF_forwarding_prep_0 + 24
5  Shopping by HeartThis - Shop for Apparel, Fashion Products, and Coupons from Designer Stores    0x000f2fe9 +[NSData(ImageContentType) sd_contentTypeForImageData:] (NSData+ImageContentType.m:13)
6  Shopping by HeartThis - Shop for Apparel, Fashion Products, and Coupons from Designer Stores    0x001dfc2b +[UIImage(MultiFormat) sd_imageWithData:] (UIImage+MultiFormat.m:22)
7  Shopping by HeartThis - Shop for Apparel, Fashion Products, and Coupons from Designer Stores    0x0014db3f -[SDWebImageDownloaderOperation connectionDidFinishLoading:] (SDWebImageDownloaderOperation.m:347)
8  CFNetwork                                                                                       0x28476eed __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 56
9  CFNetwork                                                                                       0x28476ea7 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 182
10 CFNetwork                                                                                       0x28476f99 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 36
11 CFNetwork                                                                                       0x2838beef ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 78
12 CFNetwork                                                                                       0x2842876d ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 60
13 CFNetwork                                                                                       0x2837cd71 RunloopBlockContext::_invoke_block(void const*, void*) + 60
14 CoreFoundation                                                                                  0x2882f5a1 CFArrayApplyFunction + 36
15 CFNetwork                                                                                       0x2837cc2b RunloopBlockContext::perform() + 182
16 CFNetwork                                                                                       0x2837caf1 MultiplexerSource::perform() + 216
17 CFNetwork                                                                                       0x2837c98d MultiplexerSource::_perform(void*) + 48
18 CoreFoundation                                                                                  0x288e4fd7 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
19 CoreFoundation                                                                                  0x288e43eb __CFRunLoopDoSources0 + 222
20 CoreFoundation                                                                                  0x288e2a69 __CFRunLoopRun + 768
21 CoreFoundation                                                                                  0x2882fb31 CFRunLoopRunSpecific + 476
22 CoreFoundation                                                                                  0x288794fb CFRunLoopRun + 98
23 Shopping by HeartThis - Shop for Apparel, Fashion Products, and Coupons from Designer Stores    0x0014c7bb -[SDWebImageDownloaderOperation start] (SDWebImageDownloaderOperation.m:107)
24 Foundation                                                                                      0x2961ea57 __NSOQSchedule_f + 186
25 libdispatch.dylib                                                                               0x36a135d9 _dispatch_queue_drain$VARIANT$mp + 948
26 libdispatch.dylib                                                                               0x36a130a9 _dispatch_queue_invoke$VARIANT$mp + 84
27 libdispatch.dylib                                                                               0x36a150d3 _dispatch_root_queue_drain + 330
28 libdispatch.dylib                                                                               0x36a161fb _dispatch_worker_thread3 + 106
29 libsystem_pthread.dylib                                                                         0x36b86e25 _pthread_wqthread + 668
30 libsystem_pthread.dylib                                                                         0x36b86b78 start_wqthread + 8

**Comment by siddharthsingh1122** [comment]
*** -[NSPathStore2 length]: message sent to deallocated instance 0x7b6a8260
Getting this error

**Comment by vickieduong** [comment]
no, not reproducible all the time (with all our images), though we have had 6 crashes for 6 different users at this exact line of code

**Comment by shreeshecommstreet** [comment]
I am getting this issue at all time.

**Comment by bpoplauschi** [comment]
Let's close this issue, see if it happens again with 4.0.0 (4.0.0-beta is available for download, 4.0.0 official release is on its way).
