### ISSUE TITLE
Cant use SDWebImage in my own staticFramework

### ISSUE THREAD

**Issue by evrenios** [rs/SDWebImage#980]
I successfully created the static framework (.a) without any error or exception but when i try to use it in my project i' m getting
 Undefined symbols for architecture i386: "_OBJC_CLASS_$_SDWebImageManager" it doesnt matter simulator or device i m getting architecture error.

I added the SDWebImage folder and added #import "UIImageView+WebCache.h" and it works without a problem inside of the source,

Any idea or suggestions?

**Comment by mythodeia** [comment]
closing this. please reopen if you need more info
